### DISCUSSION TITLE
各位大佬有没有办法实现这样的功能，对于一个域名，人在不同的地方，不同的网络环境，走不同的ip，以及不同的网卡（zerotier）

### DISCUSSION THREAD

**Discussion by FlyInWind1** [MetaCubeX/mihomo#1008] [General]
我视乎将clash用在了它设计初衷以外的地方。这个想法，最终也不一定要用clash实现，当然如果可以省去我装一个新软件那当然是最好的。

我最终希望实现的效果是
我在家里，ip用192.168.31.x，（这个我在我家的路由器hosts里面设置了）
人在外面，如果有ipv6，走ipv6，ip是xx:xx:...
ipv6不可用，走zerotier，ip是172.30.xx.xx
最后，zerotier也走不了，走内网穿透，ip是一个的外xx.xx.xx.xx。

这个想法，我在折腾了几天后已经有了一个初步的效果，不过有一些小问题我并不满意。这是部分的配置文件
```yaml
dns:
   nameserver-policy:
      +.xxx.com:
          - 192.168.31.1 #家里路由器ip
          - 172.30.31.1#ZeroTier One [xxxx] #zerotier dns
          - 8.8.8.8 #解析外网ip
    fake-ip-filter:
       - +.xxx.com
proxy-groups:
    -   name: DirectOrZerotier
        type: fallback
        # type: url-test
        proxies:
            - DIRECT
            - ZerotierWindows
        url: https://nextcloud.xxx.com
proxies:
    -   name: ZerotierWindows
        type: direct
        interface-name: ZeroTier One [xxxx]
        udp: true
```
我不满意的地方在于，proxy-groups 中测试延迟，由于 zerotier dns 可能不稳定，然后走8.8.8.8返回了外网ipv4地址，用这个ip测试 zerotier 的延迟是一定会error的。
我的想法，是否可以每一个 proxies 都独自维护一个 dns 缓存，然后测试延迟时，使用自己独立的dns缓存。如果我这想法实现不了，有其它方案也可以
