### DISCUSSION TITLE
关于fakeip，如果不在路由器（网关）上用，是不是不需要设置

### DISCUSSION THREAD

**Discussion by toyo2333** [MetaCubeX/mihomo#1033] [Q&A]
傻瓜配置里这一段
```
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
``` 

我目前配置文件里没有这一段。
我看了一些文章，似乎这个是用在透明网关上的。我就是想确认下，如果我只是pc、mac、移动设备上用，有必要设置么？带来的好处是什么呢？

请解惑！谢谢
