### DISCUSSION TITLE
ubuntu中使用tun作为旁路由时本机可以上网其他机器无法上网

### DISCUSSION THREAD

**Discussion by UntaggedRui** [MetaCubeX/mihomo#1042] [Q&A] [answered]
核心配置如下。
```yml
tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:1053'
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
  nameserver:
    - 223.5.5.5
  fallback:
    - 8.8.8.8
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```
本机使用是正常的
<img width="1771" alt="image" src="https://github.com/MetaCubeX/mihomo/assets/28807947/b9e2082b-5e5a-49d0-bc71-787fdd9cdc65">
原本的iptables规则如下，没有为mihomo设置过特别的规则。曾经为zerotier设置了两条iptables规则。
```bash
sudo iptables -t nat -A POSTROUTING -o $PHY_IFACE -j MASQUERADE
sudo iptables -A FORWARD -i $PHY_IFACE -o $ZT_IFACE -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i $ZT_IFACE -o $PHY_IFACE -j ACCEPT
```
机器上运行了很多docker容器。
<img width="955" alt="image" src="https://github.com/MetaCubeX/mihomo/assets/28807947/f90c9209-ddc1-4bab-a5a2-e4ec0191f776">
局域网内其他机器的配置如下
```yml
ethernets:
    eno12399np0:
      dhcp4: false
      dhcp6: false
      addresses:
              - 10.176.22.221/24
      nameservers:
              addresses:
                      - 223.5.5.5
      routes:
              - to: 0.0.0.0/0
                via: 10.176.22.207
                metric: 50
```
其中`10.176.22.207`为运行了mihomo tun的设备的局域网ip。
该机器无法访问任何网络
```bash
$ traceroute 114.114.114.114
traceroute to 114.114.114.114 (114.114.114.114), 64 hops max
  1   10.176.22.207  0.315ms  0.228ms  0.227ms
  2   *  *  *
  3   *  *  *
```
可能的原因是出现在哪里？
