### DISCUSSION TITLE
dns似乎只监听了udp

### DISCUSSION THREAD

**Discussion by idpj** [MetaCubeX/mihomo#1086] [General]
dns配置后发现只监听了1053端口的udp，但是iptables连带tcp也一并转发了。
```yaml
dns:
  enable: true
  ipv6: true
  use-hosts: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:1053
  nameserver: [tcp://192.168.123.153:20153]
  proxy-server-nameserver: [tcp://192.168.123.153:20153]
  nameserver-policy:
    "geosite:private": [192.168.123.1]
    "geosite:cn": [tcp://192.168.123.153:20053]
```
```bash
mihomo ~# lsof -i:1053
COMMAND   PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
mihomo  31065 root    9u  IPv6 224967464      0t0  UDP *:1053
```
```bash
REDIRECT   udp  --  anywhere             anywhere             redir ports 1053
REDIRECT   tcp  --  anywhere             anywhere             redir ports 1053
```
