### DISCUSSION TITLE
关于 DNS 性能的疑问 / Questions about DNS performance

### DISCUSSION THREAD

**Discussion by trantuan-20048607** [MetaCubeX/mihomo#1189] [General]
## 问题描述
由于我使用的节点 UDP 性能较差，且有 DNS 防泄漏需求，故在 DNS 配置中进行了详细的分流。针对需要出墙的 DNS 请求，我暂时使用 TCP 协议查询。
[mosdns 文档](https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns-v5/ru-he-pei-zhi-mosdns/ke-zhi-hang-cha-jian#forward)中提到了可以对 TCP、DoT 方法查询 DNS 进行连接复用优化（RFC 7766），请问 clash 内核是否实现了这些优化？实现此功能可以大幅降低连接数，避免因连接数过多被机场封禁。

## 相关配置
这是当前使用的 DNS 解析策略（使用 ACL4SSR 策略组、OpenClash 自动生成）：
```yaml
dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - "tls://dns.alidns.com#\U0001F3AF 全球直连"
  - "tls://dot.pub#\U0001F3AF 全球直连"
  fallback:
  - "tcp://dns.google#\U0001F680 节点选择"
  - "tcp://one.one.one.one#\U0001F680 节点选择"
  default-nameserver:
  - 223.5.5.5
  - 119.28.28.28
  - 223.6.6.6
  - 119.29.29.29
  proxy-server-nameserver:
  - 223.5.5.5
  - 119.28.28.28
  - 223.6.6.6
  - 119.29.29.29
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
  nameserver-policy:
    rule-set:LocalAreaNetwork:
    - "tls://dns.alidns.com#\U0001F3AF 全球直连"
    - "tls://dot.pub#\U0001F3AF 全球直连"
    rule-set:UnBan:
    - "tls://dns.alidns.com#\U0001F3AF 全球直连"
    - "tls://dot.pub#\U0001F3AF 全球直连"
    rule-set:GoogleFCM:
    - "tcp://dns.google#\U0001F4E2 谷歌推送"
    - "tcp://one.one.one.one#\U0001F4E2 谷歌推送"
    rule-set:GoogleCN:
    - "tls://dns.alidns.com#\U0001F3AF 全球直连"
    - "tls://dot.pub#\U0001F3AF 全球直连"
    rule-set:SteamCN:
    - "tls://dns.alidns.com#\U0001F3AF 全球直连"
    - "tls://dot.pub#\U0001F3AF 全球直连"
    rule-set:OneDrive:
    - tcp://dns.google#Ⓜ️ 微软云盘
    - tcp://one.one.one.one#Ⓜ️ 微软云盘
    rule-set:Microsoft:
    - tls://dns.alidns.com#Ⓜ️ 微软服务
    - tls://dot.pub#Ⓜ️ 微软服务
    rule-set:Apple:
    - "tls://dns.alidns.com#\U0001F34E 苹果服务"
    - "tls://dot.pub#\U0001F34E 苹果服务"
    rule-set:Telegram:
    - "tcp://dns.google#\U0001F4F2 电报消息"
    - "tcp://one.one.one.one#\U0001F4F2 电报消息"
    rule-set:OpenAi:
    - "tcp://dns.google#\U0001F4AC OpenAi"
    - "tcp://one.one.one.one#\U0001F4AC OpenAi"
    rule-set:NetEaseMusic:
    - "tls://dns.alidns.com#\U0001F3B6 网易音乐"
    - "tls://dot.pub#\U0001F3B6 网易音乐"
    rule-set:Epic:
    - "tls://dns.alidns.com#\U0001F3AE 游戏平台"
    - "tls://dot.pub#\U0001F3AE 游戏平台"
    rule-set:Origin:
    - "tls://dns.alidns.com#\U0001F3AE 游戏平台"
    - "tls://dot.pub#\U0001F3AE 游戏平台"
    rule-set:Sony:
    - "tls://dns.alidns.com#\U0001F3AE 游戏平台"
    - "tls://dot.pub#\U0001F3AE 游戏平台"
    rule-set:Steam:
    - "tls://dns.alidns.com#\U0001F3AE 游戏平台"
    - "tls://dot.pub#\U0001F3AE 游戏平台"
    rule-set:Nintendo:
    - "tls://dns.alidns.com#\U0001F3AE 游戏平台"
    - "tls://dot.pub#\U0001F3AE 游戏平台"
    rule-set:Xbox:
    - "tls://dns.alidns.com#\U0001F3AE 游戏平台"
    - "tls://dot.pub#\U0001F3AE 游戏平台"
    rule-set:YouTube:
    - "tcp://dns.google#\U0001F4F9 油管视频"
    - "tcp://one.one.one.one#\U0001F4F9 油管视频"
    rule-set:Netflix:
    - "tcp://dns.google#\U0001F3A5 奈飞视频"
    - "tcp://one.one.one.one#\U0001F3A5 奈飞视频"
    rule-set:Bahamut:
    - "tcp://dns.google#\U0001F4FA 巴哈姆特"
    - "tcp://one.one.one.one#\U0001F4FA 巴哈姆特"
    rule-set:Bilibili:
    - "tls://dns.alidns.com#\U0001F4FA 哔哩哔哩"
    - "tls://dot.pub#\U0001F4FA 哔哩哔哩"
    rule-set:BilibiliHMT:
    - "tls://dns.alidns.com#\U0001F4FA 哔哩哔哩"
    - "tls://dot.pub#\U0001F4FA 哔哩哔哩"
    rule-set:ChinaMedia:
    - "tls://dns.alidns.com#\U0001F30F 国内媒体"
    - "tls://dot.pub#\U0001F30F 国内媒体"
    rule-set:ProxyMedia:
    - "tcp://dns.google#\U0001F30D 国外媒体"
    - "tcp://one.one.one.one#\U0001F30D 国外媒体"
    rule-set:Adobe:
    - "tcp://dns.google#\U0001F680 节点选择"
    - "tcp://one.one.one.one#\U0001F680 节点选择"
    rule-set:Scholar:
    - "tcp://dns.google#\U0001F680 节点选择"
    - "tcp://one.one.one.one#\U0001F680 节点选择"
    rule-set:ProxyGFWlist:
    - "tcp://dns.google#\U0001F680 节点选择"
    - "tcp://one.one.one.one#\U0001F680 节点选择"
    rule-set:ChinaDomain:
    - "tls://dns.alidns.com#\U0001F3AF 全球直连"
    - "tls://dot.pub#\U0001F3AF 全球直连"
```
