### DISCUSSION TITLE
在 Orange PI 5 Plus Debian 12 启用 TUN 报错

### DISCUSSION THREAD

**Discussion by xiwangly2** [MetaCubeX/mihomo#1248] [Q&A]
我尝试在 香橙派 5 Plus 安装 mihomo

我的操作系统是从香橙派官网下载的，安装镜像名为 `Orangepi5plus_1.0.8_debian_bookworm_server_linux6.1.43.img`

我使用无线网卡作为 WAN，网卡型号是 RTL8852BE （我在之前也尝试过使用有线网络，结果也是一样的问题）

我使用`dpkg -i mihomo-linux-arm64-v1.18.4.deb`命令安装的，这个文件我使用 SFTP 上传的，文件完整性没有问题

我将 metacubexd 的 dist 正确解压到了 `/etc/mihomo/metacubexd/`

我在`/etc/mihomo/config.yaml`进行了如下配置：

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
mixed-port: 10809
inbound-tfo: true
mode: rule
ipv6: true
log-level: debug
find-process-mode: always
allow-lan: true
geodata-mode: true
tcp-concurrent: true
external-controller: :9090
secret: "my secret"

external-ui: metacubexd

interface-name: wlP2p33s0

tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-detect-interface: false
  strict-route: true 

dns:
  enable: true
  enhanced-mode: fake-ip
  use-hosts: true
  nameserver-policy:
    'geosite:cn': 
         - 223.5.5.5
    'geosite:private': 
         - 223.5.5.5
  proxy-server-nameserver:
     - 223.5.5.5  
  fake-ip-filter:
    #LAN
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'

profile:
  store-selected: false
  store-fake-ip: false

proxies:
  -
    这里省略我的个人配置
```

我使用`systemctl start mihomo`运行

当我每次点击 metacubexd 的 TUN 开关时得到了这个报错（开关在点击开启后立即还原到了关闭状态）：
```bash
ERRO[2024-05-06T19:21:52.768503418+08:00] Start TUN listening error: configure tun interface: cleanup rules: operation not supported
```
我使用这些命令看了一下：
```bash
root@orangepi5plus:~# uname -a
Linux orangepi5plus 6.1.43-rockchip-rk3588 #1.0.8 SMP Sat Feb  3 00:04:38 CST 2024 aarch64 GNU/Linux

root@orangepi5plus:~# ip rule
RTNETLINK answers: Operation not supported
Dump terminated

root@orangepi5plus:~# lsmod
Module                  Size  Used by
tun                    57344  0
xt_nat                 16384  32
veth                   32768  0
xt_conntrack           16384  2
nft_chain_nat          16384  15
xt_MASQUERADE          20480  10
nf_nat                 40960  3 xt_nat,nft_chain_nat,xt_MASQUERADE
nf_conntrack_netlink    45056  0
nf_conntrack          126976  5 xt_conntrack,nf_nat,xt_nat,nf_conntrack_netlink,xt_MASQUERADE
nf_defrag_ipv6         24576  1 nf_conntrack
nf_defrag_ipv4         16384  1 nf_conntrack
xt_addrtype            16384  2
nft_compat             20480  46
nf_tables             208896  536 nft_compat,nft_chain_nat
nfnetlink              20480  4 nft_compat,nf_conntrack_netlink,nf_tables
br_netfilter           28672  0
bridge                266240  1 br_netfilter
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
overlay               126976  8
bnep                   28672  2
btusb                  65536  0
btrtl                  24576  1 btusb
btbcm                  24576  1 btusb
btmtk                  16384  1 btusb
btintel                40960  1 btusb
bluetooth             733184  29 btrtl,btmtk,btintel,btbcm,bnep,btusb
pwm_fan                24576  0
rtw88_8821ce           16384  0
rtw88_8821c            86016  1 rtw88_8821ce
rtw88_pci              32768  1 rtw88_8821ce
rtw88_core            147456  2 rtw88_pci,rtw88_8821c
fuse                  126976  1
ip_tables              32768  0
r8169                  86016  0

root@orangepi5plus:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute
       valid_lft forever preferred_lft forever
2: enP4p65s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether c0:74:2b:fe:4a:e1 brd ff:ff:ff:ff:ff:ff
3: enP3p49s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether c0:74:2b:fe:4a:e0 brd ff:ff:ff:ff:ff:ff
4: wlP2p33s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 28:39:26:37:89:bd brd ff:ff:ff:ff:ff:ff
    inet 192.168.204.188/24 brd 192.168.204.255 scope global noprefixroute wlP2p33s0
       valid_lft forever preferred_lft forever
    inet 192.168.204.39/24 brd 192.168.204.255 scope global secondary dynamic noprefixroute wlP2p33s0
       valid_lft 47799sec preferred_lft 47799sec
    inet6 fe80::f97d:20b0:70b7:5781/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

```

看起来需要重新编译内核，然后又一堆很麻烦的操作（（

我现在不知所措了……
