### DISCUSSION TITLE
dns 和 ip rule的问题

### DISCUSSION THREAD

**Discussion by ZTG0421** [MetaCubeX/mihomo#1300] [Q&A]
有两个问题，第一个是ip rule
```
9000:   from all to 198.18.0.0/30 lookup 2022
9001:   from all ipproto icmp goto 9010
9002:   not from all dport 53 lookup main suppress_prefixlength 0
9002:   not from all iif lo lookup 2022
9002:   from 0.0.0.0 iif lo lookup 2022
9002:   from 198.18.0.0/30 iif lo lookup 2022
9010:   from all nop
32766:  from all lookup main
32767:  from all lookup default
```

中的
```
9010:   from all nop
```
是什么？

第二个是当我把dns监听改成
```
dns:
  enable: true
  listen: :53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    ...
```
之后，lsof -i :53 看到只监听了ipv6呢？
```lsof -i :53
COMMAND    PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
mihomo  107028 root    8u  IPv6 4784769      0t0  UDP *:domain```
