### DISCUSSION TITLE
请教能否劫持tailscale或者zerotier数据

### DISCUSSION THREAD

**Discussion by somnifex** [MetaCubeX/mihomo#1360] [Q&A]
请教大家一个问题，当同时使用tailscale或者zerotier这种组网软件时，因为同时也建立的虚拟网卡，这时候相同网段就会与代理软件出现冲突，能否实现把clash作为前置代理分流后决定转发给组网出口还是直接通过系统网卡出口。
场景举例：
使用t/z组网，如果能够打通p2p的情况下使用t/z，如果不能打通则通过自建的某个内网穿透ss节点转发路由内网网段。通过clash的urltest可以实现快速判断有没有成功p2p（内穿服务器在国内，p2p延迟在10-20ms，中转延迟在80左右，t/z转发延迟在250+）

**Comment by somnifex** [comment]
这是我的部分配置文件：
```yaml
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: false
bind-address: "*"
ipv6: true
external-controller: 127.0.0.1:9090
mode: rule
log-level: info
unified-delay: true
global-ua: clash.meta
geo-auto-update: true
geodata-mode: false
geo-update-interval: 12
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/Hackl0us/GeoIP2-CN@release/Country.mmdb"
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8888]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
    - +.x.com
    - +.google.com
    - +.facebook.com
    - +.youtube.com
    - +.googlevideo.com
    - +.twitter.com
    - +.instagram.com
  skip-domain:
    - Mijia Cloud
    - Xiaomi Cloud
    - +.apple.com
    - +.icloud.com
dns:
  enabled: true
  ipv6: true
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
    - controlplane.tailscale.com
    - log.tailscale.io
  default-nameserver:
    - 223.5.5.5
    - 1.1.1.1
  nameserver:
    - system
    - dhcp://en0
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
    - https://8.8.8.8/dns-query
  fallback:
    - https://8.8.8.8/dns-query
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: false
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
      - 46.82.174.69/32
      - 59.24.3.174/32
      - 8.7.198.46/32
      - 93.46.8.90/32
    domain:
      - "+.ai.com"
      - "+.algolia.net"
      - "+.anthropic.com"
      - "+.arkoselabs.com"
      - "+.auth0.com"
      - "+.azure.com"
      - "+.azureedge.net"
      - "+.azureedge.net"
      - "+.bing.com"
      - "+.bingapis.com"
      - "+.bugsnag.com"
      - "+.chatgpt.com"
      - "+.claude.ai"
      - "+.cloudflare.net"
      - "+.cloudflareinsights.com"
      - "+.cohere.ai"
      - "+.docker.com"
      - "+.docker.io"
      - "+.facebook.com"
      - "+.github.com"
      - "+.githubusercontent.com"
      - "+.google"
      - "+.google.com"
      - "+.google.dev"
      - "+.googleapis.cn"
      - "+.googlevideo.com"
      - "+.identrust.com"
      - "+.infinitynewtab.com"
      - "+.instagram.com"
      - "+.intercom.io"
      - "+.live.com"
      - "+.livekit.cloud"
      - "+.microsoft.com"
      - "+.microsoftapp.net"
      - "+.minecraft.net"
      - "+.msn.com"
      - "+.openai.com"
      - "+.poe.com"
      - "+.segment.com"
      - "+.segment.io"
      - "+.sentry.io"
      - "+.synn.cc"
      - "+.stripe.com"
      - "+.t.me"
      - "+.tailscale.com"
      - "+.tailscale.io"
      - "+.twitter.com"
      - "+.usefathom.com"
      - "+.v2ex.com"
      - "+.windows.net"
      - "+.wootric.com"
      - "+.x.com"
      - "+.xn--ngstr-lra8j.com"
      - "+.youtube.com"
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
  device: utuncat0
  mtu: 1500
  strict-route: true
  route-address:
    - 0.0.0.0/1
    - 128.0.0.0/1
    - "::/1"
    - "8000::/1"
  route-exclude-address:
    - 100.64.0.0/10
    - 192.168.128.0/17
    - fd7a:115c:a1e0::/48
  include-package:
    - com.android.chrome
  exclude-package:
    - com.android.captiveportallogin
```
