### DISCUSSION TITLE
hysteria2 userpass 如何配置用户密码

### DISCUSSION THREAD

**Discussion by zendext** [MetaCubeX/mihomo#1364] [Q&A]
``` yaml
# v1.18.6 Mihomo
proxies:
  - name: 搬瓦工 US
    server: somehost
    port: 443
    type: hysteria2
    password: "user1:tHriy7Kaccd8Y9" # failed
    # password: somepassword # success
    protocol: udp
    up: 100
    down: 100

# server
auth:
  type: password
  password: somepassword 
  userpass: 
    user1: tHriy7Kaccd8Y9
```

**Comment by zendext** [comment]
服务端配置问题
```
# server
auth:
  type: userpass
  userpass: 
    user1: tHriy7Kaccd8Y9
```
