### DISCUSSION TITLE
请问Tun模式下创建的虚拟网卡可以不指定DNS吗？

### DISCUSSION THREAD

**Discussion by CarterCL** [MetaCubeX/mihomo#1394] [Q&A]
操作系统：Windows 11  
版本：alpha-9e3589d  

### 目前配置
```yaml
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:50053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - tls://223.5.5.5
tun:
  enable: true
  stack: system
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true
  route-address:
    - 198.18.0.0/16
```
### 想实现的功能
使用mosdns分流，国内的网址返回真实IP，国外的网址用mihomo的fake ip。因为配置了route-address，fake-ip段的流量会经过mihomo内核，国内的流量则不会经过。

### 遇到的问题
mihomo启动后，会生成一个虚拟网卡，并且配置了DNS 198.18.0.1，这样就导致我在出口网卡配置的DNS 127.0.0.1(mosdns)不生效，nslookup任意一个网址都会使用198.18.0.1这个DNS去解析返回fake-ip。
![mihomo](https://github.com/user-attachments/assets/a8397890-da22-48ff-b36a-a63510ead356)

而使用clash premium内核，生成的虚拟网卡不会配置DNS，这样在需要解析时，就会使用出口网卡的DNS了
![clash premium](https://github.com/user-attachments/assets/e322ea68-b840-4392-9266-8b16202bcccf)

### 我的问题
想问问各位大佬，有方法使mihomo在创建tun虚拟网卡时，不指定DNS吗？
