### DISCUSSION TITLE
如何才能把规则集添加到出站代理列表，使用不同的规则集？

### DISCUSSION THREAD

**Discussion by minusmulticoloredper** [MetaCubeX/mihomo#1401] [Q&A]
以下是基本配置
```yaml
proxy-groups:
- name: "节点选择"
  type: select
  include-all: true
  proxies:
  - REJECT
  - 自动选择
- name: "自动选择"
  type: url-test
  lazy: true
  url: 'https://www.google.com/generate_204'
  interval: 300
  include-all: true
- name: "规则模式"
  type: select 
  proxies:
  - 全局
  - 绕过大陆-白名单
  - 绕过大陆-黑名单
- name: "大陆网站"
  type: select 
  proxies:
  - REJECT
  - DIRECT
- name: "广告网站"
  type: select
  proxies:
  - REJECT
  - 节点选择
rule-providers:
  cndirect:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  gfwproxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400
  adreject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
```

以下是我想要添加到出站代理列表的规则集

全局:
```yaml
- GEOSITE,category-ads-all,广告网站
- RULE-SET,adreject,广告网站
- MATCH,节点选择
```
绕过大陆-白名单:
```yaml
- GEOSITE,category-ads-all,广告网站
- RULE-SET,adreject,广告网站
- RULE-SET,cndirect,大陆网站
- GEOSITE,CN,大陆网站
- RULE-SET,cncidr,大陆网站,no-resolve
- GEOIP,CN,大陆网站,no-resolve
- MATCH,节点选择
```
绕过大陆-黑名单:
```yaml
- GEOSITE,category-ads-all,广告网站
- RULE-SET,adreject,广告网站
- RULE-SET,gfwproxy,节点选择
- MATCH,大陆网站
```
