### DISCUSSION TITLE
安卓ChatGPT app无法登录

### DISCUSSION THREAD

**Discussion by misakaok** [MetaCubeX/mihomo#1477] [General]
登录一直返回主页 节点是支持app解锁的 iPhone上小🚀没问题 不知道怎么回事

```
mixed-port: 7890
allow-lan: false
ipv6: false
mode: rule
unified-delay: true
keep-alive-interval: 15
log-level: info
dns:
  cache-algorithm: arc
  enable: true
  respect-rules: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  nameserver:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
    - 1.1.1.1
    - 8.8.8.8
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
  nameserver-policy:
    "geosite:cn,private,apple":
      - https://223.5.5.5/dns-query
      - https://1.12.12.12/dns-query
external-controller: 127.0.0.1:9090
```
