### DISCUSSION TITLE
[使用问题求助]: 遇到了issue和讨论区中没出现的报错信息 "[UDP] dial 其他 (match Match/) 192.168.1.158:56256 --> 168.143.171.154:123 error: connection rejected: UDP initialization failed"

### DISCUSSION THREAD

**Discussion by youralmight** [MetaCubeX/mihomo#1515] [Q&A]
### 系统信息
```
root@openwrt ~/w/s/clash (main)# uname -a
Linux openwrt 5.15.150 #0 SMP Fri Mar 22 22:09:42 2024 aarch64 GNU/Linux
root@openwrt ~/w/s/clash (main)# ./clash.meta-linux-arm64 -v
Mihomo Meta v1.18.7 linux arm64 with go1.22.5 Sun Jul 28 05:47:47 UTC 2024
```
### 配置文件
```
proxy-providers:
  balabala

proxies:
  - name: "直连"
    type: direct
    udp: true

mixed-port: 7890
ipv6: true
allow-lan: true
unified-delay: false
tcp-concurrent: true

find-process-mode: off
global-client-fingerprint: chrome

profile:
  store-selected: false
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: false
  include-interface:
    - br-lan

dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  nameserver:
    - 4.2.2.1 # microsoft
    - 4.2.2.2
    - 208.67.222.222 # cisco
    - 208.67.220.220
    - 2620:0:ccc::2
    - 2620:0:ccd::2
proxy-groups:
  balabala

rules:
  - balabala
  - MATCH,其他

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: yaml}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: yaml}
rule-providers:
  balabala
```
## 复现方法
```
./clash.meta-linux-arm64 -d CONFIG_FOLDER -f CONFIG_FILE 2>&1 |tee clash.log
```

## 预期行为
```
root@openwrt ~/w/s/clash (main) [SIGINT|SIGINT]# cat clash.log|grep -i "level=error"
root@openwrt ~/w/s/clash (main) [0|1]# cat clash.log|grep -i "level=warning"|head -n 5
root@openwrt ~/w/s/clash (main) [0|1]#
```

##  实际结果

```
root@openwrt ~/w/s/clash (main)# cat clash.log|grep -i "level=error"
root@openwrt ~/w/s/clash (main) [0|1]# cat clash.log|grep -i "level=warning"|wc
    22705    340537   4561531
root@openwrt ~/w/s/clash (main)# cat clash.log|grep -i "level=warning"|grep 192.168.1.158|tail -n 20
time="2024-09-15T16:15:23.783046843Z" level=warning msg="[UDP] dial 其他 (match Match/) 192.168.1.158:56256 --> 168.143.171.154:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:15:23.863237137Z" level=warning msg="[UDP] dial 其他 (match Match/) 192.168.1.158:56256 --> 168.143.171.154:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:15:23.952918086Z" level=warning msg="[UDP] dial 其他 (match Match/) 192.168.1.158:56256 --> 168.143.171.154:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:15:24.042647664Z" level=warning msg="[UDP] dial 其他 (match Match/) 192.168.1.158:56256 --> 168.143.171.154:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:15:24.135582761Z" level=warning msg="[UDP] dial 其他 (match Match/) 192.168.1.158:56256 --> 168.143.171.154:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:15:24.342581951Z" level=warning msg="[UDP] dial 其他 (match Match/) 192.168.1.158:56256 --> 168.143.171.154:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:15:24.512568674Z" level=warning msg="[UDP] dial 其他 (match Match/) 192.168.1.158:56256 --> 168.143.171.154:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:15:24.90959897Z" level=warning msg="[UDP] dial 其他 (match Match/) 192.168.1.158:56256 --> 168.143.171.154:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:15:25.88496139Z" level=warning msg="[UDP] dial 其他 (match Match/) 192.168.1.158:56256 --> 168.143.171.154:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:15:26.912378339Z" level=warning msg="[UDP] dial 其他 (match Match/) 192.168.1.158:56256 --> 168.143.171.154:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:17:13.886012639Z" level=warning msg="[UDP] dial Twitter (match RuleSet/twitter_ip) 192.168.1.158:51023 --> 103.252.115.53:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:17:14.035156655Z" level=warning msg="[UDP] dial Twitter (match RuleSet/twitter_ip) 192.168.1.158:51023 --> 103.252.115.53:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:17:14.184751422Z" level=warning msg="[UDP] dial Twitter (match RuleSet/twitter_ip) 192.168.1.158:51023 --> 103.252.115.53:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:17:14.281431399Z" level=warning msg="[UDP] dial Twitter (match RuleSet/twitter_ip) 192.168.1.158:51023 --> 103.252.115.53:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:17:14.421426014Z" level=warning msg="[UDP] dial Twitter (match RuleSet/twitter_ip) 192.168.1.158:51023 --> 103.252.115.53:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:17:14.674907414Z" level=warning msg="[UDP] dial Twitter (match RuleSet/twitter_ip) 192.168.1.158:51023 --> 103.252.115.53:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:17:15.06953802Z" level=warning msg="[UDP] dial Twitter (match RuleSet/twitter_ip) 192.168.1.158:51023 --> 103.252.115.53:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:17:15.702411692Z" level=warning msg="[UDP] dial Twitter (match RuleSet/twitter_ip) 192.168.1.158:51023 --> 103.252.115.53:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:17:16.109572883Z" level=warning msg="[UDP] dial Twitter (match RuleSet/twitter_ip) 192.168.1.158:51023 --> 103.252.115.53:123 error: connection rejected: UDP initialization failed"
time="2024-09-15T16:17:17.231926706Z" level=warning msg="[UDP] dial Twitter (match RuleSet/twitter_ip) 192.168.1.158:51023 --> 103.252.115.53:123 error: connection rejected: UDP initialization failed"
```
192.168.1.158是我的openwrt路由器的下游设备，下游设备的ip是openwrt通过dhcp分配的。
