### DISCUSSION TITLE
新手有点不太理解这个的意思

### DISCUSSION THREAD

**Discussion by fyhong** [MetaCubeX/mihomo#1547] [Q&A]
https://wiki.metacubex.one/config/proxy-providers/content/#uri
这里说 YAML/uri/base64不可写在同一文件,uri/base64不需要proxies:字段,直接书写即可
这到底是什么意思？ 我这样写，直接是报错的。有没有哪位大老给个详细一点的配置教一下
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxy-providers:
   ss://YWVzLTI1Ni1nY206bWV0YUAxMjcuMC4wLjE6NDQz#ss1
   ss://YWVzLTI1Ni1nY206bWV0YUAxMjcuMC4wLjE6NDQz#ss2

![image](https://github.com/user-attachments/assets/39b430ef-19ae-4068-9c37-8839103a43ba)

**Comment by fouvromenth** [comment]
这是provider用的，你要再建一个文件，填进去，然后provider路径填到这个文件的

```
Folder
├─ mihomo内核文件
├─ 1.yml
└─ 2.yml
```
1就是你这个文件
```
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxy-providers:
    provider:
        type: file
        path: ./2.yml
...
```
2里填
```
ss://YWVzLTI1Ni1nY206bWV0YUAxMjcuMC4wLjE6NDQz#ss1
ss://YWVzLTI1Ni1nY206bWV0YUAxMjcuMC4wLjE6NDQz#ss2
```
