### DISCUSSION TITLE
求助：服务端为trojan-go时开启多路复用无法连接

### DISCUSSION THREAD

**Discussion by Einskai** [MetaCubeX/mihomo#1558] [Q&A]
Mihomo 版本：mihomo-linux-386-v1.18.9
配置：
```
  - name: "trojan-go"
    type: trojan
    server: server-url
    sni: server-url
    network: ws
    ws-opts:
      path: "/ws"
      headers:
        Host: server-url
    port: 443
    password: pw
    udp: true
    skip-cert-verify: true
    alpn:
      - http/1.1
    smux:
      enabled: true
      protocol: smux
```
当我把smux的enabled设置为false时，测试延迟会正常返回一个时间，但是当我把smux的enabled设置为true时，测试延迟会返回：
```{"message":"An error occurred in the delay test"}```
