### DISCUSSION TITLE
昨天新更新的direct-nameserver研究了半天不知道怎么用，希望各位大佬不吝赐教

### DISCUSSION THREAD

**Discussion by ciagelinsom** [MetaCubeX/mihomo#1567] [Q&A]
```yaml
dns:
    enable: true
    enhanced-mode: fake-ip
    fake-ip-filter:
        - rule-set:AD,HttpDNS
        - rule-set:CNdomain
    default-nameserver:
        - 223.5.5.5
    proxy-server-nameserver:
        - 223.6.6.6
    nameserver:
        - https://dns.cloudflare.com/dns-query#Proxy&ecs=1.1.1.1/24&ecs-override=true
        - https://dns.google/dns-query#Proxy&ecs=1.1.1.1/24&ecs-override=true
    nameserver-policy:
        rule-set:AD,HttpDNS: rcode://success
        rule-set:CNdomain:
            - https://dns.alidns.com/dns-query#ecs=114.114.114.114/24&ecs-override=true
            - https://doh.pub/dns-query#ecs=114.114.114.114/24&ecs-override=true
    direct-nameserver:
        - https://dns.alidns.com/dns-query#ecs=114.114.114.114/24&ecs-override=true
        - https://doh.pub/dns-query#ecs=114.114.114.114/24&ecs-override=true
    direct-nameserver-follow-policy: true
```
是这么个用法吗？
原来是按wiki的nspolicy非cn ns用cn
现在加了这么一功能
感觉ns继续用cn会乱套
所以这么改了一下
但感觉还是怪怪的
希望各位大佬不吝赐教

---

顺便再麻烦大佬重画下 https://wiki.metacubex.one/config/dns/diagram 的流程图吧

**Comment by potoo0** [comment]
域名解析时 direct-nameserver 和 nameserver/fallback 两条路径是平级的，如果配置了 direct-nameserver 那 nameserver/fallback 这条路径就无效了。

源码 [executor ApplyConfig -> updateDNS](https://github.com/MetaCubeX/mihomo/blob/v1.19.3/hub/executor/executor.go#L285):
```go
if r.DirectResolver.Invalid() {
    // r.DirectResolver 对应配置文件的 direct-nameserver, 配置了就会走这部分逻辑
    //     如果 `direct-nameserver-follow-policy: true` 则会引用 r.Resolver.policy (对应配置文件的 nameserver-policy)
    resolver.DirectHostResolver = r.DirectResolver
} else {
    // r.Resolver 对应就是 nameserver/fallback/nameserver-policy 这一堆, 配置文件不配置 direct-nameserver 就会走这部分逻辑
    resolver.DirectHostResolver = r.Resolver
}
```

dns resolver 的创建 [dns.resolver](https://github.com/MetaCubeX/mihomo/blob/v1.19.3/dns/resolver.go#L566)
```
if rs.DirectResolver != nil && config.DirectFollowPolicy {
    rs.DirectResolver.policy = r.policy
}
```

**Comment by gemnioo** [comment]
翻mihomo群聊**大概是如下逻辑:** 

direct-nameserver 用于 direct 出口域名解析的 DNS 服务器, 等于在 [nameserver-policy](https://wiki.metacubex.one/config/dns/#nameserver-policy) 加了条路由规则 Rules 里为所有 Direct 的DNS请求规则.(路由规则有些单独不在 Rule-set 里的 Direct)

[direct-nameserver-follow-policy](https://wiki.metacubex.one/config/dns/#direct-nameserver-follow-policy) 为 true 就先查 nameserver policy  默认为不遵守，仅当 direct-nameserver 不为空时生效

然后再是 nameserver-policy >>> nameserver <===> fallback 的配置

> nameserver-policy 只能匹配到域名，然而 direct 过来的又不一定是域名规则匹配到的
> 免了某些人希望 direct 走特定 direct-nameserver 的同时还想遵循 nameserver-policy
> 比如把 direct-nameserver 配置成国内的doh，然后再 nameserver-policy 中指定某些内网域名走内网dns服务器
> 要是direct-nameserver都没配置，那就完全不影响，继续以前的行为

以及 [direct-nameserver-follow-policy](https://wiki.metacubex.one/config/dns/#direct-nameserver-follow-policy) 为 true 实际上等于二选一 !!
> 看你开不开direct-nameserver-follow-policy喽
> 开了的话就policy优先
> 不开就直接无视

[respect-rules](https://wiki.metacubex.one/config/dns/#respect-rules) 等于省掉了 nameserver-policy 配的 💩\ 花一样. 
**匹配的仅是有规则 Dot/DoH 或者其他在路由规则申明的 DNS服务器**

> 想问一下 respect-rules 是怎么个流程？
> 根据rule规则，决定DNS服务器后面跟着的#
> 你要是#号指定了出站   就不匹配rule规则了吧
> 有那么难理解吗! dns的“连接”[遵守路由规则](https://wiki.metacubex.one/config/dns/#respect-rules)

> respect-rules 不是说是把 dns 服务器走哪个出口吗
> 是呀，其实就是把nameserver的远程解析开开
> 还是说你全程远程解析？**（把nameserver写国外，然后direct-ns和proxyserver-ns写国内并开respect-rules)**
> 是呀  匹配到direct再国内解析

> 那name server policy就用不上了吧
> 我自己的确没用
> 只不过以前udp走不了direct-ns的时候没办法得用

> respect-rules 开和关有什么区别
> 不开的话不走路由规则，那是怎么样的呢
> 不开走直连呗 
> 默认 #DIRECT
> 那我还是一一用#来指定策略组好点吧
> 就为了免得想你这种写一堆用#来指定策略组  ~~看着又臭又长~~

省流就是 direct-nameserver 用 ISP 的; nameserver 用海外的. 不要什么  nameserver-policy & fallback 那一坨.

对于域名匹配到 IP-CIDR规则后没有加 no-resolve IP规则会解析多次DNS.(理想情况是到 GeoIP: CN 才会开始解析)  使用 nameserver (海外的,可添加 ecs 参数.  若解析得到的 IP匹配 GeoIP: CN 的会用 direct-nameserver 二次解析:

> 第一次用nameserver解析出IP做判断，第二次用direct-nameserver做解析来实际连接

解决了可直连的小众网站被解析到 海外CDN的问题. 以及众多的 DNS 检测网站并发走了 nameserver fallback ~~泄露~~的问题 (只会有 nameserver 配置的和远程VPS配置的 DNS (Match Proxy 情况下

> 反正现在mihomo的reject在fakeip下终于不用解析IP了
> 之前是先解析了再做匹配
> 现在匹配流程和tcp一样了
> 所以以前对于udp到底写不写no-resolve都没啥意义
> 现在是匹配阶段和tcp一样，碰到没写no-resolve才开始解析
> 然后解析交给outbound
> 这样direct能走direct-ns
> reject能不用解析
> wireguard能走远程解析
> 其他的还是老老实实的本地解析

> 其实还是符合我自己的使用习惯，把nameserver写国外，然后direct-ns和proxyserver-ns写国内并开respect-rules

以及 fake-ip 还是 redir-host模式 如何匹配

> 简单来说，nameserver policy 还要为了redir-hos t模式，以及ip规则服务
> 不过要是redir-host模式，还是要用policy解决
> fake-ip就可以不用

> redir host解析生效在匹配前

> fakeip的逻辑很简单
> fakeip入站→恢复成域名
> 域名匹配规则→匹配到ip规则→解析用于判断
> 没匹配到ip规则就不解析
> 直连→使用解析出的ip连接
> **所以也不需要什么dns分流** !
> 只有udp会直接解析成ip为了兼容性

> 代理→发送域名给代理

**Reply by hplee0120** [reply]
> 
> 省流就是 direct-nameserver 用 ISP 的; nameserver 用海外的. 不要什么 nameserver-policy & fallback 那一坨.
> 

不用nameserver-policy的话会不会产生一个问题，fake-ip-filter里的所有域名，默认会发给nameserver走代理查询，虽然域名匹配阶段匹配到direct的话实际会被direct-nameserver兜回来用国内dns查询然后发起连接，但是实际解析了两次，第一次应答是国外，第二次是国内，会有什么问题吗，比如cloud.tencent.com这个域名，第一次是用nameserver应答走了代理返回了国外ip，但是又被direct-nameserver兜回来了，并不是单指这个域名，是有些国内服务需要真实ip的时候，第一次用了国外ip应答，然后又用国内ip连接会有问题吗

**Reply by gemnioo** [reply]
fake-ip-filter 那是 fake-ip 的范畴了. 

按照先匹配在选择那个解析. 你用的例子 cloud.tencent.com 这个域名 在路由规则里写了 Direct 是直接走 direct-nameserver. (respect-rules: true). 不会到 nameserver / fallback 匹配的 DNS 

> 反正现在mihomo的reject在fakeip下终于不用解析IP了
> 之前是先解析了再做匹配
> 现在 (UDP) 匹配流程和tcp一样了

**Reply by gemnioo** [reply]
> fake-ip-filter 那是 fake-ip 的范畴了.
> 
> 按照先匹配在选择那个解析. 你用的例子 cloud.tencent.com 这个域名 在路由规则里写了 Direct 是直接走 direct-nameserver. (respect-rules: true). 不会到 nameserver / fallback 匹配的 DNS
> 
> > 反正现在mihomo的reject在fakeip下终于不用解析IP了
> > 之前是先解析了再做匹配
> > 现在 (UDP) 匹配流程和tcp一样了

即不再路由规则的小众国内能直连的网站才会二次匹配走 direct-nameserver 兜回来 (可能就更新为国内有的 CDN 了).  虽然这个网站是 拿到的是 fake-ip

**Reply by kabuda2077** [reply]
> 翻mihomo群聊**大概是如下逻辑:**
> 
> direct-nameserver 用于 direct 出口域名解析的 DNS 服务器, 等于在 [nameserver-policy](https://wiki.metacubex.one/config/dns/#nameserver-policy) 加了条路由规则 Rules 里为所有 Direct 的DNS请求规则.(路由规则有些单独不在 Rule-set 里的 Direct)
> 
> [direct-nameserver-follow-policy](https://wiki.metacubex.one/config/dns/#direct-nameserver-follow-policy) 为 true 就先查 nameserver policy 默认为不遵守，仅当 direct-nameserver 不为空时生效
> 
> 然后再是 nameserver-policy >>> nameserver <===> fallback 的配置
> 
> > nameserver-policy 只能匹配到域名，然而 direct 过来的又不一定是域名规则匹配到的
> > 免了某些人希望 direct 走特定 direct-nameserver 的同时还想遵循 nameserver-policy
> > 比如把 direct-nameserver 配置成国内的doh，然后再 nameserver-policy 中指定某些内网域名走内网dns服务器
> > 要是direct-nameserver都没配置，那就完全不影响，继续以前的行为
> 
> 以及 [direct-nameserver-follow-policy](https://wiki.metacubex.one/config/dns/#direct-nameserver-follow-policy) 为 true 实际上等于二选一 !!
> 
> > 看你开不开direct-nameserver-follow-policy喽
> > 开了的话就policy优先
> > 不开就直接无视
> 
> [respect-rules](https://wiki.metacubex.one/config/dns/#respect-rules) 等于省掉了 nameserver-policy 配的 💩\ 花一样. **匹配的仅是有规则 Dot/DoH 或者其他在路由规则申明的 DNS服务器**
> 
> > 想问一下 respect-rules 是怎么个流程？
> > 根据rule规则，决定DNS服务器后面跟着的#
> > 你要是#号指定了出站   就不匹配rule规则了吧
> > 有那么难理解吗! dns的“连接”[遵守路由规则](https://wiki.metacubex.one/config/dns/#respect-rules)
> 
> > respect-rules 不是说是把 dns 服务器走哪个出口吗
> > 是呀，其实就是把nameserver的远程解析开开
> > 还是说你全程远程解析？**（把nameserver写国外，然后direct-ns和proxyserver-ns写国内并开respect-rules)**
> > 是呀  匹配到direct再国内解析
> 
> > 那name server policy就用不上了吧
> > 我自己的确没用
> > 只不过以前udp走不了direct-ns的时候没办法得用
> 
> > respect-rules 开和关有什么区别
> > 不开的话不走路由规则，那是怎么样的呢
> > 不开走直连呗
> > 默认 #DIRECT
> > 那我还是一一用#来指定策略组好点吧
> > 就为了免得想你这种写一堆用#来指定策略组  ~看着又臭又长~
> 
> 省流就是 direct-nameserver 用 ISP 的; nameserver 用海外的. 不要什么 nameserver-policy & fallback 那一坨.
> 
> 对于域名匹配到 IP-CIDR规则后没有加 no-resolve IP规则会解析多次DNS.(理想情况是到 GeoIP: CN 才会开始解析) 使用 nameserver (海外的,可添加 ecs 参数. 若解析得到的 IP匹配 GeoIP: CN 的会用 direct-nameserver 二次解析:
> 
> > 第一次用nameserver解析出IP做判断，第二次用direct-nameserver做解析来实际连接
> 
> 解决了可直连的小众网站被解析到 海外CDN的问题. 以及众多的 DNS 检测网站并发走了 nameserver fallback ~泄露~的问题 (只会有 nameserver 配置的和远程VPS配置的 DNS (Match Proxy 情况下
> 
> > 反正现在mihomo的reject在fakeip下终于不用解析IP了
> > 之前是先解析了再做匹配
> > 现在匹配流程和tcp一样了
> > 所以以前对于udp到底写不写no-resolve都没啥意义
> > 现在是匹配阶段和tcp一样，碰到没写no-resolve才开始解析
> > 然后解析交给outbound
> > 这样direct能走direct-ns
> > reject能不用解析
> > wireguard能走远程解析
> > 其他的还是老老实实的本地解析
> 
> > 其实还是符合我自己的使用习惯，把nameserver写国外，然后direct-ns和proxyserver-ns写国内并开respect-rules
> 
> 以及 fake-ip 还是 redir-host模式 如何匹配
> 
> > 简单来说，nameserver policy 还要为了redir-hos t模式，以及ip规则服务
> > 不过要是redir-host模式，还是要用policy解决
> > fake-ip就可以不用
> 
> > redir host解析生效在匹配前
> 
> > fakeip的逻辑很简单
> > fakeip入站→恢复成域名
> > 域名匹配规则→匹配到ip规则→解析用于判断
> > 没匹配到ip规则就不解析
> > 直连→使用解析出的ip连接
> > **所以也不需要什么dns分流** !
> > 只有udp会直接解析成ip为了兼容性
> 
> > 代理→发送域名给代理

您好我想请教一下：
是不是在fakeip模式下。整个过程分两个阶段：dns解析ip映射和数据路由

dns解析阶段：先通过nameserver-policy分别解析ip。剩下的给nameserver解析。如果没有配置policy就全部交给nameserver解析。同时fakeip匹配一个假ip，假ip给浏览器

数据路由阶段：域名和真ip发给rules去匹配规则。匹配上了direct，那就交给direct-nameserver去解析然后连接传输数据。如果匹配到代理，那就直接把域名发给代理服务器，代理服务器解析后，建立连接开始传输数据。

不知道这个流程对不对？

但是我不理解的是：
1.dns解析这个过程的目的是啥？最终不都要交给directns解析一遍，或者发给代理服务器解析一遍。
2.如果我在fakeipfilter设置了所有国内域名，那国内域名的整个流程又是什么样的。

**Reply by mengdegege** [reply]
> 是不是在fakeip模式下。整个过程分两个阶段：dns解析ip映射和数据路由
> 
> dns解析阶段：先通过nameserver-policy分别解析ip。剩下的给nameserver解析。如果没有配置policy就全部交给nameserver解析。同时fakeip匹配一个假ip，假ip给浏览器
> 
> 数据路由阶段：域名和真ip发给rules去匹配规则。匹配上了direct，那就交给direct-nameserver去解析然后连接传输数据。如果匹配到代理，那就直接把域名发给代理服务器，代理服务器解析后，建立连接开始传输数据。
> 
> 不知道这个流程对不对？
> 
> 但是我不理解的是：
> 1.dns解析这个过程的目的是啥？最终不都要交给directns解析一遍，或者发给代理服务器解析一遍。
> 2.如果我在fakeipfilter设置了所有国内域名，那国内域名的整个流程又是什么样的。

就是这样的，但是这两个阶段是有先后顺序的，不是同时发生。而且tun模式和代理模式有点区别，代理模式，不需要返回给浏览器IP，浏览器会直接把域名请求交给入站代理，之后匹配规则，只有匹配到出站为直连时才需要解析。或者某些情况下如果配置到系统的入站代理支持UDP，浏览器可能会把UDP请求交给入站代理，然后有的代理协议需要在代理UDP出站时进行本地解析（这个可能是UDP协议的特性，必须有目标IP，具体没有了解很深入）。
tun模式的区别就在于，它要先发起一次解析请求，获得IP后，再用IP发起连接请求，这个IP可以是fake-ip，也可以是真实IP，取决于enhanced配置和fake-ip-filter， 但是入站前的解析，不会跟direct-names-server有关，因为这时还没有匹配出站。
所以，如果你把需要直连的域名配置为，需要解析真实IP，同时又配置了direct-namese-server，并且是tun入站，就会观察到两次解析。

**Comment by gemnioo** [comment]
用 Nikki 在路由器内测试,  `direct-nameserver ` 字段的 Direct 控制的只是 `fake-ip` 不再 `fake-ip-filter` 内的直连.  一旦走 `redir-host` & `fake-ip-filter` 还是直接请求 nameserver/ fallback. 区别只是会兜底绕回来 ?

第一份 Config: 
```
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - rule-set:fakeip-filter
    - geosite:cn
  nameserver:
    - 'https://dns.google/dns-query#Proxy&ecs=223.5.5.5&ecs-override=true'
  nameserver-policy:
   '+.caixin.com': '223.5.5.5'
   '+.hash070.com': 'https://dns.alidns.com/dns-query'
   '+.aigcbest.top': 'https://dns.alidns.com/dns-query'
   '+.ptlogin2.qq.com': 'https://dns.alidns.com/dns-query'
   '*.tailname.ts.net': '100.100.100.100'
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query#DIRECT
  direct-nameserver:
    - <ISP_DNS_1>
    - <ISP_DNS_1>
  direct-nameserver-follow-policy: true
  ```
  观察到 weibo 在 fake-ip filter - geostie:cn 内.  redir-host 请求 name server 然后兜底回 ISP_DNS
  ```
  time="2025-06-28T02:53:37.063584586Z" level=debug msg="[DNS] resolve weibo.com HTTPS from https://dns.google:443/dns-query"
time="2025-06-28T02:53:37.065804326Z" level=debug msg="[DNS] resolve weibo.com A from https://dns.google:443/dns-query"
time="2025-06-28T02:53:37.297106267Z" level=debug msg="[DNS] weibo.com --> [] HTTPS from https://dns.google:443/dns-query"
time="2025-06-28T02:53:37.297347062Z" level=debug msg="[DNS] weibo.com --> [49.7.37.74] A from https://dns.google:443/dns-query"
time="2025-06-28T02:53:37.422555274Z" level=debug msg="[Rule] use default rules"
time="2025-06-28T02:53:37.425920364Z" level=debug msg="[DNS] resolve weibo.com A from udp://<ISP_DNS_1>:53"
time="2025-06-28T02:53:37.426002532Z" level=debug msg="[DNS] resolve weibo.com A from udp://<ISP_DNS_2>:53"
time="2025-06-28T02:53:37.470488503Z" level=debug msg="[DNS] weibo.com --> [198.18.0.62] A from udp://<ISP_DNS_1>:53"
time="2025-06-28T02:53:37.470676547Z" level=debug msg="[DNS] weibo.com --> [198.18.0.62] A from udp://<ISP_DNS_2>:53"

time="2025-06-28T02:54:10.460581230Z" level=debug msg="[DNS] resolve tvax1.sinaimg.cn HTTPS from https://dns.google:443/dns-query"
time="2025-06-28T02:54:10.461238823Z" level=debug msg="[DNS] resolve tvax1.sinaimg.cn A from https://dns.google:443/dns-query"
time="2025-06-28T02:54:10.503014630Z" level=debug msg="[DNS] reward.media.weibo.com --> [49.7.37.74 106.63.15.10] A from https://dns.google:443/dns-query"
time="2025-06-28T02:54:10.568421859Z" level=debug msg="[Rule] use default rules"
time="2025-06-28T02:54:10.571773532Z" level=debug msg="[DNS] resolve reward.media.weibo.com A from udp://<ISP_DNS_1>:53"
time="2025-06-28T02:54:10.571854409Z" level=debug msg="[DNS] resolve reward.media.weibo.com A from udp://<ISP_DNS_2>:53"
time="2025-06-28T02:54:10.615054361Z" level=debug msg="[DNS] reward.media.weibo.com --> [198.18.0.66] A from udp://<ISP_DNS_2>:53"
```

**Comment by gemnioo** [comment]
第二份 Config: (增改简略)
```
dns:
  enable: true
  fake-ip-filter:
    - rule-set:fakeip-filter
    # geosite:cn  **删除geosite:cn 迫使国内域名也拿到的也是 fake-ip**
  nameserver-policy:
   '+.aigcbest.top': 'https://223.5.5.5/dns-query'  **该域名在 rule-set:fakeip-filter中** 
  direct-nameserver:
    - <ISP_DNS_1>
    - <ISP_DNS_1>
  direct-nameserver-follow-policy: true
  ```
  观察到 某些域名  redir-host 请求 遵照 `nameserver-policy` 定义拿到 真实的 <IPv4_address>
  ```
  time="2025-06-28T04:51:18.008131687Z" level=debug msg="[DNS] resolve weibo.com A from udp://<ISP_DNS_2>:53"
time="2025-06-28T04:51:18.008216396Z" level=debug msg="[DNS] resolve weibo.com A from udp://<ISP_DNS_1>:53"
time="2025-06-28T04:51:18.050868215Z" level=debug msg="[DNS] weibo.com --> [198.18.0.35] A from udp://<ISP_DNS_2>:53"
time="2025-06-28T04:51:18.052648407Z" level=info msg="[TCP] 192.168.10.103:57059 --> weibo.com:443 match RuleSet(ChinaDirect) using 🚀 直接连接[DIRECT]"

time="2025-06-28T04:53:10.551165864Z" level=debug msg="[DNS] cache hit weibo.com --> [198.18.0.35] A, expire at 2025-06-28 04:51:19"
time="2025-06-28T04:53:10.551663788Z" level=debug msg="[DNS] resolve weibo.com A from udp://<ISP_DNS_2>:53"
time="2025-06-28T04:53:10.551739622Z" level=debug msg="[DNS] resolve weibo.com A from udp://<ISP_DNS_1>:53"
time="2025-06-28T04:53:10.553023849Z" level=info msg="[TCP] 192.168.10.103:57103 --> weibo.com:443 match RuleSet(ChinaDirect) using 🚀 直接连接[DIRECT]"
time="2025-06-28T04:53:10.560651083Z" level=debug msg="[DNS] weibo.com --> [198.18.0.35] A from udp://<ISP_DNS_2>:53"
time="2025-06-28T04:53:11.391536351Z" level=debug msg="[Rule] use default rules"
time="2025-06-28T04:53:11.395183194Z" level=debug msg="[DNS] resolve reward.media.weibo.com A from udp://<ISP_DNS_2>:53"
time="2025-06-28T04:53:11.395245612Z" level=debug msg="[DNS] resolve reward.media.weibo.com A from udp://<ISP_DNS_1>:53"
time="2025-06-28T04:53:11.438416105Z" level=debug msg="[DNS] reward.media.weibo.com --> [198.18.0.60] A from udp://<ISP_DNS_1>:53"
time="2025-06-28T04:53:11.438644067Z" level=debug msg="[DNS] reward.media.weibo.com --> [198.18.0.60] A from udp://<ISP_DNS_2>:53"
time="2025-06-28T04:53:11.440604595Z" level=info msg="[TCP] 192.168.10.103:57104 --> reward.media.weibo.com:443 match RuleSet(ChinaDirect) using 🚀 直接连接[DIRECT]"

time="2025-06-28T05:00:31.560313489Z" level=debug msg="[Rule] use default rules"
time="2025-06-28T05:00:31.563397825Z" level=debug msg="[DNS] cache hit api2.aigcbest.top --> [<IPv4_address>] A, expire at 2025-06-28 04:58:31"
time="2025-06-28T05:00:31.563839498Z" level=debug msg="[DNS] resolve api2.aigcbest.top A from https://223.5.5.5:443/dns-query"
time="2025-06-28T05:00:31.565260143Z" level=info msg="[TCP] 192.168.10.103:51445 --> api2.aigcbest.top:443 match RuleSet(ChinaDirect) using 🚀 直接连接[DIRECT]"
time="2025-06-28T05:00:31.566082988Z" level=info msg="[TCP] mihomo --> 223.5.5.5:443 doesn't match any rule using DIRECT"
time="2025-06-28T05:00:31.685637988Z" level=debug msg="[DNS] api2.aigcbest.top --> [<IPv4_address>] A from https://223.5.5.5:443/dns-query"
```

**Comment by gemnioo** [comment]
第三份 Config: (增改简略)
```
dns:
  enable: true
  fake-ip-filter:
    - rule-set:fakeip-filter
    - geosite:cn  **重新添加回该字段**
  nameserver-policy:
   '+.aigcbest.top': 'https://223.5.5.5/dns-query'  **该域名在 rule-set:fakeip-filter 中** 
  direct-nameserver:
    - <ISP_DNS_1>
    - <ISP_DNS_1>
  direct-nameserver-follow-policy: false **改为只请求 direct-nameserver:**
  ```
  观察到: weibo 在 fake-ip filter - geostie:cn 内. redir-host 请求 name server 然后兜底回 ISP_DNS 但为何拿到的是 fakeip  [198.18.0.35] [198.18.0.60]  & 在面板 flush Fake-IP 后试了两次均为如此..
  
### `direct-nameserver` + `follow-policy: false` 等同于强制使用全部 fake-ip ？
  
 在 某些域名  redir-host 请求 因 false `nameserver-policy` 导致不再 `geosite:cn` 中的某些域名拿到 fake-ip [198.18.0.93]
  
  
  ```
  time="2025-06-28T05:31:16.007651364Z" level=debug msg="[DNS] cache hit weibo.com --> [] HTTPS, expire at 2025-06-28 05:30:03"
time="2025-06-28T05:31:16.007798158Z" level=debug msg="[DNS] cache hit weibo.com --> [49.7.37.74] A, expire at 2025-06-28 05:30:03"
time="2025-06-28T05:31:16.008056120Z" level=debug msg="[DNS] resolve weibo.com HTTPS from https://dns.google:443/dns-query"
time="2025-06-28T05:31:16.008138663Z" level=debug msg="[DNS] resolve weibo.com A from https://dns.google:443/dns-query"
time="2025-06-28T05:31:16.018350856Z" level=debug msg="[Rule] use default rules"
time="2025-06-28T05:31:16.021575487Z" level=debug msg="[DNS] cache hit weibo.com --> [198.18.0.35] A, expire at 2025-06-28 05:29:04"
time="2025-06-28T05:31:16.022023327Z" level=debug msg="[DNS] resolve weibo.com A from udp://<ISP_DNS_2>:53"
time="2025-06-28T05:31:16.022108828Z" level=debug msg="[DNS] resolve weibo.com A from udp://<ISP_DNS_1>:53"
time="2025-06-28T05:31:16.023291804Z" level=info msg="[TCP] 192.168.10.103:54053 --> weibo.com:443 match RuleSet(ChinaDirect) using 🚀 直接连接[DIRECT]"

time="2025-06-28T05:31:16.983617113Z" level=debug msg="[DNS] resolve reward.media.weibo.com HTTPS from https://dns.google:443/dns-query"
time="2025-06-28T05:31:16.984401833Z" level=debug msg="[DNS] resolve reward.media.weibo.com A from https://dns.google:443/dns-query"
time="2025-06-28T05:31:17.041191299Z" level=debug msg="[Rule] use default rules"
time="2025-06-28T05:31:17.044772727Z" level=debug msg="[DNS] resolve reward.media.weibo.com A from udp://<ISP_DNS_1>:53"
time="2025-06-28T05:31:17.044856062Z" level=debug msg="[DNS] resolve reward.media.weibo.com A from udp://<ISP_DNS_2>:53"
time="2025-06-28T05:31:17.051462493Z" level=debug msg="[DNS] reward.media.weibo.com --> [198.18.0.60] A from udp://<ISP_DNS_1>:53"
time="2025-06-28T05:31:17.051634162Z" level=debug msg="[DNS] reward.media.weibo.com --> [198.18.0.60] A from udp://<ISP_DNS_2>:53"
time="2025-06-28T05:31:17.053571733Z" level=info msg="[TCP] 192.168.10.103:54063 --> reward.media.weibo.com:443 match RuleSet(ChinaDirect) using 🚀 直接连接[DIRECT]"

time="2025-06-28T05:30:42.101321991Z" level=debug msg="[Rule] use default rules"
time="2025-06-28T05:30:42.104620415Z" level=debug msg="[DNS] resolve api2.aigcbest.top A from udp://<ISP_DNS_2>:53"
time="2025-06-28T05:30:42.104702583Z" level=debug msg="[DNS] resolve api2.aigcbest.top A from udp://<ISP_DNS_1>:53"
time="2025-06-28T05:30:42.150860226Z" level=debug msg="[DNS] api2.aigcbest.top --> [198.18.0.93] A from udp://<ISP_DNS_2>:53"
time="2025-06-28T05:30:42.152633294Z" level=info msg="[TCP] 192.168.10.103:54049 --> api2.aigcbest.top:443 match RuleSet(ChinaDirect) using 🚀 直接连接[DIRECT]"
```
