### DISCUSSION TITLE
怎么配置，才能让mihomo的DNS监听能同时监听某个ipv4和ipv6地址？

### DISCUSSION THREAD

**Discussion by weiweiwitch** [MetaCubeX/mihomo#1582] [Q&A]
目前在内网的某台ubuntu机器上（192.168.0.5）部署了mihomo当透明代理。然后其他机器的DNS配置也会指定这台机器。

因为ubuntu本身会监听`127.0.0.53`，所以，mihomo的DNS只能配置为
```yaml
dns:
  # 因为会和本机的resolve冲突，所以必须强制绑定内网IP。
  listen: 192.168.0.5:53
```

然后因为Ubuntu本身的缘故，其他的Ubuntu机器在配置DNS时，如果不指定ipv6的DNS地址。系统会自动从路由器获取一个ipv6的DNS。

其他机器上执行resolvectl命令，输出的信息类似
```
Current DNS Server: 192.168.0.5
       DNS Servers: 192.168.0.5 fd40:967c:e266::38
```

这导致mihomo如果不充当ipv6的DNS服务器。其他机器的DNS查询就不会走mihomo那台机器。

问题是，我无法找到配置上的说明，能让我同时配置特定ipv4和ipv6地址的DNS监听。

所以如何配置，才能让mihomo的DNS监听能同时监听某个`192.168.0.5:53`和`[fd40:967c:e266::5]:53`？
