### DISCUSSION TITLE
彦祖们，配置求帮助

### DISCUSSION THREAD

**Discussion by iwalke** [MetaCubeX/mihomo#1599] [Q&A] [answered]
彦祖们，配置疑惑，求解答

 [geosite](https://wiki.metacubex.one/config/dns/?h=geosite#geosite) 列表的内容（cn,private）指的是 [rule-providers](https://wiki.metacubex.one/config/rule-providers/content/) 中定义的名称么？

对于 `https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt` 的域名都走指定的 dns？

部分配置
```yaml
...
dns:
  ...
  ipv6: true
  enhanced-mode: redir-host / fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
  nameserver:
    - https://doh.pub/dns-query
  fallback:
    - https://8.8.8.8/dns-query
  nameserver-policy:
    # 这个 cn,private
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
...
rule-providers:
  private:
    type: http
    format: yaml
    interval: 86400
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/loyalsoldier/private.yaml
...
```
