### DISCUSSION TITLE
[TUN] 规则路由如何在 tun 模式中排除指定规则集并保留原有的私有地址

### DISCUSSION THREAD

**Discussion by Kwisma** [MetaCubeX/mihomo#1609] [Q&A]
排除规则集后会暴露本机的 WebRTC 私有地址，而非 tun 的私有地址
我想排除国内ip不经过 tun 该怎么写

```
tun:
  enable: true 
  stack: gvisor
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53 
  device: utun0 
  mtu: 9000  
  strict-route: true 
  gso: true 
  gso-max-size: 65536 
  udp-timeout: 300
  iproute2-table-index: 2022 
  iproute2-rule-index: 9000
  endpoint-independent-nat: false
  route-address-set: [all] 
  route-exclude-address-set: [cnip] 
```
