### DISCUSSION TITLE
direct-nameserver 无法正常解析直连规则的域名

### DISCUSSION THREAD

**Discussion by HozumiMoa** [MetaCubeX/mihomo#1656] [General]
```yaml
dns:
  enable: true
  ipv6: false
  use-system-hosts: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - geosite:private
  default-nameserver:
    - quic://223.5.5.5
    - quic://223.6.6.6
  nameserver-policy:
    geosite:private:
      - system
  direct-nameserver:
    - https://dns.alidns.com/dns-query#h3=true
    - quic://dns.alidns.com
  nameserver:
    - https://dns.google/dns-query#h3=true
    - https://cloudflare-dns.com/dns-query#h3=true
rules:
  # GEOSITE 规则
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,private,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - DOMAIN-SUFFIX,googleapis.cn,🚀 节点选择
  - GEOSITE,geolocation-!cn,🚀 节点选择
  - GEOSITE,cn,DIRECT

  # GEOIP 规则
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,🐟 Final
```
- RT，用的是上述配置，`direct-nameserver` 使用 alidns，`nameserver` 使用 google、cloudflare
- 按理来说，`rules` 中所有走 `DIRECT` 的域名会被 `direct-nameserver` 解析，结果是 TCP 连接确实被 `direct-nameserver` 解析，但 UDP 连接却绕过 `direct-nameserver`，被 `nameserver` 解析了
- 现象：正常情况下腾讯游戏的延迟在 10ms 左右，但使用上述配置后延迟达到 40ms+，检查连接记录后发现 UDP 连接走的域名都被本地解析到**香港腾讯云**的 IP

---

- 怎么验证这个结论呢，只要将 `direct-nameserver` 和 `nameserver` 对调，结果是网页浏览的延迟明显变高的同时，游戏延迟却变回正常 10ms 了
