### DISCUSSION TITLE
Tun的fake ip模式下ipv6如何使用远程桌面等功能？

### DISCUSSION THREAD

**Discussion by Keldos-Li** [MetaCubeX/mihomo#1685] [Q&A]
大家好，我使用clash verge rev的tun模式，DNS模式是fake-ip。

我目前一直使用动态解析的公网ipv6来连接我的主机（被控端），相关的远程和串流软件有Windows App（RDP协议）、Moonlight（NVIDIA 的 GameStream 协议）。只要我开启tun模式时同时启用ipv6，所有远程服务都会失效，只有不tun代理ipv6才能被连接通。相关端口和进程名都写给了规则的DIRECT，但是没有用。

目前我是一直在clash中关闭ipv6使用远程连接的。我并不能在日志或者哪里找到tun代理了哪些地址或端口导致的问题，在发起请求端查看网络日志也只有向主机的ipv6地址发起tcp请求之类。这是应该写fake ip filter规则可以解决的问题吗？我实在找不出办法了o(╥﹏╥)o

附上我的扩展配置：

```yaml
tun:
  route-exclude-address:
    - 10.0.0.0/8
    - 172.27.0.0/16

dns:
  enable: true
  use-system-hosts: true
  enhanced-mode: fake-ip
  ipv6: true
  default-nameserver: 
    - 114.114.114.114
    - 119.29.29.29
    - 1.0.0.1
  nameserver-policy:
    '*.zju.edu.cn': '10.10.0.21'
  nameserver: 
    - 233.5.5.5
    - 119.29.29.29
  fallback:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
  route-exclude-address:
    - 172.27.0.0/16
    - fc00::/7
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.google.cn
      - +.googleapis.cn
      - +.gvt1.com
  fake-ip-filter: 
    # Local
    - "*.lan"
    - "*.local"
    - ".ntp.org"
    - "*.localhost"
    - "*.localdomain"
    - "*.test"
    - "*.home.arpa"
    - "*.invalid"
    - "*.example"
    # 放行NTP服务
    - "time.*.com"
    - "time.*.gov"
    - "ntp.*.com"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    # Tencent
    - 'localhost.ptlogin2.qq.com'
    - "localhost.sec.qq.com"
    - "+.qq.com"
    - "+.tencent.com"
    - "localhost.work.weixin.qq.com"
    - "+.weixin.qq.com"
    - "+.wechat.com" 
    # Microsoft Windows Serivice
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - "*.microsoftonline.com"
    - "time.windows.com" 
    - "+.msftncsi.com"
    - "+.steamcontent.com"
    # STUN
    - "stun.*.*"
    - "stun.*.*.*"
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    # Apple Software Update Service
    - "mesu.apple.com"
    - "swscan.apple.com"
    - "swquery.apple.com"
    - "swdownload.apple.com"
    - "swcdn.apple.com"
    - "swdist.apple.com"
    # Mijia
    - "Mijia Cloud"


rule-providers:
(略）

rules:
  - IP-CIDR,10.0.0.0/8,PASS,no-resolve

  - DST-PORT,3389,DIRECT
  - DST-PORT,47984-47989,DIRECT
  - DST-PORT,48010-48011,DIRECT
  - DST-PORT,47998-48000,DIRECT

……其他规则略

```
