### DISCUSSION TITLE
host 配置需要怎么写才能正常生效？

### DISCUSSION THREAD

**Discussion by Starseeker-H** [MetaCubeX/mihomo#1750] [Q&A]
起因是openwrt上使用openclash，会自动劫持内网所有dns请求，为了确保服务在内外网的域名一致，在openclash内设置自定义dns解析如下：

```yaml
dns:
  enable: true
  use-hosts: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874

  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
    - tls://1.12.12.12:853
    - tls://223.5.5.5:853
  nameserver-policy:
    "geosite: cn,private,apple":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
  nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - 119.29.29.29
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
  fallback:
    - https://doh.dns.sb/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://dns.twnic.tw/dns-query
    - https://public.dns.iij.jp/dns-query
    - https://jp.tiar.app/dns-query
    - https://jp.tiarap.org/dns-query
    - tls://8.8.4.4:853
    - tls://1.1.1.1
  fallback-filter:
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
hosts:
  "test.test": 192.168.1.15  ##lucky 宿主机
```

但完全没用，内网 test.test 并不能解析到ip

考虑到是不是openclash的问题，使用 Clash Nyanpasu ，写了个极简配置，只写了dns和hosts

```yaml
mixed-port: 7893
ipv6: false
mode: rule
dns:
  enable: true
  use-hosts: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:53
hosts:
  test.test: 192.168.1.15
```

结果如下
```
C:\Windows\system32>nslookup test.test 192.168.1.21 # 测试的windows主机
Server:  UnKnown
Address:  192.168.1.21

*** UnKnown can't find test.test: Non-existent domain
```

所以说，是hosts配置哪里写的有问题吗？还是说需要其他配置配合？
