### DISCUSSION TITLE
内置的DNS服务器，解析结果不支持内网IP？

### DISCUSSION THREAD

**Discussion by Starseeker-H** [MetaCubeX/mihomo#1773] [Q&A]
测试用配置：
```yaml
hosts:
  "test.com": 1.2.3.4
  "test.in.com": 192.168.99.99
```

```
PS C:\Users\-xz-> nslookup test.com 192.168.1.1
服务器:  XZ_Op.lan
Address:  192.168.1.1

名称:    test.com
Addresses:  ::ffff:1.2.3.4
          1.2.3.4

PS C:\Users\-xz-> nslookup test.in.com 192.168.1.1
服务器:  XZ_Op.lan
Address:  192.168.1.1

*** 没有 test.in.com 可以使用的 internal type for both IPv4 and IPv6 Addresses (A+AAAA)记录
```

类似的，DNS 供应商记录里填的内网 IP 记录在其他 DNS 服务器均可正常解析到的情况下，通过 meta 解析不到，同样返回无记录

这一需求主要来源于校园网内，不需要也搞不到公网 IP，DNS 解析指定寝室内设备 IP 就足够校园内使用了，但反而是 meta 控制的内网下无法用域名直接访问就很难顶……
