### DISCUSSION TITLE
urltest

### DISCUSSION THREAD

**Discussion by screousi0103** [MetaCubeX/mihomo#1779] [Ideas]
一点想法

现在的 url test 是按照延迟从低到高选择，虽然有 tolerance 在，但被选中的节点依旧比较集中，网络波动大

---
延迟从高到低选择的 url-test

```yaml
proxy-groups:
- name: "自动选择"
  type: url-test
  include-all: true
  filter: "(?i)港|hk|hongkong|hong kong"
  timeout: 200

  order: reverse
```
可以选择延迟最接近 200 而不是 0 的节点

---
可以选择位次的 url-test
```yaml
proxy-groups:
- name: "自动选择"
  type: url-test
  include-all: true
  filter: "(?i)港|hk|hongkong|hong kong"

  rank: 5
```
可以选择延迟排序时的第 5 个节点，若节点数量小于 5，则选择排序末位的。
