### DISCUSSION TITLE
设置geox-url后无法获取geo

### DISCUSSION THREAD

**Discussion by houtarchat-cyber** [MetaCubeX/mihomo#1813] [Q&A]
将rules-dat上传至OSS，文件sha256与GitHub Actions所记录一致，但无法下载

![image](https://github.com/user-attachments/assets/17bf8a87-95e5-4c88-acaa-2fc2007f1f70)

![image](https://github.com/user-attachments/assets/77d2359c-8e48-43dd-b4e0-0d4183f0cfc2)

```yaml
geodata-mode: true
geox-url:
  geoip: "https://freesub.oss-cn-beijing.aliyuncs.com/geodata/geoip-lite.dat"
  geosite: "https://freesub.oss-cn-beijing.aliyuncs.com/geodata/geosite.dat"
  mmdb: "https://freesub.oss-cn-beijing.aliyuncs.com/geodata/country-lite.mmdb"
```

如何解决
