### DISCUSSION TITLE
使用curl通过mihomo代理无法完成访问

### DISCUSSION THREAD

**Discussion by ShiFangJuMie** [MetaCubeX/mihomo#1843] [Q&A]
为了演示方便，我选择百度作为目标服务器

实际使用场景是，人在外面时通过家里的nas服务器做中转，实现包括内网穿透、翻墙等。路径上是
当前设备->ddns到家里路由器->nat到nas指定端口

mihomo是通过docker部署的最新版镜像，主要集中的表现是得到以下回复
curl: (56) Recv failure: Connection reset by peer
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.baidu.com:443 

配置文件节选：

```
mixed-port: 7890
ipv6: true
allow-lan: true
authentication:
  - "aaa:bbb"
skip-auth-prefixes:
省略
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
clash-for-android:
    append-system-dns: false
dns:
  enable: true
  listen: 127.0.0.1:53
  default-nameserver: [223.5.5.5, 119.29.29.29]
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter: ["*.n.n.srv.nintendo.net", +.stun.playstation.net, xbox.*.*.microsoft.com, "*.msftncsi.com", "*.msftconnecttest.com", WORKGROUP, "*.lan", stun.*.*.*, stun.*.*, time.windows.com, time.nist.gov, time.apple.com, time.asia.apple.com, "*.ntp.org.cn", "*.openwrt.pool.ntp.org", time1.cloud.tencent.com, time.ustc.edu.cn, pool.ntp.org, ntp.ubuntu.com, "*.*.xboxlive.com", speedtest.cros.wr.pvp.net]
  nameserver: [tls://223.5.5.5:853, https://223.6.6.6/dns-query, https://120.53.53.53/dns-query]
  nameserver-policy: {+.tmall.com: 223.5.5.5, +.taobao.com: 223.5.5.5, +.alicdn.com: 223.5.5.5, +.aliyun.com: 223.5.5.5, +.alipay.com: 223.5.5.5, +.alibaba.com: 223.5.5.5, +.qq.com: 119.29.29.29, +.tencent.com: 119.29.29.29, +.weixin.com: 119.29.29.29, +.qpic.cn: 119.29.29.29, +.jd.com: 119.29.29.29, +.bilibili.com: 119.29.29.29, +.hdslb.com: 119.29.29.29, +.163.com: 119.29.29.29, +.126.com: 119.29.29.29, +.126.net: 119.29.29.29, +.127.net: 119.29.29.29, +.netease.com: 119.29.29.29, +.baidu.com: 223.5.5.5, +.bdstatic.com: 223.5.5.5, +.bilivideo.+: 119.29.29.29, +.iqiyi.com: 119.29.29.29, +.douyinvod.com: 180.184.1.1, +.douyin.com: 180.184.1.1, +.douyincdn.com: 180.184.1.1, +.douyinpic.com: 180.184.1.1, +.feishu.cn: 180.184.1.1}
  fallback: [tls://101.101.101.101:853,https://101.101.101.101/dns-query, https://public.dns.iij.jp/dns-query, https://208.67.220.220/dns-query]
  fallback-filter: {geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32, 127.0.0.1/32], domain: [+.google.com, +.facebook.com, +.twitter.com, +.youtube.com, +.xn--ngstr-lra8j.com, +.google.cn, +.googleapis.cn, +.googleapis.com, +.gvt1.com, +.paoluz.com, +.paoluz.link, +.paoluz.xyz, +.sodacity-funk.xyz, +.nloli.xyz,+.jsdelivr.net, +.proton.me]}
hosts:
  'challenges.cloudflare.com': 104.22.51.225
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
proxies:
省略
proxy-providers:
省略
proxy-groups:
省略
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - DIRECT
  - name: 直连IPV4
    type: select
    ip-version: ipv4
    proxies:
      - DIRECT
rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400
rules:
省略
## Cloudflare IP&ASN
  - 'IP-CIDR,173.245.48.0/20,直连IPV4'
  - 'IP-CIDR,103.21.244.0/22,直连IPV4'
  - 'IP-CIDR,103.22.200.0/22,直连IPV4'
  - 'IP-CIDR,103.31.4.0/22,直连IPV4'
  - 'IP-CIDR,141.101.64.0/18,直连IPV4'
  - 'IP-CIDR,108.162.192.0/18,直连IPV4'
  - 'IP-CIDR,190.93.240.0/20,直连IPV4'
  - 'IP-CIDR,188.114.96.0/20,直连IPV4'
  - 'IP-CIDR,197.234.240.0/22,直连IPV4'
  - 'IP-CIDR,198.41.128.0/17,直连IPV4'
  - 'IP-CIDR,162.158.0.0/15,直连IPV4'
  - 'IP-CIDR,104.16.0.0/13,直连IPV4'
  - 'IP-CIDR,104.24.0.0/14,直连IPV4'
  - 'IP-CIDR,172.64.0.0/13,直连IPV4'
  - 'IP-CIDR,131.0.72.0/22,直连IPV4'
  - 'IP-CIDR6,2400:cb00::/32,🐟 漏网之鱼'
  - 'IP-CIDR6,2606:4700::/32,🐟 漏网之鱼'
  - 'IP-CIDR6,2803:f800::/32,🐟 漏网之鱼'
  - 'IP-CIDR6,2405:b500::/32,🐟 漏网之鱼'
  - 'IP-CIDR6,2405:8100::/32,🐟 漏网之鱼'
  - 'IP-CIDR6,2a06:98c0::/29,🐟 漏网之鱼'
  - 'IP-CIDR6,2c0f:f248::/32,🐟 漏网之鱼'
  - 'IP-ASN,13335,🐟 漏网之鱼'
# 外部规则
  - 'RULE-SET,applications,🐟 漏网之鱼'
  - 'RULE-SET,private,🐟 漏网之鱼'
  - 'RULE-SET,reject,REJECT'
  - 'RULE-SET,icloud,🐟 漏网之鱼'
  - 'RULE-SET,apple,🐟 漏网之鱼'
  - 'RULE-SET,google,🚀 节点选择'
  - 'RULE-SET,proxy,🚀 节点选择'
  - 'RULE-SET,direct,🐟 漏网之鱼'
  - 'RULE-SET,lancidr,🐟 漏网之鱼'
  - 'RULE-SET,cncidr,🐟 漏网之鱼'
  - 'RULE-SET,telegramcidr,🚀 节点选择'
  - 'GEOIP,LAN,🐟 漏网之鱼'
  - 'GEOIP,CN,🐟 漏网之鱼'
  - 'IP-CIDR6,::/0,🐟 漏网之鱼' # 所有ipv6都走直连
  - 'MATCH,🚀 节点选择'
```

多次CURL日志，只有一次成功访问

```

root in /tmp 
❯ curl --verbose "https://www.baidu.com"
* Uses proxy env variable https_proxy == 'http://aaa:bbb@go.ccc.com:54321'*   Trying 183.x.x.x:54321...
* Connected to (nil) (183.x.x.x) port 54321 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.baidu.com:443
* Proxy auth using Basic with user 'aaa'
> CONNECT www.baidu.com:443 HTTP/1.1
> Host: www.baidu.com:443
> Proxy-Authorization: Basic xxxxx
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to www.baidu.com:443 
* Closing connection 0
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.baidu.com:443 




root in /tmp 
❯ curl --verbose "https://www.baidu.com"
* Uses proxy env variable https_proxy == 'http://aaa:bbb@go.ccc.com:54321'*   Trying 183.x.x.x:54321...
* Connected to (nil) (183.x.x.x) port 54321 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.baidu.com:443
* Proxy auth using Basic with user 'aaa'
> CONNECT www.baidu.com:443 HTTP/1.1
> Host: www.baidu.com:443
> Proxy-Authorization: Basic xxxxx
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to www.baidu.com:443 
* Closing connection 0
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.baidu.com:443 




root in /tmp 
❯ curl --verbose "https://www.baidu.com"
* Uses proxy env variable https_proxy == 'http://aaa:bbb@go.ccc.com:54321'*   Trying 183.x.x.x:54321...
* Connected to (nil) (183.x.x.x) port 54321 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.baidu.com:443
* Proxy auth using Basic with user 'aaa'
> CONNECT www.baidu.com:443 HTTP/1.1
> Host: www.baidu.com:443
> Proxy-Authorization: Basic xxxxx
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to www.baidu.com:443 
* Closing connection 0
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.baidu.com:443 




root in /tmp 
❯ curl --verbose "https://www.baidu.com"
* Uses proxy env variable https_proxy == 'http://aaa:bbb@go.ccc.com:54321'*   Trying 183.x.x.x:54321...
* Connected to (nil) (183.x.x.x) port 54321 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.baidu.com:443
* Proxy auth using Basic with user 'aaa'
> CONNECT www.baidu.com:443 HTTP/1.1
> Host: www.baidu.com:443
> Proxy-Authorization: Basic xxxxx
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
> 
* Recv failure: Connection reset by peer
* Received HTTP code 0 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer




root in /tmp 
❯ curl --verbose "https://www.baidu.com"
* Uses proxy env variable https_proxy == 'http://aaa:bbb@go.ccc.com:54321'*   Trying 183.x.x.x:54321...
* Connected to (nil) (183.x.x.x) port 54321 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.baidu.com:443
* Proxy auth using Basic with user 'aaa'
> CONNECT www.baidu.com:443 HTTP/1.1
> Host: www.baidu.com:443
> Proxy-Authorization: Basic xxxxx
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to www.baidu.com:443 
* Closing connection 0
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.baidu.com:443 




root in /tmp 
❯ curl --verbose "https://www.baidu.com"
* Uses proxy env variable https_proxy == 'http://aaa:bbb@go.ccc.com:54321'*   Trying 183.x.x.x:54321...
* Connected to (nil) (183.x.x.x) port 54321 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.baidu.com:443
* Proxy auth using Basic with user 'aaa'
> CONNECT www.baidu.com:443 HTTP/1.1
> Host: www.baidu.com:443
> Proxy-Authorization: Basic xxxxx
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to www.baidu.com:443 
* Closing connection 0
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.baidu.com:443 




root in /tmp 
❯ curl --verbose "https://www.baidu.com"
* Uses proxy env variable https_proxy == 'http://aaa:bbb@go.ccc.com:54321'*   Trying 183.x.x.x:54321...
* Connected to (nil) (183.x.x.x) port 54321 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.baidu.com:443
* Proxy auth using Basic with user 'aaa'
> CONNECT www.baidu.com:443 HTTP/1.1
> Host: www.baidu.com:443
> Proxy-Authorization: Basic xxxxx
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
> 
* Recv failure: Connection reset by peer
* Received HTTP code 0 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer




root in /tmp 
❯ curl --verbose "https://www.baidu.com"
* Uses proxy env variable https_proxy == 'http://aaa:bbb@go.ccc.com:54321'*   Trying 183.x.x.x:54321...
* Connected to (nil) (183.x.x.x) port 54321 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.baidu.com:443
* Proxy auth using Basic with user 'aaa'
> CONNECT www.baidu.com:443 HTTP/1.1
> Host: www.baidu.com:443
> Proxy-Authorization: Basic xxxxx
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to www.baidu.com:443 
* Closing connection 0
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.baidu.com:443 



root in /tmp 
❯ curl --verbose "https://www.baidu.com"
* Uses proxy env variable https_proxy == 'http://aaa:bbb@go.ccc.com:54321'*   Trying 183.x.x.x:54321...
* Connected to (nil) (183.x.x.x) port 54321 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.baidu.com:443
* Proxy auth using Basic with user 'aaa'
> CONNECT www.baidu.com:443 HTTP/1.1
> Host: www.baidu.com:443
> Proxy-Authorization: Basic xxxxx
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=CN; ST=beijing; L=beijing; O=Beijing Baidu Netcom Science Technology Co., Ltd; CN=baidu.com
*  start date: Jul  8 01:41:02 2024 GMT
*  expire date: Aug  9 01:41:01 2025 GMT
*  subjectAltName: host "www.baidu.com" matched cert's "*.baidu.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign RSA OV SSL CA 2018
*  SSL certificate verify ok.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET / HTTP/1.1
> Host: www.baidu.com
> User-Agent: curl/7.81.0
> Accept: */*
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Cache-Control: no-cache
< Connection: keep-alive
< Content-Length: 227
< Content-Security-Policy: frame-ancestors 'self' https://chat.baidu.com http://mirror-chat.baidu.com https://fj-chat.baidu.com https://hba-chat.baidu.com https://hbe-chat.baidu.com https://njjs-chat.baidu.com https://nj-chat.baidu.com https://hna-chat.baidu.com https://hnb-chat.baidu.com http://debug.baidu-int.com;
< Content-Type: text/html
< Date: Sun, 16 Feb 2025 09:20:44 GMT
< Pragma: no-cache
< Server: BWS/1.1
< Set-Cookie: BD_NOT_HTTPS=1; path=/; Max-Age=300
< Set-Cookie: PSTM=1739697644; expires=Thu, 31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; domain=.baidu.com
< Set-Cookie: H_PS_PSSID=61027_61986_62054_62066_62113_62131_62159_62168_62176_62185_62186_62181_62195; path=/; expires=Mon, 16-Feb-26 09:20:44 GMT; domain=.baidu.com
< Set-Cookie: BAIDUID=5DF38DD5CBFB3DC14D8090C7ACC4DF8B:FG=1; Path=/; Domain=baidu.com; Max-Age=31536000
< Set-Cookie: BAIDUID_BFESS=5DF38DD5CBFB3DC14D8090C7ACC4DF8B:FG=1; Path=/; Domain=baidu.com; Max-Age=31536000; Secure; SameSite=None
< Traceid: 1739697644062381671415592648476291405722
< X-Ua-Compatible: IE=Edge,chrome=1
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< X-Xss-Protection: 1;mode=block
< 
<html>
<head>
        <script>
                location.replace(location.href.replace("https://","http://"));
        </script>
</head>
<body>
        <noscript><meta http-equiv="refresh" content="0;url=http://www.baidu.com/"></noscript></body>
* Connection #0 to host (nil) left intact
</html>⏎                                                                        
```

通过MetacubeXD查看日志，看到的error只有这些：

```
18491 | [error] | [Sniffer] [104.21.48.1] [tls] may not have any sent data, Consider adding skip
18484 | [error] | [Sniffer] [172.67.136.195] [tls] may not have any sent data, Consider adding skip
18481 | [error] | [Sniffer] [104.21.48.1] [tls] may not have any sent data, Consider adding skip
18479 | [error] | [Sniffer] [198.251.89.85] [tls] may not have any sent data, Consider adding skip
18472 | [error] | [Sniffer] [104.21.65.34] [tls] may not have any sent data, Consider adding skip
18465 | [error] | [Sniffer] [104.21.39.77] [tls] may not have any sent data, Consider adding skip
18453 | [error] | [Sniffer] [104.21.86.131] [tls] may not have any sent data, Consider adding skip
18452 | [error] | [Sniffer] [104.21.48.1] [tls] may not have any sent data, Consider adding skip
18443 | [error] | [Sniffer] [172.67.136.195] [tls] may not have any sent data, Consider adding skip
18442 | [error] | [Sniffer] [104.21.112.1] [tls] may not have any sent data, Consider adding skip
18441 | [error] | [Sniffer] [104.21.48.1] [tls] may not have any sent data, Consider adding skip
18432 | [error] | [Sniffer] [104.21.39.77] [tls] may not have any sent data, Consider adding skip
18425 | [error] | [Sniffer] [104.21.112.1] [tls] may not have any sent data, Consider adding skip
18424 | [error] | [Sniffer] [104.21.39.77] [tls] may not have any sent data, Consider adding skip
18414 | [error] | [Sniffer] [104.21.39.77] [tls] may not have any sent data, Consider adding skip
18410 | [error] | [Sniffer] [104.21.48.1] [tls] may not have any sent data, Consider adding skip
18398 | [error] | [Sniffer] [104.21.48.1] [tls] may not have any sent data, Consider adding skip
18392 | [error] | [Sniffer] [104.21.49.206] [tls] may not have any sent data, Consider adding skip
18383 | [error] | [Sniffer] [172.67.136.195] [tls] may not have any sent data, Consider adding skip
18373 | [error] | [Sniffer] [104.21.39.77] [tls] may not have any sent data, Consider adding skip
18369 | [error] | [Sniffer] [104.21.48.1] [tls] may not have any sent data, Consider adding skip
18367 | [error] | [Sniffer] [188.114.96.12] [tls] may not have any sent data, Consider adding skip
18356 | [error] | [Sniffer] [172.67.179.26] [tls] may not have any sent data, Consider adding skip
18355 | [error] | [Sniffer] [172.67.136.195] [tls] may not have any sent data, Consider adding skip
18348 | [error] | [Sniffer] [188.114.96.12] [tls] may not have any sent data, Consider adding skip
18343 | [error] | [Sniffer] [104.21.39.77] [tls] may not have any sent data, Consider adding skip
18340 | [error] | [Sniffer] [172.67.136.195] [tls] may not have any sent data, Consider adding skip
18326 | [error] | [Sniffer] [172.67.41.40] [tls] may not have any sent data, Consider adding skip
18322 | [error] | [Sniffer] [104.21.48.1] [tls] may not have any sent data, Consider adding skip
18304 | [error] | [Sniffer] [104.21.96.1] [tls] may not have any sent data, Consider adding skip
18301 | [error] | [Sniffer] [104.21.48.1] [tls] may not have any sent data, Consider adding skip
18296 | [error] | [Sniffer] [172.67.137.109] [tls] may not have any sent data, Consider adding skip
18397 | [warning] | [TCP] dial 直连IPV4 (match IPCIDR/172.64.0.0/13) 114.x.x.x:43410 --> 172.67.41.40:443 error: connect failed: dial tcp 172.67.41.40:443: i/o timeout
