### DISCUSSION TITLE
[HELP] WireGuard doesn’t reconnect after proxy dialer reconnects

### DISCUSSION THREAD

**Discussion by zzzt27** [MetaCubeX/mihomo#1856] [Q&A]
I have a setup where WireGuard is using my-proxy-dialer as its dialer.

- When my-proxy-dialer disconnects, WireGuard also stops working (which is expected).
 
- After my-proxy-dialer reconnects, its status shows as connected.
 
- However, WireGuard does not automatically reconnect. It only works again if I manually stop/kill the process and restart it.

example my config:

```
- name: "cf wrap"
  type: wireguard
  private-key: "xxxxxxx"
  server: engage.cloudflareclient.com
  port: 2408
  ip: 172.16.0.2
  ipv6: 2606:4700:110:8f68:10e9:c2c4:8d0b:3580
  public-key: "xxxxxxx"
  allowed-ips:
    - "0.0.0.0/0"
    - "::/0"
  udp: true
  dns:
    - "1.1.1.1"
    - "1.0.0.1"
    - "[2606:4700:4700::1111]"
    - "[2606:4700:4700::1001]"
  mtu: 1280
  dialer-proxy: my-proxy-dialer
  
- name: my-proxy-dialer
  type: direct
  udp: true
```

Is there a way to make WireGuard reconnect automatically when my-proxy-dialer comes back online? Or is this bug?

Notes: WG from Cloudflare WARP.

Thanks!
