### DISCUSSION TITLE
fake ip模式下可能会导致steam下载走新加坡

### DISCUSSION THREAD

**Discussion by RichardLuo0** [MetaCubeX/mihomo#1858] [General]
https://github.com/clash-verge-rev/clash-verge-rev/issues/2737
```yml
dns:
  fake-ip-filter:
    - "lancache.steamcontent.com"
```
可以解决

但是很多用户也许并不清楚这种设置，也许一个比较合适的办法是，增加一个单独的选项：对于匹配到直连规则的域名，就返回真实的ip。然后在gui中提供该选项？
