### DISCUSSION TITLE
为什么会使用他们解析

### DISCUSSION THREAD

**Discussion by yiteei** [MetaCubeX/mihomo#1901] [Q&A]
```yaml
dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  default-nameserver: [ '180.184.2.2', '223.6.6.6', '4.2.2.2' ]
  proxy-server-nameserver: [ 'https://223.5.5.5/dns-query#ecs=202.197.96.0/24&ecs-override=true', 'https://doh.pub/dns-query#ecs=202.197.96.0/24&ecs-override=true' ]
  nameserver: [ 'https://208.67.220.2/dns-query#ecs=202.197.96.0/24&ecs-override=true&Proxy', 'https://8.8.4.4/dns-query#ecs=202.197.96.0/24&ecs-override=true&Proxy' ]
  direct-nameserver: [ 'https://223.6.6.6/dns-query#&ecs=202.197.96.0/24&ecs-override=true', 'https://doh.pub/dns-query#ecs=202.197.96.0/24&ecs-override=true' ]

rules:
- 'DST-PORT,53,dns-hijack'
- 'OR,((RULE-SET,site_private),(RULE-SET,ip_private,no-resolve)),Local'
- 'OR,((RULE-SET,site_category-httpdns-cn),(DOMAIN-REGEX,(?i:httpdns|httpsdns))),Httpdns'
- 'RULE-SET,site_dns-blocklists-normal,Advert'
- 'AND,((NETWORK,udp),(DOMAIN-REGEX,(?i:stun|turn))),WebRTC'
- 'AND,((DST-PORT,5228-5230),(RULE-SET,site_googlefcm)),Message'
- 'OR,((DOMAIN-REGEX,.*\.(mcdn|pcdn)\.(bilivideo|bilibili)\.(com|cn)),(DOMAIN-REGEX,cn-.*\.(bilivideo|bilibili)\.(com|cn))),BiliCDN'
- 'OR,((RULE-SET,site_telegram),(RULE-SET,ip_telegram,no-resolve)),Telegram'
- 'RULE-SET,site_wechat,WeChat'
- 'DOMAIN,wetype.weixin.qq.com,REJECT'
- 'RULE-SET,site_category-games@cn,GameCN'
- 'RULE-SET,site_category-ai-cn,LLMCN'
- 'RULE-SET,site_youtube,YouTube'
- 'OR,((RULE-SET,site_adobe),(RULE-SET,site_autodesk)),REJECT'
- 'RULE-SET,site_onedrive,OneDrive'
- 'RULE-SET,site_gfw,Proxy'
- 'RULE-SET,site_geolocation-!cn,Proxy'
- 'RULE-SET,site_cn,Local'
- 'RULE-SET,ip_cn,Local'
- 'MATCH,Proxy'
```
![image](https://github.com/user-attachments/assets/a9b78064-dc17-4a5a-b3ac-9df59766fa16)
