### DISCUSSION TITLE
direct-nameserver 字段似乎并没有正常生效？

### DISCUSSION THREAD

**Discussion by xixi-furry** [MetaCubeX/mihomo#1924] [Q&A]
我的DNS相关配置：
```
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  respect-rules: true
  fake-ip-filter-mode: blacklist
  nameserver:
  - tls://1.1.1.1
  - tls://8.8.8.8
  proxy-server-nameserver:
  - 211.137.58.x
  - 211.137.64.x
  direct-nameserver:
  - 211.137.58.x
  - 211.137.64.x
  nameserver-policy:
    _vlmcs._tcp.lan: 127.0.0.1:53
    geosite:category-games@cn:
    - https://doh.pub/dns-query
    - 114.114.114.114
    - 223.5.5.5
    geosite:google:
    - tls://8.8.4.4
    - https://1.0.0.1/dns-query
    geosite:cn,apple,private:
    - 211.137.58.X
    - 211.137.64.X
    - https://doh.pub/dns-query
  use-hosts: true
  default-nameserver:
  - 211.137.58.X
  - 211.137.64.X
```

以下是我的额外增加的rules的部分：
```
rules:
## STEAMCN 直连
- DOMAIN,steamcdn-a.akamaihd.net,DIRECT
- DOMAIN-SUFFIX,cm.steampowered.com,DIRECT
- DOMAIN-SUFFIX,steamserver.net,DIRECT
```

在日志里查看，DIRECT似乎都没有按照我指定的direct-nameserver在请求，反而还是默认的nameserver，证据如下：
![image](https://github.com/user-attachments/assets/f0467e86-5712-4680-a6e4-6e6d325e85bd)
![image](https://github.com/user-attachments/assets/9356e563-d4ed-4a07-ad10-76abc4d3983b)

规则也是生效的:
![image](https://github.com/user-attachments/assets/28c1b7eb-6f7c-40b7-b0e6-19ab1cb23a1f)

自己研究了一下还是没找到解决办法，恳请各位大佬帮忙看看（
