### DISCUSSION TITLE
Epic Games 下载非常慢

### DISCUSSION THREAD

**Discussion by yueisme** [MetaCubeX/mihomo#1955] [General]
使用 mihomo 代理时 Epic Games 下载速度很慢，跑不满带宽，关闭 mihomo 的速度是正常的，这是什么原因？

代理后的速度很慢：
![下载管理器 2025-04-03 00_59_26](https://github.com/user-attachments/assets/ec5e5f9a-37bf-4963-8150-ffab48af0869)

测试的 config ，系统的代理设置也确认过，用`mode: direct`也一样：

```yaml
mode: rule
mixed-port: 7892
log-level: debug
ipv6: false
dns:
  enable: false
sniffer:
  enable: false
tun:
  enable: false
geodata-mode: true
geodata-loader: standard
rules:
- GEOSITE,private,DIRECT
- GEOSITE,cn,DIRECT
- GEOIP,private,DIRECT,no-resolve
- GEOIP,CN,DIRECT
- MATCH,DIRECT
```

内核版本：`Mihomo Meta v1.19.4 windows amd64 with go1.24.1 Tue Apr  1 14:37:26 UTC 2025`
