### DISCUSSION TITLE
Mijia Cloud:443 error: dns resolve failed: couldn't find ip

### DISCUSSION THREAD

**Discussion by SlippinDylan** [MetaCubeX/mihomo#1994] [General]
我最近在使用mihomo的时候遇到了点问题
首先我家里有很多米家的设备，本人电脑是Mac，Mac上跑的mihomo party，家里的openwrt是24.10版本跑的最新版本的OpenWrt-nikki，同时采用fake-ip的模式，只有主路由，无旁路由，所有流量通过 openwrt 出入站

1. 问题场景一：当我在外，通过 tailscale 远程连接到家里的时候（tailscale 是部署在家里的 debian 里面的），家里的所有米家设备全都会遇到掉线的情况，查看 mihomo 的日志会发现“Mijia Cloud:443 error: dns resolve failed: couldn't find ip”的报错
2. 问题场景二：当我回到家的时候，我写了一个简单的脚本，通过 ARP 查询看当前的局域网是否是 openwrt 的 Mac，是的话会自动退出 Mac 上的mihomo party，通过 openwrt 上的 mihomo 进行🪜，但是我同样会遇到家里的所有米家设备全都会遇到掉线的情况，查看 mihomo 的日志也会发现“Mijia Cloud:443 error: dns resolve failed: couldn't find ip”的报错
3. Mac 上的mihomo party和openwrt上的OpenWrt-nikki，使用的配置文件都是一样的

> 为了处理我遇到的这个问题，在嗅探的时候，我将很多小米的域名都禁止嗅探了，dns 的 fake-ip 我也是将很多小米的域名指定了 dns 服务器，但是仍然会遇到这种我问题，下面分别是我的 mihomo 的配置文件中的部分内容和 mihomo 的日志，我现在是在没什么办法解决这个问题了，我想知道有没有大神知道这个问题咋解决，非常感谢

```
proxy-providers:
  Pander:
    url: "订阅链接"
    type: http
    interval: 14400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      lazy: false
      tolerance: 50
    proxy: 直连节点
    header:
      User-Agent: ["Clash", "mihomo", "Clash.meta"]
    override:
      udp: true
      skip-cert-verify: true

proxies:
  - {name: 直连节点, type: direct, udp: true}

port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: true
unified-delay: true
tcp-concurrent: true
log-level: debug
mode: rule

find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
disable-keep-alive: false
profile:
  store-selected: true
  store-fake-ip: true
  tracing: true
  interval: 14400

sniffer:
  enable: true
  sniff:
    HTTP: {ports: [80, 8080-8880], override-destination: true}
    TLS: {ports: [443, 8443]}
    QUIC: {ports: [443, 8443]}
  force-domain: ["+.v2ex.com"]
  skip-domain: [
    "rule-set:private_domain,xiaomi_domain,cn_domain", "dlg.io.mi.com", 
    "+.push.apple.com", "+.apple.com", "+.wechat.com", 
    "+.qpic.cn", "+.qq.com", "+.wechatapp.com", 
    "+.vivox.com", "+.oray.com", "+.sunlogin.net", 
    "+.msftconnecttest.com", "+.msftncsi.com", "+.mi.com", 
    "*.mi.com", "io.mi.com", "+.io.mi.com", "+.ot.io.mi.com", 
    "ot.io.mi.com", "ha.mqtt.io.mi.com", "+.xiaomi.com", 
    "+.mijia.com", "+.mi-img.com", "+.miui.com", "dev.mi.com", 
    "home.mi.com", "open.account.xiaomi.com", "+.mqtt.io.mi.com", 
    "+.fds.api.mi-img.com", "+.sec.miui.com", "font.sec.miui.com", 
    "*.mqtt.io.mi.com", "*.fds.api.mi-img.com", "*.sec.miui.com"
  ]

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  respect-rules: true
  enable-dnssec: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "rule-set:private_domain,xiaomi_domain"
    - "+.services.googleapis.cn"
    - "+.xn--ngstr-lra8j.com"
    - "+.ntp.tencent.com"
    - "+.ntp1.aliyun.com"
    - "time.*.com"
    - "+.ntp.ntsc.ac.cn"
    - "+.pool.ntp.org"
    - "+.cn.ntp.org.cn"
    # 小米相关
    - "+.mi.com"
    - "*.mi.com"
    - "io.mi.com"
    - "+.io.mi.com"
    - "+.ot.io.mi.com"
    - "ot.io.mi.com"
    - "ha.mqtt.io.mi.com"
    - "+.xiaomi.com"
    - "+.mijia.com"
    - "+.mi-img.com"
    - "+.miui.com"
    - "dev.mi.com"
    - "home.mi.com"
    - "open.account.xiaomi.com"
    - "+.mqtt.io.mi.com"
    - "+.fds.api.mi-img.com"
    - "+.sec.miui.com"
    - "font.sec.miui.com"
    - "*.mqtt.io.mi.com"
    - "*.fds.api.mi-img.com"
    - "*.sec.miui.com"
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - '2400:3200::1'
    - '2402:4e00::'
  proxy-server-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - '2400:3200::1'
    - '2402:4e00::'
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - '2400:3200::1'
    - '2402:4e00::'
  nameserver-policy:
    "+.mi.com": [223.5.5.5, 119.29.29.29]
    "*.mi.com": [223.5.5.5, 119.29.29.29]
    "io.mi.com": [223.5.5.5, 119.29.29.29]
    "+.io.mi.com": [223.5.5.5, 119.29.29.29]
    "+.ot.io.mi.com": [223.5.5.5, 119.29.29.29]
    "ot.io.mi.com": [223.5.5.5, 119.29.29.29]
    "ha.mqtt.io.mi.com": [223.5.5.5, 119.29.29.29]
    "+.xiaomi.com": [223.5.5.5, 119.29.29.29]
    "+.mijia.com": [223.5.5.5, 119.29.29.29]
    "+.mi-img.com": [223.5.5.5, 119.29.29.29]
    "+.miui.com": [223.5.5.5, 119.29.29.29]
    "dev.mi.com": [223.5.5.5, 119.29.29.29]
    "home.mi.com": [223.5.5.5, 119.29.29.29]
    "open.account.xiaomi.com": [223.5.5.5, 119.29.29.29]
    "+.mqtt.io.mi.com": [223.5.5.5, 119.29.29.29]
    "+.fds.api.mi-img.com": [223.5.5.5, 119.29.29.29]
    "+.sec.miui.com": [223.5.5.5, 119.29.29.29]
    "font.sec.miui.com": [223.5.5.5, 119.29.29.29]
    "*.mqtt.io.mi.com": [223.5.5.5, 119.29.29.29]
    "*.fds.api.mi-img.com": [223.5.5.5, 119.29.29.29]
    "*.sec.miui.com": [223.5.5.5, 119.29.29.29]
``` 

```
time="2025-04-25T09:38:41.519198649Z" level=debug msg="[Sniffer] Sniff tcp [10.10.1.142:64697]-->[120.52.181.243:443] success, replace domain []-->[Mijia Cloud]"
time="2025-04-25T09:38:41.519255311Z" level=debug msg="[Rule] use default rules"
time="2025-04-25T09:38:41.519354249Z" level=debug msg="[DNS] cache hit Mijia Cloud --> [] A, expire at 2025-04-25 10:38:38"
time="2025-04-25T09:38:41.519386874Z" level=debug msg="[DNS] cache hit Mijia Cloud --> [] AAAA, expire at 2025-04-25 10:38:38"
time="2025-04-25T09:38:41.519421392Z" level=warning msg="[TCP] dial 🚥 直连访问 (match RuleSet/cn_ip) 10.10.1.142:64697 --> Mijia Cloud:443 error: dns resolve failed: couldn't find ip"
time="2025-04-25T09:38:42.028406154Z" level=debug msg="[Sniffer] Sniff tcp [10.10.1.67:50261]-->[120.52.181.243:443] success, replace domain []-->[Mijia Cloud]"
time="2025-04-25T09:38:42.028460595Z" level=debug msg="[Rule] use default rules"
time="2025-04-25T09:38:42.028585028Z" level=debug msg="[DNS] cache hit Mijia Cloud --> [] A, expire at 2025-04-25 10:38:38"
time="2025-04-25T09:38:42.028623570Z" level=debug msg="[DNS] cache hit Mijia Cloud --> [] AAAA, expire at 2025-04-25 10:38:38"
time="2025-04-25T09:38:42.028666349Z" level=warning msg="[TCP] dial 🚥 直连访问 (match RuleSet/cn_ip) 10.10.1.67:50261 --> Mijia Cloud:443 error: dns resolve failed: couldn't find ip"
time="2025-04-25T09:38:43.055164953Z" level=debug msg="[Sniffer] Sniff tcp [10.10.1.67:50262]-->[120.92.65.240:443] success, replace domain []-->[Mijia Cloud]"
time="2025-04-25T09:38:43.055208336Z" level=debug msg="[Rule] use default rules"
time="2025-04-25T09:38:43.055298239Z" level=debug msg="[DNS] cache hit Mijia Cloud --> [] A, expire at 2025-04-25 10:38:38"
time="2025-04-25T09:38:43.055331642Z" level=debug msg="[DNS] cache hit Mijia Cloud --> [] AAAA, expire at 2025-04-25 10:38:38"
time="2025-04-25T09:38:43.055354863Z" level=warning msg="[TCP] dial 🚥 直连访问 (match RuleSet/cn_ip) 10.10.1.67:50262 --> Mijia Cloud:443 error: dns resolve failed: couldn't find ip"
time="2025-04-25T09:38:43.353767274Z" level=debug msg="[Sniffer] Sniff tcp [10.10.1.32:4924]-->[120.52.181.243:443] success, replace domain []-->[Mijia Cloud]"
time="2025-04-25T09:38:43.353814498Z" level=debug msg="[Rule] use default rules"
time="2025-04-25T09:38:43.353908023Z" level=debug msg="[DNS] cache hit Mijia Cloud --> [] A, expire at 2025-04-25 10:38:38"
time="2025-04-25T09:38:43.353941461Z" level=debug msg="[DNS] cache hit Mijia Cloud --> [] AAAA, expire at 2025-04-25 10:38:38"
time="2025-04-25T09:38:43.353973775Z" level=warning msg="[TCP] dial 🚥 直连访问 (match RuleSet/cn_ip) 10.10.1.32:4924 --> Mijia Cloud:443 error: dns resolve failed: couldn't find ip"
time="2025-04-25T09:38:44.478692974Z" level=debug msg="[Sniffer] Sniff tcp [10.10.1.41:2155]-->[120.52.181.243:443] success, replace domain []-->[Mijia Cloud]"
time="2025-04-25T09:38:44.478739142Z" level=debug msg="[Rule] use default rules"
time="2025-04-25T09:38:44.478830717Z" level=debug msg="[DNS] cache hit Mijia Cloud --> [] A, expire at 2025-04-25 10:38:38"
time="2025-04-25T09:38:44.478861697Z" level=debug msg="[DNS] cache hit Mijia Cloud --> [] AAAA, expire at 2025-04-25 10:38:38"
time="2025-04-25T09:38:44.478895393Z" level=warning msg="[TCP] dial 🚥 直连访问 (match RuleSet/cn_ip) 10.10.1.41:2155 --> Mijia Cloud:443 error: dns resolve failed: couldn't find ip"

```

**Comment by Plutonium141** [comment]
像文档里一样，直接将 `Mijia Cloud` 添加到 sniffer.skip-domain:
https://wiki.metacubex.one/config/sniff/

**Reply by hubo502** [reply]
哇靠困扰我好久的问题，终于是靠这个解决了= =

**Comment by iKira** [comment]
这个问题前不久根治了，告诉你解决方法。

------------------------------------------

1、首先，OpenWrt按下面设置：

网络 > 防火墙 > 启用 FullCone NAT > 兼容模式（一定要兼容模式）
网络 > Turbo ACC 网络加速 > 快速转发引擎 > 禁用
网络 > Turbo ACC 网络加速 > 全锥形 NAT1 > 兼容模式

很多人OpenWrt里的NAT没设置对，以及打开了Flow offloading，这会导致udp流量异常，不经过代理内核，刚好不少米家设备会用udp连接（例如米家摄像头），这才是导致一些米家设备一直异常的根源。

------------------------------------------

2、mihomo配置文件，sniff配置如下，照着抄：
```
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports: [0-65535]
      override-destination: false
    TLS:
      ports: [0-65535]
      override-destination: false
    QUIC:
      ports: [0-65535]
      override-destination: false
  skip-domain:
    - 'Mijia Cloud'
```

------------------------------------------

3、mihomo配置文件，DNS配置如下，照着抄：
```
dns:
  enable: true
  ipv6: true
  prefer-h3: false
  respect-rules: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 'https://223.5.5.5/dns-query'
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: false
  fake-ip-filter:
    - '*.lan'
    - '+.windows.com'
    - '+.windowsupdate.com'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.nist.gov'
    - '+.mi.com'
    - '+.xiaomi.com'
    - '+.xiaomi.cn'
    - '+.xiaomi.net'
    - '+.xiaomiyoupin.com'
    - '+.mijia.tech'
    - '+.miot-spec.org'
    - '+.mi-img.com'
    - '+.miui.com'
  nameserver-policy:
    //这里自己按需配置
  nameserver:
    //这里自己按需配置
  proxy-server-nameserver:
    //这里自己按需配置
```
