### DISCUSSION TITLE
当系统没有ipv6的时候，ipv6的节点检测的时候会打印error日志

### DISCUSSION THREAD

**Discussion by minortex** [MetaCubeX/mihomo#2044] [Q&A]
这个问题是我在使用wireguard发现的。假如当前网络环境下没有ipv6，如果配置了纯ipv6的节点并且启用health-check，会导致日志里面一直报错。

配置文件：

```yaml
proxy-groups:
  - type: "url-test"
    name: "home"
    filter: "home"
    use:
      - "mywg"

proxy-providers:
  "mywg":
    type: file
    path: ./myconf/wg.yaml
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 300

# wg.yaml
proxies:
  - name: "endpoint-v6"
    type: wireguard
    private-key: xxxx
    server: AAAA-only.domain
    port: 4565
    ip: 10.0.0.3
    public-key: xxxx
    allowed-ips: ['10.0.0.0/24']
```

日志：
```
[WG](endpoint-v6) connect to server: connect failed: dial udp <ipv6_addr>:4565: connect: The requested address is not valid in its context.
```

会一直重复。

请问有什么办法规避吗？
