### DISCUSSION TITLE
关于启用系统代理模式下的入站流量问题

### DISCUSSION THREAD

**Discussion by TeacherLi07** [MetaCubeX/mihomo#2110] [Q&A]
使用Windows，刚刚从cfw+clash迁移到clash verge+mihomo，对于mihomo的设置还并不熟悉。

我机器有公网ipv6，在启动clash verge和内核，但不启动系统代理和tun的情况下，此地址可以被ping通。并且，如果我在本地启动监听tcp的一个服务并在Windows防火墙中放行，可以通过外部tcping建立tcp连接，IPv6 Port Checker也可以看到此端口。应该说，此时入站流量应该没有什么问题。

但是当我启动系统代理模式，此ipv6地址无法被ping通，所有端口也无法连接，就好像mihomo接管了整个机器的流量。但是我确定我没有启动tun，甚至并没有安装系统服务，ipconfig和任务管理器中也没有tunnel网卡。

在我使用原cfw+clash的配置时，似乎没有这样的问题，即是启用系统代理也能够正确暴露端口并接受v6公网连接。不知道是不是我配置有误？

完整配置如下，应该没有做什么特殊操作，节点略去：
```
mode: rule
redir-port: 7892
mixed-port: 7897
allow-lan: true
log-level: info
ipv6: true
external-controller: 127.0.0.1:9097
secret: set-your-secret
unified-delay: true
dns:
  enable: true
  listen: :53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  prefer-h3: false
  respect-rules: false
  use-hosts: false
  use-system-hosts: false
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.arpa'
  - time.*.com
  - ntp.*.com
  - time.*.com
  - +.market.xiaomi.com
  - localhost.ptlogin2.qq.com
  - '*.msftncsi.com'
  - www.msftconnecttest.com
  default-nameserver:
  - system
  - 223.6.6.6
  - 8.8.8.8
  nameserver:
  - 8.8.8.8
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback: []
  nameserver-policy: {}
  proxy-server-nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  - tls://223.5.5.5
  direct-nameserver: []
  direct-nameserver-follow-policy: false
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
    domain:
    - +.google.com
    - +.facebook.com
    - +.youtube.com
tun:
  enable: false
  stack: gvisor
  auto-route: true
  strict-route: false
  auto-detect-interface: true
  dns-hijack:
  - any:53
profile:
  store-selected: true
external-controller-cors:
  allow-private-network: true
  allow-origins:
  - tauri://localhost
  - http://tauri.localhost
  - https://yacd.metacubex.one
  - https://metacubex.github.io
  - https://board.zash.run.place
proxies:
<omitted>
proxy-groups:
- name: Proxy
  type: select
  proxies:
<omitted>
- name: 自动选择
  type: url-test
  proxies:
<omitted>
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
<omitted>
```
