### DISCUSSION TITLE
UDP流量会在本地发起DNS请求？

### DISCUSSION THREAD

**Discussion by Minhao-Geng** [MetaCubeX/mihomo#2139] [Q&A]
我所有的ip-rules都加了no-resolve，按理来说走节点的流量不会有本地dns请求，dns解析应该都是节点服务器完成。

只有cn的流量是本地解析。tcp这块倒是没问题，所有墙外流量都是代理解析dns，我昨天开了respect rules然后nameserver只写 
  - https://1.1.1.1/dns-query
  - https://8.8.8.8/dns-query。
direct nameserver 用阿里和腾讯公共dns，所以国内流量都是国内这俩dns解析。

问题出在我看log时发现cloudflare和google这两dns走了代理，说明一定有dns解析从本地发出，这个log后一条就是个udp流量，说明前面那个1.1.1.1的代理是为了获取这个udp流量的real ip。 这udp请求一定会在本地发起dns吗？我的兜底rule是走代理，所以不存在有不匹配的域名走直连。

我的配置如下·：
```
dns:
  default-nameserver:
  - https://223.6.6.6/dns-query
  - tls://223.5.5.5
  direct-nameserver:
  - https://223.5.5.5/dns-query
  - tls://223.6.6.6
  - https://doh.pub/dns-query
  - dot.pub
  direct-nameserver-follow-policy: false
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.arpa'
  - time.*.com
  - ntp.*.com
  - time.*.com
  - +.market.xiaomi.com
  - localhost.ptlogin2.qq.com
  - '*.msftncsi.com'
  - www.msftconnecttest.com
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fallback-filter:
    domain: []
    geoip: false
    geoip-code: CN
    ipcidr: []
  ipv6: false
  listen: :53
  nameserver:
  - https://1.1.1.1/dns-query
  - https://8.8.8.8/dns-query
  prefer-h3: true
  proxy-server-nameserver:
  - https://223.5.5.5/dns-query
  - tls://223.6.6.6
  - https://doh.pub/dns-query
  - dot.pub
  respect-rules: true
  use-hosts: false
  use-system-hosts: true
```
