### DISCUSSION TITLE
dns 劫持问题

### DISCUSSION THREAD

**Discussion by Miroxyz** [MetaCubeX/mihomo#377] [Q&A]
```
# Enable the TPROXY listener
tproxy-port: 9898

iptables:
  enable: true # default is false
  inbound-interface: eth0 # detect the inbound interface, default is 'lo'
```

开启了 iptables 但是没有配置 dns，启动是会报错。简单看了下代码发现好像是 tproxy iptables 规则劫持 dns 要用到 dns 的端口。

这里的 dns 劫持除了防止 dns 污染外还用别的用处吗？
目前是自建的防污 dns，clash meta 关闭了 dns 和 iptables，自己手动配置 iptables 规则实现 tproxy 的透明代理。

不知道这里的逻辑可不可以改成，如果没有配置 dns 的话，就不开启 dns 劫持相关的 iptables 规则
https://github.com/MetaCubeX/Clash.Meta/blob/Meta/listener/tproxy/tproxy_iptables.go
