### DISCUSSION TITLE
请问这是什么情况，url-test不会自动执行

### DISCUSSION THREAD

**Discussion by gg4924** [MetaCubeX/mihomo#495] [Q&A]
配置文件里的auto组类型为url-test，interval为300，但是它不会按照间隔时间自动执行，手动点击延迟测试按钮是可以的。
![Snipaste_2023-04-10_03-03-57](https://user-images.githubusercontent.com/21310130/230791703-4fa08254-6588-495a-bc2e-029520fbbff7.png)
我的使用方式是 核心 + 配置 + yacd-meta，其他使用都还好，就是url-test没有作用，我没有load-banlance、fallback等其他类型的分组，也没测试。

**Comment by gg4924** [comment]
难道是因为不是通过proxy-providers添加节点的原因吗，我看到有它下面有个health-check设置。我是自己写的脚本直接生成配置文件，proxy-providers我用过，但是有个订阅使用这个功能会出错，获取不了节点。

**Comment by gg4924** [comment]
目前通过proxy-providers的file方式解决问题了，通过脚本直接生成对应的文件到目录。
```yaml
proxy-providers:
  ef:
    type: file
    path: ./provider/ef.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: https://cp.cloudflare.com/generate_204
  djs:
    type: file
    path: ./provider/djs.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: https://cp.cloudflare.com/generate_204
  mf:
    type: file
    path: ./provider/mf.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: https://cp.cloudflare.com/generate_204
```
现在可以自动检测，正常选择了。
不过我还是很奇怪url-test这个类型为什么不会自动执行检测。
