### DISCUSSION TITLE
dns配置错误，应该如何修改

### DISCUSSION THREAD

**Discussion by fredericky123** [MetaCubeX/mihomo#506] [Q&A]
这是错误日志，如果关闭clash，本地网络能正常解析该域名，而开启clash，并利用的direc的规则后，导致无法正常解析了

错误日志：
`2023/04/15 16:15:42.975  [warning] [TCP] dial DIRECT (match DomainSuffix/wiley.com) 127.0.0.1:49901 --> onlinelibrary.wiley.com:443 error: connect failed: dial tcp 162.159.130.87:443: i/o timeout | dial tcp 162.159.129.87:443: i/o timeout | connect failed: dial tcp [2606:4700:7::a29f:8157]:443: connect: no route to host | dial tcp [2606:4700:7::a29f:8257]:443: connect: no route to host`

clash部分配置：
```
dns:
  enable: true # set true to enable dns (default is false)
  ipv6: true # default is false
  listen: 127.0.0.1:53
  default-nameserver: # resolve dns nameserver host, should fill pure IP
     - 223.5.5.5
     - 119.29.29.29
     - 114.114.114.114

  enhanced-mode: fake-ip #  # or fake-ip /redir-host
  fake-ip-range: 198.18.0.1/16 # if you don't know what it is, don't change it
  fake-ip-filter: # fake ip white domain list
     - '*.lan'
     - localhost.ptlogin2.qq.com
  nameserver:
       - 127.0.0.1
       - 101.7.8.9
       - 223.5.5.5
       - 114.114.114.114
       - 192.18.0.2
       - https://1.1.1.1/dns-query # dns over https
  fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
       - https://doh.pub/dns-query
       - 114.114.114.114
       - 1.1.1.1
       - 192.18.0.2
```
