### DISCUSSION TITLE
What is the difference between adding domain to fake-ip-filter vs DIRECT rule for that domain

### DISCUSSION THREAD

**Discussion by shvchk** [MetaCubeX/mihomo#628] [Q&A] [answered]
These seem to be two ways to do the same thing:

```yml
dns:
  # ...
  fake-ip-filter:
    - '*.lan'
```

```yml
rules:
  - DOMAIN-SUFFIX,lan,DIRECT
  # ...
```

What is the difference? Is one more performant than other?
