### DISCUSSION TITLE
配置文件中合并两个list（array）

### DISCUSSION THREAD

**Discussion by XinyuWuu** [MetaCubeX/mihomo#672] [Q&A]
希望的功能：
```yaml
some_stuff1: &some_stuff1
 - a
 - b
 - c
some_stuff2: &some_stuff2
 - g
 - h
 - i
combined_stuff:
  <<: *some_stuff1
  - d
  - e
  - f
  <<: *some_stuff2
 ```

stackoverflow上的讨论：
https://stackoverflow.com/questions/61639001/yaml-merge-multiple-arrays-into-one
https://stackoverflow.com/questions/24090177/how-to-merge-yaml-arrays
