### DISCUSSION TITLE
最新版的Mihomo，使用metatubexd作为UI，活动连接数居高不下，很多连接时长几天前的都还在，是不是我哪里设置不对？

### DISCUSSION THREAD

**Discussion by imshuai** [MetaCubeX/mihomo#920] [Q&A]
![image](https://github.com/MetaCubeX/mihomo/assets/15623716/81003a10-b8ad-45d8-98dc-721e6f7778f8)
## 关于keep-alive-interval  
我尝试过设置为15、60、300、3600以及关闭，都不能正常的断开连接
## 这是我的配置文件  
```yaml
mixed-port: 7890
allow-lan: true
bind-address: "192.168.4.4"
mode: rule
ipv6: true
external-controller: "127.0.0.1:9090"
interface-name: enxb827eb7678ab
geodata-mode: true
geodata-loader: memconservative
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
tcp-concurrent: true
#keep-alive-interval: 60
global-client-fingerprint: random
unified-delay: true #更换延迟计算方式,去除握手等额外延迟
profile:
  store-selected: true # 储存 API 对策略组的选择，以供下次启动时使用
  store-fake-ip: true # 储存 fakeip 映射表，域名再次发生连接时，使用原有映射地址
dns:
  enable: true
  prefer-h3: true
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  nameserver-policy:
    'geosite:cn': https://doh.pub/dns-query
    'geosite:gfw': [tls://8.8.4.4, https://1.0.0.1/dns-query]
    'rule-set:google,proxy': [tls://8.8.4.4, https://1.0.0.1/dns-query]
  nameserver:
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
    - https://doh.360.cn/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - tls://1.0.0.1:853
    - tls://dns.google:853
  proxy-server-nameserver:
    - https://doh.pub/dns-query
```
