### ISSUE TITLE
[Bug] fakeip range被匹配到GEOIP,private中

### ISSUE THREAD

**Issue by LordHumphrey** [MetaCubeX/mihomo#1000]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta v1.18.0 windows amd64 with go1.20.12 Tue Jan  2 07:30:46 UTC 2024

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
rules:
  ## ---- Rule Set Direct---- ##
  #  https://github.com/Loyalsoldier/clash-rules
  - IP-CIDR,172.16.0.0/12,N**
  - IP-CIDR,10.0.0.0/8,N**
  - GEOSITE,private,DIRECT
  - GEOIP,private,DIRECT,no-resolve
  - RULE-SET,applications,DIRECT
  - RULE-SET,MyApplications,DIRECT
```

### Mihomo log

```shell

time="2024-01-20T22:01:28.445361+08:00" level=debug msg="[DNS] resolve tophub.today from udp://1.2.4.8:53"
time="2024-01-20T22:01:28.4606417+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://1.2.4.8:53"
time="2024-01-20T22:01:28.5150462+08:00" level=debug msg="[DNS] h-k03.wamn.cc --> [] AAAA from https://dns.cloudflare.com:443/dns-query"
time="2024-01-20T22:01:28.445361+08:00" level=debug msg="[DNS] resolve tophub.today from udp://119.28.28.28:53"
time="2024-01-20T22:01:28.5107698+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from system(udp://[fdfe:dcba:9876::2]:53,udp://198.18.0.2:53,udp://127.0.0.1:53,udp://211.138.180.2:53,udp://223.6.6.6:53,udp://192.168.1.1:53)"
time="2024-01-20T22:01:28.445361+08:00" level=debug msg="[DNS] resolve tophub.today from system(udp://[fdfe:dcba:9876::2]:53,udp://198.18.0.2:53,udp://127.0.0.1:53,udp://211.138.180.2:53,udp://223.6.6.6:53,udp://192.168.1.1:53)"
time="2024-01-20T22:01:28.5233789+08:00" level=debug msg="[DNS] resolve tophub.today from udp://192.168.1.1:53"
time="2024-01-20T22:01:28.5233789+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://192.168.1.1:53"
time="2024-01-20T22:01:28.5107698+08:00" level=debug msg="[Rule] use default rules"
time="2024-01-20T22:01:28.5253731+08:00" level=debug msg="[DNS] resolve file.ipadown.com from udp://1.2.4.8:53"
time="2024-01-20T22:01:28.445361+08:00" level=debug msg="[DNS] resolve tophub.today from udp://101.7.8.9:53"
time="2024-01-20T22:01:28.5233789+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://198.18.0.2:53"
time="2024-01-20T22:01:28.5107698+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://117.50.11.11:53"
time="2024-01-20T22:01:28.5107698+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://1.2.4.8:53"
time="2024-01-20T22:01:28.5107698+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://119.28.28.28:53"
time="2024-01-20T22:01:28.5107698+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://117.50.11.11:53"
time="2024-01-20T22:01:28.5107698+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://223.6.6.6:53"
time="2024-01-20T22:01:28.5107698+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://223.6.6.6:53"
time="2024-01-20T22:01:28.445361+08:00" level=debug msg="[DNS] resolve tophub.today from udp://223.6.6.6:53"
time="2024-01-20T22:01:28.445361+08:00" level=debug msg="[DNS] resolve tophub.today from udp://1.2.4.8:53"
time="2024-01-20T22:01:28.445361+08:00" level=debug msg="[DNS] resolve tophub.today from udp://119.28.28.28:53"
time="2024-01-20T22:01:28.445361+08:00" level=debug msg="[DNS] resolve tophub.today from udp://117.50.11.11:53"
time="2024-01-20T22:01:28.5107698+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://101.7.8.9:53"
time="2024-01-20T22:01:28.5107698+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://119.28.28.28:53"
time="2024-01-20T22:01:28.5107698+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from system(udp://211.138.180.2:53,udp://223.6.6.6:53,udp://192.168.1.1:53,udp://[fdfe:dcba:9876::2]:53,udp://198.18.0.2:53,udp://127.0.0.1:53)"
time="2024-01-20T22:01:28.445361+08:00" level=debug msg="[DNS] resolve tophub.today from udp://101.7.8.9:53"
time="2024-01-20T22:01:28.445361+08:00" level=debug msg="[DNS] resolve tophub.today from system(udp://211.138.180.2:53,udp://223.6.6.6:53,udp://192.168.1.1:53,udp://[fdfe:dcba:9876::2]:53,udp://198.18.0.2:53,udp://127.0.0.1:53)"
time="2024-01-20T22:01:28.445361+08:00" level=debug msg="[DNS] resolve tophub.today from udp://223.6.6.6:53"
time="2024-01-20T22:01:28.445361+08:00" level=debug msg="[DNS] resolve tophub.today from udp://117.50.11.11:53"
time="2024-01-20T22:01:28.5107698+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://101.7.8.9:53"
time="2024-01-20T22:01:28.5233789+08:00" level=debug msg="[DNS] resolve tophub.today from udp://223.6.6.6:53"
time="2024-01-20T22:01:28.6488238+08:00" level=debug msg="[DNS] resolve tophub.today from udp://198.18.0.2:53"
time="2024-01-20T22:01:28.5263706+08:00" level=debug msg="[DNS] resolve file.ipadown.com from system(udp://211.138.180.2:53,udp://223.6.6.6:53,udp://192.168.1.1:53,udp://[fdfe:dcba:9876::2]:53,udp://198.18.0.2:53,udp://127.0.0.1:53)"
time="2024-01-20T22:01:28.6488238+08:00" level=debug msg="[DNS] resolve tophub.today from udp://211.138.180.2:53"
time="2024-01-20T22:01:28.5233789+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://[fdfe:dcba:9876::2]:53"
time="2024-01-20T22:01:28.5233789+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://127.0.0.1:53"
time="2024-01-20T22:01:28.5233789+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://211.138.180.2:53"
time="2024-01-20T22:01:28.5233789+08:00" level=debug msg="[DNS] resolve cdn.staticfile.org from udp://223.6.6.6:53"
time="2024-01-20T22:01:28.5243774+08:00" level=debug msg="[DNS] resolve tophub.today from udp://211.138.180.2:53"
time="2024-01-20T22:01:28.5243774+08:00" level=debug msg="[DNS] resolve tophub.today from udp://[fdfe:dcba:9876::2]:53"
time="2024-01-20T22:01:28.5243774+08:00" level=debug msg="[DNS] resolve tophub.today from udp://127.0.0.1:53"
time="2024-01-20T22:01:28.5243774+08:00" level=debug msg="[DNS] resolve tophub.today from udp://198.18.0.2:53"
time="2024-01-20T22:01:28.5263706+08:00" level=debug msg="[DNS] resolve file.ipadown.com from udp://119.28.28.28:53"
time="2024-01-20T22:01:28.5263706+08:00" level=debug msg="[DNS] resolve file.ipadown.com from udp://223.6.6.6:53"
time="2024-01-20T22:01:28.5263706+08:00" level=debug msg="[DNS] resolve file.ipadown.com from udp://101.7.8.9:53"
time="2024-01-20T22:01:28.5263706+08:00" level=debug msg="[DNS] resolve file.ipadown.com from udp://117.50.11.11:53"
time="2024-01-20T22:01:28.5263706+08:00" level=debug msg="[DNS] resolve file.ipadown.com from udp://119.28.28.28:53"
time="2024-01-20T22:01:28.5263706+08:00" level=debug msg="[DNS] resolve file.ipadown.com from udp://117.50.11.11:53"
time="2024-01-20T22:01:28.5473872+08:00" level=debug msg="[DNS] tophub.today --> [143.198.140.84] A from udp://192.168.1.1:53"
time="2024-01-20T22:01:28.5473872+08:00" level=debug msg="[DNS] cdn.staticfile.org --> [211.141.172.46 211.141.172.47 112.28.197.92 211.141.172.49 211.141.172.48 112.28.197.91 112.28.197.93 112.28.197.110] A from udp://192.168.1.1:53"
time="2024-01-20T22:01:28.5673894+08:00" level=debug msg="[DNS] tophub.today --> [] AAAA from udp://119.28.28.28:53"
```
### Warn 日志
```shell
time="2024-01-20T22:01:51.6235149+08:00" level=warning msg="[TCP] dial DIRECT (match GeoIP/private) 198.18.0.1:61767 --> freeapp.macapp8.com:443 error: dial tcp 198.18.0.36:443: i/o timeout"
time="2024-01-20T22:01:51.629378+08:00" level=warning msg="[TCP] dial DIRECT (match GeoIP/private) 198.18.0.1:61768 --> freeapp.macapp8.com:443 error: dial tcp 198.18.0.36:443: i/o timeout"
time="2024-01-20T22:01:51.6289678+08:00" level=warning msg="[TCP] dial DIRECT (match GeoIP/private) 198.18.0.1:61769 --> freeapp.macapp8.com:443 error: dial tcp 198.18.0.36:443: i/o timeout"
time="2024-01-20T22:01:51.6289678+08:00" level=warning msg="[TCP] dial DIRECT (match GeoIP/private) 198.18.0.1:61770 --> freeapp.macapp8.com:443 error: dial tcp 198.18.0.36:443: i/o timeout"
time="2024-01-20T22:01:51.629378+08:00" level=warning msg="[TCP] dial DIRECT (match GeoIP/private) 198.18.0.1:61766 --> freeapp.macapp8.com:443 error: dial tcp 198.18.0.36:443: i/o timeout"
time="2024-01-20T22:01:56.6307414+08:00" level=warning msg="[TCP] dial DIRECT (match GeoIP/private) 198.18.0.1:61785 --> freeapp.macapp8.com:443 error: dial tcp 198.18.0.36:443: i/o timeout"
time="2024-01-20T22:02:12.2654448+08:00" level=warning msg="[TCP] dial DIRECT (match GeoIP/private) 198.18.0.1:61830 --> cn.bing.com:443 error: dial tcp 198.18.0.6:443: i/o timeout"
time="2024-01-20T22:02:17.2820037+08:00" level=warning msg="[TCP] dial DIRECT (match GeoIP/private) 198.18.0.1:61832 --> cn.bing.com:443 error: dial tcp 198.18.0.6:443: i/o timeout"
time="2024-01-20T22:03:12.1655074+08:00" level=warning msg="[TCP] dial DIRECT (match GeoIP/private) 198.18.0.1:61834 --> cn.bing.com:443 error: dial tcp 198.18.0.6:443: i/o timeout"
time="2024-01-20T22:03:17.1827944+08:00" level=warning msg="[TCP] dial DIRECT (match GeoIP/private) 198.18.0.1:61836 --> cn.bing.com:443 error: dial tcp 198.18.0.6:443: i/o timeout"
time="2024-01-20T22:06:21.8390192+08:00" level=warning msg="[TCP] dial DIRECT (match GeoIP/private) mihomo --> lovefsr.top:443 error: dial tcp 198.18.0.49:443: i/o timeout"
time="2024-01-20T22:06:21.8396591+08:00" level=warning msg="[TCP] dial DIRECT (match GeoIP/private) mihomo --> jmssub.net:443 error: dial tcp 198.18.0.78:443: i/o timeout"
```

### DNS Config
```yaml
dns:
  enable: true
  cache-algorithm: arc
  listen: 0.0.0.0:53
  prefer-h3: true
  use-hosts: true
  ipv6: false
  ipv6-timeout: 150
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.example"
    - "*.home.arpa"
    - "*.invalid"
    - "+.lan"
    - "+.local"
    - "*.localdomain"
    - "*.localhost"
    - "*.test"
    - "WORKGROUP"
    #  Windows 10 Connnect Detection
    - "+.microsoft.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    # Linksys Wireless Router
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    #  NTP Service
    - "ntp.*.com"
    - "time-ios.apple.com"
    - "time-macos.apple.com"
    - "time.*.com"
    - "time.*.gov"
    - "+.pool.ntp.org"
    - "*.cloud.tencent.com"
    - "*.pool.ntp.org"
    - "pool.ntp.org"
    #  国内网站
    - "*.163.com"
    - "*.126.net"
    - "*.taihe.com"
    - "*.kugou.com"
    - "+.joox.com"
    - "+.qq.com"
    - "+.cn"
    - "+.cnblogs.com"
    #  Apple Software Update Service
    - "mesu.apple.com"
    - "swscan.apple.com"
    #  Game Service
    - "*.battle.net"
    # Microsoft Xbox
    - "speedtest.cros.wr.pvp.net"
    - "*.*.xboxlive.com"
    - "xbox.*.*.microsoft.com"
    - "xbox.*.microsoft.com"
    - "xnotify.xboxlive.com"
    # Nintendo Switch
    - "*.*.*.srv.nintendo.net"
    - "+.srv.nintendo.net"
    # Google
    - "lens.l.google.com"
    - "stun.l.google.com"
    # Sony PlayStation
    - "*.*.stun.playstation.net"
    # STUN Server
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*"
    - "stun.*.*.*"
    - "stun.*.*"
    # QQ Quick Login
    - "localhost.ptlogin2.qq.com"
    - "localhost.sec.qq.com"
    # BiliBili P2P
    - "*.mcdn.bilivideo.cn"
    # 网易云音乐
    - "music.163.com"
    - "*.music.163.com"
    - "*.126.net"
  default-nameserver:
    - "system"
    - 223.6.6.6
  nameserver:
    - "system"
    - 223.6.6.6
    - 119.28.28.28
    - "https://cn-a.iqiqz.com/cdn"
    - "https://doh.apad.pro/dns-query"
    - "https://dns.cloudflare.com/dns-query#DNS&h3=true"
  proxy-server-nameserver:
    - 223.6.6.6
    - "https://cn-a.iqiqz.com/dns-query"
    - "https://doh.apad.pro/dns-query"
    - "https://dns.cloudflare.com/dns-query#DNS&h3=true"
  nameserver-policy:
    "geosite:category-ads-all": rcode://success
    "geosite:private": ["system",211.138.180.2]
    "geosite:cn":
      [
        "system",
        101.7.8.9,
        223.6.6.6,
        119.28.28.28,
        117.50.11.11,
        1.2.4.8,
      ]
    "geosite:bing,geolocation-!cn":
      [
        "https://dns.adguard-dns.com/dns-query#DNS&h3=true",
        "https://dns.google/dns-query#DNS&h3=true",
        "https://dns.cloudflare.com/dns-query#DNS&h3=true"
      ]
```

### Description

好像是fake ip的地址范围被匹配到了geoip private当中，所以所有请求都timeout了
