### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lovexiaofan123** [MetaCubeX/mihomo#1002]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

hysteria2 UDP问题，进不去游戏，只有上传流量，下载流量过不来

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
proxies:
- name: HY2
  type: hysteria2
  server: xxxxxx
  port: xxxx
  password: xxxxx
  up: '1000'
  down: '1000'
  skip-cert-verify: true
  alpn:
  - h3
  ip-version: ipv4-prefer
  smux:
    enabled: false
```

### Mihomo log

```shell
[INFO] [UDP] 192.168.168.123:49747 --> 172.188.88.227:25158 match using
```

### Description

只有上传流量在走，下载流量没走，导致游戏进不去，包括nat转发也一样 版本用的是linux-amd64-compatible-alpha-e86567e，模式tun
![微信图片_20240121204829](https://github.com/MetaCubeX/mihomo/assets/68148054/0af2a467-cd08-4df7-b9b4-13cdf48cc2ad)
