### ISSUE TITLE
[Bug] 路由规则集没有按照顺序执行, 有时正常有时不正常

### ISSUE THREAD

**Issue by bakasine** [MetaCubeX/mihomo#1004]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.18.0

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
rules:
  # REJECT
  - RULE-SET,reject,REJECT
  - RULE-SET,privacy,REJECT
  - RULE-SET,hijacking,REJECT
  - RULE-SET,my-reject,REJECT
  - RULE-SET,miui,REJECT
  # CUSTOM
  - RULE-SET,game,GAME
  - RULE-SET,my-direct,DIRECT
```

### Description

用自己的服务器搭建幻兽帕鲁的服务器
game里是进程模式包含了"- PROCESS-NAME,Palworld-Win64-Shipping.exe"
然后这个域名前缀在顺序下方的 my-direct 里"- DOMAIN-SUFFIX,xxxxxx"
结果游戏连接帕鲁服务器的时候走的是直连

![image](https://github.com/MetaCubeX/mihomo/assets/8407699/1a811b11-da00-4ef1-8adc-9fdaaa67987e)

而且这种情况是时有时无的, 有时候他又能正常走game的代理, 有时候重启发现很卡一看连接他又是走的直连

**Comment by invisprints** [comment]
规则判断确实有问题，明明都指定Google Bard走AI通道了，却还是走得最末的国际通道
![2024-01-26 06-11-48](https://github.com/MetaCubeX/mihomo/assets/15833553/5a694ebe-01e6-4b68-b873-56a3f3b32fec)
![2024-01-26 06-12-34](https://github.com/MetaCubeX/mihomo/assets/15833553/aae31791-3bec-499b-a7f3-87ff1d934e32)
![2024-01-26 06-12-57](https://github.com/MetaCubeX/mihomo/assets/15833553/17347833-0629-447d-b171-c3355ff4a183)

**Comment by invisprints** [comment]
BTW, 不管是 Alpha 还是稳定版都有这个问题，而我切换回 CFW 或者 Stash 就是正常走 AI 通道

**Comment by Paulgudring** [comment]
@bakasine @invisprints udp的问题吧，游戏端用udp传输流量，网页端的quic协议也是基于udp的。匹配到的节点不支持udp，自动向下匹配了。可以用`network`规则搭配逻辑规则/子规则做筛选。

**Comment by invisprints** [comment]
我截图上面显示的是走的TCP诶，而且开全局是能走我期望的日本Proxy的 @Paulgudring

**Comment by Paulgudring** [comment]
> 我截图上面显示的是走的TCP诶，而且开全局是能走我期望的日本Proxy的 @Paulgudring

规则集是啥样的👀

**Comment by invisprints** [comment]
> > 我截图上面显示的是走的TCP诶，而且开全局是能走我期望的日本Proxy的 @Paulgudring
> 
> 规则集是啥样的👀

```yaml
payload:
  - DOMAIN, bard.google.com
  - DOMAIN, makersuite.google.com
  - DOMAIN, generativelanguage.googleapis.com
  - DOMAIN-SUFFIX, generativeai.google
  - DOMAIN-KEYWORD, palm2
  - DOMAINX, www.google.com
  - DOMAIN, labs.google.com
  - DOMAIN-SUFFIX, labs.google
```

**Comment by invisprints** [comment]
> > 我截图上面显示的是走的TCP诶，而且开全局是能走我期望的日本Proxy的 @Paulgudring
> 
> 规则集是啥样的👀

```yaml
payload:
  - DOMAIN, bard.google.com
  - DOMAIN, makersuite.google.com
  - DOMAIN, generativelanguage.googleapis.com
  - DOMAIN-SUFFIX, generativeai.google
  - DOMAIN-KEYWORD, palm2
  - DOMAIN, www.google.com
  - DOMAIN, labs.google.com
  - DOMAIN-SUFFIX, labs.google
```

**Comment by invisprints** [comment]
这是一份最小的可复现配置文件，神奇的是尽管我指定 Google Bard 和 OpenAI 都走同一条线路，OpenAI 遵守了规则但 Google Bard 却没有
<details>
<summary>config.yaml</summary>

```yaml
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
 
proxy-providers:
  ProxyCloud:
    type: http
    url: <URL>
    interval: 3600
    path: ./proxies/proxy.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

proxies:
            
proxy-groups:
  - name: 🚀 手动切换
    type: select
    use:
      - ProxyCloud
    proxies:
      - 🇭🇰香港
      - 🇯🇵日本
      - 🇺🇲美国
      
  - name: 🌏 国际网站
    type: select
    proxies:
      - 🚀 手动切换
      - DIRECT
      
  - name: 🌏 国内网站
    type: select
    proxies:
      - DIRECT
      - 🚀 手动切换

  - name: AI
    type: select
    proxies:
      - 🚀 手动切换
      - 🇺🇲美国
      - 🇯🇵日本
      - DIRECT

  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - DIRECT
      - 🚀 手动切换

  - name: 🇭🇰香港
    type: url-test
    filter: 港|HK|🇭🇰|(?i)Hong
    use:
      - ProxyCloud
    url: "http://www.gstatic.com/generate_204"
    interval: 300

  - name: 🇯🇵日本
    type: url-test
    filter: 日|东京|JP|🇯🇵|(?i)Japan
    use:
      - ProxyCloud
    url: "http://www.gstatic.com/generate_204"
    interval: 300

  - name: 🇺🇲美国
    type: url-test
    filter: 美|US|🇺🇸|(?i)States|American
    use:
      - ProxyCloud
    url: "http://www.gstatic.com/generate_204"
    interval: 300
      
rule-providers:

  LocalAreaNetwork:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/LocalAreaNetwork.yaml
    path: ./ruleset/UnBan.yaml
    interval: 86400
    
  UnBan:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/UnBan.yaml
    path: ./ruleset/UnBan.yaml
    interval: 86400

  ChinaDomain:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/ChinaDomain.yaml"
    path: ./ruleset/ChinaDomain.yaml
    interval: 86400

  OpenAI:
    type: http
    behavior: classical
    url: "https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/OpenAi.yaml"
    path: ./ruleset/openai.yaml
    interval: 86400
  
  GoogleBard:
    type: http
    behavior: classical
    url: "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/BardAI/BardAI.yaml"
    path: ./ruleset/BardAI.yaml
    interval: 86400

  ClaudeAI:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/Ruleset/ClaudeAI.yaml"
    path: ./ruleset/ClaudeAI.yaml
    interval: 86400
    
  Global:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Providers/ProxyGFWlist.yaml"
    path: ./ruleset/Global.yaml
    interval: 86400

rules:
  - RULE-SET,UnBan,DIRECT
  - RULE-SET,LocalAreaNetwork,DIRECT
  - RULE-SET,GoogleBard,AI
  - RULE-SET,OpenAI,AI
  - RULE-SET,ClaudeAI,AI
  - RULE-SET,Global,🌏 国际网站
  - RULE-SET,ChinaDomain,🌏 国内网站
  - GEOIP,CN,🌏 国内网站
  - MATCH,🐟 漏网之鱼
```
</details>

![2024-01-27 03-13-04](https://github.com/MetaCubeX/mihomo/assets/15833553/2e64c00d-325b-4753-b0e3-248fa477b3c3)
