### ISSUE TITLE
[Bug] lan-allowed-ips 疑似不起作用

### ISSUE THREAD

**Issue by canoziia** [MetaCubeX/mihomo#1010]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta alpha-9bd70e1 linux amd64 with go1.21.6 Wed Jan 24 09:54:11 UTC 2024 Use tags: with_gvisor

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
allow-lan: true
bind-address: '*'
external-controller: 0.0.0.0:9090
ipv6: true
lan-allowed-ips:
- 1.1.1.1/32
- 2000::/32
log-level: info
mixed-port: 7890
mode: Rule
port: 7892
socks-port: 7891
tproxy-port: 7894
```

### Description

按照 https://wiki.metacubex.one/config/general/#_1 配置lan-allowed-ip后，仍然可以使用局域网设备（地址是192.168.1.x）以及其他主机去访问运行mihomo的主机的7890端口并成功代理。似乎这个设置不起作用。
