### ISSUE TITLE
[Bug] 断网环境下macOS从睡眠中唤醒时内核高CPU占用

### ISSUE THREAD

**Issue by KingfuChan** [MetaCubeX/mihomo#1011]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

v.1.8.0/alpha-9bd70e1

### What OS are you seeing the problem on?

macOS

### Mihomo config

```yaml
# Clash-Meta-Daemon
mode: rule
mixed-port: 9091
log-level: silent
secret: __META_SECRET__
external-controller: 127.0.0.1:9089
external-ui: "./metacubexd"
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

ipv6: true
allow-lan: false
profile:
  store-selected: true
find-process-mode: always
unified-delay: true
tcp-concurrent: true
keep-alive-interval: 15
global-client-fingerprint: random
geodata-mode: true # using .dat
geo-auto-update: true
geo-update-interval: 24
geox-url:
  # https://github.com/Loyalsoldier/v2ray-rules-dat
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  prefer-h3: true
  use-hosts: true
  enhanced-mode: redir-host
  nameserver:
    - https://doh.pub/dns-query#DIRECT
    - https://dns.google/dns-query#PROXY
    - https://cloudflare-dns.com/dns-query#PROXY
  nameserver-policy:
    "rule-set:Microsoft":
      - https://dns.google/dns-query#Microsoft
      - https://cloudflare-dns.com/dns-query#Microsoft
    "rule-set:GitHub":
      - https://dns.google/dns-query#GitHub
      - https://cloudflare-dns.com/dns-query#GitHub
    "geosite:google,google-cn":
      - https://dns.google/dns-query#Google
      - https://cloudflare-dns.com/dns-query#Google
    "rule-set:Apple":
      - https://dns.alidns.com/dns-query#DIRECT
      - https://doh.pub/dns-query#DIRECT
    "geosite:private,apple-cn,icloud,cn,china-list":
      - https://dns.alidns.com/dns-query#DIRECT
      - https://doh.pub/dns-query#DIRECT
    "geosite:category-games@cn,category-games":
      - https://dns.alidns.com/dns-query#DIRECT
      - https://doh.pub/dns-query#DIRECT
    "geosite:category-ads-all":
      - https://dns.adguard-dns.com/dns-query#PROXY
  default-nameserver:
    - system
  proxy-server-nameserver:
    - https://223.6.6.6/dns-query
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
# Omit following proxy&rule related part
```

### Description

macOS Sonoma 14.3， MacBook Air M2
合盖/手动按下睡眠按钮后间隔一定时间（未作控制）唤醒，如果唤醒的时候没有有效的互联网连接，则内核开始出现高CPU占用情况，CPU温度升高。
使用debug模式输出log可以观察到大量重复DNS请求。
手动关闭Wi-Fi连接后如果不进入睡眠状态则不会出现上述情况。
