### ISSUE TITLE
[Bug] API响应超时

### ISSUE THREAD

**Issue by xkww3n** [MetaCubeX/mihomo#1012]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta alpha-9bd70e1 windows amd64 with go1.21.6 Wed Jan 24 09:53:29 UTC 2024 Use tags: with_gvisor

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
mixed-port: 1145
log-level: debug
external-controller: 127.0.0.1:1919
proxies:
  - type: ss
    cipher: aes-128-gcm
    name: Hong Kong 01
    password: REDACTED
    port: 'REDACTED'
    server: REDACTED
    udp: true
proxy-groups:
  - type: select
    name: Proxy
    proxies:
      - Hong Kong 01
```

### Mihomo log

```shell
time="2024-01-29T11:27:52.9744077+08:00" level=info msg="Start initial configuration in progress"
time="2024-01-29T11:27:52.9812121+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-01-29T11:27:52.9812121+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-01-29T11:27:52.9877358+08:00" level=info msg="Initial configuration complete, total time: 6ms"
time="2024-01-29T11:27:52.9877358+08:00" level=info msg="Sniffer is closed"
time="2024-01-29T11:27:52.9882667+08:00" level=info msg="RESTful API listening at: 127.0.0.1:1919"
time="2024-01-29T11:27:52.9882667+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:1145"
time="2024-01-29T11:27:52.9923042+08:00" level=info msg="Start initial Compatible provider Proxy"
time="2024-01-29T11:27:52.9923042+08:00" level=info msg="Start initial Compatible provider default"
time="2024-01-29T11:30:45.950083+08:00" level=warning msg="Mihomo shutting down"
```

### Description

以上述配置启动mihomo后，尝试使用metacubexd等web面板操作mihomo，发现“代理”、“规则”等页面均显示空白，F12开发者工具中看到面板在请求多个接口时均超时。

![Clip_2024-01-29_11-35-00](https://github.com/MetaCubeX/mihomo/assets/30206355/6d9dd65f-0701-4487-824b-5d3d73322a77)
