### ISSUE TITLE
[Bug] mihomo returns poisoned DNS from a proxy instead of configured nameserver

### ISSUE THREAD

**Issue by lux5am** [MetaCubeX/mihomo#1025]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta alpha-20658f6 android arm64 with go1.21.6 Mon Feb  5 14:41:30 UTC 2024 Use tags: with_gvisor

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
find-process-mode: always
unified-delay: true
keep-alive-interval: 1800

external-controller: 0.0.0.0:9090
external-ui: ./ui

dns:
  enable: true
  listen: 127.0.0.1:1053
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://94.140.14.14/dns-query#🔼Dns

proxies: []

proxy-groups:
  - name: 🌝Proxy
    type: select
    use:
      - myproxies
  - name: 🔼Dns
    type: select
    use:
      - myproxies

proxy-providers:
  myproxies:
    type: file
    path: ./proxy_provider/myproxies.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800

rules:
  - IP-CIDR,94.140.14.14/32,🔼Dns
  - MATCH,🌝Proxy

tun:
  enable: true
  mtu: 9000
  device: utun
  stack: system # gvisor / system / mixed
  dns-hijack:
    - 0.0.0.0:53
  auto-route: true
  strict-route: false
  auto-detect-interface: true
  include-android-user: [0, 10]
  exclude-package: [] # blacklist
  include-package: [] # whitelist

tproxy-port: 0
redir-port: 9797
```

### Description

It seems mihomo randomly returns a DNS response from a selected proxy instead of configured nameserver. Or what people say DNS leak.

This causing unexpected behaviour like forced safe search on google, youtube, bing, yandex etc. And require login to see public accounts on Facebook and Instagram.

This behaviour also make blocking ads via DNS like Adguard or nextdns isn't effective.

p.s I'm using a magisk module to run mihomo named Box for Root.

Picrel:
Here I set DNS to UK, and proxy to Japan
![Screenshot_20240206-111617_Kiwi Browser](https://github.com/MetaCubeX/mihomo/assets/110870661/0576f37e-7106-4e1d-ad47-41fea44d8fc4)
![Screenshot_20240206-111736_Kiwi Browser](https://github.com/MetaCubeX/mihomo/assets/110870661/1f32bf6d-a01e-4a57-94c5-125f7737576e)

Then change the proxy only to Poland
![Screenshot_20240206-111655_Kiwi Browser](https://github.com/MetaCubeX/mihomo/assets/110870661/c937f674-a26a-470e-ad3f-99d2643d69ec)
![Screenshot_20240206-111731_Kiwi Browser](https://github.com/MetaCubeX/mihomo/assets/110870661/5f957810-2e3f-4e4b-8a30-128ddf99e70a)

And if I use nextdns in nameserver. In nextdns dashboard it would show
![Screenshot_20240206-112219_Kiwi Browser](https://github.com/MetaCubeX/mihomo/assets/110870661/bff9c887-6be6-490f-815f-51de187918cf)
