### ISSUE TITLE
[Bug] 内存泄漏

### ISSUE THREAD

**Issue by cesaryuan** [MetaCubeX/mihomo#1034]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta alpha-0c384b1 windows amd64 with go1.22.0 Wed Feb  7 13:08:22 UTC 2024

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
mode: rule
mixed-port: 7890
socks-port: 7898
port: 7899
allow-lan: true
log-level: debug
ipv6: true
secret: ''
external-controller: 127.0.0.1:9192
geo-update-interval: 24
find-process-mode: strict
sub-rules:
  download:
  - RULE-SET,direct,🎯 全球直连
  - RULE-SET,ChinaDomain_domain,🎯 全球直连
  - RULE-SET,ChinaDomain_ipcidr,🎯 全球直连
  - RULE-SET,lancidr,🎯 全球直连
  - RULE-SET,cncidr,🎯 全球直连
  - GEOIP,CN,🎯 全球直连
  - MATCH,🔯 大流量节点
proxy-provider-healthcheck:
  interval: 3600
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 300
tproxy-port: 7893
external-ui-name: metacubexd
geo-auto-update: false
redir-port: 7892
geox-url:
  geoip: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb
listeners:
- name: Load-Balance
  type: http
  port: 7990
  listen: 0.0.0.0
  proxy: load-balance
geodata-loader: memconservative
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
global-client-fingerprint: chrome
dns:
  enable: true
  prefer-h3: false
  listen: :1053
  default-nameserver:
  - 114.114.114.114
  - tls://223.5.5.5:853
  - system
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter:
  - '*'
  - +.lan
  - +.local
  nameserver:
  - system://
  - system
  - dhcp://system
  - 223.5.5.5
  - 114.114.114.114
  - 8.8.8.8
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query#h3=true
external-ui: ui
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true
tun:
  enable: false
  stack: mixed
  dns-hijack:
  - 0.0.0.0:53
proxy-providers:
  laji:
    type: http
    url: 
    path: ./proxy_providers/laji.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
  mojie:
    type: http
    url: 
    path: ./proxy_providers/mojie.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
  yuyan:
    type: http
    url: 
    path: ./proxy_providers/yuyan.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
  yiyuan:
    type: http
    url: 
    path: ./proxy_providers/yiyuan.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
  mitce:
    type: http
    url: 
    path: ./proxy_providers/mitce.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: 🚀 日常网页
  type: select
  proxies:
  - 🇭🇰 香港节点
  - 🔯 大流量节点
  - 🇨🇳 台湾节点
  - 🇸🇬 狮城节点
  - 🇯🇵 日本节点
  - 🇺🇲 美国节点
  - DIRECT
  include-all-providers: true
- name: 🔯 大流量节点
  type: select
  filter: ([*|x]\s*0\.(1|2)|\w\|\w)
  use:
  - laji
  - mitce
- name: 🇭🇰 香港节点
  type: url-test
  url: https://cp.cloudflare.com/generate_204
  interval: 300
  tolerance: 50
  filter: (港|HK|Hong Kong)(?!.*\*[2-9])
  use:
  - laji
  - mitce
- name: 🇯🇵 日本节点
  type: url-test
  url: https://cp.cloudflare.com/generate_204
  interval: 300
  tolerance: 50
  filter: (日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)(?!.*\*[2-9])
  use:
  - laji
  - mitce
- name: 🇺🇲 美国节点
  type: url-test
  url: https://cp.cloudflare.com/generate_204
  interval: 300
  tolerance: 50
  filter: (美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)(?!.*\*[2-9])
  use:
  - laji
  - mitce
- name: 🇨🇳 台湾节点
  type: url-test
  url: https://cp.cloudflare.com/generate_204
  interval: 300
  tolerance: 50
  filter: (台|新北|彰化|TW|Taiwan)(?!.*\*[2-9])
  use:
  - laji
  - mitce
- name: 🇸🇬 狮城节点
  type: url-test
  url: https://cp.cloudflare.com/generate_204
  interval: 300
  tolerance: 50
  filter: (新加坡|坡|狮城|SG|Singapore)(?!.*\*[2-9])
  use:
  - laji
  - mitce
- name: 🐟 漏网之鱼
  type: select
  proxies:
  - 🚀 日常网页
  - 🔯 大流量节点
  - DIRECT
- name: 📢 谷歌FCM
  type: select
  proxies:
  - 🚀 日常网页
  - DIRECT
  - 🔯 大流量节点
- name: SSH
  type: select
  include-all: true
- name: 📲 电报消息
  type: fallback
  url: https://cp.cloudflare.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - 🔯 大流量节点
  - 🚀 日常网页
- name: Ⓜ️ 微软云盘
  type: select
  proxies:
  - 🔯 大流量节点
  - DIRECT
  - 🚀 日常网页
- name: Ⓜ️ 微软服务
  type: select
  proxies:
  - DIRECT
  - 🔯 大流量节点
  - 🚀 日常网页
- name: 🤖 Claude
  type: select
  include-all: true
  proxies:
  - 🇺🇲 美国节点
- name: 🤖 OpenAI
  type: select
  proxies:
  - 🇸🇬 狮城节点
  - 🇯🇵 日本节点
  - 🇨🇳 台湾节点
  - 🇺🇲 美国节点
- name: 🤖 BingAI
  type: select
  proxies:
  - 🇸🇬 狮城节点
  - 🇯🇵 日本节点
  - 🇨🇳 台湾节点
  - 🇺🇲 美国节点
  - DIRECT
- name: 🎯 全球直连
  type: select
  proxies:
  - DIRECT
  - 🚀 日常网页
- name: load-balance
  type: load-balance
  strategy: round-robin
  url: http://www.gstatic.com/generate_204
  interval: 600
  include-all: true
rule-providers:
  UnBan_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvVW5CYW4ubGlzdA
    path: ./providers/rule-provider_UnBan_domain.yaml
    interval: 86400
  0CesarDirect_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2Nlc2FyeXVhbi9BQ0w0U1NSL215L0NsYXNoLzBDZXNhckRpcmVjdC5saXN0
    path: ./providers/rule-provider_0CesarDirect_domain.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://apiproxy.cesaryuan.top/-----https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
    path: ./providers/rule-provider_private.yaml
    interval: 86400
  GoogleFCM_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvUnVsZXNldC9Hb29nbGVGQ00ubGlzdA
    path: ./providers/rule-provider_GoogleFCM_domain.yaml
    interval: 86400
  GoogleFCM_ipcidr:
    type: http
    behavior: ipcidr
    url: https://sub.xeton.dev/getruleset?type=4&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvUnVsZXNldC9Hb29nbGVGQ00ubGlzdA
    path: ./providers/rule-provider_GoogleFCM_ipcidr.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: https://apiproxy.cesaryuan.top/-----https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt
    path: ./providers/rule-provider_apple.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: https://apiproxy.cesaryuan.top/-----https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt
    path: ./providers/rule-provider_icloud.yaml
    interval: 86400
  GoogleCN_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvR29vZ2xlQ04ubGlzdA
    path: ./providers/rule-provider_GoogleCN_domain.yaml
    interval: 86400
  SteamCN_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvUnVsZXNldC9TdGVhbUNOLmxpc3Q
    path: ./providers/rule-provider_SteamCN_domain.yaml
    interval: 86400
  Bing_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvQmluZy5saXN0
    path: ./providers/rule-provider_Bing_domain.yaml
    interval: 86400
  OneDrive_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvT25lRHJpdmUubGlzdA
    path: ./providers/rule-provider_OneDrive_domain.yaml
    interval: 86400
  Microsoft_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvTWljcm9zb2Z0Lmxpc3Q
    path: ./providers/rule-provider_Microsoft_domain.yaml
    interval: 86400
  Telegram_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvVGVsZWdyYW0ubGlzdA
    path: ./providers/rule-provider_Telegram_domain.yaml
    interval: 86400
  Telegram_ipcidr:
    type: http
    behavior: ipcidr
    url: https://sub.xeton.dev/getruleset?type=4&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvVGVsZWdyYW0ubGlzdA
    path: ./providers/rule-provider_Telegram_ipcidr.yaml
    interval: 86400
  OpenAi_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2Nlc2FyeXVhbi9BQ0w0U1NSL215L0NsYXNoL1J1bGVzZXQvT3BlbkFpLmxpc3Q
    path: ./providers/rule-provider_OpenAi_domain.yaml
    interval: 86400
  Claude_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvUnVsZXNldC9DbGF1ZGUubGlzdA
    path: ./providers/rule-provider_Claude_domain.yaml
    interval: 86400
  YouTube_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvUnVsZXNldC9Zb3VUdWJlLmxpc3Q
    path: ./providers/rule-provider_YouTube_domain.yaml
    interval: 86400
  TikTok_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvUnVsZXNldC9UaWtUb2subGlzdA
    path: ./providers/rule-provider_TikTok_domain.yaml
    interval: 86400
  0CesarEmby_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2Nlc2FyeXVhbi9BQ0w0U1NSL215L0NsYXNoLzBDZXNhckVtYnkubGlzdA
    path: ./providers/rule-provider_0CesarEmby_domain.yaml
    interval: 86400
  0CesarEmby_ipcidr:
    type: http
    behavior: ipcidr
    url: https://sub.xeton.dev/getruleset?type=4&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2Nlc2FyeXVhbi9BQ0w0U1NSL215L0NsYXNoLzBDZXNhckVtYnkubGlzdA
    path: ./providers/rule-provider_0CesarEmby_ipcidr.yaml
    interval: 86400
  0CesarDownload_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2Nlc2FyeXVhbi9BQ0w0U1NSL215L0NsYXNoLzBDZXNhckRvd25sb2FkLmxpc3Q
    path: ./providers/rule-provider_0CesarDownload_domain.yaml
    interval: 86400
  ProxyGFWlist_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvUHJveHlHRldsaXN0Lmxpc3Q
    path: ./providers/rule-provider_ProxyGFWlist_domain.yaml
    interval: 86400
  ProxyGFWlist_ipcidr:
    type: http
    behavior: ipcidr
    url: https://sub.xeton.dev/getruleset?type=4&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvUHJveHlHRldsaXN0Lmxpc3Q
    path: ./providers/rule-provider_ProxyGFWlist_ipcidr.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://apiproxy.cesaryuan.top/-----https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
    path: ./providers/rule-provider_proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://apiproxy.cesaryuan.top/-----https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
    path: ./providers/rule-provider_direct.yaml
    interval: 86400
  ChinaDomain_domain:
    type: http
    behavior: domain
    url: https://sub.xeton.dev/getruleset?type=3&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvQ2hpbmFEb21haW4ubGlzdA
    path: ./providers/rule-provider_ChinaDomain_domain.yaml
    interval: 86400
  ChinaDomain_ipcidr:
    type: http
    behavior: ipcidr
    url: https://sub.xeton.dev/getruleset?type=4&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9tYXN0ZXIvQ2xhc2gvQ2hpbmFEb21haW4ubGlzdA
    path: ./providers/rule-provider_ChinaDomain_ipcidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: https://apiproxy.cesaryuan.top/-----https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt
    path: ./providers/rule-provider_lancidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: https://apiproxy.cesaryuan.top/-----https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt
    path: ./providers/rule-provider_cncidr.yaml
    interval: 86400
  0CesarSSH:
    type: http
    behavior: classical
    url: https://apiproxy.cesaryuan.top/-----https://raw.githubusercontent.com/cesaryuan/ACL4SSR/my/Clash/0CesarSSH.yaml
    path: ./providers/rule-provider_0CesarSSH.yaml
    interval: 86400
rules:
- RULE-SET,UnBan_domain,🎯 全球直连
- RULE-SET,0CesarDirect_domain,🎯 全球直连
- RULE-SET,private,🎯 全球直连
- RULE-SET,GoogleFCM_domain,📢 谷歌FCM
- RULE-SET,GoogleFCM_ipcidr,📢 谷歌FCM
- RULE-SET,apple,🎯 全球直连
- RULE-SET,icloud,🎯 全球直连
- RULE-SET,GoogleCN_domain,🎯 全球直连
- RULE-SET,SteamCN_domain,🎯 全球直连
- RULE-SET,Bing_domain,🤖 BingAI
- RULE-SET,OneDrive_domain,Ⓜ️ 微软云盘
- RULE-SET,Microsoft_domain,Ⓜ️ 微软服务
- RULE-SET,Telegram_domain,📲 电报消息
- RULE-SET,Telegram_ipcidr,📲 电报消息
- RULE-SET,OpenAi_domain,🤖 OpenAI
- RULE-SET,Claude_domain,🤖 Claude
- RULE-SET,YouTube_domain,🔯 大流量节点
- RULE-SET,TikTok_domain,🔯 大流量节点
- RULE-SET,0CesarEmby_domain,🔯 大流量节点
- RULE-SET,0CesarEmby_ipcidr,🔯 大流量节点
- RULE-SET,0CesarDownload_domain,🔯 大流量节点
- SUB-RULE,(PROCESS-NAME,aria2c.exe),download
- RULE-SET,ProxyGFWlist_domain,🚀 日常网页
- RULE-SET,ProxyGFWlist_ipcidr,🚀 日常网页
- RULE-SET,proxy,🚀 日常网页
- RULE-SET,direct,🎯 全球直连
- RULE-SET,ChinaDomain_domain,🎯 全球直连
- RULE-SET,ChinaDomain_ipcidr,🎯 全球直连
- RULE-SET,lancidr,🎯 全球直连
- RULE-SET,cncidr,🎯 全球直连
- GEOIP,CN,🎯 全球直连
- RULE-SET,0CesarSSH,SSH
- MATCH,🐟 漏网之鱼
```

### Mihomo log

```shell
日志有700多兆，上传不上来，我看了下，大部分日志是
2024-02-13 08:45:23 INFO - [clash]: time="2024-02-13T08:45:23.447846+08:00" level=debug msg="[DNS] resolve [DOMAIN] from [DNS SERVER]"
```

### Description

大概在我宿舍电脑（Windows11）运行一晚上后，内存就会增长的600M，之后便会稳定，而同样的配置文件，在我的笔记本上（Windows10）没有问题，这是heap文件：

[heap.txt](https://github.com/MetaCubeX/mihomo/files/14254438/heap.txt)
