### ISSUE TITLE
[Bug] 使用DNS经过代理查询时，DNS连通失败时无法触发代理节点的健康检查。

### ISSUE THREAD

**Issue by ghost** [MetaCubeX/mihomo#1044]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

23e3f12

### Mihomo config

```yaml
No response
```

### Mihomo log

```shell
No response
```

### Description

各位大佬好：
举例：
```yaml
dns:
  nameserver:
  - https://dns.cloudflare.com/dns-query#DNS
  - https://dns.google/dns-query#DNS
proxy-groups:
- {name: DNS, type: select, proxies: [A...
- {name: A, type: url-test/fallback...
- {name: Z...
rules:
- DOMAIN-SUFFIX,google.com,A
- DOMAIN-SUFFIX,twitter.com,Z
```
当代理组A选择的节点掉线时访问twitter，访问流量该走代理组Z，但会因代理组A无法连通而无法获取到dns致连接失败。亦无法激活A节点的失败5次强制健康检查功能。此时访问google有概率触发强制健康检查功能。否则只能等interval。如果A中还包含lazy参数，在不访问google的情况下无法解除lazy。
