### ISSUE TITLE
[Feature] functionality to edit/add fragment to configs

### ISSUE THREAD

**Issue by EbadiDev** [MetaCubeX/mihomo#1046]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

Add a Hello Fragmentation option.

This feature allows for stable connections to servers that are blocked or blacklisted by the Great Firewall of China (GFW).

It means we can now also connect to servers behind a CDN with a "dirty" IP address, without the need to find a new "clean" IP.

Fragmentation has already been added to [V2rayNG](https://github.com/2dust/v2rayNG/pull/2839), and I was wondering if there are any plans to include it in a future release, in order to enable fragmentation for configurations? This would help hide the SNI from the GFW, which is especially relevant in Iran. This feature effectively solves ping, speed and blocking SNI issues in Iran.
configuration can be like this:

```yaml
- name: "vless-ws"
  type: vless
  server: server
  port: 443
  uuid: uuid
  udp: true
  tls: true
  network: ws
  servername: example.com # priority over wss host
  # skip-cert-verify: true
  fragment: true
  fragments-opt:
    fragment-packets : tlshello
    fragment-length: 50-100 # (min-max)
    fragment-interval: 10-20 # (min-max)
  ws-opts:
    path: "/"
    headers:
      Host: example.com
    # v2ray-http-upgrade: false
```

useful links:
https://xtls.github.io/config/outbounds/freedom.html
