### ISSUE TITLE
[Bug] dns-hijack is not compatible with IPv6 addr

### ISSUE THREAD

**Issue by Journalist-HK** [MetaCubeX/mihomo#1054]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Meta v1.18.1 linux arm64 with go1.21.6

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
tun:
  enable: true
  stack: system
  dns-hijack:
    - 8.8.8.8:53
    - 8.8.4.4:53
    - [2001:4860:4860::8888]:53
    - [2001:4860:4860::8844]:53
  auto-route: false
  auto-detect-interface: false
```

### Mihomo log

```shell
~ $ mihomo -t
ERRO[2024-02-21T22:22:02.684953412+08:00] yaml: line 146: did not find expected '-' indicator 
configuration file /home/pi/.config/mihomo/config.yaml test failed
```

### Description

Since some DNS addresses used by another program need to bypass the hijack, I prefer not to use `any:53`. But I can't input IPv6 address in the config file.

Another option is to use something like whitelist, but idk how to do.
