### ISSUE TITLE
[Bug] 使用IPV6地址+vmess+http伪装的配置引起内核panic

### ISSUE THREAD

**Issue by imbalaomao** [MetaCubeX/mihomo#1063]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-78b4b11

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
proxies:
  - name: Name
    type: vmess
    server: *:ddc0:a000:*
    port: 12345
    cipher: auto
    uuid: uuid
    alterId: 0
    tls: false
    network: http
    http-opts:
      path:
        - /
      headers: {}
proxy-groups
  - name: 🌐全球手动
    type: select
    proxies:
      - Name
rules:
  - GEOIP,cn,DIRECT,no-resolve
  - MATCH,🌐全球手动
```

### Description

+ 使用GUI：Clash for Windows / Clash Verge Rev

+ 问题表现：
在使用上述配置时（只要配置中包含IPV6地址的VMESS+HTTP no TLS节点），出现下图的报错，且导致内核panic，需要先切换配置再重启软件解决
![图片](https://github.com/MetaCubeX/mihomo/assets/35653686/a156684b-1308-449c-956b-13bdcf4f1f69)

+ 已尝试方案：
  > - 给IPV6地址添加英文引号，依然报此错误
  > - 切换至IPV4地址的VMESS + HTTP（无TLS），不会报错
  > - 将IPV6地址解析到域名并替换配置内的IP地址，不会报错
