### ISSUE TITLE
[Bug] WireGuard实际上不支持多Peer

### ISSUE THREAD

**Issue by daiaji** [MetaCubeX/mihomo#1069]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta 1.10.0 linux amd64 with go1.22.0 unknown time

### What OS are you seeing the problem on?

sudo lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        23.1.3
Codename:       Vulcan

### Mihomo config

```yaml
- name: wg
    type: wireguard
    private-key: 1111111111111111111111111
    ip: 10.0.0.2
    ipv6: fdc9:281f:4d7:9ee9::2
    udp: true
    peers:
      - server: 10.10.10.1
        port: 51871
        public-key: 1111111111111111111111111
        allowed-ips: ["10.0.0.1/32","10.10.10.0/24"]
      - server: 10.10.10.2
        port: 51871
        public-key: 1111111111111111111111111
        allowed-ips: ["10.0.0.3/32"]
```

### Mihomo log

```shell
DEBU[2024-02-28T20:42:53.767997752+08:00] Finish A Health Checking {176e1d42-ac35-4160-937d-34a54ffba28c} 
DEBU[2024-02-28T20:42:54.275094838+08:00] [Rule] use default rules                     
DEBU[2024-02-28T20:42:54.275225187+08:00] [DNS] resolve chat.aio.lan from udp://10.0.0.1:53 
DEBU[2024-02-28T20:42:54.275268207+08:00] [DNS] resolve chat.aio.lan from udp://10.0.0.1:53 
DEBU[2024-02-28T20:42:54.275386666+08:00] [WG](wg) Interface up requested              
DEBU[2024-02-28T20:42:54.275449365+08:00] [WG](wg) Routine: receive incoming receive - started 
DEBU[2024-02-28T20:42:54.275474165+08:00] [WG](wg) UDP bind has been updated           
DEBU[2024-02-28T20:42:54.275511235+08:00] [WG](wg) peer(JdOB…efjA) - Starting          
DEBU[2024-02-28T20:42:54.275544645+08:00] [WG](wg) peer(07Uh…42Wo) - Starting          
DEBU[2024-02-28T20:42:54.275607604+08:00] [WG](wg) peer(07Uh…42Wo) - Routine: sequential receiver - started 
DEBU[2024-02-28T20:42:54.275610104+08:00] [WG](wg) peer(JdOB…efjA) - Routine: sequential receiver - started 
DEBU[2024-02-28T20:42:54.275629294+08:00] [WG](wg) peer(07Uh…42Wo) - Routine: sequential sender - started 
DEBU[2024-02-28T20:42:54.275625624+08:00] [WG](wg) Interface state was Down, requested Up, now Up 
DEBU[2024-02-28T20:42:54.275635074+08:00] [WG](wg) peer(JdOB…efjA) - Routine: sequential sender - started 
DEBU[2024-02-28T20:42:59.275775474+08:00] [DNS] resolve chat.aio.lan error: couldn't find ip 
DEBU[2024-02-28T20:42:59.275912463+08:00] [DNS] resolve chat.aio.lan from udp://10.0.0.1:53 
DEBU[2024-02-28T20:42:59.275942813+08:00] [DNS] resolve chat.aio.lan from udp://10.0.0.1:53 
DEBU[2024-02-28T20:42:59.276094642+08:00] [WG](wg) peer(JdOB…efjA) - Sending handshake initiation 
WARN[2024-02-28T20:43:04.276347877+08:00] [TCP] dial 🎯 全球直连 (match GeoSite/private) 127.0.0.1:37804 --> chat.aio.lan:443 error: dns resolve failed: couldn't find ip 
DEBU[2024-02-28T20:43:04.276425116+08:00] [DNS] resolve chat.aio.lan from udp://10.0.0.1:53 
DEBU[2024-02-28T20:43:04.276754054+08:00] [WG](wg) peer(JdOB…efjA) - Sending handshake initiation
```

### Description

https://github.com/MetaCubeX/mihomo/issues/522
https://github.com/daiaji/mihomo/commit/709737f56de06adf5661245f2ac30119dcd63315
通过一些修改，我尝试让配置更规范，就像https://wiki.archlinux.org/title/WireGuard#wg-quick
但实际上就算只为本地接口配置一个IP地址，故障依旧。
然后我又尝试迭代循环wireguard.NewClientBind所有的Endpoint,但结果还是不行。
我现在没活了，不知道该怎么办了，GPT说配置部分又是已经迭代循环枚举完了。

**Comment by daiaji** [comment]
在此 https://github.com/MetaCubeX/mihomo/commit/eae1f05e88365706141bf6c64663e2a16beea4ff PR之后，WG功能对于多Peer的支持应该已经完善。

**Comment by topgun-cn** [comment]
亲测，支持多个Peer，应该是你自己配置有问题

**Comment by thomasTAT** [comment]
你好，手机流量下 Clash meta for andriod + WireGuard 正常连接，切换后WiFi断连，需要重启 clash 才能恢复连接，请问你有遇到过吗？https://github.com/MetaCubeX/mihomo/discussions/1810



# 完整配置信息：
```
#clash config

proxies:

- name: "SF-UK-LD"
  type: wireguard
  ip: 10.14.0.2
  private-key: dfjashdjfjkdsfhjkdshfjkdhjkfhkdjfdfhdjfhdjfhd
  peers:
    - server: uk-lon.prod.surfshark.com
      port: 51820
      public-key: iBJRXLZwXuWWrOZE1ZrAXEKMgV/z0WjG0Tks5rnWLBI=
      allowed-ips: ['0.0.0.0/0']  
  udp: true


proxy-groups:
  
  - name: "ChatGPT"
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - SF-UK-LD

rules:
  - DOMAIN-SUFFIX,openai.com,ChatGPT
  - DOMAIN-SUFFIX,chatgpt.com,ChatGPT
  - MATCH,DIRECT


```
