### ISSUE TITLE
HY2节点无法打开gmail网页

### ISSUE THREAD

**Issue by wyw1018** [MetaCubeX/mihomo#1071]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

mihomo-v1.18.1-windows-amd64

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
dns:
  enabled: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - tls://1.0.0.1:853
    - tls://dns.google:853
proxies:
  - name: ip
    type: hysteria2
    server: 64.xxx.xxx.11
    port: 3xxxx
    password: xxxxxxxxx
    fast-open: true
    udp: true
    sni: www.bing.com
    skip-cert-verify: true
    up: 30
    down: 100
    alpn:
      - h3
proxy-groups:

rules:
  - DOMAIN-SUFFIX,xxxx.com,DIRECT
  - DOMAIN-SUFFIX,xxxx.net,DIRECT
  - MATCH,ip
```

### Mihomo log

```shell
time="2024-02-29T16:07:37.3029822+:00" level=info msg="[TCP] 127.0.0.1:23823 --> mail.google.com:443 match Match using ip"
time="2024-02-29T16:07:37.5153935+:00" level=info msg="[TCP] 127.0.0.1:23824 --> mail.google.com:443 match Match using ip"
time="2024-02-29T16:07:37.657005+:00" level=info msg="[TCP] 127.0.0.1:23825 --> mail.google.com:443 match Match using ip"
time="2024-02-29T16:07:37.846731+:00" level=info msg="[TCP] 127.0.0.1:23826 --> mail.google.com:443 match Match using ip"
time="2024-02-29T16:07:38.0517869+:00" level=info msg="[TCP] 127.0.0.1:23827 --> mail.google.com:443 match Match using ip"
time="2024-02-29T16:07:38.733431+:00" level=info msg="[TCP] 127.0.0.1:23828 --> mail.google.com:443 match Match using ip"
time="2024-02-29T16:07:38.9259388+08:00" level=info msg="[TCP] 127.0.0.1:23829 --> mail.google.com:443 match Match using ip"
time="2024-02-29T16:07:42.7590617+:00" level=info msg="[TCP] 127.0.0.1:23830 --> mail.google.com:443 match Match using ip"
time="2024-02-29T16:07:42.9529073+:00" level=info msg="[TCP] 127.0.0.1:23831 --> mail.google.com:443 match Match using ip"
time="2024-02-29T16:07:43.1567964+:00" level=info msg="[TCP] 127.0.0.1:23832 --> mail.google.com:443 match Match using ip"
time="2024-02-29T16:07:43.3515612+:00" level=info msg="[TCP] 127.0.0.1:23833 --> mail.google.com:443 match Match using ip"
time="2024-02-29T16:07:44.1635727+:00" level=info msg="[TCP] 127.0.0.1:23834 --> mail.google.com:443 match Match using ip"
time="2024-02-29T16:07:44.354939+:00" level=info msg="[TCP] 127.0.0.1:23835 --> mail.google.com:443 match Match using ip"
```

### Description

一个HY2节点，用clash-verge-rev及windows命令行能打开google搜索及youtube等网站，不能打开gmail网站。显示：无法访问此网站网址为 https://mail.google.com/mail/u/0/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址ERR_FAILED。看log显示其已经使用代理节点连接gmail。用其它某些节点比如vless可以打开gmail，说明可能是节点的问题。

但是用其它代理类型比如sing-box用同一个HY2节点同样配置又能打开gmail，又说明可能是代理类型的问题。

这个问题困扰好长时间了。
