### ISSUE TITLE
[Feature] 基于HTTP的代理集合应当可以把DNS请求从nameserver/fallback策略中独立

### ISSUE THREAD

**Issue by tihSdoolB** [MetaCubeX/mihomo#1074]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

在下面给定的样式中，"DNS代理"需要获取代理节点后生效；如果网络运营商阻断了指定服务器的DNS请求，会导致"somewhere"的代理集合无法正常加载。
```yaml
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  default-nameserver:
    - https://223.5.5.5/dns-query
    # - 114.114.114.114
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://dns.rubyfish.cn/dns-query
    - https://dns.pub/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://dns.rubyfish.cn/dns-query
    - https://dns.pub/dns-query
  fallback:
    - https://1.1.1.1/dns-query#DNS代理
    - https://dns.google/dns-query#DNS代理
    - https://cloudflare-dns.com/dns-query#DNS代理
  fallback-filter:
    domain:
      - example.com
  nameserver-policy:
    'geosite:gfw':
      - https://1.1.1.1/dns-query#DNS代理
      - https://dns.google/dns-query#DNS代理
      - https://cloudflare-dns.com/dns-query#DNS代理
proxy-providers:
  somewhere:
    type: http
    path: ./profile/somewhere.yaml
    url: https://example.com/config.yaml
```

### Possible Solution

建议由proxy-server-nameserver策略组代理集合DNS请求到。
