### ISSUE TITLE
[Bug] geoip问题

### ISSUE THREAD

**Issue by Nine499** [MetaCubeX/mihomo#1083]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-974332c

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
mixed-port: 4949
ipv6: false
log-level: warning
mode: rule
keep-alive-interval: 1800
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: iOS
geox-url:
  geoip: "https://fast.nine499.uk/3aaa9/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://fast.nine499.uk/3aaa9/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://fast.nine499.uk/3aaa9/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb"
geo-auto-update: true
geo-update-interval: 24
dns:
    enable: true
    listen: 0.0.0.0:4953
    ipv6: false
    enhanced-mode: fake-ip
    fake-ip-range: 22.49.0.1/16
    nameserver:
      - https://dns.alidns.com/dns-query#h3=true
49-jiedian: &49-jiedian
  type: http
  interval: 10800
  override:
    skip-cert-verify: true
    udp: true
  health-check:
    enable: true
    interval: 10800
    url: https://cp.cloudflare.com/generate_204
proxy-providers:
    huayun:
        <<: *49-jiedian
        url: "https://api.flowercloud.xyz/"
    bocchi:
        <<: *49-jiedian
        url: "https://bocchi.site/api/v1/client/"
49-xuanze: &49-xuanze
  type: select
  use:
    - huayun
    - bocchi
proxy-groups:
  - name: 49鱼
    <<: *49-xuanze
  - name: 日本媒体
    <<: *49-xuanze
  - name: 台湾媒体
    <<: *49-xuanze
  - name: 大流量下载
    <<: *49-xuanze
49-guize: &49-guize
  behavior: classical
  interval: 10800
  type: http
rule-providers:
  da:
    <<: *49-guize
    url: "https://box.nine499.uk/clash_meta_aaa/rule/app/da.txt"
  jp:
    <<: *49-guize
    url: "https://box.nine499.uk/clash_meta_aaa/rule/app/jp.txt"
  tw:
    <<: *49-guize
    url: "https://box.nine499.uk/clash_meta_aaa/rule/app/tw.txt"
  REJECT49:
    <<: *49-guize
    url: "https://box.nine499.uk/clash_meta_aaa/rule/REJECT.txt"
  PROXY49:
    <<: *49-guize
    url: "https://box.nine499.uk/clash_meta_aaa/rule/PROXY.txt"
  DIRECT49:
    <<: *49-guize
    url: "https://box.nine499.uk/clash_meta_aaa/rule/DIRECT.txt"
rules:
  - AND,((DST-PORT,443),(NETWORK,udp)),REJECT
  - RULE-SET,da,大流量下载
  - RULE-SET,jp,日本媒体
  - RULE-SET,tw,台湾媒体
  - RULE-SET,REJECT49,REJECT
  - RULE-SET,PROXY49,49鱼
  - RULE-SET,DIRECT49,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,49鱼
```

### Description

mmdb: "https://fast.nine499.uk/3aaa9/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb"

只要使用 geoip.metadb 以外的任何文件，GEOIP,CN,DIRECT 就像坏了一样不匹配规则，流量全会流向MATCH。
已测试文件 meta-rules-dat 的 country-lite.mmdb country.mmdb 和 Loyalsoldier/geoip 的 Country-only-cn-private.mmdb

**Comment by rickblue** [comment]
geodata-mode: true
用上面的设置试试，默认是false用.mmdb格式的geoip库，但是我发现这样ip规则不起作用，修改成true也就是使用.dat的格式的就行了，原因未知，用的meta alpha最新版。

**Comment by xuelide** [comment]
同问题，mmdb失效
暂时用geodata-mode: true，配geoip.dat就好了
用的alpha，天天更，大概这5 6天出现的问题

**Comment by wwqgtxx** [comment]
导致问题的commit已被撤销，请更新最新alpha尝试是否恢复正常
https://github.com/MetaCubeX/mihomo/commit/6b74ade897c6b307e068e44cfee96a7b57640685

**Comment by rickblue** [comment]
升级到alpha-6b74ade，问题仍存在，我这里用的clash verge。

**Comment by xishang0128** [comment]
> 升级到alpha-6b74ade，问题仍存在，我这里用的clash verge。

再试试?最近有修改过

**Comment by rickblue** [comment]
> > 升级到alpha-6b74ade，问题仍存在，我这里用的clash verge。
> 
> 再试试?最近有修改过

奇怪，我这里还不行，用的clash verge最新版，内核也是alpha最新版，以下是部分配置：
```
mixed-port: 7891
bind-address: 127.0.0.1
mode: rule
sniffer:
  enable: true
  parse-pure-ip: false
  sniff: {HTTP: {ports: [80, 8080-8880], override-destination: true}, TLS: {ports: [443, 8443]}, QUIC: {ports: [443, 8443]}}
  skip-domain: ['Mijia Cloud']
profile:
  store-selected: true
  store-fake-ip: true
tcp-concurrent: true 
secret: '123456'
external-controller: 127.0.0.1:9090
external-ui: ui/m
external-ui-name: xd
geox-url:
  geosite: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  geoip: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/Country.mmdb"
geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 72
```

**Comment by rickblue** [comment]
仔细查看了连接规则，发现内核已经加载mmdb数据，ip规则已经生效，但web面板（metacubexd、yacd）geoip规则部分都显示0，误导了我，感谢大佬！
另，mmdb和dat用起来用啥大的区别么？

**Comment by xishang0128** [comment]
@rickblue db不会显示数量,只有dat可以

**Comment by rickblue** [comment]
> @rickblue db不会显示数量,只有dat可以
原来这样啊，又学到了，^^……

**Comment by CaoKang-David** [comment]
哪位能解释一下geoip.dat和country.mmdb在性能上有差吗？

**Comment by gemnioo** [comment]
想请问 mihomo 调用 geoip 需要 .dat 和 .mmdb 两个内容一致的文件. 是为了 fallback-filter 使用前者GEOIP,CN,DIRECT 使用后者么？ 
```
geox-url:                           
  geoip: "https://ghp.p3terx.com/https://raw.githubusercontent.com/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://ghp.p3terx.com/https://raw.githubusercontent.com/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://ghp.p3terx.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-only-cn-private.mmdb"
```

我在 openclash 遇到自定义 geoip geosite 出现无法加载的问题 failed to decode geosite file

https://github.com/vernesong/OpenClash/issues/4033
