### ISSUE TITLE
[Bug] Docker 中 TUN 网卡不接受IP而直接转发给下一跳网关。

### ISSUE THREAD

**Issue by confuseder** [MetaCubeX/mihomo#1084]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

v1.18.1

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
######### 锚点 start #######
# proxy 相关
pr: &pr {type: select, proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,DIRECT]}

#这里是订阅更新和延迟测试相关的
p: &p {type: http, interval: 86400, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 36000}}


urltestinterval: &urltest-interval
  type: url-test
  url: 'http://www.gstatic.com/generate_204'
  interval: 300
  lazy: true
######### 锚点 end #######

ipv6: false
allow-lan: true
mixed-port: 7890
unified-delay: false
tcp-concurrent: true
external-controller: 0.0.0.0:9090
secret: "123456"
external-ui: ui

geodata-mode: true
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]

tun:
  enable: true
  dns-hijack:
    - 'any:53'
  stack: system
  auto-route: false
  auto-detect-interface: false

dns:
  enable: true
  ipv6: true
  listen: :53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    "geosite:geolocation-!cn":
      - "https://dns.cloudflare.com/dns-query#dns"
      - "https://dns.google/dns-query#dns"

proxies:

proxy-groups:
  - name: Proxies
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 香港
      - 美国
      - 日本

  - name: 自动选择
    <<: *urltest-interval
    use:
      - renzhe
      - west
      
  - name: 手动选择
    type: select
    use:
      - renzhe
      - west

  - name: 香港
    <<: *urltest-interval
    use:
      - renzhe
      - west
    filter: "港|Hong Kong"

  - name: 美国
    <<: *urltest-interval
    use:
      - renzhe
      - west
    filter: "美|United States"

  - name: 日本
    <<: *urltest-interval
    use:
      - renzhe
      - west
    filter: "日|Japan"
  
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./profiles/ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./profiles/ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./profiles/ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"
    path: ./profiles/ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./profiles/ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./profiles/ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./profiles/ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./profiles/ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt"
    path: ./profiles/ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
    path: ./profiles/ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./profiles/ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./profiles/ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./profiles/ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./profiles/ruleset/applications.yaml
    interval: 86400

rules:
 - DOMAIN-SUFFIX,coze.com,Proxies 
 - DOMAIN-SUFFIX,bulianglin.com,Proxies
 - DOMAIN-SUFFIX,macapp.org.cn,Proxies
 - RULE-SET,applications,DIRECT
 - RULE-SET,private,DIRECT
 - RULE-SET,icloud,DIRECT
 - RULE-SET,apple,DIRECT
 - RULE-SET,google,DIRECT
 - RULE-SET,proxy,Proxies
 - RULE-SET,direct,DIRECT
 - RULE-SET,lancidr,DIRECT
 - RULE-SET,cncidr,DIRECT
 - RULE-SET,telegramcidr,Proxies
 - GEOIP,CN,DIRECT
 - MATCH,Proxies
```

### Description

fake IP的地址段没有被tun接受，核心跑在routeros的docker容器中，一样的配置文件（删除meta特性）clash-premium可以正常

**Comment by xishang0128** [comment]
tun地址是fakeip段的/30,而foss是fakeip range段,所以这是预期行为

**Comment by confuseder** [comment]
那么如何排查错误呢，目前是环路状态

```
+--------+ fake+-----------+ next +----------------+
|clinet  +-----> routeros  +------>docker clash meta
+--------+  ip +---+-------+      +-------+--------+
                   ^                      |
                   |                      |
                   |                      |
                   |                      |
                   +----------------------+
```

目前就是这种状态

**Comment by confuseder** [comment]
另外 routerOS 的docker容器不支持自动路由配置的那个选项，我关掉了。在 clash-premium 内核中这样就可以直接跑

**Comment by xishang0128** [comment]
> 日志中没有明显的报错，这些包都没到tun网卡里，需要手动在容器中写路由表将 fakeip 段发到tun里吗？？

是,主动转发到tun

**Comment by Victor2333** [comment]
docker tun macvlan 自动路由没有把fakeip网段配进去
```yaml
tun:
  enable: true
  stack: system # gvisor / lwip
  auto-detect-interface: true # 自动识别出口网卡
  auto-route: true # 配置路由表
  inet4-route-address: # 启用 auto_route 时使用自定义路由而不是默认路由
    - 198.16.0.0/16
```

ip route
`
198.16.0.0/30 dev Meta scope link  src 10.2.0.0
`
