### ISSUE TITLE
[Bug] Trojan在设置client-fingerprint为chrome时，无法与Sing-Box服务端连通

### ISSUE THREAD

**Issue by jklolixxs** [MetaCubeX/mihomo#1094]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-feedc9e

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
######### 锚点 start #######
# 策略组相关
pr-gb:
  &pr-gb {
    type: select,
    url: https://cp.cloudflare.com/generate_204,
    proxies:
      [
        🪜 Shadowsocks,
        🪜 Trojan,
        🪜 Hysteria 2,
        PASS,
      ],
  }
######### 锚点 end #######
# 订阅
proxy-providers:

proxies:
  # Bandwagonhost
  #=====#=====#=====#=====#=====#=====#=====#=====#=====#=====#
  - {"name":"🇺🇸 BWG-US-Trojan-A","type":"trojan","server":"1.1.1.1","port":"12345","password":"12345","udp":true,"client-fingerprint":"firefox","sni":"12345.com","fingerprint":"B1:25:41","smux":{"enabled":true,"protocol":"h2mux","max-connections":16,"min-streams":4,"padding":true}}
  - {"name":"🇺🇸 BWG-US-Trojan-B","type":"trojan","server":"1.1.1.1","port":"12345","password":"12345","udp":true,"client-fingerprint":"chrome","sni":"12345.com","fingerprint":"B1:25:41","smux":{"enabled":true,"protocol":"h2mux","max-connections":16,"min-streams":4,"padding":true}}
  #=====#=====#=====#=====#=====#=====#=====#=====#=====#=====#
  - {"name":"🇺🇸 US-Hysteria2","type":"hysteria2","server":"1.1.1.1","port":"12356","up":"100 Mbps","down":"500 Mbps","password":"12356","client-fingerprint":"chrome","sni":"12356.com","fingerprint":"B1:25:41"}
proxy-groups:
  # 分组
  - { name: 🚀 Proxy, <<: *pr-gb }

  # 自建
  - name: 🪜 Trojan
    <<: *pr-lite
    proxies:
      - 🇺🇸 US-Trojan-A
      - 🇺🇸 US-Trojan-B
  - name: 🪜 Hysteria 2
    <<: *pr-lite
    proxies:
      - 🇺🇸 US-Hysteria2
```

### Mihomo log

```shell
点击B节点测试的时候，只有如下日志显示，并无其他日志输出


2024-03-09 18:10:09 level=debug msg="use specified fingerprint:Chrome"
2024-03-09 18:10:08 level=debug msg="use specified fingerprint:Chrome"
2024-03-09 18:10:08 level=debug msg="use specified fingerprint:Chrome"
2024-03-09 18:10:07 level=debug msg="use specified fingerprint:Chrome"
2024-03-09 18:10:07 level=debug msg="use specified fingerprint:Chrome"
2024-03-09 18:10:06 level=debug msg="use specified fingerprint:Chrome"
2024-03-09 18:10:06 level=debug msg="use specified fingerprint:Chrome"
2024-03-09 18:10:05 level=debug msg="use specified fingerprint:Chrome"
2024-03-09 18:10:05 level=debug msg="use specified fingerprint:Chrome"
```

### Description

🇺🇸 US-Trojan-A使用了 ```"client-fingerprint":"firefox"```
🇺🇸 US-Trojan-B使用了 ```"client-fingerprint":"chrome"```
测试A的时候，服务端中Sing-Box正常连接，出现ping值
测试B的时候，服务端中Sing-Box报错，inbound/trojan[trojan]: process connection from xxx.xxx.xxx.xxx:51740: tls: peer doesn't support any of the certificate's signature algorithms
Sing-Box为稳定版1.8.8
唯一区别在于今天傍晚使用了metacubexd面板更新了alpha内核，更新后就无法连接了
