### ISSUE TITLE
[Bug] 系统代理部分情况下不能超越系统host文件规则

### ISSUE THREAD

**Issue by hsiayuchih** [MetaCubeX/mihomo#1100]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

v1.18.1

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
mode: rule
mixed-port: 7897
allow-lan: false
log-level: info
secret: ''
external-controller: 127.0.0.1:9097
dns:
  enable: true
  listen: 127.0.0.1:8853
  default-nameserver:
  - 223.5.5.5
  - 8.8.4.4
  ipv6: false
  enhanced-mode: fake-ip
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
  - tls://223.5.5.5:853
  - tls://223.6.6.6:853
  - tls://120.53.53.53
  - tls://1.12.12.12
  fallback:
  - https://1.0.0.1/dns-query
  - https://public.dns.iij.jp/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
    - 127.0.0.1/32
```

### Description

当在host文件中写入一个域名，指定其为不属于clash verge rev（一个使用meta内核的衍生版本）所使用的ip。然后在clash配置文件中写入这个域名（任何规则），启动clash verge rev系统代理后，软件不会接管这个域名的连接，导致浏览器访问失败。
1.在host文件中写入一个域名，注意要不属于clash verge rev所使用的系统代理ip。如系统代理ip为：127.0.0.1，则实验的域名应为127.0.0.2 twitch.tv。
2.在clash配置文件中写入这个域名（任何规则）如 - DOMAIN-SUFFIX,twitch.tv,Shark Cloud。（注：此规则为我机场的原始配置文件）
3.启动clash verge rev系统代理
4.使用浏览器或者是使用软件引入的测试功能进行测试
5.现象产生，出现HTTP ERROR 502，测试功能显示time out
![image](https://github.com/MetaCubeX/mihomo/assets/21278771/7651144c-f3c4-47a0-984f-7be0ff040e42)
![image](https://github.com/MetaCubeX/mihomo/assets/21278771/a2934c82-3e68-4c6c-828c-0ca73887590b)

**目前只有clash verge rev出现这种问题，已停更的clash verge（也是使用的meta内核，最后一个版本是去年十月底），clash nyanpasu没有这种问题（使用clash premium 2023-09-05和Clash Rust这两个内核就正常，但是切换成meta内核也是会有一样的情况）。**
**所以是不是可以理解meta内核在后续的更新中，是否改动过一些配置导致原有可以超过hosts规则的功能失效了呢？或者是直接取消了这个功能？**
