### ISSUE TITLE
开启TUN模式后，虚拟网卡显示无法连接至ipv6[Bug] 

### ISSUE THREAD

**Issue by AquaSimulacra** [MetaCubeX/mihomo#1105]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.18.1

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
mode: rule
mixed-port: 7897
socks-port: 7898
port: 7899
allow-lan: true
log-level: info
ipv6: true
secret: ''
external-controller: 127.0.0.1:9097
tun:
  auto-detect-interface: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  mtu: 9000
  stack: system
  strict-route: false
  enable: true
redir-port: 7892
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 8.8.8.8
  fallback: []
  fake-ip-filter:
  - dns.msftncsi.com
  - www.msftncsi.com
  - www.msftconnecttest.com
```

### Description

https://github.com/clash-verge-rev/clash-verge-rev/issues/579
