### ISSUE TITLE
[Bug] 最新Alpha版本wireguard协议异常

### ISSUE THREAD

**Issue by PctAIGM** [MetaCubeX/mihomo#1121]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta alpha-284b01c windows amd64 with go1.22.1 Thu Mar 21 04:25:37 UTC 2024

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
- name: warpchain
    type: wireguard
    server: engage.cloudflareclient.com
    port: 2408
    public-key: xxxxx
    private-key: xxxxx
    ip: 172.16.0.1
    ipv6: fd00:172:16::1
    udb: true
    reserved: [xxx,xxx,xxx]
```

### Mihomo log

```shell
03-21 16:38:58ERROR
[WG](warpchain) connect to server: dns resolve failed: ip version error

03-21 16:39:28ERROR
[WG](warpchain) peer(Ecqn…ls18) - Failed to send handshake initiation: dns resolve failed: ip version error
```

### Description

日志不停的刷，停不下来。

**Comment by wwqgtxx** [comment]
fixed in: https://github.com/MetaCubeX/mihomo/commit/9c08e936f971e4261e854d7bf039e28ab3eb9593

**Comment by thomasTAT** [comment]
你好，手机流量下 Clash meta for andriod + WireGuard 正常连接，切换后WiFi断连，需要重启 clash 才能恢复连接，请问你有遇到过吗？https://github.com/MetaCubeX/mihomo/discussions/1810



# 完整配置信息：
```
#clash config

proxies:

- name: "SF-UK-LD"
  type: wireguard
  ip: 10.14.0.2
  private-key: dfjashdjfjkdsfhjkdshfjkdhjkfhkdjfdfhdjfhdjfhd
  peers:
    - server: uk-lon.prod.surfshark.com
      port: 51820
      public-key: iBJRXLZwXuWWrOZE1ZrAXEKMgV/z0WjG0Tks5rnWLBI=
      allowed-ips: ['0.0.0.0/0']  
  udp: true


proxy-groups:
  
  - name: "ChatGPT"
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - SF-UK-LD

rules:
  - DOMAIN-SUFFIX,openai.com,ChatGPT
  - DOMAIN-SUFFIX,chatgpt.com,ChatGPT
  - MATCH,DIRECT


```
