### ISSUE TITLE
[Bug] 更新内核版本后，Win/Linux同一份配置文件启动报错 "Parse config error: proxy 0: missing local address"

### ISSUE THREAD

**Issue by YuukiHibiki** [MetaCubeX/mihomo#1123]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Windows: Mihomo Meta alpha-9c08e93 windows amd64 with go1.22.1 / Linux: metacubex/mihomo:Alpha

### What OS are you seeing the problem on?

Windows, Linux

### Mihomo config

```yaml
#https://github.com/MetaCubeX/mihomo/blob/Meta/docs/config.yaml
mixed-port: 7890
allow-lan: true
bind-address: "*"
lan-allowed-ips:
  - 0.0.0.0/0
  - ::/0
mode: rule
log-level: info
ipv6: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ./webui_metacubexd
global-client-fingerprint: chrome
geodata-mode: true
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.\
    mmdb"
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
tun:
  enable: false
  stack: system
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true
dns:
  enable: true
  listen: :53
  ipv6: false
  enhanced-mode: fake-ip
  use-hosts: true
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '+.lan'
    - '+.local'
  default-nameserver:
    # - 114.114.114.114
    # - 8.8.8.8
    # - tls://223.5.5.5:853
    # - https://223.5.5.5/dns-query
    - 223.5.5.5
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "rule-set:lan":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    "rule-set:terminal":
      #- 8.8.8.8
      - 'https://dns.cloudflare.com/dns-query#🚀 Proxy'
      - 'https://dns.google/dns-query#🚀 Proxy'
```

### Mihomo log

```shell
time="2024-03-22T14:44:41.3944684+08:00" level=info msg="Start initial configuration in progress"
time="2024-03-22T14:44:41.4119562+08:00" level=fatal msg="Parse config error: proxy 0: missing local address"
```

### Description

Linux：更新探针拉取最新的Alpha后重启崩溃并打印日志
Win: metacubexd的gui点击更新内核后重启崩溃并打印日志
Latest/1.18.1 暂未遇到此问题

**Comment by fakeboboliu** [comment]
本节点 ip 现在必须在根 wg 节点配置：

```yaml
proxies:
  - name: wg
    type: wireguard
    peers:
      - server: server
        port: port
        ip: 192.168.1.9/32
        allowed_ips: ['192.168.1.1/24']
```

现在应该是

```yaml
proxies:
  - name: wg
    type: wireguard
    ip: 192.168.1.9/32
    peers:
      - server: server
        port: port
        allowed_ips: ['192.168.1.1/24']
```

参考 #522
