### ISSUE TITLE
[Bug] panic: interface conversion: net.Addr is *net.IPAddr, not *net.IPNet

### ISSUE THREAD

**Issue by NavyD** [MetaCubeX/mihomo#1130]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta v1.18.1 windows amd64 with go1.21.6 Fri Feb  2 12:19:51 UTC 2024 Use tags: with_gvisor

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
mixed-port: 7890
mode: rule
log-level: debug
allow-lan: false
bind-address: "*"
external-controller: 0.0.0.0:9090
ipv6: true
profile:
  store-selected: true
  store-fake-ip: true
find-process-mode: strict
tcp-concurrent: true
keep-alive-interval: 30
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: false
  override-destination: false
  sniff:
    QUIC: null
    TLS: null
    HTTP:
      ports:
        - 80
        - 8080-8880
      override-destination: true
  force-domain:
    - +.netflix.com
    - +.nflxvideo.net
    - +.amazonaws.com
    - +.media.dssott.com
  skip-domain:
    - +.apple.com
    - Mijia Cloud
    - dlg.io.mi.com
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
  mtu: 1500
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:53
  use-hosts: true
  prefer-h3: true
  default-nameserver:
    - tls://223.5.5.5:853
    - tls://119.29.29.29:853
  nameserver:
    - tls://dns.quad9.net#DIRECT
    - tls://8.8.4.4#DIRECT
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    "rule-set:cn-site,private-site":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
# ...
```

### Mihomo log

```shell
time="2024-03-24T16:36:15.9969918+08:00" level=info msg="Start initial configuration in progress"
time="2024-03-24T16:36:16.0152836+08:00" level=warning msg="Skip start health check timer due to it's started"  
time="2024-03-24T16:36:16.0158514+08:00" level=info msg="Geodata Loader mode: standard"
time="2024-03-24T16:36:16.0164282+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-03-24T16:36:16.039224+08:00" level=info msg="Initial configuration complete, total time: 25ms"
time="2024-03-24T16:36:16.039224+08:00" level=info msg="Sniffer is loaded and working"
time="2024-03-24T16:36:16.039224+08:00" level=info msg="Use tcp concurrent"
time="2024-03-24T16:36:16.0409238+08:00" level=info msg="RESTful API listening at: [::]:10855"
time="2024-03-24T16:36:16.0414339+08:00" level=info msg="DNS server listening at: [::]:53"
time="2024-03-24T16:36:16.0420867+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:7890"       
time="2024-03-24T16:36:16.0448547+08:00" level=warning msg="[TUN] default interface changed by monitor,  => WLAN"
time="2024-03-24T16:36:16.6061943+08:00" level=info msg="[TUN] Tun adapter listening at: Meta([198.18.0.1/30],[]), mtu: 1500, auto route: true, ip stack: gVisor"
time="2024-03-24T16:36:16.6227068+08:00" level=info msg="Start initial provider SF-ALL"
time="2024-03-24T16:36:16.6242681+08:00" level=warning msg="[Provider] SF-ALL not updated for a long time, force refresh"
time="2024-03-24T16:36:16.6574402+08:00" level=info msg="Start initial provider JKL-ALL"
time="2024-03-24T16:36:16.658729+08:00" level=warning msg="[Provider] JKL-ALL not updated for a long time, force refresh"
panic: interface conversion: net.Addr is *net.IPAddr, not *net.IPNet

goroutine 195 [running]:
github.com/metacubex/mihomo/component/iface.ResolveInterface.func1()
        github.com/metacubex/mihomo/component/iface/iface.go:48 +0x552
github.com/metacubex/mihomo/common/singledo.(*Single[...]).Do(0xc000435d00, 0x1ed7338?)
        github.com/metacubex/mihomo/common/singledo/singledo.go:46 +0x197
github.com/metacubex/mihomo/component/iface.ResolveInterface({0xc000228078, 0x4})
        github.com/metacubex/mihomo/component/iface/iface.go:28 +0x35
github.com/metacubex/mihomo/component/dialer.bindIfaceToDialer({0xc000228078?, 0xc0004081f0?}, 0xc0002549a0, {0x202b410?, 0x0?}, {{0xc0004081dd?, 0x0?}, 0x0?})
        github.com/metacubex/mihomo/component/dialer/bind_windows.go:80 +0x2f
github.com/metacubex/mihomo/component/dialer.dialContext({0x2042a60, 0xc000254930}, {0x1e559f0, 0x3}, {{0x0?, 0x0?}, 0xc000004060?}, {0xc0004081dd, 0x3}, 0xc0004b1e60)
        github.com/metacubex/mihomo/component/dialer/dialer.go:150 +0x283
github.com/metacubex/mihomo/component/dialer.parallelDialContext.func1({0x2042a60?, 0xc000254930?}, {{0x0?, 0x0?}, 0xc000004060?})
        github.com/metacubex/mihomo/component/dialer/dialer.go:284 +0xfd
created by github.com/metacubex/mihomo/component/dialer.parallelDialContext in goroutine 194
        github.com/metacubex/mihomo/component/dialer/dialer.go:288 +0x245
```

### Description

在笔记本的windows 11上仅使用WIFI连接网络，再到`设置->网络和Internet->移动热点`开启热点后（想让手机连接笔记本的WIFI热点共享），启动mihomo在解析网络接口时出错:`panic: interface conversion: net.Addr is *net.IPAddr, not *net.IPNet`。关闭WIFI热点后可正常使用

在代码https://github.com/MetaCubeX/mihomo/blob/a034421a58674dd80399702de657250910bfeac3/component/iface/iface.go#L48 中的部分返回的不是net.IPNet而是`net.Addr(*net.IPAddr) *{IP: net.IP len: 16, cap: 16, [36,9,138,85,56,137,46,53,0,0,0,0,0,0,0,0], Zone: ""}`导致的问题。

如果尝试忽略这个地址似乎会导致流量循环，连接迅速增加直到崩溃。下面是部分debug截图数据

![image](https://github.com/MetaCubeX/mihomo/assets/22490764/ff0aa8f8-9620-469a-b862-1a43df1d5cff)

windows版本

```
版本	Windows 11 专业版
版本	23H2
安装日期	‎2022/‎9/‎28
操作系统版本	22631.3296
体验	Windows Feature Experience Pack 1000.22687.1000.0

```
