### ISSUE TITLE
谁有vmess+ws+tls+伪装域名的配置例子？不通啊

### ISSUE THREAD

**Issue by joshatt** [MetaCubeX/mihomo#115]
```
proxies:
  # vmess
  # cipher支持 auto/aes-128-gcm/chacha20-poly1305/none
  - name: opentunnelus
    type: vmess
    server: myserver
    port: 443
    uuid: a40d34c6-b77c-4648-9210-3e8d2f4226b5
    alterId: 16
    cipher: auto
    # udp: true
    tls: true
    skip-cert-verify: true
    # servername: example.com # priority over wss host
    network: ws
    ws-opts:
      path: /mypath
      headers:
        Host: myfakehost
    #   max-early-data: 2048
    #   early-data-header-name: Sec-WebSocket-Protocol
```
其他协议我试通了， 就是这个vmess不通，求指点
