### ISSUE TITLE
[Bug] meta内核+hysteria2速度上不去

### ISSUE THREAD

**Issue by pctoolsx** [MetaCubeX/mihomo#1154]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-g56ed901

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
secret: '123456'
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: false
unified-delay: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
sniffer:
  enable: true
  parse-pure-ip: true
tun:
  enable: true
  stack: mixed
  device: utun
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
profile:
  store-selected: true
  store-fake-ip: true
```

### Description

在Openclash中开启meta内核，使用自建的vps，hysteria2协议（hy2官方脚本搭建，单端口），用speedtest测速最高只能到200Mbps，下载大概10M/s。  同样的节点，使用shadowrocket，能跑到900Mbps，下载稳定在70-90M/s。 全天任何时段多次测试都是同样的结果。
软路由是J4125 x86的，Openclash是0.46.005，Meta内核也更新到了alpha-g56ed901，还是速度上不去。
