### ISSUE TITLE
[Bug] folded style的yaml名称没有冲突报错名称冲突

### ISSUE THREAD

**Issue by dongchengjie** [MetaCubeX/mihomo#1156]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.18.2

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
两个名称明明不相等的proxy，硬说冲突
经查证发现只有folded style的时候才会出现这种情况
1111和111_1怎么就相等了？？？而给111_1加上引号却又不相等了？
1111有引号为视为string，但111_1有下划线就可省略引号视为string，无论如何这两个说相等都说不过去吧
```

### Mihomo log

```shell
time="2024-04-01T22:52:21.9353858+08:00" level=fatal msg="Parse config error: proxy 1111 is the duplicate name"
```

### Folded style，报错"proxy 1111 is the duplicate name"
```
mode: rule

proxies:
- name: 111_1
  type: vmess
  server: 154.44.16.241
  port: 55542
  cipher: auto
  uuid: d331e15d-3849-4f7c-b5c2-b29b69620085
  alterId: 0
  tls: false
  skip-cert-verify: true
  network: tcp
- name: '1111'
  type: vmess
  server: 168.235.82.103
  port: 16123
  cipher: auto
  uuid: fa09f016-0460-4bcf-d209-197b7f3d270e
  alterId: 0
  tls: false
  skip-cert-verify: true
  network: tcp
```
### Inline style，可以正常启动，且可以正常测速
```
mode: rule

proxies:
  - {'name': '111_1', 'type': 'vmess', 'server': '154.44.16.241', 'port': 55542, 'cipher': 'auto', 'uuid': 'd331e15d-3849-4f7c-b5c2-b29b69620085', 'alterId': 0, 'tls': false, 'skip-cert-verify': true, 'network': 'tcp'}
  - {'name': '1111', 'type': 'vmess', 'server': '168.235.82.103', 'port': 16123, 'cipher': 'auto', 'uuid': 'fa09f016-0460-4bcf-d209-197b7f3d270e', 'alterId': 0, 'tls': false, 'skip-cert-verify': true, 'network': 'tcp'}

```
