### ISSUE TITLE
[Bug] 节点组内 proxies 和 use 字段里的节点顺序颠倒了

### ISSUE THREAD

**Issue by Brbrbr1995** [MetaCubeX/mihomo#1164]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
proxy-groups:

  - name: 'DNS'
    type: select
    disable-udp: false
    proxies:
      - DIRECT
      - REJECT
      - 手选
    use:
      - 节点订阅
```

### Description

之前是proxies 在前，现在反过来了，use 在前没办法自定节点组默认项
或者有能设置优先级的办法也好
