### ISSUE TITLE
配置文件中出站代理的ip-version选项的含义

### ISSUE THREAD

**Issue by smy116** [MetaCubeX/mihomo#1166]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

v1.18.3

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
proxies:
  - name: vmess-grpc
    server: server
    port: 443
    type: vmess
    uuid: uuid
    alterId: 32
    cipher: auto
    network: grpc
    tls: true
    fingerprint: xxxx
    servername: example.com
    skip-cert-verify: true
    grpc-opts:
      grpc-service-name: "example"
    ip-version: ipv4
```

### Description

Mihomo的配置文件可以为每一个出站代理设置ip-version选项，文档中描述为"_设置节点使用 IP 版本，可选：dual/ipv4/ipv6/ipv4-prefer/ipv6-prefer,默认使用dual_"。
想了解一下这个选项是设置客户端连接**代理服务器节点**时使用的IP版本，还是代理服务器连接**最终访问网站**所使用的IP版本？
