### ISSUE TITLE
[Bug] when enabled tun, built-in dns won't honor windows routing table when querying

### ISSUE THREAD

**Issue by TTTPOB** [MetaCubeX/mihomo#1167]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta v1.18.2 windows amd64 with go1.22.1 Wed Mar 27 11:22:44 UTC 2024 Use tags: with_gvisor

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  prefer-h3: true
  proxy-server-nameserver:
  - tls://1.12.12.12
  - tls://120.53.53.53
  nameserver:
  - tls://1.0.0.1
  nameserver-policy:
    +.xx.yy: 192.168.1.134 # the lan dns server
    geosite:cn:
    - tls://1.12.12.12
    - tls://120.53.53.53

tun:
  stack: mixed
  device: Meta
  auto-route: true
  auto-detect-interface: true
  inet4-route-exclude-address:
  - 192.168.1.0/24
  dns-hijack:
  - any:53
  strict-route: false
  mtu: 9000
  enable: true
```

### Description

the alpha version I tried is "Mihomo Meta alpha-c44949b windows amd64 with go1.22.1 Sat Apr  6 21:30:53 UTC 2024
Use tags: with_gvisor"

I have a wireguard in my system with 192.168.5.200 as ip address, and route 192.168.1.0/24 through it. this is my lan of my lab.

as you've seen in my config, I have excluded the lan cidr in tun config, and I can verify the system routing table is as expected
```
❯ route print -4|rg 192.168
      192.168.0.0    255.255.255.0            在链路上        198.18.0.1      0
    192.168.0.255  255.255.255.255            在链路上        198.18.0.1    256
      192.168.1.0    255.255.255.0            在链路上     192.168.5.200   5000
    192.168.1.123  255.255.255.255            在链路上     192.168.5.200   5000
    192.168.1.131  255.255.255.255            在链路上     192.168.5.200   5000
    192.168.1.133  255.255.255.255            在链路上     192.168.5.200   5000
    192.168.1.134  255.255.255.255            在链路上     192.168.5.200   5000
    192.168.1.255  255.255.255.255            在链路上     192.168.5.200   5256
      192.168.2.0    255.255.254.0            在链路上        198.18.0.1      0
    192.168.3.255  255.255.255.255            在链路上        198.18.0.1    256
      192.168.4.0    255.255.252.0            在链路上        198.18.0.1      0
      192.168.5.0    255.255.255.0            在链路上     192.168.5.200   5000
    192.168.5.200  255.255.255.255            在链路上     192.168.5.200   5256
    192.168.5.255  255.255.255.255            在链路上     192.168.5.200   5256
    192.168.7.255  255.255.255.255            在链路上        198.18.0.1    256
      192.168.8.0    255.255.248.0            在链路上        198.18.0.1      0
   192.168.15.255  255.255.255.255            在链路上        198.18.0.1    256
     192.168.16.0    255.255.240.0            在链路上        198.18.0.1      0
   192.168.31.255  255.255.255.255            在链路上        198.18.0.1    256
     192.168.32.0    255.255.224.0            在链路上        198.18.0.1      0
   192.168.63.255  255.255.255.255            在链路上        198.18.0.1    256
     192.168.64.0    255.255.192.0            在链路上        198.18.0.1      0
  192.168.127.255  255.255.255.255            在链路上        198.18.0.1    256
    192.168.128.0    255.255.128.0            在链路上        198.18.0.1      0
  192.168.255.255  255.255.255.255            在链路上        198.18.0.1    256
```

normal tcp and udp packets will bypass the tun adapter
![image](https://github.com/MetaCubeX/mihomo/assets/19909103/251a750d-7113-44d4-995e-326d1926a52d)
![image](https://github.com/MetaCubeX/mihomo/assets/19909103/193edeff-9153-4042-8971-d20ad23eb684)

but when doing nslookup with tun enabled, 
![image](https://github.com/MetaCubeX/mihomo/assets/19909103/ffc475e1-e0c9-463a-a248-0fb4542200ef)
and at the same time I can capture dns request sent through my wifi in wireshark
![image](https://github.com/MetaCubeX/mihomo/assets/19909103/51e48ffe-5287-41d0-8a60-78c83339fe54)

so I believe there are something unusual in dns resolving in mihomo. I think dns resolving should honor the routing table as well.
