### ISSUE TITLE
[Feature] 添加开关,将relay默认使用tunnel或者dailer_proxy处理

### ISSUE THREAD

**Issue by lovitus** [MetaCubeX/mihomo#1176]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

## 背景:

因为有复杂的路由选择,以及公共节点和私有节点融合。
所以配置里充满了**大量的 url-test和relay**, 因为有一些情形造成极少windows设备还在cfw，但是因为大部分设备都在使用mihomo，已经想**将所有relay转成dialer_proxy**了。 但是转换和后续的维护成本过高

## 可能的优化方案
配置里加入`relay_optimize: true`
### 示例数据
```
#relay_optimize: true
proxy-groups:
  - name: relay-warp从机场中转
    proxies:
      - 1机场nodes
      - 2落地warp
    type: relay
```
mihomo 将
- 找到relay的最后一跳(出口)的proxy
- 复制它,名字为`relay-warp从机场中转` (与relay同名),**替代原有的relay**
- 在这个proxy后面追加`dialer-proxy: 1机场nodes`
就完成了relay-->dailer_proxy的替代

## 好处
- 过渡期的配置可以兼容
- 更好的连接性能
- 更好的udp支持
- 
## 可能存在的问题
- 可能有用户的relay不是一跳,而是多个节点串联, 我这边没有这种场景.
- 上面提出的是一个用户觉得可行的优化方案,**作者或者其他有能力贡献代码的用户,可能有更加优雅的解决方案** 😀
