### ISSUE TITLE
[Bug]  1.18.3 tun模式使用完所有内存

### ISSUE THREAD

**Issue by lovitus** [MetaCubeX/mihomo#1178]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.18.3

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
proxy-providers:
...
rule-providers:
...
rules:
...
  - GEOIP,CN,🎯 全球直连
  - MATCH,🐟 漏网之鱼
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
secret: "123456"
bind-address: "*"
ipv6: true
dns:
    enable: true
    ipv6: false
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: [119.29.29.29, 223.5.5.5, 156.154.70.1, 1.0.0.1]
    fallback: ['208.67.222.222:5353', '208.67.220.220:5353', '208.67.222.220:5353', '208.67.220.222:5353', 'https://1.1.1.1/dns-query', 'https://1.1.1.2/dns-query', 'https://1.1.1.3/dns-query', 'https://1.0.0.1/dns-query', 'https://1.0.0.2/dns-query', 'https://1.0.0.3/dns-query', 'https://45.11.45.11/dns-query', 'https://146.112.41.2/dns-query', 'https://162.159.36.1/dns-query', 'https://162.159.46.1/dns-query', 'https://9.9.9.11:5053/dns-query', 'https://101.6.6.6:8443/dns-query', 'https://208.67.222.222/dns-query', 'https://208.67.220.220/dns-query', 'https://185.222.222.222/dns-query', 'https://101.101.101.101/dns-query', 'https://149.112.112.11:5053/dns-query']
    fallback-filter: null
    geoip: true
    ipcidr: [240.0.0.0/4]
profile:
  store-selected: true
```

### Description

ipv6启用√， lan启用√，tun启用√，系统代理启用√。
mihomo：1.18.3 ， alpha：72df27b
可能相关的issue：
- https://github.com/MetaCubeX/mihomo/issues/926

启用tun以后， 两分钟就用了11G，所有内存都用完， 
使用alpha版本也是一样。 
切回clash premium内核则内存稳定60M

![image](https://github.com/MetaCubeX/mihomo/assets/14361541/75138881-bdb9-4131-ab2f-9e680c666480)
