### ISSUE TITLE
在启用dns:["enable": true]自定义DNS时,DNS解析出IP地址,但显示i/o timeout

### ISSUE THREAD

**Issue by tanmoumou252** [MetaCubeX/mihomo#1195]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.18.3

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:8053
  default-nameserver :
    - 1.1.1.1
    - 223.5.5.5
  enhanced-mode: fake-ip
  # 配置不使用fake-ip的域名
  fake-ip-filter:
    - '+.*'
    - '*.lan'
    - localhost.ptlogin2.qq.com
  nameserver:
    - 223.5.5.5
    - 1.1.1.1
    - 8.8.8.8
    - 114.114.114.114
    - 119.29.29.29
  fallback:   # 与 nameserver 内的服务器列表同时发起请求，当规则符合 GEOIP 在 CN 以外时，fallback 列表内的域名服务器生效。    
    - https://dns.google/dns-query
    - https://1.1.1.1/dns-query
    - tcp://8.8.8.8:53
    - tcp://8.8.4.4:53
    - tcp://208.67.222.222:443
    - tcp://208.67.220.220:443
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.googleapis.com'
      - '+.youtube.com'
      - '+.appspot.com'
      - '+.telegram.com'
      - '+.facebook.com'
      - '+.twitter.com'
      - '+.blogger.com'
      - '+.gmail.com'
      - '+.gvt1.com'

rules: #-Lan_CN *为省略,非通配符
  - DOMAIN-SUFFIX,*.com #CF托管
  - DOMAIN,*.v6.army #dynv6二级域名
```

### Mihomo log

```shell
dial DIRECT (match RuleSet/Lan_CN) 192.168.123.1:4486 --> *.v6.army:8920 error: connect failed: dial tcp [ipv6]:8920: i/o timeout
```

### Description

1. 该报错域名为dynv6申请的二级域名,端口上是自己搭建的jellyfin服务器.访问环境为内网或者本机. 
2. 若在yaml中删除整段DNS的配置,则解析正常. 未删除时设置的223.5.5.5和1.1.1.1亦为电脑和路由器的DNS服务器,所以即便在配置中不自定义DNS,直连解析域名的时候使用的也应该是阿里和CF的解析,更何况已经解析到IP地址了.
3. 与此同时还有一个CF托管的一级域名,其和dynv6没有区别,实际IP地址,访问的端口均相同,二者均已存在已解析的DNS记录.而该域名则没有i/o timeout的报错. 

该问题在cmfa 2.10.0 上也存在,为什么相同IPv6相同端口的两个域名,在解析出实际IP的情况下,一个会报错,一个正常. 
禁用自定义dns虽然会正常,但实际使用的dns和被禁用的dns却又是相同的
