### ISSUE TITLE
[Feature] 能否让某些域名优先走IPv6

### ISSUE THREAD

**Issue by LordHumphrey** [MetaCubeX/mihomo#1199]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

在规则匹配中，可以选择匹配某些域名优先走ipv6，对于ipv6线路，直连国外某些网站效果出奇的好，但是如果设置了网卡ipv4-perfer，这些网站都会走ipv4，所以或许可以设计一个某些域名走ipv6的功能。

**Comment by ObcbO** [comment]
@LordHumphrey 刚好和我的需求不谋而合啊！

**Comment by xishang0128** [comment]
@LordHumphrey https://wiki.metacubex.one/config/proxies/#ip-version

**Comment by LordHumphrey** [comment]
> @LordHumphrey https://wiki.metacubex.one/config/proxies/#ip-version

之前看过这条，您这次发，我发现好像可以再设置一个网卡出站，设置为v6优先，然后用域名匹配？

**Comment by LordHumphrey** [comment]
```YAML
proxies:
  - name: "XGbPort1-IPv6-Prefer"
    type: direct
    udp: true
    tfo: true
    mptcp: true
    ip-version: ipv6-prefer
```
可以设置一个上面的proxy，然后在规则里让他走该节点，但是我刚刚试了，好像没啥作用...
