### ISSUE TITLE
[Bug] DNS over QUIC无法走代理

### ISSUE THREAD

**Issue by wind0fchange** [MetaCubeX/mihomo#1203]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-gfeedc9e

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
dns:
  enable: true
  ipv6: true
  listen: :23453
  enhanced-mode: redir-host
  prefer-h3: true
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query#h3=true
  nameserver-policy:
    geosite:geolocation-cn:
      - quic://223.5.5.5
  nameserver:
    - https://1.1.1.1/dns-query#h3=true&Proxy

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - ss1
      - ss2
```

### Description

如果dns设置为quic协议时，比如`quic://1.1.1.1#Proxy`或者`quic://1.1.1.1/#Proxy`则dns无法请求成功（我怀疑是dns没有被代理成功），但设置为doh时后面加`#Proxy`是可以代理dns的。
