### ISSUE TITLE
[Bug] 配置文件alpn数组,单个元素无法使用单行定义

### ISSUE THREAD

**Issue by dongchengjie** [MetaCubeX/mihomo#1206]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.18.3

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
proxies:
  - {
      name: '自动最优线路(新协议)-网址: dg1.top',
      type: hysteria,
      server: example.com,
      auth_str: 12345678-1234-1234-1234-12345678,
      alpn: h3,
      protocol: udp,
      up: 70,
      down: 150,
      fast-open: true,
      disable_mtu_discovery: true,
      skip-cert-verify: true,
      port: 13324,
      ports: 5000-20000
    }
```

### Mihomo log

```shell
time="2024-04-21T09:50:44.8836134+08:00" level=info msg="Start initial configuration in progress"
time="2024-04-21T09:50:44.9359969+08:00" level=fatal msg="Parse config error: proxy 29: 'alpn' is not a slice"
```
![image](https://github.com/MetaCubeX/mihomo/assets/37543964/ff9dd5c1-ff43-49ad-be8e-54338fb746ba)

### Description

配置如上，alpn数组无法使用单行写法
导致verge可以正确启动（因为需要二次解析合并），而裸核心无法启动
正常情况不，单个元素是有三种写法吗（这里省略引号）
```
alpn: [h3]
```
```
alpn: h3
```
```
alpn: 
  - h3
```
