### ISSUE TITLE
[Bug] DNS的解析与连接问题

### ISSUE THREAD

**Issue by rioufbi** [MetaCubeX/mihomo#1208]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.18.3

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
dns:
    enable: true
    ipv6: false
    default-nameserver: [ 127.0.0.1 , 223.5.5.5 , 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['tls://1.0.0.1:853', 'https://cloudflare-dns.com/dns-query', 'https://dns.google/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
```

### Mihomo log

```shell
4400	[warning]	[TCP] dial 漏网之鱼 (match Match/) 127.0.0.1:51880(chrome.exe) --> 55app.shop:443 error: connect failed: dial tcp [2607:f8b0:4005:802::200e]:443: i/o timeout connect failed: dial tcp 142.250.188.14:443: i/o timeout
4215	[debug]	[DNS] 55app.shop --> [118.107.10.138 216.83.52.220 202.61.141.209 202.61.141.203 172.247.242.179 23.224.179.148 118.107.10.119] A from https://doh.pub:443/dns-query
```

### Description

上面的日志可以看出要解析的域名是55app.shop
从域名服务器那里解析出来的是118.107.10.138 216.83.52.220 202.61.141.209 202.61.141.203 172.247.242.179 23.224.179.148 118.107.10.119
里面也没有142.250.188.14 更没有IPV6的地址 2607:f8b0:4005:802::200e
但是建立的连接是 2607:f8b0:4005:802::200e  142.250.188.14 这两个地址
在关闭了mihomo后可以正常访问这个网站。
采用的DNS配置也写在上方了。
