### ISSUE TITLE
[Bug] url-test分组中COMPATIBLE被选中, 流量无法经过代理

### ISSUE THREAD

**Issue by derry96** [MetaCubeX/mihomo#1215]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.18.3

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
p: &p {proxies: [🇨🇳 HK, 🇨🇳 TW, 🇯🇵 JP, 🇸🇬 SG, 🇺🇸 US, 🌍 Other]}

ut: &ut {type: url-test, tolerance: 100}

use: &use {use: [fly]}

pp: &pp
  type: http
  interval: 21600
  health-check:
    enable: true
    interval: 300
    url: https://cp.cloudflare.com

mode: rule
ipv6: true
mixed-port: 7890
log-level: warning
external-controller: 0.0.0.0:9090
# external-ui: /usr/share/yacd/
tcp-concurrent: true
profile:
  store-selected: true
  store-fake-ip: true

proxy-groups:
  - {name: "PROXY", type: select, proxies: [DIRECT,🎯 Select,🥇 Auto,🌏 Fallback]}
      
  - {name: "🌏 Fallback", type: fallback, <<: *p}
  - {name: "🥇 Auto", <<: [*ut, *p]}
  - {name: "🎯 Select", type: select, <<: *p}

  - {name: "🇨🇳 HK", filter: "(?i)港|hk|hongkong|hong kong", <<: [*ut, *use]}
  - {name: "🇨🇳 TW", filter: "(?i)台|tw|taiwan", <<: [*ut, *use]}
  - {name: "🇯🇵 JP", filter: "(?i)日本|jp|japan", <<: [*ut, *use]}
  - {name: "🇸🇬 SG", filter: "(?i)^(?!.*(?:us)).*(新|sg|singapore)", <<: [*ut, *use]}
  - {name: "🇺🇸 US", filter: "(?i)美|us|unitedstates|united states", <<: [*ut, *use]}
  - {name: "🌍 Other", filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*", <<: [*ut, *use]}
   
proxy-providers:
  fly: {url: "https://suo.yt", path: ./proxies/fly.yaml, <<: *pp}
```

### Description

🥇 Auto分组下, url-test自动选择了无节点的分组 (🇨🇳 TW), 导致COMPATIBLE被选中, 流量无法经过代理
建议: 能否支持自动移除空节点的功能, 使空节点分组不参与url-test
