### ISSUE TITLE
[Bug] 当启用Tun模式后，无法连接Hysteria2节点。

### ISSUE THREAD

**Issue by QijYooRytowYum** [MetaCubeX/mihomo#1221]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta v1.18.3 windows amd64 with go1.20.14 Fri Mar 29 11:57:58 UTC 2024 Use tags: with_gvisor

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
mixed-port: 7897
socks-port: 7898
port: 7899
log-level: debug
allow-lan: false
mode: global
external-controller: 127.0.0.1:9097
secret: password
tun:
  stack: gvisor
  device: Meta
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  strict-route: false
  mtu: 1500
dns:
    enable: true
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['https://doh.dns.sb/dns-query', 'https://dns.cloudflare.com/dns-query', 'https://dns.twnic.tw/dns-query', 'tls://8.8.4.4:853']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
以下省略机场分流规则和节点信息。
```

### Mihomo log

```shell
我无法确定这到底是Mihomo Core的日志信息还是Clash verge rev的日志信息，很抱歉。
2024-04-26 03:38:57 ERROR - failed to connect to the Clash Verge Service
```

### Description

其他常见协议的节点在Tun模式下均可正常连接，不受影响。
使用Clash verge rev作为GUI程序。
