### ISSUE TITLE
[Bug] skip-auth-prefixes 会导致 IN-USER 规则失效

### ISSUE THREAD

**Issue by arkxfly** [MetaCubeX/mihomo#1232]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并无法自行解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Linux

### 系统版本

openwrt 22

### Mihomo 版本

Mihomo Meta v1.18.4 linux amd64 with go1.22.2 Mon Apr 29 06:24:36 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
authentication:
- aaa:w123


skip-auth-prefixes:
- 127.0.0.1/8
- ::1/128
- 192.168.0.0/16

listeners:
- name: mixed
  type: mixed
  port: 1080
  listen: 192.168.1.2

rules:
- IN-USER,aaa,PROXY1
```

### 描述

配置跳过认证前缀，貌似直接跳过读取用户名了，导致无法按指定的规则走代理。建议skipauth是允许不认证，如果带账号密码还是正常认证。

在这之前是用新加 listener 加指定代理实现的。这个版本支持了 in-user，就能用户名来了，不用开那么多端口。

### 重现方式

配置 socks5 代理同时设置上，用户名密码。
