### ISSUE TITLE
[Feature] Create redirect proxy type to overwrite the current server proxy

### ISSUE THREAD

**Issue by lexavey** [MetaCubeX/mihomo#1243]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

I live in some planet which depends on cloudflare IP, they only give me access to specific IP, the IP is not persistent, always change some time.

As example today is ip 1.2.3.4 next 30 day is 2.3.4.5 or 5.6.7.8

In order to use vmess or trojan I must change IP by edit proxy provider file.

Not only me but 10k+ people in my planet maybe have same problem.

I'm already use proxy type http, unfortunatelly only available CONNECT method by default.

What I want to request is create a new proxy type `redirect`, the main function is replace server and port, or maybe sni.

```
proxies:
  # redirect
  - name: "SERVER1"
    type: redirect
    server: 1.2.3.4
    port: 443
    # tls: true # https
    # skip-cert-verify: true
    # sni: custom.com
  - name: "SS1"
    type: ss
    server: unusedserverbecause_will_overwrite by dialer
    port: unused_port_because_will_overwrite by dialer
    dialer-proxy: SERVER1
```

something like that.
how I can achieve ?

i want build my self but im really zero golang.
maybe someone give me clue how to do it ( create myself proxies type then build it ) i will do it with copilot.
