### ISSUE TITLE
[Bug] 在 dialer-proxy 中 vless 无法通过 vless 进行连接

### ISSUE THREAD

**Issue by 63936** [MetaCubeX/mihomo#1244]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

Windows 11

### Mihomo Version

v1.18.4

### Configuration File

```yaml
proxies:
  - name: "vless-ws-A-1"
    type: vless
    server: vless.ws.a
    port: 80
    udp: true
    uuid: 3b9caebf-e683-4242-9728-82704bc0cbb9
    network: ws
    ws-opts:
      path: /path/
    dialer-proxy: vless-ws-tls-B

  - name: "vless-ws-A-2"
    type: vless
    server: vless.ws.a
    port: 80
    udp: true
    uuid: 3b9caebf-e683-4242-9728-82704bc0cbb9
    network: ws
    ws-opts:
      path: /path/
    dialer-proxy: vless-ws-tls-C

  - name: "vless-ws-tls-B"
    type: vless
    server:  vless.ws-tls.b
    port: 443
    udp: true
    uuid: 6a911c3c-2316-495e-8d32-cc7a9bed6155
    tls: true
    skip-cert-verify: true
    servername:  vless.ws-tls.b
    network: ws
    ws-opts:
      path: /path/

  - name: "vmess-ws-tls-C"
    type: vmess
    server:  vmess.ws-tls.c
    port: 443
    udp: true
    uuid: 7f0777e6-38d5-4fff-844e-200e3a8099a2
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername:  vmess.ws-tls.c
    network: ws
    ws-opts:
      path: /path/
```

### Description

配置文件的节点如上所示，其中 vless-ws-A-1 是不通的，vless-ws-A-2 是通的，vless-ws-tls-B 和 vmess-ws-tls-C 都是通的，看下来就是 vless 无法通过 vless。

### Reproduction Steps

NA

**Comment by 63936** [comment]
@xishang0128 谢谢，试了下确实是 vless-ws-tls-C 服务端开了 sni 嗅探的原因，但是如果是 vmess 或者其他节点通过同样的 `dialer-proxy: vless-ws-tls-C` 就没有问题，奇怪。

**Comment by xishang0128** [comment]
@63936 建议是,如果某个节点必须要使用dialer proxy,应该把协议换成ss这类没有tls的,反正都是通过境外节点出站连接

**Comment by 63936** [comment]
@xishang0128 本来是使用 Xray-core v1.8.11 搭建的 ss 服务端配置如下：

```
{
  "inbounds": [
    {
      "port": 8080,
      "protocol": "shadowsocks",
      "settings": {
        "method": "2022-blake3-aes-256-gcm",
        "password": "iRGdDe1ARWkIYf1vuJsJJP3Pl6l2TweLSiR6/wJyTrg=",
        "network": "tcp,udp"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ]
}
```

在 windows 11 使用 v1.18.4 本地的配置如下：

```
proxies:
  - name: "ss"
    type: ss
    server: ss-server
    port: 8080
    cipher: 2022-blake3-aes-256-gcm
    password: "iRGdDe1ARWkIYf1vuJsJJP3Pl6l2TweLSiR6/wJyTrg="
    udp: true
    udp-over-tcp: true
    udp-over-tcp-version: 2
    dialer-proxy: vless-ws-tls-B
```

调试下来 udp 一直不通（判断的依据是访问 <https://browserleaks.com/webrtc>，连接里面没有 udp 的连接），最后才改用的 vless，从上面的配置文件，你能看出来大概是什么原因吗？
