### ISSUE TITLE
[Bug] OpenClash和MerlinClash无法使用配置文件

### ISSUE THREAD

**Issue by cheneyxx** [MetaCubeX/mihomo#1245]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### System Version

v0.46.003

### Mihomo Version

v1.18.4

### Configuration File

```yaml
mixed-port: 7890
allow-lan: false
mode: Rule
log-level: info
ipv6: false
keep-alive-interval: 30
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: ":23453"
  default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - swscan.apple.com
    - mesu.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - xbox.*.microsoft.com
    - xbox.*.*.microsoft.com
    - +.xboxlive.com
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - lens.l.google.com
    - +.music.163.com
    - +.126.net
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - +.y.qq.com
    - +.music.tc.qq.com
    - aqqmusic.tc.qq.com
    - +.stream.qqmusic.qq.com
    - +.xiami.com
    - +.music.migu.cn
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - +.srv.nintendo.net
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.ff14.sdo.com"
    - ff.dorado.sdo.com
    - +.linkedin.com
    - +.licdn.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - proxy.golang.org
    - +.qq.com
    - +.baidu.com
    - +.163.com
    - +.126.net
    - +.taobao.com
    - +.jd.com
    - +.tmall.com
    - "*.mcdn.bilivideo.cn"
    - +.nvidia.com
    - +.nvidia.cn
    - +.nvgs.nvidia.com
    - +.nvgs.nvidia.cn
    - shark007.net
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
rule-providers:
  applications:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
rules:
  - RULE-SET,applications,🎯 全球直连
  - DOMAIN,clash.razord.top,🎯 全球直连
  - DOMAIN,yacd.haishan.me,🎯 全球直连
  - DOMAIN-SUFFIX,steamserver.net,🎯 全球直连
  - DOMAIN-SUFFIX,hellodior.com,🎯 全球直连
  - IP-CIDR,101.32.42.87/32,🎯 全球直连
  - GEOSITE,google,🚀 节点选择
  - DOMAIN-SUFFIX,aliexpress.com,🚀 节点选择
  - DOMAIN-SUFFIX,delta.com,🚀 节点选择
  - DOMAIN-SUFFIX,adobe.io,REJECT
  - GEOSITE,linkedin,🚀 节点选择
  - GEOSITE,okx,🚀 节点选择
  - GEOSITE,microsoft,Ⓜ️ 微软服务
  - RULE-SET,direct,🎯 全球直连
  - RULE-SET,lancidr,🎯 全球直连
  - RULE-SET,cncidr,🎯 全球直连
  - RULE-SET,private,🎯 全球直连
  - GEOSITE,apple,🍎 苹果服务
  - GEOSITE,netflix,📺 Netflix
  - GEOSITE,tiktok,🎬 TikTok
  - GEOSITE,openai,🤖️ ChatGPT
  - GEOIP,telegram,🚀 节点选择
  - RULE-SET,proxy,🚀 节点选择
  - RULE-SET,tld-not-cn,🚀 节点选择
  - GEOIP,LAN,🎯 全球直连
  - GEOIP,CN,🎯 全球直连
  - MATCH,🐟 漏网之鱼
```
```


### Description

节点信息没有写进去 出现的问题是clashx.meta clash meta android clash verge rev使用正常 就是两个路由器的插件不行 不知道是配置文件的问题还是啥

### Reproduction Steps

如果不用rule-providers 把规则都展开就正常

### Logs

_No response_
