### ISSUE TITLE
how to forward all DNS to DOH

### ISSUE THREAD

**Issue by samlux04** [MetaCubeX/mihomo#125]
Why not all DNS forwarded to DOH?
While fake-ip not using DOH at all, redir-host only forwarded handful of DNS requests.
TUN or TPROXY are the same.

Tried on an android 12L device with magisk, CMFA, Windows 10 and openclash. All are the same. Tried also with the original clash premium, it's the same. Is it really how it works?

So, how to forward all DNS to DOH/DOT/DOQ with clash?

```yaml
tproxy-port: 9898
mode: 'rule' 
allow-lan: true
unified-delay: true
bind-address: "*"
log-level: silent
ipv6: false
geodata-mode: false
external-controller: 0.0.0.0:9090
external-ui: clash-dashboard/dist
tcp-concurrent: false
secret: ""
sniffer:
  enable: false
  sniffing:
    - tls
    - http
  port-whitelist: []
  skip-domain: []
  force-domain: []
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - "9.9.9.9"
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter: []
  proxy-server-nameserver: 
   - "1.1.1.1"
  nameserver:
    - "https://dns.nextdns.io/fd44f5"
  fallback:
    - "quic://fd44f5.dns.nextdns.io"
    - "tls://d44f5.dns.nextdns.io"
  fallback-filter:
    geoip: false 
    geoip-code: 'ID'
    geosite: []
    domain: []
    ipcidr: []
tun:
  enable: false
  device: Meta
  stack: system
  dns-hijack: ['any:53', 'tcp://any:53']
  auto-route: false
  auto-detect-interface: false
iptables: {enable: false, inbound-interface: "lo", bypass: []}
interface-name: ""
enable-process: true
profile: {store-selected: true, store-fake-ip: true}
proxies:
```

From https://browserleaks.com/dns

fake-ip:
![Screenshot_20220718-062050_Firefox Nightly](https://user-images.githubusercontent.com/85811479/179427874-985f941d-c2eb-4439-8bd3-7894537d8c37.png)

redir-host:
![Screenshot_20220718-070202_Via](https://user-images.githubusercontent.com/85811479/179428479-d4186910-dd2c-48e4-b9c2-bb4d99a18f2e.png)
