### ISSUE TITLE
求更新使用文档里面的示例

### ISSUE THREAD

**Issue by kirito201711** [MetaCubeX/mihomo#1251]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

我想知道vless+httpupgrade的客户端配置怎么写，使用文档里面的示例里面没有。

**Comment by kirito201711** [comment]
现在支持vless+httpupgrade或者vless+httpupgrade+cdn吗？

**Comment by xream** [comment]
文档里有 1. https://wiki.metacubex.one/config/proxies/transport/#ws-optsv2ray-http-upgrade
2. https://github.com/MetaCubeX/mihomo/blob/Alpha/docs/config.yaml
<img width="693" alt="image" src="https://github.com/MetaCubeX/mihomo/assets/1210282/044f3c42-5aa9-4ec9-9761-77e67eeef7f5">
![image](https://github.com/MetaCubeX/mihomo/assets/1210282/e205ec89-f0d9-4320-af5e-bf541175af09)

**Comment by kirito201711** [comment]
好的，谢谢你！我之前一直在找 network: httpupgrade,结果他在network: ws里面包含了。

**Comment by kirito201711** [comment]
您好，我按照这个配置还是不行，用v2rayn客户端可以，clash verga不行
![1](https://github.com/MetaCubeX/mihomo/assets/111403739/0727214b-6b17-4485-85d3-e01fcc5be77b)
![2](https://github.com/MetaCubeX/mihomo/assets/111403739/7d01f8cf-b209-4b94-a468-7a966ccd6d40)

**Comment by leic4u** [comment]
> 您好，我按照这个配置还是不行，用v2rayn客户端可以，clash verga不行 !

mihomo 似乎不支持 `?ed=2560` 这个参数。

另外参考 ws 的配置，写成这样也无法启用（服务端是 sing-box，理论上是支持 `max-early-data` 的）：
```yaml
ws-opts:
  path: /mypath
  headers:
    Host: abc.com
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
    v2ray-http-upgrade: true
    v2ray-http-upgrade-fast-open: true #服务端上要开启 tcp-fast-open
```

不知道是不是仅支持通过 TFO 来降低握手延迟。

目前可以写成这样来正常连接，并且能够降低一些延迟。

```yaml
ws-opts:
  path: /mypath
  headers:
    Host: abc.com
    v2ray-http-upgrade: true
    v2ray-http-upgrade-fast-open: true #服务端上要开启 tcp-fast-open
```
