### ISSUE TITLE
[Bug] 内核panic

### ISSUE THREAD

**Issue by ayanami-desu** [MetaCubeX/mihomo#1256]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

x86_64

### Mihomo Version

alpha-6d1c62b

### Configuration File

```yaml
---
proxies:
- name: cf-worker
  type: vless
  server: "2606:4700:3035::ac43:8c32"
  port: 443
  uuid: uuid
  network: ws
  tls: true
  servername: a
  ws-opts:
    path: "/?ed=2048"
    headers:
      Host: a
proxy-providers:
  provider:
    type: http
    url: "https://a/konoseikai/proxy-provider.yml"
    path: "./proxy_provider/proxy-provider.yaml"
proxy-groups:
- name: PROXY
  type: select
  use:
  - provider
- name: SPECIAL
  type: select
  use:
  - provider
  filter: "-sg-"
rule-providers:
  direct-list:
    type: http
    behavior: domain
    url: https://a/konoseikai/direct-list.txt
    path: "./rule_provider/direct-list.yaml"
    interval: 86400
  proxy-list:
    type: http
    behavior: domain
    url: https://a/konoseikai/proxy-list.txt
    path: "./rule_provider/proxy-list.yaml"
    interval: 86400
  special-list:
    type: http
    behavior: classical
    url: https://a/konoseikai/special-list.txt
    path: "./rule_provider/special-list.yaml"
    interval: 86400
rules:
- RULE-SET,special-list,SPECIAL
- RULE-SET,proxy-list,PROXY
- RULE-SET,direct-list,DIRECT
- GEOSITE,apple-cn,DIRECT
- GEOSITE,microsoft@cn,DIRECT
- GEOSITE,geolocation-cn,DIRECT
- GEOSITE,cn,DIRECT
- GEOSITE,geolocation-!cn,PROXY
- GEOIP,cn,DIRECT
- MATCH,PROXY
listeners:
- name: mixed-in
  type: mixed
  port: 10800
  proxy: cf-worker
- name: mixed-in-direct
  type: mixed
  port: 10810
  proxy: DIRECT
```

### Description

通过openclash启动clash meta，但panic

### Reproduction Steps

应该与linux内核有关。其他固件无问题

### Logs

```shell
github.com/metacubex/mihomo/main.go:114 +0x615
main.main()
	github.com/metacubex/mihomo/hub/hub.go:50 +0x245
github.com/metacubex/mihomo/hub.Parse({0x0, 0x0, 0x7fff3865bfb5?})
	github.com/metacubex/mihomo/hub/executor/executor.go:111 +0x345
github.com/metacubex/mihomo/hub/executor.ApplyConfig(0xc0002a2000, 0x1)
	github.com/metacubex/mihomo/hub/executor/executor.go:425 +0x2c
github.com/metacubex/mihomo/hub/executor.updateProfile(0xc0001fc9c0?)
	github.com/metacubex/mihomo/hub/executor/executor.go:430 +0x45
github.com/metacubex/mihomo/hub/executor.patchSelectGroup(0xc0001fc990)
	github.com/metacubex/mihomo/component/profile/cachefile/cache.go:173
github.com/metacubex/mihomo/component/profile/cachefile.Cache(...)
sync.(*Once).Do(...)
	sync/once.go:74 +0xc2
sync.(*Once).doSlow(0xc001a00ff0?, 0xc0001fc9c0?)
	github.com/metacubex/mihomo/component/profile/cachefile/cache.go:152 +0xc5
github.com/metacubex/mihomo/component/profile/cachefile.initCache()
	github.com/sagernet/bbolt@v0.0.0-20231014093535-ea5cb2fe9f0a/db.go:268 +0x3dc
github.com/sagernet/bbolt.Open({0xc002ff5c80, 0x17}, 0x1b6, 0xc000c879f0)
	github.com/sagernet/bbolt@v0.0.0-20231014093535-ea5cb2fe9f0a/db.go:384 +0x45
github.com/sagernet/bbolt.(*DB).loadFreelist(0xc0059f2160?)
sync.(*Once).Do(...)
	sync/once.go:74 +0xc2
sync.(*Once).doSlow(0xc000c878a8?, 0xc0059f2160?)
	github.com/sagernet/bbolt@v0.0.0-20231014093535-ea5cb2fe9f0a/db.go:391 +0xaf
github.com/sagernet/bbolt.(*DB).loadFreelist.func1()
	github.com/sagernet/bbolt@v0.0.0-20231014093535-ea5cb2fe9f0a/freelist.go:269 +0x174
github.com/sagernet/bbolt.(*freelist).read(0x0?, 0x0?)
goroutine 1 [running]:
panic: invalid freelist page: 140633170919616, page type is unknown<40c0>
```
