### ISSUE TITLE
[Bug] openwrt tun mixed stack unable to route local traffic.

### ISSUE THREAD

**Issue by lux5am** [MetaCubeX/mihomo#1258]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

Openwrt 23.05.3

### Mihomo Version

Mihomo Meta alpha-619f341 linux arm64 with go1.22.2 Sat May 11 16:12:32 UTC 2024
Use tags: with_gvisor

### Configuration File

```yaml
allow-lan: true
bind-address: "*"
mode: rule
log-level: warning
find-process-mode: 'off'
unified-delay: true
keep-alive-interval: 1800

external-controller: 0.0.0.0:9090
external-ui: ./ui

dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  nameserver:
    # - 8.8.8.8
    - "https://94.140.14.14/dns-query"
  default-nameserver: 
    # - system
    - 8.8.8.8
  proxy-server-nameserver: 
    # - system
    # - 8.8.4.4
    - 1.1.1.1
proxies: []

proxy-groups:
  - name: 🌝Proxy
    type: select
    use:
      - myproxies

proxy-providers:
  myproxies:
    type: file
    path: ./proxy_provider/myproxies.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1800

rules:
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - MATCH,🌝Proxy

sniffer:   
  enable: true
  force-dns-mapping: false
  parse-pure-ip: true
  override-destination: false
  sniff: # TLS 和 QUIC 默认如果不配置 ports 默认嗅探 443
    QUIC:
      ports: [443]
    TLS:
      ports: [443, 8443, 5222-5228]
    # 默认嗅探 80
    HTTP: # 需要嗅探的端口
      ports: [80, 8080-8880]
  sniffing:
    - tls
    - http
  port-whitelist:
    - 80
    - 443

tun:
  enable: teue
  mtu: 9000
  device: utun
  stack: mixed
  dns-hijack:
    - 0.0.0.0:53
  auto-route: true
  strict-route: false
  auto-detect-interface: true
```

### Description

When using tun mixed stack local traffic didn't appear in connection log. It seems there's no local traffic routed to mihomo tun. Checked with `curl https://ip.sb/ip` it's indeed not enter mihomo.
Changed to system or gvisor there's no problem. It able to routed local traffic normally.

I also tried sing-box. it has the same issue. I suspected  it's something to do with sing library. I opened the issue few weeks ago in sing project it's immediately closed without reply as expected.

### Reproduction Steps

Enable tun with mixed stack.
Try to use internet within the router with ssh. Eg `curl https://ip.sb/ip`
Observe
