### ISSUE TITLE
[Bug] 重启后 geo-update-interval 更新时间间隔会重新计算

### ISSUE THREAD

**Issue by xiaoQQya** [MetaCubeX/mihomo#1261]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Windows

### 系统版本

Windows 11 专业版 22631.3527

### Mihomo 版本

Mihomo Meta alpha-6d1c62b windows amd64 with go1.22.2 Wed May  8 01:30:29 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb
```

### 描述

启用 `geo-auto-update`，设置 `geo-update-interval` 为 24h，在 mihomo 内核不关闭的情况下，每 24h 会自动更新 geodata；如果在中途 mihomo 重启过，geodata 更新的时间间隔似乎会重新计算。

考虑日常使用场景，设置 geo-update-interval 为 24h，每天早上启动 mihomo，晚上关机关闭 mihomo ，因时间不足 24h 所以不会触发 geodata 自动更新，每天如此会导致 geodata 一直不会更新，只能手动更新。

期望同 provider 一样，在启动时检查上次更新时间，如果超过了设置的更新间隔，则进行更新。

### 重现方式

1. 配置文件中启用 `geo-auto-update` 并设置 `geo-update-interval` 为 1h；
2. 启动 mihomo 后在 1h 内退出；
3. 等待 1h 之后再次启动 mihomo，此时距 geodata 文件的修改时间已经超过了 1h，但并不会自动更新 geodata 数据；

### 日志

```shell
无
```
