### ISSUE TITLE
[Bug] 使用tun模式将正向代理服务流量劫持在本地，进行全局路由。运行一段时间后,偶发出现访问失败

### ISSUE THREAD

**Issue by liuhaibin0528** [MetaCubeX/mihomo#1265]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [X] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Linux

### 系统版本

Ubuntu 22.04

### Mihomo 版本

Mihomo Meta v1.17.0 linux amd64 with go1.20.11 Sun Dec  3 01:03:59 UTC 2023
Use tags: with_gvisor

### 配置文件

```yaml
redir-port: 9999
allow-lan: true
mode: rule
interface-name: ens160
log-level: error
#external-controller: '0.0.0.0:9090'
#external-ui: /opt/clash/ui
#secret: "123456"
udp: true
ipv6: false
ntp:
  enable: true
  write-to-system: false
  server: ntp1.aliyun.com
  port: 123
  interval: 30
dns:
  enable: true
  ipv6: false
  prefer-h3: false
  listen: 0.0.0.0:54
  fake-ip-range: 198.19.0.1/16
  enhanced-mode: redir-host
  nameserver:
    - 100.125.136.29
    - 100.125.1.250
tun:
  enable: true
  stack: system
  auto-route: true
  dns-hijack:
    - 100.125.136.29:53
    - 100.125.1.250:53
    - any:53
    - tcp://any:53
proxies:
  - name: "http"
    type: http
    server: 192.168.0.3
    port: 9999
    udp: true
proxy-groups:
  - name: all
    type: select
    proxies:
      - http
      - DIRECT
rules:
  - IP-CIDR,172.19.0.0/16,DIRECT
  - IP-CIDR,100.125.0.0/16,DIRECT
  - MATCH,all
```

### 描述

操作系统日志、clash日志均无错误日志

### 重现方式

使用tun模式开启全局代理，将正向代理服务器的流量劫持到本地。以进行访问外网。起初一切正常，运行一段时间后，我是运行2个多月左右，机器访问外网偶发就出现失败，curl www.baidu.com 直接卡住，多次执行时而可以时而失败，最终重启clash后就又恢复正常一段时间。
