### ISSUE TITLE
[Bug] 关于vless+grpc+reality节点切换网络会断连的问题

### ISSUE THREAD

**Issue by ForestL18** [MetaCubeX/mihomo#1281]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Android

### System Version

Android 14

### Mihomo Version

Meta-Alpha-c504985

### Configuration File

```yaml
- name: 'test'
    type: vless
    server: example.com
    port: 8443
    uuid: xxxxxxx
    network: grpc
    tls: true
    udp: true
    servername: example.com
    grpc-opts:
      grpc-service-name: test
    reality-opts:
      public-key: xxxxxxxx
      short-id: xxxxx
    client-fingerprint: chrome
    xtls: 2
```

### Description

当我从WiFi切换到移动网络的时候，节点可以测速正常，连接正常；当我再从移动网络切换回WiFi的时候，节点测速失败，连接失败。

同样的服务器xtls+tcp+vision没有出现这个问题。

### Reproduction Steps

如上
