### ISSUE TITLE
[Bug] 关于出现route ip+net: netlinkrib: permission denied的错误问题

### ISSUE THREAD

**Issue by ForestL18** [MetaCubeX/mihomo#1291]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [X] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Android

### 系统版本

Android 14

### Mihomo 版本

Alpha-3195c67

### 配置文件

```yaml
######### 锚点 start #######
# proxy 相关
GeneralProxies:
    &GeneralProxies {
        type: select,
        proxies: [Default, HK, TW, JP, SG, US, Manual, Direct],
        url: "http://1.1.1.1/generate_204",
    }

proxyurl: &proxyurl { url: "http://1.1.1.1/generate_204" }

# provider 相关
GeneralProviders: &GeneralProviders {
        type: http,
        health-check: { enable: false, url: "http://1.1.1.1/generate_204" },
        proxy: Direct,
    }

mode: rule
ipv6: false
log-level: silent
allow-lan: false
mixed-port: 7890
keep-alive-interval: 30
unified-delay: false
tcp-concurrent: true
external-controller: "127.0.0.1:9090"
#external-ui: ui
#external-ui-name: xd
#external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

geodata-mode: false
geo-auto-update: true
geo-update-interval: 24
geox-url:
    geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
    geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
    mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
    store-selected: true
    store-fake-ip: true
tun:
    enable: true
    stack: system
    dns-hijack:
        - any:53
        #- tcp://any:53
    auto-route: true
    auto-detect-interface: true
    strict-route: true

dns:
    enable: true
    listen: 0.0.0.0:1053
    #use-hosts: true
    ipv6: false
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/15
    #prefer-h3: true
    default-nameserver:
        - 223.5.5.5
        #- 119.29.29.29
    nameserver:
        - "https://doh.pub/dns-query"
        - "https://dns.alidns.com/dns-query"
    proxy-server-nameserver:
        - "https://doh.pub/dns-query"
    nameserver-policy:
        "geosite:googlefcm,apple,microsoft,epicgames,private,cn":
            - 223.5.5.5
            - 119.29.29.29
        "geosite:geolocation-!cn":
            - "tls://8.8.8.8#Others"

    fake-ip-filter:

        ### Games
        # Stun Services
        - "stun.*.*"
        - "stun.*.*.*"
        - "+.stun.*.*"
        - "+.stun.*.*.*"
        - "+.stun.*.*.*.*"
        - "+.stun.*.*.*.*.*"
        # Nintendo Switch
        - "+.srv.nintendo.net"
        - "*.n.n.srv.nintendo.net"
        # Sony PlayStation
        - "*.*.stun.playstation.net"
        # XBox
        - "xbox.*.*.microsoft.com"
        - "*.*.xboxlive.com"
        #- "xbox.*.microsoft.com"
        #- xnotify.xboxlive.com
        # Wotgame
        - "+.battlenet.com.cn"
        - "+.wotgame.cn"
        - "+.wggames.cn"
        - "+.wowsgame.cn"
        - "+.wargaming.net"
        # FinalFantasy XIV Worldwide Server & CN Server
        - "*.square-enix.com"
        - "*.finalfantasyxiv.com"
        - "*.ffxiv.com"
        - "*.ff14.sdo.com"
        - ff.dorado.sdo.com
        #UU Plugin
        - "+.uu.163.com"
        - ps.res.netease.com

proxies:
    - name: "Direct"
      type: direct
      udp: true

proxy-groups:
    # Primary Switch
    - {
          name: Default,
          type: select,
          proxies: [HK, TW, JP, SG, US, Manual, Direct],
          <<: *proxyurl,
      }

    # Secondary Switch
    - { name: Others, <<: *GeneralProxies }

    # 分隔,下面是地区分组
    - {
          name: HK,
          type: select,
          include-all-providers: true,
          filter: "(?i)香港|HK|hongkong|hong kong",
          exclude-filter: "(?i)premium",
      }

    - {
          name: TW,
          type: select,
          include-all-providers: true,
          filter: "(?i)台湾|TW|taiwan",
          exclude-filter: "(?i)premium",
      }

    - {
          name: JP,
          type: select,
          include-all-providers: true,
          filter: "(?i)日本|JP|japan",
          exclude-filter: "(?i)premium",
      }

    - {
          name: SG,
          type: select,
          include-all-providers: true,
          filter: "(?i)新加坡|SG|singapore",
          exclude-filter: "(?i)premium",
      }

    - {
          name: US,
          type: select,
          include-all-providers: true,
          filter: "(?i)美国|USA|unitedstates|united states|洛杉矶",
          exclude-filter: "(?i)premium",
      }

    - { name: Manual, type: select, include-all-providers: true }

    # 分隔,下面是应用分组
    - { name: Telegram, <<: *GeneralProxies }

    - {
          name: AIGC,
          type: select,
          proxies: [US, SG, TW, JP, Manual],
          <<: *proxyurl,
      }

    - { name: Google, <<: *GeneralProxies }

    - { name: Apple, <<: *GeneralProxies }

    - { name: Microsoft, <<: *GeneralProxies }

    - { name: Amazon, <<: *GeneralProxies }

    - { name: Github, <<: *GeneralProxies }

    - { name: Steam, <<: *GeneralProxies }

    - {
          name: Epic,
          type: select,
          proxies: [Direct, Default, HK, TW, JP, SG, US, Manual],
          <<: *proxyurl,
      }

    - {
          name: Netflix,
          type: select,
          proxies: [SG, TW, JP, HK, US, Manual, Direct],
          <<: *proxyurl,
      }
    - { name: Ehentai, <<: *GeneralProxies }

    - { name: Pixiv, <<: *GeneralProxies }

    - { name: Twitter, <<: *GeneralProxies }

    - { name: Facebook, <<: *GeneralProxies }

    - { name: Spotify, <<: *GeneralProxies }

    - { name: Twitch, <<: *GeneralProxies }

    - { name: Reddit, <<: *GeneralProxies }

    - { name: Discord, <<: *GeneralProxies }

    - {
          name: Bilibili,
          type: select,
          proxies: [Direct, Default, HK, TW, JP, SG, US, Manual],
          <<: *proxyurl,
      }

    - {
          name: SitesOnlyJP,
          type: select,
          proxies: [JP, TW, HK, SG, US, Manual, Direct],
          <<: *proxyurl,
      }

    - {
          name: Speedtest,
          type: select,
          proxies: [Direct, Default, HK, TW, JP, SG, US, Manual],
          <<: *proxyurl,
      }

    - {
          name: GoogleFCM,
          type: select,
          proxies: [Direct, Default, HK, TW, JP, SG, US, Manual],
          <<: *proxyurl,
      }

rules:

    - GEOIP,private,Direct,no-resolve
    - RULE-SET,reject,REJECT
    - RULE-SET,private,Direct
    - RULE-SET,aigc,AIGC
    - RULE-SET,direct,Direct
    - RULE-SET,proxy,Default
    - RULE-SET,netwroktest,Speedtest

    - GEOSITE,category-games@cn,Direct

    - GEOSITE,ehentai,Ehentai

    - GEOSITE,pixiv,Pixiv

    - GEOSITE,telegram,Telegram

    - GEOSITE,github,Github

    - GEOSITE,googlefcm,GoogleFCM
    - GEOSITE,google,Google

    - GEOSITE,apple@cn,Direct
    - GEOSITE,apple,Apple

    - GEOSITE,microsoft@cn,Direct
    - GEOSITE,microsoft,Microsoft

    - GEOSITE,amazon@cn,Direct
    - GEOSITE,amazon,Amazon

    - GEOSITE,steam@cn,Direct
    - GEOSITE,steam,Steam

    - GEOSITE,epicgames,Epic

    - GEOSITE,bilibili,Bilibili

    - GEOSITE,netflix,Netflix

    - GEOSITE,twitter,Twitter

    - GEOSITE,facebook,Facebook
    - GEOSITE,instagram,Facebook
    - GEOSITE,threads,Facebook

    - GEOSITE,spotify,Spotify

    - GEOSITE,reddit,Reddit

    - GEOSITE,twitch,Twitch

    - GEOSITE,discord,Discord

    - GEOSITE,dmm,SitesOnlyJP

    - GEOSITE,cn,Direct
    - GEOSITE,geolocation-!cn,Others

    - GEOIP,telegram,Telegram
    - GEOIP,google,Google
    - GEOIP,netflix,Netflix
    - GEOIP,twitter,Twitter
    - GEOIP,facebook,Facebook
    - GEOIP,CN,Direct
    - MATCH,Others
```

### 描述

使用最新的cmfa的pre-release版本，发现直连策略（direct）的udp无法连接，使用debug查看日志如下：`Warning: [UDP] dial Bilibili (match GeoSite/bilibili) 192.168.89.16:57899 --> stun.chat.bilibili.com:3478 error: route ip+net: netlinkrib: permission denied`。

于是我回退到release版本，发现该问题消失，日志如下：`Info: [UDP] 192.168.89.16:53176 --> stun.chat.bilibili.com:3478 match GeoSite(bilibili) using Bilibili[Direct]`

我查看了下mihomo的commit记录，发现可能与这个commit的修改有关：[fix: avoid netlink dos networkUpdateMonitor](https://github.com/MetaCubeX/mihomo/commit/ba09139bd70dc6a424c61df39a5caf38dad386eb)。

@wwqgtxx 希望大佬有时间的话帮忙看下，非常感谢！

### 重现方式

如上

### 日志

```shell
日志为附件方式
```
