### ISSUE TITLE
[Bug] 关于`health-check`的问题

### ISSUE THREAD

**Issue by F1Y2M0N** [MetaCubeX/mihomo#1298]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

MacOS, Windows, Linux, Android

### 系统版本

openwrt23 windows11 ubuntu24 android14 macos14

### Mihomo 版本

版本太多了，已经用了两年了，有问题一直存在
可以保证使用的版本是新于等于Release中的v1.xx.x版本
每个正式Release保证更新，有时会更新Prerelease-Alpha
比如现在用的是 846bdfa

### 配置文件

```yaml
0: &0 {interval: 256, lazy: true, tolerance: 128}
1: &1 {health-check: {<<: *0, enable: false}, interval: 65536, type: http}
proxy-providers:
 z: {<<: *1, url: }
proxy-groups:
- {<<: *0, name: 手, type: select, include-all: true}
- {<<: *0, name: 代, type: select, proxies: [F1]}
- {<<: *0, name: F1, type: fallback, proxies: [手, F2]}
- {<<: *0, name: F2, type: fallback, proxies: [手, F3], url: 'https://www.msftconnecttest.com/connecttest.txt'}
- {<<: *0, name: F3, type: fallback, proxies: [手, U1, U2, U3, DIRECT], url: 'https://www.apple.com/library/test/success.html'}
- {<<: *0, name: U1, type: url-test, include-all: true, filter: 地区1}
- {<<: *0, name: U2, type: url-test, include-all: true, filter: 地区2}
- {<<: *0, name: U3, type: url-test, include-all: true, filter: 地区3}
rules:
- MATCH,代
```

### 描述

确定是内核问题，非拉起内核的客户端的问题
所有问题只使用`proxy-providers`未在运行配置内手动填写[proxies](https://wiki.metacubex.one/config/proxies/)，运行配置内含`proxies:`或影响复现

---
问题一
当 mihomo 的`lazy: true`生效后，再稳定运行超过三天，`url-test`就会失效
此时即使**所有组中已被选中的节点失效**`alive: false, delay: 65535 ms`，`fallback`划到`DIRECT`1小时也不会激活`url-test`的`health-check`去选择一个未失效的节点
该问题是先在openwrt中发现的，然后经windows、ubuntu和mac复核

---
问题二（有可能需要结合问题一）
多个自动组套用时，节点的[max-failed-times](https://wiki.metacubex.one/config/proxy-groups/#max-failed-times)切换会异常
我在`interval: 99999`的情况下尝试`max-failed-times: 1`，结果`max-failed-times`失效，仍需要等`interval: 99999`去切换节点更不要说默认的`max-failed-times: 5`了

---
问题三（这个问题是这两年一直存在的）
当`proxy-providers`的`health-check: {enable: false}`时
`url-test`的节点只会选择第一个，无论该节点是否可用延迟如何
只能靠`health-check: {enable: true}`来解决，所以会带来
1`filter`只筛选了四个地区不到二十个节点，但完整的`proxy-provider`有三个订阅超过二百个节点，所以有些浪费资源
2我直接引用其他人发的吧
> 由于不同网站的对节点的不同需要，我设置了 7 个 url-test 的代理组，间隔在一到两分钟，然后我发现它们会消耗大约每小时 60-80m 的流量，一个月下来约 50-60GB，是一个巨量的损耗
> https://github.com/vernesong/OpenClash/issues/3878 

我也有类似情况，测试问题一时发现的，确定是`health-check`导致的，但没如此严重

### 重现方式

描述
