### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ipaguge** [MetaCubeX/mihomo#1340]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Android

### System Version

鸿蒙 4.0+

### Mihomo Version

全部版本

### Configuration File

```yaml
proxies:
- name: h+h ID:5037
  server: 38.114.101.134
  port: 35379
  type: hysteria2
  sni: www.bing.com
  password: email-uid-0-nodeId-5037-code-[]@xray.com:d36b5bb1-fae7-4ddc-b023-1935f64e350b
  udp: true
  skip-cert-verify: true
```

### Description

我将clashMeta 打包成了aar 提供给安卓使用
当使用hysteria2协议时遇到了问题

测试了大量的安卓手机没有任何问题 但是使用鸿蒙系统4.0呀以上时 出现了没网的情况

通过日志看到是有正确的路由到hysteria2协议所在的节点  并且在hysteria2的后端也看到了正确的日志

但是客户端就是没网 并且没有任何错误日志 

一开始我怀疑可能是鸿蒙系统的问题 后面我测试了singbox 它是正常的 hysteria2协议能正常上网

我有看到clashmeta的hysteria2协议与singbox都是依赖源之于
https://github.com/SagerNet/sing-quic项目
由于个人技术能力有限没有排查到可疑的地方 

该问题是100%复现的

### Reproduction Steps

鸿蒙系统4.0以上系统  使用hysteria2协议没网 服务端日志正常 客户端日志也正常  就是没网
