### ISSUE TITLE
[Bug] 废弃的链接不会杀死，一直保留在进程中

### ISSUE THREAD

**Issue by lkxlzx** [MetaCubeX/mihomo#1341]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

debian11

### Mihomo Version

alpha-a9ecc62

### Configuration File

```yaml
mode: rule
ipv6: true
log-level: info
allow-lan: true
port: 7890 # HTTP(S) 代理服务器端口
socks-port: 1080 # SOCKS5 代理端口
mixed-port: 10801 # HTTP(S) 和 SOCKS 代理混合端口
redir-port: 7892 # 透明代理端口，用于 Linux 和 MacOS
# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
tproxy-port: 7893
unified-delay: true
#unified-delay: false
tcp-concurrent: true
external-controller: 0.0.0.0:8090
secret: 11111111
external-ui: /etc/mihomo/ui
external-ui-name: xd
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
keep-alive-interval: 30
geodata-mode: true
geodata-loader: standard
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
geo-auto-update: true # 是否自动更新 geodata
geo-update-interval: 1 # 更新间隔，单位：小时

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: false
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
proxies:
#  - name: "WARP-plus"
#    type: wireguard
#    server: 2606:4700:d0::4cc3:70aa:0f1b:a767
#    port: 2506
#    ip: "172.16.0.2/32"
#    ipv6: "2606:4700:110:8e14:c98:88a8:9109:fa15/128"
#    private-key: "mKPd8cCXEAlvXIukZ+7CII234KOreqDdG9QjXcn1l2Q="
#    public-key: "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
#    udp: true
#//   reserved: []
#    mtu: 1280
#    allowed_ips: ['0.0.0.0/0,::/0']

proxy-groups:
#- name: "节点预览"
#  type: url-test
#  proxies:
#  - akile-美国
#  - akile-台湾
#  - akile-香港
#  - akile-澳门
#  - aws-首尔
#  - aws-新加坡
#  - desivps-圣何塞
#  - cloudcone-洛杉矶
#  - racknerd-洛杉矶
#  - 腾讯云-香港
#  - 阿里云-香港
#  - Juhost-日本
#  - wikihost-日本
#  url: 'http://www.apple.com/library/test/success.html'
#  expected-status: 200/302/204
#  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
#  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
#  tolerance: 50  #节点切换容差,单位ms
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
#  disable-udp: false  #禁用该策略组的UDP
#- name: "故障转移"
#  type: fallback
#  proxies:
#  - akile-美国
#  - akile-台湾
#  - akile-香港
#  - akile-澳门
#  - aws-首尔
#  - aws-新加坡
#  - cloudcone-洛杉矶
#  - racknerd-洛杉矶
#  - Juhost-日本
#  - wikihost-日本
#  url: 'http://www.google.com/generate_204'
#  expected-status: 200/302/204
#  interval: 120  #健康检查间隔，如不为 0 则启用定时测试
#  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
#  tolerance: 50  #节点切换容差,单位ms
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
#  disable-udp: false  #禁用该策略组的UDP
#- name: "香港负载均衡"
#  type: load-balance
#  proxies:
#  - akile-香港
#  - akile-台湾
#  url: 'http://www.apple.com/library/test/success.html'
#  expected-status: 200/302/204
#  interval: 15
#  max-failed-times: 3
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
#  strategy: round-robin #consistent-hashing or round-robin
#- name: "美国负载均衡"
#  type: load-balance
#  proxies:
#  - cloudcone-洛杉矶
#  - racknerd-洛杉矶
#  url: 'http://www.apple.com/library/test/success.html'
#  expected-status: 200/302/204
#  interval: 15
#  max-failed-times: 3
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
#  strategy: round-robin #consistent-hashing or round-robin
- name: 欧美
  type: select
  proxies:
  - akile-美国
  - cloudcone-洛杉矶
  - racknerd-洛杉矶
#  url: 'http://www.apple.com/library/test/success.html'
#  expected-status: 200/302/204
#  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
#  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
#  max-failed-times: 3
#  tolerance: 50  #节点切换容差,单位ms
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
- name: 亚太
  type: select
  proxies:
  - akile-台湾NAT
  - akile-香港
  - aws-新加坡
#  url: 'http://www.apple.com/library/test/success.html'
#  expected-status: 200/302/204
#  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
#  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
#  max-failed-times: 3
#  tolerance: 50  #节点切换容差,单位ms
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
- name: 日韩
  type: select
  proxies:
  - aws-首尔
#  url: 'http://www.apple.com/library/test/success.html'
#  expected-status: 200/302/204
#  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
#  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
#  max-failed-times: 3
#  tolerance: 50  #节点切换容差,单位ms
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
- name: 港台
  type: select
  proxies:
  - akile-台湾NAT
  - akile-香港
  - 腾讯云-香港
#  url: 'http://www.apple.com/library/test/success.html'
#  expected-status: 200/302/204
#  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
#  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
#  max-failed-times: 3
#  tolerance: 50  #节点切换容差,单位ms
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
- name: 默认出口
  type: url-test
  proxies:
  - akile-台湾NAT
  - akile-美国
  - akile-香港
  - aws-首尔
  - aws-新加坡
  - desivps-圣何塞
  - cloudcone-洛杉矶
  - racknerd-洛杉矶
  - 腾讯云-香港
  url: 'http://www.apple.com/library/test/success.html'
  expected-status: 200/302/204
  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
  max-failed-times: 3
  tolerance: 50  #节点切换容差,单位ms
  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
#- name: "自动选择"
#  type: url-test
#  proxies:
#  - akile-美国
#  - akile-台湾
#  - akile-香港
#  - akile-澳门
#  - aws-首尔
#  - aws-新加坡
#  - cloudcone-洛杉矶
#  - racknerd-洛杉矶
#  - Juhost-日本
#  - wikihost-日本
#  - 美国负载均衡
#  - WARP-plus
#  url: 'http://www.google.com/generate_204'
#  expected-status: 200/302/204
#  interval: 60  #健康检查间隔，如不为 0 则启用定时测试
#  tolerance: 50  #节点切换容差,单位ms
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
#  disable-udp: false #禁用该策略组的UDP
- name: DNS服务
  type: url-test
  proxies:
  - akile-台湾NAT
  - akile-香港
  - aws-新加坡
  url: 'http://www.apple.com/library/test/success.html'
  expected-status: 200/302/204
  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
  max-failed-times: 3
  tolerance: 5  #节点切换容差,单位ms
  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
- name: Cloudflare
  type: url-test
  proxies:
  - akile-台湾NAT
  - akile-香港
  - aws-首尔
  - aws-新加坡
  - cloudcone-洛杉矶
  - racknerd-洛杉矶
  url: 'http://www.apple.com/library/test/success.html'
  expected-status: 200/302/204
  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
  max-failed-times: 3
  tolerance: 50  #节点切换容差,单位ms
  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
- name: YouTube
  type: url-test
  proxies:
  - akile-台湾NAT
  - akile-美国
  - akile-香港
  - aws-新加坡
  - aws-首尔
  - cloudcone-洛杉矶
  - racknerd-洛杉矶
  url: 'http://www.apple.com/library/test/success.html'
  expected-status: 200/302/204
  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
  max-failed-times: 3
  tolerance: 50  #节点切换容差,单位ms
  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
- name: Google&Google TV
  type: url-test
  proxies:
  - akile-美国
  - akile-香港
  - aws-首尔
  - aws-新加坡
  - cloudcone-洛杉矶
  - racknerd-洛杉矶
  url: 'http://www.apple.com/library/test/success.html'
  expected-status: 200/302/204
  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
  max-failed-times: 3
  tolerance: 50  #节点切换容差,单位ms
  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
#- name: Google
#  type: select
#  icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Google_Search.png
#  proxies:
#  - 自动选择
#  - 故障转移
#  - akile-美国
#  - akile-香港
#  - aws-首尔
#  - aws-新加坡
#  - cloudcone-洛杉矶
#  - racknerd-洛杉矶
#  - Juhost-日本
#  - wikihost-日本
#  - 美国负载均衡
#  disable-udp: false  #禁用该策略组的UDP
- name: NETFLIX&Disney+
  type: select
  icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Netflix.png
  proxies:
  - akile-台湾NAT
  - akile-美国
  - akile-香港
  - aws-首尔
  - aws-新加坡
  - cloudcone-洛杉矶
  - racknerd-洛杉矶
  - desivps-圣何塞
#  url: 'http://www.apple.com/library/test/success.html'
#  expected-status: 200/302/204
#  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
#  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
#  max-failed-times: 3
#  tolerance: 50  #节点切换容差,单位ms
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
#- name: Tubi
#  type: select
#  proxies:
#  - 故障转移
#  - desivps-圣何塞
#  - cloudcone-洛杉矶
#  - racknerd-洛杉矶
#  - Cloudflare-vless
#  disable-udp: false
#- name: Viki
#  type: select
#  proxies:
#  - 故障转移
#  - desivps-圣何塞
#  - cloudcone-洛杉矶
#  - racknerd-洛杉矶
#  - Cloudflare-vless
#  disable-udp: false
- name: 美区流媒体
  type: select
  proxies:
  - akile-美国
  - cloudcone-洛杉矶
  - racknerd-洛杉矶
#  url: 'http://www.apple.com/library/test/success.html'
#  expected-status: 200/302/204
#  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
#  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
#  max-failed-times: 3
#  tolerance: 50  #节点切换容差,单位ms
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
#- name: ViuTV
#  type: select
#  proxies:
#  - akile-台湾
#  - akile-香港
#  - aws-新加坡
#  - 腾讯云-香港
#  - 阿里云-香港
#  disable-udp: false
- name: 群晖服务
  type: select
  proxies:
  - akile-台湾NAT
  - akile-香港
  - aws-首尔
  - aws-新加坡
  - cloudcone-洛杉矶
  - racknerd-洛杉矶
  - 腾讯云-香港
#  url: 'http://www.apple.com/library/test/success.html'
#  expected-status: 200/302/204
#  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
#  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
#  max-failed-times: 3
#  tolerance: 50  #节点切换容差,单位ms
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
#- name: TikTok
#  type: select
#  proxies:
#  - akile-美国
#  - akile-台湾
#  - akile-香港
#  - akile-澳门
#  - aws-首尔
#  - aws-新加坡
#  - cloudcone-洛杉矶
#  - racknerd-洛杉矶
#  - Juhost-日本
#  - wikihost-日本
#  disable-udp: false
#- name: Telegram
#  type: select
#  proxies:
#  - 自动选择
#  - 故障转移
#  - aws-首尔
#  - aws-新加坡
#  - desivps-圣何塞
#  - cloudcone-洛杉矶
#  - racknerd-洛杉矶
#  - Juhost-日本
#  - wikihost-日本
#  - Cloudflare-vless
#  disable-udp: false
- name: Twitter&Facebook
  type: select
  proxies:
  - akile-台湾NAT
  - akile-美国
  - akile-香港
  - aws-首尔
  - aws-新加坡
  - cloudcone-洛杉矶
  - racknerd-洛杉矶
#  url: 'http://www.apple.com/library/test/success.html'
#  expected-status: 200/302/204
#  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
#  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
#  max-failed-times: 3
#  tolerance: 50  #节点切换容差,单位ms
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
- name: Github&Docker
  type: select
  proxies:
  - akile-台湾NAT
  - akile-美国
  - akile-香港
  - aws-首尔
  - aws-新加坡
  - cloudcone-洛杉矶
  - racknerd-洛杉矶
#  url: 'http://www.apple.com/library/test/success.html'
#  expected-status: 200/302/204
#  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
#  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
#  max-failed-times: 3
#  tolerance: 50  #节点切换容差,单位ms
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
#- name: Docker
#  type: select
#  proxies:
#  - 自动选择
#  - 故障转移
#  - aws-首尔
#  - aws-新加坡
#  - desivps-圣何塞
#  - cloudcone-洛杉矶
#  - racknerd-洛杉矶
#  - Juhost-日本
#  - wikihost-日本
#  - Cloudflare-vless
#  disable-udp: false
- name: PT站点
  type: select
  proxies:
#  - 直连
  - akile-台湾NAT
  - akile-美国
  - akile-香港
  - aws-首尔
  - aws-新加坡
  - cloudcone-洛杉矶
  - racknerd-洛杉矶
#  url: 'http://www.apple.com/library/test/success.html'
#  expected-status: 200/302/204
#  interval: 15  #健康检查间隔，如不为 0 则启用定时测试
#  timeout: 3000  #健康检查超时时间，单位为毫秒 (ms)
#  max-failed-times: 3
#  tolerance: 50  #节点切换容差,单位ms
#  lazy: false  #懒惰状态，默认为true,未选择到当前策略组时，不进行测试
  disable-udp: false  #禁用该策略组的UDP
rules:
  # - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,cn))),REJECT # quic
  - DST-PORT,53/853,DNS服务
  - RULE-SET,DNS_classical,DNS服务
#  - DST-PORT,16881,PT站点
#  - IP-CIDR6,2607:f8b0::/32,YouTube
#  - IP-CIDR6,2404:6800::/32,YouTube
#  - IP-CIDR,74.125.0.0/16,YouTube
  - DOMAIN-SUFFIX,1e100.net,YouTube
  - DOMAIN-KEYWORD,youtube-ui,YouTube
  - IP-ASN,1026,YouTube,no-resolve
  - IP-ASN,11344,YouTube,no-resolve
  - IP-ASN,36040,YouTube,no-resolve
  - IP-ASN,36561,YouTube,no-resolve
  - IP-ASN,43515,YouTube,no-resolve
#  - DOMAIN-SUFFIX,youtubei.googleapis.com,Google&Google TV
#  - DOMAIN-SUFFIX,androidtvlauncherxfe-pa.googleapis.com,Google&Google TV
#  - DOMAIN,tv.google.com,Google&Google TV
#  - DOMAIN-SUFFIX,tv.google,Google&Google TV
#  - DOMAIN-KEYWORD,tv.google,Google&Google TV
  - RULE-SET,Synology_classical,群晖服务
#  - RULE-SET,Telegram_classical,Telegram
#  - RULE-SET,telegram_ip,Telegram
  - RULE-SET,GitHub_classical,Github&Docker
  - RULE-SET,Docker_classical,Github&Docker
  - RULE-SET,Twitter_classical,Twitter&Facebook
  - RULE-SET,Facebook_classical,Twitter&Facebook
  - RULE-SET,Netflix_classical,NETFLIX&Disney+
#  - GEOSITE,youtube,YouTube
  - RULE-SET,YouTube_classical,YouTube
  - RULE-SET,Disney_classical,NETFLIX&Disney+
#  - RULE-SET,TikTok_classical,TikTok
  - RULE-SET,Viki_classical,美区流媒体
  - RULE-SET,USMedia_classical,美区流媒体
  - DOMAIN-SUFFIX,tubitv.com,美区流媒体
  - DOMAIN-SUFFIX,tubi.video,美区流媒体
  - DOMAIN-SUFFIX,tubi.io,美区流媒体
  - RULE-SET,ViuTV_classical,港台
  - RULE-SET,HiNet_classical,港台
  - DOMAIN-KEYWORD,4gtv,港台
  - RULE-SET,PrivateTracker_classical,PT站点
#  - GEOSITE,plutotv,PlutoTV
#  - DOMAIN-KEYWORD,pthome,PT站点
#  - DOMAIN-KEYWORD,haidan,PT站点
#  - DOMAIN-KEYWORD,m-team,PT站点
#  - DOMAIN-KEYWORD,1ptba,PT站点
#  - DOMAIN-KEYWORD,hdatmos,PT站点
#  - DOMAIN-KEYWORD,tracker,PT站点
#  - DOMAIN,tracker.m-team.io,PT站点
#  - DOMAIN-KEYWORD,hinet,港台
#  - DOMAIN-KEYWORD,hdfans,PT站点
#  - DOMAIN-KEYWORD,hdtime,PT站点
#  - DOMAIN,tracker.hdtime.org,PT站点
  - RULE-SET,Cloudflare_classical,Cloudflare
  - RULE-SET,Google_classical,Google&Google TV
#  - DOMAIN-SUFFIX,viki.io,Viki
#  - DOMAIN-SUFFIX,viki.net,Viki
#  - DOMAIN-SUFFIX,viki.com,Viki
#  - DOMAIN-SUFFIX,akamaized.net,Viki
#  - DOMAIN-SUFFIX,llnwi.net,Viki
#  - DOMAIN-SUFFIX,vikiplatform.com,Viki
#  - DOMAIN-SUFFIX,quickconnect.to,群晖服务
#  - DOMAIN-SUFFIX,synology.com,群晖服务
#  - DOMAIN-KEYWORD,quickconnect,群晖服务
#  - DOMAIN-KEYWORD,synology,群晖服务
#  - GEOSITE,github,Github
#  - GEOSITE,docker,Docker
#  - GEOSITE,twitter,Twitter
#  - GEOSITE,disney,Disney+
#  - GEOSITE,tiktok,TikTok
#  - GEOSITE,telegram,Telegram
#  - GEOSITE,netflix,NETFLIX
#  - GEOSITE,viu,ViuTV
#  - GEOSITE,google,Google&Google TV
#  - GEOSITE,hulu,Hulu
#  - GEOSITE,bilibili,哔哩哔哩
#  - GEOSITE,bahamut,巴哈姆特
#  - GEOSITE,spotify,Spotify
#  - GEOSITE,microsoft,微软服务
#  - DOMAIN,mikrotik.com,MikroTik服务
#  - DOMAIN,cloud2.mikrotik.com,MikroTik服务
#  - DOMAIN,whatismyipaddress.com,IP地址检测
#  - GEOSITE,geolocation-!cn,默认出口
#  - DOMAIN,tv.google.com,Google TV
#  - DOMAIN-SUFFIX,tv.google,Google TV
#  - DOMAIN-KEYWORD,tv.google,Google TV
#  - DOMAIN-SUFFIX,ebates.com,Viki
#  - DOMAIN-SUFFIX,infoseek.co.jp,Viki
#  - DOMAIN-SUFFIX,o50.jp,Viki
#  - DOMAIN-SUFFIX,r10.to,Viki
#  - DOMAIN-SUFFIX,r10s.com,Viki
#  - DOMAIN-SUFFIX,r10s.jp,Viki
#  - DOMAIN-SUFFIX,rakuten-static.com,Viki
#  - DOMAIN-SUFFIX,rakuten.ca,Viki
#  - DOMAIN-SUFFIX,rakuten.co.jp,Viki
#  - DOMAIN-SUFFIX,rakuten.com,Viki
#  - DOMAIN-SUFFIX,rakuten.com.tw,Viki
#  - DOMAIN-SUFFIX,rakuten.ne.jp,Viki
#  - DOMAIN-SUFFIX,rakuten.tw,Viki
#  - DOMAIN-SUFFIX,rclon.com,Viki
#  - DOMAIN-SUFFIX,rebates.jp,Viki
#  - DOMAIN-SUFFIX,showtime.co.jp,Viki
#  - DOMAIN-SUFFIX,viber.co.jp,Viki
#  - DOMAIN-SUFFIX,viber.com,Viki
#  - DOMAIN-KEYWORD,pandoranext,PandoraNext
#  - GEOSITE,!cn,默认出口
# - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOIP,CN))),REJECT # quic
#  - IP-CIDR,216.73.80.0/20,YouTube
#  - IP-CIDR6,2620:120:e000::/40,YouTube
#  - IP-ASN,43515,YouTube,no-resolve
#  - GEOIP,netflix,NETFLIX
#  - GEOIP,tiktok,TikTok
#  - GEOIP,telegram,Telegram
#  - GEOIP,twitter,Twitter
#  - GEOSITE,cloudflare,港台
#  - GEOIP,google,Google&Google TV
  - RULE-SET,Netflix_ip,NETFLIX&Disney+
  - RULE-SET,Facebook_ip,Twitter&Facebook
  - RULE-SET,twitter_ip,Twitter&Facebook
  - RULE-SET,google_ip,Google&Google TV
  - GEOIP,us,欧美
  - GEOIP,th,亚太
  - GEOIP,id,亚太
  - GEOIP,ph,亚太
  - GEOIP,my,亚太
  - GEOIP,sg,亚太
  - GEOIP,kh,亚太
  - GEOIP,la,亚太
  - GEOIP,vn,亚太
  - GEOIP,jp,日韩
  - GEOIP,kr,日韩
  - GEOIP,mo,港台
  - GEOIP,hk,港台
  - GEOIP,tw,港台
  - MATCH,默认出口
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: yaml}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: yaml}
  classical: &classical {type: http, interval: 86400, behavior: classical, format: yaml}
rule-providers:
  TikTok_classical:
    <<: *classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml"
  Synology_classical:
    <<: *classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Synology/Synology.yaml"
  Viki_classical:
    <<: *classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Viki/Viki.yaml"
  GitHub_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub.yaml"
  Docker_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Docker/Docker.yaml"
  Twitter_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitter/Twitter.yaml"
  Facebook_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Facebook/Facebook.yaml"
  YouTube_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml"
  Disney_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney.yaml"
  Telegram_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml"
  Netflix_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix.yaml"
  Netflix_ip:
    <<: *ip
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix_IP.yaml"
  Cloudflare_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Cloudflare/Cloudflare.yaml"
  ViuTV_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ViuTV/ViuTV.yaml"
  USMedia_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/USMedia/USMedia.yaml"
  Google_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml"
  PrivateTracker_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PrivateTracker/PrivateTracker.yaml"
  google_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.yaml"
  twitter_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.yaml"
  Facebook_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/facebook.yaml"
  telegram_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.yaml"
  HiNet_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Cloud/HiNet/HiNet.yaml"
  DNS_classical:
    <<: *classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/DNS/DNS.yaml"
```

### Description

我是使用外挂TUN程序提供socks-port端口，然后Mihomo 设置监听SOCKS5 代理端口进行的，上个月一直正常使用，不知道怎么回事这个月使用过程中发现，打开网页产生的活动连接，在关闭网页后不会自动杀手，产生很多僵尸连接。调整了配置文件也解决不了。

### Reproduction Steps

我的使用环境比较复杂，我是用ROS的BGP把路由发送给虚拟TUN网卡，然后网卡通过socks-port端口与Mihomo 通信，以前一直正常使用，最近不知道为什么产生很多僵尸连接不会自动杀死，一直保留在后台，造成运行缓慢。
