### ISSUE TITLE
invalid

### ISSUE THREAD

**Issue by jooekong** [MetaCubeX/mihomo#1356]
invalid

**Comment by guodong000** [comment]
macOS 网络里手动设置一个 DNS 试试，比如 223.5.5.5 这种，因为 TUN 的 dns-hijack 无法劫持发送到局域网的 DNS 请求。

**Comment by jooekong** [comment]
> macOS 网络里手动设置一个 DNS 试试，比如 223.5.5.5 这种，因为 TUN 的 dns-hijack 无法劫持发送到局域网的 DNS 请求。

这个观察过，TUN启动的时候会忘macOs的网络里手动加一个233.5.5.5. 另外这个不像是DNS的问题，IP的解析都是正确的，只是在连接的时候报connection refused

**Comment by guodong000** [comment]
你把 mihimo 配置文件里的 dns 和 tun 换成这个试一下（记得先在网络里边手动设置一个非局域网内的 dns）。
这是我自己的一个配置，刚试了一下能跑通。
```yaml
dns:
  enable: true
  prefer-h3: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '+.lan'
    - '+.local'
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.test.com'

tun:
  enable: true
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
```
