### ISSUE TITLE
[Bug] 更新v1.18.6之后启用v6有报错

### ISSUE THREAD

**Issue by SixGodSGD** [MetaCubeX/mihomo#1362]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Android

### System Version

安卓14 已root

### Mihomo Version

v1.18.6

### Configuration File

```yaml
mixed-port: 7890
allow-lan: true
mode: rule
log-level: info

ipv6: true
unified-delay: true
tcp-concurrent: true
keep-alive-interval: 15
external-controller: 0.0.0.0:9090
secret: "mihomo"
external-ui: ui

find-process-mode: always
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.oray.com"
    - "+.oray.net"
    - "+.orayer.com"
    - "+.apple.com"
    - "dlg.io.mi.com"
    
tun:
  enable: true
  device: tun0
  stack: system
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  strict-route: true
  auto-redirect: true
  auto-detect-interface: true
```

### Description

mihomo中启用ipv6，我使用tun，会造成tun网卡起不来，报错如下

level=error msg="Start TUN listening error: listen tcp6 [fdfe:dcba:9876::1]:0: bind: cannot assign requested address"

### Reproduction Steps

将mihomo配置文件中的ipv6开启，杀死mihomo进程，即可重现bug
