### ISSUE TITLE
[Bug] default-nameserver不支持dhcp://system

### ISSUE THREAD

**Issue by lonble** [MetaCubeX/mihomo#1363]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

Arch Linux

### Mihomo Version

Mihomo Meta alpha-0e22876 linux amd64 with go1.22.4 Fri Jun 28 06:15:31 UTC 2024
Use tags: with_gvisor

### Configuration File

```yaml
log-level: 'warning'

mode: 'rule'

ipv6: true

profile:
  store-selected: true
  store-fake-ip: true

geodata-mode: true
geox-url:
  geoip: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat'
  geosite: 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat'

mixed-port: 2080

# clash meta for android不支持system，支持dhcp://system
# 其他平台不支持dhcp://system
dns:
  enable: true
  ipv6: true
  use-system-hosts: true
  default-nameserver:
  - 'system'
  - 'dhcp://system'
  enhanced-mode: 'fake-ip'
  nameserver-policy:
    'geosite:cn':
    - 'system'
    - 'dhcp://system'
  nameserver:
  - 'tcp://8.8.8.8#PROXY'
  proxy-server-nameserver:
  - 'system'
  - 'dhcp://system'

sniffer:
  enable: false

tun:
  enable: true
  stack: 'mixed'
  device: 'utun0'
  auto-route: true
  auto-detect-interface: true
  strict-route: false
  dns-hijack:
  - 'any:53'

proxy-providers:
  subscription:
    type: 'http'
    url: '***'

proxy-groups:
- name: 'PROXY'
  type: 'select'
  use:
  - 'subscription'

rules:
- 'GEOIP,private,DIRECT'
- 'GEOSITE,geolocation-cn,DIRECT'
- 'GEOIP,cn,DIRECT'
- 'MATCH,PROXY'
```

### Description

`nameserver-policy`, `proxy-server-nameserver`这些DNS字段都支持`dhcp://system`，只有`default-nameserver`不支持。`default-nameserver`支持`system`

这个配置会报错: `default nameserver should be pure IP`

### Reproduction Steps

我猜测是字符串检查的时候把这个选项漏掉了，加上即可
