### ISSUE TITLE
[Bug] tun模式的连接出现大量connect error: context deadline exceeded

### ISSUE THREAD

**Issue by iLemonRain** [MetaCubeX/mihomo#1366]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [X] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Windows

### 系统版本

windows 10

### Mihomo 版本

cfc0233a

### 配置文件

```yaml
{
    "allow-lan": false,
    "ipv6": true,
    "mode": "rule",
    "log-level": "warning",
    "keep-alive-interval": 15,
    "dns": {
        "enable": false,
        "ipv6": true,
        "cache-algorithm": "arc",
        "listen": "0.0.0.0:53"
    },
    "tun": {
        "enable": true,
        "stack": "gvisor",
        "dns-hijack": [],
        "auto-route": true,
        "auto-detect-interface": true,
        "inet4-route-address": [
            "10.0.0.0/8",
            "172.16.0.0/12",
            "192.168.0.0/24",
            "192.168.10.0/24"
        ]
    },
    "proxies": [
        {
            "name": "server-0",
            "type": "socks5",
            "server": "xxx",
            "port": 8888,
            "udp": true,
            "tls": true,
            "skip-cert-verify": false,
            "username": "xxx",
            "password": "xxx"
        },
        {
            "name": "server-1",
            "type": "socks5",
            "server": "yyy",
            "port": 8888,
            "udp": true,
            "tls": true,
            "skip-cert-verify": false,
            "username": "yyy",
            "password": "yyy"
        },
        {
            "name": "server-2",
            "type": "socks5",
            "server": "zzz",
            "port": 8888,
            "udp": true,
            "tls": true,
            "skip-cert-verify": false,
            "username": "zzz",
            "password": "zzz"
        }
    ],
    "proxy-groups": [
        {
            "name": "Proxy",
            "type": "load-balance",
            "proxies": [
                "server-0",
                "server-1",
                "server-2"
            ],
            "interval": 300,
            "strategy": "consistent-hashing"
        }
    ],
    "rules": [
        "IP-CIDR,几个DNS,DIRECT",
        "NETWORK,udp,DIRECT",
        "IP-CIDR,10.0.0.0/8,Proxy",
        "IP-CIDR,172.16.0.0/12,Proxy",
        "IP-CIDR,192.168.0.1/24,Proxy",
        "IP-CIDR,192.168.10.1/24,Proxy",
        "MATCH,DIRECT"
    ]
}
```

### 描述

现在需要将一些内网网段用tun模式代理到流量网关，发现在有的win10电脑上发生巨量报错，类似于：
time="2024-06-20T17:43:05.6979607+08:00" level=warning msg="[TCP] dial Proxy (match IPCIDR/10.0.0.0/8) srcip:srcport --> 流量网关ip:流量网关端口  error: 流量网关ip:流量网关端口 connect error: context deadline exceeded"
该日志会不断循环产生，其中每一条连接日志的srcport会发生改变，很快造成cpu占用过高和端口不足

### 重现方式

相同的配置，部分电脑必现，部分电脑（即使都是win10）永远不会出现
