### ISSUE TITLE
[Bug] dns:   ipv6: false 不起作用？或者是我的配置有哪些问题。

### ISSUE THREAD

**Issue by twiehpooh** [MetaCubeX/mihomo#1370]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows, Linux

### System Version

Windows 11 24H2, OpenWrt 23.05

### Mihomo Version

Mihomo Meta v1.18.6

### Configuration File

```yaml
部分运行时配置

mode: rule
mixed-port: 7897
allow-lan: true
log-level: debug
ipv6: true
external-controller: 127.0.0.1:9097
secret: ''
sniffer:
  enable: true
  override-destination: true
  force-domain:
  - +.v2ex.com
  sniffing:
  - tls
  - http
bind-address: '*'
profile:
  store-selected: true
  store-fake-ip: true
find-process-mode: strict
c:
  type: http
  behavior: classical
  interval: 86400
dns:
  enable: true
  prefer-h3: false
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - localhost.ptlogin2.qq.com
  - +.stun.*.*
  - +.stun.*.*.*
  - +.stun.*.*.*.*
  - +.stun.*.*.*.*.*
  - '*.n.n.srv.nintendo.net'
  - +.stun.playstation.net
  - xbox.*.*.microsoft.com
  - '*.*.xboxlive.com'
  - WORKGROUP
  - '*.msftncsi.com'
  - '*.msftconnecttest.com'
  nameserver:
  - https://8.8.8.8/dns-query#DNS&h3=false
  - https://1.1.1.1/dns-query#DNS&h3=false
  - https://94.140.14.140/dns-query#DNS&h3=false
  nameserver-policy:
    '*.msftncsi.com,*.msftconnecttest.com':
    - https://8.8.8.8/dns-query#DNS&h3=false
    - https://1.1.1.1/dns-query#DNS&h3=false
    - https://94.140.14.140/dns-query#DNS&h3=false
    geosite:private,apple-cn,google-cn,cn,category-games@cn:
    - tls://1.12.12.12:853#h3=false
    - https://223.5.5.5/dns-query#h3=false
    - tls://120.53.53.53#h3=false
  use-hosts: true
  fallback: []
global-client-fingerprint: edge
d:
  type: http
  behavior: domain
  interval: 86400
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb
tun:
  enable: true
  stack: mixed
  dns-hijack:
  - any:53
  auto-route: true
  device: Mihomo
  auto-detect-interface: true
  strict-route: false
  mtu: 1500
```

### Description

```yaml
dns:
  ipv6: false
```
不起作用？或者是我的配置有哪些问题。

### Reproduction Steps

![image](https://github.com/MetaCubeX/mihomo/assets/112604675/28dde19d-19ae-482e-a4a7-ed1d28eea993)
在 openclash 中我也出现了这种情况，我使用 smartdns 设置禁止返回AAAA记录来避免这种情况。

### Logs

```shell
time="2024-07-07T15:14:17.7059739Z" level=debug msg="[DNS] resolve api.bilibili.com from tls://120.53.53.53:853"
time="2024-07-07T15:14:17.7059739Z" level=debug msg="[DNS] resolve api.bilibili.com from tls://1.12.12.12:853"
time="2024-07-07T15:14:17.7059739Z" level=debug msg="[DNS] resolve api.bilibili.com from tls://1.12.12.12:853"
time="2024-07-07T15:14:17.7059739Z" level=debug msg="[DNS] resolve api.bilibili.com from tls://120.53.53.53:853"
time="2024-07-07T15:14:17.7059739Z" level=debug msg="[DNS] resolve api.bilibili.com from https://223.5.5.5:443/dns-query"
time="2024-07-07T15:14:17.7059739Z" level=debug msg="creating a new http client"
time="2024-07-07T15:14:17.7059739Z" level=debug msg="[https://223.5.5.5:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2024-07-07T15:14:17.7059739Z" level=debug msg="[DNS] resolve api.bilibili.com from https://223.5.5.5:443/dns-query"
time="2024-07-07T15:14:17.7687813Z" level=debug msg="[DNS] api.bilibili.com --> [110.40.30.34 119.84.174.67 110.40.30.33 110.40.30.32 119.84.174.68 119.84.174.66] A from https://223.5.5.5:443/dns-query"
time="2024-07-07T15:14:17.7687813Z" level=debug msg="[DNS] api.bilibili.com --> [240e:bf:b800:4300:1::15 240e:d9:a600:834::12 240e:bf:b800:4300:1::14 240e:930:c200:209::34 240e:bf:b800:4300:1::13 240e:d9:a600:834::14 240e:bf:b800:4300:1::12 240e:d9:a600:834::13] AAAA from https://223.5.5.5:443/dns-query"
time="2024-07-07T15:14:17.775413Z" level=info msg="[TCP] [fdfe:dcba:9876::1]:4891 --> api.bilibili.com:443 match GeoSite(cn) using 🎯 全球直连[DIRECT]"
```
