### ISSUE TITLE
[Bug] 手机热点代理模式大量error: dns resolve failed

### ISSUE THREAD

**Issue by utopeadia** [MetaCubeX/mihomo#1373]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### System Version

macos14.5

### Mihomo Version

1.18.6

### Configuration File

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: false
bind-address: "*"
ipv6: true
external-controller: 127.0.0.1:9090
mode: rule
log-level: info
unified-delay: true
global-ua: clash.meta
geo-auto-update: true
geodata-mode: false
geo-update-interval: 12
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/Hackl0us/GeoIP2-CN@release/Country.mmdb"
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8888]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
    - +.x.com
    - +.google.com
    - +.facebook.com
    - +.youtube.com
    - +.googlevideo.com
    - +.twitter.com
    - +.instagram.com
  skip-domain:
    - Mijia Cloud
    - Xiaomi Cloud
    - +.apple.com
    - +.icloud.com
dns:
  enabled: true
  ipv6: false
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - doh.pub
    - WORKGROUP
    - controlplane.tailscale.com
    - log.tailscale.io
    - 1.1.1.1
    - 119.29.29.29
    - 223.5.5.5
    - 8.8.8.8
  default-nameserver:
    - 119.29.29.29
    - 1.1.1.1
  nameserver:
    - system
    - dhcp://en0
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
    - https://8.8.8.8/dns-query
  fallback:
    - https://8.8.8.8/dns-query
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: false
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
      - 46.82.174.69/32
      - 59.24.3.174/32
      - 8.7.198.46/32
      - 93.46.8.90/32
    domain:
      - "+.ai.com"
      - "+.algolia.net"
      - "+.anthropic.com"
      - "+.arkoselabs.com"
      - "+.auth0.com"
      - "+.azure.com"
      - "+.azureedge.net"
      - "+.azureedge.net"
      - "+.bing.com"
      - "+.bingapis.com"
      - "+.bugsnag.com"
      - "+.chatgpt.com"
      - "+.claude.ai"
      - "+.cloudflare.net"
      - "+.cloudflareinsights.com"
      - "+.cohere.ai"
      - "+.docker.com"
      - "+.docker.io"
      - "+.facebook.com"
      - "+.github.com"
      - "+.githubusercontent.com"
      - "+.google"
      - "+.google.com"
      - "+.google.dev"
      - "+.googleapis.cn"
      - "+.googlevideo.com"
      - "+.identrust.com"
      - "+.instagram.com"
      - "+.intercom.io"
      - "+.live.com"
      - "+.livekit.cloud"
      - "+.microsoft.com"
      - "+.microsoftapp.net"
      - "+.minecraft.net"
      - "+.msn.com"
      - "+.openai.com"
      - "+.poe.com"
      - "+.segment.com"
      - "+.segment.io"
      - "+.sentry.io"
      - "+.synn.cc"
      - "+.stripe.com"
      - "+.t.me"
      - "+.tailscale.com"
      - "+.tailscale.io"
      - "+.twitter.com"
      - "+.usefathom.com"
      - "+.v2ex.com"
      - "+.windows.net"
      - "+.wootric.com"
      - "+.x.com"
      - "+.xn--ngstr-lra8j.com"
      - "+.youtube.com"
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
  device: utuncat0
  mtu: 1500
  strict-route: true
  include-package:
    - com.android.chrome
  exclude-package:
    - com.android.captiveportallogin
```

### Description

连接手机热点，使用代理模式系统存在大量dns错误，反复刷新可以恢复，相同热点在tun模式下正常

### Reproduction Steps

连接热点，开启系统代理
