### ISSUE TITLE
[Bug] level=warning msg="Deprecated: Use Sniff instead"

### ISSUE THREAD

**Issue by h0NponJR** [MetaCubeX/mihomo#1381]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

Ubuntu 24.04 LTS

### Mihomo Version

Mihomo Meta alpha-0e22876 linux amd64 with go1.22.4 Fri Jun 28 06:16:30 UTC 2024

### Configuration File

```yaml
mixed-port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
allow-lan: true
ipv6: true

mode: Rule

log-level: info
external-controller: 0.0.0.0:9090
routing-mark: 255
secret: ''

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true

proxies:
proxy-groups:
  - name: Manual
    type: select
    proxies:
      - DIRECT

rules:
  - MATCH,Manual
```

### Description

When the mihomo is starting, the `level=warning msg="Deprecated: Use Sniff instead"` appears in logs

### Reproduction Steps

Enable sniffer in configuration and start mihomo

### Logs

```shell
level=warning msg="Deprecated: Use Sniff instead
```
