### ISSUE TITLE
[Bug] The dns over proxy log is meaningless and too many

### ISSUE THREAD

**Issue by h0NponJR** [MetaCubeX/mihomo#1382]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

Ubuntu 24.04 LTS

### Mihomo Version

Mihomo Meta alpha-0e22876 linux amd64 with go1.22.4 Fri Jun 28 06:16:30 UTC 2024

### Configuration File

```yaml
mixed-port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
allow-lan: true
ipv6: true

mode: Rule

log-level: info
external-controller: 0.0.0.0:9090
routing-mark: 255
secret: ''

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  proxy-server-nameserver:
    - 192.168.1.1
  nameserver:
    - 8.8.8.8#Manual
  nameserver-policy:
    rule-set:override: 8.8.8.8#Manual
    rule-set:private,direct: 192.168.1.1

proxies:
  - {name: HK 01 | ss, type: ss, server:xxx, port:80, cipher: 2022-blake3-aes-256-gcm, password:xxx, udp: true, udp-over-tcp: true, udp-over-tcp-version: 2}
proxy-groups:
  - name: Manual
    type: select
    proxies:
      - HK 01 | ss
rules:
  - IP-CIDR,8.8.8.8,Manual
  - RULE-SET,override,Manual
  - MATCH,Manual
```

### Description

This configuration `8.8.8.8#Manual` made the DNS query through a proxy directly. I think that Mihomo ignored the rule `IP-CIDR,8.8.8.8,Manual` is no problem, but it doesn't need to say `[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss` continuesly

### Reproduction Steps

Make DNS query over proxy by adding `#Manual` after the address `8.8.8.8.`，the log will continuously output `[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss`

### Logs

```shell
time="2024-07-11T16:25:37.530223886Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:37.540602361Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:37.831152372Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:37.831899427Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:37.901661119Z" level=info msg="[TCP] 192.168.31.20:3685 --> www.google.com:443 match RuleSet(override) using Manual[HK 01 | ss]"
time="2024-07-11T16:25:37.963570755Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:38.173728803Z" level=info msg="[TCP] 192.168.31.20:3687 --> www.gstatic.com:443 match RuleSet(override) using Manual[HK 01 | ss]"
time="2024-07-11T16:25:38.345639591Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:38.563408524Z" level=info msg="[TCP] 192.168.31.20:3688 --> waa-pa.clients6.google.com:443 match RuleSet(override) using Manual[HK 01 | ss]"
time="2024-07-11T16:25:38.592730001Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:38.592821961Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:38.82851621Z" level=info msg="[TCP] 192.168.31.20:3689 --> accounts.google.com:443 match RuleSet(override) using Manual[HK 01 | ss]"
time="2024-07-11T16:25:38.986061203Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:39.053829943Z" level=info msg="[TCP] 192.168.31.20:3690 --> 192.168.31.10:9090 match RuleSet(lancidr) using DIRECT"
time="2024-07-11T16:25:39.282227522Z" level=info msg="[TCP] 192.168.31.20:3691 --> play.google.com:443 match RuleSet(override) using Manual[HK 01 | ss]"
time="2024-07-11T16:25:39.372180737Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:39.985388951Z" level=info msg="[TCP] 192.168.31.20:3686 --> play.google.com:443 match RuleSet(override) using Manual[HK 01 | ss]"
time="2024-07-11T16:25:43.099966714Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:43.105410143Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:48.10119295Z" level=info msg="[TCP] 192.168.31.20:3692 --> ogs.google.com:443 match RuleSet(override) using Manual[HK 01 | ss]"
time="2024-07-11T16:25:49.095072476Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:49.101421338Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:50.095340699Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:50.099879237Z" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using HK 01 | ss"
time="2024-07-11T16:25:50.252903484Z" level=info msg="[TCP] 192.168.31.20:3695 --> ssl.gstatic.com:443 match RuleSet(override) using Manual[HK 01 | ss]"
time="2024-07-11T16:25:51.219195606Z" level=info msg="[TCP] 192.168.31.20:3696 --> clients4.google.com:443 match RuleSet(override) using Manual[HK 01 | ss]"
```
