### ISSUE TITLE
[Bug] Mihomo always uses the Host in the HTTP header to connect, even if the sniffer and override-destination is disabled

### ISSUE THREAD

**Issue by h0NponJR** [MetaCubeX/mihomo#1386]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

Ubuntu 24.04 LTS

### Mihomo Version

Mihomo Meta alpha-0e22876 linux amd64 with go1.22.4 Fri Jun 28 06:16:30 UTC 2024

### Configuration File

```yaml
mixed-port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
allow-lan: true
ipv6: true

mode: Rule

log-level: info
external-controller: 0.0.0.0:9090
routing-mark: 255
secret: ''

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: normal
  proxy-server-nameserver:
    - 192.168.1.1
  nameserver:
    - 8.8.8.8

sniffer:
  enable: false
  force-dns-mapping: false
  parse-pure-ip: false
  override-destination: false
```

### Description

Mihomo always uses the Host in the HTTP header to connect, even if the sniffer is disabled

#### Open postman, set the proxy to mihomo, and send GET to http://95.85.16.212. This IP address will return an iptest page
![image](https://github.com/user-attachments/assets/1768edbb-092b-4a60-bc73-f8fb9a820b56)

![image](https://github.com/user-attachments/assets/ef3ff8d1-b529-4acb-be6e-d49f33b77d5b)
-----------------
-----------------
-----------------
-----------------
#### Fill in the Host Header with www.google.com and send it again. Mihomo will ignore the IP address and send the request directly to www.google.com.
![image](https://github.com/user-attachments/assets/abaa97de-50a4-40e0-9cbb-92e8ecbddd99)

#### The log before setting the Host header
```shell
time="2024-07-14T08:21:11.171001547Z" level=info msg="[TCP] 192.168.1.20:13968 --> 95.85.16.212:80 match Match using Manual[HK 01 | ss]"
```

#### The log after setting the Host header
```shell
time="2024-07-14T08:21:27.465335013Z" level=info msg="[TCP] 192.168.1.20:13979 --> www.google.com:80 match Match using Manual[HK 01 | ss]"
```
