### ISSUE TITLE
[Bug] 为策略组启用 include-all-providers 时，节点排序问题

### ISSUE THREAD

**Issue by KsharpMoring** [MetaCubeX/mihomo#1387]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Windows

### 系统版本

Windows 10 专业版 22H2 19045.4529

### Mihomo 版本

Mihomo Meta v1.18.6 windows amd64 with go1.22.4 Mon Jul  1 15:03:47 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
proxy-providers:
  p1:
    type: file
    path: ./proxy_providers/p1.yaml
    override:
      additional-prefix: "P1 | "
  p2:
    type: file
    path: ./proxy_providers/p2.yaml
    override:
      additional-prefix: "P2 | "
  p3:
    type: file
    path: ./proxy_providers/p3.yaml
    override:
      additional-prefix: "P3 | "

proxy-groups:
  - name: Proxy
    type: select
    include-all-providers: true
    proxies:
      - DIRECT
```

### 描述

当使用形如上述配置时，在webui、或第三方工具ui的「代理」界面为策略组选择节点时，节点并没有按照p1 p2 p3的顺序排列，而是每次启动都随机变化（例如p3 p1 p2的顺序）

### 重现方式

使用形如上述配置启动clash后，使用任意webui或第三方工具ui查看「代理」界面，可以发现节点未按照p1 p2 p3的书写顺序排列
