### ISSUE TITLE
[Bug] rule-set with AND & OR & NOT shows empty when running

### ISSUE THREAD

**Issue by RayWangQvQ** [MetaCubeX/mihomo#1390]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

Win11

### Mihomo Version

v1.18.6

### Configuration File

```yaml
rule-providers:
  Set-China:
    <<: *rule_provider_classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Classical_No_Resolve.yaml"
    path: ./ruleset/Set-China.yaml

rules:
  # SSH
  - DST-PORT,22,🇸SSH
  # 禁用国外站的udp443
  - AND,((NETWORK,UDP),(DST-PORT,443),(NOT,((RULE-SET,Set-China))),(NOT,((DOMAIN-REGEX,^dns\..+)))),🇶Quic
```

### Description

![image](https://github.com/user-attachments/assets/b39acf3c-219b-411b-a714-e79b03bbe23d)

The rule shows empty string for rule-set

### Reproduction Steps

add rules and run the mihomo
