### ISSUE TITLE
[Bug] 内核启动时似乎不遵守proxy-providers中的interval，而是直接请求url

### ISSUE THREAD

**Issue by ziiaoc** [MetaCubeX/mihomo#1398]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows, Android

### System Version

Windows11 Clash_Nyanpasu1.5.1, Android14 FlClash0.8.44

### Mihomo Version

alpha-9e3589d

### Configuration File

```yaml
mode: rule
mixed-port: 7890
allow-lan: true
log-level: debug
ipv6: true
secret: *removed*
external-controller: 127.0.0.1:17650
dns:
  enable: true
  listen: 127.0.0.1:1053
  ipv6: false
  default-nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  use-hosts: true
  fake-ip-filter:
  - '*.lan'
  - '*.localdomain'
  - '*.example'
  - '*.invalid'
  - '*.localhost'
  - '*.test'
  - '*.local'
  - '*.home.arpa'
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - '*.time.edu.cn'
  - '*.ntp.org.cn'
  - +.pool.ntp.org
  - time1.cloud.tencent.com
  - music.163.com
  - '*.music.163.com'
  - '*.126.net'
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - '*.kuwo.cn'
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - '*.y.qq.com'
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - '*.xiami.com'
  - '*.music.migu.cn'
  - music.migu.cn
  - +.msftconnecttest.com
  - +.msftncsi.com
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - +.srv.nintendo.net
  - +.stun.playstation.net
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - +.ipv6.microsoft.com
  - +.battlenet.com.cn
  - +.wotgame.cn
  - +.wggames.cn
  - +.wowsgame.cn
  - +.wargaming.net
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - +.stun.*.*
  - +.stun.*.*.*
  - +.stun.*.*.*.*
  - heartbeat.belkin.com
  - '*.linksys.com'
  - '*.linksyssmartwifi.com'
  - '*.router.asus.com'
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - '*.square-enix.com'
  - '*.finalfantasyxiv.com'
  - '*.ffxiv.com'
  - '*.ff14.sdo.com'
  - ff.dorado.sdo.com
  - '*.mcdn.bilivideo.cn'
  - +.media.dssott.com
  - +.pvp.net
  nameserver:
  - tls://223.5.5.5:853
  - tls://223.6.6.6:853
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
tcp-concurrent: true
proxy-groups:
- name: 🔰 节点选择
  type: select
  use:
  - myproxy
- name: ⛔️ 广告拦截
  type: select
  proxies:
  - REJECT
  - DIRECT
  - 🔰 节点选择
- name: 🌍 国外媒体
  type: select
  use:
  - myproxy
  proxies:
  - 🔰 节点选择
- name: 🤖 Copilot
  type: select
  use:
  - myproxy
  proxies:
  - 🔰 节点选择
- name: Ⓜ️ 微软服务
  type: select
  proxies:
  - DIRECT
  - 🔰 节点选择
- name: 🐟 漏网之鱼
  type: select
  proxies:
  - 🔰 节点选择
  - DIRECT
proxy-providers:
  myproxy:
    type: http
    url: *removed*
    interval: 86400
    proxy: DIRECT
    path: ./provider1.yaml
    health-check:
      enable: true
      interval: 600
      lazy: true
      url: http://www.gstatic.com/generate_204
#rules不重要没粘贴
```

### Description

（刚从subconverter换到proxy-providers）
内核在启动时似乎不遵守proxy-providers中的interval设置，启动时会请求url多次，而不是像各GUI代理软件达到设定的间隔时间再进行请求，部分机场限制订阅每日获取次数（解释是订阅过多怀疑共享封号）
感觉可以通过读取保存的yaml修改时间来和interval比较判断是否需要爬取url

### Reproduction Steps

打开GUI代理软件，路由器上tcpdump就可见对url请求（本机似乎抓不到），andorid上flClash自带的请求记录上是请求4次url
