### ISSUE TITLE
dns泄露问题

### ISSUE THREAD

**Issue by GeorgeRudd** [MetaCubeX/mihomo#140]
请直接看最后

**Comment by Skyxim** [comment]
@GeorgeRudd 使用fake-ip 配合规则所有IP-CIDR规则添加no-resolve

**Comment by xishang0128** [comment]
@GeorgeRudd 有没有一种可能,你压根就没劫持到dns

**Comment by xishang0128** [comment]
@GeorgeRudd 另外,如果有问题请附带debug level的log,而不是仅贴一份配置

**Comment by Taoiy** [comment]
> > @GeorgeRudd 有没有一种可能,你压根就没劫持到dns
> 
> 请问tun模式下如何配置dns劫持

```
tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53

```
