### ISSUE TITLE
[Bug] rule-providers中出现IP-CIDR等规则时，文件中所有的域名均变成了本地解析DNS！

### ISSUE THREAD

**Issue by dfmntx** [MetaCubeX/mihomo#1400]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

MacOS

### 系统版本

macOS 13.6.7

### Mihomo 版本

Mihomo Meta v1.18.6 darwin amd64 with go1.22.4 Mon Jul  1 15:01:53 UTC 2024
Mihomo Meta alpha-28794c6 darwin amd64 with go1.22.5 Fri Jul 19 14:24:57 UTC 2024

### 配置文件

```yaml
配置一:
    config.yaml: "
      mixed-port: 1082

      allow-lan: true
      # bind-address: "*"
      find-process-mode: strict

      mode: rule

      geodata-mode: true
      geox-url:
        geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
        geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
        mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
        asn: "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb"

      geo-auto-update: true
      geo-update-interval: 24

      log-level: debug
      ipv6: true

      external-controller: 127.0.0.1:9090

      external-ui: dashboard/metacubexd
      external-ui-name: metacubexd
      external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

      profile:
        store-selected: true
        store-fake-ip: true

      unified-delay: true
      tcp-concurrent: true

      dns:
        enable: true
        prefer-h3: true
        listen: 0.0.0.0:53
        ipv6: true
        enhanced-mode: fake-ip
        fake-ip-range: 198.18.0.1/16
        fake-ip-filter:
          - '*.lan'
          - localhost.ptlogin2.qq.com

        default-nameserver:
          - tls://208.67.220.220:853
          - tls://208.67.222.222:853
          # - https://1.0.0.1/dns-query

        nameserver-policy:
          '+.lan': 'system'
          'geosite:cn': ['223.5.5.5', '223.6.6.6']

        nameserver:
          - tls://8.8.4.4:853
          - tls://1.0.0.1:853

        proxy-server-nameserver:
          - tls://8.8.4.4:853
          - tls://1.0.0.1:853
          - https://dns.adguard-dns.com/dns-query

      proxies:
        - name: proxy1
          type: ss
          server: x.x.x.x
          port: 37655
          cipher: xchacha20-ietf-poly1305
          password: "password1"
          udp: true

        - name: proxy2
          type: ss
          server: x.x.x.x
          port: 23875
          cipher: xchacha20-ietf-poly1305
          password: "password2"
          udp: true

      proxy-groups:
        - name: "PROXY-FALLBACK"
          type: fallback
          proxies:
            - proxy1
            - proxy2
          url: "https://cp.cloudflare.com/generate_204"
          interval: 300

      rule-providers:
        openai:
          behavior: classical
          interval: 43200
          path: ./provider/rule-set/openai_domain.yaml
          type: http
          url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml"

      rules:
        # INNER
        - IN-TYPE,INNER,PROXY-FALLBACK
        # REJECT
        - GEOSITE,category-ads-all,REJECT-DROP
        # PROXY
        - RULE-SET,openai,PROXY-FALLBACK
        # DIRECT
        - GEOSITE,cn,DIRECT
        - GEOSITE,private,DIRECT
        ## DIRECT GEOIP Rules
        - GEOIP,private,DIRECT,no-resolve
        - GEOIP,CN,DIRECT
        - MATCH,PROXY-FALLBACK
    ",
    openai_domain.yaml: "
      payload:
        - DOMAIN,browser-intake-datadoghq.com
        - DOMAIN,chat.openai.com.cdn.cloudflare.net
        - DOMAIN,gemini.google.com
        - DOMAIN,openai-api.arkoselabs.com
        - DOMAIN,openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net
        - DOMAIN,openaicomproductionae4b.blob.core.windows.net
        - DOMAIN,production-openaicom-storage.azureedge.net
        - DOMAIN,static.cloudflareinsights.com
        - DOMAIN-SUFFIX,ai.com
        - DOMAIN-SUFFIX,algolia.net
        - DOMAIN-SUFFIX,api.statsig.com
        - DOMAIN-SUFFIX,auth0.com
        - DOMAIN-SUFFIX,chatgpt.com
        - DOMAIN-SUFFIX,chatgpt.livekit.cloud
        - DOMAIN-SUFFIX,client-api.arkoselabs.com
        - DOMAIN-SUFFIX,events.statsigapi.net
        - DOMAIN-SUFFIX,featuregates.org
        - DOMAIN-SUFFIX,host.livekit.cloud
        - DOMAIN-SUFFIX,identrust.com
        - DOMAIN-SUFFIX,intercom.io
        - DOMAIN-SUFFIX,intercomcdn.com
        - DOMAIN-SUFFIX,launchdarkly.com
        - DOMAIN-SUFFIX,oaistatic.com
        - DOMAIN-SUFFIX,oaiusercontent.com
        - DOMAIN-SUFFIX,observeit.net
        - DOMAIN-SUFFIX,openai.com
        - DOMAIN-SUFFIX,openaiapi-site.azureedge.net
        - DOMAIN-SUFFIX,openaicom.imgix.net
        - DOMAIN-SUFFIX,segment.io
        - DOMAIN-SUFFIX,sentry.io
        - DOMAIN-SUFFIX,stripe.com
        - DOMAIN-SUFFIX,turn.livekit.cloud
        - DOMAIN-KEYWORD,openai
        - IP-CIDR,24.199.123.28/32
        - IP-CIDR,64.23.132.171/32
        - IP-ASN,20473
    "
配置二:
    config.yaml: "
      mixed-port: 1082

      allow-lan: true
      # bind-address: "*"
      find-process-mode: strict

      mode: rule

      geodata-mode: true
      geox-url:
        geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
        geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
        mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
        asn: "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb"

      geo-auto-update: true
      geo-update-interval: 24

      log-level: debug
      ipv6: true

      external-controller: 127.0.0.1:9090

      external-ui: dashboard/metacubexd
      external-ui-name: metacubexd
      external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

      profile:
        store-selected: true
        store-fake-ip: true

      unified-delay: true
      tcp-concurrent: true

      dns:
        enable: true
        prefer-h3: true
        listen: 0.0.0.0:53
        ipv6: true
        enhanced-mode: fake-ip
        fake-ip-range: 198.18.0.1/16
        fake-ip-filter:
          - '*.lan'
          - localhost.ptlogin2.qq.com

        default-nameserver:
          - tls://208.67.220.220:853
          - tls://208.67.222.222:853
          # - https://1.0.0.1/dns-query

        nameserver-policy:
          '+.lan': 'system'
          'geosite:cn': ['223.5.5.5', '223.6.6.6']

        nameserver:
          - tls://8.8.4.4:853
          - tls://1.0.0.1:853

        proxy-server-nameserver:
          - tls://8.8.4.4:853
          - tls://1.0.0.1:853
          - https://dns.adguard-dns.com/dns-query

      proxies:
        - name: proxy1
          type: ss
          server: x.x.x.x
          port: 37655
          cipher: xchacha20-ietf-poly1305
          password: "password1"
          udp: true

        - name: proxy2
          type: ss
          server: x.x.x.x
          port: 23875
          cipher: xchacha20-ietf-poly1305
          password: "password2"
          udp: true

      proxy-groups:
        - name: "PROXY-FALLBACK"
          type: fallback
          proxies:
            - proxy1
            - proxy2
          url: "https://cp.cloudflare.com/generate_204"
          interval: 300

      rule-providers:
        openai:
          behavior: classical
          interval: 43200
          path: ./provider/rule-set/openai_domain.yaml
          type: http
          url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml"

      rules:
        # INNER
        - IN-TYPE,INNER,PROXY-FALLBACK
        # REJECT
        - GEOSITE,category-ads-all,REJECT-DROP
        # PROXY
        - RULE-SET,openai,PROXY-FALLBACK
        # 将openai_domain.yaml中的IP-CIDR和IP-ASN挪到下面：
        - IP-CIDR,24.199.123.28/32,PROXY-FALLBACK
        - IP-CIDR,64.23.132.171/32,PROXY-FALLBACK
        - IP-ASN,20473,PROXY-FALLBACK
        # DIRECT
        - GEOSITE,cn,DIRECT
        - GEOSITE,private,DIRECT
        ## DIRECT GEOIP Rules
        - GEOIP,private,DIRECT,no-resolve
        - GEOIP,CN,DIRECT
        - MATCH,PROXY-FALLBACK
    ",
    openai_domain.yaml: "
      payload:
        - DOMAIN,browser-intake-datadoghq.com
        - DOMAIN,chat.openai.com.cdn.cloudflare.net
        - DOMAIN,gemini.google.com
        - DOMAIN,openai-api.arkoselabs.com
        - DOMAIN,openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net
        - DOMAIN,openaicomproductionae4b.blob.core.windows.net
        - DOMAIN,production-openaicom-storage.azureedge.net
        - DOMAIN,static.cloudflareinsights.com
        - DOMAIN-SUFFIX,ai.com
        - DOMAIN-SUFFIX,algolia.net
        - DOMAIN-SUFFIX,api.statsig.com
        - DOMAIN-SUFFIX,auth0.com
        - DOMAIN-SUFFIX,chatgpt.com
        - DOMAIN-SUFFIX,chatgpt.livekit.cloud
        - DOMAIN-SUFFIX,client-api.arkoselabs.com
        - DOMAIN-SUFFIX,events.statsigapi.net
        - DOMAIN-SUFFIX,featuregates.org
        - DOMAIN-SUFFIX,host.livekit.cloud
        - DOMAIN-SUFFIX,identrust.com
        - DOMAIN-SUFFIX,intercom.io
        - DOMAIN-SUFFIX,intercomcdn.com
        - DOMAIN-SUFFIX,launchdarkly.com
        - DOMAIN-SUFFIX,oaistatic.com
        - DOMAIN-SUFFIX,oaiusercontent.com
        - DOMAIN-SUFFIX,observeit.net
        - DOMAIN-SUFFIX,openai.com
        - DOMAIN-SUFFIX,openaiapi-site.azureedge.net
        - DOMAIN-SUFFIX,openaicom.imgix.net
        - DOMAIN-SUFFIX,segment.io
        - DOMAIN-SUFFIX,sentry.io
        - DOMAIN-SUFFIX,stripe.com
        - DOMAIN-SUFFIX,turn.livekit.cloud
        - DOMAIN-KEYWORD,openai
        # 删掉了下方的IP-CIDR和IP-ASN！
    "
```

### 描述

        首先，感谢MetaCudeX的各位对此项目的付出！
        我遇到的问题是：使用配置一时，chatgpt.com、cdn.oaistatic.com、ab.chatgpt.com的DNS为本地解析！然而，在使用配置二时，chatgpt.com、cdn.oaistatic.com、ab.chatgpt.com的DNS为远程解析！
        配置一和配置二的差异在于"- IP-CIDR,24.199.123.28/32"、"- IP-CIDR,64.23.132.171/32"和"- IP-ASN,20473"这三条规则的位置。在配置一中，这三条规则位于openai_domain.yaml文件中。在配置二中，我将这三条规则挪到了“- RULE-SET,openai,PROXY-FALLBACK”的下方。
        我的问题是，这种情况是有意为之，还是bug？在rule-providers文件中有诸如IP-CIDR、IP-CIDR6、IP-ASN规则时，是否可以行为统一，均使用远程解析？
        麻烦赐教，谢谢！

### 重现方式

分别在使用配置一和配置二时，访问chatgpt.com，应该可以得到与我上传日志类似的结果！

### 日志

```shell
配置一log: "
time="2024-07-20T22:28:38.768214+08:00" level=info msg="Start initial configuration in progress"
time="2024-07-20T22:28:38.768699+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-07-20T22:28:38.768757+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-07-20T22:28:39.154275+08:00" level=info msg="Start initial GeoSite rule category-ads-all => REJECT-DROP, records: 719"
time="2024-07-20T22:28:39.453358+08:00" level=info msg="Start initial GeoSite rule cn => DIRECT, records: 90310"
time="2024-07-20T22:28:39.462332+08:00" level=info msg="Start initial GeoSite rule private => DIRECT, records: 142"
time="2024-07-20T22:28:39.474246+08:00" level=info msg="Start initial GeoIP rule private => DIRECT, records: 18"
time="2024-07-20T22:28:39.478147+08:00" level=info msg="Start initial GeoIP rule cn => DIRECT, records: 10791"
time="2024-07-20T22:28:39.478554+08:00" level=info msg="Initial configuration complete, total time: 710ms"
time="2024-07-20T22:28:39.479019+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2024-07-20T22:28:39.48154+08:00" level=info msg="Sniffer is closed"
time="2024-07-20T22:28:39.481649+08:00" level=info msg="Use tcp concurrent"
time="2024-07-20T22:28:39.785812+08:00" level=info msg="DNS server listening at: [::]:53"
time="2024-07-20T22:28:39.786077+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:1082"
time="2024-07-20T22:28:39.78619+08:00" level=info msg="Start initial provider openai"
time="2024-07-20T22:28:40.085005+08:00" level=info msg="[TCP] mihomo --> raw.githubusercontent.com:443 match InType(INNER) using PROXY-FALLBACK[proxy1]"
time="2024-07-20T22:28:41.082524+08:00" level=info msg="Start initial Compatible provider PROXY-FALLBACK"
time="2024-07-20T22:28:41.082584+08:00" level=info msg="Start initial Compatible provider default"
time="2024-07-20T22:28:41.082672+08:00" level=debug msg="Start New Health Checking {741b58a1-8c84-4670-b1a3-0e8b22cab4f2}"
time="2024-07-20T22:28:41.082837+08:00" level=debug msg="Health Checking, proxy: proxy2, url: https://cp.cloudflare.com/generate_204, id: {741b58a1-8c84-4670-b1a3-0e8b22cab4f2}"
time="2024-07-20T22:28:41.082878+08:00" level=debug msg="Health Checking, proxy: proxy1, url: https://cp.cloudflare.com/generate_204, id: {741b58a1-8c84-4670-b1a3-0e8b22cab4f2}"
time="2024-07-20T22:28:41.083053+08:00" level=info msg="[GEO] last update time 2024-07-20 21:41:43.416310118 +0800 CST"
time="2024-07-20T22:28:42.473635+08:00" level=debug msg="Health Checked, proxy: proxy1, url: https://cp.cloudflare.com/generate_204, alive: true, delay: 334 ms uid: {741b58a1-8c84-4670-b1a3-0e8b22cab4f2}"
time="2024-07-20T22:28:42.478471+08:00" level=debug msg="Health Checked, proxy: proxy2, url: https://cp.cloudflare.com/generate_204, alive: true, delay: 308 ms uid: {741b58a1-8c84-4670-b1a3-0e8b22cab4f2}"
time="2024-07-20T22:28:42.478523+08:00" level=debug msg="Finish A Health Checking {741b58a1-8c84-4670-b1a3-0e8b22cab4f2}"
time="2024-07-20T22:28:59.860365+08:00" level=debug msg="[Rule] use default rules"
time="2024-07-20T22:28:59.860571+08:00" level=debug msg="[DNS] resolve chatgpt.com from tls://1.0.0.1:853"
time="2024-07-20T22:28:59.860593+08:00" level=debug msg="[DNS] resolve chatgpt.com from tls://8.8.4.4:853"
time="2024-07-20T22:28:59.860595+08:00" level=debug msg="[DNS] resolve chatgpt.com from tls://1.0.0.1:853"
time="2024-07-20T22:28:59.860597+08:00" level=debug msg="[DNS] resolve chatgpt.com from tls://8.8.4.4:853"
time="2024-07-20T22:29:00.803695+08:00" level=debug msg="[DNS] chatgpt.com --> [104.18.30.2 104.18.31.2] A from tls://1.0.0.1:853"
time="2024-07-20T22:29:00.80372+08:00" level=debug msg="[DNS] chatgpt.com --> [2606:4700::6812:1e02 2606:4700::6812:1f02] AAAA from tls://8.8.4.4:853"
time="2024-07-20T22:29:00.803722+08:00" level=debug msg="[DNS] chatgpt.com --> [2606:4700::6812:1f02 2606:4700::6812:1e02] AAAA from tls://1.0.0.1:853"
time="2024-07-20T22:29:00.803756+08:00" level=debug msg="[DNS] chatgpt.com --> [104.18.31.2 104.18.30.2] A from tls://8.8.4.4:853"
time="2024-07-20T22:29:00.803976+08:00" level=debug msg="[DNS] chatgpt.com --> 104.18.30.2"
time="2024-07-20T22:29:01.100462+08:00" level=info msg="[TCP] 127.0.0.1:55773 --> chatgpt.com:443 match RuleSet(openai) using PROXY-FALLBACK[proxy1]"
time="2024-07-20T22:29:02.074175+08:00" level=debug msg="[Rule] use default rules"
time="2024-07-20T22:29:02.07547+08:00" level=debug msg="[DNS] resolve cdn.oaistatic.com from tls://1.0.0.1:853"
time="2024-07-20T22:29:02.076819+08:00" level=debug msg="[DNS] resolve cdn.oaistatic.com from tls://1.0.0.1:853"
time="2024-07-20T22:29:02.077425+08:00" level=debug msg="[DNS] resolve cdn.oaistatic.com from tls://8.8.4.4:853"
time="2024-07-20T22:29:02.079335+08:00" level=debug msg="[DNS] resolve cdn.oaistatic.com from tls://8.8.4.4:853"
time="2024-07-20T22:29:02.359575+08:00" level=info msg="Load ASN file: /usr/local/etc/mihomo/ASN.mmdb"
time="2024-07-20T22:29:02.921609+08:00" level=debug msg="[DNS] cdn.oaistatic.com --> [104.18.12.201 104.18.13.201] A from tls://1.0.0.1:853"
time="2024-07-20T22:29:02.933139+08:00" level=debug msg="[DNS] cdn.oaistatic.com --> [2606:4700::6812:dc9 2606:4700::6812:cc9] AAAA from tls://1.0.0.1:853"
time="2024-07-20T22:29:02.933388+08:00" level=debug msg="[DNS] cdn.oaistatic.com --> 104.18.13.201"
time="2024-07-20T22:29:03.260975+08:00" level=info msg="[TCP] 127.0.0.1:55785 --> cdn.oaistatic.com:443 match RuleSet(openai) using PROXY-FALLBACK[proxy1]"
time="2024-07-20T22:29:06.263634+08:00" level=debug msg="[Rule] use default rules"
time="2024-07-20T22:29:06.26393+08:00" level=debug msg="[DNS] resolve ab.chatgpt.com from tls://1.0.0.1:853"
time="2024-07-20T22:29:06.265501+08:00" level=debug msg="[DNS] resolve ab.chatgpt.com from tls://1.0.0.1:853"
time="2024-07-20T22:29:06.266455+08:00" level=debug msg="[DNS] resolve ab.chatgpt.com from tls://8.8.4.4:853"
time="2024-07-20T22:29:06.267542+08:00" level=debug msg="[DNS] resolve ab.chatgpt.com from tls://8.8.4.4:853"
time="2024-07-20T22:29:06.946566+08:00" level=debug msg="[DNS] ab.chatgpt.com --> [2606:4700::6812:1e02 2606:4700::6812:1f02] AAAA from tls://1.0.0.1:853"
time="2024-07-20T22:29:06.951631+08:00" level=debug msg="[DNS] ab.chatgpt.com --> [104.18.30.2 104.18.31.2] A from tls://1.0.0.1:853"
time="2024-07-20T22:29:06.951887+08:00" level=debug msg="[DNS] ab.chatgpt.com --> 104.18.30.2"
time="2024-07-20T22:29:07.247936+08:00" level=info msg="[TCP] 127.0.0.1:55793 --> ab.chatgpt.com:443 match RuleSet(openai) using PROXY-FALLBACK[proxy1]"
",
配置二log: "
time="2024-07-20T22:31:00.813715+08:00" level=info msg="Start initial configuration in progress"
time="2024-07-20T22:31:00.817485+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-07-20T22:31:00.817533+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-07-20T22:31:01.235342+08:00" level=info msg="Start initial GeoSite rule category-ads-all => REJECT-DROP, records: 719"
time="2024-07-20T22:31:01.645723+08:00" level=info msg="Start initial GeoSite rule cn => DIRECT, records: 90310"
time="2024-07-20T22:31:01.660043+08:00" level=info msg="Start initial GeoSite rule private => DIRECT, records: 142"
time="2024-07-20T22:31:01.695513+08:00" level=info msg="Start initial GeoIP rule private => DIRECT, records: 18"
time="2024-07-20T22:31:01.701791+08:00" level=info msg="Start initial GeoIP rule cn => DIRECT, records: 10791"
time="2024-07-20T22:31:01.704577+08:00" level=info msg="Initial configuration complete, total time: 890ms"
time="2024-07-20T22:31:01.708208+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2024-07-20T22:31:01.715101+08:00" level=info msg="Sniffer is closed"
time="2024-07-20T22:31:01.715168+08:00" level=info msg="Use tcp concurrent"
time="2024-07-20T22:31:02.156265+08:00" level=info msg="DNS server listening at: [::]:53"
time="2024-07-20T22:31:02.157208+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:1082"
time="2024-07-20T22:31:02.158013+08:00" level=info msg="Start initial provider openai"
time="2024-07-20T22:31:02.160437+08:00" level=info msg="Start initial Compatible provider default"
time="2024-07-20T22:31:02.160559+08:00" level=info msg="Start initial Compatible provider PROXY-FALLBACK"
time="2024-07-20T22:31:02.161364+08:00" level=info msg="[GEO] last update time 2024-07-20 21:41:43.416310118 +0800 CST"
time="2024-07-20T22:31:02.161514+08:00" level=debug msg="Start New Health Checking {ef2e1519-09ed-4cf5-8243-269a7eb87840}"
time="2024-07-20T22:31:02.161718+08:00" level=debug msg="Health Checking, proxy: proxy2, url: https://cp.cloudflare.com/generate_204, id: {ef2e1519-09ed-4cf5-8243-269a7eb87840}"
time="2024-07-20T22:31:02.161779+08:00" level=debug msg="Health Checking, proxy: proxy1, url: https://cp.cloudflare.com/generate_204, id: {ef2e1519-09ed-4cf5-8243-269a7eb87840}"
time="2024-07-20T22:31:03.684354+08:00" level=debug msg="Health Checked, proxy: proxy2, url: https://cp.cloudflare.com/generate_204, alive: true, delay: 408 ms uid: {ef2e1519-09ed-4cf5-8243-269a7eb87840}"
time="2024-07-20T22:31:03.684373+08:00" level=debug msg="Health Checked, proxy: proxy1, url: https://cp.cloudflare.com/generate_204, alive: true, delay: 381 ms uid: {ef2e1519-09ed-4cf5-8243-269a7eb87840}"
time="2024-07-20T22:31:03.684454+08:00" level=debug msg="Finish A Health Checking {ef2e1519-09ed-4cf5-8243-269a7eb87840}"
time="2024-07-20T22:31:22.468832+08:00" level=debug msg="[Rule] use default rules"
time="2024-07-20T22:31:22.833681+08:00" level=info msg="[TCP] 127.0.0.1:55876 --> chatgpt.com:443 match RuleSet(openai) using PROXY-FALLBACK[proxy1]"
time="2024-07-20T22:31:23.817835+08:00" level=debug msg="[Rule] use default rules"
time="2024-07-20T22:31:24.121557+08:00" level=info msg="[TCP] 127.0.0.1:55884 --> cdn.oaistatic.com:443 match RuleSet(openai) using PROXY-FALLBACK[proxy1]"
time="2024-07-20T22:31:27.331113+08:00" level=debug msg="[Rule] use default rules"
time="2024-07-20T22:31:27.627239+08:00" level=info msg="[TCP] 127.0.0.1:55888 --> ab.chatgpt.com:443 match RuleSet(openai) using PROXY-FALLBACK[proxy1]"
"
```
