### ISSUE TITLE
[Bug] proxy group 引用proxy provider后自动选择（URL-Test）不生效，默认选中第一个节点

### ISSUE THREAD

**Issue by sixrui** [MetaCubeX/mihomo#1402]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

Win11 23H2

### Mihomo Version

V1.18.6

### Configuration File

```yaml
proxy-providers:
 mojie:
   type: http
   path: ./profiles/mojie.yaml
   interval: 43200
   health-check:
     enable: false
     url: http://www.gstatic.com/generate_204
     interval: 900

proxy-groups:
- name: PROXY
  type: select
  proxies:
   - auto
  
- name: auto
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 600 # 自动测试间隔时间，单位秒
  tolerance: 50 # 允许的偏差，节点之间延迟差小于该值不切换 非必要
  use: # 引入proxy-provider 使用 use 关键字
   - mojie
```

### Description

proxy-group 的自动选择（URT-Test）未能生效，其默认选中了第一个节点，在设定的测试间隔interval后也不会测速，一直无测速信息。在此情况下，需手动点击测速操作，而后自动选择功能方可生效。

似乎只有引用Proxy-provider的proxy group才会这样。

### Reproduction Steps

客户端是Clash Verge
Proxy-group采用USE方法引用proxy-provider 提供的节点，类型为UR-Test
关闭软件后再打开软件，Proxy-group默认均选中第一个节点，不会进行自动测速切换，等待一段时间后也不会。
![image](https://github.com/user-attachments/assets/54821abc-7137-42d1-9aa9-f3ca572036f0)
