### ISSUE TITLE
[Bug] GeoSite规则未使用代理服务器的DNS

### ISSUE THREAD

**Issue by auqhjjqdo** [MetaCubeX/mihomo#1403]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

Windows 10 22H2

### Mihomo Version

v1.18.6

### Configuration File

```yaml
dns:
  enable: true
  listen: 0.0.0.0:5353
  ipv6: true
  prefer-h3: true
  enhanced-mode: fake-ip
  nameserver:
  - tls://223.5.5.5
  - tls://1.12.12.12
……
rules:
# - DOMAIN-SUFFIX,ipleak.net,PROXY
- GEOSITE,private,DIRECT
- GEOSITE,geolocation-!cn,PROXY
- GEOSITE,cn,DIRECT
- GEOIP,private,DIRECT,no-resolve
- GEOIP,cn,DIRECT,no-resolve
- MATCH,PROXY
```

### Description

在规则中将GEOSITE指定为`PROXY`规则，当访问的域名匹配到GEOSITE规则后，按照Clash的DNS解析流程，匹配到基于域名的规则时通过代理服务器解析域名并建立连接，GEOSITE理论上应该是属于`基于域名的规则`，但还是通过Clash DNS进行了解析，会导致DNS泄露。

### Reproduction Steps

例如在打开网站`https://ipleak.net/`时，匹配到规则`GeoSite(geolocation-!cn)`，属于`PROXY`规则应该走代理服务器的DNS解析，但实际上依旧在本地发起了DNS请求；
如果在规则里添加了`DOMAIN-SUFFIX,ipleak.net,PROXY`，再打开该网站时就直接走的代理服务器解析，此时该网站也并未检测到本地泄露的DNS

### Logs

```shell
使用GEOSITE匹配规则时：
time="2024-07-21T22:07:59.9865286+08:00" level=debug msg="[DNS] resolve ipleak.net from tls://1.12.12.12:853"
time="2024-07-21T22:07:59.9865286+08:00" level=debug msg="[DNS] resolve ipleak.net from tls://223.5.5.5:853"
time="2024-07-21T22:08:00.031541+08:00" level=debug msg="[DNS] ipleak.net --> [2a03:b0c0:0:1010::509:d001] AAAA from tls://223.5.5.5:853"
time="2024-07-21T22:08:00.0372301+08:00" level=debug msg="[DNS] ipleak.net --> [95.85.16.212] A from tls://223.5.5.5:853"
time="2024-07-21T22:08:00.0510354+08:00" level=info msg="[TCP] 127.0.0.1:39724(chrome.exe) --> ipleak.net:443 match GeoSite(geolocation-!cn) using PROXY"
time="2024-07-21T22:08:00.096206+08:00" level=debug msg="[Rule] use default rules"

使用DOMAIN-SUFFIX匹配规则时：
time="2024-07-21T22:12:37.2583056+08:00" level=info msg="[TCP] 127.0.0.1:41740(chrome.exe) --> ipv4.ipleak.net:443 match DomainSuffix(ipleak.net) using PROXY"
time="2024-07-21T22:12:37.9037931+08:00" level=debug msg="[Rule] use default rules"
```
