### ISSUE TITLE
[Bug] hosts写法不完善

### ISSUE THREAD

**Issue by yiteei** [MetaCubeX/mihomo#1416]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [X] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Windows

### 系统版本

win11

### Mihomo 版本

aIpha-c830b8a

### 配置文件

```yaml
#!MANAGED-CONFIG https://gist.githubusercontent.com/ / /raw/ 
#################### START ####################
mode: "rule" # 运行模式 rule/global/direct ,暂不支持 script
log-level: "debug" # 日志级别 silent/error/warning/info/debug
find-process-mode: "off" # 进程模式 off/strict/always
global-client-fingerprint: "chrome" # 全局客户端指纹,可选: chrome/firefox/safari/iOS/android/edge/360/qq/random ,优先低于 proxy 内的 client-fingerprint ,目前支持开启 TLS 传输的 TCP/grpc/WS/HTTP , 支持协议有 VLESS,Vmess 和 trojan
global-ua: "Mozilla" # 全局 UA ,默认 clash.meta

tproxy-port: 7890 # tproxy 透明代理端口,可代理 TCP 与 UDP 流量
mixed-port: 7891 # 混合端口 同时支持 HTTP(S) 和 SOCKS5 协议
ipv6: true # IPv6 是否允许内核接受 IPv6 流量
keep-alive-interval: 5 # TCP Keep Alive 间隔,单位为秒,控制 Clash 发出 TCP Keep Alive 包的间隔,减少移动设备耗电问题的临时措施
tcp-concurrent: true # TCP 并发 如果域名解析结果对应多个IP,并发请求所有IP,选择握手最快的IP进行通讯
unified-delay: true # 统一延迟 true/false
allow-lan: true # 允许其他设备经过 Clash 的代理端口访问互联网
bind-address: "*" # 绑定地址，仅允许其他设备通过这个地址访问
authentication: # 用户验证 http(s)/socks/mixed 代理的用户验证
  - "clash:clash" # 用户:密码
skip-auth-prefixes: # 跳过验证的IP段
  - "127.0.0.1/8"
  - "::1/128"

geodata-mode: false # GEOIP 数据模式,更改 geoip 使用文件为 mmdb 或者 dat , true 为 dat
geosite-matcher: "succinct" # GeoSite 匹配器使用的实现 succinct (default, same as rule-set)/mph (from V2Ray, also `hybrid` in Xray)
geodata-loader: "standard" # GEO 文件加载模式 standard/memconservative
geo-auto-update: false # 自动更新 GEO 是否启用,可选 true/false
geo-update-interval: 24 # 更新间隔,单位 h
geox-url: # 自定 GEO 下载地址
  Mmdb: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  ASN: "https://cdn.jsdelivr.net/gh/xishang0128/geoip@release/GeoLite2-ASN.mmdb"
  GeoIp: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  GeoSite: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"

profile: # 缓存
  store-selected: true # 储存 API 对策略组的选择,以供下次启动时使用

external-ui: "./ui" # 外部用户界面的路径
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip" # 自定义外部用户界面下载地址

external-controller: "0.0.0.0:9090" # API 监听地址
secret: "clash" # API 的访问密钥

#################### 域名嗅探 ####################
sniffer:
  enable: true # 是否启用,可选 true/false
  force-dns-mapping: true # 对 redir-host 类型识别的流量进行强制嗅探
  parse-pure-ip: true # 对所有未获取到域名的流量进行强制嗅探
  override-destination: true # 是否使用嗅探结果作为实际访问,默认为 true
  sniff: # TLS 和 QUIC 默认如果不配置 ports 默认嗅探 443
    HTTP: # 默认嗅探 80
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain: # 需要跳过嗅探的域名,主要解决部分站点sni字段非域名,导致嗅探结果异常的问题,如米家设备
    - "+.apple.com"
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.jd.com"
    - "+.taobao.com"
    - "+.tmall.com"
    - "*.rc.sunlogin.net"

#################### 入站 ####################
tun:
  enable: true # 是否启用,可选 true/false
  stack: "mixed" # tun 模式堆栈 system/gvisor/mixed
  device: "Clash" # 指定 tun 网卡名称, MacOS 设备只能使用 utun 开头的网卡名
  auto-route: true # 自动设置全局路由,可以自动将全局流量路由进入 tun 网卡
  auto-redirect: false # 自动配置 iptables/nftables 以重定向 TCP 连接，需要auto-route已启用
  auto-detect-interface: true # 自动选择流量出口接口,多出口网卡同时连接的设备建议手动指定出口网卡
  dns-hijack: # 需要劫持的 DNS 端口
    - "any:53"
    - "tcp://any:53"
  strict-route: false # true/false 严格路由,所有连接路由到 tun 来防止泄漏,但设备将无法被其他设备访问
  udp-timeout: 180 # UDP NAT 过期时间，以秒为单位，默认为 300(5 分钟)
  endpoint-independent-nat: false # 启用独立于端点的 NAT，性能可能会略有下降，所以不建议在不需要的时候开启
  route-address: # 启用 auto-route 时使用自定义路由而不是默认路由
    - "0.0.0.0/1"
    - "128.0.0.0/1"
    - "::/1"
    - "8000::/1"
  route-exclude-address: # 启用 auto-route 时排除自定义网段
    - "192.168.0.0/16"
    - "fc00::/7"

#################### DNS ####################
hosts:
  cloudflare-dns.com: ["[2606:4700:4700::6464]", "[2606:4700:4700::64]", "[2606:4700:4700::1001]", "[2606:4700:4700::1111]", "1.0.0.1", "1.1.1.1"]
  dns.google: ["[2001:4860:4860::6464]", "[2001:4860:4860::64]", "[2001:4860:4860::8844]", "[2001:4860:4860::8888]", "8.8.4.4", "8.8.8.8"]
  dns.alidns.com: ["[2400:3200:baba::1]", "[2400:3200::1]", "223.6.6.6", "223.5.5.5"]
  doh.pub: ["120.53.53.53", "1.12.12.12"]
dns:
  enable: true # 关闭将使用系统 DNS
  listen: "0.0.0.0:1053" # 开启 DNS 服务器监听
  ipv6: true # false 将返回 AAAA 的空结果
  ipv6-timeout: 300 # 单位：ms，内部双栈并发时，向上游查询 AAAA 时，等待 AAAA 的时间，默认 100ms
  prefer-h3: false # 开启 DoH 支持 HTTP/3 ,将并发尝试
  use-hosts: true # 是否查询配置中的 hosts,默认 true
  use-system-hosts: false # 是否查询系统 hosts，默认 true
  respect-rules: true # dns 连接跟随 rules，需配置 proxy-server-nameserver
  default-nameserver:
    - "223.6.6.6"
    - "119.29.29.29"
    - "1.0.0.1"
    - "8.8.4.4"
  enhanced-mode: "redir-host" # DNS 处理模式 normal/redir-host/fake-ip
  nameserver: # 默认域名解析,如不配置 fallback/proxy-server-nameserver ,则都由 nameserver 解析
    - "https://cloudflare-dns.com/dns-query" # Cloudflare DNS
    - "https://dns.google/dns-query" # Google DNS
  proxy-server-nameserver: # 专用于节点域名解析的 DNS 服务器，非必要配置项
    - "https://dns.alidns.com/dns-query" # Alibaba DNS
    - "https://doh.pub/dns-query" # DNSPod DNS
  nameserver-policy: # 指定的解析服务,没匹配到时使用 nameserver/fallback 并发查询
    "geosite:private,cn":
      - "https://dns.alidns.com/dns-query" # Alibaba DNS
      - "https://doh.pub/dns-query" # DNSPod DNS

#################### NTP ####################
ntp:
  enable: false # 是否启用 NTP 服务 true/false
  write-to-system: true # 是否同步至系统时间,需要 root、管理员模式运行
  server: "ntp.ntsc.ac.cn" # NTP 服务地址
  port: "123" # NTP 服务端口,默认 123
  interval: 1440 # 同步时间间隔,单位 min ,默认 30 min

#################### 出站代理 ####################
proxies:
  - {name: "⚫ DNS劫持", type: dns} # dns 出站会将请求劫持到内部 dns 模块，所有请求均在内部处理

#################### 代理集合 ####################
proxy-providers-anchor:
  - proxy_providers_header: &proxy_providers_header
      User-Agent:
        - "clash.meta"
        - "meta"
        - "mihomo"
        - "verge"
        - "stash"
        - "flclash"
        - "clash"
  - proxy_providers_health_check: &proxy_providers_health_check
      url: "https://ipv6.google.com/generate_204" # 使⽤ https ,防⽌⽆良⽼板伪造延迟! https://www.gstatic.com/generate_204 https://cp.cloudflare.com
      interval: "180" # 测试间隔,如不为 0 则启用定时测试,单位 s
      timeout: "3000" # 健康检查超时时间,单位为 ms
      expected-status: "204" # 期望状态,只有当响应状态码与期望状态一致时才认为节点可用
  - proxy_providers_override: &proxy_providers_override
      skip-cert-verify: false # 跳过证书验证,仅适用于使用 tls 的协议
      ip-version: "ipv6-prefer" # 设置节点使用 IP 版本,默认使用 dual ; dual/ipv4/ipv6/ipv4-prefer/ipv6-prefer

proxy-providers:
  "Subscription_1": # 自动爬取订阅 #订阅名称
    type: http # 必须, provider 类型,可选 http/file
    url: "https://"
    path: "./proxy_providers/Subscription_1.yaml" # 机场配置保存位置
    interval: 86400 # 更新provider的时间,单位为秒
    header:
      <<: *proxy_providers_header # 引用相关锚点
    exclude-type: "hysteria|hysteria2|ss|ssr|trojan" # 不支持正则表达式，通过 | 分割，根据节点类型排除
    exclude-filter: "(?i)(?:通知|公告|官网|地址|域名|邀|佣|com|tg|前往|加入|群|频道|流量|剩|期|续)" # 过滤..
    filter: "(?i)(?:🇭🇰|港|Hong Kong|Hongkong)" # 筛选满足关键词或正则表达式的节点，可以使用 ` 区分多个正则表达式
    health-check: # 延迟测试
      enable: true # 是否启用,可选 true/false
      <<: *proxy_providers_health_check
    override: # 覆写节点内容
      <<: *proxy_providers_override
      additional-suffix: "@🔖 aggregator" # 为节点名称添加固定前缀
  "Subscription_2": # CM优选订阅
    type: http
    url: "https://"
    path: "./proxy_providers/Subscription_2.yaml"
    interval: 86400
    header:
      <<: *proxy_providers_header
    exclude-filter: "(?i)(?:通知|公告|官网|地址|域名|邀|佣|com|tg|前往|加入|群|频道|流量|剩|期|续)"
    health-check:
      enable: true
      <<: *proxy_providers_health_check
    override:
      <<: *proxy_providers_override
      additional-suffix: "@🔖 CMLiussss"
  "Subscription_3": # Free Cloud aff: https://intel.im/#/register?code=YDEx84ta
    type: http
    url: "https://"
    path: "./proxy_providers/Subscription_3.yaml"
    interval: 86400
    header:
      <<: *proxy_providers_header
    exclude-filter: "(?i)(?:通知|公告|官网|地址|域名|邀|佣|com|tg|前往|加入|群|频道|流量|剩|期|续)"
    health-check:
      enable: true
      <<: *proxy_providers_health_check
    override:
      <<: *proxy_providers_override
      additional-suffix: "@🔖 Free Cloud"
  "Subscription_4": # 小鸡快跑 aff: v2.xiaojikp.cc/#/register?invitecode=z1RKg6KW
    type: http
    url: "https://"
    path: "./proxy_providers/Subscription_4.yaml"
    interval: 86400
    header:
      <<: *proxy_providers_header
    exclude-filter: "(?i)(?:通知|公告|官网|地址|域名|邀|佣|com|tg|前往|加入|群|频道|流量|剩|期|续)"
    health-check:
      enable: true
      <<: *proxy_providers_health_check
    override:
      <<: *proxy_providers_override
      additional-suffix: "@🔖 Chicken Run"

#################### 策略组 ####################
proxy-groups-anchor:
  - proxy_groups_health_check: &proxy_groups_health_check {url: "https://ipv6.google.com/generate_204", interval: "180", timeout: "3000", expected-status: "204", max-failed-times: 1}
  - proxy_groups_proxy: &proxy_groups_proxy {type: select, proxies: [🧭 全局模式, 🌐 全球直连]}
  - proxy_groups_direct: &proxy_groups_direct {type: select, proxies: [🌐 全球直连, 🧭 全局模式]}

proxy-groups:
  - {name: "🧭 全局模式", <<: *proxy_groups_health_check, type: select, proxies: [🗺 代理连接, 🌐 全球直连]}
  - {name: "🗺 代理连接", <<: *proxy_groups_health_check, type: select, proxies: [🌸 自动切换, 📉 故障排除, 📊 负载均衡, 🧬 链式代理, 🔖 aggregator, 🔖 CMLiussss, 🔖 Free Cloud, 🔖 Chicken Run]}
  - {name: "🌸 自动切换", <<: *proxy_groups_health_check, type: url-test, tolerance: 5, include-all-providers: true, exclude-filter: "(?:CN|CH|中国|国内)", hidden: true}
  - {name: "📉 故障排除", <<: *proxy_groups_health_check, type: fallback, include-all-providers: true, hidden: true}
  - {name: "📊 负载均衡", <<: *proxy_groups_health_check, type: load-balance, use: [Subscription_3, Subscription_4], strategy: consistent-hashing, hidden: true}
  - {name: "🧬 链式代理", <<: *proxy_groups_health_check, type: relay, proxies: [REJECT-DROP], hidden: true}
  - {name: "💬 谷歌推送", <<: *proxy_groups_health_check, type: select, proxies: [🌐 全球直连, 📉 故障排除]}
  - {name: "🎞 奈飞影视", <<: *proxy_groups_proxy}
  - {name: "🧲 种子下载", <<: *proxy_groups_health_check, type: url-test, tolerance: 5, include-all-providers: true, filter: "(?i)(?:BT|PT|卢森堡)"}
  - {name: "👁 🄼🅈🄸🄿", <<: *proxy_groups_health_check, type: select, proxies: [PASS, REJECT-DROP]}
  - {name: "🇶 🅀🅄🄸🄲", <<: *proxy_groups_health_check, type: select, proxies: [PASS, REJECT-DROP]}
  - {name: "🌐 全球直连", <<: *proxy_groups_health_check, type: select, proxies: [DIRECT], include-all-providers: true, filter: "(?:CN|CH|中国|国内)"}
  - {name: "🔖 aggregator", <<: *proxy_groups_health_check, type: load-balance, use: [Subscription_1], strategy: consistent-hashing, hidden: true}
  - {name: "🔖 CMLiussss", <<: *proxy_groups_health_check, type: url-test, use: [Subscription_2], tolerance: 5, hidden: true}
  - {name: "🔖 Free Cloud", <<: *proxy_groups_health_check, type: url-test, use: [Subscription_3], tolerance: 5, hidden: true}
  - {name: "🔖 Chicken Run", <<: *proxy_groups_health_check, type: url-test, use: [Subscription_4], tolerance: 5, hidden: true}
  # - {name: "🇺🇸 美国节点", <<: *proxy_groups_health_check, type: load-balance, include-all-providers: true, filter: "(?i)(?:🇺🇸|🇺🇲|美|United States|UnitedStates|America)", hidden: true}
  # - {name: "🇯🇵 日本节点", <<: *proxy_groups_health_check, type: load-balance, include-all-providers: true, filter: "(?i)(?:🇯🇵|日|东京|Japan|Nippon|Nihon)", hidden: true}
  # - {name: "🇸🇬 狮城节点", <<: *proxy_groups_health_check, type: load-balance, include-all-providers: true, filter: "(?i)(?:🇸🇬|新加坡|狮城|Singapore|Singapura)", hidden: true}
  # - {name: "🇭🇰 香港节点", <<: *proxy_groups_health_check, type: load-balance, include-all-providers: true, filter: "(?i)(?:🇭🇰|港|Hong Kong|HongKong)", hidden: true}
  # - {name: "🇺🇳 其他节点", <<: *proxy_groups_health_check, type: select, include-all-providers: true, filter: "(?i)^(?!.*(?:🇺🇸|🇺🇲|美|United States|UnitedStates|America|🇯🇵|日|Japan|Nippon|Nihon|🇸🇬|新加坡|狮城|Singapore|Singapura|🇭🇰|港|Hong Kong|Hongkong)).*"}

#################### 规则集合 ####################
rule-providers-anchor:
  rule_domain: &rule_domain {type: http, behavior: domain, format: yaml, interval: 86400}
  rule_ipcidr: &rule_ipcidr {type: http, behavior: ipcidr, format: yaml, interval: 86400}
  rule_classical: &rule_classical {type: http, behavior: classical, format: yaml, interval: 86400}

rule-providers:
  AdGuard_DNS_filter: # AdGuard DNS filter
    <<: *rule_classical
    path: "./rule_providers/AdGuard_DNS_filter"
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AdGuardSDNSFilter/AdGuardSDNSFilter_Classical.yaml"

#################### 子规则 ####################
sub-rules: null

#################### 规则 ####################
rules:
  - "DST-PORT,53,⚫ DNS劫持" # 劫持 DNS
  - "RULE-SET,AdGuard_DNS_filter,REJECT-DROP" # 广告
  - "AND,((NETWORK,udp),(DST-PORT,443),(OR,(GEOSITE,!cn),(GEOIP,!cn))),🇶 🅀🅄🄸🄲" # 国内以外的 QUIC
  - "OR,((DOMAIN-KEYWORD,stun),(DOMAIN-KEYWORD,turn)),👁 🄼🅈🄸🄿" # WebRTC 连接 STUN/TURN 服务器获取 IP 地址
  - "OR,((GEOSITE,category-httpdns),(DOMAIN-KEYWORD,httpdns)),REJECT-DROP" # 屏蔽 httpdns ,可解决某些页面加载不出来
  - "OR,((GEOSITE,private),(GEOIP,private)),🌐 全球直连"
  - "OR,((GEOSITE,googlefcm),(DST-PORT,5228-5230)),💬 谷歌推送"
  - "OR,((GEOSITE,category-pt),(GEOSITE,category-public-tracker)),🧲 种子下载"
  - "OR,((GEOSITE,netflix),(GEOIP,netflix)),🎞 奈飞影视"
  - "OR,((GEOSITE,cloudflare),(GEOIP,cloudflare)),🧭 全局模式"
  - "OR,((GEOSITE,google),(GEOIP,google)),🧭 全局模式"
  - "OR,((GEOSITE,cn),(GEOIP,cn)),🌐 全球直连"
  - "MATCH,🧭 全局模式"

#################### END ####################
```

### 描述

我尝试了hosts多行写法与单行仍然报错
![2024-07-29-124352-chrome](https://github.com/user-attachments/assets/e22ab4fd-9686-48fa-ae9c-f9bddc542534)

### 重现方式

单行写法与多行写法配置文件分别测试 有一次核心直接死了 测试客户端Clash Nyanpasu
