### ISSUE TITLE
[Bug] provider 中设定的 HTTP header 不生效

### ISSUE THREAD

**Issue by ayasechan** [MetaCubeX/mihomo#1420]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Linux

### 系统版本

docker

### Mihomo 版本

Clash Meta v1.16.0 linux amd64 with go1.21.1 Mon Sep 25 11:39:25 UTC 2023
Use tags: with_gvisor

### 配置文件

```yaml
provider-default: &provider-default
  type: http
  interval: 3600
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 300
    timeout: 3000

proxy-providers:
  fooo:
    <<: *provider-default
    # nc address
    url: 'http://127.0.0.1:8080'
    header:
      Foo: ["hello"]

rules:
  - MATCH,DIRECT
```

### 描述

如题

### 重现方式

执行 nc -lp8080 后启动 clash 
没有在请求里面看到预设的请求头

nc 输出
```
GET / HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: clash.meta
Accept-Encoding: gzip

```
