### ISSUE TITLE
[Bug] 负载均衡s5崩溃的问题

### ISSUE THREAD

**Issue by svchostmm** [MetaCubeX/mihomo#1421]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

5.4.0-182-generic #202-Ubuntu 

### Mihomo Version

mihomo-v1.18.6 -go

### Configuration File

```yaml
# 基本设置
port: 7323  # HTTP 代理端口
socks-port: 7890 # SOCKS5 代理端口
allow-lan: true  # 允许局域网访问
mode: Rule  # 代理模式，Rule 模式根据规则路由流量
log-level: info  # 日志级别
external-controller: :9090  # 外部控制器端口


proxy-providers:
  provider_0:
    type: http
    url: url
    interval: 86400
    path: ./Proxy/provider_0.yaml
    health-check:
      enable: true
      interval: 30
      timeout: 5000
      lazy: false
      url: https://www.gstatic.com/generate_204
  provider_1:
    type: http
    url: url
    interval: 86400
    path: ./Proxy/provider_1.yaml
    health-check:
      enable: true
      interval: 30
      timeout: 5000
      lazy: false
      url: https://www.gstatic.com/generate_204
  provider_2:
    type: http
    url: url
    interval: 86400
    path: ./Proxy/provider_2.yaml
    health-check:
      enable: true
      interval: 30
      timeout: 5000
      lazy: false
      url: https://www.gstatic.com/generate_204
  provider_3:
    type: http
    url: url
    interval: 86400
    path: ./Proxy/provider_3.yaml
    health-check:
      enable: true
      interval: 30
      timeout: 5000
      lazy: false
      url: https://www.gstatic.com/generate_204

proxy-groups:
- name: "负载均衡-散列"
  type: load-balance
  strategy: round-robin
  url: http://www.google.com/generate_204
  interval: 300
  use:
  - provider_0
  - provider_1
  - provider_2


rules:
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - MATCH,负载均衡-散列
```

### Description

作为代理池使用，使用负载均衡模式，一般运行24小时候之后就会出现这个错误，代理的请求并发量在1000左右，

### Reproduction Steps

一般运行24小时候之后就会出现这个错误，代理的请求并发量在1000左右，持续的高并发

### Logs

```shell
github.com/metacubex/mihomo/tunnel/tunnel.go:66 +0x47 fp=0x43a70f2c sp=0x43a70f18 pc=0x87513b7
github.com/metacubex/mihomo/tunnel.(*tunnel).HandleTCPConn(0xa176638, {0x93aaa20, 0x66b6c810}, 0x413548f0)
        <autogenerated>:1 +0x40 fp=0x43a70f3c sp=0x43a70f2c pc=0x8756d40
github.com/metacubex/mihomo/listener/socks.HandleSocks5({0x93aaa20, 0x66b6c810}, {0x93a53a4, 0xa176638}, {0xc37e358, 0x2, 0x2})
        github.com/metacubex/mihomo/listener/socks/tcp.go:126 +0x1f4 fp=0x43a70fac sp=0x43a70f3c pc=0x8dc7df4
github.com/metacubex/mihomo/listener/socks.handleSocks({0x93ac910, 0xe30929a8}, {0x93a53a4, 0xa176638}, {0xc37e358, 0x2, 0x2})
        github.com/metacubex/mihomo/listener/socks/tcp.go:90 +0xc7 fp=0x43a70fd0 sp=0x43a70fac pc=0x8dc78f7
github.com/metacubex/mihomo/listener/socks.New.func1.1()
        github.com/metacubex/mihomo/listener/socks/tcp.go:70 +0x51 fp=0x43a70ff0 sp=0x43a70fd0 pc=0x8dc7781
runtime.goexit()
        runtime/asm_386.s:1326 +0x1 fp=0x43a70ff4 sp=0x43a70ff0 pc=0x80b60a1
created by github.com/metacubex/mihomo/listener/socks.New.func1
        github.com/metacubex/mihomo/listener/socks/tcp.go:70 +0x17f

goroutine 703042590 [chan receive, 4 minutes]:
runtime.gopark(0x9202fb4, 0x6f1be7b0, 0xe, 0x17, 0x2)
        runtime/proc.go:381 +0x108 fp=0x71913f14 sp=0x71913f00 pc=0x8083de8
runtime.chanrecv(0x6f1be780, 0x0, 0x1)
        runtime/chan.go:583 +0x3f4 fp=0x71913f5c sp=0x71913f14 pc=0x804dc64
runtime.chanrecv1(0x6f1be780, 0x0)
        runtime/chan.go:442 +0x1c fp=0x71913f70 sp=0x71913f5c pc=0x804d83c
github.com/metacubex/mihomo/common/batch.(*Batch[...]).Go.func1()
        github.com/metacubex/mihomo/common/batch/batch.go:46 +0xa3 fp=0x71913ff0 sp=0x71913f70 pc=0x8e219c3
runtime.goexit()
        runtime/asm_386.s:1326 +0x1 fp=0x71913ff4 sp=0x71913ff0 pc=0x80b60a1
created by github.com/metacubex/mihomo/common/batch.(*Batch[...]).Go
        github.com/metacubex/mihomo/common/batch/batch.go:43 +0xc7

goroutine 703140364 [running]:
runtime.throw({0x918aa7b, 0xd})
        runtime/panic.go:1047 +0x4d fp=0x428918e8 sp=0x428918d4 pc=0x8080bed
runtime.(*mcache).allocLarge(0xf7f67f00, 0x1c000, 0x0)
        runtime/mcache.go:236 +0x1be fp=0x42891910 sp=0x428918e8 pc=0x805c6ee
runtime.mallocgc(0x1c000, 0x9104820, 0x1)
        runtime/malloc.go:1053 +0x3fd fp=0x42891948 sp=0x42891910 pc=0x8053fbd
runtime.growslice(0xffbcc000, 0x2c0a, 0x2c00, 0x14, 0x9104820)
        runtime/slice.go:274 +0x428 fp=0x42891974 sp=0x42891948 pc=0x80999a8
github.com/metacubex/mihomo/adapter/outboundgroup.(*GroupBase).GetProxies(0xc40c540, 0x0)
        github.com/metacubex/mihomo/adapter/outboundgroup/groupbase.go:103 +0xfb1 fp=0x42891b88 sp=0x42891974 pc=0x8d43971
github.com/metacubex/mihomo/adapter/outboundgroup.(*LoadBalance).Unwrap(0xc34b500, 0xd2eae750, 0x0)
        github.com/metacubex/mihomo/adapter/outboundgroup/loadbalance.go:226 +0x2c fp=0x42891ba8 sp=0x42891b88 pc=0x8d45abc
github.com/metacubex/mihomo/adapter.(*Proxy).Unwrap(0xc133c80, 0xd2eae750, 0x0)
        <autogenerated>:1 +0x3e fp=0x42891bc0 sp=0x42891ba8 pc=0x8d1684e
github.com/metacubex/mihomo/tunnel.match(0xd2eae750)
        github.com/metacubex/mihomo/tunnel/tunnel.go:645 +0x7ad fp=0x42891cb8 sp=0x42891bc0 pc=0x8755e1d
github.com/metacubex/mihomo/tunnel.resolveMetadata(0xd2eae750)
        github.com/metacubex/mihomo/tunnel/tunnel.go:316 +0x85 fp=0x42891ce8 sp=0x42891cb8 pc=0x87520a5
github.com/metacubex/mihomo/tunnel.handleTCPConn({0x93a479c, 0xe74fe120})
        github.com/metacubex/mihomo/tunnel/tunnel.go:482 +0x2e4 fp=0x42891f18 sp=0x42891ce8 pc=0x87536c4
github.com/metacubex/mihomo/tunnel.tunnel.HandleTCPConn({}, {0x93aaa20, 0xe6fc83c0}, 0xd2eae750)
        github.com/metacubex/mihomo/tunnel/tunnel.go:66 +0x47 fp=0x42891f2c sp=0x42891f18 pc=0x87513b7
github.com/metacubex/mihomo/tunnel.(*tunnel).HandleTCPConn(0xa176638, {0x93aaa20, 0xe6fc83c0}, 0xd2eae750)
        <autogenerated>:1 +0x40 fp=0x42891f3c sp=0x42891f2c pc=0x8756d40
github.com/metacubex/mihomo/listener/socks.HandleSocks5({0x93aaa20, 0xe6fc83c0}, {0x93a53a4, 0xa176638}, {0xc37e358, 0x2, 0x2})
        github.com/metacubex/mihomo/listener/socks/tcp.go:126 +0x1f4 fp=0x42891fac sp=0x42891f3c pc=0x8dc7df4
github.com/metacubex/mihomo/listener/socks.handleSocks({0x93ac910, 0x718e40c0}, {0x93a53a4, 0xa176638}, {0xc37e358, 0x2, 0x2})
        github.com/metacubex/mihomo/listener/socks/tcp.go:90 +0xc7 fp=0x42891fd0 sp=0x42891fac pc=0x8dc78f7
github.com/metacubex/mihomo/listener/socks.New.func1.1()
        github.com/metacubex/mihomo/listener/socks/tcp.go:70 +0x51 fp=0x42891ff0 sp=0x42891fd0 pc=0x8dc7781
runtime.goexit()
        runtime/asm_386.s:1326 +0x1 fp=0x42891ff4 sp=0x42891ff0 pc=0x80b60a1
created by github.com/metacubex/mihomo/listener/socks.New.func1
        github.com/metacubex/mihomo/listener/socks/tcp.go:70 +0x17f
```
