### ISSUE TITLE
[Bug] 关闭IPV6的情况下，有部分网站依然被分配IPV6地址并可绕过clash直接访问网络

### ISSUE THREAD

**Issue by qdsp6sw** [MetaCubeX/mihomo#1426]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [X] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Windows

### 系统版本

Windows 11 22631.3880

### Mihomo 版本

Mihomo Meta v1.18.6 windows amd64 with go1.22.4 Mon Jul  1 15:03:47 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
mode: global
allow-lan: false
log-level: silent
ipv6: false
find-process-mode: strict
enable-process: true
profile:
  store-selected: true
tcp-concurrent: true
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb
dns:
  enable: true
  prefer-h3: false
  listen: :1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.16.0.1/16
  fake-ip-filter:
  - '*'
  - +.lan
  - +.local
  nameserver:
  - 8.8.8.8
  - 8.8.4.4
  proxy-server-nameserver:
  - 8.8.8.8
  nameserver-policy:
    geosite:cn: 114.114.114.114
  use-system-hosts: false
  fallback: []
tun:
  enable: true
  stack: system
  dns-hijack:
  - any:53
  auto-detect-interface: true
  auto-route: true
  auto-redirect: true
  strict-route: false
  device: Meta
  mtu: 1500
proxies:
- name: ***
  type: vless
  server: ***
  port: ***
  uuid: ***
  network: ws
proxy-groups:
- name: Proxy
  type: select
  proxies:
  - ***
rules:
- NOT,((OR,(PROCESS-NAME,java.exe),(PROCESS-NAME,vmnat.exe),(PROCESS-NAME,vmware-vmx.exe),(PROCESS-NAME,git-remote-https.exe),(PROCESS-NAME,Microsoft.Media.Player.exe),(PROCESS-NAME,git.exe)(PROCESS-NAME,WinSCP.exe),(PROCESS-NAME,git.exe),(PROCESS-NAME,git-remote-https.exe),(PROCESS-NAME,AnyDesk.exe),(PROCESS-NAME,smartscreen.exe),(PROCESS-NAME,chrome.exe),(PROCESS-NAME,svchost.exe),(PROCESS-NAME,Fusion360.exe),(PROCESS-NAME,Telegram.exe),(PROCESS-NAME,ssh.exe))),DIRECT
- Match,Proxy
```

### 描述

使用tun模式，对于所有cloud flare代理的网站，无论如何设置关闭ipv6，依然会返回ipv6的地址。
使用ping -4 cloudflare.net正常返回fake-ip v4地址
使用ping cloudflare.net返回ipv6地址

### 重现方式

1.开启全局模式
2.关闭ipv6，配置中阻止dns解析出v6地址
3.ping cloudflare.net

依然返回v6地址，且此地址不走mihomo core

### 日志

```shell
全局模式下，无日志，访问cloudflare.net时mihomo core无任何输出，但该网站已经直连到了解析出的ipv6地址
```
