### ISSUE TITLE
[技术咨询] Mihomo 监听 shadowsocks 端口同时在另一台主机使用 Mihomo 作为客户端访问时不通

### ISSUE THREAD

**Issue by xiaoQQya** [MetaCubeX/mihomo#1437]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Linux

### 系统版本

Arch Linux x86_64

### Mihomo 版本

Mihomo Meta v1.18.7 linux amd64 with go1.22.5 Sun Jul 28 05:46:59 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
# 服务端配置，系统为 CentOS 7.9，使用 docker 部署 Mihomo，服务端地址为 10.128.0.109
mode: direct
allow-lan: true
bind-address: "*"
log-level: debug

listeners:
  - name: ss
    type: shadowsocks
    listen: 0.0.0.0
    port: 1081
    cipher: 2022-blake3-aes-256-gcm
    password: CIBbWDuyhKRWV741FmQtYcjYkYEiMIx4A/Hew74wg2U=
    udp: true


# 客户端配置，客户端地址为 10.128.0.110
# clash
mixed-port: 7890
mode: rule
log-level: debug
allow-lan: true
bind-address: "*"

external-controller: 0.0.0.0:9090

proxies:
  - name: test
    type: ss
    server: 10.128.0.109
    port: 1081
    cipher: 2022-blake3-aes-256-gcm
    password: CIBbWDuyhKRWV741FmQtYcjYkYEiMIx4A/Hew74wg2U=
    udp: true

proxy-groups:
  - name: "proxy"
    type: select
    include-all: true
```

### 描述

在 CentOS 服务器上使用 Mihomo 作为服务端监听了 shadowsocks 端口。
分别在 Arch Linux 和 Windows 11 上使用 Mihomo 作为客户端去访问服务端的 shadowsocks 端口，Windows 11 可以正常连通，Arch Linux 访问不通，测试了两台 Windows 11 和两台 Arch Linux 结果均如上所述。
可以确保客户端与服务端之间网络是通的，通过 telnet 与 nc 进行测试得出。

### 重现方式

1. 在 CentOS 上使用上述提供的服务端配置监听 shadowsocks 端口；
2. 在 Arch Linux 上使用上述提供的客户端配置启动客户端；
3. 通过 https://metacubex.github.io/metacubexd/#/proxies 页面测试 test 节点，节点访问不通；

### 日志

```shell
# debug level 下点节点测试时无任何日志输出
```
