### ISSUE TITLE
[Bug] docker部署到威联通无法正常代理

### ISSUE THREAD

**Issue by MrZhaobh** [MetaCubeX/mihomo#1455]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### System Version

威联通 

### Mihomo Version

./mihomo -v
Mihomo Meta alpha-0793998 linux amd64 with go1.23.0 Fri Aug 16 06:16:48 UTC 2024
Use tags: with_gvisor

### Configuration File

```yaml
订阅文件使用了 懒人配置：
https://gist.github.com/liuran001/5ca84f7def53c70b554d3f765ff86a33
只是把机场地址换成我自己的
```

### Description

同样的配置在 windows下使用 mihomo-windows-amd64.exe 可以正常代理使用
但是部署到docker后 无法正常代理
使用了 终端命令测试：curl -x http://127.0.0.1:7890 http://google.com

### Reproduction Steps

```

services:
  meta:
    container_name: meta
    image: docker.io/metacubex/mihomo:Alpha
    restart: always
    pid: host
    ipc: host
    network_mode: host
    cap_add:
      - ALL
    volumes:
      - /share/CACHEDEV1_DATA/Container/clash2/:/root/.config/mihomo/
      - /dev/net/tun:/dev/net/tun

```
使用以上配置 部署docker 到威联通

### Logs

```shell
以下是日志


time="2024-08-17T05:09:50.25154239Z" level=info msg="Start initial configuration in progress"

time="2024-08-17T05:09:50.251699988Z" level=error msg="PrepareUIPath error: ExternalUI configure incomplete"

time="2024-08-17T05:09:50.25180345Z" level=info msg="Geodata Loader mode: memconservative"

time="2024-08-17T05:09:50.25188908Z" level=info msg="Geosite Matcher implementation: succinct"

time="2024-08-17T05:09:50.253339592Z" level=info msg="Initial configuration complete, total time: 1ms"

time="2024-08-17T05:09:50.286918085Z" level=info msg="Sniffer is closed"

time="2024-08-17T05:09:50.287277441Z" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"

time="2024-08-17T05:09:50.288977968Z" level=info msg="Start initial Compatible provider default"

time="2024-08-17T05:10:12.695654855Z" level=warning msg="[TCP] dial DIRECT 127.0.0.1:42654 --> google.com:80 error: connect failed: dial tcp 142.251.43.14:80: i/o timeout\nconnect failed: dial tcp [2404:6800:4012:3::200e]:80: connect: network is unreachable"
```
```
