### ISSUE TITLE
[Bug] 逻辑规则 NOT 不能包含 OR，括号使用正确

### ISSUE THREAD

**Issue by yiteei** [MetaCubeX/mihomo#1460]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [X] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Windows

### 系统版本

Windows 11 专业工作站版 24H2 26100.1457

### Mihomo 版本

1.18.7

### 配置文件

```yaml
proxy-groups:
  - {name: 'QUIC', type: select, proxies: [PASS, REJECT-DROP], icon: 'https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png'}

rules:
  - 'AND,((NETWORK,udp),(DST-PORT,443),(NOT,(OR,(RULE-SET,site_cn),(RULE-SET,ip_cn)))),QUIC'
```

### 描述

![Code_2j5mGA1Jfw](https://github.com/user-attachments/assets/e01d8b03-4be9-4935-b79f-3f119098cff3)
![mihomo-party_NlOhQTDkYO](https://github.com/user-attachments/assets/621bdd2d-f638-4aba-929b-094342621cc1)

使用 Mihomo Party 客户端 使用该配置报错

### 重现方式

使用 FlClash 客户端 依旧
