### ISSUE TITLE
[Bug] 一直提示ASN下载失败

### ISSUE THREAD

**Issue by codetiger666** [MetaCubeX/mihomo#1464]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

X-WRT 24.04_b202408182159 Noble

### Mihomo Version

alpha-c4660e1

### Configuration File

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 20000
allow-lan: true
tcp-concurrent: true
geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb
geo-auto-update: true
geo-update-interval: 720
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 0.0.0.0:9090
secret: ''
authentication: null
profile:
  store-selected: true
  store-fake-ip: false
tun:
  enable: false
  stack: system
  dns-hijack:
  - tcp://223.5.5.5:53
  - tcp://129.29.29.29:53
hosts: null
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:7874
  prefer-h3: true
  default-nameserver:
  - 223.5.5.5
  - 129.29.29.29
  nameserver-policy:
    geosite:cn,private,apple:
    - 223.5.5.5
    - 129.29.29.29
    - '[2400:3200::1]:53'
    - '[2402:4e00::]:53'
    - tls://dot.pub:853
    - tls://dns.alidns.com:853
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    rule-set:direct,chinaDomain,nn-direct:
    - 223.5.5.5
    - 129.29.29.29
    - '[2400:3200::1]:53'
    - '[2402:4e00::]:53'
    - tls://dot.pub:853
    - tls://dns.alidns.com:853
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    geosite:category-ads-all: rcode://success
    rule-set:icloud,apple,google,PROXY,gfw,greatfire,tld-not-cn,netflix,onedrive,speedtest,openai,nn-exchanges,nn-proxy,nn-dns:
    - https://dns.google/dns-query
    - https://dns.cloudflare.com/dns-query
  fake-ip-range: 198.18.0.1/16
  use-hosts: false
  nameserver:
  - 223.5.5.5
  - 129.29.29.29
  - '[2400:3200::1]:53'
  - '[2402:4e00::]:53'
  - tls://dot.pub:853
  - tls://dns.alidns.com:853
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  fallback:
  - https://dns.google/dns-query
  - https://dns.cloudflare.com/dns-query
sniffer:
  enable: true
  override-destination: false
  sniff:
    QUIC: null
    TLS: null
    HTTP:
      ports:
      - 80
      - 443
      override-destination: true
rules:
- RULE-SET,nn-exchanges,💰交易所
- RULE-SET,nn-direct,🟢全球直连
- RULE-SET,nn-proxy,🗺自定义代理
- RULE-SET,nn-dns,🔑dns
- RULE-SET,wechat,🟢全球直连
- RULE-SET,openai,🌐PROXY
- RULE-SET,reject,⭕全球拦截
- RULE-SET,lancidr,🟢全球直连,no-resolve
- RULE-SET,cncidr,🟢全球直连,no-resolve
- RULE-SET,direct,🟢全球直连
- RULE-SET,chinaDomain,🟢全球直连
- GEOSITE,cn,🟢全球直连
- GEOSITE,tld-cn,🟢全球直连
- GEOSITE,category-games@cn,🟢全球直连
- GEOIP,CN,🟢全球直连,no-resolve
- RULE-SET,icloud,🍏ICLOUD
- RULE-SET,apple,🍎苹果服务
- RULE-SET,onedrive,🪟微软服务
- RULE-SET,google,🌏GOOGLE
- RULE-SET,netflix,📺NETFLIX
- RULE-SET,netflixcidr,📺NETFLIX
- RULE-SET,gfw,🌐PROXY
- RULE-SET,speedtest,🏎️SPEEDTEST
- RULE-SET,greatfire,🌐PROXY
- RULE-SET,telegramcidr,🌐PROXY,no-resolve
- RULE-SET,PROXY,🌐PROXY
- MATCH,🐟漏网之鱼
```

### Description

无法下载ASN文件

### Reproduction Steps

无法下载ASN文件
![image](https://github.com/user-attachments/assets/3360c4b2-8437-468d-b219-f2b35f3cc8a3)
