### ISSUE TITLE
[Bug] listeners里定义的服务不走sub-rules，而是直接走rules

### ISSUE THREAD

**Issue by bsdcpp** [MetaCubeX/mihomo#1466]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Linux

### 系统版本

5.10.194

### Mihomo 版本

Mihomo Meta alpha-41efc5e linux amd64 with go1.23.0 Thu Aug 22 01:26:01 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
rules:
  - RULE-SET,rule1,DIRECT
  - IP-ASN,1,PROXY
  - Match,PROXY

sub-rules:
  sub-rule-name1:
    - Match,REJECT
    - DOMAIN,google.com,ss1
    - DOMAIN,baidu.com,DIRECT


# 流量入站
listeners:
  - name: ss
    type: shadowsocks
    port: 10808
    listen: 0.0.0.0 # 默认监听 0.0.0.0
    rule: sub-rule-name1 # 默认使用 rules，如果未找到 sub-rule 则直接使用 rules
    password: 3sWe86+UpxxxiK75a3so4ujw==
    cipher: rc4-md5
```

### 描述

按照上述官方配置，sub-rules只在listener里用，rules里并没有调用。
现象就是客户端进来并没有按照sub-rule-name1里的全部REJECT，而是走了上面rules里的规则。我把上面的代码片段放在最后，
或者任意调整rules和sub-rules的顺序都是一样的结果。
而且试过几个版本的mihomo，包括release里的，都是一样只走默认的rules。

### 重现方式

最新版本的mihomo的alpha, release都可以，按照[官网文档](https://github.com/MetaCubeX/mihomo/blob/Meta/docs/config.yaml)配置即可
