### ISSUE TITLE
[Bug] 疑似内存泄漏

### ISSUE THREAD

**Issue by Ptilopsis01** [MetaCubeX/mihomo#1467]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 系统版本

win11 26100.1586

### Mihomo 版本

v1.18.7

### 配置文件

```yaml
mode: rule
mixed-port: 7897
allow-lan: true
log-level: info
ipv6: true
external-controller: 127.0.0.1:9097
secret: ''
profile:
  store-selected: true
dns:
  use-system-hosts: false
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 8.8.8.8
  fallback: []
  fake-ip-filter:
  - dns.msftncsi.com
  - www.msftncsi.com
  - www.msftconnecttest.com
tun:
  stack: gvisor
  device: Clash_verge
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  strict-route: false
  mtu: 1500
  enable: true

proxies:
- xxx

proxy-groups:
- xxx

rules:
- xxx
```

### 描述

https://github.com/clash-verge-rev/clash-verge-rev/issues/1619

### 重现方式

https://github.com/clash-verge-rev/clash-verge-rev/issues/1619
