### ISSUE TITLE
[Bug] 配置文件得把https://输入两次，否则doh不生效

### ISSUE THREAD

**Issue by rumianoesa** [MetaCubeX/mihomo#1471]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [ ] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [ ] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Linux

### 系统版本

OpenWrt 23.05

### Mihomo 版本

Mihomo Meta 1.18.7 linux amd64 with go1.22.6 2024-08-17T15:54:08+00:00
Use tags: with_gvisor

### 配置文件

```yaml
dns:
  enable: true
  prefer-h3: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
```

### 描述

我通过设置doh为nameserver，然后用nameserver-policy指定所有直连域名dns的方式避免dns泄露。

当配置文件如下时，doh不生效，ipleak检测会有isp的dns
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
  
配置为
  nameserver:
    - https://https://223.5.5.5/dns-query
    - https://https://223.6.6.6/dns-query
就不会有dns泄露的情况

### 重现方式

按照文档配置
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
doh不生效

参考openclash生成的运行配置把https://输入两次就能生效
