### ISSUE TITLE
[Bug] 最新两个测试版本，扔在 cfw 里无法开启 tun 模式

### ISSUE THREAD

**Issue by 328902301** [MetaCubeX/mihomo#1472]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

windows 10

### Mihomo Version

2024.8.25 518e9bd
2024.8.26 81756fc

### Configuration File

```yaml
port: 7890
mixed-port: 7891
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
proxy-providers:
  All:
    type: file
    path: ./providers/proxy/all.yaml
    filter: ^(?!.*((?i)流量|套餐|重置)).*$
    health-check:
      enable: true
      interval: 1800
      url: http://www.gstatic.com/generate_204
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
    - 119.28.28.28
    - 223.5.5.5
    - 223.6.6.6
  fallback:
    - tls://dns.rubyfish.cn:853
    - tls://1.0.0.1:853
    - tls://dns.google:853
    - https://doh.opendns.com/dns-query
    - https://doh.familyshield.opendns.com/dns-query
  nameserver-policy: {}
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
proxies: null
proxy-groups:
  - name: 🚀 节点选择
    type: select
    use:
      - All
    proxies:
      - ♻️ 自动选择
      - 🎯 全球直连
      - 🛑 全球拦截
  - name: ♻️ 自动选择
    type: url-test
    use:
      - All
    url: http://www.gstatic.com/generate_204
    interval: 100
    tolerance: 1
    lazy: false
    disable-udp: false
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - REJECT
  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
rule-providers:
  Lan:
    type: file
    behavior: classical
    path: ./providers/rule/Lan_No_Resolve.yaml
    interval: 172800
  AppleCDN:
    type: file
    behavior: classical
    path: ./providers/rule/apple_cdn.yaml
    interval: 172800
  CDN:
    type: file
    behavior: classical
    path: ./providers/rule/cdn.yaml
    interval: 172800
  Direct:
    type: file
    behavior: classical
    path: ./providers/rule/Direct_No_Resolve.yaml
    interval: 172800
  Proxy_Classical:
    type: file
    behavior: classical
    path: ./providers/rule/Proxy_Classical_No_Resolve.yaml
    interval: 172800
  Global_Classical:
    type: file
    behavior: classical
    path: ./providers/rule/Global_Classical_No_Resolve.yaml
    interval: 172800
rules:
  - RULE-SET,Lan,DIRECT
  - RULE-SET,AppleCDN,DIRECT
  - RULE-SET,CDN,🚀 节点选择
  - RULE-SET,Direct,DIRECT
  - RULE-SET,Proxy_Classical,🌏 国外网站
  - RULE-SET,Global_Classical,🌏 国外网站
  - GEOIP,CN,🇨🇳 国内网站,no-resolve
  - MATCH,🐟 漏网之鱼
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```

### Description

使用的是 Clash for Windows GUI 客户端，替换 mihomo 内核到 \resources\static\files\win\x64\clash-win64.exe，并且修复了 cfw 面板上使其显示 Meta 版本号，以及修复服务模式小地球灰色问题。

25号晚上 mihomo 更新了 518e9bd 版本，正常替换后，tun 模式就无法开启了。回退到上一个版本 16c95fc，以及之前的其他版本都正常，26号发布的最新分支版本也无法正常开启 tun，表现为无法创建一个网卡。

### Reproduction Steps

使用 Clash for Windows GUI 客户端，下载最新 Alpha 内核替换自带的内核即可复现。

### Logs

```shell
No response
```
