### ISSUE TITLE
[Bug] 关于DNS 配置的 端口号问题

### ISSUE THREAD

**Issue by toyo2333** [MetaCubeX/mihomo#1473]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [X] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Windows

### 系统版本

11

### Mihomo 版本

1.18.4

### 配置文件

```yaml
dns:
  enable: true
  prefer-h3: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
     - "*"
     - "+.lan"
     - "+.local"
  nameserver:
    - https://1.12.12.12/dns-query
    - https://223.5.5.5/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://1.12.12.12/dns-query
      - https://223.5.5.5/dns-query

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
```
```


### 描述

我想问 listen里的端口和dns-hijack里的端口不一样会怎么样，就像上面这样，listen是1053（这个也是按你们wiki里的示例填写的），dns-hijack里写的是53

很困惑，请解答，谢谢。

请告知我正确的写法。谢谢

### 重现方式

我想问 listen里的端口和dns-hijack里的端口不一样会怎么样，就像上面这样，listen是1053（这个也是按你们wiki里的示例填写的），dns-hijack里写的是53

很困惑，请解答，谢谢。

请告知我正确的写法。谢谢

### 日志

_No response_
