### ISSUE TITLE
[Feature] Fake IP filter能否增加取反选项

### ISSUE THREAD

**Issue by psychosispy** [MetaCubeX/mihomo#1479]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

目前的Fake IP filter是匹配规则内的域名使用realip
假如路由设备性能一般，在千兆以上的网络环境里，不绕过内核就没有办法跑满带宽，导致大量国内网站速度打折
目前想实现大陆域名realip，仅代理和广告屏蔽域名fakeip，只能用fake IP filter+cn规则，但是cn域名规则集不可能完美，还会和rule中的ad规则重合导致去广告失效，似乎无法实现只对黑名单网站使用fakeip，别的网站默认realip
可不可以为fake ip提供一种黑名单模式，只对匹配proxy和ad规则内的域名使用fakeip，未命中规则则使用realip

**Comment by wwqgtxx** [comment]
done: https://github.com/MetaCubeX/mihomo/commit/f6164ac1959945cc5366bf3207ec41db13966a52

**Comment by wwqgtxx** [comment]
global仅仅只是针对rule，对其他任何设置都不该有任何影响，所以不会修改

**Comment by HEUDavid** [comment]
> done: [f6164ac](https://github.com/MetaCubeX/mihomo/commit/f6164ac1959945cc5366bf3207ec41db13966a52)

@wwqgtxx 

感觉当前这个设计还是不够灵活，比如下面这种情景：

只把fake-ip的流量发往tun处理，real-ip走en0，tun配置如下：
```
tun:
  auto-route: true
  route-address:
    - 198.18.0.0/16
```

DNS处理广告域名与代理域名，仅广告和需要代理的域名解析为fake-ip，其他返回real-ip
```
dns:
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - rule-set:anti-AD
    - geosite:google
    - geosite:gfw
  fake-ip-filter-mode: whitelist
```
那么，当广告和需要代理的域名规则不全面时，许多漏网之鱼会绕过clash核心，发往en0，漏网之鱼无法走代理了，从而无法连接或者连接速度很慢无法加速，或广告域名未被处理。

如果采用黑名单模式呢：
```
dns:
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - geosite:cn
    - rule-set:my_direct
    - "*.lan"
  fake-ip-filter-mode: blacklist
```
那么很多广告域名会命中geosite:cn规则返回real-ip，然后绕过clash核心，发往en0，广告域名就无法被clash核心处理所屏蔽掉。

我认为，更好的做法可能是：
可以明确指定黑白名单fake-ip-filter，以及final返回fake-ip / real-ip。
配置效果可能是这样：
```
dns:
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  white-fake-ip-filter: # 满足规则列表则返回fake-ip，可以明确满足规则的域名指定发往clash核心（cn广告域名同时满足geosite:cn）
    - rule-set:anti-AD
    - geosite:google
    - geosite:gfw
  black-fake-ip-filter: # 满足规则列表则返回real-ip，可以明确满足规则的域名绕过clash核心
    - geosite:cn
    - rule-set:my_direct
    - "*.lan"
  fake-ip-final: fake-ip / real-ip  # 最终返回 fake-ip 还是 real-ip
```
这样的话，就更灵活了，能解决上面单独的黑名单或者白名单的痛点。我们可以指定广告、gfw、 proxy等域名列表返回fake-ip, 一些cn常用、直连、内网等域名列表绕过clash核心。同时规则之外的final 可决定是否发往clash核心处理。
