### ISSUE TITLE
[Bug] 使用更新 provider 的 API，如果内容一样就不会去更新订阅信息

### ISSUE THREAD

**Issue by Yakuiee** [MetaCubeX/mihomo#1480]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [X] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Windows

### 系统版本

win11 22631.4037

### Mihomo 版本

Mihomo Meta alpha-38fd371 windows amd64 with go1.23.0 Thu Aug 29 16:08:40 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
proxy-providers:
  Enet:
    type: http
    url: https://sub.getlitchi.com/api/v1/client/subscribe?token=123
    path: ./proxy-providers/enet.yaml
    interval: 86400
```

### 描述

更新 provider，如果内容一样就不会去更新订阅信息

https://github.com/MetaCubeX/mihomo/blob/4fecf68b8ba3f6e95257607fa67af94f35bdc08e/adapter/provider/provider.go#L76

### 重现方式

https://github.com/user-attachments/assets/2b8ffbf8-91dd-4c5d-a317-ea1492158493
