### ISSUE TITLE
wireguard节点，似乎不支持服务器反向访问客户端？

### ISSUE THREAD

**Issue by orwithout** [MetaCubeX/mihomo#1485]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

## 环境说明
我希望通过WireGuard将没有公网IP的家庭电脑与具有公网IP的服务器连接，以便暴露家庭电脑的远程桌面服务。考虑使用Clash Verge（Mihomo内核）来支持WireGuard协议，代替官方客户端以建立连接。

## 问题描述
在Windows客户端上，我使用Mihomo（Clash Verge）配置了WireGuard代理节点，并启用了Windows的远程桌面服务（3389端口）。服务器能够ping通客户端的WireGuard隧道IP，但无法访问隧道IP上的3389端口。

当我切换回WireGuard官方客户端，并使用相同配置时，服务器可以正常访问客户端的3389端口的远程桌面服务。

## 疑问
这可能是Mihomo出于安全考虑的设计。是否有可能在配置中添加一个选项，以允许服务器访问客户端的服务？
还是说mihomo 确实支持这种能力，而我错过了某个细节？（希望得到支持）

**Comment by xishang0128** [comment]
代理软件的的代理协议仅支持正向

**Comment by thomasTAT** [comment]
大佬，您的WireGuard配置成功了吗？能否分享一下您的配置文件参考一下？
我的配置虽然能连上，但遇到了一些小问题，想对比看看是否有优化空间。
https://github.com/MetaCubeX/mihomo/discussions/1810

**Comment by thomasTAT** [comment]
手机 Clash meta for andriod + WireGuard 正常连接，切换后WiFi断连，需要重启 clash 才能恢复连接，请问你有遇到过吗？https://github.com/MetaCubeX/mihomo/discussions/1810



# 完整配置信息：
```
#clash config

proxies:

- name: "SF-UK-LD"
  type: wireguard
  ip: 10.14.0.2
  private-key: dfjashdjfjkdsfhjkdshfjkdhjkfhkdjfdfhdjfhdjfhd
  peers:
    - server: uk-lon.prod.surfshark.com
      port: 51820
      public-key: iBJRXLZwXuWWrOZE1ZrAXEKMgV/z0WjG0Tks5rnWLBI=
      allowed-ips: ['0.0.0.0/0']  
  udp: true


proxy-groups:
  
  - name: "ChatGPT"
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - SF-UK-LD

rules:
  - DOMAIN-SUFFIX,openai.com,ChatGPT
  - DOMAIN-SUFFIX,chatgpt.com,ChatGPT
  - MATCH,DIRECT


```
