### ISSUE TITLE
安卓系统上 代理出现问题

### ISSUE THREAD

**Issue by Qing15** [MetaCubeX/mihomo#1486]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Android

### 系统版本

安卓14 ，小米澎湃OS

### Mihomo 版本

mihomo-android-arm64-v8-v1.18.8.gz

### 配置文件

```yaml
mixed-port: 11223
allow-lan: true
geodata-mode: true
unified-delay: true
mode: rule
log-level: debug
ipv6: false
udp: true
tcp-concurrent: true
enable-process: true
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  skip-domain:
  force-domain:
    - 'google.com'
profile:
  store-selected: true
  store-fake-ip: true
external-controller: 127.0.0.1:9090
secret: 'clash'
external-ui: ClashDashboard/metacubexd
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip" #从 GitHub Pages 分支获取
tun:
  enable: true
  device: Meta
  stack: gvisor #gvisor
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
  strict-route: true
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  prefer-h3: false
  use-hosts: true
  use-system-hosts: true
  respect-rules: false
  enhanced-mode: fake-ip
  # enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - 'lens.l.google.com'
    - '*.mcdn.bilivideo.cn'
    - 'connect.rom.miui.com'
    - 'localhost.ptlogin2.qq.com'
    - '+.msftnsci.com'
    - '+.msftconnecttest.com'
  default-nameserver:
    - '119.29.29.29'
    - '180.76.76.76'
 #   - '114.114.114.114#REJECT'
  proxy-server-nameserver:
    - '119.29.29.29#DNS'
    - 'https://1.12.12.12/dns-query#DNS'    
    - '180.76.76.76#DNS'
    
  nameserver:
    - 'https://1.12.12.12/dns-query'      
    - 'tcp://180.76.76.76'   

  fallback:
    - '8.8.8.8'    
    - '119.29.29.29'
```

### 描述

https://github.com/user-attachments/assets/e36040f3-9241-4140-aee6-c8b75389bec1

看直播时，只代理了半分钟数据，就不代理了，面板没数据了
![IMG_20240902_190259](https://github.com/user-attachments/assets/d564b76f-a1bb-4bdc-b737-58d2b3460c05)

### 重现方式

手机是小米13pro，安卓14澎湃系统。mihomo使用的是mihomo-android-arm64-v8-v1.18.8.gz。用的是TUN模式gvisor, 使用V1.18.3版本没问题，使用最新的几个版本,同样的配置都出现只代理半分钟左右，数据就不经过mihomo处理了
