### ISSUE TITLE
[Bug] Linux上无法连接到ipv6 提示network is unreachable，服务器有ipv6

### ISSUE THREAD

**Issue by nmyo** [MetaCubeX/mihomo#1487]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

Debian12

### Mihomo Version

1.18.8

### Configuration File

```yaml
mode: rule
# ipv6 支持
ipv6: true
log-level: info
# 允许局域网连接
allow-lan: false
# socks5/http 端口
mixed-port: 7890
redir-port: 7892   # redirect 透明代理端口，仅能代理 TCP 流量, Linux macOS 使用
tproxy-port: 7893  # tproxy 透明代理端口，可代理 TCP 与 UDP 流量，仅 Linux 使用
# Meta 内核特性 https://wiki.metacubex.one/config/general
# 统一延迟
# 更换延迟计算方式,去除握手等额外延迟
unified-delay: true
# TCP 并发
# 同时对所有ip进行连接，返回延迟最低的地址
tcp-concurrent: true

geodata-mode: true
# Geo 数据库下载地址
# 使用 FastGit 代理 (https://fgit.cf)
# 源地址 https://github.com/MetaCubeX/meta-rules-dat
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"

# 进程匹配模式
# 路由器上请设置为 off
find-process-mode: off

# 全局客户端指纹
global-client-fingerprint: random # 随机指纹

# 缓存
profile:
  store-selected: true
  store-fake-ip: true

# 域名嗅探
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
# tun 模式
tun:
  enable: true  # enable 'true'
  stack: system  # or 'gvisor'
  
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-detect-interface: true

# dns 设置
dns:
  enable: true
  listen: :1053
  ipv6: true
  prefer-h3: true  
  enhanced-mode: redir-host
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
```

### Description

linux上无法连接到ipv6

### Reproduction Steps

尝试修改配置文件但是无效
