### ISSUE TITLE
[Bug] win11 仅设置Tun模式 出现DNS泄露

### ISSUE THREAD

**Issue by toyo2333** [MetaCubeX/mihomo#1490]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

11

### Mihomo Version

v1.8.18 beta

### Configuration File

```yaml
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true

dns:
  enable: true
  prefer-h3: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  nameserver:
    - https://1.12.12.12/dns-query
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://1.12.12.12/dns-query
      - https://223.5.5.5/dns-query
    "geosite:geolocation-!cn":
      - https://dns.cloudflare.com/dns-query
      - https://dns.google/dns-query
```
```


### Description

win11系统，仅开启Tun模式后，出现DNS泄露：使用测试工具：https://browserleaks.com/dns 和 https://ipleak.net/ 测试 

发现测试结果里，出现了 本地运营商的 DNS 服务器 ip（预期不应该出现）

如果测试开启 系统代理模式 则正常不会泄露，或者 TUN和 系统代理同时开，也不会泄露，仅开tun才会。

### Reproduction Steps

win11系统，仅开启Tun模式后，出现DNS泄露：使用测试工具：https://browserleaks.com/dns 和 https://ipleak.net/ 测试 

发现测试结果里，出现了 本地运营商的 DNS 服务器 ip（预期不应该出现）

如果测试开启 系统代理模式 则正常不会泄露，或者 TUN和 系统代理同时开，也不会泄露，仅开tun才会。

### Logs

_No response_
