### ISSUE TITLE
[Bug] Mihomo Unexpectedly Resolves and Connects to the Domain in Rules

### ISSUE THREAD

**Issue by RebelliousWhiz** [MetaCubeX/mihomo#1503]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [x] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

Windows 11 (arm64)

### Mihomo Version

Mihomo Meta v1.18.8 windows arm64 with go1.23.0

### Configuration File

```yaml
(Minimal Config)
ipv6: false
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 119.29.29.29
  fake-ip-range: 192.18.0.1/16
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
  proxy-server-nameserver:
    - 119.29.29.29
tun:
  enable: true
  stack: system
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
proxies:
  - name: LINE1
    type: ss
    server: xxxx
    port: 15xxx
    udp: true
    cipher: aes-256-gcm
    password: "xxx"
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - LINE1
rules:
  - DOMAIN-KEYWORD,google,PROXY
  - DOMAIN-KEYWORD,gstatic,PROXY
  - GEOIP,CN,DIRECT
  - MATCH,PROXY

```

### Description

Domains match proxy rules do not route through proxy directly sometimes. We can see unexpected DNS requests in the log, and Mihomo is connecting to the resolved IP using a server (Destination IP shown on the connection page) instead of connecting to the server directly (no Destination IP shown on the connection page).

<img width="982" alt="Screenshot 2024-09-10 at 2 59 41 PM" src="https://github.com/user-attachments/assets/b727d7e1-4c4f-45eb-af3d-f6970590d8bc">

<img width="1282" alt="Screenshot 2024-09-10 at 2 58 54 PM" src="https://github.com/user-attachments/assets/c5201ca2-34bd-49ae-a3df-c57de58d2afe">

According to my understanding in the graphic here, the domain that matches the RULE-SET should be resolved by the remote server and not through _nameserver_.

https://wiki.metacubex.one/config/dns/diagram/
