### ISSUE TITLE
[Bug] tun模式下跳过qbittorrent但是会一直有大量的io timeout日志刷屏

### ISSUE THREAD

**Issue by AceCandy** [MetaCubeX/mihomo#1504]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [X] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Linux

### 系统版本

fnOS (debian 12.6)

### Mihomo 版本

Mihomo Meta v1.18.8 linux amd64 with go1.23.0

### 配置文件

```yaml
用了懒人配置https://gist.github.com/liuran001/5ca84f7def53c70b554d3f765ff86a33
但是开启了tun模式

tun:
  enable: true  # enable 'true'
  stack: mixed  # or 'gvisor'
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-detect-interface: true

规则添加了qBittorrent-nox程序跳过
rules:
  - PROCESS-NAME,qBittorrent,DIRECT,no-resolve
  - PROCESS-NAME,qBittorrent-nox,DIRECT,no-resolve
```

### 描述

![image](https://github.com/user-attachments/assets/afe1f407-f810-4f1d-8598-9d97911132d8)
能正常运行，但是从后台日志里看到大量的warning io timeout刷屏

序列号 | 类型 | 内容
-- | -- | --
12014 | [warning] | [TCP] dial DIRECT (match ProcessName/qBittorrent-nox) [fdfe:dcba:9876::1]:44755(qbittorrent-nox, uid=991) --> [2409:8a1e:62:da20::66f]:36882 error: dial tcp [2409:8a1e:62:da20::66f]:36882: connect: connection refused
12013 | [warning] | [TCP] dial DIRECT (match ProcessName/qBittorrent-nox) 198.18.0.1:52251(qbittorrent-nox, uid=991) --> 125.73.195.6:55287 error: dial tcp 125.73.195.6:55287: connect: connection refused
12012 | [warning] | [TCP] dial DIRECT (match ProcessName/qBittorrent-nox) 198.18.0.1:52251(qbittorrent-nox, uid=991) --> 125.73.195.6:55287 error: dial tcp 125.73.195.6:55287: connect: connection refused
12011 | [warning] | [TCP] dial DIRECT (match ProcessName/qBittorrent-nox) [fdfe:dcba:9876::1]:58515(qbittorrent-nox, uid=991) --> [240e:b67:58f:c100:1cf4:5144:a938:96f1]:5375 error: dial tcp [240e:b67:58f:c100:1cf4:5144:a938:96f1]:5375: i/o timeout
12010 | [warning] | [TCP] dial DIRECT (match ProcessName/qBittorrent-nox) 198.18.0.1:37455(qbittorrent-nox, uid=991) --> 122.97.239.38:18579 error: dial tcp 122.97.239.38:18579: i/o timeout
12009 | [warning] | [TCP] dial DIRECT (match ProcessName/qBittorrent-nox) 198.18.0.1:44749(qbittorrent-nox, uid=991) --> 117.64.68.43:5375 error: dial tcp 117.64.68.43:5375: i/o timeout
12008 | [warning] | [TCP] dial DIRECT (match ProcessName/qBittorrent-nox) 198.18.0.1:49593(qbittorrent-nox, uid=991) --> 112.23.64.39:18819 error: dial tcp 112.23.64.39:18819: i/o timeout

### 重现方式

一直都会出现
