### ISSUE TITLE
[Bug] old connection not closed if ip address changed

### ISSUE THREAD

**Issue by JeelsBoobz** [MetaCubeX/mihomo#1512]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Android

### System Version

Android 12

### Mihomo Version

v1.18.8

### Configuration File

```yaml
tproxy-port: 9898
redir-port: 9797
mode: 'rule'
allow-lan: true
unified-delay: true
bind-address: '*'
log-level: silent
ipv6: false
geodata-mode: true
geox-url:
  geoip: 'https://fastly.jsdelivr.net/gh/JeelsBoobz/v2ray-rules-dat@release/geoip.dat'
  geosite: 'https://fastly.jsdelivr.net/gh/JeelsBoobz/v2ray-rules-dat@release/geosite.dat'
  mmdb: 'https://fastly.jsdelivr.net/gh/JeelsBoobz/geoip@release/Country.mmdb'
tcp-concurrent: true
external-controller: 0.0.0.0:9090
external-ui: ./ui
#external-ui-url: 'https://github.com/MetaCubeX/Yacd-meta/archive/refs/heads/gh-pages.zip'
external-ui-url: 'https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'
global-client-fingerprint: chrome
hosts:
  'test-server.gov.id': 127.0.0.1
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  use-system-hosts: true
  nameserver:
    - '127.0.0.1:5591'
sniffer:
  enable: true
  override-destination: true
  sniff:
    QUIC:
      ports: [443]
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-20000]
      override-destination: true
  skip-domain: []
  force-domain: []
tun:
  enable: false
  device: utun
  stack: system
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: false
  auto-detect-interface: false
iptables: {enable: false}
interface-name: ''
find-process-mode: always
proxies: []
proxy-groups:
  - name: DEFAULT
    type: select
    url: 'https://www.gstatic.com/generate_204'
    interval: 200
    tolerance: 100
    lazy: true
    proxies:
      - SINGAPORE
      - INDONESIA
      - UDP-SERVER
      - DIRECT
    use:
      - FREE
      - PREMIUM
      - JeelsCDN
#      - JeelsSNI
  - name: GAMING
    type: select
    url: 'https://www.gstatic.com/generate_204'
    interval: 200
    tolerance: 100
    lazy: true
    proxies:
      - SINGAPORE
      - INDONESIA
      - UDP-SERVER
      - DIRECT
    use:
      - FREE
      - PREMIUM
#      - JeelsSNI
  - name: SINGAPORE
    type: load-balance
    strategy: consistent-hashing
    url: 'https://www.gstatic.com/generate_204'
    interval: 200
    tolerance: 100
    lazy: true
    filter: '🇸🇬'
    exclude-filter: 'FoolVPN|JagoanSSH'
    use:
      - FREE
      - PREMIUM
      - JeelsCDN
#      - JeelsSNI
  - name: INDONESIA
    type: load-balance
    url: 'https://www.gstatic.com/generate_204'
    interval: 200
    tolerance: 100
    lazy: true
    filter: '🇮🇩'
#    exclude-filter: 'FoolVPN'
    use:
      - FREE
      - PREMIUM
      - JeelsCDN
#      - JeelsSNI
  - name: UDP-SERVER
    type: load-balance
    strategy: consistent-hashing
    url: 'https://www.gstatic.com/generate_204'
    interval: 200
    tolerance: 100
    lazy: true
    filter: '🇸🇬'
    exclude-filter: 'FoolVPN'
    use:
      - FREE
      - PREMIUM
  - name: DNS
    type: load-balance
    strategy: consistent-hashing
    url: 'https://www.gstatic.com/generate_204'
    interval: 200
    tolerance: 100
    lazy: true
    exclude-filter: 'FoolVPN'
    use:
      - FREE
      - PREMIUM
  - name: HOTSPOT
    type: select
    proxies:
      - REJECT
      - PASS
proxy-providers:
  PREMIUM:
    type: file
    interval: 21600
    path: ./provider/proxy/Premium.CDN
    health-check:
      enable: true
      interval: 300
      lazy: true
      url: 'https://www.gstatic.com/generate_204'
  FREE:
    type: file
    interval: 21600
    path: ./provider/proxy/Free.CDN
    health-check:
      enable: true
      interval: 300
      lazy: true
      url: 'https://www.gstatic.com/generate_204'
rule-providers:
  GAME_LOGIN:
    type: file
    behavior: classical
    interval: 86400
    path: ./provider/rule/rule_game_login.yml
  GAME_DATA:
    type: file
    behavior: classical
    interval: 86400
    path: ./provider/rule/rule_game_data.yml
  GAME_PLAY:
    type: file
    behavior: classical
    interval: 86400
    path: ./provider/rule/rule_game_play.yml
  SHORTLINK:
    type: file
    behavior: classical
    interval: 86400
    path: ./provider/rule/rule_shortlink.yml
  HOTSPOT:
    type: file
    behavior: classical
    interval: 86400
    path: ./provider/rule/rule_hotspot.yml
rules:
  # Default #
  - NETWORK,UDP,UDP-SERVER
  - MATCH,DEFAULT
```

### Description

After the IP Address changes, old connection not close automatically
![Screenshot_2024-09-15-11-54-04-414_xyz chz bfm](https://github.com/user-attachments/assets/1ead4db1-8d39-43e6-9b7f-187358ea9085)

### Reproduction Steps

Just run normally
