### ISSUE TITLE
[Bug] nameserver-policy 通配符 `+` 没有工作

### ISSUE THREAD

**Issue by AsenHu** [MetaCubeX/mihomo#1523]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

Windows 11 Pro N for Workstations 23H2

### Mihomo Version

Mihomo Meta alpha-a08aa10 windows amd64 with go1.23.1 Thu Sep 19 10:43:13 UTC 2024
Use tags: with_gvisor

### Configuration File

```yaml
# https://github.com/MetaCubeX/mihomo/commit/f20f371a612a6cb62fb1045fc63732b503e30071

mixed-port: 6081

allow-lan: false # 允许局域网连接

mode: rule

#自定义 geodata url
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"

geo-auto-update: true # 是否自动更新 geodata
geo-update-interval: 24 # 更新间隔，单位：小时

log-level: debug # 日志等级 silent/error/warning/info/debug

ipv6: true # 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录

external-controller: 127.0.0.1:9093
secret: ""

tcp-concurrent: true # TCP 并发连接所有 IP, 将使用最快握手的 TCP

# 全局 TLS 指纹，优先低于 proxy 内的 client-fingerprint
# 可选： "chrome","firefox","safari","ios","random","none" options.
# Utls is currently support TLS transport in TCP/grpc/WS/HTTP for VLESS/Vmess and trojan.
global-client-fingerprint: firefox

#  TCP keep alive interval
disable-keep-alive: false #目前在android端强制为true
keep-alive-idle: 15
keep-alive-interval: 15

profile: # 存储 select 选择记录
  store-selected: true

  # 持久化 fake-ip
  store-fake-ip: true

# Tun 配置
tun:
  enable: false

# 嗅探域名 可选配置
sniffer:
  enable: false

# DNS 配置
dns:
  cache-algorithm: arc
  enable: true # 关闭将使用系统 DNS
  prefer-h3: false # 是否开启 DoH 支持 HTTP/3，将并发尝试
  ipv6: true # false 将返回 AAAA 的空结果
  # 用于解析 nameserver，fallback 以及其他 DNS 服务器配置的，DNS 服务域名
  # 只能使用纯 IP 地址，可使用加密 DNS
  default-nameserver:
    - "tcp://1.1.1.1#PROXY"
  enhanced-mode: fake-ip # or redir-host

  fake-ip-range: 198.18.0.1/16 # fake-ip 池设置

  # use-hosts: true # 查询 hosts

  # 配置后面的nameserver、fallback和nameserver-policy向dns服务器的连接过程是否遵守遵守rules规则
  # 如果为false（默认值）则这三部分的dns服务器在未特别指定的情况下会直连
  # 如果为true，将会按照rules的规则匹配链接方式（走代理或直连），如果有特别指定则任然以指定值为准
  # 仅当proxy-server-nameserver非空时可以开启此选项, 强烈不建议和prefer-h3一起使用
  # 此外，这三者配置中的dns服务器如果出现域名会采用default-nameserver配置项解析，也请确保正确配置default-nameserver
  respect-rules: false

  # 配置不使用 fake-ip 的域名
  fake-ip-filter:
    - "www.msftconnecttest.com"
    - "ping.archlinux.org"
    - "frp-mix.top"

  # DNS 主要域名配置
  # 支持 UDP，TCP，DoT，DoH，DoQ
  # 这部分为主要 DNS 配置，影响所有直连，确保使用对大陆解析精准的 DNS
  nameserver:
    - "tcp://1.1.1.1#PROXY"

  # 当配置 fallback 时，会查询 nameserver 中返回的 IP 是否为 CN，非必要配置
  # 当不是 CN，则使用 fallback 中的 DNS 查询结果
  # 确保配置 fallback 时能够正常查询
  # fallback:
  #   - tcp://1.1.1.1
  #   - 'tcp://1.1.1.1#ProxyGroupName' # 指定 DNS 过代理查询，ProxyGroupName 为策略组名或节点名，过代理配置优先于配置出口网卡，当找不到策略组或节点名则设置为出口网卡

  # 专用于节点域名解析的 DNS 服务器，非必要配置项
  proxy-server-nameserver:
    - tls://223.5.5.5
    - tls://[2400:3200::1]

  # 配置 fallback 使用条件
  # fallback-filter:
  #   geoip: true # 配置是否使用 geoip
  #   geoip-code: CN # 当 nameserver 域名的 IP 查询 geoip 库为 CN 时，不使用 fallback 中的 DNS 查询结果
  #   配置强制 fallback，优先于 IP 判断，具体分类自行查看 geosite 库
  #   geosite:
  #     - gfw
  #   如果不匹配 ipcidr 则使用 nameservers 中的结果
  #   ipcidr:
  #     - 240.0.0.0/4
  #   domain:
  #     - '+.google.com'
  #     - '+.facebook.com'
  #     - '+.youtube.com'

  # 配置查询域名使用的 DNS 服务器
  nameserver-policy:
    #   'www.baidu.com': '114.114.114.114'
    #   '+.internal.crop.com': '10.0.0.1'
    "geosite:cn, steam@cn":
      - tls://223.5.5.5
      - tls://[2400:3200::1]
    "www.msftconnecttest.com, ping.archlinux.org, +.tanggaoyun.com, +.candycake.cloud":
      - tls://223.5.5.5
      - tls://[2400:3200::1]
    "geosite:geolocation-!cn":
      - "tcp://1.1.1.1#PROXY"

proxies:
  - name: PROXY
    type: vless
    server: ""
    port: 443
    uuid: 
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: # REALITY servername
    reality-opts:
      public-key: 
      short-id: # optional
    client-fingerprint: firefox # cannot be empty
    tfo: true
    mptcp: true

rules:
  - DOMAIN-SUFFIX,tanggaoyun.com,DIRECT
  - DOMAIN-SUFFIX,candycake.cloud,DIRECT

  - AND,((NETWORK,UDP),(DST-PORT,443)),REJECT
  - MATCH,PROXY
```

### Description

当传入的请求目标地址不包含 IP（例如 http 传入，只包含域名这种），即使域名在 nameserver-policy 指定了 DNS 服务器，也不会遵守。

为了方便发现问题，我没有压缩 全局字段和 DNS 字段，如果配置文件仍然不够精简，请告诉我。

### Reproduction Steps

1. 补充我提供的配置文件中，代理节点（是一个 REALITY 节点）的信息。
2. 使用 `mihomo -d ./配置文件目录` 启动 mihomo
3. 在同一台设备启动命令行，使用 `curl https://www.tanggaoyun.com -x 127.0.0.1:6081` 发出请求
4. 查看日志文件，得到 `[DNS] resolve www.tanggaoyun.com A from tcp://1.1.1.1:53`，说明 `www.tanggaoyun.com` 未命中 `nameserver-policy` 中的 `+.candycake.cloud`
5. 复现完成，使用 Ctrl + C 关闭主程序

### Logs

```shell
PS D:\Mihomo> .\mihomo-windows-amd64.exe -d .\
time="2024-09-20T13:32:38.7135252+08:00" level=info msg="Start initial configuration in progress"
time="2024-09-20T13:32:38.7146579+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-09-20T13:32:38.7146579+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-09-20T13:32:38.7177623+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-09-20T13:32:38.7188014+08:00" level=info msg="Load GeoSite rule: cn"
time="2024-09-20T13:32:39.0524793+08:00" level=info msg="Finished initial GeoSite rule cn => dns.nameserver-policy, records: 90143"
time="2024-09-20T13:32:39.0529863+08:00" level=info msg="Load GeoSite rule: steam@cn"
time="2024-09-20T13:32:39.0705765+08:00" level=info msg="Finished initial GeoSite rule  steam@cn => dns.nameserver-policy, records: 13"
time="2024-09-20T13:32:39.0705765+08:00" level=info msg="Load GeoSite rule: geolocation-!cn"
time="2024-09-20T13:32:39.1705197+08:00" level=info msg="Finished initial GeoSite rule geolocation-!cn => dns.nameserver-policy, records: 25380"
time="2024-09-20T13:32:39.1760381+08:00" level=info msg="Initial configuration complete, total time: 461ms"
time="2024-09-20T13:32:39.1760381+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9093"
time="2024-09-20T13:32:39.1780386+08:00" level=info msg="Sniffer is closed"
time="2024-09-20T13:32:39.1780386+08:00" level=info msg="Use tcp concurrent"
time="2024-09-20T13:32:39.1780386+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:6081"
time="2024-09-20T13:32:39.1822159+08:00" level=info msg="Start initial Compatible provider default"
time="2024-09-20T13:32:39.1822159+08:00" level=info msg="[GEO] last update time 2024-09-19 13:49:25.6550377 +0800 CST"
time="2024-09-20T13:32:43.0073532+08:00" level=debug msg="Auth success from 127.0.0.1:14390 -> "
time="2024-09-20T13:32:43.0074373+08:00" level=debug msg="[Rule] use default rules"
time="2024-09-20T13:32:43.0082056+08:00" level=debug msg="[DNS] resolve www.tanggaoyun.com A from tcp://1.1.1.1:53"
time="2024-09-20T13:32:43.0082056+08:00" level=debug msg="[DNS] resolve www.tanggaoyun.com AAAA from tcp://1.1.1.1:53"
time="2024-09-20T13:32:43.0088012+08:00" level=debug msg="initial random HelloID:safari"
time="2024-09-20T13:32:43.0093467+08:00" level=debug msg="initial random HelloID:chrome"
time="2024-09-20T13:32:43.0104631+08:00" level=debug msg="use specified fingerprint:Firefox"
time="2024-09-20T13:32:43.0099502+08:00" level=debug msg="use specified fingerprint:Firefox"
time="2024-09-20T13:32:43.2285877+08:00" level=debug msg="REALITY Authentication: true, AEAD: *aes.gcmAsm"
time="2024-09-20T13:32:43.2291066+08:00" level=info msg="[TCP] mihomo --> 1.1.1.1:53 doesn't match any rule using PROXY"
time="2024-09-20T13:32:43.229182+08:00" level=debug msg="XTLS Vision write padding2: command=0, payloadLen=38, paddingLen=128"
time="2024-09-20T13:32:43.2428927+08:00" level=debug msg="REALITY Authentication: true, AEAD: *aes.gcmAsm"
time="2024-09-20T13:32:43.2436483+08:00" level=info msg="[TCP] mihomo --> 1.1.1.1:53 doesn't match any rule using PROXY"
time="2024-09-20T13:32:43.2473805+08:00" level=debug msg="XTLS Vision write padding2: command=0, payloadLen=38, paddingLen=174"
time="2024-09-20T13:32:43.2775717+08:00" level=debug msg="XTLS Vision read padding: command=0, payloadLen=242, paddingLen=163"
time="2024-09-20T13:32:43.2775717+08:00" level=debug msg="[DNS] www.tanggaoyun.com --> [43.159.98.10 43.159.99.100 43.159.99.102] A from tcp://1.1.1.1:53"
time="2024-09-20T13:32:43.3030409+08:00" level=debug msg="XTLS Vision read padding: command=0, payloadLen=180, paddingLen=217"
time="2024-09-20T13:32:43.3031061+08:00" level=debug msg="[DNS] www.tanggaoyun.com --> [] AAAA from tcp://1.1.1.1:53"
time="2024-09-20T13:32:43.4611307+08:00" level=info msg="[TCP] 127.0.0.1:14390 --> www.tanggaoyun.com:443 match DomainSuffix(tanggaoyun.com) using DIRECT"
time="2024-09-20T13:33:04.6344542+08:00" level=warning msg="Mihomo shutting down"
PS D:\Mihomo>
```
