### ISSUE TITLE
[Bug] provider 里的节点名替换无效

### ISSUE THREAD

**Issue by Brbrbr1995** [MetaCubeX/mihomo#1526]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

win 10

### Mihomo Version

1.18.8

### Configuration File

```yaml
proxy-providers:

  Abroad:
    type: http
    url: "http://192.168.1.14/Proxy/Abroad.yaml"
    path: ./Provider/Proxy/Abroad.yaml
    interval: 60
    health-check:
      enable: true
      interval: 60
      lazy: false
      url: "https://www.google.com/"
    override:
      udp: true
      additional-prefix: "🌐 : "
      proxy-name:
        - pattern: "CN"
          target: "大陆"
```

### Description

https://wiki.metacubex.one/config/proxy-providers/#overrideproxy-name
节点名替换无效?
![Screenshot 2024-09-20 204217](https://github.com/user-attachments/assets/e0daa1ee-e357-46cb-a26b-d0e3578e67e5)
![Screenshot 2024-09-20 204311](https://github.com/user-attachments/assets/8e339c6c-7c1d-4f33-9f0b-aa80196c92a0)

### Reproduction Steps

更改proxy-providers: 复写选项
reload config
前缀更改生效
节点名替换无效
