### ISSUE TITLE
[Bug] ip-based rule GEOIP doesn't forward dns query request into proxy

### ISSUE THREAD

**Issue by NamelessDev0000** [MetaCubeX/mihomo#1527]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

Windows 11 23H2 22631.4169

### Mihomo Version

Mihomo Meta v1.18.8 windows 386 with go1.23.0 Mon Sep  2 08:36:57 UTC 2024
Use tags: with_gvisor

### Configuration File

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090

dns:
  enable: true
  prefer-h3: true
  enhanced-mode: fake-ip
  default-nameserver:
  - 119.29.29.29
  nameserver:
  - https://doh.pub/dns-query
  proxy-server-nameserver:
  - https://doh.pub/dns-query
  fake-ip-range: 198.18.0.1/16
  fallback: []
  fake-ip-filter:
  - dns.msftncsi.com
  - www.msftncsi.com
  - www.msftconnecttest.com

tun:
  stack: gvisor
  device: Mihomo
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  strict-route: true
  mtu: 1500
  enable: true

proxies:
  - { name: "Telstra 01", ... }
proxy-groups:
  - name: Proxies
    type: select
    proxies:
      - Telstra 01
rules:
  - GEOIP,CN,DIRECT
  - MATCH,Proxies
```

### Description

In global mode, everything is fine. But when in rule mode, geoip goes strange.

Theoretically, every dns query in matching url agains ip-based rule will be forward to proxies, but when match against `geoip,cn`,
the query will be forward to `nameserver` defined dns server. It will cause dns leak.

### Reproduction Steps

1. Fill your proxy in `proxies` field
2. Start mihomo
3. Check dns leakage with this [website](https://browserleaks.com/dns).
