### ISSUE TITLE
[Bug] 订阅的 Base64 解码错误

### ISSUE THREAD

**Issue by Brbrbr1995** [MetaCubeX/mihomo#1530]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

10pro

### Mihomo Version

alpha 223eae0
### Configuration File

```yaml
log-level: debug

profile:
  store-selected: true
  store-fake-ip: false

allow-lan: true
bind-address: "*"

ipv6: false

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  mtu: 1480
  dns-hijack:
    - any:53
    - tcp://any:53

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: redir-host
  use-hosts: true
  prefer-h3: false
  respect-rules: true

  nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 1.0.0.1
    - 8.8.4.4
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 1.0.0.1
    - 8.8.4.4
  proxy-server-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 1.0.0.1
    - 8.8.4.4


mode: rule

find-process-mode: always

geodata-mode: false

geox-url:
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"

geodata-loader: standard

rules:
  - MATCH,选择

unified-delay: false
tcp-concurrent: true
keep-alive-interval: 10
global-client-fingerprint: chrome

proxy-providers:

  SSR_Base64:
    type: file
    path: ./Provider/SSR_Base64.txt
    health-check:
      enable: true
      url: "https://www.gstatic.com/generate_204"
      interval: 300
    override:
      additional-prefix: "SSR_Base64:"

  SSR_URL:
    type: file
    path: ./Provider/SSR_URL.txt
    health-check:
      enable: true
      url: "https://www.gstatic.com/generate_204"
      interval: 300
    override:
      additional-prefix: "SSR_URL:"

  SSR_URL_Fix:
    type: file
    path: ./Provider/SSR_URL_Fix.txt
    health-check:
      enable: true
      url: "https://www.gstatic.com/generate_204"
      interval: 300
    override:
      additional-prefix: "SSR_URL_Fix:"

proxies:
  - {name: 新加坡, server: tacm.ix2.edge.kunlunae.com, port: 50139, type: ssr, cipher: chacha20, password: mPQ5C9, protocol: auth_chain_a, obfs: tls1.2_ticket_auth, protocol-param: 40640910:PUgdMf, obfs-param: ""}
  - {name: 日本, server: tacm.ix2.edge.kunlunae.com, port: 50122, type: ssr, cipher: chacha20, password: mPQ5C9, protocol: auth_chain_a, obfs: tls1.2_ticket_auth, protocol-param: 40640910:PUgdMf, obfs-param: ""}

proxy-groups:

  - name: '选择'
    type: select
    disable-udp: false
    proxies:
    include-all-proxies: true
    include-all-providers: true
```

### Description

[Mihomo.zip](https://github.com/user-attachments/files/17088063/Mihomo.zip)
Base64 解码 BUG
url里的 "_" 要替换成 “/” 才能顺利导入
然而手动替换之后节点失效
如下图，同样的节点只有直接写在config里的能用

### Reproduction Steps

同样的节点只有直接写在config里的能用：
![Screenshot 2024-09-22 103730](https://github.com/user-attachments/assets/5cc92b56-06b1-4ae7-88b4-8a2da4068e91)

未手动替换的无法导入：
![Screenshot 2024-09-22 103819](https://github.com/user-attachments/assets/9e5a7c3f-ef8c-4b8e-ab77-3e634190bba4)

### Logs

```shell
time="2024-09-22T10:27:55.4284003+08:00" level=info msg="Start initial provider SSR_URL_Fix"
time="2024-09-22T10:27:55.4284003+08:00" level=info msg="Start initial provider SSR_Base64"
time="2024-09-22T10:27:55.4284003+08:00" level=info msg="Start initial provider SSR_URL"
time="2024-09-22T10:27:55.4296148+08:00" level=error msg="initial proxy provider SSR_Base64 error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `c3NyOi8...` into provider.ProxySchema, convert v2ray subscribe error: format invalid"
time="2024-09-22T10:27:55.4296148+08:00" level=error msg="initial proxy provider SSR_URL error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `ssr://d...` into provider.ProxySchema, convert v2ray subscribe error: format invalid"
```
