### ISSUE TITLE
[Bug] ipv6解析行为与预期不符

### ISSUE THREAD

**Issue by PDxtXHd** [MetaCubeX/mihomo#1531]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

Windows 10

### Mihomo Version

Mihomo Meta alpha-223eae0 windows amd64 with go1.23.1 Sat Sep 21 16:27:48 UTC 2024
Use tags: with_gvisor

### Configuration File

```yaml
dns:
  enable: true
  ipv6: false
  respect-rules: false
  prefer-h3: false
  use-hosts: true
  use-system-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
    - "rule-set:fakeip-filter"
  nameserver:
    - "https://208.67.222.222/dns-query"
  default-nameserver:
    - tls://1.12.12.12
    - tls://223.5.5.5
  proxy-server-nameserver:
    - "https://9.9.9.10/dns-query"
  nameserver-policy:
    "geosite:cn,private":
      - system
    "geosite:geolocation-!cn":
      - "https://dns.google/dns-query#h3=true&RULES"
```

### Description

在dns配置部分设置ipv6: false后仍然返回AAAA解析，而文档中描述“是否解析 IPV6, 如为 false, 则回应 AAAA 的空解析”

### Reproduction Steps

找一个在rules中命中DIRECT的双栈域名并访问。
我这里因为引用了https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/cn.mrs这个规则，而crl.pki.goog被错误地放在里面，因此可以通过这个域名触发。
由于在nameserver-policy中配置了geosite:geolocation-!cn走google doh，因而触发了本地解析后交给dns.google解析。预期应该会返回空的AAAA记录，实际上同时返回了A记录和AAAA记录。

### Logs

```shell
time="2024-09-22T10:16:54.5519129+08:00" level=debug msg="[DNS] resolve crl.pki.goog A from https://dns.google:443/dns-query"
time="2024-09-22T10:16:54.5519129+08:00" level=debug msg="[DNS] resolve crl.pki.goog AAAA from https://dns.google:443/dns-query"
time="2024-09-22T10:16:54.8722725+08:00" level=debug msg="[DNS] crl.pki.goog --> [142.251.40.131] A from https://dns.google:443/dns-query"
time="2024-09-22T10:16:54.8750539+08:00" level=debug msg="[DNS] crl.pki.goog --> [2607:f8b0:4006:820::2003] AAAA from https://dns.google:443/dns-query"
time="2024-09-22T10:16:57.5990978+08:00" level=debug msg="[Rule] use default rules"
time="2024-09-22T10:16:57.6008607+08:00" level=debug msg="[DNS] cache hit crl.pki.goog --> [142.251.40.131] A, expire at 2024-09-22 10:18:09"
time="2024-09-22T10:16:57.6008607+08:00" level=debug msg="[DNS] cache hit crl.pki.goog --> [2607:f8b0:4006:820::2003] AAAA, expire at 2024-09-22 10:18:09"
time="2024-09-22T10:16:58.5813662+08:00" level=debug msg="[Rule] use default rules"
time="2024-09-22T10:16:59.5517388+08:00" level=warning msg="[TCP] dial DIRECT (match RuleSet/cn) 127.0.0.1:52501(chrome.exe) --> crl.pki.goog:443 error: dial tcp 142.251.40.131:443: i/o timeout\ndial tcp [2607:f8b0:4006:820::2003]:443: i/o timeout"
time="2024-09-22T10:17:02.601537+08:00" level=warning msg="[TCP] dial DIRECT (match RuleSet/cn) 127.0.0.1:52504(chrome.exe) --> crl.pki.goog:80 error: dial tcp [2607:f8b0:4006:820::2003]:80: i/o timeout\ndial tcp 142.251.40.131:80: i/o timeout"
time="2024-09-22T10:17:04.090543+08:00" level=warning msg="Mihomo shutting down"
```
