### ISSUE TITLE
[Bug] 用dns.twnic.tw/dns-query这个dns，Mihomo就会报dns resolve failed: context deadline exceeded，然后能直连打开的网站就打不开了，一删除这个dns就恢复了

### ISSUE THREAD

**Issue by WeberLeah** [MetaCubeX/mihomo#1539]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

win10 22H2

### Mihomo Version

1.18.7

### Configuration File

```yaml
mixed-port: 7890
mode: rule
allow-lan: false
ipv6: true
unified-delay: true
tcp-concurrent: true
log-level: silent
bind-address: "*"
external-controller: 0.0.0.0:9090
external-ui: "/usr/share/openclash/ui"
secret: WeberLeah
keep-alive-interval: 3600
find-process-mode: 'strict'
global-client-fingerprint: chrome
authentication:
- Clash:WeberLeah
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  skip-domain:
  - Mijia Cloud
  - "+.push.apple.com"
  sniff:
    TLS:
      ports:
      - 443
      - 8443
    QUIC:
      ports:
      - 443
      - 8443
    HTTP:
      ports:
      - 80
      - 8080-8880
      override-destination: true
experimental:
  sniff-tls-sni: true
geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
skip-auth-prefixes:
- 127.0.0.1/8
- "::1/128"
- 10.0.0.0/8
- 192.168.0.0/16
- 172.16.0.0/12
dns:
  enable: true
  prefer-h3: false
  use-hosts: true
  use-system-hosts: true
  respect-rules: true
  listen: 0.0.0.0:7874
  ipv6: true
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - "*"
  - "+.lan"
  - "+.local"
  - "+.market.xiaomi.com"
  nameserver-policy:
    "+.arpa": 10.0.0.1
    rule-set:China:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  fallback:
  - https://public.dns.iij.jp/dns-query
  - https://dns.twnic.tw/dns-query
  proxy-server-nameserver:
  - https://120.53.53.53/dns-query
  - https://223.5.5.5/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
    - gfw
    ipcidr:
    - 240.0.0.0/4
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
proxy-providers:
  All:
    type: http
    path: "./proxy_provider/All.yaml"
    url: 
    interval: 3600
    health-check:
      enable: true
      url: http://www.google.com/generate_204
      interval: 3600
proxy-groups:
- name: Proxy
  type: select
  disable-udp: true
  use:
  - All
- name: Final
  type: select
  disable-udp: true
  proxies:
  - DIRECT
  - Proxy
rule-providers:
  Advertise:
    type: http
    behavior: classical
    path: "./rule_provider/Advertise.yaml"
    format: yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml
    interval: 86400
  Proxy:
    type: http
    behavior: classical
    path: "./rule_provider/Proxy.yaml"
    format: yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Classical.yaml
    interval: 86400
  China:
    type: http
    behavior: classical
    path: "./rule_provider/China.yaml"
    format: yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Classical.yaml
    interval: 86400
rules:
- RULE-SET,Advertise,REJECT
- RULE-SET,Proxy,Proxy
- RULE-SET,China,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Final
```

### Description

用dns.twnic.tw/dns-query这个dns，Mihomo就会报dns resolve failed: context deadline exceeded，然后能直连打开的网站就打不开了，一删除这个dns就恢复了

### Reproduction Steps

 www.hifini.com走的的兜底策略，都死策略选择直连
 
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  fallback:
  - https://public.dns.iij.jp/dns-query
  - https://dns.twnic.tw/dns-query
  proxy-server-nameserver:
  - https://120.53.53.53/dns-query
  - https://223.5.5.5/dns-query
  使用这个就打不开www.hifini.com网站

    nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  fallback:
  - https://public.dns.iij.jp/dns-query
  - 223.5.5.5
  proxy-server-nameserver:
  - https://120.53.53.53/dns-query
  - https://223.5.5.5/dns-query
    使用这个就能打开www.hifini.com网站

### Logs

```shell
09-24 17:26:45WARNING
[TCP] dial Final (match Match/) 127.0.0.1:3665(msedge.exe) --> www.hifini.com:443 error: dns resolve failed: context deadline exceeded
09-24 17:26:55WARNING
[TCP] dial Final (match Match/) 127.0.0.1:3689(msedge.exe) --> www.hifini.com:443 error: dns resolve failed: context deadline exceeded
09-24 17:27:06WARNING
[TCP] dial Final (match Match/) 127.0.0.1:3718(msedge.exe) --> www.hifini.com:443 error: dns resolve failed: context deadline exceeded
09-24 17:27:16WARNING
[TCP] dial Final (match Match/) 127.0.0.1:3732(msedge.exe) --> www.hifini.com:443 error: dns resolve failed: context deadline exceeded
```
