### ISSUE TITLE
[Bug] listeners 规则下监听的端口对于 skip-auth-prefixes 的验证过滤不生效

### ISSUE THREAD

**Issue by shang-he** [MetaCubeX/mihomo#1549]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

23H2 22631.4169

### Mihomo Version

[v1.18.8](https://github.com/MetaCubeX/mihomo/releases/tag/v1.18.8)

### Configuration File

```yaml
# DO NOT EDIT - Generated by GUI.for.Clash
mode: rule
ipv6: false
mixed-port: 1080
allow-lan: true
log-level: info
interface-name: ""
port: 0
socks-port: 0
secret: ID_5ct1755o
external-controller: 127.0.0.1:20113
external-ui: ""
keep-alive-interval: 30
find-process-mode: strict
external-controller-tls: ""
external-ui-name: ""
external-ui-url: ""
unified-delay: true
tcp-concurrent: true
authentication:
  - aa:bb
skip-auth-prefixes:
  - 127.0.0.1/8
  - ::1/128
tls:
  certificate: ""
  private-key: ""
global-client-fingerprint: chrome
geodata-mode: true
geo-auto-update: false
geo-update-interval: 24
geodata-loader: standard
geosite-matcher: mph
geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb
  asn: https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
global-ua: chrome
profile:
  store-selected: true
  store-fake-ip: true
lan-allowed-ips:
  - 0.0.0.0/0
  - ::/0
lan-disallowed-ips: []
tun:
  enable: false
  stack: Mixed
  auto-route: true
  route-address:
    - 0.0.0.0/1
    - 128.0.0.0/1
    - ::/1
    - 8000::/1
  auto-detect-interface: true
  dns-hijack:
    - any:53
  device: utun_clash
  mtu: 9000
  strict-route: true
  endpoint-independent-nat: false
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  use-hosts: false
  use-system-hosts: true
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver-policy: {}
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - +.msftconnecttest.com
    - +.msftncsi.com
    - +.xboxlive.com
    - msftconnecttest.com
    - xbox.*.microsoft.com
    - "*.battlenet.com.cn"
    - "*.battlenet.com"
    - "*.blzstatic.cn"
    - "*.battle.net"
  fallback:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
  prefer-h3: false
hosts: {}
proxies: []
proxy-groups:
  - name: Proxy
    type: select
    filter: ""
    exclude-filter: ""
    hidden: false
    icon: ""
    include-all-proxies: true
    disable-udp: false
rules:
  - MATCH,Proxy
listeners:
  - name: proxy_all
    type: mixed
    port: 1085
    listen: 0.0.0.0
    udp: true
    proxy: Proxy
```

### Description

在 listeners 中配置入站 mixed 类型的代理，用户名继承全局配置。在 v1.18.7 中遵循 skip-auth-prefixes 规则时是不需要验证账户的，在 v1.18.8 中则需要验证账户才能使用

### Reproduction Steps

使用以上配置分别启动 v1.18.7 客户端和 v1.18.8 客户端连接 1085 端口，期望的情况是在使用符合 skip-auth-prefixes  条件时不需要验证账户，其他情况下验证账户
