### ISSUE TITLE
[Bug] VMESS gRPC 链式代理负载均衡不会回收TCP连接

### ISSUE THREAD

**Issue by Netrvin** [MetaCubeX/mihomo#1550]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

Linux Kwrt 6.6.48 #0 SMP Thu Sep  5 09:52:21 2024 x86_64 GNU/Linux

### Mihomo Version

Mihomo Meta alpha-e33d4a4 linux amd64 with go1.21.13 2024-09-16T08:21:24+00:00
Use tags: with_gvisor

### Configuration File

```yaml
{
    "proxy-groups": [
        {
            "name": "代理节点",
            "proxies": [
                "落地节点"
            ],
            "type": "select"
        },
        {
            "name": "落地节点",
            "proxies": [
                "落地1",
                "落地2",
                "DIRECT"
            ],
            "type": "select"
        },
        {
            "name": "负载均衡",
            "proxies": [
                "[SS]负载均衡1",
                "[tr]负载均衡2",
                "[v2grpc]负载均衡3",
                "[v2grpc]负载均衡4"
            ],
            "interval": 300,
            "timeout": 800,
            "type": "load-balance",
            "strategy": "round-robin",
            "max-failed-times": 3,
            "url": "http://www.gstatic.com/generate_204"
        }
    ],
    "rule-providers": {},
    "rules": [
        "GEOIP,CN,DIRECT",
        "MATCH,代理节点"
    ],
    "proxies": [
        {
            "cipher": "aes-128-gcm",
            "name": "[SS]负载均衡1",
            "password": "xxx",
            "plugin": "obfs",
            "plugin-opts": {
                "host": "xxx.com",
                "mode": "http"
            },
            "port": "1234",
            "server": "xxx.xxx",
            "type": "ss",
            "udp": true
        },
        {
            "multiport": "1234-5678",
            "name": "[tr]负载均衡2",
            "password": "xxx",
            "server": "xxx.xxx",
            "type": "trojan",
            "alpn": [
                "h2",
                "http/1.1"
            ],
            "port": 1234,
            "sni": "xxx.com"
        },
        {
            "alterId": "0",
            "cipher": "auto",
            "grpc-opts": {
                "grpc-service-name": "xxx"
            },
            "name": "[v2grpc]负载均衡3",
            "network": "grpc",
            "port": "1234",
            "server": "xxx.xxx",
            "tls": true,
            "type": "vmess",
            "udp": true,
            "uuid": "xxx",
            "alpn": [
                "http/1.1"
            ],
            "servername": "xxx.com"
        },
        {
            "alterId": "0",
            "cipher": "auto",
            "grpc-opts": {
                "grpc-service-name": "xxx"
            },
            "name": "[v2grpc]负载均衡4",
            "network": "grpc",
            "port": "1234",
            "server": "xxx.xxx",
            "tls": true,
            "type": "vmess",
            "udp": true,
            "uuid": "xxx",
            "alpn": [
                "http/1.1"
            ],
            "servername": "xxx.com"
        },
        {
            "name": "落地1",
            "type": "ss",
            "server": "xxx.xxx",
            "password": "xxx",
            "cipher": "aes-128-gcm",
            "udp": true,
            "port": "1234",
            "dialer-proxy": "负载均衡"
        },
        {
            "name": "落地2",
            "type": "ss",
            "server": "xxx.xxx",
            "password": "xxx",
            "cipher": "aes-128-gcm",
            "udp": true,
            "port": "1234",
            "dialer-proxy": "负载均衡"
        }
    ],
    "ipv6": true,
    "keep-alive-interval": 500
}
```

### Description

使用DialerProxy或relay，进行如下链路的代理，观察到系统中存在上千由mihomo创建的ESTABLISHED状态的TCP连接，99%的目标连接地址和端口均为VMESS gRPC协议的节点，且这些连接会一直保持并不断增加，直至影响正常的代理功能：

电脑<->软路由 Kwrt（luci-app-mihomo）<->负载均衡代理组<->落地节点<->境外服务

期望：连接数会保持在够用的程度，会对不必要的连接进行关闭

### Reproduction Steps

如上
