### ISSUE TITLE
[Feature] Add a type of proxy-group or add a property of proxies. alternative solution for resolving UDP over TCP/Save tcp traffic

### ISSUE THREAD

**Issue by MNDIA** [MetaCubeX/mihomo#1573]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

问题如何影响到你？
Need a fallback policy for [proxies known no-udp] to allow udp to another [proxy with udp]
实现什么功能？
Add a type of proxy-group to separate udp and tcp streams to two different [proxies/proxy-groups]
```yaml
proxy-groups:
- name: US1
  type: separate
  proxies:
  - US1-NoUDP
  - US1-Normal
```
There are two [proxies/proxy-groups], one does not support udp "US1-NoUDP", one supports udp "US1-Normal", they should be treated as a type of [proxy-group] "US1".
When "US1" is selected by the parent proxy-group(select), tcp enters the proxy US1-NoUDP, udp enters the proxy US1-Normal.

Another better realization
```yaml
proxies:
- name: "US1-NoUDP"
- udp: false
- udp-redirect:  Groups-with-udp # Like dialer-proxy
  ...

- name: "US1-Normal"
- udp: true
  ...

proxy-groups:
- name: Groups-with-udp
  type: select
  proxies:
  - US1-Normal
```

目前 Mihomo Core 的行为是什麽？
The logic ability to distinguish between udp and tcp only exists in /rules/#network
```yaml
rules:
-  NETWORK,udp,US1-NoUDP
-  NETWORK,tcp,US1-Normal
```

The ability to switch nodes exists only in proxy-groups/select/
```yaml
proxy-groups:
- name: Proxy
  type: select
  proxies:
  - US1
  - US2
```
Rules are dead and cannot be dynamically selected as sub-rulefs
The proxy-group is live, but cannot contain sub-rules
Cannot fulfill both:
Being able to be dynamically selected and having logical processing ability

It's similar
```yaml
- SUB-RULE,(NETWORK,tcp),proxy-group-name 
```
but the father-son relationship is reversed.
It is a live node from a dead sub-rule.
Requirement is to select dead sub-rules from live nodes：

The whole process with tcp and udp streaming logic cannot be able to be selected as a proxy.
Logical processing only exists in the rules without selected function. 
Existing functionality doesn't do that "Being able to be dynamically selected and having logical processing ability"

### Possible Solution

```yaml
proxies:
- name: "US1-NoUDP"
- udp: false
- udp-redirect:  Groups-with-udp # Like dialer-proxy
  ...

- name: "US1-Normal"
- udp: true
  ...

proxy-groups:
- name: Groups-with-udp
  type: select
  proxies:
  - US1-Normal
```
