### ISSUE TITLE
[Bug] 认证绕过地址不生效

### ISSUE THREAD

**Issue by yixiuge301** [MetaCubeX/mihomo#1577]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

Windows 10 Pro 22H2

### Mihomo Version

![image](https://github.com/user-attachments/assets/bee1f580-fae6-4445-b7f1-dbe0dce1d325)
![image](https://github.com/user-attachments/assets/ac80e31d-fc95-4ff5-a189-d41ef7b90c8a)

### Configuration File

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
authentication:
- proxy:clash
skip-auth-prefixes:
- 127.0.0.1/8
- ::1/128
proxies:
  - {name: 香港, server: 120.232.16.70, port: 34701, type: ss, cipher: aes-128-gcm, password: 86beb7e7-5405-4832-9338-d4188d15e502, udp: true}
proxy-groups:
  - name: 🔰 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - 🎯 全球直连
      - 香港
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 香港
  - name: 🎥 NETFLIX
    type: select
    proxies:
      - 🔰 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 香港
  - name: ⛔️ 广告拦截
    type: select
    proxies:
      - 🛑 全球拦截
      - 🎯 全球直连
      - 🔰 节点选择
  - name: 🚫 运营劫持
    type: select
    proxies:
      - 🛑 全球拦截
      - 🎯 全球直连
      - 🔰 节点选择
  - name: 🌍 国外媒体
    type: select
    proxies:
      - 🔰 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 香港
  - name: 🌏 国内媒体
    type: select
    proxies:
      - 🎯 全球直连
      - 香港
      - 🔰 节点选择
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - 🎯 全球直连
      - 🔰 节点选择
      - 香港
  - name: 📲 电报信息
    type: select
    proxies:
      - 🔰 节点选择
      - 🎯 全球直连
      - 香港
  - name: 🍎 苹果服务
    type: select
    proxies:
      - 🔰 节点选择
      - 🎯 全球直连
      - ♻️ 自动选择
      - 香港
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🔰 节点选择
      - 🎯 全球直连
      - ♻️ 自动选择
      - 香港
rules:
  - DOMAIN-SUFFIX,local,🎯 全球直连
  - IP-CIDR,192.168.0.0/16,🎯 全球直连,no-resolve
  - IP-CIDR,10.0.0.0/8,🎯 全球直连,no-resolve



[profile.yaml.txt](https://github.com/user-attachments/files/17301273/profile.yaml.txt)
```

### Description

![image](https://github.com/user-attachments/assets/4cb512f2-1aa9-4b7f-8541-4454c5feea69)

![image](https://github.com/user-attachments/assets/ab025463-44af-4a0a-b889-440f320a022a)

### Reproduction Steps

是我写的配置不对，还是我对这个认证理解不对

我开启了 允许局域网代理，但想仅允许一部分 ip 免密使用。配置了 skip-auth-prefixes: 好像不起作用，本机还是弹要认证。
