### ISSUE TITLE
[Bug] 在windows的wsl里启动后，连接代理后，访问不了国内网站

### ISSUE THREAD

**Issue by GostGrimmy** [MetaCubeX/mihomo#1583]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [X] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Windows

### 系统版本

win10 wsl debian

### Mihomo 版本

Mihomo Meta alpha-fb4d3c4 linux amd64 with go1.23.1 Tue Sep 17 04:04:42 UTC 2024

### 配置文件

```yaml
mixed-port: 7900
allow-lan: true
mode: rule
log-level: info
external-controller: '0.0.0.0:10000'
secret: ''
dns:
  enable: false
  ipv6: true
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.168.1.0/16
  fake-ip-filter:
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
  use-hosts: true
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
  fallback-filter: 
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
      - +.githubusercontent.com
```

## 问题 
1. 本机windows连接wsl，postman用代理打开百度报错,chrome用proxy-switchyomega打开百度报错，外网没问题
```
Error: Client network socket disconnected before secure TLS connection was established

```
2. 同样配置，另外电脑(ubuntu)开启clash服务,此电脑连没有问题
3. 局域网ip 192.168.1.0
4. 经常使用过poxifier软件
5. 日志显示正常
```
time="2024-10-12T15:24:24.318823733Z" level=info msg="[TCP] 172.17.0.1:42328 --> static.doubleclick.net:443 match GeoIP(cn) using DIRECT"
time="2024-10-12T15:24:24.322137088Z" level=info msg="[TCP] 172.17.0.1:42362 --> www.baidu.com:443 match GeoIP(cn) using DIRECT"
time="2024-10-12T15:24:24.322340461Z" level=info msg="[TCP] 172.17.0.1:42336 --> api.theblockbeats.info:443 match GeoIP(cn) using DIRECT"
time="2024-10-12T15:24:24.328982232Z" level=info msg="[TCP] 172.17.0.1:42366 --> www.baidu.com:443 match GeoIP(cn) using DIRECT"
time="2024-10-12T15:24:24.334402186Z" level=info msg="[TCP] 172.17.0.1:42388 --> www.baidu.com:443 match GeoIP(cn) using DIRECT"
```

### 重现方式

使用window 安装wsl,使用上面配置，连接服务，访问百度。无法访问
