### ISSUE TITLE
[Bug] 1.18.7开始，include-all-proxies 导致节点排序错误

### ISSUE THREAD

**Issue by leic4u** [MetaCubeX/mihomo#1591]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Windows

### 系统版本

Windows 11 24H2

### Mihomo 版本

Mihomo Meta v1.18.7 windows amd64 with go1.22.5 Sun Jul 28 05:49:06 UTC 2024
Use tags: with_gvisor

Mihomo Meta v1.18.9 windows amd64 with go1.23.1 Sun Sep 29 09:46:42 UTC 2024
Use tags: with_gvisor

Mihomo Meta alpha-ca3f1eb windows amd64 with go1.23.2 Sat Oct 12 00:31:56 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
proxies:

  - name: 🇯🇵 S3-3
    type: hysteria2
    server: s3.xxx.org
    port: 12345
    password: xxxxxxxx
    up: 120 Mbps
    down: 500 Mbps
    #ip-version: ipv6-prefer

  - name: 🇯🇵 S3-2
    type: hysteria2
    server: hy.xxxx.org
    port: 12346
    password: xxxxxxxxxxx
    up: 120 Mbps
    down: 500 Mbps
    #ip-version: ipv6-prefer

  - name: 🇰🇷 S2
    type: hysteria2
    server: s2.xxxxxx.org
    port: 12345
    password: xxxxxxxx
    up: 120 Mbps
    down: 500 Mbps
    #ip-version: ipv6-prefer

  - name: 🇰🇷 R2
    type: hysteria2
    server: hy.xxxx.xyz
    port: 443
    password: xxxxxxxx
    up: 120 Mbps
    down: 500 Mbps
    #ip-version: ipv6-prefer

  - name: 🇯🇵 S1
    type: hysteria2
    server: s1.xxx.org
    port: 12345
    password: xxxxxxxxxx
    up: 120 Mbps
    down: 500 Mbps
    #ip-version: ipv6-prefer

  - name: 🇯🇵 S4
    type: hysteria2
    server: s4.xxxxxx.org
    port: 12345
    password: xxxxxxxxxx
    up: 120 Mbps
    down: 500 Mbps
    #ip-version: ipv6-prefer

  - vmess节点1TLS
  - vless节点1TLS

  - vmess节点2TLS
  - vless节点2TLS

  ...

  - vmess节点9TLS
  - vless节点9TLS

  - vmess节点1
  - vmess节点2
  ...
  - vmess节点9

proxy-groups:
  - name: 👆 手动切换
    type: select
    icon: https://ghp.ci/raw.githubusercontent.com/leic4u/Qure/master/IconSet/Color/Click.png
    include-all-proxies: true
    use:
      - a-sub-provider
    url: http://www.apple.com/library/test/success.html
    interval: 300
```

### 描述

在 `v1.18.6` 中，`👆 手动切换`策略组中的节点排序正确，即按照 `S3-3, S3-2, S2, R2, S1, S4, 9组vmessTLS+vlessTLS, 9个vmess, a-sub-provider` 的顺序进行排列。

升级至 `v1.18.7`，`v1.18.8`，`v1.18.9` 之后，均无法正确排序，但顺序是固定的，按照 `S1, S3-2, S3-3, 9个vlessTLS, 9组vmess+vmessTLS, S4, R2, S2, a-sub-provider`的顺序进行排列。

自己观察了一下，没看出来是用什么规则进行了重排，只看得出来是同协议的节点排在一起去了（provider 的节点排序正常，看起来没有参与重新排序）。

看了下 changelog 的内容，但猜测有可能是 `v1.18.7` 这个更新导致的。
 https://github.com/MetaCubeX/mihomo/commit/0d90a936455b0e373f38b8b239614b5337c17283 chore: sort proxies and providers by name before include all by @wwqgtxx 

### 重现方式

使用以上配置文件，使用 `include-all-proxies: true` 将节点加入策略组，即可出现。
