### ISSUE TITLE
[Bug]  使用如下配置，会出现DNS出口泄漏，

### ISSUE THREAD

**Issue by Rem1x-2019** [MetaCubeX/mihomo#1594]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

ImmortalWrt 23.05.4 r28061-399f9a1db3 / LuCI openwrt-23.05 branch git-24.265.44782-0ff45d8

### Mihomo Version

OpenWrt-mihomo
核心版本 alpha-ca3f1eb
插件版本1.8.7-1

### Configuration File

```yaml
port: 8080
socks-port: 1080
allow-lan: true
mode: rule
log-level: warning
external-controller: 0.0.0.0:9090
dns:
  enabled: true
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  respect-rules: true
  prefer-h3: true
  ipv6: false
  use-system-hosts: false
  use-hosts: false
  direct-nameserver:
    - 127.0.0.1:53
  fake-ip-filter-mode: whitelist
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  default-nameserver:
    - 127.0.0.1:53
  proxy-server-nameserver:
    - tls://8.8.8.8
    - tls://1.1.1.1
  nameserver:
    - 127.0.0.1:53
  fallback:
    - tls://8.8.8.8
    - tls://1.1.1.1
  nameserver-policy:
    geosite:cn,private:
      - 127.0.0.1:53
    geosite:geolocation-!cn:
      - https://dns.google/dns-query
      - tls://1.1.1.1
proxies:
  - {name: "\U0001F1ED\U0001F1F0 HK", server: *}
  - {name: "\U0001F1F0\U0001F1F7 KR", server: *}
  - {name: "\U0001F1F0\U0001F1F7 KR-ARM", server: *}
  - {name: "\U0001F1F0\U0001F1F7 KR-ARM2", server: *}
proxy-groups:
  - name: proxy
    type: select
    proxies:
      - "DIRECT"
      - "\U0001F1ED\U0001F1F0 HK"
      - "\U0001F1F0\U0001F1F7 KR"
      - "\U0001F1F0\U0001F1F7 KR-ARM"
      - "\U0001F1F0\U0001F1F7 KR-ARM2"
  - name: video
    type: select
    proxies:
      - "DIRECT"
      - "\U0001F1ED\U0001F1F0 HK"
      - "\U0001F1F0\U0001F1F7 KR"
      - "\U0001F1F0\U0001F1F7 KR-ARM"
      - "\U0001F1F0\U0001F1F7 KR-ARM2"
rules:
  - GEOIP,private,DIRECT,no-resolve
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,win-update,DIRECT
  - GEOIP,cn,DIRECT
  - GEOSITE,youtube,video
  - GEOSITE,twitch,video
  - GEOSITE,telegram,video
  - MATCH,proxy
find-process-mode: off
keep-alive-idle: 600
keep-alive-interval: 15
ipv6: false
external-ui: ui
external-ui-name: metacubexd
external-ui-url: https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
secret: 816250
profile:
  store-selected: true
  store-fake-ip: false
mixed-port: 7890
redir-port: 7891
tproxy-port: 7892
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
tun:
  enable: true
  stack: mixed
  device: mihomo
  mtu: 9000
  gso: true
  gso-max-size: 65536
  endpoint-independent-nat: false
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false
  dns-hijack: []
geodata-mode: true
geodata-loader: standard
geox-url:
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  asn: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb
geo-auto-update: false
geo-update-interval: 24
authentication:
  - mihomo:816250
```

### Description

DNS国内走的内网的ADG，国外8.8.8.8
按照上面的配置，白名单模式，国内直连，其他代理，
一些google，youtube什么的访问正常，IP也显示国外，但是DNS出口显示的是国内
而且有部分CF泛播和GOOGLE泛播没有走代理，不知道为什么。。
![image](https://github.com/user-attachments/assets/cec33a3c-f105-4156-9b4a-abe748e45ebe)

### Reproduction Steps

使用我提供的配置文件。。。
