### ISSUE TITLE
[Feature] Add priority determination to nameserver-policy.

### ISSUE THREAD

**Issue by MNDIA** [MetaCubeX/mihomo#1598]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

For this simple example.
```yaml
  nameserver-policy: 
    "rule-set:category-ads-all_classical": rcode://success
    "+.cn": *cn_dns
    #......
    "+.us": *us_dns
    "+.uk": *uk_dns

    "rule-set:geolocation-!cn": 
      *international_dns
```
这个问题如何影响到你？
The nameserver-policy is a set dictionary is unordered, and when encountering a domain name that together belongs to
{ 'rule-set:category-ads-all_classical' , '+.us' , 'rule-set:geolocation-!cn' } 
there is no top-to-bottom match order, which can cause to happen:  
for a '+.us' URL,
If +.us takes precedence over rule-set, then unblocked ads.
If rule-set takes precedence over +.us, then US matches don't work anymore
(There are more complex implications at the end)

你想实现什么功能？
Add priority determination inside current nameserver-policy.
For example, Arrays are sequential, just like rules
```yaml
nameserver-policy: 
  - {policy: "rule-set:category-ads-all_classical", use: rcode://success}:
  - {policy: "+.cn", use: *cn_dns}:
  #......
  - {policy: "+.us", use: *us_dns}:
  - {policy: "+.uk", use: *uk_dns}:
  - {policy: "rule-set:geolocation-!cn", use: *international_dns}:
```
目前 Mihomo Core 的行为是什麽
The set dictionary of nameserver-policy is not in order, and match priority may depend on the level of detail of the domain wildcard, rather than the policy order. 
Currently the only order for DNS resolution is [direct-nameserver, nameserver-policy, nameserver, fallback]. 
The simple example above is used to illustrate the problem and can be solved by the following as a temporary alternative
```yaml
  nameserver-policy: 
    "rule-set:category-ads-all_classical": rcode://success
    "+.cn": *cn_dns
    #......
    "+.us": *us_dns
    "+.uk": *uk_dns

    # "rule-set:geolocation-!cn": 
    #   *international_dns
  nameserver: 
    *cn_dns
  fallback: 
    *international_dns
  fallback-filter:
    geoip: true 
    geoip-code: CN 
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
```
But rule-set:geolocation-!cn seems to work better, no omissions
But fallback is limited and geosite is about to be deprecated,  can't use ruleset.
But four [direct-nameserver, nameserver-policy, nameserver, fallback] cannot express complex DNS logic.

In complex DNS logic policy has **intersection**, especially the logic appears to be application-oriented set, the following logic example in [direct-nameserver, nameserver-policy, nameserver, fallback] can not be expressed:
```yaml
  nameserver-policy:
    "rule-set:category-ads-all_classical": rcode://success 
    "rule-set:bilibili_domain": *bilibili_dns 
    "rule-set:domestic_classical": *cn_dns
    "rule-set:download_domain,bing_domain,microsoft_domain,biliintl_domain,ehentai_domain,github_domain,twitter_domain,instagram_domain,facebook_domain,youtube_domain,google_domain,apple_domain,telegram_domain,discord_domain,reddit_domain,netflix_domain,bahamut_domain,spotify_domain,pixiv_domain,steam_domain,epic_domain,openai_domain":
      *international_dns

    "+.cn": *cn_dns
    "+.us": *us_dns
    "+.uk": *uk_dns
    "+.de,+.eu": *de_dns
    "+.jp,+.nico": *jp_dns
    "+.hk": *hk_dns
    #...

    "rule-set:international_classical": 
      *international_dns
    "+.org,+.io,+.dev":
      *international_dns
    "rule-set:geolocation-!cn":
      *international_dns
```
Assuming that bilibili.com appears in bilibili_domain, domestic_classical, (even category-ads-all_classical) at the same time, the resolution priority is all about luck

### Possible Solution

```yaml
nameserver-policy: 
  - {policy: "rule-set:category-ads-all_classical", use: rcode://success}
  - {policy: "rule-set:bilibili_domain", use: *bilibili_dns}
  - {policy: "rule-set:domestic_classical", use: *cn_dns}
  - policy: "rule-set:download_domain,bing_domain,microsoft_domain,biliintl_domain,ehentai_domain,github_domain,twitter_domain,instagram_domain,facebook_domain,youtube_domain,google_domain,apple_domain,telegram_domain,discord_domain,reddit_domain,netflix_domain,bahamut_domain,spotify_domain,pixiv_domain,steam_domain,epic_domain,openai_domain"
    use: *international_dns
  - {policy: "+.cn", use: *cn_dns}
  - {policy: "+.us", use: *us_dns}
  - {policy: "+.uk", use: *uk_dns}
  - {policy: "+.de,+.eu", use: *de_dns}
  - {policy: "+.jp,+.nico", use: *jp_dns}
  - {policy: "+.hk", use: *hk_dns}
  #......
  - {policy: "rule-set:international_classical", use: *international_dns}
  - {policy: "+.org,+.io,+.dev", use: *international_dns}
  - {policy: "rule-set:geolocation-!cn", use: *international_dns}
```
