### ISSUE TITLE
[Not a bug technically] tun模式无法完全控制qbittorrent的路由，需要手动设置后者

### ISSUE THREAD

**Issue by Aniark** [MetaCubeX/mihomo#1605]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [X] 我是中文用户，而非其他语言用户
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [ ] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [X] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

7 sp1 64bit

### Mihomo 版本

```
Mihomo Meta alpha-3e966e8 windows amd64 with go1.20.14 Mon Oct 21 01:46:46 UTC 2024
Use tags: with_gvisor
```

### 配置文件

```yaml
mixed-port: 7890
bind-address: '*'
allow-lan: false
mode: rule
log-level: debug
external-controller: 0.0.0.0:9090
find-process-mode: strict
tcp-concurrent: false
ipv6: false

geodata-mode: false

keep-alive-interval: 15

profile:
    store-selected: false
    store-fake-ip: true

sniffer:
  enable: false
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: false
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]


tun:
    enable: true
    stack: system
    dns-hijack:
        - any:53
    auto-route: true
    auto-detect-interface: true
    endpoint-independent-nat: false

dns:
    enable: true
    prefer-h3: false
    ipv6: false
    listen: 0.0.0.0:53
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter-mode: blacklist
    fake-ip-filter:
      - '*'
    default-nameserver:
      - system
    nameserver:
      - system
    

proxies:
  - name: "proxy"
    type: vless
    server: server
    port: 443
    udp: true
    uuid: uuid
    tls: true
    sni: sni
    servername: servername
    client-fingerprint: ios
    skip-cert-verify: true
    network: tcp
    smux:
        enabled: false

rules:
    - MATCH,proxy
```

### 描述

tun模式，流量均走代理，观察到qbittorrent有部分流量走的境内，mihomo日志却没有相关信息，遂检查qbittorrent日志，发现日志内出现了境内ip，如下，敏感信息已手动打码
```
检测到外部 IP。IP：“境内ipv4”
检测到外部 IP。IP：“代理ip”
检测到外部 IP。IP：“境内ipv6”
检测到外部 IP。IP：“境内ipv6”
```
进一步检查qbittorrent设置，发现该软件默认设置会用到所有网络接口，在我的使用场景中是`Meta`和`本地连接 4`，如下

此为qbittorren默认t设置
![image](https://github.com/user-attachments/assets/791c9156-e3ce-4ab9-b47c-00a853fc0f10)

此为我的所有网络接口
![image](https://github.com/user-attachments/assets/a8409303-5058-4e80-a2c6-92a3db6d8d58)

解决方案：手动切换qbittorrent网络接口为`Meta`，如下
![image](https://github.com/user-attachments/assets/74fb793f-2afe-4d41-8940-8bbdc871dd51)

再次检查qbittorrent日志，已经没有境内ip，仅有代理ip
```
检测到外部 IP。IP：“代理ip”
```

### 重现方式

在tun模式下使用默认设置的qbittorrent

### 日志

```shell
无，此issue仅为提醒
```
