### ISSUE TITLE
[Bug] 设置了tunnels和dialer-proxy 均不生效

### ISSUE THREAD

**Issue by hanyaxxx** [MetaCubeX/mihomo#1616]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [X] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [X] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [X] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [X] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [X] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Windows

### System Version

windows

### Mihomo Version

1.18.9

### Configuration File

```yaml
mode: rule
mixed-port: 7897
allow-lan: false
log-level: silent
ipv6: true
external-controller: 127.0.0.1:9097
secret: ""
hosts:
  time.facebook.com: 17.253.84.125
  time.android.com: 17.253.84.125  
dns:
  enable: true
  use-hosts: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 223.6.6.6
    - tcp://223.5.5.5
    - tcp://223.6.6.6
    - tls://dns.google:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://dns.alidns.com
    - tls://223.5.5.5
    - tls://223.6.6.6
    - tls://dot.pub
    - tls://1.12.12.12
    - tls://120.53.53.53
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.alidns.com/dns-query
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://doh.pub/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 223.6.6.6
    - tcp://119.29.29.29
    - tcp://223.5.5.5
    - tcp://223.6.6.6
  use-system-hosts: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.0/24
  fake-ip-filter:
    - "*"
    - +.lan
  fallback:
    - https://8.8.8.8/dns-query
  nameserver-policy:
    geosite:cn,private:
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
profile:
  store-selected: true
tun:
  auto-detect-interface: true
  auto-route: true
  device: Mihomo
  dns-hijack:
    - any:53
  mtu: 1500
  stack: system
  strict-route: true
  enable: true

external-controller-cors:
  allow-private-network: true
  allow-origins:
    - "*"
# tunnels:
# - network: [tcp, udp]
#   address: 120.232.17.120:19275 //这里换成 127.0.0.1:7897 也不行
#   target: 149.50.79.67:465
#   proxy: 日本A01
rules:
  match,120.232.17.120:19275 // 这里换成 tunnels或者其他地址 都是优先匹配match后面的ip 也就是没响应tunnels配置
```

### Description

问题1: tunnles 配置如上  tunnels流量没被监听到. address 替换成127.0.0.1:7897 也不行. 都是直接走了 rules match的代理

问题2: dialer-proxy 没生效, 

proxies:
  - name: 日本SS
    server: ****
    port: 476
    type: ss
    dialer-proxy: 链式代理2
    cipher: aes-256-gcm
    password: ****
    udp: true

proxy-groups:
  - name: 链式代理2
    type: select
    proxies:
    - 🔰 选择节点

rules:
MATCH,链式代理2

其他配置如上, 也是直接走选择节点没有进入日本SS代理

### Reproduction Steps

导入配置启动
