### ISSUE TITLE
[Bug] delay问题

### ISSUE THREAD

**Issue by memory9596** [MetaCubeX/mihomo#1618]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [X] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [X] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [X] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Windows

### System Version

Windows 10

### Mihomo Version

alpha-3e966e8

### Configuration File

```yaml
t: &t {url: https://www.gstatic.com/generate_204, interval: 300, lazy: false}

p: &p {type: http, interval: 3600, proxy: DIRECT, health-check: {enable: true, <<: *t}}

proxy-providers:
  provider1:
    url: 
    <<: *p

proxies:

proxy-groups:
  - name: 默认
    type: select
    include-all: true
    <<: *t

log-level: debug
mixed-port: 7890
ipv6: true
allow-lan: true
unified-delay: true
tcp-concurrent: false
external-controller: 0.0.0.0:9090
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip

geodata-mode: true
geodata-loader: memconservative
geosite-matcher: mph

geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip-lite.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip-lite.metadb
  asn: https://testingcf.jsdelivr.net/gh/xishang0128/geoip@release/GeoLite2-ASN.mmdb

profile:
  store-selected: true
  store-fake-ip: false

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    http:
      ports: [80, 8080-8880]
    tls:
      ports: [443, 8443]
    quic:
      ports: [443, 8443]

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
  direct-nameserver:
    - 114.114.114.114
    - 119.29.29.29
  proxy-server-nameserver:
    - 114.114.114.114
    - 119.29.29.29
  nameserver:
    - 8.8.8.8#默认

rules:
  - GEOSITE,cn,DIRECT
  - MATCH,默认
```

### Description

首次启动核心，provider过期并自发更新内容。此时，虽然核心日志显示完成测速，但external-ui不能获取delay信息

### Reproduction Steps

在provider过期且内容需要变更时，首次启动核心。

### Logs

```
time="2024-10-27T21:04:49.5704818+08:00" level=info msg="Start initial configuration in progress"
time="2024-10-27T21:04:49.5750709+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-10-27T21:04:49.5750709+08:00" level=info msg="Geosite Matcher implementation: mph"
time="2024-10-27T21:04:49.5760909+08:00" level=info msg="Load GeoSite rule: cn"
time="2024-10-27T21:04:49.6660548+08:00" level=info msg="Finished initial GeoSite rule cn => DIRECT, records: 92852"
time="2024-10-27T21:04:49.6680553+08:00" level=info msg="Initial configuration complete, total time: 93ms"
time="2024-10-27T21:04:49.6680553+08:00" level=info msg="RESTful API listening at: [::]:9090"
time="2024-10-27T21:04:49.6710557+08:00" level=info msg="Sniffer is loaded and working"
time="2024-10-27T21:04:49.6710557+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:7890"
time="2024-10-27T21:04:49.6710557+08:00" level=info msg="Start initial provider provider1"
time="2024-10-27T21:04:49.6730552+08:00" level=warning msg="[Provider] provider1 not updated for a long time, force refresh"
time="2024-10-27T21:04:49.6730552+08:00" level=debug msg="Start New Health Checking {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:49.6730552+08:00" level=debug msg="Health Checking, proxy: A国 20, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:49.6730552+08:00" level=debug msg="Health Checking, proxy: B国 9, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:49.6730552+08:00" level=debug msg="Health Checking, proxy: B国 4, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:49.6730552+08:00" level=debug msg="Health Checking, proxy: B国 10, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:49.6730552+08:00" level=debug msg="Health Checking, proxy: B国 2, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:49.6730552+08:00" level=debug msg="Health Checking, proxy: B国 3, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:49.6730552+08:00" level=debug msg="Health Checking, proxy: B国 6, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:49.6730552+08:00" level=debug msg="Health Checking, proxy: B国 7, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:49.6730552+08:00" level=debug msg="Health Checking, proxy: B国 8, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:49.6730552+08:00" level=debug msg="Health Checking, proxy: B国 5, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:49.6780558+08:00" level=info msg="Start initial Compatible provider default"
time="2024-10-27T21:04:49.6780558+08:00" level=info msg="UI already exists, skip downloading"
time="2024-10-27T21:04:49.8993746+08:00" level=info msg="[TCP] mihomo --> provider1's url using DIRECT"
time="2024-10-27T21:04:49.9003947+08:00" level=info msg="[TCP] mihomo --> provider1's url using DIRECT"
time="2024-10-27T21:04:49.9003947+08:00" level=info msg="[TCP] mihomo --> provider1's url using DIRECT"
time="2024-10-27T21:04:50.3642756+08:00" level=debug msg="Health Checked, proxy: B国 6, url: https://www.gstatic.com/generate_204, alive: true, delay: 103 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:50.3642756+08:00" level=debug msg="Health Checking, proxy: B国 15, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:50.389236+08:00" level=debug msg="Health Checked, proxy: B国 7, url: https://www.gstatic.com/generate_204, alive: true, delay: 104 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:50.389236+08:00" level=debug msg="Health Checking, proxy: B国 11, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:51.1282942+08:00" level=info msg="[TCP] mihomo --> provider1's url using DIRECT"
time="2024-10-27T21:04:51.2123542+08:00" level=info msg="[Provider] provider1's content update"
time="2024-10-27T21:04:51.3949745+08:00" level=debug msg="Health Checked, proxy: B国 5, url: https://www.gstatic.com/generate_204, alive: true, delay: 301 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:51.3949745+08:00" level=debug msg="Health Checking, proxy: B国 14, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:51.4137797+08:00" level=info msg="[TCP] mihomo --> provider1's url using DIRECT"
time="2024-10-27T21:04:51.4184192+08:00" level=info msg="[TCP] mihomo --> provider1's url using DIRECT"
time="2024-10-27T21:04:51.5060112+08:00" level=debug msg="Health Checked, proxy: B国 4, url: https://www.gstatic.com/generate_204, alive: true, delay: 225 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:51.5060112+08:00" level=debug msg="Health Checking, proxy: A国 17, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:51.6033354+08:00" level=debug msg="Health Checked, proxy: A国 20, url: https://www.gstatic.com/generate_204, alive: true, delay: 298 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:51.6033354+08:00" level=debug msg="Health Checking, proxy: B国 16, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:51.6525779+08:00" level=debug msg="Health Checked, proxy: B国 2, url: https://www.gstatic.com/generate_204, alive: true, delay: 269 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:51.6525779+08:00" level=debug msg="Health Checking, proxy: A国 18, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:51.7380514+08:00" level=debug msg="Health Checked, proxy: B国 3, url: https://www.gstatic.com/generate_204, alive: true, delay: 312 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:51.7380514+08:00" level=debug msg="Health Checking, proxy: B国 13, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:52.213369+08:00" level=info msg="[TCP] mihomo --> provider1's url using DIRECT"
time="2024-10-27T21:04:52.3730184+08:00" level=debug msg="Health Checked, proxy: B国 8, url: https://www.gstatic.com/generate_204, alive: true, delay: 643 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:52.3730184+08:00" level=debug msg="Health Checking, proxy: A国 19, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:52.4391851+08:00" level=debug msg="Health Checked, proxy: B国 14, url: https://www.gstatic.com/generate_204, alive: true, delay: 138 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:52.4391851+08:00" level=debug msg="Health Checking, proxy: B国 12, url: https://www.gstatic.com/generate_204, id: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:52.4862917+08:00" level=debug msg="[Provider] provider1's content doesn't change"
time="2024-10-27T21:04:52.5092156+08:00" level=debug msg="Health Checked, proxy: B国 16, url: https://www.gstatic.com/generate_204, alive: true, delay: 127 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:52.6390285+08:00" level=info msg="[TCP] mihomo --> provider1's url using DIRECT"
time="2024-10-27T21:04:52.9362583+08:00" level=debug msg="Health Checked, proxy: B国 13, url: https://www.gstatic.com/generate_204, alive: true, delay: 138 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:53.3282502+08:00" level=debug msg="Health Checked, proxy: B国 11, url: https://www.gstatic.com/generate_204, alive: true, delay: 510 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:54.205136+08:00" level=debug msg="Health Checked, proxy: B国 9, url: https://www.gstatic.com/generate_204, alive: true, delay: 377 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:54.2358232+08:00" level=debug msg="Health Checked, proxy: B国 10, url: https://www.gstatic.com/generate_204, alive: true, delay: 526 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:54.3534918+08:00" level=debug msg="Health Checked, proxy: A国 17, url: https://www.gstatic.com/generate_204, alive: true, delay: 243 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:54.6082306+08:00" level=debug msg="Health Checked, proxy: B国 12, url: https://www.gstatic.com/generate_204, alive: true, delay: 413 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:54.9850858+08:00" level=debug msg="Health Checked, proxy: A国 18, url: https://www.gstatic.com/generate_204, alive: true, delay: 284 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:55.364582+08:00" level=debug msg="Health Checked, proxy: B国 15, url: https://www.gstatic.com/generate_204, alive: false, delay: 65535 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:57.3734158+08:00" level=debug msg="Health Checked, proxy: A国 19, url: https://www.gstatic.com/generate_204, alive: false, delay: 65535 ms uid: {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:04:57.3734158+08:00" level=debug msg="Finish A Health Checking {733d7ec3-0438-4dc6-8990-21424dca7ce7}"
time="2024-10-27T21:05:03.5136788+08:00" level=warning msg="Mihomo shutting down"
```
