### ISSUE TITLE
[Bug]  dialer-proxy connect failed 如何解决?

### ISSUE THREAD

**Issue by hanyaxxx** [MetaCubeX/mihomo#1621]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [X] 我是中文用户，而非其他语言用户
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [X] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [X] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

windows11

### Mihomo 版本

1.18.9

### 配置文件

```yaml
profile:
  store-selected: true

dns:
  use-system-hosts: true
  enable: true
  use-hosts: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 223.6.6.6
    - tcp://223.5.5.5
    - tcp://223.6.6.6
    - tls://dns.google:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://dns.alidns.com
    - tls://223.5.5.5
    - tls://223.6.6.6
    - tls://dot.pub
    - tls://1.12.12.12
    - tls://120.53.53.53
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.alidns.com/dns-query
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://doh.pub/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query

  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 223.6.6.6
    - tcp://119.29.29.29
    - tcp://223.5.5.5
    - tcp://223.6.6.6

  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - "+.lan"
  fallback:
    - https://8.8.8.8/dns-query

  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
tun:
  auto-detect-interface: true
  auto-route: true
  device: Mihomo
  dns-hijack:
  - any:53
  mtu: 1500
  stack: system
  strict-route: true
  enable: true

proxies:
  - {
      name: 🇭🇰 香港A02,
      server: v50307shvkaa.art,
      port: 14563,
      dialer-proxy: DIALER-TEST,
      type: ss,
      cipher: aes-256-gcm,
      udp: true,
    }
  - {
      name: 🇭🇰 香港A04,
      server: v50307shvkaa.art,
      port: 807,
      type: ss,
      cipher: aes-256-gcm,
      udp: true,
    }

proxy-group:
  - name: DIALER-TEST
    type: select
    proxies:
      - 🇭🇰 香港A04
```

### 描述

前提:
开启fake-ip,无dns嗅探,开启tun,均ss协议

期望行为
内核>🇭🇰 香港A04>🇭🇰 香港A02>目标

日志:
[TCP] dial 🇭🇰 香港A02  (match Match/) 28.0.0.1:55164 --> data.bilibili.com:443 error:v50307shvkaa.art:14563 connect error: v50307shvkaa.art:807 connect error: connect failed: dial tcp 119.135.231.***:807: i/o timeout

### 重现方式

均可重现
