### ISSUE TITLE
[Bug] mixed stack 在GSO启用的情况下会导致UDP异常无法使用

### ISSUE THREAD

**Issue by vernesong** [MetaCubeX/mihomo#1630]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [X] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [X] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [X] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [X] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [X] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Linux

### System Version

ImmortalWrt 18.06-k5.4-SNAPSHOT r12328-cfa5234f62 / LuCI openwrt-18.06-k5.4 branch (git-22.298.58837-381482c)

### Mihomo Version

Mihomo Meta alpha-3e966e8 linux arm64 with go1.23.2 Mon Oct 21 01:45:23 UTC 2024
Use tags: with_gvisor

### Configuration File

```yaml
tun:
  enable: true
  stack: mixed
  device: utun
  dns-hijack:
  - any:53
  gso: true
  gso-max-size: 65536
  auto-route: true
  auto-detect-interface: true
  auto-redirect: true
  strict-route: false
  endpoint-independent-nat: true
```

### Description

使用mixed并同时启用GSO后会导致UDP异常丢包，例如ntp服务等无法进行同步，关闭GSO后正常，单独使用其他协议栈也正常

### Reproduction Steps

使用mixed协议栈并同时启用GSO
![image](https://github.com/user-attachments/assets/4a579ac0-dcdd-46a5-82fa-7d81ab2806ac)
![image](https://github.com/user-attachments/assets/12a1ba47-1222-4ef1-99c5-99e51d83e28e)
关闭GSO后
![image](https://github.com/user-attachments/assets/549ab517-63fb-4f90-82ce-6c41368faa7d)
![image](https://github.com/user-attachments/assets/b7878b41-1ff6-4a4c-868f-23f23cabe9f5)
