### ISSUE TITLE
[Bug] TUN的 mixed stack 在GSO启用的情况下会导致UDP异常无法使用

### ISSUE THREAD

**Issue by vernesong** [MetaCubeX/mihomo#1632]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [X] 我是中文用户，而非其他语言用户
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [X] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [X] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

ImmortalWrt 18.06-k5.4-SNAPSHOT r12328-cfa5234f62 / LuCI openwrt-18.06-k5.4 branch (git-22.298.58837-381482c)

### Mihomo 版本

Mihomo Meta alpha-3e966e8 linux arm64 with go1.23.2 Mon Oct 21 01:45:23 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
tun:
  enable: true
  stack: mixed
  device: utun
  dns-hijack:
  - any:53
  gso: true
  gso-max-size: 65536
  auto-route: true
  auto-detect-interface: true
  auto-redirect: true
  strict-route: false
  endpoint-independent-nat: true
```

### 描述

使用mixed并同时启用GSO后会导致UDP异常丢包，例如ntp服务等无法进行同步，关闭GSO后正常，单独使用其他协议栈也正常

### 重现方式

使用mixed协议栈并同时启用GSO：
![image](https://github.com/user-attachments/assets/4a579ac0-dcdd-46a5-82fa-7d81ab2806ac)
![image](https://github.com/user-attachments/assets/12a1ba47-1222-4ef1-99c5-99e51d83e28e)
关闭GSO后：
![image](https://github.com/user-attachments/assets/549ab517-63fb-4f90-82ce-6c41368faa7d)
![image](https://github.com/user-attachments/assets/b7878b41-1ff6-4a4c-868f-23f23cabe9f5)
