### ISSUE TITLE
[Bug] 关于ss协议解析报错initialize error: unknown method: ss"

### ISSUE THREAD

**Issue by whp98** [MetaCubeX/mihomo#1637]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [X] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [X] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [x] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [X] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [X] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [X] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### System Version

Ubuntu 24.04

### Mihomo Version

Mihomo Meta v1.18.7 linux amd64 with go1.22.5 Sun Jul 28 05:47:02 UTC 2024
Use tags: with_gvisor

### Configuration File

```yaml
见如下
```

### Description

[LD8l3BAms5Jv.yaml.zip](https://github.com/user-attachments/files/17636014/LD8l3BAms5Jv.yaml.zip)
https://subapi.fxxk.dedyn.io/sub?&url=https%3A%2F%2Fraw.githubusercontent.com%2Faiboboxx%2Fv2rayfree%2Frefs%2Fheads%2Fmain%2Fv2&target=clash&emoji=true&append_type=true&append_info=true&scv=false&udp=false&list=false&sort=false&fdn=true&insert=false

### Reproduction Steps

添加订阅即可报错

### Logs

```shell
2024-11-06 00:56:53 ERROR - proxy 56: ss 183.240.255.75:11001 initialize error: unknown method: ss
2024-11-06 00:57:24 ERROR - proxy 56: ss 183.240.255.75:11001 initialize error: unknown method: ss
2024-11-06 01:04:52 ERROR - proxy 56: ss 183.240.255.75:11001 initialize error: unknown method: ss
2024-11-06 01:05:06 ERROR - proxy 56: ss 183.240.255.75:11001 initialize error: unknown method: ss
```

**Comment by whp98** [comment]
神奇的是单独添加这个节点不报错

```yaml
# Profile Template for Clash Verge

proxies: 
  - {name: "[SS] 🇭🇰 13|🇭🇰 香港3|@ripaojiedian", server: 183.240.255.75, port: 11001, type: ss, cipher: chacha20-ietf-poly1305, password: 813e5b6e-76c7-4ed3-a913-7cfcb7490424}
  - {name: "[SS] 🇭🇰 13|🇭🇰 香港4|@ripaojiedian", server: gdcub.yunnode.win, port: 31672, type: ss, cipher: chacha20-ietf-poly1305, password: 01ec0aea-686e-4c3a-8276-cf3f145b5304}
  - {name: "[VMess] 🇭🇰 13|🇭🇰 香港5|@ripaojiedian", server: 143.92.42.65, port: 2902, type: vmess, uuid: 640c1077-d10b-4225-a9fb-d3e9c3ce7a00, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false}

proxy-groups: []

rules: []

```
