### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by AquaSimulacra** [MetaCubeX/mihomo#1660]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [X] 我是中文用户，而非其他语言用户
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [X] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [X] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

Windows 11 24H2

### Mihomo 版本

1.8.10

### 配置文件

```yaml
tcp-concurrent: true

geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"

global-client-fingerprint: chrome

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  prefer-h3: true
  nameserver-policy:
    'geosite:cn':
    - https://223.5.5.5/dns-query
    - 223.5.5.5
  nameserver:
    - https://1.1.1.1/dns-query
  fallback:
    - 1.1.1.1

proxies:
- name: "Shadowsocks"
  type: ss
  server: 
  port: 27951
  cipher: 2022-blake3-aes-256-gcm
  password: 
  tfo: true
  udp: true
  udp-over-tcp: true
  udp-over-tcp-version: 2
  plugin: v2ray-plugin
  plugin-opts:
    mode: websocket
    tfo: true
    path: "/?ed=2048"
    tls: true
    host: 
  smux:
    enabled: false

proxy-groups:
-
  name: Proxy
  type: select
  proxies:
    - Shadowsocks
    - Vless
    - Vmess

rules:
  - DOMAIN-SUFFIX,bing.com,Shadowsocks
  - DOMAIN-SUFFIX,copilot.microsoft.com,Shadowsocks
  - GEOSITE,cn,DIRECT
  - MATCH,Proxy
```

### 描述

![image](https://github.com/user-attachments/assets/59744c16-a972-4c29-a05d-efb46b94d037)
在v2ray-plugin中的ws path填写/?ed=2048，ss将无法联通远端服务器

### 重现方式

同描述
