### ISSUE TITLE
[Bug] windows11开启ip转发后，tun模式不可用

### ISSUE THREAD

**Issue by kckm** [MetaCubeX/mihomo#1664]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [X] 我是中文用户，而非其他语言用户
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [X] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [X] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

23H2

### Mihomo 版本

`Mihomo Meta v1.18.10 windows amd64 with go1.23.2 Sun Nov  3 09:22:18 UTC 2024
Use tags: with_gvisor`

### 配置文件

```yaml
dns:
  enable: true
  prefer-h3: true
  listen: 127.0.0.1:1053
  ipv6: false
  use-hosts: true
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
  nameserver-policy:
  nameserver:
    # - https://dns.alidns.com/dns-query
    # - https://doh.pub/dns-query
    - system
  fallback:
  #  - "https://cloudflare-dns.com/dns-query#PROXY"
  fallback-filter:
    geoip: false
    geoip-code: cn
    geosite:
    ipcidr:
    domain:

sniffer:
  enable: false
  override-destination: false
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - Mijia Cloud

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  endpoint-independent-nat: false
  dns-hijack:
    - any:53
    - tcp://any:53

profile:
  store-selected: true
  # 储存 API 对策略组的选择，以供下次启动时使用
  store-fake-ip: true
  # 储存 fakeip 映射表，域名再次发生连接时，使用原有映射地址
mixed-port: 7890
allow-lan: true
mode: Rule
log-level: debug
ipv6: true
hosts:
external-controller: 127.0.0.1:9090
geodata-mode: true
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

proxies:
  - name: "xxx"
    type: vless
    server: 服务器ip
    port: 8443
    udp: true
    uuid: 
    flow: xtls-rprx-vision
    packet-encoding: xudp
    tls: true
    servername: www.
    alpn:
    - h2
    client-fingerprint: chrome
    skip-cert-verify: false
    reality-opts:
      public-key: 
      short-id: 

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - xxx

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    proxy: PROXY
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    proxy: PROXY
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    proxy: PROXY
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"
    proxy: PROXY
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    proxy: PROXY
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    proxy: PROXY
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    proxy: PROXY
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
    proxy: PROXY
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
    proxy: PROXY
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    proxy: PROXY
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    proxy: PROXY
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    proxy: PROXY
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    proxy: PROXY
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  # 封禁域名

  # 直连域名
  - DOMAIN-SUFFIX,xn--ngstr-cn-8za9o.com,DIRECT
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,DIRECT
  - DOMAIN,services.googleapis.cn,DIRECT
  - DOMAIN-SUFFIX,steamserver.net,DIRECT
  # 规则模板
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  # - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - AND,((RULE-SET,google),(NOT,((AND,((NETWORK,udp),(DST-PORT,443)))))),PROXY
  - AND,((RULE-SET,proxy),(NOT,((AND,((NETWORK,udp),(DST-PORT,443)))))),PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - AND,((RULE-SET,telegramcidr),(NOT,((AND,((NETWORK,udp),(DST-PORT,443)))))),PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - And,((DST-PORT,443),(NETWORK,udp)),REJECT
  - MATCH,PROXY
```

### 描述

通过注册表或者是powershell命令`Set-NetIPInterface -ifAlias '网卡名称' -Forwarding Enabled`后，tun模式启动，mihomo非常卡顿网络不可用，终端日志一直刷。

### 重现方式

通过注册表或者是powershell命令`Set-NetIPInterface -ifAlias '网卡名称' -Forwarding Enabled`将全局或是单独网卡设置成ip转发开启，然后tun模式启动mihomo。

### 日志

```shell
time="2024-11-22T19:25:49.3151442+08:00" level=debug msg="use specified fingerprint:Chrome"
time="2024-11-22T19:25:49.3151442+08:00" level=debug msg="[Rule] use default rules"
time="2024-11-22T19:25:49.3162001+08:00" level=debug msg="use specified fingerprint:Chrome"
time="2024-11-22T19:25:49.3162001+08:00" level=debug msg="[Rule] use default rules"
time="2024-11-22T19:25:49.3193446+08:00" level=debug msg="use specified fingerprint:Chrome"
time="2024-11-22T19:25:49.3193446+08:00" level=debug msg="[Rule] use default rules"
time="2024-11-22T19:25:49.3198586+08:00" level=warning msg="[TCP] dial PROXY (match Match/) 192.168.28.97:18856(mihomo-windows-amd64.exe) --> 服务器ip:8443 error: 服务器ip:8443 connect error: context deadline exceeded"
time="2024-11-22T19:25:49.3214929+08:00" level=warning msg="[TCP] dial PROXY (match Match/) 192.168.28.97:18857(mihomo-windows-amd64.exe) --> 服务器ip:8443 error: 服务器ip:8443 connect error: context deadline exceeded"
time="2024-11-22T19:25:49.3214929+08:00" level=debug msg="use specified fingerprint:Chrome"
time="2024-11-22T19:25:49.3219988+08:00" level=debug msg="[Rule] use default rules"
time="2024-11-22T19:25:49.3214929+08:00" level=debug msg="[Rule] use default rules"
time="2024-11-22T19:25:49.3219988+08:00" level=debug msg="use specified fingerprint:Chrome"
time="2024-11-22T19:25:49.3251455+08:00" level=debug msg="use specified fingerprint:Chrome"
time="2024-11-22T19:25:49.3251455+08:00" level=debug msg="[Rule] use default rules"
time="2024-11-22T19:25:49.3277615+08:00" level=warning msg="[TCP] dial PROXY (match Match/) 192.168.28.97:18858(mihomo-windows-amd64.exe) --> 服务器ip:8443 error: 服务器ip:8443 connect error: context deadline exceeded"
time="2024-11-22T19:25:49.3282904+08:00" level=warning msg="[TCP] dial PROXY (match Match/) 192.168.28.97:18859(mihomo-windows-amd64.exe) --> 服务器ip:8443 error: 服务器ip:8443 connect error: context deadline exceeded"
time="2024-11-22T19:25:49.3293384+08:00" level=debug msg="use specified fingerprint:Chrome"
time="2024-11-22T19:25:49.3293384+08:00" level=debug msg="[Rule] use default rules"
time="2024-11-22T19:25:49.3298593+08:00" level=debug msg="[Rule] use default rules"
time="2024-11-22T19:25:49.3298593+08:00" level=debug msg="use specified fingerprint:Chrome"
time="2024-11-22T19:25:49.3309018+08:00" level=debug msg="use specified fingerprint:Chrome"
time="2024-11-22T19:25:49.3309018+08:00" level=debug msg="[Rule] use default rules"
```
