### ISSUE TITLE
[Bug] 使用tun模式时，开启ipv6会导致tun内核启动失败

### ISSUE THREAD

**Issue by SixGodSGD** [MetaCubeX/mihomo#1667]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [X] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [X] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [X] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [X] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [X] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Android

### System Version

安卓15

### Mihomo Version

v1.18.10

### Configuration File

```yaml
mixed-port: 1080
redir-port: 7891
tproxy-port: 1536
allow-lan: true
mode: rule
log-level: debug

ipv6: true
keep-alive-interval: 15
keep-alive-idle: 15
unified-delay: true
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

find-process-mode: always
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.oray.com"
    - "+.oray.net"
    - "+.orayer.com"
    - "+.apple.com"
    - "dlg.io.mi.com"
    
tun:
  enable: true
  stack: gvisor
  device: tun0
  mtu: 9000
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  strict-route: true
#  auto-redirect: true
  auto-detect-interface: true
```

### Description

time="2024-11-23T17:30:08.486507524+08:00" level=error msg="Start TUN listening error: configure tun interface: permission denied"

### Reproduction Steps

开启配置文件中的ipv6即可复现问题

### Logs

```shell
time="2024-11-23T17:30:08.486507524+08:00" level=error msg="Start TUN listening error: configure tun interface: permission denied"
```
