### ISSUE TITLE
[Bug] key missing for tun inbound

### ISSUE THREAD

**Issue by Long0x0** [MetaCubeX/mihomo#1672]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [X] 我是中文用户，而非其他语言用户
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [X] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [X] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

23H2

### Mihomo 版本

Mihomo Meta alpha-eb985b0 windows amd64 with go1.23.3 Thu Nov 21 14:54:05 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
mode: rule
log-level: debug

listeners:
  - name: tun-in
    type: tun
    stack: system
    dns-hijack:
      - 0.0.0.0:53
    auto-route: true
    auto-detect-interface: true
    exclude-interface: []
    inet4-address:
      - 198.19.0.1/30

    ## the following keys are mandatory?
    # iproute2-table-index: 2022
    # iproute2-rule-index: 9000
    # auto-redirect: true
    # auto-redirect-input-mark: 6666
    # auto-redirect-output-mark: 6667
    # route-address: []
    # route-address-set: []
    # route-exclude-address: []
    # route-exclude-address-set: []

rules:
  - MATCH,DIRECT
```

### 描述

tun入站的配置默认缺少`iproute2-table-index`、`iproute2-rule-index`等。部分键值在文档里也没有提到。记得前几个版本没有问题。

### 重现方式

`./mihomo-windows-amd64-alpha.exe -f ./config.yaml -t`

### 日志

```shell
time="2024-11-25T13:15:01.2130283+08:00" level=info msg="Start initial configuration in progress"
time="2024-11-25T13:15:01.2202054+08:00" level=error msg="proxy 0: key 'iproute2-table-index' missing"
configuration file config.yaml test failed

time="2024-11-25T13:15:07.0055137+08:00" level=info msg="Start initial configuration in progress"
time="2024-11-25T13:15:07.0131423+08:00" level=error msg="proxy 0: key 'iproute2-rule-index' missing"
configuration file config.yaml test failed

time="2024-11-25T13:15:10.222249+08:00" level=info msg="Start initial configuration in progress"
time="2024-11-25T13:15:10.2300203+08:00" level=error msg="proxy 0: key 'auto-redirect' missing"
configuration file config.yaml test failed

time="2024-11-25T13:15:13.3484527+08:00" level=info msg="Start initial configuration in progress"
time="2024-11-25T13:15:13.3566058+08:00" level=error msg="proxy 0: key 'auto-redirect-input-mark' missing"
configuration file config.yaml test failed

time="2024-11-25T13:15:16.5719643+08:00" level=info msg="Start initial configuration in progress"
time="2024-11-25T13:15:16.5796745+08:00" level=error msg="proxy 0: key 'auto-redirect-output-mark' missing"
configuration file config.yaml test failed

time="2024-11-25T13:15:19.5153912+08:00" level=info msg="Start initial configuration in progress"
time="2024-11-25T13:15:19.5235885+08:00" level=error msg="proxy 0: key 'route-address' missing"
configuration file config.yaml test failed

time="2024-11-25T13:15:22.0491507+08:00" level=info msg="Start initial configuration in progress"
time="2024-11-25T13:15:22.0563157+08:00" level=error msg="proxy 0: key 'route-address-set' missing"
configuration file config.yaml test failed

time="2024-11-25T13:15:25.372104+08:00" level=info msg="Start initial configuration in progress"
time="2024-11-25T13:15:25.379812+08:00" level=error msg="proxy 0: key 'route-address-set' missing"
configuration file config.yaml test failed

time="2024-11-25T13:15:27.8285588+08:00" level=info msg="Start initial configuration in progress"
time="2024-11-25T13:15:27.8383566+08:00" level=error msg="proxy 0: key 'route-exclude-address-set' missing"
configuration file config.yaml test failed
```
