### ISSUE TITLE
[Bug] 当配置开启v6之后，开启手机热点会有部分流量不走代理

### ISSUE THREAD

**Issue by SixGodSGD** [MetaCubeX/mihomo#1674]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [X] 我是中文用户，而非其他语言用户
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [X] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [X] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Android

### 系统版本

安卓15

### Mihomo 版本

v1.18.10

### 配置文件

```yaml
mixed-port: 1080
redir-port: 7891
tproxy-port: 1536
allow-lan: true
mode: rule
log-level: warning

ipv6: true
keep-alive-interval: 15
keep-alive-idle: 15
unified-delay: true
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

find-process-mode: always
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.oray.com"
    - "+.oray.net"
    - "+.orayer.com"
    - "+.apple.com"
    - "dlg.io.mi.com"
    - ".push.apple.com"
    
tun:
  enable: true
  stack: gvisor
  device: tun0
  mtu: 9000
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  strict-route: true
#  auto-redirect: true
  auto-detect-interface: true
```

### 描述

手机开启热点之后，不管是tun还是tp还是redirect都会出现，热点流量部分会不经过代理。
但是关闭v6之后，则正常

### 重现方式

配置开启v6，即可复现

### 日志

```shell
time="2024-11-26T13:59:23.766817553+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
me="2024-11-26T13:59:23.776521563+08:00" level=info msg="Sniffer is loaded and working"
time="2024-11-26T13:59:23.776545001+08:00" level=info msg="Use tcp concurrent"
time="2024-11-26T13:59:23.776913647+08:00" level=info msg="DNS server listening at: [::]:1053"
time="2024-11-26T13:59:23.777033751+08:00" level=info msg="Redirect proxy listening at: [::]:7891"
time="2024-11-26T13:59:23.777148594+08:00" level=info msg="TProxy server listening at: [::]:1536"
time="2024-11-26T13:59:23.777258438+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:1080"
time="2024-11-26T13:59:23.779406511+08:00" level=warning msg="[TUN] default interface changed by monitor,  => rmnet_data3"
time="2024-11-26T13:59:23.799214636+08:00" level=info msg="[TUN] Tun adapter listening at: tun0([198.18.0.0/30],[fdfe:dcba:9876::1/126]), mtu: 9000, auto route: true, auto redir: false, ip stack: gVisor"
```
