### ISSUE TITLE
[Bug] shadowsocks协议cipher为none时仍然需要写password

### ISSUE THREAD

**Issue by lonble** [MetaCubeX/mihomo#1677]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [X] 我是中文用户，而非其他语言用户
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [X] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [X] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

Arch Linux

### Mihomo 版本

Mihomo Meta alpha-1fff34d linux amd64 with go1.23.3 Tue Nov 26 05:42:00 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
log-level: 'debug'
mode: 'rule'
allow-lan: false
mixed-port: 2080

geodata-mode: true
geox-url:
  geoip: 'https://cdn.jsdelivr.net/gh/v2fly/geoip@release/geoip.dat'
  geosite: 'https://cdn.jsdelivr.net/gh/v2fly/domain-list-community@release/dlc.dat'

proxies:
- name: 'PROXY'
  type: 'ss'
  server: '*****'
  port: 7433
  udp: true
  cipher: "none"

rules:
- 'GEOSITE,cn,DIRECT'
- 'GEOIP,cn,DIRECT'
- 'MATCH,PROXY'
```

### 描述

shadowsocks协议cipher为none时仍然需要写password，否则启动报错。添加password字段，随便写任意值可以正常启动

### 重现方式

直接运行此配置

### 日志

```shell
INFO[2024-11-26T22:53:26.971846436+08:00] Start initial configuration in progress      
FATA[2024-11-26T22:53:26.971925289+08:00] Parse config error: proxy 0: key 'password' missing
```
