### ISSUE TITLE
tun模式下vless协议开启UDP会很慢

### ISSUE THREAD

**Issue by yang05051** [MetaCubeX/mihomo#168]
在vless节点下，添加`udp: true`，Clash接管了UDP流量之后会非常慢，DNS无论选择redir-host并使用嗅探器Sniffer，或是fake-ip都是这样

去除`udp: true`，Clash不接管UDP流量（UDP流量不走代理，直连）速度正常

以上结果于澳门本地的网络环境得出，不存在运营商UDP阻断

客户端选用了clash-verge，启用了服务模式

配置文件如下：
```
proxies:
  - name: "VLESS"
    type: vless
    server: IP
    port: 443
    uuid: UUID
    tls: true
    udp: true
    network: tcp
    servername: example.com
    skip-cert-verify: false

# sniffer:
#   enable: true
#   sniffing:
#     - tls
#     - http

dns:
  ipv6: true
  # enable: true
  # listen: 0.0.0.0:53
  # enhanced-mode: redir-host
  # fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 1.1.1.1
    - 114.114.114.114
  proxy-server-nameserver:
    - 1.1.1.1
  nameserver:
    - 1.1.1.1
    - 114.114.114.114
  fallback:
    - 1.1.1.1
    - 114.114.114.114

proxy-groups:
  - name: "GROUP"
    type: select
    proxies:
      - VLESS

rule-providers:
  private:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400
  ads:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

rules:
  ### Direct ###
  # Local Network
  - RULE-SET,private,DIRECT
  # Education
  - DOMAIN-SUFFIX,um.edu.mo,DIRECT
  - DOMAIN-KEYWORD,.zoom.,DIRECT
  - DOMAIN-KEYWORD,zoom.,DIRECT
  - DOMAIN-KEYWORD,iclass30,DIRECT
  - DOMAIN-KEYWORD,talk915,DIRECT
  - DOMAIN-KEYWORD,xuedianyun,DIRECT
  - DOMAIN-KEYWORD,yuansouti,DIRECT
  - DOMAIN-KEYWORD,zybang,DIRECT
  # Ruanmei
  - DOMAIN-SUFFIX,ruanmei.com,DIRECT
  - DOMAIN-KEYWORD,ithome,DIRECT
  # Huawei
  - DOMAIN-SUFFIX,e.huawei.com,DIRECT
  - DOMAIN-SUFFIX,huaweicloud.com,DIRECT
  - DOMAIN-SUFFIX,huaweiuniversity.com,DIRECT
  - DOMAIN-SUFFIX,uniportal.huawei.com,DIRECT
  # Bilibili
  - DOMAIN-SUFFIX,biliapi.net,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,bilivideo.com,DIRECT
  # Lenovo
  - DOMAIN-SUFFIX,lecloud-pc.lenovo.com,DIRECT
  - DOMAIN-SUFFIX,legionzone.lenovo.com,DIRECT
  - DOMAIN-SUFFIX,lenovomm.com,DIRECT
  - DOMAIN-SUFFIX,lestore.lenovo.com,DIRECT
  # Tencent
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-KEYWORD,tencent,DIRECT
  # Microsoft
  # - DOMAIN-SUFFIX,insider.windows.com,DIRECT
  # - DOMAIN-SUFFIX,login.live.com,DIRECT
  # - DOMAIN-SUFFIX,login.microsoftonline.com,DIRECT
  # - DOMAIN-SUFFIX,smartscreen-prod.microsoft.com,DIRECT
  # - DOMAIN-SUFFIX,smartscreen.microsoft.com,DIRECT
  # - DOMAIN-SUFFIX,urs.microsoft.com,DIRECT
  # - DOMAIN-SUFFIX,wip-api-prod.azurewebsites.net,DIRECT
  # Others
  - DOMAIN-SUFFIX,163.com,DIRECT
  - DOMAIN-SUFFIX,360.com,DIRECT
  - DOMAIN-SUFFIX,cdntips.net,DIRECT
  - DOMAIN-SUFFIX,ipip.net,DIRECT
  - DOMAIN-SUFFIX,jianyujiasu.com,DIRECT
  - DOMAIN-SUFFIX,kami.vip,DIRECT
  - DOMAIN-SUFFIX,kuaifaka.net,DIRECT
  - DOMAIN-SUFFIX,sandsresortsmacao.com,DIRECT
  - DOMAIN-KEYWORD,.cn,DIRECT
  - DOMAIN-KEYWORD,afdian,DIRECT
  - DOMAIN-KEYWORD,baidu,DIRECT
  - DOMAIN-KEYWORD,baijiayun,DIRECT
  - DOMAIN-KEYWORD,bmclapi,DIRECT
  - DOMAIN-KEYWORD,coolapk,DIRECT
  - DOMAIN-KEYWORD,csdn,DIRECT
  - DOMAIN-KEYWORD,hmcl,DIRECT
  - DOMAIN-KEYWORD,huangyuhui,DIRECT
  - DOMAIN-KEYWORD,iqiyi,DIRECT
  - DOMAIN-KEYWORD,jianshu,DIRECT
  - DOMAIN-KEYWORD,luogu,DIRECT
  - DOMAIN-KEYWORD,vijos,DIRECT
  - DOMAIN-KEYWORD,xunlei,DIRECT
  - DOMAIN-KEYWORD,zhengruioi,DIRECT
  ### Block Ads ###
  - RULE-SET,ads,REJECT
  ### Others ###
  - MATCH,GROUP

```
