### ISSUE TITLE
[Bug] NETIO.SYS 蓝屏   进程 verge-mihomo.e

### ISSUE THREAD

**Issue by feiqingbiss** [MetaCubeX/mihomo#1686]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [X] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [X] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [X] I am a non-Chinese user.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [X] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [X] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [X] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Windows

### System Version

WIN11PRO 24H2 26100.2454 & 1000.26100.36.0

### Mihomo Version

V1.18.10

### Configuration File

```yaml
# Generated by Clash Verge

mixed-port: 6666
socks-port: 7898
port: 7899
log-level: info
allow-lan: false
mode: rule
external-controller: 127.0.0.1:9097
secret: ''
tun:
  stack: gvisor
  device: Mihomo
  auto-route: true
  strict-route: false
  auto-detect-interface: true
  dns-hijack:
  - any:53
  mtu: 1500
external-controller-cors:
  allow-private-network: true
  allow-origins:
  - '*'
unified-delay: true
```

### Description

正常使用过程中蓝屏，客户端clash verge rev 2.0.1版，dump文件指向verge-mihomo.e，不懂代码，看大佬们怎么解决吧
[112824-8578-01.dmp](https://github.com/user-attachments/files/17950417/112824-8578-01.dmp)
[2024-11-28-2348.log](https://github.com/user-attachments/files/17950441/2024-11-28-2348.log)
[2024-11-26-1914.log](https://github.com/user-attachments/files/17950442/2024-11-26-1914.log)
[2024-11-26-2331.log](https://github.com/user-attachments/files/17950443/2024-11-26-2331.log)
[2024-11-27-1848.log](https://github.com/user-attachments/files/17950444/2024-11-27-1848.log)
[2024-11-28-0057.log](https://github.com/user-attachments/files/17950445/2024-11-28-0057.log)
[2024-11-28-0135.log](https://github.com/user-attachments/files/17950446/2024-11-28-0135.log)
[2024-11-28-1931.log](https://github.com/user-attachments/files/17950447/2024-11-28-1931.log)

### Reproduction Steps

暂时无法复现

### Logs

```shell
蓝屏发生前info等级，不知道有没有用。
```
