### ISSUE TITLE
[Feature] don't track outbound type dns

### ISSUE THREAD

**Issue by nunu6689** [MetaCubeX/mihomo#1691]
### Verification Steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and confirmed that this feature is not implemented
- [X] I have searched for the feature request I want to propose in the [Issue Tracker](……/) and did not find it
- [X] I am a non-Chinese user.

### Description

When using tproxy with outbound type DNS please don't put it in the connections list. It flooded the connections list and stay there for a while. XD dashboard was lagging a lot, only yacd can handle it.
Thanks.

```yaml
proxies:
  - name: 'dns-hijack'
    type: dns

rules:
  - DST-PORT,53,dns-hijack
```

![Screenshot_20241202-234915_Kiwi Browser](https://github.com/user-attachments/assets/24979830-31cf-46ad-bd01-5e8c15ec04ca)
