### ISSUE TITLE
[Bug] wireguard节点连不上

### ISSUE THREAD

**Issue by RoJoHub** [MetaCubeX/mihomo#1713]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [X] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [X] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [ ] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

MacOS

### System Version

15.1.1 

### Mihomo Version

v1.19.0

### Configuration File

```yaml
测试文件1

proxies:
  - {name: 家庭路由WireGuard线路, server: xxx.asuscomm.cn, port: 51820, type: wireguard, ip: 10.6.0.2, private-key: xb, public-key: xa, dns-server: 10.6.0.1, mtu: 1420, udp: true, persistent-keepalive: 25}
proxy-groups:
  - name: 家庭路由节点
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 家庭路由WireGuard线路
  - name: 家庭局域网
    type: select
    proxies:
      - 家庭路由节点
rules:
  - IP-CIDR,192.168.50.0/24,家庭局域网
  - IP-CIDR,10.6.0.0/24,家庭局域网
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
```

测试文件2
```
proxies:
- name: "家庭路由WireGuard线路"
  type: wireguard
  ip: 10.6.0.2
  private-key: xb
  peers:
    - server: xxx.asuscomm.cn
      port: 51820
      public-key: xa
      allowed-ips: ['0.0.0.0/0']     # 分流由clash处理
  udp: true
  remote-dns-resolve: true    # 按需设置，不用直接删除
  dns: [10.6.0.1]             # 按需设置，不用直接删除
proxy-groups:
  - name: 家庭路由节点
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 家庭路由WireGuard线路
  - name: 家庭局域网
    type: select
    proxies:
      - 家庭路由节点
rules:
  - IP-CIDR,192.168.50.0/24,家庭局域网
  - IP-CIDR,10.6.0.0/24,家庭局域网
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
```

### Description

使用 Clash Verge 根据WireGuard 文件配置了 yaml

```
[Interface]
PrivateKey = xb
Address = 10.6.0.2/32
DNS = 10.6.0.1

[Peer]
PublicKey = xa
AllowedIPs = 10.6.0.0/24, 192.168.50.0/24
Endpoint = xxx.asuscomm.cn:51820
PersistentKeepalive = 25
```

### Reproduction Steps

使用配置文件后,在代理可以看见测试连接成功

然而我遇到了 Clash 显示 连接成功, 但是实际使用不成

- ping 192.168.50.1 失败
- ping 10.6.0.0/32 成功 (好像是假的?)
- Chrome 访问 192.168.50.1 失败

<img width="1033" alt="image" src="https://github.com/user-attachments/assets/8870c2fd-4540-4b8e-91ae-ba9efd02eaac" />

### Logs

```shell
https://github.com/user-attachments/files/18107021/2024-12-12-1507.log
```

**Comment by thomasTAT** [comment]
大佬，你的 wireguard 配置成功了吗？

我的能连上，但是有些小问题！
https://github.com/MetaCubeX/mihomo/discussions/1810

**Comment by thomasTAT** [comment]
和你的配置信息基本一致，但不知为何，手机 Clash meta for andriod + WireGuard 正常连接，切换后WiFi断连，需要重启 clash 才能恢复连接，请问你有遇到过吗？https://github.com/MetaCubeX/mihomo/discussions/1810



# 完整配置信息：
```
#clash config

proxies:

- name: "SF-UK-LD"
  type: wireguard
  ip: 10.14.0.2
  private-key: dfjashdjfjkdsfhjkdshfjkdhjkfhkdjfdfhdjfhdjfhd
  peers:
    - server: uk-lon.prod.surfshark.com
      port: 51820
      public-key: iBJRXLZwXuWWrOZE1ZrAXEKMgV/z0WjG0Tks5rnWLBI=
      allowed-ips: ['0.0.0.0/0']  
  udp: true


proxy-groups:
  
  - name: "ChatGPT"
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - SF-UK-LD

rules:
  - DOMAIN-SUFFIX,openai.com,ChatGPT
  - DOMAIN-SUFFIX,chatgpt.com,ChatGPT
  - MATCH,DIRECT


```
