### ISSUE TITLE
[Bug] TUN 开启后在本机运行的docker中，无法通过ssh访问github

### ISSUE THREAD

**Issue by LiNY2-01** [MetaCubeX/mihomo#1736]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [X] 我是中文用户，而非其他语言用户
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [X] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [X] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

Linux ubuntu 22.04 server 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Mihomo 版本

Mihomo Meta alpha-89dfabe linux amd64 with go1.23.4 Thu Dec 19 07:57:02 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
mixed-port: 7890
ipv6: true
allow-lan: true
unified-delay: false
tcp-concurrent: true

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: false
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  nameserver-policy:
    "rule-set:cn_domain,private_domain":
      - https://120.53.53.53/dns-query
      - https://223.5.5.5/dns-query
    "rule-set:geolocation-!cn":
      - "https://dns.cloudflare.com/dns-query"
      - "https://dns.google/dns-query"
```

### 描述

宿主机启动mihomo内核并开启TUN转发之后，其运行的docker中无法通过ssh访问github。ssh返回：
```
ssh -T git@github.com
ssh_exchange_identification: Connection closed by remote host
```
通过修改`.ssh/config`
```
Host github.com
    HostName github.com
    User git
    Port 443
```
将请求的ssh端口从22切换到443亦如此。
同时，通过docker执行：
```
ping github.com
PING github.com (198.18.0.13): 56 data bytes
```

### 重现方式

1. 宿主机启动mihomo内核并打开tun转发
2. 启动一个docker并且在其中配置好github的sshkey
3. docker 中执行 `ssh -T git@github.com` 和 `ping github.com`

### 日志

```shell
24-12-21 21:59:06[ debug ][DNS] hijack udp:198.18.0.2:53 from 198.18.0.1:54121
24-12-21 21:58:55[ info ][TCP] 172.17.0.2:33164 --> github.com:443 match RuleSet(github_domain) using Github[[provider1]香港01]
24-12-21 21:58:55[ debug ]use specified fingerprint:Chrome
24-12-21 21:58:55[ debug ][DNS] cache hit ppg-hk.05vr9nyqg5.download --> [2409:8754:10:4:c000:0:1:a50 2409:8754:10:4:c000:0:1:a4] AAAA, expire at 2024-12-21 21:59:15
24-12-21 21:58:55[ debug ][DNS] cache hit ppg-hk.05vr9nyqg5.download --> [183.236.51.4 183.236.51.50] A, expire at 2024-12-21 21:58:58
24-12-21 21:58:55[ debug ][Rule] use default rules
24-12-21 21:58:55[ debug ][DNS] hijack udp:198.18.0.2:53 from 198.18.0.1:50709
```
