### ISSUE TITLE
[Bug] Port forward stops working after program start on router 

### ISSUE THREAD

**Issue by Jon811** [MetaCubeX/mihomo#1737]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [X] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [X] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [X] I am a non-Chinese user.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [X] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [X] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [X] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Linux

### System Version

OpenWrt 23.05.5 r24106-10cc5fcd00 

### Mihomo Version

Version v1.19.0

### Configuration File

```yaml
mode: rule
ipv6: false
log-level: error
allow-lan: false
tproxy-port: 7894
unified-delay: true
tcp-concurrent: true
external-controller: 0.0.0.0:9090
external-ui: ./ui

dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: false
  default-nameserver: [1.1.1.1, 1.0.0.1, 8.8.8.8, 8.8.4.4]
  nameserver: [https://dns10.quad9.net/dns-query, https://dns.aa.net.uk/dns-query]

profile:
  store-selected: true
  store-fake-ip: true

routing-mark: 2

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    # QUIC:
    #   ports: [443, 8443]
  skip-domain:
    - "Mijya Cloud"

proxies:

  # vless
  - name: "MYVLESS"
    type: vless
    server: 123.456.789.123
    port: 443
    uuid: *******************************
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.*******.com
    reality-opts:
      public-key: ********************
      short-id: *****
    client-fingerprint: chrome


proxy-groups:
  # Select (used for selecting proxy or proxy group)
  - name: PROXY
    type: select
    # disable-udp: true
    proxies:
      - MYVLESS

  # Fallback
  #- name: FALLBACK
  #  type: fallback
  #  proxies:
  #    - VASHVLESS1


  #  url: 'https://www.gstatic.com/generate_204' # or https://cp.cloudflare.com/generate_204
  #  interval: 300

  # Load-balance
 # - name: LB-PROXY
 #   type: load-balance
 #   proxies:
 #     - VASHVLESS1

 #   url: 'https://www.gstatic.com/generate_204'
 #   interval: 300
 #   strategy: consistent-hashing # or round-robin

rule-providers:

  ru-blocked:
    behavior: domain
    type: http
    format: text
    url: 'https://cdn.jsdelivr.net/gh/shvchk/unblock-net/lists/clash/ru-blocked'
    interval: 86400
    path: ./ruleset/ru-blocked.yaml

  intel:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Intel/Intel.yaml"
    interval: 86400
    path: ./ruleset/intel.yaml

  wix:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WIX/WIX.yaml"
    interval: 86400
    path: ./ruleset/wix.yaml

  twitter:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml"
    interval: 86400
    path: ./ruleset/twitter.yaml

  instagram:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.yaml"
    interval: 86400
    path: ./ruleset/instagram.yaml

  facebook:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.yaml"
    interval: 86400
    path: ./ruleset/facebook.yaml

  youtube:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"
    interval: 86400
    path: ./ruleset/youtube.yaml

  discord-domain:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/fildunsky/clash_discord/refs/heads/main/discord-domain.yaml"
    interval: 86400
    path: ./ruleset/discord-domain.yaml

  discord-ip:
    behavior: classical
    type: http
    url: "https://raw.githubusercontent.com/fildunsky/clash_discord/refs/heads/main/discord-ip.yaml"
    interval: 86400
    path: ./ruleset/discord-ip.yaml
rules:
# Правила исполняются по порядку, чем выше, тем раньше
  - SRC-IP-CIDR,192.168.0.127/32,DIRECT # Пускаем весь трафф конкретного устройства напрямую (без VPN)
#  - DOMAIN-SUFFIX,yandex.ru,PROXY # Так можно пускать любой сайт и все его поддомены (mail.yandex.ru и тп) через прокси, если надо напрямую, пишем DIRECT
#  - DOMAIN,gdeposylka.ru,REJECT # Так можно блокировать любой сайт и в теории резать рекламу
  #- IP-CIDR,192.168.0.0/24,DIRECT
  - RULE-SET,ru-blocked,PROXY
  - RULE-SET,intel,PROXY
  - RULE-SET,wix,PROXY
  - RULE-SET,youtube,PROXY
  - RULE-SET,twitter,PROXY
  - RULE-SET,instagram,PROXY
  - RULE-SET,facebook,PROXY
  - RULE-SET,discord-domain,PROXY
  - RULE-SET,discord-ip,PROXY
  - DOMAIN,chatgpt.com,PROXY
  - DOMAIN-SUFFIX,4pda.to,PROXY
  - DOMAIN-SUFFIX,4pda.ru,PROXY
  - DOMAIN-SUFFIX,4pda.ws,PROXY
  - IP-CIDR,31.131.253.250/32,PROXY # IP сайта 4PDA для работы приложения
  - MATCH,DIRECT
```

### Description

When starting program, port forwarding on router stops working

### Reproduction Steps

Start program, no access to home server
