### ISSUE TITLE
[Bug] UDP会话已经建立了应答状态， 但是仍被超时关闭

### ISSUE THREAD

**Issue by xcstatus** [MetaCubeX/mihomo#1742]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [X] 我是中文用户，而非其他语言用户
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [X] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [X] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 系统版本

15.1.1

### Mihomo 版本

alpha-89dfabe

### 配置文件

```yaml
mode: rule
mixed-port: 7897
allow-lan: false
log-level: warning
external-controller: 127.0.0.1:9097
secret: ''
unified-delay: true
dns:
  use-system-hosts: false
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
tun:
  udp-timeout: -1
  auto-detect-interface: true
  auto-route: true
  device: Mihomo
  dns-hijack:
  - any:53
  mtu: 1500
  stack: mixed
  strict-route: false
  enable: true
external-controller-cors:
  allow-private-network: true
  allow-origins:
  - '*'
profile:
  store-selected: true
bind-address: '*'
```

### 描述

我同时使用了 Mihomo和netbird（一个wireguard软件）。 netbird代理的网段频繁的断开连接， 在添加了tun.udp-timeout=-1参数后情况得到缓解。 netbird建立的p2p是upd协议，且经过了MIhomo，所以我怀疑Mihomo将应答状态的udp给关闭了。

ping 192.168.0.1 | while read line; do echo "$(date '+%Y-%m-%d %H:%M:%S') $line"; done
2024-12-24 17:14:27 PING 192.168.0.1 (192.168.0.1): 56 data bytes
2024-12-24 17:14:27 64 bytes from 192.168.0.1: icmp_seq=0 ttl=63 time=19.388 ms
2024-12-24 17:14:28 64 bytes from 192.168.0.1: icmp_seq=1 ttl=63 time=19.077 ms
2024-12-24 17:14:29 64 bytes from 192.168.0.1: icmp_seq=2 ttl=63 time=13.414 ms
2024-12-24 17:16:00 64 bytes from 192.168.0.1: icmp_seq=92 ttl=63 time=11.089 ms
2024-12-24 17:16:01 64 bytes from 192.168.0.1: icmp_seq=93 ttl=63 time=9.985 ms
2024-12-24 17:16:02 64 bytes from 192.168.0.1: icmp_seq=94 ttl=63 time=11.597 ms
2024-12-24 17:16:03 64 bytes from 192.168.0.1: icmp_seq=95 ttl=63 time=11.577 ms
2024-12-24 17:16:05 Request timeout for icmp_seq 96
2024-12-24 17:16:06 Request timeout for icmp_seq 97
2024-12-24 17:16:07 Request timeout for icmp_seq 98
2024-12-24 17:16:07 64 bytes from 192.168.0.1: icmp_seq=99 ttl=63 time=13.726 ms
2024-12-24 17:16:08 64 bytes from 192.168.0.1: icmp_seq=100 ttl=63 time=16.622 ms
2024-12-24 17:16:09 64 bytes from 192.168.0.1: icmp_seq=101 ttl=63 time=8.893 ms
2024-12-24 17:16:10 64 bytes from 192.168.0.1: icmp_seq=102 ttl=63 time=10.162 ms
2024-12-24 17:16:11 64 bytes from 192.168.0.1: icmp_seq=103 ttl=63 time=11.768 ms
2024-12-24 17:16:12 64 bytes from 192.168.0.1: icmp_seq=104 ttl=63 time=10.396 ms
2024-12-24 17:16:13 64 bytes from 192.168.0.1: icmp_seq=105 ttl=63 time=13.378 ms
2024-12-24 17:16:14 64 bytes from 192.168.0.1: icmp_seq=106 ttl=63 time=14.404 ms
2024-12-24 17:16:15 64 bytes from 192.168.0.1: icmp_seq=107 ttl=63 time=14.004 ms
2024-12-24 17:17:02 64 bytes from 192.168.0.1: icmp_seq=154 ttl=63 time=14.267 ms
2024-12-24 17:17:03 64 bytes from 192.168.0.1: icmp_seq=155 ttl=63 time=12.357 ms
2024-12-24 17:17:04 64 bytes from 192.168.0.1: icmp_seq=156 ttl=63 time=13.294 ms
2024-12-24 17:17:05 64 bytes from 192.168.0.1: icmp_seq=157 ttl=63 time=15.530 ms
2024-12-24 17:17:06 64 bytes from 192.168.0.1: icmp_seq=158 ttl=63 time=11.549 ms
2024-12-24 17:17:07 64 bytes from 192.168.0.1: icmp_seq=159 ttl=63 time=10.379 ms
2024-12-24 17:17:09 Request timeout for icmp_seq 160
2024-12-24 17:17:10 Request timeout for icmp_seq 161
2024-12-24 17:17:11 Request timeout for icmp_seq 162
2024-12-24 17:17:12 Request timeout for icmp_seq 163
2024-12-24 17:17:13 Request timeout for icmp_seq 164
2024-12-24 17:17:14 Request timeout for icmp_seq 165
2024-12-24 17:17:15 Request timeout for icmp_seq 166
2024-12-24 17:17:16 Request timeout for icmp_seq 167
2024-12-24 17:17:17 Request timeout for icmp_seq 168
2024-12-24 17:17:18 Request timeout for icmp_seq 169
2024-12-24 17:17:19 Request timeout for icmp_seq 170
2024-12-24 17:17:20 Request timeout for icmp_seq 171
2024-12-24 17:17:21 Request timeout for icmp_seq 172
2024-12-24 17:17:22 Request timeout for icmp_seq 173
2024-12-24 17:17:23 Request timeout for icmp_seq 174
2024-12-24 17:17:23 64 bytes from 192.168.0.1: icmp_seq=175 ttl=63 time=15.451 ms
2024-12-24 17:17:24 64 bytes from 192.168.0.1: icmp_seq=176 ttl=63 time=13.480 ms
2024-12-24 17:17:25 64 bytes from 192.168.0.1: icmp_seq=177 ttl=63 time=11.083 ms
2024-12-24 17:17:26 64 bytes from 192.168.0.1: icmp_seq=178 ttl=63 time=12.291 ms
2024-12-24 17:17:27 64 bytes from 192.168.0.1: icmp_seq=179 ttl=63 time=22.579 ms
2024-12-24 17:17:28 64 bytes from 192.168.0.1: icmp_seq=180 ttl=63 time=13.507 ms
2024-12-24 17:17:29 64 bytes from 192.168.0.1: icmp_seq=181 ttl=63 time=11.090 ms
2024-12-24 17:17:30 64 bytes from 192.168.0.1: icmp_seq=182 ttl=63 time=14.836 ms
2024-12-24 17:23:02 64 bytes from 192.168.0.1: icmp_seq=513 ttl=63 time=9.505 ms
2024-12-24 17:23:03 64 bytes from 192.168.0.1: icmp_seq=514 ttl=63 time=10.239 ms
2024-12-24 17:23:04 64 bytes from 192.168.0.1: icmp_seq=515 ttl=63 time=9.236 ms
2024-12-24 17:23:05 64 bytes from 192.168.0.1: icmp_seq=516 ttl=63 time=14.833 ms
2024-12-24 17:23:07 Request timeout for icmp_seq 517
2024-12-24 17:23:08 Request timeout for icmp_seq 518
2024-12-24 17:23:09 Request timeout for icmp_seq 519
2024-12-24 17:23:10 Request timeout for icmp_seq 520
2024-12-24 17:23:11 Request timeout for icmp_seq 521

### 重现方式

建立一个upd连接 保持upd连接。 测试Mihomo是否会关闭这个upd连接
