### ISSUE TITLE
[Bug] SS2022 UDP_OVER_TCP 版本无法修改

### ISSUE THREAD

**Issue by Mitsuhaxy** [MetaCubeX/mihomo#1761]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [X] 我是中文用户，而非其他语言用户
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [X] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [X] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

OpenWRT 23.04.5

### Mihomo 版本

Mihomo Meta v1.19.1 linux amd64 with go1.23.4

### 配置文件

```yaml
proxies:
- name: "NODE"
  type: ss
  server:
  port:
  cipher: 2022-blake3-aes-128-gcm
  password:
  udp: true
  udp-over-tcp: true
  udp-over-tcp-version: 1
```

### 描述

使用上述配置文件，ss2022 uot 设置为v1，udp 不通，服务器端使用shadowsocks-rust，错误日志如下：
tcp server stream aborted with error: dns resolve sp.v2.udp-over-tcp.arpa:0 error: no record found for Query { name: Name("sp.v2.udp-over-tcp.arpa.vm-fewkspo6."), query_type: A, query_class: IN }

### 重现方式

稳定复现
