### ISSUE TITLE
[Feature] Tun模式增加按端口范围包括/排除流量

### ISSUE THREAD

**Issue by okhowang** [MetaCubeX/mihomo#1769]
### Verification Steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and confirmed that this feature is not implemented
- [X] I have searched for the feature request I want to propose in the [Issue Tracker](……/) and did not find it
- [ ] I am a non-Chinese user.

### Description

我的场景类似于#984
是混合使用tailscale和tun
由于tun会劫持掉tailscale的udp包，相当于天然多一层nat，导致tailscale很难打洞直连成功。
如果可以按tailscale的端口排除掉流量，让tailscale的udp包直连，那么两者跑起来会更顺畅，也会减少额外的资源占用

**Comment by xishang0128** [comment]
@okhowang ip route不支持端口

**Comment by okhowang** [comment]
我这边测试在mihomo的添加的ip rule的基础上加了一条 就可以按端口跳过mihomo的劫持了
```shell
$ ip rule
0:      from all lookup local
8999:   from all sport 41641 goto 9010 # 跳过来源端口为41641
9000:   from all to 198.18.0.0/30 lookup 2022
9001:   not from all dport 53 lookup main suppress_prefixlength 0
9001:   from all iif ztMeta goto 9010
9002:   not from all iif lo lookup 2022
9002:   from 0.0.0.0 iif lo lookup 2022
9002:   from 198.18.0.0/30 iif lo lookup 2022
9010:   from all nop
32766:  from all lookup main
32767:  from all lookup default
```

**Comment by klttr** [comment]
> 我这边测试在mihomo的添加的ip rule的基础上加了一条 就可以按端口跳过mihomo的劫持了
> 
> $ ip rule
> 0:      from all lookup local
> 8999:   from all sport 41641 goto 9010 # 跳过来源端口为41641
> 9000:   from all to 198.18.0.0/30 lookup 2022
> 9001:   not from all dport 53 lookup main suppress_prefixlength 0
> 9001:   from all iif ztMeta goto 9010
> 9002:   not from all iif lo lookup 2022
> 9002:   from 0.0.0.0 iif lo lookup 2022
> 9002:   from 198.18.0.0/30 iif lo lookup 2022
> 9010:   from all nop
> 32766:  from all lookup main
> 32767:  from all lookup default

```yaml
tun:
  enable: true
  mtu: 9000
  strict-route: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  exclude-dst-port-range:
    - "0:79"
    - "81:442"
    - "444:5227"
    - "5231:65535"
```
``` shell
# ip rule
0:      from all lookup local
9000:   from all fwmark 0x2024 goto 9002
9001:   from all fwmark 0x2023 lookup 2022
9002:   from all nop
32766:  from all lookup main
32767:  from all lookup default
```
大佬，麻烦看看呢；为什么我添加了exclude-dst-port-range ``ip rule``中没有相关的信息呢；使用的最新稳定版本
