### ISSUE TITLE
[Bug] 反馈tuic和hysteria观看抖音直播卡顿阻塞问题

### ISSUE THREAD

**Issue by wenzhuning** [MetaCubeX/mihomo#1775]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [X] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [X] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [X] I am a non-Chinese user.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [X] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [X] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [X] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Android

### System Version

android12

### Mihomo Version

1.19.1

### Configuration File

```yaml
listeners:
- name: tproxy-in
  type: tproxy
  port: 1536
  listen: 0.0.0.0
  udp: true
redir-port: 7891

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]


log-level: error

ipv6: false

tcp-concurrent: false

unified-delay: true

disable-keep-alive: false
keep-alive-interval: 600
keep-alive-idle: 600

experimental:
  quic-go-disable-gso: true
  quic-go-disable-ecn: true

profile:
  store-selected: true

geodata-loader: standard


rule-providers:
  
  privateip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./rules/privateip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/privateip.mrs"
    interval: 86400
   
  cn:
    type: http
    behavior: domain
    format: mrs
    path: ./rules/cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cn.mrs"
    interval: 86400
  
  cnip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./rules/cnip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cnip.mrs"
    interval: 86400
  
  ads:
    type: http
    behavior: domain
    format: mrs
    path: ./rules/ads.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ads.mrs"
    interval: 86400


proxies:
- name: "proxy"
  type: vmess
  ip-version: ipv4
  server: ****
  port: ****
  uuid: ****
  alterId: 0
  udp: true
  tfo: false
  tls: false
  cipher: auto
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ****
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol

- name: "cn"
  type: vmess
  ip-version: ipv4
  server: ****
  port: ****
  uuid: ****
  alterId: 0
  udp: true
  tfo: false
  tls: false
  cipher: auto
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ****
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol

- name: "cn2"
  type: tuic
  server: ****
  port: ****
  uuid: ****
  tls: true
  alpn:
  - h3
  skip-cert-verify: true
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  max-open-streams: 1024

- name: "cn3"
  type: tuic
  server: ****
  port: ****
  uuid: ****
  tls: true
  alpn:
  - h3
  skip-cert-verify: true
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  max-open-streams: 1024

- name: "cn4"
  type: tuic
  server: ****
  port: ****
  uuid: ****
  tls: true
  alpn:
  - h3
  skip-cert-verify: true
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  max-open-streams: 1024

- name: "cn5"
  type: tuic
  server: ****
  port: ****
  uuid: ****
  tls: true
  alpn:
  - h3
  skip-cert-verify: true
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  max-open-streams: 1024

- name: "cn6"
  type: tuic
  server: ****
  port: ****
  uuid: ****
  tls: true
  alpn:
  - h3
  skip-cert-verify: true
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  max-open-streams: 1024

- name: "cn7"
  type: tuic
  server: ****
  port: ****
  uuid: ****
  tls: true
  alpn:
  - h3
  skip-cert-verify: true
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  max-open-streams: 1024

- name: "cn8"
  type: tuic
  server: ****
  port: ****
  uuid: ****
  tls: true
  alpn:
  - h3
  skip-cert-verify: true
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  max-open-streams: 1024

- name: "cn9"
  type: tuic
  server: ****
  port: ****
  uuid: ****
  tls: true
  alpn:
  - h3
  skip-cert-verify: true
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  max-open-streams: 1024

- name: "direct"
  type: direct

- name: "dns-out"
  type: dns


proxy-groups:
- name: "balance"
  type: load-balance
  proxies:
  - cn2
  - cn3
  - cn4
  - cn5
  - cn6
  - cn7
  - cn8
  - cn9
  strategy: round-robin


dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  nameserver:
    - 180.76.76.76


rules:
- DST-PORT,53,dns-out
- RULE-SET,privateip,direct
- RULE-SET,ads,REJECT-DROP
- RULE-SET,cn,balance
- RULE-SET,cnip,balance
- MATCH,proxy
```

### Description

实测，用基于quic的tuic协议和hysteria观看app（比如抖音，B站）的直播或者视频会导致阻塞卡顿，特别是直播，频繁出现卡顿，体验极差，用浏览器观看就不会出现这种情况。

目前的解决方法是：利用mihomo的负载均衡功能，将请求分散处理，可以缓解卡顿问题

要说明的是，这些出站节点的配置都是一样的，不一样的是节点name，实际上连接到的都是同一个vps的节点，个人猜测能缓解卡顿是因为mihomo内核使用负载均衡后，会有多个连接线程，比如当其中一个请求阻塞了cn2节点后，其他请求会被分发到cn3，cn4等节点，这样就不会导致卡顿。

另外，希望有大佬能更好的解决此问题，利用负载均衡仍然会有概率出现卡顿问题

### Reproduction Steps

如上
