### ISSUE TITLE
[Bug] ss2022-blake3-chacha20-poly1305无法使用

### ISSUE THREAD

**Issue by seekajobs1337** [MetaCubeX/mihomo#1781]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [X] 我是中文用户，而非其他语言用户
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [X] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [X] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

win10 22H2

### Mihomo 版本

Alpha-c7661d7

### 配置文件

```yaml
- name: 香港1-ss
    type: ss
    server: 192.168.1.1
    port: 6666
    cipher: 2022-blake3-chacha20-poly1305
    password: 2022blake3aes128gcm
    udp: true
    tfo: true
```

### 描述

测试延迟秒返回error,delay=65535，同ip同端口使用aes128gcm正常通联（排除被墙）

### 重现方式

客户端使用cipher: 2022-blake3-chacha20-poly1305加密即可

### 日志

```shell
time="2025-01-08T20:47:31.945931500+08:00" level=debug msg="Health Checked, proxy: 香港1-ss, url: https://www.gstatic.com/generate_204, alive: false, delay: 65535 ms uid: {89630a1c-4619-4812-93b0-0e8e024b4ad7}"
```
