### ISSUE TITLE
[Bug] 使用OpenClash加载配置 运行时内核崩溃

### ISSUE THREAD

**Issue by yuntong613** [MetaCubeX/mihomo#1804]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [x] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Linux

### System Version

openclash 

### Mihomo Version

openclash/core、mihomo/release latest version 都会出错

### Configuration File

```yaml
---
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
proxies:
  # ====proxy list====
rules:
  # ====rule list====
dns:
  enable: true
  nameserver-policy:
    geosite:cn:
    - 119.29.29.29
    - 223.5.5.5
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - 223.5.5.5
  - 119.29.29.29
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  default-nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - 223.5.5.5
authentication:
- Clash:xnyMCMXJ
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
secret: clash
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
keep-alive-interval: 15
keep-alive-idle: 600
ipv6: false
geodata-mode: true
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
profile:
  store-selected: true
```

### Description

	github.com/metacubex/mihomo/common/batch/batch.go:43 +0xb9
created by github.com/metacubex/mihomo/common/batch.(*Batch[...]).Go in goroutine 113
	github.com/metacubex/mihomo/common/batch/batch.go:52 +0xfd
github.com/metacubex/mihomo/common/batch.(*Batch[...]).Go.func1()
	github.com/metacubex/mihomo/adapter/provider/healthcheck.go:202 +0x1b8
github.com/metacubex/mihomo/adapter/provider.(*HealthCheck).execute.func1()
	github.com/metacubex/mihomo/adapter/adapter.go:228 +0x290
github.com/metacubex/mihomo/adapter.(*Proxy).URLTest(0xc000610db0, {0x16becc0, 0xc0001be700}, {0xc0002cfd40, 0x23}, {0x0, 0x0, 0x43ba69?})
	github.com/metacubex/mihomo/adapter/adapter.go:67
github.com/metacubex/mihomo/adapter.(*Proxy).DialContext(...)
	github.com/metacubex/mihomo/adapter/outbound/shadowsocksr.go:68 +0xf4
github.com/metacubex/mihomo/adapter/outbound.(*ShadowSocksR).DialContext(0xc00016ab00, {0x16becc0, 0xc0001be700}, 0xc002ac7680, {0x0?, 0x0?, 0x0?})
	github.com/metacubex/mihomo/adapter/outbound/shadowsocksr.go:88 +0x22a
github.com/metacubex/mihomo/adapter/outbound.(*ShadowSocksR).DialContextWithDialer(0xc00016ab00, {0x16becc0, 0xc0001be700}, {0x16b1fd0?, 0xc000402660?}, 0xc002ac7680)
	github.com/metacubex/mihomo/adapter/outbound/shadowsocksr.go:62 +0x163
github.com/metacubex/mihomo/adapter/outbound.(*ShadowSocksR).StreamConnContext(0xc00016ab00, {0x16becc0?, 0xc0001be700?}, {0x16ca490?, 0xc002efda40?}, 0xc002ac7680)
	github.com/metacubex/mihomo/transport/ssr/protocol/stream.go:45 +0x112
github.com/metacubex/mihomo/transport/ssr/protocol.(*Conn).Write(0xc0001bea80, {0xc0024d4750, 0x13, 0x13})
	github.com/metacubex/mihomo/transport/shadowsocks/shadowstream/stream.go:155 +0x55
github.com/metacubex/mihomo/transport/shadowsocks/shadowstream.(*Conn).Write(0xc001000240?, {0xc001bd8900?, 0x318?, 0x900?})
	github.com/metacubex/mihomo/transport/shadowsocks/shadowstream/stream.go:28 +0xf5
github.com/metacubex/mihomo/transport/shadowsocks/shadowstream.(*Writer).Write(0xc0004c0d08, {0xc001bd8900, 0x318, 0x900})
	golang.org/x/crypto@v0.31.0/chacha20/chacha_generic.go:218 +0x3f8
golang.org/x/crypto/chacha20.(*Cipher).XORKeyStream(0xc002efda80?, {0xc0004c0d28?, 0x318?, 0x800?}, {0xc001bd8900?, 0x318?, 0x900?})
goroutine 465 [running]:
panic: chacha20: counter overflow

### Logs

```shell

```
