### ISSUE TITLE
[Feature] default-nameserver未按预期工作

### ISSUE THREAD

**Issue by hanepudding** [MetaCubeX/mihomo#1808]
### 验证步骤

- [ ] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [ ] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [x] 我是中文用户，而非其他语言用户

### 描述

// 这可能是一个bug，但我的技术不足，无力满足bug issue里的所有要求，只好提在这里，请多包涵。

内核版本: 1.19.1
界面: mihomo party（sorry增加实体）

（用户）预期行为：通过default-nameserver（ 1.1.1.1 ）去解析 cloudflare-dns.com ，进一步由 cloudflare-dns.com 提供服务。
实际行为：内核向cloudflare-dns.com发起请求前需要知道cloudflare-dns.com的ip地址，于是准备查询地址，向 cloudflare-dns.com 请求查询 cloudflare-dns.com 的地址，产生循环依赖。

我意识到这可能是预期行为：DoH是https流量，被内核当作普通的流量进行分流。但这导致了难以排查的循环依赖问题，希望至少在docs中加以描述与提醒，尤其是default-nameserver可能不会按描述的那样正确解析其他dns服务器。

我将展示2份DNS配置以及对应的2份日志。1份失败，1份成功。

第一份配置：失败
当dns模块配置为：

```yaml
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - +.lan
    - +.local
    - time.*.com
    - ntp.*.com
    - +.market.xiaomi.com
  use-hosts: false
  use-system-hosts: false
  nameserver:
    - https://cloudflare-dns.com/dns-query
  proxy-server-nameserver:
    - https://cloudflare-dns.com/dns-query
  direct-nameserver:
    - 180.76.76.76
    - 223.5.5.5
  respect-rules: true
  default-nameserver:
    - 1.1.1.1
```
这会导致无法解析一个节点域名 example.dns.army :

```ini
Auth success from 127.0.0.1:59150 ->
[Sniffer] All sniffing sniff failed with from [127.0.0.1:59150] to [192.168.2.1:80]
[Rule] use default rules
[DNS] resolve example.dns.army A from https://cloudflare-dns.com:443/dns-query
[DNS] resolve example.dns.army AAAA from https://cloudflare-dns.com:443/dns-query
[DNS] cache hit cloudflare-dns.com --> [104.16.248.249 104.16.249.249] A, expire at 2025-01-23 11:46:08
[DNS] cache hit cloudflare-dns.com --> [2606:4700::6810:f8f9 2606:4700::6810:f9f9] AAAA, expire at 2025-01-23 11:48:44
re-creating the http client due to requesting https://cloudflare-dns.com:443/dns-query: Get "https://cloudflare-dns.com:443/dns-query?dns=AAABAAABAAAAAAAAB2V4YW1wbGUDZG5zBGFybXkAABwAAQ": context deadline exceeded
[TCP] dial Lan (match RuleSet/Lan) 127.0.0.1:59150 --> 192.168.2.1:80 error: example.dns.army:54321 connect error: dns resolve failed: couldn't find ip
[https://cloudflare-dns.com:443/dns-query] using HTTP/2 for this upstream: <nil>
re-creating the http client due to requesting https://cloudflare-dns.com:443/dns-query: Get "https://cloudflare-dns.com:443/dns-query?dns=AAABAAABAAAAAAAAB2V4YW1wbGUDZG5zBGFybXkAABwAAQ": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[https://cloudflare-dns.com:443/dns-query] using HTTP/2 for this upstream: <nil>
re-creating the http client due to requesting https://cloudflare-dns.com:443/dns-query: Get "https://cloudflare-dns.com:443/dns-query?dns=AAABAAABAAAAAAAAB2V4YW1wbGUDZG5zBGFybXkAABwAAQ": context deadline exceeded
[https://cloudflare-dns.com:443/dns-query] using HTTP/2 for this upstream: <nil>
re-creating the http client due to requesting https://cloudflare-dns.com:443/dns-query: Get "https://cloudflare-dns.com:443/dns-query?dns=AAABAAABAAAAAAAAB2V4YW1wbGUDZG5zBGFybXkAABwAAQ": context deadline exceeded
[https://cloudflare-dns.com:443/dns-query] using HTTP/2 for this upstream: <nil>
[Rule] use default rules
[DNS] resolve example.dns.army A from https://cloudflare-dns.com:443/dns-query
[DNS] resolve example.dns.army AAAA from https://cloudflare-dns.com:443/dns-query
[DNS] cache hit cloudflare-dns.com --> [2606:4700::6810:f8f9 2606:4700::6810:f9f9] AAAA, expire at 2025-01-23 11:48:44
[DNS] cache hit cloudflare-dns.com --> [104.16.248.249 104.16.249.249] A, expire at 2025-01-23 11:46:08
[TCP] dial Lan (match RuleSet/Lan) 198.18.0.1:22000 --> 192.168.2.4:22000 error: example.dns.army:54321 connect error: dns resolve failed: couldn't find ip
re-creating the http client due to requesting https://cloudflare-dns.com:443/dns-query: Get "https://cloudflare-dns.com:443/dns-query?dns=AAABAAABAAAAAAAAB2V4YW1wbGUDZG5zBGFybXkAABwAAQ": context deadline exceeded
[https://cloudflare-dns.com:443/dns-query] using HTTP/2 for this upstream: <nil>
re-creating the http client due to requesting https://cloudflare-dns.com:443/dns-query: Get "https://cloudflare-dns.com:443/dns-query?dns=AAABAAABAAAAAAAAB2V4YW1wbGUDZG5zBGFybXkAABwAAQ": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[https://cloudflare-dns.com:443/dns-query] using HTTP/2 for this upstream: <nil>
re-creating the http client due to requesting https://cloudflare-dns.com:443/dns-query: Get "https://cloudflare-dns.com:443/dns-query?dns=AAABAAABAAAAAAAAB2V4YW1wbGUDZG5zBGFybXkAABxAAQ": context deadline exceeded
[https://cloudflare-dns.com:443/dns-query] using HTTP/2 for this upstream: <nil>
re-creating the http client due to requesting https://cloudflare-dns.com:443/dns-query: Get "https://cloudflare-dns.com:443/dns-query?dns=AAABAAABAAAAAAAAB2V4YW1wbGUDZG5zBGFybXkAABwAAQ": context deadline exceeded
```
看起来它尝试通过 https://cloudflare-dns.com:443/dns-query 去解析 https://cloudflare-dns.com:443/dns-query ，即循环依赖。注意到这份日志中default-nameserver从未出现过——它没有起到任何作用。
有2种方法解决：
1. 将“代理服务器域名解析”改为 1.1.1.1 
2. 指定出口： https://cloudflare-dns.com/dns-query#Gateway ，在第二份配置中展示

第二份配置：成功
当dns模块配置为：

```yaml
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - +.lan
    - +.local
    - time.*.com
    - ntp.*.com
    - +.market.xiaomi.com
  use-hosts: false
  use-system-hosts: false
  nameserver:
    - https://cloudflare-dns.com/dns-query#Gateway
  proxy-server-nameserver:
    - https://cloudflare-dns.com/dns-query#Gateway
  direct-nameserver:
    - 180.76.76.76#DIRECT
    - 223.5.5.5#DIRECT
  respect-rules: true
  default-nameserver:
    - 1.1.1.1#Gateway
```
这样配置能够成功访问节点服务器，日志如下：
```ini
Auth success from 127.0.0.1:60734 ->
[Sniffer] Skip sniffing[192.168.2.1:80] due to multiple failures
[Rule] use default rules
[DNS] resolve example.dns.army A from https://cloudflare-dns.com:443/dns-query
[DNS] cache hit example.dns.army --> [240e:304:2c93:2400::1] AAAA, expire at 2025-01-23 12:05:22
[DNS] example.dns.army --> [] A from https://cloudflare-dns.com:443/dns-query
[TCP] 127.0.0.1:60734 --> 192.168.2.1:80 match RuleSet(Lan) using Lan[Kamome]

Auth success from 127.0.0.1:60736 ->
[Sniffer] Skip sniffing[192.168.2.1:80] due to multiple failures
[Rule] use default rules
[DNS] resolve example.dns.army A from https://cloudflare-dns.com:443/dns-query
[DNS] cache hit example.dns.army --> [240e:304:2c93:2400::1] AAAA, expire at 2025-01-23 12:05:22

[DNS] example.dns.army --> [] A from https://cloudflare-dns.com:443/dns-query
[TCP] 127.0.0.1:60736 --> 192.168.2.1:80 match RuleSet(Lan) using Lan[Kamome]
```

观点在结尾重复一次：
这可能是预期行为：DoH是https流量，被内核当作普通的流量进行分流。但这导致了难以排查的循环依赖问题，希望至少在docs中加以描述与提醒，尤其是default-nameserver可能不会按描述的那样正确解析其他dns服务器。

附：您可能注意到了奇怪的地方，比如目标地址是 192.168.2.0/24 之类的。这是因为这个节点搭建在我的家里，是用于我从家外访问家中的服务的。
