### ISSUE TITLE
[Bug] Windows中sc create注册为系统服务启动会一直显示启动中，然后超时失败。

### ISSUE THREAD

**Issue by Paper-Dragon** [MetaCubeX/mihomo#1809]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

Microsoft Windows 11 Enterprise LTSC 2024

### Mihomo 版本

mihomo-windows-386.exe -v
Mihomo Meta v1.19.1 windows 386 with go1.23.4 Tue Dec 31 16:58:28 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
mixed-port: 8888
# https://d.metacubex.one
# http://yacd.metacubex.one/
# http://board.zash.run.place/#/settings
external-controller: 127.0.0.1:9090


mode: rule
allow-lan: true

log-level: debug # 日志等级 silent/error/warning/info/debug

dns:
  enable: true

sniffer:
  enable: true

#  find-process-mode has 3 values:always, strict, off
#  - always, 开启，强制匹配所有进程
#  - strict, 默认，由 mihomo 判断是否开启
#  - off, 不匹配进程，推荐在路由器上使用此模式
find-process-mode: always



proxies:
  - name: 直连节点
    type: direct
    udp: true
    # ip-version: ipv4
    # interface-name: eth0
    # routing-mark: 1234

proxy-groups:
  - name: 直连组
    type: select
    proxies:
      - 直连节点

rules:
  - MATCH,直连组
```

### 描述

sc创建服务后不能工作，命令行运行后会显示启动中状态，然后超时失败。

### 重现方式

命令行运行正常运行正常工作，我的命令行是
```powershell
mihomo-windows-386.exe -d .
time="2025-01-23T15:14:00.228276000+08:00" level=info msg="Start initial configuration in progress"
time="2025-01-23T15:14:00.258740500+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2025-01-23T15:14:00.259383200+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2025-01-23T15:14:00.269629100+08:00" level=info msg="Initial configuration complete, total time: 11ms"
time="2025-01-23T15:14:00.270177000+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2025-01-23T15:14:00.275150900+08:00" level=info msg="Sniffer is loaded and working"
time="2025-01-23T15:14:00.276912900+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:8888"
time="2025-01-23T15:14:00.278921600+08:00" level=info msg="Start initial Compatible provider 直连组"
time="2025-01-23T15:14:00.279713900+08:00" level=info msg="Start initial Compatible provider default"
```

我创建服务的命令是
```powershell
sc create "yyyy" binPath= "C:\path\to\mihomo-windows-386.exe  -d  C:\path\to" start= auto DisplayName= "YYYY Service"

```

```powershell
sc start yyyy
[SC] StartService 失败 1053:

服务没有及时响应启动或控制请求。
```

### 日志

```shell
无法获取日志
```
