### ISSUE TITLE
[Bug] fake-ip无法正常使用

### ISSUE THREAD

**Issue by Kwisma** [MetaCubeX/mihomo#1816]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [x] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Android

### System Version

14

### Mihomo Version

Clash mate for Android 2.11.5

### Configuration File

```yaml
dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  default-nameserver:
    - 223.5.5.5
    - '[2402:4e00::]'
  nameserver:
    - 'tls://8.8.4.4'
    - 'tls://[2001:4860:4860::8844]'
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
```

### Description

访问部分url导致dns失败

### Reproduction Steps

使用 fake-ip ，打开指定软件，检测超时
使用redir-host，打开指定软件，检测正常

### Logs

```shell
<script src="https://gist.github.com/Kwisma/5343071fd88200cfbbf80b2348a6838d.js"></script>
```
