### ISSUE TITLE
[Bug] mihomo 在 immortalwrt 上无法调用 tcp-brutal

### ISSUE THREAD

**Issue by love4taylor** [MetaCubeX/mihomo#1820]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 系统版本

ImmortalWrt 24.10.0-rc4 r32779-d475f4e4007b

### Mihomo 版本

Mihomo Meta alpha-192d769 linux arm64 with go1.23.4 2025-01-20T12:03:38+00:00
Use tags: with_gvisor

### 配置文件

```yaml
proxies:
  - name: "****"
    type: ss
    server: ****
    port: ****
    cipher: 2022-blake3-aes-256-gcm
    password: "****"
    udp: true
    smux:
      enabled: true
      protocol: h2mux
      padding: true
      brutal-opts:
        enabled: true
        up: 300
        down: 1000
```

### 描述

```
69110:32:28warning[TCP] dial GLOBAL 192.168.87.10:54441 --> gateway.fe2.apple-dns.net:443 error: brutal exchange: remote error: enable TCP Brutal: setsockopt IPPROTO_TCP TCP_CONGESTION brutal: no such file or directory: please make sure you have installed the tcp-brutal kernel module
```

```
root@ImmortalWrt:~# lsmod | grep brutal
brutal                 16384  1 
root@ImmortalWrt:~# 
root@ImmortalWrt:~# sysctl -a | grep brutal
net.ipv4.tcp_allowed_congestion_control = reno cubic brutal
net.ipv4.tcp_available_congestion_control = reno cubic brutal
```

### 重现方式

使用 ImmortalWrt 24.10.0-rc4 r32779-d475f4e4007b 的 SDK 编译出 https://github.com/haruue-net/openwrt-tcp-brutal 的模块并安装且挂载模块，然后使用带 tcp-brutal 的配置文件启动 mihomo

### 日志

```shell

```
