### ISSUE TITLE
[Feature] 支持嵌套的proxy group

### ISSUE THREAD

**Issue by universonic** [MetaCubeX/mihomo#1826]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [x] 我是中文用户，而非其他语言用户

### 描述

希望能够支持在proxy group中嵌套其它proxy group，类似于下面的配置：

```yaml
proxy-groups:
- name: default
  type: load-balance
  proxy-groups:
  - server1-group
  - server2-group
  - server3-group
  strategy: sticky-sessions
- name: "server1-group"
  type: fallback
  proxies:
  - server1-hysteria2
  - server1-mieru
  url: 'https://www.gstatic.com/generate_204'
  interval: 3
  lazy: false
- name: "server2-group"
  type: fallback
  proxies:
  - server2-hysteria2
  - server2-mieru
  url: 'https://www.gstatic.com/generate_204'
  interval: 3
  lazy: false
- name: "server3-group"
  type: fallback
  proxies:
  - server3-hysteria2
  - server3-mieru
  url: 'https://www.gstatic.com/generate_204'
  interval: 3
  lazy: false
```

因为运营商对UDP做了限制，hysteria2最近非常容易出现断流，尤其是晚高峰时。这样配置的好处是能够在hysteria2不可用时自动切换至下一个协议，然后通过嵌套的`proxy-groups`实现负载均衡。

谢谢
