### ISSUE TITLE
[Bug] 无法读取geosite.dat规则

### ISSUE THREAD

**Issue by Asukaaaaaa** [MetaCubeX/mihomo#1849]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

ImmortalWrt 21.02-SNAPSHOT r20627-015af9e3f2

### Mihomo 版本

Mihomo Meta v1.19.2 linux arm64 with go1.23.5 Sun Feb  9 13:21:51 UTC 2025
Use tags: with_gvisor

### 配置文件

```yaml
rules:
  - GEOSITE,CN,DIRECT
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
allow-lan: true
external-controller: 0.0.0.0:9090
secret: RCx83kza
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
keep-alive-interval: 15
keep-alive-idle: 600
log-level: debug
```

### 描述

刷了一个新固件后就无法读取geosite规则了，尝试过1.18.0、1.18.10和1.19.2版本均可复现
```
root@ASUSWRT:/etc/openclash/test# ./mihomo_1192 -t -d .
INFO[2025-02-17T22:50:11.925845856+08:00] Start initial configuration in progress
INFO[2025-02-17T22:50:11.950983304+08:00] Geodata Loader mode: memconservative  
INFO[2025-02-17T22:50:11.951379644+08:00] Geosite Matcher implementation: succinct
INFO[2025-02-17T22:50:11.963940789+08:00] Load GeoSite rule: cn                 
Killed
```
1.18.0会直接显示Killed退出，1.19.2会加载一段时间后退出
geosite使用的是[https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat](url)

### 重现方式

如描述里的操作

### 日志

```shell

```
