### ISSUE TITLE
[Feature] 关于 proxy-group 中引入 proxy-provider 的测速问题

### ISSUE THREAD

**Issue by dale0525** [MetaCubeX/mihomo#1862]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [x] 我是中文用户，而非其他语言用户

### 描述

官方文档中对于proxy-group的`url`的介绍：
> 只会检查代理组的 proxies 字段的代理，不会检查代理集合（proxy-providers）的代理（通过 use 引入的）。

这是不是意味着，如果有一个proxy-group使用了某个proxy-provider，如：
```
proxy-groups:
    - name: "AUTO"
      type: url-test
      use: 
        - a-provider
        - b-provider
      url: https://cp.cloudflare.com
      interval: 300
      tolerance: 20
      lazy: false
      hidden: false
```
那么当 AUTO 组节点失效时，无法触发主动测速，因为这里配置的`url`实际不生效，只能等待 proxy-provider 中配置的`health-check`触发才会切换节点。

另外一种可能的使用场景是，对于同一个 proxy-provider，可能希望根据不同 proxy-group 设置不同的测速地址。比如有一个香港的代理组和一个日本的代理组，引入了同一个代理集合，想要分别使用香港和日本的落地测速链接。

可能的优化方式：proxy-group 中的 url 也对使用 use 引入的节点生效，可以在代理组节点失效时触发主动测速，对引入的代理集合也进行测速。这样可以移除 proxy-provider 的 `health-check`配置。
