### ISSUE TITLE
[Bug] 使用开启了 TUN 的机器作为网关时, 发送的 UDP 流量, 网关无法接收到

### ISSUE THREAD

**Issue by popjdh** [MetaCubeX/mihomo#1866]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

Archlinux 6.13.3-arch1-1

### Mihomo 版本

Mihomo Meta 1.19.2 linux amd64 with go1.24.0 2025-02-18 17:35:29+00:00
Use tags: with_gvisor

### 配置文件

```yaml
log-level: info

mixed-port: 7890
allow-lan: true
ipv6: true

profile:
  store-selected: true
  store-fake-ip: true

find-process-mode: strict
unified-delay: false
tcp-concurrent: true
global-client-fingerprint: chrome

dns:
  enable: true
  ipv6: true
  listen: '127.0.0.1:5334'
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*"
  proxy-server-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  stack: mixed
  device: Meta
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

rules:
  - MATCH,DIRECT
```

### 描述

我的内网环境下, 有Linux 主机 A B, 都采用静态ip配置, 并接在路由器(192.168.124.1)的LAN口上

Linux主机A: IP为192.168.124.2, 网关为192.168.124.1, 启用mihomo
Linux主机B: IP为192.168.124.3, 网关为192.168.124.2

在Linux主机B上运行
-  `echo 111 | netcat -u baidu.com 1080` : mihomo 日志无相关记录, 出现 `read(net): No route to host` 错误信息 
-  `echo 111 | netcat baidu.com 1080` : mihomo 日志有相关记录

在Linux主机A上运行
-  `echo 111 | netcat -u baidu.com 1080` : mihomo 日志有相关记录
-  `echo 111 | netcat baidu.com 1080` : mihomo 日志有相关记录

我的 firewalld 关于 public zone 的配置为:
```bash
$ sudo firewall-cmd --zone=public --list-all      
public (default, active)
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: eno1
  sources: 
  services: dhcpv6-client samba ssh
  ports: 9090/tcp
  protocols: 
  forward: yes
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules:
```

### 重现方式

见上

### 日志

```shell
Feb 27 01:32:02 UM690Lite mihomo[40881]: time="2025-02-27T01:32:02.261700076+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) 192.168.124.3:56516 --> baidu.com:1080 error: dial tcp 110.242.68.66:1080: i/o timeout\ndial tcp 39.156.66.10:1080: i/o timeout"
Feb 27 01:32:19 UM690Lite mihomo[40881]: time="2025-02-27T01:32:19.898318273+08:00" level=info msg="[UDP] 198.18.0.1:40708 --> baidu.com:1080 match Match using DIRECT"
Feb 27 01:32:29 UM690Lite mihomo[40881]: time="2025-02-27T01:32:29.836082700+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) 192.168.124.2:35990 --> baidu.com:1080 error: dial tcp 110.242.68.66:1080: i/o timeout\ndial tcp 39.156.66.10:1080: i/o timeout"
```
