### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by JGXY007** [MetaCubeX/mihomo#1893]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

ubuntu20.04

### Mihomo 版本

mihomo-linux-amd64-compatible-v1.19.3

### 配置文件

```yaml
mixed-port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'

dns:
    enable: true
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver:
        - [REDACTED]
        - [REDACTED]
    fallback:
        - [REDACTED]
        - [REDACTED]
        - [REDACTED]
        - [REDACTED]
        - tls://8.8.4.4:853
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }

proxies:
    - { name: '剩余流量：91.88 GB', type: ss, server: [REDACTED], port: [REDACTED], cipher: [REDACTED], password: [REDACTED], udp: true }
    - { name: '专线-香港01', type: ss, server: [REDACTED], port: [REDACTED], cipher: [REDACTED], password: [REDACTED], udp: true }
    - { name: '专线-香港03', type: ss, server: [REDACTED], port: [REDACTED], cipher: [REDACTED], password: [REDACTED], udp: true }
    - { name: '专线-日本01', type: ss, server: [REDACTED], port: [REDACTED], cipher: [REDACTED], password: [REDACTED], udp: true }
    - { name: '专线-日本03', type: ss, server: [REDACTED], port: [REDACTED], cipher: [REDACTED], password: [REDACTED], udp: true }
    - { name: '专线-美国01', type: ss, server: [REDACTED], port: [REDACTED], cipher: [REDACTED], password: [REDACTED], udp: true }
    - { name: '中转-美国02', type: ss, server: [REDACTED], port: [REDACTED], cipher: [REDACTED], password: [REDACTED], udp: true }

proxy-groups:
    - { name: 稳连云, type: url-test, proxies: ['专线-香港01', '专线-香港03', '专线-日本01', '专线-日本03', '专线-美国01', '中转-美国02'], url: [REDACTED], interval: 86400 }

rules:
    - 'DOMAIN-SUFFIX,telegra.ph,稳连云'
    - 'DOMAIN-SUFFIX,telegram.org,稳连云'
    - 'DOMAIN-KEYWORD,google,稳连云'
    - 'DOMAIN-SUFFIX,services.googleapis.cn,稳连云'
    - 'DOMAIN,safebrowsing.googleapis.com,DIRECT'
    - 'GEOIP,CN,DIRECT'
    - 'MATCH,稳连云'
```

### 描述

https://nanodesu.net/archives/47/
我是根据上面链接的教程配置的mihomo在服务器上，可以运行，刚运行时占用的cpu很小，但是过了一段时间cpu占用就爆表了，显示100%，后面在服务器里top查看日志时mihomo cpu占用160%显示，然后服务器远程登陆连接不上，我在vnc连接关闭mihomo服务进程后，cpu使用恢复正常，后面测试了别的版本也是同样的问题，使用tmux运行时，后面也是cpu过高，使tmux进程自己关闭

### 重现方式

https://nanodesu.net/archives/47/
根据这个教程，然后用我的配置文件，一开始运行正常，但是运行一段时间过后，cpu占用过高

### 日志

```shell

```
