### ISSUE TITLE
[Bug] 同一个配置，配置文件不同写法产生不一样的效果

### ISSUE THREAD

**Issue by zeXtreme** [MetaCubeX/mihomo#1895]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

11

### Mihomo 版本

alpha-c0de3c0 Mihomo

### 配置文件

```yaml
***:
    type: inline
    payload:
      # - {name: "US-2", server: ***.me, port: *443, reality-opts: {public-key: **************_2qtzYxX7khNwA9gWyY, short-id: fff6}, client-fingerprint: chrome, type: vless, uuid: ********-0fc1-4371-b6df-a0a07446930c, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, servername: ***.me, network: tcp}
      - name: "US-2"
        type: vless
        server: ***.me
        port: *443
        ip-version: ipv4
        udp: true
        tfo: false
        uuid: ********-0fc1-4371-b6df-a0a07446930c
        flow: xtls-rprx-vision
        packet-encoding: xudp
        tls: true
        servername: ***.me
        fingerprint: chrome
        client-fingerprint: chrome
        skip-cert-verify: true
        reality-opts:
          public-key: **************_2qtzYxX7khNwA9gWyY
          short-id: fff6
        network: tcp
```

### 描述

同一个reality协议配置，使用上面注释中的配置写法时可以正常连接，使用下面的写法无法连接，服务端日志显示
```
REALITY remoteAddr: 154.92.***.**:53115
REALITY remoteAddr: 154.92.***.**:53115	hs.c.handshakeStatus: false
```

### 重现方式

使用下面的配置写法

### 日志

```shell
03-11 17:19:38debug
[DNS] cache hit ***.me --> [*.*.*.*] A, expire at 2025-03-11 17:20:17
03-11 17:19:38warning
[TCP] dial Github (match RuleSet/github_domain) 127.0.0.1:11660 --> alive.github.com:443 error: ***.me:8443 connect error: encoding/hex: invalid byte: U+0068 'h'
03-11 17:19:38debug
[DNS] cache hit ***.me --> [*.*.*.*] A, expire at 2025-03-11 17:20:17
03-11 17:19:38warning
[TCP] dial Telegram (match RuleSet/telegram_ip) 127.0.0.1:11644 --> 91.108.56.121:443 error: ***.me:8443 connect error: encoding/hex: invalid byte: U+0068 'h'
03-11 17:19:38debug
[DNS] cache hit ***.me --> [*.*.*.*] A, expire at 2025-03-11 17:20:17
03-11 17:19:38warning
[TCP] dial Github (match RuleSet/github_domain) 127.0.0.1:11660 --> alive.github.com:443 error: ***.me:8443 connect error: encoding/hex: invalid byte: U+0068 'h'
```
