### ISSUE TITLE
[Bug] `tun.stack=system` on Android 15 w/ 4.19 kernel (LOS 22.1) incorrectly route IPv6 packages, while `gvisor` works

### ISSUE THREAD

**Issue by nexplorer-3e** [MetaCubeX/mihomo#1903]
### 验证步骤

- [ ] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Android

### 系统版本

[lineage-22.1-20250310-nightly-munch-signed](https://download.lineageos.org/devices/munch/builds)

### Mihomo 版本

```
Mihomo Meta alpha-a7a796b android arm64 with go1.24.1 Thu Mar 13 08:32:34 UTC 2025
Use tags: with_gvisor
```

### 配置文件

<details><summary>Details</summary>
<p>

```yaml
log-level: debug
# redir-port: 9797
# tproxy-port: 9898
mixed-port: 7890
# unified-delay: true
geo-auto-update: true
geo-update-interval: 24
geodata-mode: true
keep-alive-interval: 90
tcp-concurrent: true
enable-process: true
find-process-mode: always

mode: rule
allow-lan: true
bind-address: '*'
external-controller: 0.0.0.0:9090
external-secret: ''
external-ui: './dashboard'

# do health check in proxy (group), deprecate this
# hp: &hp {interval: 10800, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}
# hp-gh: &hp-gh {interval: 10800, health-check: {enable: true, url: https://raw.githubusercontent.com, expected-status: 301, interval: 300}}

profile:
  store-selected: true
  # 储存 API 对策略组的选择，以供下次启动时使用
  store-fake-ip: false
  # 储存 fakeip 映射表，域名再次发生连接时，使用原有映射地址

sniffer:
  enable: true
  force-dns-mapping: true
  sniff: # TLS 默认如果不配置 ports 默认嗅探 443
    TLS:
      ports: [443, 8443]
    HTTP: # 需要嗅探的端口, 默认嗅探 80
      ports: [80, 8080-8880]
  force-domain:
    - '+.v2ex.com'
  # 白名单,跳过嗅探结果
  skip-domain:
    - 'Mijia Cloud'
    - '+.cn'
    - 'geosite:private'

tun:
  enable: true
  mtu: 9000
  device: utun
  stack: system # gvisor / system / lwip
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  # strict-route: true
  auto-detect-interface: true
  include-android-user: [0, 10]
  exclude-package:
    - 'com.android.captiveportallogin'
    - 'com.xingin.xhs'
    - 'com.UCMobile'
    - 'org.localsend.localsend_app'
    # blacklist
  include-package: [] # whitelist

dns:
  enable: true
  listen: ':1053'
  ipv6: true
  enhanced-mode: 'redir-host'
  use-hosts: true
  hosts:
    'yasho.ku':
      'x.com'
    'dns.alidns.com':
      - '223.5.5.5'
      - '223.6.6.6'
      - '2400:3200::1'
      - '2400:3200:baba::1'
    'dns.google':
      - '8.8.8.8'
      - '8.8.4.4'
      - '2001:4860:4860::8888'
      - '2001:4860:4860::8844'
    'one.one.one.one':
      - '1.1.1.1'
      - '1.0.0.1'  # mihomo does not support shorten fqdn
      - '2606:4700:4700::1111'
      - '2606:4700:4700::1001'
  # looks like gfw would detect gfwlist query even doh
  # do redir-host through proxy to eliminate leaking
  prefer-h3: false
  nameserver:
    - 'https://dns.google/dns-query#🕸️ GFWList'
    - 'https://one.one.one.one/dns-query#🕸️ GFWList'
    - 'https://dns.google/dns-query'
    - 'https://one.one.one.one/dns-query'
  nameserver-policy:
    'geosite:cn':
      - 'https://dns.alidns.com/dns-query'
      - 'tls://dot.pub'
      - '180.76.76.76'
    'geosite:private':
      - 'system'


proxy-providers:
  sub:
    interval: 10800
    type: http
    url: ""
    path: "./proxy-provider/sub.yml"
    override:
      dialer-proxy: "🏄 免流"

  bdml:
    type: file
    path: "./proxy-provider/bdbox51.yaml"

  aliml:
    type: file
    path: "./proxy-provider/gwalicdn.yaml"


proxy-groups:
  - 
    name: "🎛 代理编组"
    type: select
    proxies: ["💫 Fail Auto Switch", "AUTO"]
  -
    name: "💫 Fail Auto Switch"
    type: fallback
    include-all-proxies: true
    use: ["neko-service", "prprcloud"]
    exclude-filter: "流量|套餐|重置"
  -
    name: "🏄 免流"
    type: select
    proxies:
     - DIRECT
     - "bd"
     - "ali"
  -
    name: "bd"
    type: select
    use:
     - "bdml"
    url: https://connect.rom.miui.com/generate_204
  -
    name: "ali"
    type: select
    use:
     - "aliml"
    url: https://connect.rom.miui.com/generate_204
  - 
    name: "🔮 ANY OTHERS"
    type: select
    proxies: ["🎛 代理编组", 'DIRECT', 'REJECT']
  - 
    name: "🕸️ GFWList"
    type: select
    proxies: ["🎛 代理编组", 'DIRECT', 'REJECT']
  - 
    name: "🥮 大陆网域"
    type: select
    proxies: ["🏄 免流", "🎛 代理编组", 'REJECT']
  - 
    name: "🍎 Apple 中国"
    type: select
    proxies: ["🔮 ANY OTHERS", "🕸️ GFWList", "🥮 大陆网域"]
  - 
    name: "🍏 Apple iCloud"
    type: select
    proxies: ["🔮 ANY OTHERS", "🕸️ GFWList", "🥮 大陆网域"]
  - 
    name: "🍥 Google 中国 (慎用)"
    type: select
    proxies: ["🕸️ GFWList", "🥮 大陆网域", "🔮 ANY OTHERS", 'REJECT']
  - 
    name: "💺 Microsoft 中国"
    type: select
    proxies: ["🕸️ GFWList", "🥮 大陆网域", "🔮 ANY OTHERS", 'REJECT']
  - 
    name: "💬 Telegram"
    type: select
    proxies: ["🕸️ GFWList", "🥮 大陆网域", "🔮 ANY OTHERS"]
  - 
    name: "🖥️ 本地网络"
    type: select
    proxies: ['DIRECT', "🎛 代理编组", 'REJECT']
  - 
    name: "💼 私有网段专用域"
    type: select
    proxies: ['DIRECT', "🎛 代理编组", 'REJECT']
  - 
    name: "🧄 直连应用程序"
    type: select
    proxies: ['DIRECT', "🎛 代理编组", 'REJECT']
  - 
    name: "🚧 广告过滤"
    type: select
    proxies: ['REJECT', 'DIRECT', "🎛 代理编组"]
  - 
    name: "🚦 跟踪分析封锁"
    type: select
    proxies: ['REJECT', 'DIRECT', "🎛 代理编组"]
  -
    name: "🥗 3g规则"
    type: select
    proxies: ['DIRECT', 'REJECT']
  -
    name: "AUTO"
    type: url-test 
    include-all-providers: true
    tolerance: 10
    hidden: true

rules:
 # 需要直连的常见软件列表
 - DOMAIN-SUFFIX,dynupdate6.no-ip.com,DIRECT
 # 广告域名列表
 - GEOSITE,category-ads-all,🚧 广告过滤
 # 3gnet
 - GEOSITE,xiaohongshu,🥗 3g规则
 - GEOSITE,alibaba,🥗 3g规则
 - GEOSITE,baidu,🥗 3g规则
 - GEOSITE,bytedance@cn,🥗 3g规则
 - GEOSITE,chinaunicom,🥗 3g规则
 - GEOSITE,jd,🥗 3g规则
 - GEOSITE,netease,🥗 3g规则
 # Steam 下载分流
 - GEOSITE,steam@cn,🥮 大陆网域
 # Apple 在中国大陆可直连的域名列表
 - GEOSITE,apple-cn,🍎 Apple 中国
 # iCloud 域名列表
 - GEOSITE,icloud,🍏 Apple iCloud
 # [慎用]Google 在中国大陆可直连的域名列表
 - GEOSITE,google-cn,🍥 Google 中国 (慎用)
 - GEOSITE,microsoft@cn,💺 Microsoft 中国
 - GEOSITE,bing,💺 Microsoft 中国
 # Telegram 使用的 IP 地址列表
 - GEOIP,telegram,💬 Telegram,no-resolve
 - GEOSITE,telegram,💬 Telegram
 # 代理域名列表
 - GEOSITE,geolocation-!cn,🕸️ GFWList
 - DOMAIN-SUFFIX,lishuma.com,🔮 ANY OTHERS
 # GFWList 域名列表
 - GEOSITE,gfw,🕸️ GFWList
 # 直连域名列表
 - GEOSITE,CN,🥮 大陆网域
 # 私有网络专用域名列表
 - GEOSITE,private,💼 私有网段专用域
 # 局域网 IP 及保留 IP 地址列表
 - GEOIP,private,🖥️ 本地网络,no-resolve
 # 中国大陆 IP 地址列表
 - GEOIP,CN,🥮 大陆网域
 # 非中国大陆使用的顶级域名列表
 - MATCH,🔮 ANY OTHERS

```

</p>
</details>

### 描述

When `tun.stack` sets to `system` or `mixed` *and* the destination addr is IPv6, application cannot connect to outside network. `curl` raises `cannot connect to server` error, neither `no route to host`, nor `network is unreachable`. (see Steps to Reproduce)
if the target is a domain, `mihomo` would returns AAAA record as expected, and then app cannot connect to IPv6 destination.
`ip addr` showed that there are IPv6 addr configured. `mtr` showed that `utun` interface is selected, with `fdfe` prefix.

<details><summary>Details</summary>
<p>

```bash
munch:/ $ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 92:7b:1b:f5:10:e4 brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 5a:83:7a:45:7a:e5 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5883:7aff:fe45:7ae5/64 scope link
       valid_lft forever preferred_lft forever
4: ip_vti0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: ip6_vti0@NONE: <NOARP> mtu 1364 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd ::
6: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
7: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd ::
8: rmnet_ipa0: <> mtu 9216 qdisc noop state DOWN group default qlen 1000
    link/[519]
10: rmnet_mhi0: <UP,LOWER_UP> mtu 65535 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/[519]
11: rmnet_data0@rmnet_mhi0: <UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN group default qlen 1000
    link/[519]
    inet6 fe80::bcfa:9b9d:96a6:8b67/64 scope link
       valid_lft forever preferred_lft forever
12: rmnet_data1@rmnet_mhi0: <UP,LOWER_UP> mtu 1400 qdisc mq state UNKNOWN group default qlen 1000
    link/[519]
    inet6 2408:854a:<removed>/64 scope global dynamic mngtmpaddr
       valid_lft forever preferred_lft forever
    inet6 fe80::335c:53a0:e5e4:eb1b/64 scope link
       valid_lft forever preferred_lft forever
13: rmnet_data2@rmnet_mhi0: <UP,LOWER_UP> mtu 1400 qdisc mq state UNKNOWN group default qlen 1000
    link/[519]
    inet 10.45.80.228/29 scope global rmnet_data2
       valid_lft forever preferred_lft forever
    inet6 2408:8448:<removed>/64 scope global dynamic mngtmpaddr
       valid_lft forever preferred_lft forever
    inet6 fe80::c7d6:bc8d:181f:f857/64 scope link
       valid_lft forever preferred_lft forever
14: rmnet_data3@rmnet_mhi0: <UP,LOWER_UP> mtu 1410 qdisc mq state UNKNOWN group default qlen 1000
    link/[519]
    inet6 2409:8134:<removed>/64 scope global dynamic mngtmpaddr
       valid_lft forever preferred_lft forever
    inet6 fe80::5b4d:d773:f77a:62cf/64 scope link
       valid_lft forever preferred_lft forever
15: rmnet_data4@rmnet_mhi0: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[519]
16: rmnet_data5@rmnet_mhi0: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[519]
17: r_rmnet_data0@rmnet_mhi0: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[519]
18: r_rmnet_data1@rmnet_mhi0: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[519]
19: r_rmnet_data2@rmnet_mhi0: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[519]
20: r_rmnet_data3@rmnet_mhi0: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[519]
21: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 3000
    link/ether d8:<removed>:7e brd ff:ff:ff:ff:ff:ff
    inet 192.168.10.149/24 brd 192.168.10.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet6 240e:37a:<removed>/64 scope global temporary dynamic
       valid_lft 259029sec preferred_lft 80311sec
    inet6 240e:37a:<removed>/64 scope global dynamic mngtmpaddr stable-privacy
       valid_lft 259029sec preferred_lft 172629sec
    inet6 fe80::<removed>:1103/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
22: p2p0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 3000
    link/ether da:32:e3:0e:ee:7e brd ff:ff:ff:ff:ff:ff
23: wifi-aware0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 3000
    link/ether da:32:e3:0f:ee:7e brd ff:ff:ff:ff:ff:ff
29: utun: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 198.18.0.1/30 brd 198.18.0.3 scope global utun
       valid_lft forever preferred_lft forever
    inet6 fdfe:dcba:9876::1/126 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::70c6:d026:8805:eb14/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
```

</p>
</details> 

Set `tun.stack` to `gvisor` would make IPv6 things works as expected.
On Windows 11 Home, `tun.stack=system` works as expected.
Access via proxy directly (`-x localhost:7890`) is working, since there are no L3 issues.

### 重现方式

1. set up config, fill proxies (proxy without IPv6 should work, not tested)
2. set `tun.stack` to `system` or `mixed.
3. try connect to IPv6 network, `curl` to a IPv6-only domain for example:

```bash
munch:/ $ curl test6.ustc.edu.cn -v
* Host test6.ustc.edu.cn:80 was resolved.
* IPv6: 2001:da8:d800::1043
* IPv4: (none)
*   Trying [2001:da8:d800::1043]:80...
* connect to 2001:da8:d800::1043 port 80 from fdfe:dcba:9876::1 port 43494 failed: Connection timed out
* Failed to connect to test6.ustc.edu.cn port 80 after 31572 ms: Could not connect to server
* closing connection #0
curl: (28) Failed to connect to test6.ustc.edu.cn port 80 after 31572 ms: Could not connect to server
```

### 日志

[mihomo.log](https://github.com/user-attachments/files/19231800/mihomo.log)
