### ISSUE TITLE
[Bug] 使用listeners连接到tunnels暴露的端口时，会提示reject loopback connection to

### ISSUE THREAD

**Issue by zeyugao** [MetaCubeX/mihomo#1909]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows, Linux

### 系统版本

Debian 12

### Mihomo 版本

Mihomo Meta alpha-dee5898 linux amd64 with go1.24.1 Sat Mar 15 05:28:04 UTC 2025
Use tags: with_gvisor

### 配置文件

```yaml
find-process-mode: strict

mode: direct

log-level: debug

global-client-fingerprint: chrome

keep-alive-interval: 15

profile: # 存储 select 选择记录
  store-selected: true
  store-fake-ip: true

listeners:
  - name: ss
    type: shadowsocks
    port: 1080
    listen: 0.0.0.0
    proxy: DIRECT
    password: xxxxx
    cipher: chacha20-ietf-poly1305

tunnels:
  - network: [tcp]
    address: 0.0.0.0:9200
    target: 100.100.100.100:443
    proxy: DIRECT
```

### 描述

场景是这样的，一台机器(e.g. 10.10.10.10)在内网A里面，可以连接到另一个内网B（e.g. 100.100.100.100），同时A里面也有很多的其他机器需要访问100.100.100.100:443

但是机器也提供一个对外的ss的接口，可以访问内网A

因此期望可以在不管使用ss的方式，还是在内网A里面，都可以直接访问 10.10.10.10:9200 来访问到100.100.100.100:443

现在直接使用tunnels，即在内网A里面去访问10.10.10.10:9200是正常的，但是通过ss接入的方式去访问10.10.10.10:9200会无法访问，log里面为

```
WARN[2025-03-15T20:21:07.576255899+08:00] [TCP] dial DIRECT xx.xx.xx.xx:42864 --> 100.100.100.100:443 error: reject loopback connection to: 100.100.100.100:443
```

### 重现方式

连接到ss，访问10.10.10.10:9200

### 日志

```shell

```
