### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by KleinerSource** [MetaCubeX/mihomo#1917]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

Openwrt

### Mihomo 版本

alpha-a7a796b

### 配置文件

```yaml
port: 10008
socks-port: 10009
allow-lan: true
mode: rule
log-level: warning
external-controller: '[::]:9090'
find-process-mode: off
ipv6: false
tcp-concurrent: true
keep-alive-idle: 600
keep-alive-interval: 15
external-ui: ui
external-ui-url: https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip
secret: 123456..
mixed-port: 10010
redir-port: 7891
tproxy-port: 7892
tun:
  enable: true
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false
  device: nikki
  stack: mixed
dns:
  enable: true
  listen: '[::]:1053'
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - +.lan
    - +.local
    - geosite:private
    - geosite:cn
  fake-ip-filter-mode: blacklist
  respect-rules: true
  prefer-h3: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  direct-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
profile:
  store-selected: true
  store-fake-ip: true
geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 48
```

### 描述

日志中出现大量[UDP] Resolve Ip error: couldn't find ip

### 重现方式

启动内核后 正常使用过程中就会产生

### 日志

```shell
time="2025-03-17T06:35:11.669940930Z" level=info msg="Start initial configuration in progress"
time="2025-03-17T06:35:11.672625861Z" level=info msg="Geodata Loader mode: standard"
time="2025-03-17T06:35:11.672660988Z" level=info msg="Geosite Matcher implementation: succinct"
time="2025-03-17T06:35:11.689729354Z" level=info msg="Load GeoSite rule: cn"
time="2025-03-17T06:35:12.385699802Z" level=info msg="Load GeoSite rule: private"
time="2025-03-17T06:35:12.526889879Z" level=info msg="Finished initial GeoSite rule private => dns.fake-ip-filter, records: 131"
time="2025-03-17T06:35:12.527035314Z" level=info msg="Finished initial GeoSite rule cn => dns.fake-ip-filter, records: 96493"
time="2025-03-17T06:35:13.482429946Z" level=warning msg="[CacheFile] can't open cache file: timeout"
time="2025-03-17T06:35:13.482473229Z" level=info msg="Initial configuration complete, total time: 1812ms"
configuration file /etc/nikki/run/config.yaml test is successful
time="2025-03-17T06:35:13.648956208Z" level=error msg="External controller serve error: http: Server closed"
time="2025-03-17T06:36:32.229930677Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:36:32.345865926Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:36:32.746464677Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:36:33.546750257Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:36:35.147310673Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:36:36.747815506Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:36:38.351696743Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:36:39.949274283Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:38:40.883042939Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:38:41.163355255Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:41:41.554549359Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:41:41.654933565Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:41:41.855112092Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:41:42.255358894Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:41:43.055636086Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:41:44.655738783Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:41:46.256744202Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:41:47.856844162Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:41:49.457722862Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:43:07.995504645Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:43:07.995922787Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:43:08.794938152Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:43:08.795336670Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:43:10.396481342Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:43:10.398008189Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:46:51.063999228Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:46:51.164260348Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:46:51.364453601Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:46:51.765915534Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:46:52.565600493Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:46:54.165882535Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:46:55.766865399Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:46:57.368417461Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:46:58.968602479Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:48:28.838569631Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:48:28.838800803Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:48:29.038689375Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:48:29.038949425Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:48:31.841428111Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:48:31.842898272Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:51:35.795923307Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:51:35.796190725Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:51:36.399813033Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:51:36.400130074Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:51:37.199376787Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:51:37.199712972Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:51:38.799402163Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:51:38.799774852Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:52:00.573803098Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:52:00.674366009Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:52:00.875501629Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:52:01.275503310Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:52:02.078848319Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:52:03.678893180Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:52:05.279509485Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:52:06.879639617Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:52:08.481030958Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:55:54.745013326Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:55:54.745467594Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:55:54.945355905Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:55:54.947111786Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:55:55.347313805Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:55:55.348914980Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:55:56.148860007Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:55:57.747456519Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:55:57.749028388Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:57:10.085207691Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:57:10.185882630Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:57:10.386067326Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:57:10.787086498Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:57:11.588055321Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:57:13.189689861Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:57:14.789815666Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:57:16.392626333Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:57:17.993046124Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:58:15.291317704Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:58:15.291942978Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:58:15.492616757Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:58:15.493205808Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:58:15.892985875Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
time="2025-03-17T06:58:15.893086565Z" level=warning msg="[UDP] Resolve Ip error: couldn't find ip"
```
