### ISSUE TITLE
[Bug] direct-nameserver似乎并不对rules内直接为DIRECT的链接起效

### ISSUE THREAD

**Issue by xixi-furry** [MetaCubeX/mihomo#1925]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

OpenWRT 6.6.79 OpenClash v0.46.080

### Mihomo 版本

Mihomo Meta alpha-g4f8b70c linux amd64 with go1.24.1 Wed Mar 19 20:09:14 UTC 2025

### 配置文件

```yaml
请看下方
```

### 描述

我的DNS相关配置：
```
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  respect-rules: true
  fake-ip-filter-mode: blacklist
  nameserver:
  - tls://1.1.1.1
  - tls://8.8.8.8
  proxy-server-nameserver:
  - 211.137.58.x
  - 211.137.64.x
  direct-nameserver:
  - 211.137.58.x
  - 211.137.64.x
  nameserver-policy:
    _vlmcs._tcp.lan: 127.0.0.1:53
    geosite:category-games@cn:
    - https://doh.pub/dns-query
    - 114.114.114.114
    - 223.5.5.5
    geosite:google:
    - tls://8.8.4.4
    - https://1.0.0.1/dns-query
    geosite:cn,apple,private:
    - 211.137.58.X
    - 211.137.64.X
    - https://doh.pub/dns-query
  use-hosts: true
  default-nameserver:
  - 211.137.58.X
  - 211.137.64.X
```

以下是我的额外增加的rules的部分：
```
rules:
## STEAMCN 直连
- DOMAIN,steamcdn-a.akamaihd.net,DIRECT
- DOMAIN-SUFFIX,cm.steampowered.com,DIRECT
- DOMAIN-SUFFIX,steamserver.net,DIRECT
```

在日志里查看，DIRECT似乎都没有按照我指定的direct-nameserver在请求，反而还是默认的nameserver，证据如下：
![image](https://github.com/user-attachments/assets/f0467e86-5712-4680-a6e4-6e6d325e85bd)
![image](https://github.com/user-attachments/assets/9356e563-d4ed-4a07-ad10-76abc4d3983b)

规则也是生效的:
![image](https://github.com/user-attachments/assets/28c1b7eb-6f7c-40b7-b0e6-19ab1cb23a1f)

自己研究了一下还是没找到解决办法，恳请各位大佬帮忙看看（

### 重现方式

在rules里新增某个网站域名为direct，还是会请求nameserver

### 日志

```shell

```
