### ISSUE TITLE
[bug] 对于不可达的 DNS 服务器，缩短超时时间

### ISSUE THREAD

**Issue by Rirmach** [MetaCubeX/mihomo#1932]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [x] 我是中文用户，而非其他语言用户

### 描述

* 如果 DNS 配置项中使用 system，代理程序将会添加若干个 DNS 服务器地址，所添加的地址有的是不可达的错误地址（非链路地址，可能是从 VMware 虚拟网卡上拿到的无效地址）
* 此时访问 **仅有 IPv6 地址的目标网站** 将会延迟 5 秒，即便代理程序已经从其中一个 DNS 服务器中拿到了正确的 IPv6 地址，这导致访问体验不佳。但强制指定 DNS 服务器又会降低普适性，失去 system 原有的作用
* 经测试，手动配置一个错误的 DNS 服务器同样会复现
* 希望能增加配置项，缩短 DNS 服务器的 A/AAAA 查询的超时时间，或者在其中一个服务器拿到 IP 后立刻开始访问。

**Comment by Skyxim** [comment]
@Rirmach 请提供日志以及最小配置佐证，同类多个 DNS 并发并取得最快结果

**Comment by Rirmach** [comment]
> [@Rirmach](https://github.com/Rirmach) 请提供日志以及最小配置佐证，同类多个 DNS 并发并取得最快结果

1. 日志（隐去隐私信息）：
![Image](https://github.com/user-attachments/assets/f9ac0a1c-1e1a-4c02-8eb8-9e4c5bcd192d)
2. 完整测试用配置文件（隐去隐私信息）
```yaml
mode: rule
allow-lan: true
log-level: debug
ipv6: true
unified-delay: true

dns:
  enable: true
  listen: :5300
  ipv6: true
  nameserver:
    - system

listeners:
  - name: default
    type: mixed
    port: 7892

global-client-fingerprint: chrome

proxies:
  - name: akkode(gRPC)
    type: vless
    server: ***
    port: ***
    uuid: ***
    tls: true
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: ***

proxy-groups:
  - name: Oversea
    type: select
    proxies:
      - akkode(gRPC)
    url: http://www.gstatic.com/generate_204
    interval: 60

rules:
  - GEOIP,CN,DIRECT
  - MATCH,Oversea
```
3. 测试环境：
版本和工作目录
![Image](https://github.com/user-attachments/assets/47f56711-8de8-499e-be04-e722cc064146)
![Image](https://github.com/user-attachments/assets/5c8bbe3a-3c69-461c-8f57-3f90ed2bd2b6)
测试命令
```curl https://***:10140 --proxy http://localhost:7892```

4. 对比测试
如果强制指定 DNS 服务器，则无问题：
```yaml
dns:
  enable: true
  listen: :5300
  ipv6: true
  nameserver:
    - 10.0.0.40
```

![Image](https://github.com/user-attachments/assets/421277e9-0c48-4dbc-9bb4-5322e378af11)

**Comment by Skyxim** [comment]
日志看到从查询 DNS 到发起 TCP 请求根本没有达到 DNS 超时，甚至没到 100ms，与其描述并不符合

**Comment by Rirmach** [comment]
curl 执行时间戳是 16:16:41，Clash 开始查询 DNS 是 16:16:41.418，查询到地址是 16:16:41.441，但实际匹配出口是 16:16:46.420，curl 返回结果差不多也是这个时候，和 curl 执行开始时间和 Clash 开始查询 DNS 的时间正好相差 5 秒
第二次测试是无问题的测试。作为对比，DNS 是显式指定的

**Comment by Skyxim** [comment]
> curl 执行时间戳是 16:16:41，Clash 开始查询 DNS 是 16:16:41.418，查询到地址是 16:16:41.441，但实际匹配出口是 16:16:46.420，curl 返回结果差不多也是这个时候，和 curl 执行开始时间和 Clash 开始查询 DNS 的时间正好相差 5 秒 第二次测试是无问题的测试。作为对比，DNS 是显式指定的

![Image](https://github.com/user-attachments/assets/3b8f10c5-c6c1-42a7-9bd0-e800aae21673)

请上传描述对应的日志，从此日志并看不出来，甚至时间都不对应

**Comment by Rirmach** [comment]
> 请上传描述对应的日志，从此日志并看不出来，甚至时间都不对应

![Image](https://github.com/user-attachments/assets/b076f824-499b-43a2-b674-1159d5ba688f)

**Comment by Rirmach** [comment]
> ![Image](https://github.com/user-attachments/assets/c4deda21-1334-49ea-8e45-db966bd95226) 这里已经代表 DNS 已经完成解析

是的，但不知为何配置 system 为 DNS 上游就要等待五秒才会访问。仅配置 223.5.5.5，或网关 IP 10.0.0.1 作为 DNS 服务器上游没有这个问题，两种配置方法都能拿到 IP。这个问题可以反复复现，也就是说第一次改成 system 要延迟 5 秒，第二次改成 223.5.5.5 问题消失，第三次改成 system 问题又会出现

**Comment by Skyxim** [comment]
System 多个地址也是并发请求的，尝试通过 dig/nslookup 对 System 的地址请求，是否其他地址无法解析

**Comment by Rirmach** [comment]
> System 多个地址也是并发请求的，尝试通过 dig/nslookup 对 System 的地址请求，是否其他地址无法解析

是的，配置 system 时会自动添加 192.168.95.115 作为 DNS 上游，这个 DNS 所在网段和局域网网段不一致，推测是 VMware 虚拟网卡上的地址，这个上游很显然是无效的
但我的理解是 system 设计目标应当是具有在不同网络下的自适应性，强制指定 DNS 服务器会降低普适性
系统 DNS 经测试无问题，可正常解析
![Image](https://github.com/user-attachments/assets/5e9091e9-06ac-42c9-8798-6b2f525d28cc)

补充：不使用 system，仅添加 223.5.5.5 和 127.0.0.1（无效 DNS 服务器），也会出现此问题

**Comment by Skyxim** [comment]
> 223.5.5.5 和 127.0.0.1（无效 DNS 服务器），也会出现此问题

添加到 nameserver？

**Comment by Rirmach** [comment]
> > 223.5.5.5 和 127.0.0.1（无效 DNS 服务器），也会出现此问题
> 
> 添加到 nameserver？

是的，涉及到的配置之前已列出：
```yaml
dns:
  enable: true
  listen: :5300
  ipv6: true
  nameserver:
    - system
```
或者
```yaml
dns:
  enable: true
  listen: :5300
  ipv6: true
  nameserver:
    - 223.5.5.5
    - 127.0.0.1
```
