### ISSUE TITLE
[Feature] 提议增加子分组功能以优化代理组织方式

### ISSUE THREAD

**Issue by Zayrick** [MetaCubeX/mihomo#1933]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [x] 我是中文用户，而非其他语言用户

### 描述

**Description:**  
你好，感谢你们提供如此优秀的代理软件！在使用过程中，我遇到了一些代理分组管理上的困扰，希望能够提出改进建议。  

### **问题描述**  
对于使用多个代理提供商的用户而言，不同供应商可能提供相同国家的节点。如果仅按照国家进行分组，某些国家可能会出现代理节点数量过多，导致选择困难，影响使用体验。  

例如：  
```yaml
proxy-groups:
- name: Proxy
  type: select
  proxies:
  - us1
  - us2
  - hk1
  - hk2
  - tw1
  - tw2
```
当多个供应商都提供美国、日本等节点时，整个 `Proxy` 组会变得非常庞大，缺乏层级管理，选择代理时也会显得混乱。  

### **改进建议**  
希望支持 **子分组（sub-proxy）** 结构，以便用户能更有条理地管理代理，并在前端提供二级选择的方式。例如：  

```yaml
proxy-groups:
- name: Proxy
  type: select
  proxies:
  - sub-proxy:us
  - sub-proxy:hk
  - sub-proxy:tw

sub-proxy:
- name: us
  type: sub-proxy
  proxies:
  - us1
  - us2

- name: hk
  type: sub-proxy
  proxies:
  - hk1
  - hk2

- name: tw
  type: sub-proxy
  proxies:
  - tw1
  - tw2
```
**前端可能的表示方式**：  
1. 在 `Proxy` 组的选择界面，`sub-proxy` 不能直接作为代理选项，而是作为**二级选项的入口**。  
2. 例如，选择 **"us"** 后，界面会弹出新的二级选择框，允许用户在 **"us1"** 和 **"us2"** 之间进一步选择。  
3. 这类似于多级菜单的选择方式，使得代理管理更加清晰，避免一级列表过长导致的混乱。  

### **预期收益**  
1. **提高可读性**：代理列表层级清晰，避免国家和供应商混杂在一个组中。  
2. **提升用户体验**：减少需要手动滚动的大量代理，提高代理切换效率。  
3. **增强前端交互**：更符合逻辑的层级选择方式，提升可用性。  
4. **兼容性**：现有用户仍可使用原有方式，不影响兼容性。  

（虽然也不知道会有什么用，纯属强迫症犯了 😆）  

希望能考虑这个建议，期待你的回复！谢谢！ 😊

**Comment by 000320LUCKY** [comment]
再嵌套一层分组就行了呀

**Comment by Zayrick** [comment]
> 再嵌套一层分组就行了呀

非常感谢大佬的回复，我也这样尝试过，但我遇到问题，比如同样的美国节点，A需要美国的专线节点，B需要美国的直连（廉价）节点，嵌套的话就只能二选一

**Comment by 000320LUCKY** [comment]
> > 再嵌套一层分组就行了呀
> 
> 非常感谢大佬的回复，我也这样尝试过，但我遇到问题，比如同样的美国节点，A需要美国的专线节点，B需要美国的直连（廉价）节点，嵌套的话就只能二选一

可以灵活一点，创建几个特殊需求的代理组就能解决了。可以创建一些"手动选择”，“专线”这样的代理组，给一些特殊流量使用

**Comment by 000320LUCKY** [comment]
> > > 再嵌套一层分组就行了呀
> > 
> > 
> > 非常感谢大佬的回复，我也这样尝试过，但我遇到问题，比如同样的美国节点，A需要美国的专线节点，B需要美国的直连（廉价）节点，嵌套的话就只能二选一
> 
> 可以灵活一点，创建几个特殊需求的代理组就能解决了。可以创建一些"手动选择”，“专线”这样的代理组，给一些特殊流量使用

![Image](https://github.com/user-attachments/assets/7f0eed94-4490-421f-bcb9-755f88152349) 把一些常用的代理组放前面就行

**Comment by iKira** [comment]
```
proxy-groups:
  - name:
    type: select
    use:
    filter: 正则表达式
```

你可以用filter筛选节点
