### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by CrazyThursdayV50** [MetaCubeX/mihomo#1938]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [x] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

MacOS

### System Version

15.3.2 (24D81)

### Mihomo Version

v1.19.3

### Configuration File

```yaml
- name: ss
    type: ss
    server: ***********
    port: 10799
    cipher: none
    password: GUBGL95O19
    udp: true
    plugin: obfs
    plugin-opts:
      mode: tls
      host: *********
```

### Description

概述：Shadowsocks 在某种情况下节点无法通过 mihomo 连接上。

细节：

简单 shadowsocks 节点（无混淆无tls）可以连接。但当我增加了 ssl（打开 tls 后，mihomo 内核无法连接上节点）。
首先，我的这个 ss-tls 节点是没问题的，因为我通过其他客户端测试了确实可以连上并且成功通过该节点翻墙。
其次，我通过v1.19.3版本源码分析、并且 debug，成功定位到了错误：在 adapter/adaper.go 264 行，发起客户端请求后，返回了错误，错误原因具体解释为“消息解密失败”：
- 如果 cipher 是 aes-256-gcm，错误为：cipher: message authenticationn failed
- 如果 cipher 是 chacha20-ietf-poly1350，错误为：chacha20 消息解密失败（具体我忘了，日志因为debug太多找不到了）

另外，我在 test 下面做了一些测试，有这个结论：
1. mihomo 自己的测试是完全都通过的，没有问题。具体表现在：在本机 docker 中跑的 ss-server，本机 mihomo 内核均能成功连接
2. 修改 test 配置后，测试连接远程节点（ss-tls、ss-wss）均连接失败，主要体现在消息解密失败。

中间，我考虑是不是 shadowsocks 协议中没有正确将 cipher decoder 加进去，于是尝试把 ssr 中的 cipher stream 加到了 ss 中，发现解决不了问题，并且产生了新的问题，所以我将自己的代码退回了。

截至目前为止，这个问题（ss-tls、ss-wss 无法连接上）我通过自己的方式确实解决不了了，所以来求助。

附上我的客户端配置（这个配置如果放在本地，是能连上的）：
```yaml
  - name: ss
    type: ss
    server: ***********
    port: 10799
    cipher: none
    password: GUBGL95O19
    udp: true
    plugin: obfs
    plugin-opts:
      mode: tls
      host: *********
```
我的服务端使用的是 x-ui 创建的  ss 节点，这个节点通过 ShadowrocketR 能够连上。

### Reproduction Steps

如我描述

### Logs

```shell

```
