### ISSUE TITLE
[Bug] Vless 无法使用gRPC

### ISSUE THREAD

**Issue by LordHumphrey** [MetaCubeX/mihomo#1940]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 系统版本

win 11

### Mihomo 版本

[1.19.3](https://github.com/MetaCubeX/mihomo/releases/tag/v1.19.3)

### 配置文件

```yaml
服务端入站
 
 - name: vless-in
    type: vless
    port: 1028
    listen: 0.0.0.0
#    grpc-service-name: "GunService"
    users:
      - username: Moss
        uuid: 
        flow: xtls-rprx-vision
    reality-config:
      dest: www.wps.cn:443
      private-key: 

      short-id:
        - ""
      server-names:
        - www.wps.cn

客户端配置：

  - name: "-Vless"
    type: vless
    server: 172.18.0.6 #
    port: 1028
    uuid: 
#    network: grpc
    network: tcp
    tls: true
    udp: true
    servername: www.wps.cn
    skip-cert-verify: true
    client-fingerprint: chrome
    flow: xtls-rprx-vision
    reality-opts:
      public-key: 
      short-id: ""
#    grpc-opts:
#      grpc-service-name: "GunService"
```

### 描述

一旦将注释中的gRPC配置打开，改为使用gRPC，就无法连接，不使用gRPC则正常！

### 重现方式

一旦将注释中的gRPC配置打开，改为使用gRPC，就无法连接，不使用gRPC则正常！

### 日志

```shell

```

**Comment by xishang0128** [comment]
vision仅适用于tcp

**Comment by LordHumphrey** [comment]
谢谢开发者，单独使用`vision`可以了，但是单独使用gRPC还是不行。
服务端：
```
  - name: vless-gRPC-in
    type: vless
    port: 1028
    listen: 0.0.0.0
    grpc-service-name: "MossService"
    users:
      - username: Moss
        uuid: xx-xx
    reality-config:
      dest: www.speedtest.cn:443
      private-key: xxxx
      #      PublicKey: xxx-xx
      short-id:
        - ""
        - xxx
      server-names:
        - www.speedtest.cn
```
客户端
```
  - name: "gRPC-Vless"
    type: vless
    server: 172.28.0.6
    port: 1028
    uuid: xxxx-xx-xx-xx
    network: grpc
    tls: true
    udp: true
    servername: www.speedtest.cn
    reality-opts:
      public-key: xx-xx
      short-id: xxx
    grpc-opts:
      grpc-service-name: "MossService"
    client-fingerprint: chrome
```
再次感谢开发者的工作~
