### ISSUE TITLE
[Bug] windows通过系统代理方式无法访问

### ISSUE THREAD

**Issue by AceCandy** [MetaCubeX/mihomo#1945]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

win11

### Mihomo 版本

v1.19.3

### 配置文件

```yaml
tun:
  enable: true  # enable 'true'
  stack: mixed  # or 'gvisor'
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true

# dns 设置
# 已配置 ipv6
dns:
  enable: true
  listen: :1053
  ipv6: true
  prefer-h3: true
  respect-rules: true
  enhanced-mode: fake-ip
  #fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
    - "+.market.xiaomi.com"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    - '[2402:4e00::]'
    - '[2400:3200::1]'
  nameserver:
    #- https://dns.digitale-gesellschaft.ch/dns-query
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
    #- https://1.12.12.12/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://120.53.53.53/dns-query
      - https://223.5.5.5/dns-query
    "geosite:!cn,!private": 
      - "https://dns.cloudflare.com/dns-query"
```

### 描述

我在1.205上配置好了mihomo之后，通过34的win11配置系统代理，访问局域网其它docker容器服务均失败，关闭代理访问正常。
查看mihomo上日志已经接收到并返回策略为DIRECT。

[TCP] 192.168.1.34:51809 --> 192.168.1.205:23000 match IPCIDR(192.168.0.0/16) using DIRECT

### 重现方式

配置其它端配置代理方式访问会出现问题

### 日志

```shell

```
