### ISSUE TITLE
[Bug] RULE-SET 内部规则与精确规则的优先级不一致问题

### ISSUE THREAD

**Issue by epodak** [MetaCubeX/mihomo#1947]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

11

### Mihomo 版本

Mihomo Meta v1.19.3 windows amd64 with go1.24.0 Mon Mar  3 03:57:35 UTC 2025

### 配置文件

```yaml
rules:
  - "DOMAIN-SUFFIX,claude.ai,AI"  # 能正常工作
  - "RULE-SET,claude_rule,AI"        # 会被后面的 tld-not-cn 覆盖
  - "RULE-SET,tld-not-cn,PROXY"      # 包含 .com 等通用规则

rule-providers:
  claude_rule:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude.yaml"
    path: ./ruleset/claude_rule.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
```

### 描述

精确规则优先：当使用 DOMAIN/DOMAIN-SUFFIX 明确定义时（如 "DOMAIN-SUFFIX,claude.ai,🧠 AI 服务"），确实能优先匹配
规则集(RULE-SET)问题：当相同的域名通过 RULE-SET 引入时（如 "RULE-SET,claude_rule,🧠 AI 服务" 包含 claude.ai），会被后面的通用规则（如 tld-not-cn）覆盖

### 重现方式

上面的配置即可重现

### 日志

```shell

```
