### ISSUE TITLE
[Bug] 文档和代码不一致

### ISSUE THREAD

**Issue by okami-chen** [MetaCubeX/mihomo#1952]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [x] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

MacOS

### System Version

137.

### Mihomo Version

1.19.4

### Configuration File

```yaml
proxies:
- name: "vless"
  type: vless
  server: server
  port: 443
  udp: true
  uuid: uuid
  flow: xtls-rprx-vision
  packet-encoding: xudp

  tls: true
  servername: example.com
  alpn:
  - h2
  - http/1.1
  fingerprint: xxxx
  client-fingerprint: chrome
  skip-cert-verify: true
  reality-opts:
    public-key: xxxx
    short-id: xxxx

  network: tcp

  smux:
    enabled: false
```

### Description

![Image](https://github.com/user-attachments/assets/7e19a67e-fe44-4b35-9f4d-22de5e174b09)
实际：

![Image](https://github.com/user-attachments/assets/514f17a6-f4d2-46f6-92f1-dcb2956d03da)

### Reproduction Steps

![Image](https://github.com/user-attachments/assets/7e19a67e-fe44-4b35-9f4d-22de5e174b09)
实际：

![Image](https://github.com/user-attachments/assets/514f17a6-f4d2-46f6-92f1-dcb2956d03da)

### Logs

```shell
![Image](https://github.com/user-attachments/assets/7e19a67e-fe44-4b35-9f4d-22de5e174b09)
实际：

![Image](https://github.com/user-attachments/assets/514f17a6-f4d2-46f6-92f1-dcb2956d03da)
```
