### ISSUE TITLE
[Bug] TUN模式下，DNS的 #h3=true 标签导致DNS解析强制跟随规则

### ISSUE THREAD

**Issue by nekohy** [MetaCubeX/mihomo#1960]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Windows

### System Version

26100.3624

### Mihomo Version

Mihomo Meta v1.19.2 windows amd64 with go1.23.5 Sun Feb  9 13:23:16 UTC 2025
Use tags: with_gvisor

### Configuration File

```yaml
tun:
    enable: true
    stack: mixed
    dns-hijack: ['any:53', 'tcp://any:53']
    auto-route: true
    auto-redirect: true
    auto-detect-interface: true
    strict-route: true

dns:
    enable: true
    ipv6: false
    respect-rules: false
    enhanced-mode: fake-ip
    fake-ip-filter: ['*', "rule-set:geosite_cn,private_domain"]
    default-nameserver: ['quic://223.5.5.5', 'https://120.53.53.53/dns-query#h3=true']
    nameserver: ['quic://223.5.5.5', 'https://120.53.53.53/dns-query#h3=true']
    proxy-server-nameserver: ['quic://223.5.5.5', 'https://120.53.53.53/dns-query#h3=true']
    nameserver-policy: { 'rule-set:geosite_cn,private_domain': system, 'rule-set:geosite_!cn': ['https://dns.cloudflare.com/dns-query#RULES', 'https://dns.google/dns-query#RULES'] }

rules:
  - DST-PORT,853,REJECT
  - AND,((DST-PORT,443),(NETWORK,UDP)),REJECT
```

### Description

在系统代理下正常运行
在TUN模式下，加入 #h3=true 标签的DNS解析请求错误进入Rules处理

若使用prefer-h3则无此问题，未测试其他标签例如ecs是否会导致DNS错误进入规则处理

### Reproduction Steps

按照上述运行

### Logs

```shell
time="2025-04-04T02:07:59.157749800+08:00" level=debug msg="[DNS] resolve iepl1.节点地址 AAAA from 223.5.5.5:853"
time="2025-04-04T02:07:59.157749800+08:00" level=debug msg="[DNS] resolve iepl1.节点地址 A from 223.5.5.5:853"
time="2025-04-04T02:07:59.157749800+08:00" level=debug msg="[DNS] resolve iepl1.节点地址 AAAA from https://120.53.53.53:443/dns-query"
time="2025-04-04T02:07:59.158273500+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-04T02:07:59.158273500+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-04T02:07:59.158273500+08:00" level=info msg="[UDP] 198.18.0.1:51837 --> 223.5.5.5:853 match DstPort(853) using REJECT"
time="2025-04-04T02:07:59.158273500+08:00" level=info msg="[UDP] 198.18.0.1:51835 --> 120.53.53.53:443 match AND(((DstPort,443) && (Network,udp))) using REJECT"
time="2025-04-04T02:07:59.343694400+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-04T02:07:59.343694400+08:00" level=info msg="[UDP] 198.18.0.1:64810 --> 223.5.5.5:853 match DstPort(853) using REJECT"
time="2025-04-04T02:07:59.344804100+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-04T02:07:59.344804100+08:00" level=info msg="[UDP] 198.18.0.1:64811 --> 120.53.53.53:443 match AND(((DstPort,443) && (Network,udp))) using REJECT"
time="2025-04-04T02:07:59.358381000+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-04T02:07:59.358381000+08:00" level=info msg="[UDP] 198.18.0.1:51837 --> 223.5.5.5:853 match DstPort(853) using REJECT"
time="2025-04-04T02:07:59.358381000+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-04T02:07:59.358381000+08:00" level=info msg="[UDP] 198.18.0.1:51835 --> 120.53.53.53:443 match AND(((DstPort,443) && (Network,udp))) using REJECT"
time="2025-04-04T02:07:59.758682100+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-04T02:07:59.758682100+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-04T02:07:59.758682100+08:00" level=info msg="[UDP] 198.18.0.1:51837 --> 223.5.5.5:853 match DstPort(853) using REJECT"
time="2025-04-04T02:07:59.758682100+08:00" level=info msg="[UDP] 198.18.0.1:51835 --> 120.53.53.53:443 match AND(((DstPort,443) && (Network,udp))) using REJECT"
time="2025-04-04T02:08:00.558809100+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-04T02:08:00.558809100+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-04T02:08:00.558809100+08:00" level=info msg="[UDP] 198.18.0.1:51837 --> 223.5.5.5:853 match DstPort(853) using REJECT"
time="2025-04-04T02:08:00.558809100+08:00" level=info msg="[UDP] 198.18.0.1:51835 --> 120.53.53.53:443 match AND(((DstPort,443) && (Network,udp))) using REJECT"
time="2025-04-04T02:08:01.342216500+08:00" level=debug msg="re-creating the http client due to requesting https://120.53.53.53:443/dns-query: Get_0rtt \"https://120.53.53.53:443/dns-query?dns=AAABAAABAAAAAAAAA2RucwZnb29nbGUAABwAAQ\": context deadline exceeded"
time="2025-04-04T02:08:01.342216500+08:00" level=debug msg="[DNS] resolve dns.google A from https://120.53.53.53:443/dns-query"
time="2025-04-04T02:08:01.342216500+08:00" level=debug msg="[DNS] resolve dns.google A from 223.5.5.5:853"
time="2025-04-04T02:08:01.342216500+08:00" level=debug msg="[https://120.53.53.53:443/dns-query] using HTTP/2 for this upstream: <nil>"
time="2025-04-04T02:08:01.342216500+08:00" level=debug msg="creating a new http client"
time="2025-04-04T02:08:01.342216500+08:00" level=debug msg="[DNS] resolve geover.prod.do.dsp.mp.microsoft.com A from tls://dns.google:853"
time="2025-04-04T02:08:01.342216500+08:00" level=debug msg="[DNS] resolve geover.prod.do.dsp.mp.microsoft.com error: couldn't find ip"
time="2025-04-04T02:08:01.342216500+08:00" level=debug msg="[DNS] resolve functional.events.data.microsoft.com error: couldn't find ip"
time="2025-04-04T02:08:01.342216500+08:00" level=debug msg="[DNS] resolve dns.google AAAA from https://120.53.53.53:443/dns-query"
time="2025-04-04T02:08:01.342720300+08:00" level=debug msg="[https://120.53.53.53:443/dns-query] using HTTP/3 for this upstream: QUIC was faster"
time="2025-04-04T02:08:01.342216500+08:00" level=debug msg="[DNS] resolve dns.google AAAA from 223.5.5.5:853"
time="2025-04-04T02:08:01.342216500+08:00" level=debug msg="[DNS] resolve geover.prod.do.dsp.mp.microsoft.com AAAA from tls://dns.google:853"
time="2025-04-04T02:08:01.342216500+08:00" level=debug msg="[DNS] resolve functional.events.data.microsoft.com error: couldn't find ip"
time="2025-04-04T02:08:01.342720300+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-04T02:08:01.342720300+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-04T02:08:01.343240500+08:00" level=info msg="[UDP] 198.18.0.1:51840 --> 223.5.5.5:853 match DstPort(853) using REJECT"
time="2025-04-04T02:08:01.343240500+08:00" level=info msg="[UDP] 198.18.0.1:51841 --> 120.53.53.53:443 match AND(((DstPort,443) && (Network,udp))) using REJECT"
```
