### ISSUE TITLE
[Bug] expected-status字段是否有效

### ISSUE THREAD

**Issue by EnderAvaritia** [MetaCubeX/mihomo#1962]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

Windows 10 22H2

### Mihomo 版本

Mihomo Meta v1.19.4 windows amd64 with go1.20.14 Tue Apr  1 14:36:56 UTC 2025
Use tags: with_gvisor

### 配置文件

```yaml
- name: test1
    type: select
    url: https://storage.googleapis.com/labs-web-prod/favicon-48x48.png
    interval: 300
    tolerance: 100
    expected-status: "504"
    include-all: true

  - name: test2
    type: select
    url: https://storage.googleapis.com/labs-web-prod/favicon-48x48.png
    interval: 300
    tolerance: 100
    expected-status: "504"
    use:
        - RSS
    include-all: false
```

### 描述

我不清楚expected-status字段无法起作用是因为我配置文件写错了还是字段无效，我原本是想判定403的返回码用于确定节点是否送中，但是无效，因此尝试判定504，504正常情况下是连不上才会返回的，预期返回应该是所有节点离线，问题是，所有节点都显示在线。

![Image](https://github.com/user-attachments/assets/9da4656d-c402-4c4b-a39b-5a9ef05651b9) 

### 重现方式

添加代理组并且启动mihomo

### 日志

```shell
https://paste.ubuntu.com/p/wW3Y3f7vRZ/
日志太长， github 不让我粘贴，这里也不能贴文件
```
