### ISSUE TITLE
[Feature] 希望拓展 `use` 参数的功能

### ISSUE THREAD

**Issue by ChuheGit** [MetaCubeX/mihomo#1964]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [x] 我是中文用户，而非其他语言用户

### 描述

实现类似场景：同时筛选两个机场的 **香港** 节点，并让 **机场A** 优先命中，减少 **proxy-provider** 的本地下载和存储，策略嵌套更加灵活。

sample：
 ```
  - name: "HK"
    type: fallback
    use:  # 目前无法使用 use 引用 HKA HKB
      - HK A
      - HK B

  - name: "HK A"
    type: select
    filter: "^(?=.*香港)(?=.*优化)"
    use:
      - 机场A

  - name: "HK B"
    type: select
    filter:"^(?=.*香港)(?=.*中转)"
    use:
      - 机场B
```

目前 **proxy-group** 内 **use** 参数只能引用 **proxy-provider**。**proxy-group** 策略内嵌套只可以使用 **proxies**，未支持 **use**
