### ISSUE TITLE
syntax error: loop check bug[Bug]

### ISSUE THREAD

**Issue by shazvic** [MetaCubeX/mihomo#1966]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [x] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### System Version

windows11

### Mihomo Version

v1.19.4 mihomo

### Configuration File

```yaml
proxies:
  - name: "直连"
    type: direct
    udp: true
pr: &pr {type: select, proxies: [🚀 默认代理,🌐 全部节点, 直连]}
proxy-groups:
- {name: "🚀 默认代理", <<: *pr, exclude-filter: 🚀 默认代理}
- {name: 🌐 全部节点, type: select, include-all: true}
```

### Description

failed to pass syntax check: 'loop is detected in ProxyGroup, please check following ProxyGroups: [🚀 默认代理]'

I am certain "exclude-filter" can do its job excluding proxy-groups. Maybe check loop can be done after exclude-filter applies?

### Reproduction Steps

Run syntax check

### Logs

```shell
loop is detected in ProxyGroup, please check following ProxyGroups: [🚀 默认代理]
```
