### ISSUE TITLE
[Bug] 开启TUN模式后，tracert 本机IP变得很慢，3-5秒执行完成，关闭TUN后可以瞬间完成

### ISSUE THREAD

**Issue by startle09** [MetaCubeX/mihomo#1974]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

10/11

### Mihomo 版本

1.19.4

### 配置文件

```yaml
tun:
  route-exclude-address:
  - 192.168.0.0/16
  stack: gvisor
  device: Meta
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  strict-route: true
  mtu: 1500
  enable: true
```

### 描述

开启TUN模式后，tracert 本机IP变得很慢，3-5秒执行完成，关闭TUN后可以瞬间完成

已做过的尝试：

切换stack
添加route-exclude-address
重启内核
重启系统
更换系统
更换电脑

均复现

### 重现方式

cmd执行tracert本机ip

### 日志

```shell
DEBUG没有相关日志
```
