### ISSUE TITLE
[Bug] ShadowsocksR 节点无法通过 dialer-proxy 链式代理 WireGuard

### ISSUE THREAD

**Issue by ramondsq** [MetaCubeX/mihomo#1979]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

Windows 11 专业版 24H2 26100.3775

### Mihomo 版本

Mihomo Meta alpha-8fa4e81 windows amd64 with go1.24.2 Sat Apr 12 19:04:07 UTC 2025
Use tags: with_gvisor

### 配置文件

```yaml
# url 里填写自己的订阅,名称不能重复
proxy-providers:
  provider1:
    url: 
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204", interval: 300}
    override:
      additional-prefix: "[]"

log-level: debug

proxies: 
  - name: "直连"
    type: direct
    udp: true
  - name: "wg"
    type: wireguard
    private-key: 
    server: engage.cloudflareclient.com
    port: 2408
    ip: 172.16.0.2
    ipv6: 2606:4700:110:801a:902d:811a:7ac0:43d2
    public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
    allowed-ips: ['0.0.0.0/0']
    udp: true
    dialer-proxy: "ssr"
    remote-dns-resolve: true
    dns: [ 1.1.1.1, 8.8.8.8 ]
  - name: "vmess"
    type: vmess
    server: 
    port: 20012
    udp: true
    uuid: 
    alterId: 0
    cipher: auto
    network: tcp
  - name: "ssr" 
    server: 
    port: 2601
    type: ssr
    cipher: aes-256-cfb
    password: 
    protocol: auth_aes128_md5
    obfs: tls1.2_ticket_auth
    protocol-param: 144637:OXhxrl
    obfs-param: 8685f144637.www.gov.hk
    udp: true

mixed-port: 7890
ipv6: true
allow-lan: true
unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

geodata-mode: true
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"
  asn: "https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  default-nameserver:
    - tls://223.5.5.5
    - tls://223.6.6.6
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

proxy-groups:

  - name: 默认
    type: select
    proxies: [自动选择,直连,香港,台湾,日本,新加坡,美国,菲律宾,其它地区,全部节点,wg,vmess,ssr]

  - name: Google
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: Telegram
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: Twitter
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: 哔哩哔哩
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: 巴哈姆特
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: YouTube
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: NETFLIX
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: Spotify
    type: select
    proxies:  [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: Github
    type: select
    proxies:  [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: 国内
    type: select
    proxies:  [直连,默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择]

  - name: 其他
    type: select
    proxies:  [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  #分隔,下面是地区分组
  - name: 香港
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)港|hk|hongkong|hong kong"

  - name: 台湾
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)台|tw|taiwan"

  - name: 日本
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)日|jp|japan"

  - name: 美国
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)美|us|unitedstates|united states"

  - name: 新加坡
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)(新|sg|singapore)"

  - name: 菲律宾
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)菲|ph|philippines"

  - name: 其它地区
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*"

  - name: 全部节点
    type: select
    include-all: true
    exclude-type: direct

  - name: 自动选择
    type: url-test
    include-all: true
    exclude-type: direct
    tolerance: 10

rules:
  - GEOIP,lan,直连,no-resolve
  - GEOSITE,github,Github
  - GEOSITE,twitter,Twitter
  - GEOSITE,youtube,YouTube
  - GEOSITE,google,Google
  - GEOSITE,telegram,Telegram
  - GEOSITE,netflix,NETFLIX
  - GEOSITE,bilibili,哔哩哔哩
  - GEOSITE,bahamut,巴哈姆特
  - GEOSITE,spotify,Spotify
  - GEOSITE,CN,国内
  - GEOSITE,geolocation-!cn,其他

  - GEOIP,google,Google
  - GEOIP,netflix,NETFLIX
  - GEOIP,telegram,Telegram
  - GEOIP,twitter,Twitter
  - GEOIP,CN,国内
  - MATCH,其他
```

### 描述

我尝试使用 wireguard 节点作为机场节点的**落地代理**。我在 wireguard 节点信息中加入 `dialer-proxy:` 字段，指向机场提供的 ssr 节点，关键配置如下所示。但是发现 wireguard 节点无法作为 ssr 节点的后置节点，会出现无法连接。当我尝试把 ssr 节点换为 vmess 节点时，wireguard 落地代理可以正常使用。
同时我也验证了 ssr 节点本身是可以正常使用的。
```
proxies: 
  - name: "wg"
    type: wireguard
    private-key: 
    server: engage.cloudflareclient.com
    port: 2408
    ip: 172.16.0.2
    ipv6: 2606:4700:110:801a:902d:811a:7ac0:43d2
    public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
    allowed-ips: ['0.0.0.0/0']
    udp: true
    dialer-proxy: "ssr"
    remote-dns-resolve: true
    dns: [ 1.1.1.1, 8.8.8.8 ]

  - name: "ssr" 
    server: 
    port: 2601
    type: ssr
    cipher: aes-256-cfb
    password: 
    protocol: auth_aes128_md5
    obfs: tls1.2_ticket_auth
    protocol-param: 144637:OXhxrl
    obfs-param: 8685f144637.www.gov.hk
    udp: true
```

### 重现方式

通过命令`.\mihomo-windows-amd64.exe -d ./`运行，同目录下包含以下文件。配置文件来自官方文档。
```
config.yaml
geoip.dat
geosite.dat
mihomo-windows-amd64.exe
```

### 日志

```shell
time="2025-04-13T12:30:00.994763900+08:00" level=debug msg="Health Checked, proxy: [机场名]🇰🇷 Lil 韩国05 | 倍率:1.2, url: https://www.gstatic.com/generate_204, alive: true, delay: 471 ms uid: {04ff3bc6-6d7f-432c-b6a1-6b14a368126e}"
time="2025-04-13T12:30:01.011656600+08:00" level=debug msg="Health Checked, proxy: [机场名]🇭🇰 Lil 香港11 | 倍率:2, url: https://www.gstatic.com/generate_204, alive: true, delay: 174 ms uid: {04ff3bc6-6d7f-432c-b6a1-6b14a368126e}"
time="2025-04-13T12:30:01.029132300+08:00" level=debug msg="Health Checked, proxy: [机场名]🇦🇷 Lil 阿根廷01 | 倍率:1.5, url: https://www.gstatic.com/generate_204, alive: true, delay: 1130 ms uid: {04ff3bc6-6d7f-432c-b6a1-6b14a368126e}"
time="2025-04-13T12:30:01.385066700+08:00" level=debug msg="Health Checked, proxy: [机场名]🇭🇰 Lil 香港06 | 倍率:1.5, url: https://www.gstatic.com/generate_204, alive: true, delay: 718 ms uid: {04ff3bc6-6d7f-432c-b6a1-6b14a368126e}"
time="2025-04-13T12:30:02.382325800+08:00" level=debug msg="Health Checked, proxy: wg, url: https://www.gstatic.com/generate_204, alive: false, delay: 65535 ms uid: {6688f644-fc74-487e-815c-42d76358ada4}"
time="2025-04-13T12:30:02.382325800+08:00" level=debug msg="Health Checked, proxy: ssr, url: https://www.gstatic.com/generate_204, alive: false, delay: 65535 ms uid: {6688f644-fc74-487e-815c-42d76358ada4}"
time="2025-04-13T12:30:02.383130600+08:00" level=debug msg="Finish A Health Checking {6688f644-fc74-487e-815c-42d76358ada4}"
time="2025-04-13T12:30:02.867594300+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 2)"
time="2025-04-13T12:30:02.867594300+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:30:03.987996700+08:00" level=debug msg="Health Checked, proxy: [机场名]🇺🇸 Lil 美国04 | 倍率:1.3, url: https://www.gstatic.com/generate_204, alive: false, delay: 65535 ms uid: {04ff3bc6-6d7f-432c-b6a1-6b14a368126e}"
time="2025-04-13T12:30:03.988671100+08:00" level=debug msg="Finish A Health Checking {04ff3bc6-6d7f-432c-b6a1-6b14a368126e}"
time="2025-04-13T12:30:08.191479800+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 3)"
time="2025-04-13T12:30:08.191479800+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:30:13.292571000+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 4)"
time="2025-04-13T12:30:13.292571000+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:30:16.592474500+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [机场服务器ip] A, expire at 2025-04-13 12:30:25"
time="2025-04-13T12:30:16.592474500+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [] AAAA, expire at 2025-04-13 12:31:08"
time="2025-04-13T12:30:16.594017500+08:00" level=debug msg="[DNS] cache hit www.gstatic.com --> [203.208.41.98] A, expire at 2025-04-13 12:33:58"
time="2025-04-13T12:30:16.594017500+08:00" level=debug msg="[DNS] cache hit www.gstatic.com --> [] AAAA, expire at 2025-04-13 12:30:57"
time="2025-04-13T12:30:16.594766900+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [] AAAA, expire at 2025-04-13 12:31:08"
time="2025-04-13T12:30:16.594766900+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [机场服务器ip] A, expire at 2025-04-13 12:30:25"
time="2025-04-13T12:30:16.595280800+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [机场服务器ip] A, expire at 2025-04-13 12:30:25"
time="2025-04-13T12:30:16.595280800+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [] AAAA, expire at 2025-04-13 12:31:08"
time="2025-04-13T12:30:16.596404000+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [机场服务器ip] A, expire at 2025-04-13 12:30:25"
time="2025-04-13T12:30:16.596404000+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [] AAAA, expire at 2025-04-13 12:31:08"
time="2025-04-13T12:30:16.596907200+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [] AAAA, expire at 2025-04-13 12:31:08"
time="2025-04-13T12:30:16.596907200+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [机场服务器ip] A, expire at 2025-04-13 12:30:25"
time="2025-04-13T12:30:16.680841400+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [机场服务器ip] A, expire at 2025-04-13 12:30:25"
time="2025-04-13T12:30:16.680841400+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [] AAAA, expire at 2025-04-13 12:31:08"
time="2025-04-13T12:30:16.682437600+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [机场服务器ip] A, expire at 2025-04-13 12:30:25"
time="2025-04-13T12:30:16.682437600+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [] AAAA, expire at 2025-04-13 12:31:08"
time="2025-04-13T12:30:16.688838500+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [机场服务器ip] A, expire at 2025-04-13 12:30:25"
time="2025-04-13T12:30:16.690338700+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [] AAAA, expire at 2025-04-13 12:31:08"
time="2025-04-13T12:30:16.707089700+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [机场服务器ip] A, expire at 2025-04-13 12:30:25"
time="2025-04-13T12:30:16.707089700+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [] AAAA, expire at 2025-04-13 12:31:08"
time="2025-04-13T12:30:16.827467200+08:00" level=debug msg="[DNS] resolve www.gstatic.com A from udp://8.8.8.8:53"
time="2025-04-13T12:30:16.827467200+08:00" level=debug msg="[DNS] resolve www.gstatic.com A from udp://1.1.1.1:53"
time="2025-04-13T12:30:16.827467200+08:00" level=debug msg="[DNS] resolve www.gstatic.com AAAA from udp://8.8.8.8:53"
time="2025-04-13T12:30:16.827467200+08:00" level=debug msg="[DNS] resolve www.gstatic.com AAAA from udp://1.1.1.1:53"
time="2025-04-13T12:30:16.827467200+08:00" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using wg"
time="2025-04-13T12:30:16.827467200+08:00" level=info msg="[UDP] mihomo --> 1.1.1.1:53 doesn't match any rule using wg"
time="2025-04-13T12:30:16.827467200+08:00" level=info msg="[UDP] mihomo --> 8.8.8.8:53 doesn't match any rule using wg"
time="2025-04-13T12:30:16.827467200+08:00" level=info msg="[UDP] mihomo --> 1.1.1.1:53 doesn't match any rule using wg"
time="2025-04-13T12:30:16.937937200+08:00" level=debug msg="[DNS] cache hit stream.c01-h01.fnode.top --> [221.131.165.141] A, expire at 2025-04-13 12:29:58"
time="2025-04-13T12:30:16.937937200+08:00" level=debug msg="[DNS] cache hit stream.c01-h01.fnode.top --> [] AAAA, expire at 2025-04-13 12:30:57"
time="2025-04-13T12:30:16.937937200+08:00" level=debug msg="[DNS] resolve stream.c01-h01.fnode.top A from https://dns.alidns.com:443/dns-query"
time="2025-04-13T12:30:16.937937200+08:00" level=debug msg="[DNS] resolve stream.c01-h01.fnode.top A from https://doh.pub:443/dns-query"
time="2025-04-13T12:30:16.942280000+08:00" level=debug msg="[DNS] stream.c01-h01.fnode.top --> [221.131.165.142] A from https://dns.alidns.com:443/dns-query"
time="2025-04-13T12:30:17.006629800+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [] AAAA, expire at 2025-04-13 12:31:08"
time="2025-04-13T12:30:17.006629800+08:00" level=debug msg="[DNS] cache hit [机场服务器url] --> [机场服务器ip] A, expire at 2025-04-13 12:30:25"
time="2025-04-13T12:30:18.406106700+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 2)"
time="2025-04-13T12:30:18.406106700+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:30:23.657339500+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 3)"
time="2025-04-13T12:30:23.657339500+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:30:28.866901700+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 4)"
time="2025-04-13T12:30:28.866901700+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:30:33.870817900+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 5)"
time="2025-04-13T12:30:33.870817900+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:30:38.883925100+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 6)"
time="2025-04-13T12:30:38.883925100+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:30:44.018933500+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 7)"
time="2025-04-13T12:30:44.018933500+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:30:49.227685400+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 8)"
time="2025-04-13T12:30:49.227685400+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:30:54.417022100+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 9)"
time="2025-04-13T12:30:54.417022100+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:30:59.495902200+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 10)"
time="2025-04-13T12:30:59.495902200+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:31:04.742579200+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 11)"
time="2025-04-13T12:31:04.742896800+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:31:10.062898000+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 12)"
time="2025-04-13T12:31:10.062898000+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:31:15.081116800+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 13)"
time="2025-04-13T12:31:15.081116800+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:31:20.149155700+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 14)"
time="2025-04-13T12:31:20.149155700+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:31:25.273253500+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 15)"
time="2025-04-13T12:31:25.273253500+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:31:30.407114700+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 16)"
time="2025-04-13T12:31:30.407114700+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:31:35.608635000+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 17)"
time="2025-04-13T12:31:35.608635000+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:31:40.820980000+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 18)"
time="2025-04-13T12:31:40.820980000+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
time="2025-04-13T12:31:45.928118700+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 19)"
time="2025-04-13T12:31:45.928118700+08:00" level=debug msg="[WG](wg) peer(bmXO…fgyo) - Sending handshake initiation"
```
