### ISSUE TITLE
[Bug] 最新v1.19.4无法使用vless-reality，同样的配置文件在v1.94.3上可用

### ISSUE THREAD

**Issue by Jzzzi** [MetaCubeX/mihomo#1980]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Windows

### System Version

windows11家庭中文版

### Mihomo Version

Mihomo Meta v1.19.4 windows amd64 with go1.24.1 Tue Apr  1 14:37:26 UTC 2025
Use tags: with_gvisor

### Configuration File

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
dns:
  enabled: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - tls://1.0.0.1:853
    - tls://dns.google:853
proxies:
  - {name: New York, server: 1**.***.***.**2, port: 62224, reality-opts: {public-key: IsRfieqk6tYxyS5Ia5zcPqY9BISF9YdozGyQtJc7TFM}, client-fingerprint: chrome, type: vless, uuid: 73fb653f-****-4e56-8e79-1279da6101c2, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, servername: www.cloudflare.com, network: tcp}
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
      - DIRECT
  - name: 🚀 手动切换
    type: select
    proxies:
      - New York
  - name: 📲 电报消息
    type: select
    proxies:
      - 🚀 节点选择
      - 🇸🇬 狮城节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
      - DIRECT
  - name: 💬 OpenAi
    type: select
    proxies:
      - 🚀 节点选择
      - 🇸🇬 狮城节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
      - DIRECT
  - name: 📹 油管视频
    type: select
    proxies:
      - 🚀 节点选择
      - 🇸🇬 狮城节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
      - DIRECT
  - name: 🎥 奈飞视频
    type: select
    proxies:
      - 🎥 奈飞节点
      - 🚀 节点选择
      - 🇸🇬 狮城节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
      - DIRECT
  - name: 📺 巴哈姆特
    type: select
    proxies:
      - 🇨🇳 台湾节点
      - 🚀 节点选择
      - 🚀 手动切换
      - DIRECT
  - name: 📺 哔哩哔哩
    type: select
    proxies:
      - 🎯 全球直连
      - 🇨🇳 台湾节点
      - 🇭🇰 香港节点
  - name: 🌍 国外媒体
    type: select
    proxies:
      - 🚀 节点选择
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
      - DIRECT
  - name: 🌏 国内媒体
    type: select
    proxies:
      - DIRECT
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🚀 手动切换
  - name: 📢 谷歌FCM
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🇺🇲 美国节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
  - name: Ⓜ️ 微软Bing
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🇺🇲 美国节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
  - name: Ⓜ️ 微软云盘
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🇺🇲 美国节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🇺🇲 美国节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
  - name: 🍎 苹果服务
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🇺🇲 美国节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
  - name: 🎮 游戏平台
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🇺🇲 美国节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
  - name: 🎶 网易音乐
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
  - name: 🛑 广告拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🍃 应用净化
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - DIRECT
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
  - name: 🇭🇰 香港节点
    type: select
    proxies:
      - DIRECT
  - name: 🇯🇵 日本节点
    type: select
    proxies:
      - DIRECT
  - name: 🇺🇲 美国节点
    type: select
    proxies:
      - DIRECT
  - name: 🇸🇬 狮城节点
    type: select
    proxies:
      - DIRECT
  - name: 🇨🇳 台湾节点
    type: select
    proxies:
      - DIRECT
  - name: 🇰🇷 韩国节点
    type: select
    proxies:
      - DIRECT
  - name: 🎥 奈飞节点
    type: select
    proxies:
      - DIRECT
rules:
  - DOMAIN-SUFFIX,acl4.ssr,🎯 全球直连
  ...省略...
```

### Description

运行`.\mihomo-windows-amd64.exe -f .\config.yaml`，会提示多次类似于
```
time="2025-04-13T16:04:41.332336400+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match DomainKeyword/github) 127.0.0.1:61454(msedge.exe) --> alive.github.com:443 error: 107.172.140.181:62224 connect error: REALITY authentication failed"
```
的报错，并且无法连接，但是实测在v1.19.3的版本中，同样的配置文件不会出现问题。

### Reproduction Steps

运行`.\mihomo-windows-amd64.exe -f .\config.yaml`，其中配置文件为上述基于vless-reality的配置文件，服务端使用的xray脚本搭建。

### Logs

```shell

```
