### ISSUE TITLE
[Bug] 在使用ssr节点过程中出现panic: runtime error: slice bounds out of range [12:0]

### ISSUE THREAD

**Issue by cuddly-guacamole** [MetaCubeX/mihomo#1983]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Android

### 系统版本

alpha-9e0889c

### Mihomo 版本

Mihomo Meta alpha-9e0889c android arm64 with go1.24.2 Wed Apr 16 06:11:41 UTC 2025
Use tags: with_gvisor

### 配置文件

```yaml
mixed-port: 7892
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
allow-lan: true
mode: rule
log-level: debug
ipv6: true
udp: true
keep-alive-idle: 600
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 443, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 853, 8443]
    QUIC:
      ports: [443, 853, 8443]

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  dns-hijack: [any:53]

dns:
  enable: true
  cache-algorithm: arc
  ipv6: true
  listen: 0.0.0.0:1053
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-filter: ['rule-set:private,cn']
  nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query#h3=true']
  proxy-server-nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query#h3=true']

proxies:
  - {"type":"ssr","server":"","port":,"protocol":"auth_aes128_md5","cipher":"chacha20-ietf","obfs":"tls1.2_ticket_auth","password":"","name":"[Vip3] 香港 01 | 深港专线 |x3","protocol-param":"122307:thulVEt5GPKAmvl6","obfs-param":"27d2d122307.microsoft.com","udp":true,"tfo":true,"fast-open":true}

proxy-groups:
  - {name: 代理, <<: *SelectHK}
  - {name: 微软服务, <<: *SelectProxy}
  - {name: 谷歌服务, <<: *SelectProxy}
  - {name: 香港策略, type: select, proxies: [香港自动], include-all: true, filter: *FilterHK}
  - {name: 国内网站, type: select, proxies: [direct]}
  - {name: 漏网之鱼, type: select, proxies: [代理, direct]}
  - {name: 香港自动, <<: *UrlTest, filter: *FilterHK}

rules:
  - RULE-SET,private,国内网站,no-resolve
  - RULE-SET,microsoft,微软服务
  - RULE-SET,google,谷歌服务
  - RULE-SET,cn,国内网站
  - RULE-SET,private_ip,国内网站,no-resolve
  - RULE-SET,cn_ip,国内网站,no-resolve
  - MATCH,漏网之鱼

FilterHK: &FilterHK '^(?=.*(?i)(港|🇭🇰|HK|Hong|HKG))(?!.*(排除1|排除2|5x)).*$'
UrlTest: &UrlTest {type: url-test, interval: 60, tolerance: 20, lazy: true, url: 'https://wifi.vivo.com.cn/generate_204', disable-udp: false, timeout: 2000, max-failed-times: 3, hidden: true, include-all: true, proxies: [REJECT]}
SelectHK: &SelectHK {type: select, proxies: [香港策略, direct]}
SelectProxy: &SelectProxy {type: select, proxies: [代理, 香港策略, direct]}
```

### 描述

已经尽量缩减配置文件了。机场提供的是SSR订阅链接，我用了 sub-store-org/Sub-Store 把节点转换成 mihomo 能用的格式，并开了 UDP 转发和 TCP Fast Open。

### 重现方式

启动内核，使用配置文件中的节点浏览网站。

### 日志

```shell
time="2025-04-16T20:13:38.241955249+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-16T20:13:38.242131708+08:00" level=debug msg="[DNS] cache hit iepl.nodecn.top --> [183.240.139.245 120.232.220.41 120.241.45.12] A, expire at 2025-04-16 20:13:53"
time="2025-04-16T20:13:38.242181864+08:00" level=debug msg="[DNS] cache hit content-autofill.googleapis.com --> [142.250.217.106 142.250.217.74 142.251.33.74 142.251.215.234 172.217.14.202 142.250.69.202 142.251.33.106 142.251.211.234] A, expire at 2025-04-16 20:16:55"
time="2025-04-16T20:13:38.242255145+08:00" level=debug msg="[DNS] cache hit content-autofill.googleapis.com --> [] AAAA, expire at 2025-04-16 20:13:35"
time="2025-04-16T20:13:38.242351187+08:00" level=debug msg="[DNS] cache hit iepl.nodecn.top --> [] AAAA, expire at 2025-04-16 20:13:49"
time="2025-04-16T20:13:38.242474260+08:00" level=debug msg="[DNS] resolve content-autofill.googleapis.com AAAA from https://dns.alidns.com:443/dns-query"
time="2025-04-16T20:13:38.242663218+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-16T20:13:38.242744312+08:00" level=debug msg="[TUN] Auto detect interface for 183.240.139.245 --> rmnet_data1"
time="2025-04-16T20:13:38.242787541+08:00" level=debug msg="[TUN] Auto detect interface for 2400:3200:baba::1 --> rmnet_data1"
time="2025-04-16T20:13:38.243255979+08:00" level=info msg="[UDP] mihomo --> [2400:3200:baba::1]:443 match RuleSet(cn_ip) using 国内网站[直连]"
time="2025-04-16T20:13:38.242796499+08:00" level=debug msg="[DNS] resolve content-autofill.googleapis.com AAAA from https://doh.pub:443/dns-query"
time="2025-04-16T20:13:38.242686395+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-16T20:13:38.242807906+08:00" level=debug msg="[TUN] Auto detect interface for 120.241.45.12 --> rmnet_data1"
time="2025-04-16T20:13:38.242822593+08:00" level=debug msg="[TUN] Auto detect interface for 120.232.220.41 --> rmnet_data1"
time="2025-04-16T20:13:38.244325458+08:00" level=debug msg="[DNS] cache hit iepl.nodecn.top --> [] AAAA, expire at 2025-04-16 20:13:49"
time="2025-04-16T20:13:38.244882072+08:00" level=debug msg="[DNS] cache hit iepl.nodecn.top --> [183.240.139.245 120.232.220.41 120.241.45.12] A, expire at 2025-04-16 20:13:53"
time="2025-04-16T20:13:38.245026239+08:00" level=debug msg="[TUN] Auto detect interface for ::ffff:120.232.220.41 --> rmnet_data1"
time="2025-04-16T20:13:38.245235354+08:00" level=info msg="[UDP] 198.18.0.1:45091 --> content-autofill.googleapis.com:443 match RuleSet(google) using 谷歌服务[[GKD] [Vip3] 香港 01 | 深港专线 |x3]"
time="2025-04-16T20:13:38.265480874+08:00" level=debug msg="[DNS] hijack udp:218.85.157.99:53 from 198.18.0.1:30834"
time="2025-04-16T20:13:38.268283895+08:00" level=debug msg="[DNS] hijack udp:218.85.157.99:53 from 198.18.0.1:56863"
time="2025-04-16T20:13:38.270613062+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-16T20:13:38.270836812+08:00" level=debug msg="[DNS] cache hit iepl.nodecn.top --> [] AAAA, expire at 2025-04-16 20:13:49"
time="2025-04-16T20:13:38.271089156+08:00" level=debug msg="[DNS] cache hit iepl.nodecn.top --> [183.240.139.245 120.232.220.41 120.241.45.12] A, expire at 2025-04-16 20:13:53"
time="2025-04-16T20:13:38.271255249+08:00" level=debug msg="[TUN] Auto detect interface for 120.241.45.12 --> rmnet_data1"
time="2025-04-16T20:13:38.271777020+08:00" level=debug msg="[TUN] Auto detect interface for 183.240.139.245 --> rmnet_data1"
time="2025-04-16T20:13:38.271819364+08:00" level=debug msg="[TUN] Auto detect interface for 120.232.220.41 --> rmnet_data1"
time="2025-04-16T20:13:38.310150093+08:00" level=info msg="[TCP] 198.18.0.1:38446 --> content-autofill.googleapis.com:443 match RuleSet(google) using 谷歌服务[[GKD] [Vip3] 香港 01 | 深港专线 |x3]"
time="2025-04-16T20:13:38.310413687+08:00" level=debug msg="[DNS] content-autofill.googleapis.com --> [2404:6800:4012:8::200a 2404:6800:4012:9::200a 2404:6800:4012:6::200a 2404:6800:4012:7::200a] AAAA from https://doh.pub:443/dns-query"
time="2025-04-16T20:13:38.314460614+08:00" level=info msg="[TCP] 198.18.0.1:42614 --> alive.github.com:443 match RuleSet(microsoft) using 微软服务[[GKD] [Vip3] 香港 01 | 深港专线 |x3]"
time="2025-04-16T20:13:38.362157437+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-16T20:13:38.362740614+08:00" level=debug msg="[DNS] cache hit iepl.nodecn.top --> [183.240.139.245 120.232.220.41 120.241.45.12] A, expire at 2025-04-16 20:13:53"
time="2025-04-16T20:13:38.363354885+08:00" level=debug msg="[DNS] cache hit iepl.nodecn.top --> [] AAAA, expire at 2025-04-16 20:13:49"
time="2025-04-16T20:13:38.364935145+08:00" level=debug msg="[TUN] Auto detect interface for 120.241.45.12 --> rmnet_data1"
time="2025-04-16T20:13:38.365570874+08:00" level=debug msg="[TUN] Auto detect interface for 120.232.220.41 --> rmnet_data1"
time="2025-04-16T20:13:38.365826760+08:00" level=debug msg="[TUN] Auto detect interface for 183.240.139.245 --> rmnet_data1"
time="2025-04-16T20:13:38.367981031+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-16T20:13:38.368117541+08:00" level=debug msg="[DNS] cache hit iepl.nodecn.top --> [] AAAA, expire at 2025-04-16 20:13:49"
time="2025-04-16T20:13:38.368141551+08:00" level=debug msg="[DNS] cache hit iepl.nodecn.top --> [183.240.139.245 120.232.220.41 120.241.45.12] A, expire at 2025-04-16 20:13:53"
time="2025-04-16T20:13:38.368165406+08:00" level=debug msg="[TUN] Auto detect interface for 120.241.45.12 --> rmnet_data1"
time="2025-04-16T20:13:38.368343114+08:00" level=debug msg="[TUN] Auto detect interface for 120.232.220.41 --> rmnet_data1"
time="2025-04-16T20:13:38.368393322+08:00" level=debug msg="[TUN] Auto detect interface for 183.240.139.245 --> rmnet_data1"
time="2025-04-16T20:13:38.403321864+08:00" level=info msg="[TCP] 198.18.0.1:38454 --> content-autofill.googleapis.com:443 match RuleSet(google) using 谷歌服务[[GKD] [Vip3] 香港 01 | 深港专线 |x3]"
time="2025-04-16T20:13:38.408713479+08:00" level=info msg="[TCP] 198.18.0.1:42630 --> alive.github.com:443 match RuleSet(microsoft) using 微软服务[[GKD] [Vip3] 香港 01 | 深港专线 |x3]"
panic: runtime error: slice bounds out of range [12:0]

goroutine 2981 [running]:
github.com/metacubex/mihomo/transport/shadowsocks/shadowstream.(*PacketConn).WaitReadFrom(0x400066dba0)
	github.com/metacubex/mihomo/transport/shadowsocks/shadowstream/packet.go:87 +0x124
github.com/metacubex/mihomo/transport/ssr/protocol.(*PacketConn).WaitReadFrom(0x400066dbc0)
	github.com/metacubex/mihomo/transport/ssr/protocol/packet.go:40 +0x2c
github.com/metacubex/mihomo/adapter/outbound.(*ssrPacketConn).WaitReadFrom(0x40010c6fc0?)
	github.com/metacubex/mihomo/adapter/outbound/shadowsocksr.go:239 +0x2c
github.com/metacubex/mihomo/common/net/deadline.(*enhancePacketConn).pipeWaitReadFrom(0x400066dc08)
	github.com/metacubex/mihomo/common/net/deadline/packet_enhance.go:76 +0x2c
created by github.com/metacubex/mihomo/common/net/deadline.(*enhancePacketConn).WaitReadFrom in goroutine 2952
	github.com/metacubex/mihomo/common/net/deadline/packet_enhance.go:70 +0x2dc
```
