### ISSUE TITLE
[Bug] shadowsocks listener入站，udp请求有多余的本地dns请求

### ISSUE THREAD

**Issue by Simcfcs** [MetaCubeX/mihomo#1985]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

Docker version 20.10.3, build b35e731

### Mihomo 版本

Mihomo Meta v1.19.4 linux amd64 with go1.24.1 Tue Apr  1 14:38:17 UTC 2025

### 配置文件

```yaml
allow-lan: true

bind-address: "*"

mode: rule

find-process-mode: off

log-level: debug

ipv6: false


external-controller: 0.0.0.0:9090

external-ui: /ui

secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"


dns:
  enable: false

proxies:
  - name: Pedal
    type: ss
    server: 机场ss服务域名，确认支持udp
    port: "34874"
    cipher: chacha20-ietf-poly1305
    password: jintianhaoreya123
    udp: true
    
    
rules:
  - IN-NAME,Pedal-SS-IN,Pedal
  - MATCH,REJECT
  
listeners:
  - name: Pedal-SS-IN
    type: shadowsocks
    port: 34874
    listen: 0.0.0.0
    password: hahahahahahahahahahaha
    cipher: chacha20-ietf-poly1305
    udp: true
```

### 描述

docker网络是macvlan，配置的ip是192.168.0.240，dns是192.168.0.253.

手机ios18.4.1
Shadowrocket2.2.64
app发起通过udp走的访问，比如instagram的app发起，i.instagram.com，的443，应该是QUIC。
此时，mihomo收到请求后，会通过本地dns192.168.0.253，请求一下i.instragram.com的A记录，然后再开始开始通过机场ss服务器去访问数据。

而tcp链接，就没有这一步，直接就是把请求送出去到远程机场ss服务器，不在本地做dns请求。

这条udp443的请求，最终发起的时候，在ui界面点详情，大概是这样的
目标域名：i.instragram.com
目标ip：“具体ip，通过250查询得到的”
远程主机：机场ss的ip域名，这里是机场域名，不是ip

而普通的tcp请求，看起来是这样的
目标域名：i.instragram.com
目标ip：“这里是空的”
远程主机：机场ss的ip，不是域名

我希望的结果，因为rule很简单，就是直接送走，那udp应该和tcp一样，不需要本地解析一下域名，直接从配置的远端ss发走。

谢谢。

另外，因为请求本地dns得到的ip可能有污染，所以，最终这条udp数据连接，大概率是不通的，但不绝对不通，偶尔还是会通。

再另外，其实我这几天都在试，还是这个版本的mihomo，入站用socks5，用trojan都是一样的效果。

然后，我换了个环境，那里有跑了几年的一个docker版本的clash（截至停更最后一个版本），也一样。
只要是udp协议通过域名发起的业务，都会请求一次本次dns，来解析那个域名。

再然后，docker版本的xray，没这个问题，不论udp还是tcp，都是本地不解析域名，直接往机场ss送，但是我想用mihomo。。。
上面说的测试，各个软件都没启用dns，没有启用tun，就是很简单的一个入站，然后无脑转走。

以上供参考。

谢谢。

对了，解释下为什么要这么用，我在局域网装了个这个，提供一个ss入口，给局域网连进来，转给机场，具体规则，都是大家在各个客户端上自己去设置，这个ss入口相当于全局转走，没有分流规则。
这样一来，可以给大家只要在办公环境，就可以使用公司提供的出口，下班后，就和公司无关了。因为对于用户来说，服务器是局域网地址，而且之前clash，现在mihomo都有ui界面来做观察和管理。
网关模式的话，没有这管理精细，所以就一直这样用了不少年了。

说完了，谢谢。

### 重现方式

docker pull metacubex/mihomo:latest
引用上面的配置文件。

ios手机端，配置代理，打开instagram app

本地dns服务器上看，可以看到有来自docker的dns请求，请求的域名，就是手机端发起的，udp的域名。

### 日志

```shell
192.168.0.102是手机的ip

tcp是这样的:
DEBU[2025-04-18T16:51:39.997353952Z] [DNS] cache hit 机场ss域名 --> [ip地址] A, expire at 2025-04-18 16:51:49 
INFO[2025-04-18T16:51:40.447221344Z] [TCP] 192.168.0.102:3614 --> signaler-pa.clients6.google.com:443 match InName(Pedal-SS-IN) using Pedal


udp是这样的，对域名多了一次本地发起的dns请求:
DEBU[2025-04-18T16:51:53.930551037Z] [DNS] resolve i.instagram.com A from udp://192.168.0.253:53 
DEBU[2025-04-18T16:51:53.934766507Z] [DNS] i.instagram.com --> [208.31.254.33] A from udp://192.168.0.253:53 
INFO[2025-04-18T16:51:54.392708969Z] [UDP] 192.168.0.102:62375 --> i.instagram.com:443 match InName(Pedal-SS-IN) using Pedal
```
