### ISSUE TITLE
[Bug] dns模块所使用的doh的域名解析不遵循hosts模块定义

### ISSUE THREAD

**Issue by wingeva1986** [MetaCubeX/mihomo#1992]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### System Version

openwrt kernel 6.12.23

### Mihomo Version

<html>
<body>

alpha-g4ecb49b

</body>
</html>

### Configuration File

```yaml
hosts:
  test.test: 104.xx.xx.1
dns:
  enable: true
  prefer-h3: true
  cache-algorithm: arc
  listen: :7874
  use-hosts: true
  default-nameserver:
  - 223.5.5.5
  nameserver:
  - https://test.test/dns-query#h3=true&ecs=182.239.127.137/24&ecs-override=true
  nameserver-policy:
    test.test: rcode://success
```

### Description

使用上述配置，实际仍使用default-nameserver的dns去解析doh的host（test.test），而不是直接返回hosts自定义的值。

### Reproduction Steps

。

### Logs

```shell

```
