### ISSUE TITLE
[Bug] 不存在的记录为什么被错误匹配

### ISSUE THREAD

**Issue by helllkz** [MetaCubeX/mihomo#1993]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Linux

### System Version

immortawrl 24.10.0

### Mihomo Version

alpha-468cfc3

### Configuration File

```yaml
######### 锚点 start #######
# 策略组相关
pr: &pr {type: select, proxies: [默认, 香港, 香港自动选择, 台湾, 台湾自动选择, 日本, 日本自动选择, 新加坡, 新加坡自动选择, 美国, 美国自动选择, 其它地区, 全部节点, 自动选择, 直连]}
#这里是订阅更新和延迟测试相关的
p: &p {type: http, interval: 3600, health-check: {enable: true, url: "https://www.gstatic.com/generate_204", interval: 300}}
######### 锚点 end #######

mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: debug
external-controller: '[::]:9090'
experimental:
  ignore-resolve-fail: true
hosts:
  smtp.gmail.com: 74.125.20.109
  
dns:
  enable: true
  listen: '[::]:1053'
  ipv6: false
  default-nameserver:
  - 61.139.2.69
  - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - +.lan
  - +.local
  - geosite:cn
  - geosite:category-games@cn
  - stun.*.*.*
  - stun.*.*
  - '*.msftconnecttest.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - xbox.*.*.microsoft.com
  - '*.*.xboxlive.com'
  - '*.*.xboxlive.cn'
  use-hosts: true
  nameserver:
  - 127.0.0.1:5335
find-process-mode: off
unified-delay: true
tcp-concurrent: true
external-ui: ui
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist-cdn-fonts.zip
secret: '536569'
port: 8080
socks-port: 1080
redir-port: 7891
tproxy-port: 7892
tun:
  enable: true
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false
  device: nikki
  stack: mixed
profile:
  store-selected: true
  store-fake-ip: true
geodata-mode: false
geodata-loader: standard
geox-url:
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  asn: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb
geo-auto-update: true
geo-update-interval: 24
proxy-providers:
  xxx:
    type: http
    url: xxx
    path: ./profiles/xxx.yaml
    interval: 3600
    proxy: DIRECT
    size-limit: 0
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 5000
    exclude-filter: xxx
    exclude-type: ss|http
proxy-groups:
- {name: 默认, type: select, proxies: [自动选择, 直连, 香港, 香港自动选择, 台湾, 台湾自动选择, 日本, 日本自动选择, 新加坡, 新加坡自动选择, 美国, 美国自动选择, 其它地区, 全部节点], icon: "https://www.clashverge.dev/assets/icons/adjust.svg"}
- {name: 直连, type: select, proxies: [DIRECT], icon: "https://www.clashverge.dev/assets/icons/link.svg"}
- {name: 广告过滤, type: select, proxies: [REJECT], icon: "https://www.clashverge.dev/assets/icons/bug.svg"} 
- {name: 拦截, type: select, proxies: [REJECT], icon: "https://www.clashverge.dev/assets/icons/block.svg"}
- {name: OpenAI, <<: *pr, icon: "https://www.clashverge.dev/assets/icons/chatgpt.svg"}
- {name: NETFLIX, <<: *pr, icon: "https://www.clashverge.dev/assets/icons/netflix.svg"}
- {name: YOUTUBE, <<: *pr, icon: "https://www.clashverge.dev/assets/icons/youtube.svg"}
- {name: 漏网之鱼, type: select, proxies: [直连, 默认], icon: "https://www.clashverge.dev/assets/icons/fish.svg"}  
- {name: 香港, type: select, include-all: true, filter: "(?i)(?!直连)(港|hk|hongkong|hong kong)", icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg"}
- {name: 台湾, type: select, include-all: true, filter: "(?i)(?!直连)(台|tw|taiwan)", icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tw.svg"}
- {name: 日本, type: select, include-all: true, filter: "(?i)(?!直连)(日|jp|japan)", icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg"}
- {name: 美国, type: select, include-all: true, filter: "(?i)(?!直连)(美|us|unitedstates|united states)", icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg"}
- {name: 新加坡, type: select, include-all: true, filter: "(?i)(?!直连)(新|sg|singapore)", icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg"}
- {name: 其它地区, type: select, include-all: true, filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates|直连)).*", icon: "hhttps://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/Domestic.svg"}
- {name: 自动选择, type: url-test, include-all: true, tolerance: 10, icon: "https://www.clashverge.dev/assets/icons/speed.svg"}
- {name: 全部节点, type: select, include-all: true, icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png"}
- {name: 香港自动选择,type: url-test, include-all: true, filter: "(?i)(?!直连)(港|hk|hongkong|hong kong)", icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg"}
- {name: 台湾自动选择,type: url-test, include-all: true, filter: "(?i)(?!直连)(台|tw|taiwan)", icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tw.svg"}
- {name: 日本自动选择,type: url-test, include-all: true, filter: "(?i)(?!直连)(日|jp|japan)", icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg"}
- {name: 美国自动选择,type: url-test, include-all: true, filter: "(?i)(?!直连)(美|us|unitedstates|united states)", icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg"}
- {name: 新加坡自动选择,type: url-test, include-all: true, filter: "(?i)(新|sg|singapore)", icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg"}

rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  steam:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    path: ./ruleset/steam.yaml
    url: "https://cdn.jsdelivr.net/gh/Femoon/clash-rules/steam.yaml"
  icloud:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
- RULE-SET,applications,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- RULE-SET,private,DIRECT
- GEOSITE,category-ads-all,广告过滤
- RULE-SET,reject,REJECT
- RULE-SET,icloud,直连
- RULE-SET,apple,直连
- RULE-SET,steam,直连
- GEOSITE,category-games@cn,DIRECT
- GEOSITE,openai,OpenAI
- GEOSITE,netflix,NETFLIX
- GEOSITE,youtube,YOUTUBE
- RULE-SET,tld-not-cn,默认
- RULE-SET,gfw,默认
- RULE-SET,proxy,默认
- RULE-SET,direct,DIRECT
- RULE-SET,lancidr,DIRECT
- RULE-SET,cncidr,DIRECT
- GEOIP,LAN,DIRECT,no-resolve
- GEOIP,CN,DIRECT
- MATCH,漏网之鱼
```

### Description

苹果推送的服务器
13-courier.push.apple.com
37-courier.push.apple.com
Proxy中不存在的规则，但是被错误匹配到了代理出口，兜底是直连的，不知道为什么能在规则里面匹配到这个域名，我看了规则里面是没有这个域名的
{
"id": 
"ea370a91-f518-4b7b-bede",
"metadata": 
{
"network": 
"tcp",
"type": 
"Redir",
"sourceIP": 
"192.168.2.16",
"destinationIP": 
"",
"sourceGeoIP": 
null,
"destinationGeoIP": 
null,
"sourceIPASN": 
"",
"destinationIPASN": 
"",
"sourcePort": 
"54521",
"destinationPort": 
"5223",
"inboundIP": 
"192.168.2.1",
"inboundPort": 
"7891",
"inboundName": 
"DEFAULT-REDIR",
"inboundUser": 
"",
"host": 
"13-courier.push.apple.com",
"dnsMode": 
"fake-ip",
"uid": 
0,
"process": 
"",
"processPath": 
"",
"specialProxy": 
"",
"specialRules": 
"",
"remoteDestination": 
"183.240.210.6",
"dscp": 
0,
"sniffHost": 
""
},
"upload": 
18136,
"download": 
8083,
"start": 
"2025-04-24T14:40:22.86936941Z",
"chains": 
[
"HK丨香港1",
"香港",
"默认"
],
"rule": 
"RuleSet",
"rulePayload": 
"proxy",
"downloadSpeed": 
0,
"uploadSpeed": 
0
}

### Reproduction Steps

无

### Logs

```shell

```
