### ISSUE TITLE
在阿里云ECS安装mihomo不成功

### ISSUE THREAD

**Issue by CrazyJasonwell** [MetaCubeX/mihomo#1995]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [ ] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [ ] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

ali cloud linux 3

### Mihomo 版本

在自己的服务器上安装mihomo基本上都ok，在阿里云ECS上安装不成功，在metacubex设置TUN时报：
Request failed with status code 405 Method Not Allowed: PATCH http://xxx.xx.xx.xx:9097/configs 错误，9097端口放开了，是不是ECS为虚化网卡就不能使用还是阿里做了一些限制？大佬帮忙看看。

### 配置文件

```yaml
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false

skip-auth-prefixes: # 设置跳过验证的 IP 段
  - 127.0.0.1/8
  - ::1/128
 
find-process-mode: strict
unified-delay: true


external-controller: 0.0.0.0:9090
external-controller-cors:
  allow-private-network: true
  allow-origins:
  - '*'


### Tunnel配置

  tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
```

### 描述

这个配置在群晖等服务器上正常。
在阿里ECS上没有看到连接数、规则、代理等等都为空。

### 重现方式

在阿里ECS上没有看到连接数、规则、代理等等都为空。

### 日志

```shell

```
