### ISSUE TITLE
[Bug] 发现周期性不明流量

### ISSUE THREAD

**Issue by hawie** [MetaCubeX/mihomo#2000]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

docker

### Mihomo 版本

latest v1.19.5, and Alpha 

### 配置文件

```yaml
#---------------------------------------------------#
## Clash Premium 配置文件
## 
## 当前配置:
## - Hysteria2 代理
## - TUN 模式支持
## - 优化 DNS 解析
## - 自动分流规则
##
## 使用方法: 将此文件放置在 $HOME/.config/clash/config.yaml
#---------------------------------------------------#

# 日志设置：silent=不显示日志，info=显示基本信息，warning=显示警告
# error=只显示错误，debug=显示所有调试信息（日志会占用内存，一般保持静默即可）
log-level: silent

# 通用代理端口：同时支持HTTP和SOCKS5协议，一般软件都可以使用这个端口
mixed-port: 7890

# 仅HTTP协议专用端口（如果你的软件只支持HTTP代理，用这个）
port: 7891

# 仅SOCKS5协议专用端口（如果你的软件只支持SOCKS5代理，用这个）
socks-port: 7892

# 这里填写clash的IP地址更可靠，而不是直接指向接口名称，接口名称可能会变化，
# 如有时候是 eth0@Meta， 有时候是 eth0
interface-name: ppp0

# 监听地址，"*"表示监听所有地址，这样局域网内其他设备才能连接
bind-address: "*"
ipv6: true

mode: rule

# 是否允许来自局域网的连接（开启后，其他设备可以通过你的电脑上网）
allow-lan: true


# 控制面板访问地址和端口，可以通过浏览器访问查看连接状态
external-controller: 0.0.0.0:9090

# MetaCubeX界面，比上面那个更漂亮（目前启用的是这个）
external-ui: ui


# DNS设置（处理域名解析的方式，很重要！）
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true # 关闭IPv6，大多数情况下不需要

  # 国内DNS服务器，用于解析常规域名
  default-nameserver:
    - 223.5.5.5  # 阿里DNS
    - 114.114.114.114  # 114DNS
  enhanced-mode: fake-ip # 加速DNS解析的模式
  fake-ip-range: 198.18.0.1/16 # 虚拟IP地址池

  # 下面这些域名将使用真实IP而非虚拟IP，这样可以避免一些服务无法正常工作
  # 比如网易云音乐、游戏服务器等需要真实IP的服务
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'msftconnecttest.com'
    - 'msftncsi.com'
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - 'xnotify.xboxlive.com'
    - '+.battlenet.com.cn'
    - '+.wotgame.cn'
    - '+.wggames.cn'
    - '+.wowsgame.cn'
    - '+.wargaming.net'
    - 'proxy.golang.org'
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - 'heartbeat.belkin.com'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - 'mesu.apple.com'
    - 'swscan.apple.com'
    - 'swquery.apple.com'
    - 'swdownload.apple.com'
    - 'swcdn.apple.com'
    - 'swdist.apple.com'
    - 'lens.l.google.com'
    - 'stun.l.google.com'
    - '+.nflxvideo.net'
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.mcdn.bilivideo.cn'
    - '+.zerotier.com'
    - 'checkip.synology.com'
    - 'checkipv6.synology.com'
    - 'checkip.digitalocean.synology.com'
    - 'checkipv6.digitalocean.synology.com'
#    - 'geosite:cn'

  # 国内DNS服务器（加密连接，更安全）
  nameserver:
  #  - https://doh.pub/dns-query      # 腾讯DNS
  #  - https://dns.alidns.com/dns-query  # 阿里DNS
    - 202.96.134.133
    - 223.5.5.5

  # 国外DNS服务器，用于解析被污染的域名
  fallback:
     - https://dns.google/dns-query     # 谷歌DNS
     - https://cloudflare-dns.com/dns-query  # Cloudflare DNS

  # 哪些情况下会使用国外DNS
  fallback-filter:
    geoip: false
    ipcidr:
      # 以下是内网IP段，不会使用国外DNS
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      # 这些网站强制使用国外DNS解析，避免被污染
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.githubusercontent.com'
      - '+.googlevideo.com'

# TUN模式设置（让系统所有流量都经过Clash，无需单独为每个软件设置代理）
tun:
  enable: true # 开启后所有流量都会通过Clash，无需在软件里单独设置代理
  stack: system # 使用系统网络栈
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - tcp://any:53  # 接管所有DNS请求，防止DNS泄露
    - udp://any:53  # 接管所有DNS请求，防止DNS泄露

# 代理服务器设置, 机场用户要用机场的Clash配置平替这这部分
proxies:  
  - name: "usa2vmess"
    type: vmess

  # Hysteria2代理（高性能抗干扰协议）
  - name: "kr0"
    type: hysteria2

  - name: "usa2"
    type: hysteria2

  - name: "jpn2"
    type: hysteria2

  - name: "kr2"
    type: hysteria2


# 代理分组（让你可以选择走直连还是代理）
proxy-groups:
  # 手动选择代理组
  - name: Proxy
    type: select
    proxies:
      - autourl
      - kr0
      - usa2
      - jpn2
      - kr2
      - usa2vmess
      - DIRECT # 直连选项

  - name: Media
    type: select
    proxies:
      - autohysteria      
      - kr0
      - usa2
      - jpn2
      - kr2
      - usa2vmess

  # 自动测速选择最快的代理
  - name: "autourl"
    type: url-test
    proxies:
      - kr0
      - usa2
      - jpn2
      - kr2
      - usa2vmess
    url: 'http://www.gstatic.com/generate_204'
    interval: 300 # 每300秒测速一次

  # 自动测速选择最快的代理
  - name: "autohysteria"
    type: url-test
    proxies:
      - kr0
      - usa2
      - jpn2
      - kr2
    url: 'http://www.gstatic.com/generate_204'
    interval: 300 # 每300秒测速一次

# 规则集（决定哪些网站走代理，哪些直连）
rule-providers:
  apple-proxy:
    type: http
    behavior: classical
    url: "https://dl.dl/learn/Apple-proxy.yaml"
    path: ./ruleset/Apple-proxy.yaml
    interval: 86400 # 每小时更新一次规则

  apple-direct:
    type: http
    behavior: classical
    url: "https://dl.dl/learn/Apple-direct.yaml"
    path: ./ruleset/Apple-direct.yaml
    interval: 86400

  cn:
    type: http
    behavior: classical
    url: "https://dl.dl/learn/CN.yaml"
    path: ./ruleset/CN.yaml
    interval: 86400

  ad-keyword:
    type: http
    behavior: classical
    url: "https://dl.dl/learn/common-ad-keyword.yaml"
    path: ./ruleset/common-ad-keyword.yaml
    interval: 86400

  foreign:
    type: http
    behavior: classical
    url: "https://dl.dl/learn/foreign.yaml"
    path: ./ruleset/foreign.yaml
    interval: 86400

  telegram:
    type: http
    behavior: classical
    url: "https://dl.dl/learn/Telegram.yaml"
    path: ./ruleset/Telegram.yaml
    interval: 86400

  youtube:
    type: http
    behavior: classical
    url: "https://dl.dl/learn/YouTube.yaml"
    path: ./ruleset/YouTube.yaml
    interval: 86400

  disney:
    type: http
    behavior: classical
    url: "https://dl.dl/learn/DisneyPlus.yaml"
    path: ./ruleset/DisneyPlus.yaml
    interval: 86400

  netflix:
    type: http
    behavior: classical
    url: "https://dl.dl/learn/Netflix.yaml"
    path: ./ruleset/Netflix.yaml
    interval: 86400

  chatgpt:
    type: http
    behavior: classical
    url: "https://dl.dl/learn/ChatGPT.yaml"
    path: ./ruleset/ChatGPT.yaml
    interval: 86400

  custom:
    type: http
    behavior: classical
    url: "https://dl.dl/learn/custom.yaml"
    path: ./ruleset/custom.yaml
    interval: 3600

  lan:
    type: http
    behavior: classical
    url: "https://dl.dl/learn/LAN.yaml"
    path: ./ruleset/LAN.yaml
    interval: 86400

# 最终规则（按顺序匹配，匹配到就停止）
rules:
#  - RULE-SET,apple-proxy,Proxy # 苹果服务走代理
#  - RULE-SET,apple-direct,DIRECT # 苹果国内服务走直连
#  - RULE-SET,cn,DIRECT # 中国网站走直连
#  - RULE-SET,ad-keyword,REJECT # 广告关键词拦截
  - RULE-SET,youtube,Media
  - RULE-SET,netflix,Media
  - RULE-SET,disney,Media
  - RULE-SET,chatgpt,Proxy # x走代理
  - RULE-SET,foreign,Proxy # 国外网站走代理
  - RULE-SET,custom,Proxy # x走代理
  - RULE-SET,telegram,Proxy # Telegram走代理
#  - RULE-SET,lan,DIRECT # 局域网直连
#  - GEOIP,CN,DIRECT # 中国IP直连
  - MATCH,DIRECT # 其他所有请求直连,改为不走代理

# UI界面使用指南:
# 1. 启动Clash后，在浏览器中访问 http://localhost:9090/ui 或 http://[你的IP]:9090/ui
```

### 描述

最简配置，只是将已知几个知名的走proxy，其他直连。外部就将198.18.0.0/16的路由指向这个docker，dns指向这个docker。
理想目标是，除了已知几个知名的走proxy，其他dns返回realip，不经过docker。但docker性能在启用geosite:cn之后，太慢，所以直连的大部份也保留了fakeip。

问题是，有不明流量（源地址非内网段192.168.9.x）经过这个docker如图。换alpha也是一样。这是正常流量？还是mihomo本身置入的。

<img width="1487" alt="Image" src="https://github.com/user-attachments/assets/4180d16d-15f4-4ec8-874b-75356eb75e08" />

### 重现方式

访问任意proxy站点比如google，稍闲置一会儿（三两分钟），就会出现这个流量，然后大约隔几秒钟一分钟不等，就会又出现，一直这样。这时将将访问的这台电脑关机，这个流量也是一直在，除非将docker关机才消失。

### 日志

```shell

```
