### ISSUE TITLE
[Bug] v1.19.5版本Trojan-ws 功能存在证书问题` failed to dial WebSocket: tls: failed to verify certificate`，降级至v1.19.4无此问题

### ISSUE THREAD

**Issue by SuperNG6** [MetaCubeX/mihomo#2002]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

Linux5.1

### Mihomo 版本

v1.19.5

### 配置文件

```yaml
- name: 11
    server: xx.xxx.com
    port: 443
    type: trojan
    password: xxxxx
    network: ws
    skip-cert-verify: false
    udp: true
    ws-opts:
      path: /xxxx?ed=2048
```

### 描述

 v1.19.5版本Trojan-ws 功能存在证书问题` failed to dial WebSocket: tls: failed to verify certificate](ls: failed to verify certificate: x509: certificate is valid for xxx.com, *.xxx.com,, not xx.xxx.com:443`，降级至v1.19.4无问题.

acme生成的通配符证书+Nginx反代ws，在v1.19.4及更早之前都无问题

 v1.19.5 debug日志
```
25-04-29 15:21:43[ warn ][TCP] dial 国外网站 (match RuleSet/proxy) 127.0.0.1:39854 --> registry-1.docker.io:443 error: failed to dial WebSocket: tls: failed to verify certificate: x509: certificate is valid for xxx.com, *.xxx.com,, not xx.xxx.com:443
```
降级 v1.19.4 后无错误日志，正常运行

环境，docker 裸内核运行 

### 重现方式

升级至 v1.19.5，trojan+ws+nginx+通配符证书
```
  - name: 11
    server: xx.xxx.com
    port: 443
    type: trojan
    password: xxxxx
    network: ws
    skip-cert-verify: false
    udp: true
    ws-opts:
      path: /xxxx?ed=2048
```
```
    location /xxxx {
	if ($http_upgrade != "websocket") {
		return 404;
	}
        proxy_pass http://xxxx:xxx;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 52w;
    }
```

### 日志

```shell
25-04-29 15:21:43[ warn ][TCP] dial 国外网站 (match RuleSet/proxy) 127.0.0.1:39854 --> registry-1.docker.io:443 error: failed to dial WebSocket: tls: failed to verify certificate: x509: certificate is valid for xxx.com, *.xxx.com,, not xx.xxx.com:443
```
