### ISSUE TITLE
[Bug] shadowTLS 客户端不支持多SNI

### ISSUE THREAD

**Issue by dolaxi** [MetaCubeX/mihomo#2012]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

11

### Mihomo 版本

1.19.5

### 配置文件

```yaml
- name: xx
  type: ss
  server: xxxxxxxx
  port: 443
  udp: true
  cipher: 2022-blake3-chacha20-poly1305
  password: "xxxx"
  plugin: shadow-tls
  client-fingerprint: chrome
  plugin-opts:
    host: a.org;b.com;c.org
    password: "xxxxxx"
    version: 3
```

### 描述

host 这里不支持 多个 host: a.org;b.com;c.org

原作者那边是支持客户端多个的：

https://github.com/ihciah/shadow-tls/blob/master/docker-compose.yml

# If client is configured with multiple SNIs, client will pick one in random.

### 重现方式

配置多SNI
host: a.org;b.com;c.org

或者
host: "a.org;b.com;c.org"

### 日志

```shell

```
