### ISSUE TITLE
[Bug] win端无法启用TCP Brutal

### ISSUE THREAD

**Issue by wort2m** [MetaCubeX/mihomo#2016]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

Windows 11 企业版 24H2

### Mihomo 版本

alpha-8771521 Mihomo

### 配置文件

```yaml
proxies:
- name: "x"
  type: ss
  server: x.x.x.x
  port: x
  cipher: 2022-blake3-aes-128-gcm
  password: "x"
  udp: true
  ip-version: ipv4
  smux:
    enabled: true
    protocol: smux
    max-connections: 4
    min-streams: 4
    max-streams: 0
    statistic: false
    only-tcp: false
    padding: true
    brutal-opts:
      enabled: true
      up: 300
      down: 300
```

### 描述

win端无法启用 TCP Brutal 拥塞控制算法，和文档中描述不符

### 重现方式

略

### 日志

```shell
failed to enable TCP Brutal at client: TCP Brutal is only supported on Linux
```
