### ISSUE TITLE
[Bug] Android上频繁出现断流

### ISSUE THREAD

**Issue by thomas-rhong** [MetaCubeX/mihomo#2025]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### System Version

HyperOS 2 + Android 14

### Mihomo Version

Clash Meta for Android
2.11.9.Meta
Alpha-39d6a0d-250421

### Configuration File

```yaml
proxy-providers:
  CTC:
    url: ""
    type: http
    interval: 86400
    health-check: {enable: true, url: "https://www.gstatic.com/generate_204", interval: 300}
dns:
  enable: true
  listen: ":53"
  prefer-h3: true
  enhanced-mode: fake-ip
  fake-ip-filter: ["*", "+.lan", "+.local", "+.market.xiaomi.com", "*talk.google.com"]
  default-nameserver: [system]
  nameserver: [system]
  proxy-server-nameserver: [1.2.4.8]
sniffer:
  enable: true
  sniff: {HTTP: {ports: [80, 8080-8880], override-destination: true}, TLS: {ports: [443, 8443]}, QUIC: {ports: [443, 8443]}}
  skip-domain: ["Mijia Cloud", "+.push.apple.com"]
proxy-groups:
  - {name: PROXY, type: select, use: [CTC], proxies: [FALLBACK]}
  - {name: FALLBACK, type: fallback, use: [CTC], interval:300, lazy: true, hidden: true}
  - {name: MATCH, type: select, proxies: [DIRECT, PROXY]}

rules:
  - MATCH,DIRECT
```

### Description

某些直连场景，特别是知乎Android端，内容无法加载，日志里体现为dial tcp ip地址 error: i/o timeout。此ip多为ipv6，但应该不是运营商的问题，因为关闭cmfa或者使用Hiddify都是正常的。

Sometimes using DIRECT causes dial tcp ip error: i/o timeout. close vpn, or use hiddify etc., it works well, so the problem shouldn't come from original network.

### Reproduction Steps

正常使用，并打开知乎Android客户端等应用。

use normally, and open apps like Zhihu for Android.

### Logs

```shell
https://drive.google.com/file/d/1-4ZL4uiENL8m_Q8NqUXP7GRtNC8I71H3/view?usp=drivesdk

too long to paste directly
```
