### ISSUE TITLE
[Bug] CFW和Clash Verge在更新内核到1.19.6之后，均出现无法顺利切换订阅的情况

### ISSUE THREAD

**Issue by Maozai-Teng** [MetaCubeX/mihomo#2030]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [ ] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [ ] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [ ] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

Windows 10 企业版 22H2 19045.5796

### Mihomo 版本

mihomo-windows-amd64-v1.19.6

### 配置文件

```yaml
mixed-port: 7890
allow-lan: false
bind-address: "*"
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
unified-delay: true
tcp-concurrent: true
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 223.6.6.6
    - 114.114.115.115
    - 1.1.1.1
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true

#以下省略机场分流规则和节点信息。
```

### 描述

将mihomo核心更新到1.19.6之后，会出现无法顺利切换订阅和莫名其妙卡顿的情况。
把核心还原成到1.19.6之前版本（比如1.19.5）则一切恢复正常。

我分别试验了CFW和Clash Verge。
CFW的情况是切换很慢，之前点一下就切过去了，现在起码要一分钟，并且会感觉软件卡顿。
Clash Verge的情况则更加严重，根本无法切换，下面的重现方式就用Clash Verge举例。

两个Windows下的软件都出现了问题，并且之前都是正常的，所以感觉应该是内核更新出了bug？
个人感觉是和1.19.6修改了配置文件的路径有关？
我也有根据要求设置了新的环境变量也没什么变化和改善。

![Image](https://github.com/user-attachments/assets/839f9b4d-0fd4-4941-bce0-5415a882d4d0)

![Image](https://github.com/user-attachments/assets/9d79d846-9a4d-4a97-ad0b-13236b990ef0)

### 重现方式

全部都是正常操作，无需特别说明。
唯一要求是需要两个不同的订阅（机场）导入，然后对订阅进行切换。

下图是订阅1的情况
![Image](https://github.com/user-attachments/assets/ea23ca04-468a-498b-97cd-2f1dcd2e4cfe)

下图是点击订阅2，切换到订阅2的情况，可以看到订阅1左边的蓝条消失，订阅2左边出现蓝条，即表明用户切换订阅这一行为已经完成。
但转到代理页面，可以看到代理组里面还是之前的代理（剩余流量还是上一个订阅的），即表明实际上的订阅切换并未成功。
![Image](https://github.com/user-attachments/assets/28714874-ab7f-4961-b47d-fca0e0977942)

这时候唯一的解决方法是：重启应用，可以看到这样子操作之后，才能正常切换成新的订阅。但再想切别的订阅又不行了，又需要切换过去了再重启一下。
![Image](https://github.com/user-attachments/assets/233e33f5-b401-478c-8854-fa3536e30bcd)

### 日志

```shell

```
