### ISSUE TITLE
[Bug] 从1.19.6更新到Alpha版本后所有直连无法连接

### ISSUE THREAD

**Issue by CHANTXU64** [MetaCubeX/mihomo#2033]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

`Linux chant-arch 6.14.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 03 May 2025 13:34:12 +0000 x86_64 GNU/Linux`

### Mihomo 版本

`Mihomo Meta alpha.20250512.3270.6e35cf93 linux amd64 with go1.24.3 Mon May 12 06:53:33 AM UTC 2025`

### 配置文件

```yaml
proxy-providers: ****

mode: rule # clash工作模式（rule/global/direct,meta暂不支持script）

mixed-port: 7890    # 本地混合代理(http和socks5合并）端口
redir-port: 7892

ipv6: true # ip6开关，当为false时，停止解析hostanmes为ip6地址

allow-lan: true

log-level: warning # 日志等级（info/warning/error/debug/silent）

interface-name: ppp0       # 出口网卡名称
# routing-mark: 9527         # 流量标记(仅Linux)

tcp-concurrent: true #【Meta专属】TCP连接并发，如果域名解析结果对应多个IP，
                     # 并发所有IP，选择握手最快的IP进行连接
unified-delay: true # 开启统一延迟时，会计算 RTT，以消除连接握手等带来的不同类型节点的延迟差异

external-controller: 0.0.0.0:9091
external-ui: /usr/share/metacubexd

geodata-mode: true #【Meta专属】使用geoip.dat数据库(默认：false使用mmdb数据库)
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

find-process-mode: off

global-client-fingerprint: random

profile:
  store-selected: false
  store-fake-ip: false

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: false
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: false
  stack: gvisor # mixed # gvisor
  mtu: 1500 # 最大传输单元
  device: tun_clash

hosts:
  # '*.clash.dev': 127.0.0.1

proxy-groups:
  - name: 默认
    type: select
    proxies: [香港,台湾,日本,新加坡,美国,全部节点,DIRECT]
  - name: Google
    type: select
    proxies: [香港,台湾,日本,新加坡,美国,全部节点,默认,DIRECT]
  - name: Telegram
    type: select
    proxies: [香港,默认,台湾,日本,新加坡,美国,全部节点,DIRECT]
  - name: Twitter
    type: select
    proxies: [香港,默认,台湾,日本,新加坡,美国,全部节点,DIRECT]
  - name: 哔哩哔哩
    type: select
    proxies: [DIRECT,默认,香港,台湾,日本,新加坡,美国,全部节点]
  - name: 巴哈姆特
    type: select
    proxies: [台湾,默认,香港,日本,新加坡,美国,全部节点,DIRECT]
  - name: YouTube
    type: select
    proxies: [香港,默认,台湾,日本,新加坡,美国,全部节点,DIRECT]
  - name: NETFLIX
    type: select
    proxies: [香港,默认,台湾,日本,新加坡,美国,全部节点,DIRECT]
  - name: Spotify
    type: select
    proxies:  [香港,默认,台湾,日本,新加坡,美国,全部节点,DIRECT]
  - name: Tiktok
    type: select
    proxies:  [日本,默认,香港,台湾,新加坡,美国,全部节点,DIRECT]
  - name: Github
    type: select
    proxies:  [香港,默认,台湾,日本,新加坡,美国,全部节点,DIRECT]
  - name: 国内
    type: select
    proxies:  [DIRECT,默认,香港,台湾,日本,新加坡,美国,全部节点]
  - name: 其他
    type: select
    proxies:  [默认,DIRECT,香港,台湾,日本,新加坡,美国,全部节点]
  # 分隔,下面是地区分组
  - name: 香港
    type: url-test
    include-all: true
    filter: "香港.*\\|.*V2"
    tolerance: 10
  - name: 台湾
    type: url-test
    include-all: true
    filter: "台湾.*\\|.*V2"
    tolerance: 10
  - name: 日本
    type: url-test
    include-all: true
    filter: "日本.*\\|.*V2"
    tolerance: 10
  - name: 美国
    type: url-test
    include-all: true
    filter: "美国"
    tolerance: 10
  - name: 新加坡
    type: url-test
    include-all: true
    filter: "新加坡.*\\|.*V2"
    tolerance: 10
  - name: 全部节点
    type: select
    include-all: true

rules:
  - GEOIP,private,DIRECT,no-resolve
  - DOMAIN-SUFFIX,iprofiles.apple.com,REJECT
  - DOMAIN-SUFFIX,mdmenrollment.apple.com,REJECT
  - DOMAIN-SUFFIX,deviceenrollment.apple.com,REJECT
  - DOMAIN-SUFFIX,gdmf.apple.com,REJECT
  - DOMAIN-SUFFIX,albert.apple.com,REJECT
  - GEOSITE,CN,国内
  - GEOSITE,google-gemini,日本
  - GEOSITE,github,Github
  - GEOSITE,twitter,Twitter
  - GEOSITE,youtube,YouTube
  - GEOSITE,google,Google
  - GEOSITE,telegram,Telegram
  - GEOSITE,netflix,NETFLIX
  - GEOSITE,bilibili,哔哩哔哩
  - GEOSITE,bahamut,巴哈姆特
  - GEOSITE,spotify,Spotify
  - GEOSITE,tiktok,Tiktok
  - GEOSITE,dmm,日本
  - GEOSITE,gfw,默认
  - GEOSITE,category-dev,默认
  - GEOSITE,private,DIRECT
  - DOMAIN-SUFFIX,cloudflare-dns.com,默认
  - DOMAIN-SUFFIX,api.nn.ci,默认
  - DOMAIN-SUFFIX,api.ipify.org,默认
  - DOMAIN-SUFFIX,gsas.apple.com,默认
  - DOMAIN-SUFFIX,hotmail.com,默认
  # - GEOSITE,geolocation-!cn,其他
  # - GEOSITE,category-ads-all,REJECT
  - DOMAIN-REGEX,^gsp.*-ssl\.ls\.apple\.com$,国内 # apple map

  - IP-CIDR,1.0.0.1/32,默认,no-resolve
  - IP-CIDR,1.1.1.1/32,默认,no-resolve
  - IP-CIDR,8.8.8.8/32,默认,no-resolve
  - IP-CIDR,8.8.4.4/32,默认,no-resolve
  - GEOIP,google,Google
  - GEOIP,netflix,NETFLIX
  - GEOIP,telegram,Telegram
  - GEOIP,twitter,Twitter
  - GEOIP,CN,国内
  - MATCH,其他
```

### 描述

从1.19.6更新到 Alpha 版本后所有直连无法连接

在我的配置中，是`GEOSITE,CN,国内`这条规则中的网站（包括百度、B站）无法连接，在网页 UI 中把“国内”这个策略从”Direct“改为”默认“就能连接了

再退回1.19.6就正常了

### 重现方式

见描述

### 日志

```shell
73	[warning]	[TCP] dial 国内 (match GeoSite/CN) 192.168.1.187:38102 --> 163.177.4.23:80 error: connect failed: dial tcp 163.177.4.23:80: i/o timeout
72	[debug]	[DNS] cache hit baidu.com --> [] AAAA, expire at 2025-05-12 16:25:33
71	[debug]	[DNS] cache hit baidu.com --> [39.156.66.10 110.242.68.66] A, expire at 2025-05-12 15:43:22
70	[debug]	[Rule] use default rules
69	[debug]	[Sniffer] Sniff tcp [10.10.42.45:58642]-->[39.156.66.10:443] success, replace domain []-->[baidu.com]
```
