### ISSUE TITLE
[Bug] vmess节点无法正常连接timeout

### ISSUE THREAD

**Issue by Tison6** [MetaCubeX/mihomo#2034]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

win10 22h2

### Mihomo 版本

v1.19.8和alpha-8771521

### 配置文件

```yaml
dns:
  enable: true
  use-hosts: true
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - https://223.6.6.6/dns-query
  fallback:
    - tls://8.8.8.8:853
    - tls://1.1.1.1:853
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
  use-system-hosts: false
```

### 描述

无法正常连接xray core建立的vmess节点，测速也timeout，可能需要兼容xray core的高版本。希望可以。
如：使用如下脚本（https://github.com/233boy/Xray ）在服务器上建立vmess+tls+ws
使用是clash verge，而v2ray/xray-core的v2rayXS (macOS）和v2rayN (win）可以正常连接。

### 重现方式

在服务器上建立，使用如下脚本：https://github.com/233boy/Xray
建立vmess+tls+ws节点，或其它协议的vmess节点。

### 日志

```shell

```
