### ISSUE TITLE
[Bug] 更新了 `SAFE_PATHS` 后导致面板无法访问启用了 TLS 的 API

### ISSUE THREAD

**Issue by muink** [MetaCubeX/mihomo#2035]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

openwrt 24.10.1

### Mihomo 版本

```
Mihomo Meta alpha-266fb03 linux amd64 with go1.23.9 2025-05-13T09:40:46+00:00
Use tags: with_gvisor
```

### 配置文件

```yaml
global-ua: clash.meta
mode: rule
find-process-mode: "off"
log-level: warning
etag-support: true
ipv6: true
unified-delay: true
tcp-concurrent: true
keep-alive-interval: 30
keep-alive-idle: 600
routing-mark: 200
authentication:
  - fchomodef:33fa1876-19b0-4531-8fbc-4c935ae4d945
skip-auth-prefixes:
  - 127.0.0.1/8
  - ::1/128
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: false
global-client-fingerprint: chrome
tls:
  certificate: /etc/ssl/acme/my.openwrt.fullchain.crt # 域名证书
  private-key: /etc/ssl/acme/my.openwrt.key # 域名证书
external-controller-cors:
  allow-origins:
    - '*'
  allow-private-network: true
external-controller: '[::]:9090'
external-controller-tls: '[::]:9043'
secret: aabbff66
external-ui: /var/run/fchomo/ui
external-ui-url: https://codeload.github.com/metacubex/metacubexd/zip/refs/heads/gh-pages # 面板
profile:
  store-selected: true
  store-fake-ip: false
experimental: {}
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
        - 80
        - 8080-8880
      override-destination: true
    TLS:
      ports:
        - 443
        - 8443
      override-destination: true
    QUIC:
      ports:
        - 443
        - 8443
      override-destination: true
  skip-domain:
    - "Mijia Cloud"
  force-domain: []
listeners:
  - name: mixed-in
    type: mixed
    port: 7890
    listen: '::'
    udp: true
  - name: redir-in
    type: redir
    port: 7891
    listen: '::'
  - name: tproxy-in
    type: tproxy
    port: 7892
    listen: '::'
    udp: true
  - name: dns-in
    type: tunnel
    port: 7893
    listen: '::'
    network:
      - tcp
      - udp
    target: 1.1.1.1:53
dns:
  enable: true
  prefer-h3: false
  listen: '[::]:7853'
  ipv6: true
  enhanced-mode: redir-host
  use-hosts: true
  use-system-hosts: true
  respect-rules: true
  default-nameserver:
    - 223.5.5.5#DIRECT
  proxy-server-nameserver:
    - 223.5.5.5#DIRECT
  nameserver:
    - 223.5.5.5#DIRECT
  fallback: []
  nameserver-policy: {}
  fallback-filter:
    geoip: false
    domain: []
hosts:
  dns.alidns.com: [223.6.6.6, '2400:3200:baba::1', 223.5.5.5, '2400:3200::1']
  dns.google: [8.8.8.8, '2001:4860:4860::8888', 8.8.4.4, '2001:4860:4860::8844']
proxies:
  - name: dns-out
    type: dns
proxy-groups:
  - name: group_block
    type: select
    proxies:
      - DIRECT
      - REJECT
    disable-udp: false
proxy-providers: {}
rule-providers: {}
rules:
  - IN-NAME,dns-in,dns-out
  - DST-PORT,53,dns-out
  - DOMAIN,hm.baidu.com,group_block
  - MATCH,DIRECT
sub-rules: {}
```

### 描述

在 mihomo 更新了 `SAFE_PATHS` 后, 1.19.6 开始的版本, 面板无法访问启用了 TLS 的 API, 目前通过 `SKIP_SAFE_PATH_CHECK=true` 缓解问题

### 重现方式

1. 准备好以下几个文件
```
/etc/fchomo/asn.mmdb
/etc/fchomo/geoip.dat
/etc/fchomo/geosite.dat
/var/run/fchomo/mihomo-c.yaml # 配置文件
/var/run/fchomo/ui/ # 解压好面板
```

2. 执行
``` shell
export SAFE_PATHS="/var/run/fchomo"
mihomo -d /etc/fchomo -f /var/run/fchomo/mihomo-c.yaml
```

3. mihomo 能启动, http://my.openwrt:9090/ui/#/setup?hostname=my.openwrt&port=9090&secret=aabbff66 也能访问
   但是换成了 https://my.openwrt:9043/ui/#/setup?hostname=my.openwrt&port=9043&secret=aabbff66 就无法 fetch 数据

### 日志

```shell

```
