### ISSUE TITLE
[Bug]  无法读取caddy证书

### ISSUE THREAD

**Issue by lgufan** [MetaCubeX/mihomo#2045]
### Verify steps

- [ ] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [ ] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [ ] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Linux

### System Version

cat /etc/os-release

### Mihomo Version

Mihomo Meta v1.19.8 linux amd64 with go1.24.3 Tue May 13 04:23:15 UTC 2025
Use tags: with_gvisor

### Configuration File

```yaml
listeners:
- name: anytls-in-1
  type: anytls
  port: 8443
  listen: 0.0.0.0
  users:
    username1: password1
  certificate: /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/xxx.com/xxx.com.crt
  private-key: /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/xxx.com/xxx.com.key
  padding-scheme: |
   stop=8
   0=30-30
   1=100-400
   2=400-500,c,500-1000,c,500-1000,c,500-1000,c,500-1000
   3=9-9,500-1000
   4=500-1000
   5=500-1000
   6=500-1000
   7=500-1000
```

### Description

启动后报错，个人猜测不会是因为路径包含了隐藏文件夹吗

### Reproduction Steps

读取caddy生成证书

### Logs

```shell
level=error msg="Listener anytls-in-1 listen err: parse certificate failed, maybe format error:tls: failed to find any PEM data in certificate input, or path error: path is not subpath of home directory or SAFE_PATHS: /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/xxx.com/xxx.com.crt \n allowed paths: [/etc/mihomo]"
```
