### ISSUE TITLE
[Bug] 无法开启api的tls，配置safe_paths和SKIP_SAFE_PATH_CHECK=1无效

### ISSUE THREAD

**Issue by c15412** [MetaCubeX/mihomo#2046]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

win11

### Mihomo 版本

Mihomo Meta v1.19.8 windows amd64 with go1.24.3 Tue May 13 04:24:19 UTC 2025
Use tags: with_gvisor

### 配置文件

```yaml
# Generated by Clash Verge

mixed-port: 4446
log-level: error
allow-lan: true
mode: rule
external-controller: 0.0.0.0:9090
external-ui: yacd
secret: ''
external-controller-tls: 0.0.0.0:9443
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
tls:
  certificate: D:\15412\SSL\certificate.crt
  private-key: D:\15412\SSL\private.key
unified-delay: false
interface-name: 以太网
ipv6: true
profile:
  store-selected: true
global-client-fingerprint: edge
tcp-concurrent: false
tcp:
  nodelay: false
  fast_open: false
  port_reuse: false
  concurrent: false
tun:
  stack: gvisor
  device: Meta
  auto-route: true
  auto-detect-interface: false
  dns-hijack:
  - any:53
  strict-route: false
  mtu: 1472
dns:
  enable: false
socks-port: 7898
port: 7899
```

### 描述

配置api的tls监听、设置了tls证书后，启动mihomo仍无法使用https API
经查询是更新1.19.8后添加safe_paths识别，
给`safe_paths`变量添加: `D:\15412\SSL\private.key` `D:\15412\SSL\certificate.crt`
仍无法使用

再查询发现有 
> 如果想存储到任意位置配置环境变量 SKIP_SAFE_PATH_CHECK=1

于是给系统环境变量添加`SKIP_SAFE_PATH_CHECK`，值为1
重启mihomo，仍无法访问https API

### 重现方式

见描述

### 日志

```shell
Spawning process: D:\Program Files\Clash.Verge\verge-mihomo.exe -d D:\15412\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev -f D:\15412\AppData\Roaming\io.github.clash-verge-rev.clash-verge-rev\clash-verge.yaml
time="2025-05-18T12:44:04.736079100+08:00" level=info msg="Start initial configuration in progress"
time="2025-05-18T12:44:04.750593900+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2025-05-18T12:44:04.750593900+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2025-05-18T12:44:04.770383900+08:00" level=info msg="Initial configuration complete, total time: 22ms"
time="2025-05-18T12:44:04.771385500+08:00" level=error msg="External controller tls listen error: parse certificate failed, maybe format error:tls: failed to find any PEM data in certificate input, or path error: path is not subpath of home directory or SAFE_PATHS: D:\\15412\\SSL\\certificate.crt \n allowed paths: [D:\\15412\\AppData\\Roaming\\io.github.clash-verge-rev.clash-verge-rev]"
time="2025-05-18T12:44:04.771385500+08:00" level=info msg="RESTful API listening at: [::]:9090"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Sniffer is closed"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:44446"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider 故障转移-美国"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial provider ReizhiFree"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider 故障转移0.9-1.0"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider iwara"
time="2025-05-18T12:44:04.773383400+08:00" level=debug msg="Start New Health Checking {380b162c-76f7-4627-a3f5-d0a5a96296c6}"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider coomer"
time="2025-05-18T12:44:04.773383400+08:00" level=debug msg="Health Checking, proxy: 可直连网站, url: https://iwara.tv/, id: {380b162c-76f7-4627-a3f5-d0a5a96296c6}"
time="2025-05-18T12:44:04.773383400+08:00" level=debug msg="Health Checking, proxy: 负载均衡-轮询下载, url: https://iwara.tv/, id: {380b162c-76f7-4627-a3f5-d0a5a96296c6}"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider Discord"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial provider Turkey"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider E-hentai"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider HentaiVerse手动组"
time="2025-05-18T12:44:04.774382200+08:00" level=debug msg="Start New Health Checking {f4278d00-7ad8-4996-b764-7e8bb92e8366}"
time="2025-05-18T12:44:04.774382200+08:00" level=debug msg="Start New Health Checking {f968423c-7562-4342-be7e-c5fff59988c8}"
time="2025-05-18T12:44:04.774382200+08:00" level=debug msg="Health Checking, proxy: 负载均衡-轮询下载, url: https://www.gstatic.com/generate_204, id: {f4278d00-7ad8-4996-b764-7e8bb92e8366}"
time="2025-05-18T12:44:04.774382200+08:00" level=debug msg="Health Checking, proxy: 不计费故障转移, url: https://www.gstatic.com/generate_204, id: {f4278d00-7ad8-4996-b764-7e8bb92e8366}"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider EA"
time="2025-05-18T12:44:04.774382200+08:00" level=debug msg="Start New Health Checking {ac902d47-829d-4758-bf9e-0ace35ef1696}"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial provider ReizhiLow"
time="2025-05-18T12:44:04.774382200+08:00" level=debug msg="Health Checking, proxy: 不计费故障转移, url: https://www.gstatic.com/generate_204, id: {ac902d47-829d-4758-bf9e-0ace35ef1696}"
time="2025-05-18T12:44:04.774382200+08:00" level=debug msg="Health Checking, proxy: 可直连网站, url: https://www.gstatic.com/generate_204, id: {ac902d47-829d-4758-bf9e-0ace35ef1696}"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider 🔰 节点选择"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider Boinc"
time="2025-05-18T12:44:04.773383400+08:00" level=debug msg="Health Checking, proxy: 🔰 节点选择, url: https://iwara.tv/, id: {380b162c-76f7-4627-a3f5-d0a5a96296c6}"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider 📲 电报US"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider 🌏 国内媒体"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider Epic"
time="2025-05-18T12:44:04.777902200+08:00" level=debug msg="Start New Health Checking {08915aa4-5cc7-441a-a1cb-d42732751ccf}"
time="2025-05-18T12:44:04.773383400+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2025-05-18T12:44:04.777902200+08:00" level=debug msg="Health Checking, proxy: 低倍率故障转移, url: https://www.gstatic.com/generate_204, id: {08915aa4-5cc7-441a-a1cb-d42732751ccf}"
```
