### ISSUE TITLE
[Bug] dialer-proxy 在多路复用的情况下存在死连接 导致节点连接失败

### ISSUE THREAD

**Issue by OIake** [MetaCubeX/mihomo#2047]
### 系统版本

Android MacOS Linux(Openwrt)

### Mihomo 版本

Mihomo Meta v1.19.8 darwin arm64 with go1.20.14 Tue May 13 04:23:22 UTC 2025
Use tags: with_gvisor

### 配置文件

```yaml
proxies:
  - name: "trojan"
    type: trojan
    server: 127.0.0.1
    port: 12345
    # 省略............
    network: grpc
    dialer-proxy: shadowsocks

  - name: "shadowsocks"
    type: ss
    server: 1.1.1.1
    port: 1234
```

### 描述

2024/9 已经存在相同的问题 https://github.com/MetaCubeX/mihomo/issues/1550

以配置文件为例,并且本地存在多个网络接口的情况下。

---

### OpenWrt 为例:

假设当前的 PPPoE 的 IPv4 的地址为: `1.1.1.1` (已经启动 Clash )
那么当运营商踢下线重新拨号时 那么 PPPoE IPv4 的地址为: `2.2.2.2` (不重新启动 Clash)

那么此时代理节点不可用

通过 `netstat -tnp` 命令查看时,发现 Clash 没有正常关闭旧连接。多路复用的节点依旧在使用旧连接。这种问题在多路复用的情况更严重

tcp 0 4487 1.1.1.1:49214 x.x.x.x:1234 ESTABLISHED

需要手动从面板中关闭下面这条连接即可恢复

类型 Inner(tcp)
域名 127.0.0.1 (Trojan 中的地址)
节点链 1.1.1.1 (shadowsocks 中的地址)

---

### 以 Android 系统为例:

在不关闭Clash的情况下 从 Wi-Fi 网络切换至 4G。此时 Wi-Fi 和 4G 的情况下节点都可用。

1.  再切回原来的 Wi-Fi 网络下，无法使用节点。 存在死链接
2.  再切回 4G, 无法使用节点。 存在死链接
