### ISSUE TITLE
[Bug] 出现大量的re-creating the http client日志

### ISSUE THREAD

**Issue by xiaoziguys** [MetaCubeX/mihomo#2051]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

MacOS

### 系统版本

MacOS 15.4.1

### Mihomo 版本

v1.19.8 

### 配置文件

```yaml
dns:
  enable: true
  prefer-h3: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true

  nameserver-policy:
    "rule-set:copilot":
      - https://208.67.220.220/dns-query # open dns
      - https://cloudflare-dns.com/dns-query  # Cloudflare DoH
    "geosite:geolocation-!cn":
      - https://208.67.220.220/dns-query # open dns
      - https://cloudflare-dns.com/dns-query  # Cloudflare DoH
  
  nameserver:
    - https://223.6.6.6/dns-query  # 阿里DoH

  fallback:
    - https://208.67.220.220/dns-query # open dns
    - https://cloudflare-dns.com/dns-query  # Cloudflare DoH
  
  direct-nameserver:
   - https://223.6.6.6/dns-query
  direct-nameserver-follow-policy: true
  
  default-nameserver: [119.29.29.29, 223.5.5.5]

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
  route-exclude-address:
    - 192.168.0.0/16
    - 17.0.0.0/8
```

### 描述

不知道为什么出现大量的re-creating the http client 提示。DoH是不是不能用?dns=去访问

### 重现方式

按照配置这样配置dns就会有这个问题，用的clash verge。

### 日志

```shell
05-19 14:17:27DEBUG
re-creating the http client due to requesting https://208.67.220.220:443/dns-query: Get "https://208.67.220.220:443/dns-query?dns=AAABAAABAAAAAAAAA2FwaQJpcAJzYgAAAQAB": context deadline exceeded
05-19 14:17:27DEBUG
[DNS] resolve api.ip.sb AAAA from https://cloudflare-dns.com:443/dns-query
05-19 14:17:27DEBUG
[TUN] Auto detect interface for 104.16.248.249 --> en0
05-19 14:17:27DEBUG
[DNS] resolve api.ip.sb AAAA from https://208.67.220.220:443/dns-query
05-19 14:17:27DEBUG
[TUN] Auto detect interface for 208.67.220.220 --> en0
05-19 14:17:27DEBUG
[https://208.67.220.220:443/dns-query] using HTTP/2 for this upstream: <nil>
05-19 14:17:27DEBUG
re-creating the http client due to requesting https://208.67.220.220:443/dns-query: Get "https://208.67.220.220:443/dns-query?dns=AAABAAABAAAAAAAAA2FwaQJpcAJzYgAAAQAB": context deadline exceeded
05-19 14:17:27DEBUG
[TUN] Auto detect interface for 208.67.220.220 --> en0
05-19 14:17:27DEBUG
[https://208.67.220.220:443/dns-query] using HTTP/2 for this upstream: <nil>
05-19 14:17:27WARNING
[UDP] Resolve Ip error: couldn't find ip
```
