### ISSUE TITLE
[Bug] time="2025-05-19T08:45:38.427695960Z" level=error msg="Start TUN listening error: initialize auto redirect: missing nftables support: netlink receive: invalid argument"

### ISSUE THREAD

**Issue by hyird** [MetaCubeX/mihomo#2052]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [ ] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [ ] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Linux

### System Version

routeros v7.18.2

### Mihomo Version

1.19.8

### Configuration File

```yaml
redir-port: 7893
mixed-port: 7897
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
unified-delay: true
tcp-concurrent: true

external-controller: 0.0.0.0:9090
external-ui: "./ui"
external-ui-name: xd
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

find-process-mode: strict
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 30

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - "dlg.io.mi.com"
    - "+.push.apple.com"
    - "+.apple.com"

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 7.0.0.0/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "+.services.googleapis.cn"
    - "+.xn--ngstr-lra8j.com"
    - "time.*.com"
    - "+.pool.ntp.org"
    - "+.ntp.tencent.com"
    - "+.ntp1.aliyun.com"
    - "+.ntp.ntsc.ac.cn"
    - "+.cn.ntp.org.cn"
  nameserver-policy:
    '+.arpa': '10.0.0.1'
    'rule-set:private_domain,cn_domain':
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
  fallback-filter:
    geoip: true
    geoip-code: CN
  proxy-server-nameserver:
    - https://doh.pub/dns-query

tun:
  enable: true
  stack: system
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
```

### Description

由于routeros 内核没有 nftables 支持 自己build 了 基于 alpine 3.18的使用iptables的docker镜像
```
FROM alpine:3.18
ARG TARGETARCH
COPY bin/${TARGETARCH}/mihomo /usr/local/bin/mihomo
RUN apk update && apk add iptables && chmod +x /usr/local/bin/mihomo
ENTRYPOINT ["/usr/local/bin/mihomo"]
```
这是我的dockerfile 在routeros 的container中 tun模式无法启动 
`time="2025-05-19T08:45:38.427695960Z" level=error msg="Start TUN listening error: initialize auto redirect: missing nftables support: netlink receive: invalid argument"`
根据日志得知 是 mihomo 使用了 nftables 进行 redirect 而不是 iptables.

根据文档得知 auto_redirect 自动配置 iptables/nftables 以重定向 TCP 连接.

之前是 1.19.4 运行正常,升级到 1.19.8后报错. 应该是判断使用 iptables还是nftables出了问题.

### Reproduction Steps

.

### Logs

```shell
time="2025-05-19T08:45:38.427695960Z" level=error msg="Start TUN listening error: initialize auto redirect: missing nftables support: netlink receive: invalid argument"
```
