### ISSUE TITLE
[Bug] hysteria2 随机端口失效

### ISSUE THREAD

**Issue by qist** [MetaCubeX/mihomo#2056]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [x] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Windows

### System Version

windows11 

### Mihomo Version

alpha-8f92b1d

### Configuration File

```yaml
- name: "hysteria2"
    type: hysteria2
    server: hysteria
    port: 0
    ports: 40000-50000
    hop-interval: 15
    # up: "1000 mbps"
    # down: "1000 mbps"
    password: password
    obfs: salamander
    obfs-password: password
    sni: hysteria.swsixtwo.top
    skip-cert-verify: false
    alpn:
      - h3
    fast-open: true
```

### Description

hysteria2 随机端口失效 单个端口正常

### Reproduction Steps

hysteria2 随机端口失效 单个端口正常

### Logs

```shell

```
