### ISSUE TITLE
[Feature] DNS模块nameserver输入支持二维数组展开

### ISSUE THREAD

**Issue by futuretech6** [MetaCubeX/mihomo#2057]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [x] 我是中文用户，而非其他语言用户

### 描述

由于会定义很多dns，且有重复利用，所以我将不同属性的dns归进了不同的锚点组，例如：

```yaml
.ns-domestic: &ns-domestic
  - &dns-ali https://dns.alidns.com/dns-query
  - &dns-tx https://doh.pub/dns-query
.ns-global: &ns-global
  - &dns-cf tls://1.1.1.1
  - &dns-go tls://8.8.4.4
  - &dns-qd9 https://149.112.112.112/dns-query
  - &dns-open https://208.67.222.222/dns-query
.ns-proxy: &ns-proxy
  - *dns-ali
  - *dns-cf
  - *dns-go
.ns-fallback: &ns-fallback # 相当于 domestic + global
  - *dns-ali
  - *dns-tx
  - *dns-cf
  - *dns-go
  - *dns-qd9
  - *dns-open
```

然后在dns模块中就可以：

```yaml
dns:
  default-nameserver: *ns-doh
  nameserver: *ns-fallback
  proxy-server-nameserver: *ns-proxy
  nameserver-policy:
    "geosite:gfw": *ns-global
    "geosite:cn": *ns-domestic
    # ...
```

这样就可以在不同的规则中复用这些dns了。但是现在的写法 ns-fallback 是完全冗余的，由于 yaml 不支持合并多个锚点数组，所以才要把他们都写一遍。但是 yaml 支持把多个锚点数组合并成一个二维数组，如下：

```python
import yaml

yaml_str = """
array1: &array1 [1, 2]
array2: &array2 [3, 4]
merged_array:
  [*array1, *array2]
"""

data = yaml.safe_load(yaml_str)
print(data["merged_array"])
```

输出为：`[[1, 2], [3, 4]]`。同理，`[*ns-domestic, *ns-global]` 也可以合并成一个二维数组 `[[*dns-ali, *dns-tx], [*dns-cf, *dns-go, ...]]`。因此，如果 dns 模块的 `nameserver` 等字段可以接受二维数组作为输入，并且在内部二维数组展开为一维数组，那么就可以直接用 `[*ns-domestic, *ns-global]` 来代替 `*ns-fallback`，这样就可以避免冗余的定义，在修改dns配置时不需要进行多余的修改，避免出错。
