### ISSUE TITLE
[Bug] v1.19.8 auto-redirect 异常

### ISSUE THREAD

**Issue by hyird** [MetaCubeX/mihomo#2061]
### Verify steps

- [ ] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [ ] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [ ] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Linux

### System Version

routeros v7.18.2

### Mihomo Version

1.19.4 and 1.19.8

### Configuration File

```yaml
redir-port: 7893
mixed-port: 7897
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
unified-delay: true
tcp-concurrent: true

external-controller: 0.0.0.0:9090
external-ui: "./ui"
external-ui-name: xd
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

find-process-mode: strict
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 30

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - "dlg.io.mi.com"
    - "+.push.apple.com"
    - "+.apple.com"

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 7.0.0.0/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "+.services.googleapis.cn"
    - "+.xn--ngstr-lra8j.com"
    - "time.*.com"
    - "+.pool.ntp.org"
    - "+.ntp.tencent.com"
    - "+.ntp1.aliyun.com"
    - "+.ntp.ntsc.ac.cn"
    - "+.cn.ntp.org.cn"
  nameserver-policy:
    '+.arpa': '10.0.0.1'
    'rule-set:private_domain,cn_domain':
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
  fallback-filter:
    geoip: true
    geoip-code: CN
  proxy-server-nameserver:
    - https://doh.pub/dns-query

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
```

### Description

使用自己封装的docker 运行mihomo 发现 v1.19.8 ipt 没有加上 mihomo-prerouting 实际使用中流量全部走tun 降级到 1.19.4 正常.

```
/ # iptables -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 mihomo-prerouting  0    --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 40 packets, 2372 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   40  2372 mihomo-output  0    --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain POSTROUTING (policy ACCEPT 40 packets, 2372 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain mihomo-output (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   6    --  *      Meta    0.0.0.0/0            0.0.0.0/0            redir ports 42845

Chain mihomo-prerouting (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     0    --  Meta   *       0.0.0.0/0            0.0.0.0/0           
    0     0 DNAT       17   --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:53 to:7.0.0.1
    0     0 RETURN     0    --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
    0     0 REDIRECT   6    --  *      *       0.0.0.0/0            0.0.0.0/0            redir ports 42845
```

```
/ # iptables -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 50 packets, 15306 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 25 packets, 1746 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 104 packets, 6212 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  104  6212 mihomo-output  0    --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain POSTROUTING (policy ACCEPT 129 packets, 19772 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain mihomo-output (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   6    --  *      Meta    0.0.0.0/0            0.0.0.0/0            redir ports 44565
```

### Reproduction Steps

分别测试 v1.19.4 v1.19.8 使用 iptables -t nat -L -n -v 查看 信息

### Logs

```shell
no log
```
