### ISSUE TITLE
[Bug] HY2 入站 ECH 配置异常

### ISSUE THREAD

**Issue by Purgepyro** [MetaCubeX/mihomo#2062]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

Debian 12.11

### Mihomo 版本

Mihomo Meta v1.19.9 linux amd64 with go1.24.3 Thu May 22 02:45:24 UTC 2025
Use tags: with_gvisor

### 配置文件

```yaml
ipv6: true
allow-lan: true
unified-delay: false
tcp-concurrent: true

find-process-mode: strict
global-client-fingerprint: chrome

listeners:
- name: hysteria2-in
  type: hysteria2
  port: /
  listen: 0.0.0.0
  users:
    user1: /
  ignore-client-bandwidth: true
  masquerade: ""
  alpn:
  - h3
  ech-key: 
    -----BEGIN ECH KEYS-----
    ACATlLgi0thBqlipyaFA/NFVeI4v166uBA3HE47PvDLOgQBJ/g0ARQAAIAAgawPo
    GzY8ughZJtqqN+yoOGoJ0nJZS7/s8sxq1NdIZBUADAABAAEAAQACAAEAAwAOd3d3
    LmljbG91ZC5jb20AAA==
    -----END ECH KEYS-----
  certificate: /
  private-key: /
```

### 描述

同样的 ECH 配置在 Vless 中没有报错，但在 hy2 中报错
msg="Listener hysteria2-in listen err: parse certificate failed, maybe format error:tls: failed to find any PEM data in certificate input, or path error: path is not subpath of home directory or SAFE_PATHS

### 重现方式

已详细描述

### 日志

```shell
time="2025-05-22T05:36:39.728109731Z" level=info msg="Start initial configuration in progress"
time="2025-05-22T05:36:39.728687018Z" level=info msg="Geodata Loader mode: memconservative"
time="2025-05-22T05:36:39.728696732Z" level=info msg="Geosite Matcher implementation: succinct"
time="2025-05-22T05:36:39.728803743Z" level=info msg="Initial configuration complete, total time: 0ms"
time="2025-05-22T05:36:39.743608753Z" level=info msg="Sniffer is closed"
time="2025-05-22T05:36:39.743823825Z" level=info msg="Use tcp concurrent"
time="2025-05-22T05:36:39.745774965Z" level=error msg="Listener hysteria2-in listen err: parse certificate failed, maybe format error:tls: failed to find any PEM data in certificate in>
time="2025-05-22T05:36:39.747311693Z" level=info msg="DNS server(TCP) listening at: [::]:1053"
time="2025-05-22T05:36:39.747421457Z" level=info msg="Vless[vless-in] proxy listening at: [::]:8443"
time="2025-05-22T05:36:39.747521718Z" level=info msg="Start initial compatible provider default"
time="2025-05-22T05:36:39.747799415Z" level=info msg="DNS server(UDP) listening at: [::]:1053"
```
