### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ghost** [MetaCubeX/mihomo#2066]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

CentOS7

### Mihomo 版本

Mihomo Meta v1.19.8 linux amd64 with go1.24.3 Tue May 13 04:23:15 UTC 2025
Use tags: with_gvisor

### 配置文件

```yaml
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '0.0.0.0:9090'
# external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
tun:
  enable: true
  stack: system
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  default-nameserver:
    - tls://223.5.5.5
    - tls://223.6.6.6
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
```

### 描述

请问我已经在配置文件中打开了  auto-route: true，auto-redirect: true，为什么在容器中查看没有默认路由呢？但是我将局域网内的设备指向这里，是可以正常使用的，另外如果将运行frp的服务器指向这个网关，我就无法连上tcp的隧道了是为什么，如何解决

![Image](https://github.com/user-attachments/assets/60a6fb41-bc9a-45a9-b056-a20f66f85072)

下面是我的docekr-compose文件：
```
services:
  mihomo:
    image: metacubex/mihomo
    container_name: mihomo
    restart: always
    networks:
      magic:
        ipv4_address: 10.1.1.10
    cap_add:
      - NET_ADMIN
      # - ALL
    # privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    security_opt:
      - apparmor=unconfined
    volumes:
      - ./config.yaml:/root/.config/mihomo/config.yaml
    environment:
      - TZ=Asia/Shanghai
  yacd:
    image: haishanh/yacd:master
    container_name: yacd
    hostname: yacd
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mihomo
    networks:
      magic:
        ipv4_address: 10.1.1.4
networks:
  magic:
    name: proxy_network
    driver: macvlan
    driver_opts:
      parent: ens192
    ipam:
      config:
        - subnet: "10.1.1.0/24"
          ip_range: "10.1.1.0/24"
          gateway: "10.1.1.1"
```

### 重现方式

按配置重现

### 日志

```shell

```
