### ISSUE TITLE
[Bug] 在 Vless 入站和出站中使用 ech 后会报错

### ISSUE THREAD

**Issue by Purgepyro** [MetaCubeX/mihomo#2067]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

Debian 12.11

### Mihomo 版本

Mihomo Meta v1.19.9 linux amd64 with go1.24.3 Thu May 22 02:45:24 UTC 2025
Use tags: with_gvisor

最新的 alpha 版没有描述中的报错但仍然无法连接

### 配置文件

```yaml
服务端配置：
- name: vless-test
  type: vless
  port: 8444
  listen: 0.0.0.0
  users:
    - uuid: /
  grpc-service-name: "GService"
  ech-key: |
    -----BEGIN ECH KEYS-----
    ACBQgjP8dJtcFQCOym9GjJBrJGCpc37Rp16uIIMJeCX4UwBJ/g0ARQAAIAAgY/CJ
    3n5L1FABYSRIq5+4zQqZYW6eGNp+JiRsLaApgWoADAABAAEAAQACAAEAAwAOd3d3
    LmljbG91ZC5jb20AAA==
    -----END ECH KEYS-----
  certificate: /etc/nginx/ssl/*.visax.net_visax.net_P256/fullchain.cer
  private-key: /etc/nginx/ssl/*.visax.net_visax.net_P256/private.key

客户端配置：
  - name: Vless test
    type: vless
    server: /
    port: 8444
    tfo: true
    mptcp: true
    udp: true
    packet-encoding: xudp
    uuid: /
    tls: true
    servername: visax.net
    alpn:
      - h3
      - h2
      - http/1.1
    skip-cert-verify: false
    network: grpc
    ech-opts:
      enable: true
      config: AEn+DQBFAAAgACBj8InefkvUUAFhJEirn7jNCplhbp4Y2n4mJGwtoCmBagAMAAEAAQABAAIAAQADAA53d3cuaWNsb3VkLmNvbQAA
    grpc-opts:
      grpc-service-name: GService
```

### 描述

客户端启用 ECH 后，服务端报错
time="2025-05-23T06:49:27.962403392Z" level=error msg="https server panic: runtime error: invalid memory address or nil pointer dereference"
客户端关闭 ECH 后，可以正常连接

### 重现方式

如上

### 日志

```shell
time="2025-05-23T00:06:13.400088700-07:00" level=info msg="Start initial configuration in progress"
time="2025-05-23T00:06:13.401807900-07:00" level=info msg="Geodata Loader mode: memconservative"
time="2025-05-23T00:06:13.401807900-07:00" level=info msg="Geosite Matcher implementation: succinct"
time="2025-05-23T00:06:13.412947800-07:00" level=info msg="Initial configuration complete, total time: 12ms"
time="2025-05-23T00:06:13.412947800-07:00" level=info msg="RESTful API listening at: 127.0.0.1:1024"
time="2025-05-23T00:06:13.415343100-07:00" level=info msg="Sniffer is closed"
time="2025-05-23T00:06:13.415343100-07:00" level=info msg="Use tcp concurrent"
time="2025-05-23T00:06:13.415343100-07:00" level=info msg="NTP service start, sync system time is true"
time="2025-05-23T00:06:13.422735400-07:00" level=debug msg="[DNS] system dns update to [2600:1700:7dd5:4010::1 192.168.1.254]"
time="2025-05-23T00:06:13.422735400-07:00" level=debug msg="[DNS] resolve time.apple.com A from system(udp://[2600:1700:7dd5:4010::1]:53,udp://192.168.1.254:53)"
time="2025-05-23T00:06:13.422735400-07:00" level=debug msg="[DNS] resolve time.apple.com AAAA from system(udp://[2600:1700:7dd5:4010::1]:53,udp://192.168.1.254:53)"
time="2025-05-23T00:06:13.423272300-07:00" level=debug msg="[DNS] resolve time.apple.com A from udp://192.168.1.254:53"
time="2025-05-23T00:06:13.423272300-07:00" level=debug msg="[DNS] resolve time.apple.com AAAA from udp://192.168.1.254:53"
time="2025-05-23T00:06:13.423272300-07:00" level=debug msg="[DNS] resolve time.apple.com AAAA from udp://[2600:1700:7dd5:4010::1]:53"
time="2025-05-23T00:06:13.423272300-07:00" level=debug msg="[DNS] resolve time.apple.com A from udp://[2600:1700:7dd5:4010::1]:53"
time="2025-05-23T00:06:13.427336100-07:00" level=debug msg="[DNS] time.apple.com --> [2620:149:a00:3000::1f2 2620:149:a00:4000::1f2 2620:149:a0c:4000::1f2] AAAA from udp://192.168.1.254:53"
time="2025-05-23T00:06:13.427336100-07:00" level=debug msg="[DNS] time.apple.com --> [17.253.16.125 17.253.4.125 17.253.16.253] A from udp://192.168.1.254:53"
time="2025-05-23T00:06:13.427336100-07:00" level=debug msg="[DNS] time.apple.com --> [2620:149:a0c:4000::1f2 2620:149:a00:3000::1f2 2620:149:a00:4000::1f2] AAAA from udp://[2600:1700:7dd5:4010::1]:53"
time="2025-05-23T00:06:13.427336100-07:00" level=debug msg="[DNS] time.apple.com --> [17.253.16.125 17.253.4.125 17.253.16.253] A from system(udp://[2600:1700:7dd5:4010::1]:53,udp://192.168.1.254:53)"
time="2025-05-23T00:06:13.427336100-07:00" level=debug msg="[DNS] time.apple.com --> [2620:149:a00:3000::1f2 2620:149:a00:4000::1f2 2620:149:a0c:4000::1f2] AAAA from system(udp://[2600:1700:7dd5:4010::1]:53,udp://192.168.1.254:53)"
time="2025-05-23T00:06:13.442990600-07:00" level=info msg="System clock is ahead of NTP time by 8.87345ms"
time="2025-05-23T00:06:13.654425200-07:00" level=info msg="Sync system time success: 2025-05-23 00:06:13 -0700"
time="2025-05-23T00:06:13.654933000-07:00" level=info msg="DNS server(UDP) listening at: [::]:53"
time="2025-05-23T00:06:13.654933000-07:00" level=info msg="HTTP proxy listening at: [::]:8082"
time="2025-05-23T00:06:13.655517600-07:00" level=info msg="DNS server(TCP) listening at: [::]:53"
time="2025-05-23T00:06:13.655517600-07:00" level=info msg="SOCKS proxy listening at: [::]:8081"
time="2025-05-23T00:06:13.656035400-07:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:8080"
time="2025-05-23T00:06:13.656035400-07:00" level=info msg="Start initial compatible provider default"
time="2025-05-23T00:06:13.656035400-07:00" level=info msg="Start initial compatible provider GLOBAL"
time="2025-05-23T00:06:25.077570300-07:00" level=debug msg="[DNS] resolve www.gstatic.com A from https://1.1.1.1:443/dns-query"
time="2025-05-23T00:06:25.078113700-07:00" level=debug msg="creating a new http client"
time="2025-05-23T00:06:25.077570300-07:00" level=debug msg="[DNS] resolve www.gstatic.com AAAA from https://1.1.1.1:443/dns-query"
time="2025-05-23T00:06:25.079163100-07:00" level=debug msg="[https://1.1.1.1:443/dns-query] using HTTP/3 for this upstream: QUIC was faster"
time="2025-05-23T00:06:25.079687800-07:00" level=debug msg="use specified fingerprint:Edge"
time="2025-05-23T00:06:25.079687800-07:00" level=debug msg="use specified fingerprint:Edge"
time="2025-05-23T00:06:25.130764700-07:00" level=debug msg="REALITY Authentication: true, AEAD: *gcm.GCM"
time="2025-05-23T00:06:25.188301100-07:00" level=debug msg="[DNS] www.gstatic.com --> [142.250.72.227] A from https://1.1.1.1:443/dns-query"
time="2025-05-23T00:06:25.213910500-07:00" level=debug msg="[DNS] www.gstatic.com --> [2607:f8b0:4007:801::2003] AAAA from https://1.1.1.1:443/dns-query"
```
