### ISSUE TITLE
[Bug] Android 系统在仅使用 TUN，选择 system 或 mixed 模式时，存在请求未被代理捕获的问题

### ISSUE THREAD

**Issue by Energetic3906** [MetaCubeX/mihomo#2069]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [x] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Android

### System Version

Android 13

### Mihomo Version

v1.19.9

### Configuration File

```yaml
tun:
  enable: true
  stack: system # mixed or gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
  route-exclude-address:
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.1/24
    - 172.16.0.0/12
    - 192.168.0.0/16
```

### Description

TUN 模式启用且设置为 system/mixed 模式时，某些请求（尤其是首次请求）未被日志捕获且未进入代理流程，导致加载失败。返回上一步并重新请求后才会被正常捕获。而启用 gvisor 模式后，该问题完全消失。

可能是 TUN 模块未能及时捕获初始连接，而 gvisor 使用用户态协议栈，避免了系统干预，因此表现正常。

### Reproduction Steps

TUN 模式启用且设置为 system/mixed 模式时，打开微博，b站等 APP，会出现转圈，卡图或页面加载空白的情况。

### Logs

```shell

```
