### ISSUE TITLE
[Bug] Openclash 对于 external-ui-name 的修改与v1.19.9新添加的安全特性冲突

### ISSUE THREAD

**Issue by DonLeeFK** [MetaCubeX/mihomo#2071]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

OpenWrt

### Mihomo 版本

v1.19.9

### 配置文件

```yaml
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
```

### 描述

将openclash的meta内核版本更新到v1.19.9后，将无法正常启动。原因在于openclash自带的ui存储在/usr/share/openclash/ui当中，而新版本内核只允许调用/etc/openclash(ie 本地)的ui。
openclash会强制修改用户的config，所以无法通过手动设置external-ui-name一项来规避该问题。

### 重现方式

将openlash的meta内核升级到v1.19.9版本即可重现该问题。

### 日志

```shell
msg="path is not subpath of home directory or SAFE_PATHS: /usr/share/openclash/ui \n allowed paths: [/etc/openclash]"
```
