### ISSUE TITLE
[Bug] fake-ip-filter-mode模式问题

### ISSUE THREAD

**Issue by rsgdn** [MetaCubeX/mihomo#2072]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Linux

### System Version

Alpha

### Mihomo Version

Mihomo Meta alpha-989f4ec linux arm64 with go1.24.3 Fri May 23 13:05:34 UTC 2025
Use tags: with_gvisor

### Configuration File

```yaml
p: &p {type: http, interval: 86400, proxy: 🟢 直连, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}, exclude-filter: "(?i)[Hh][Tt][Tt][Pp]|[Tt][Gg]|官网|流量|网址|网站|剩余|套餐|到期|过期|朝鲜|地址|订阅|机场(?<!\\.)[2-9]{1}[0-9]?\\.?[0-9]?[x×]|(?<!\\.)[1]{1}[0-9]?\\.?[6-9]?[x×]"}

proxy-providers:
  机场:
    url: "#"
    <<: *p

proxies: 
  - name: "🟢 直连"
    type: direct
    ip-version: ipv6-prefer
    udp: true

mode: rule
log-level: silent
mixed-port: 7890
redir-port: 7891
tproxy-port: 7892
port: 8080
socks-port: 1080
ipv6: true
allow-lan: true
unified-delay: true
tcp-concurrent: true
external-controller: "[::]:9090"
external-ui: ui
external-ui-name: Zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"
secret: 63051

authentication:
  - nikki:63051

find-process-mode: off
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]

tun:
  enable: false
  stack: mixed
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false
  dns-hijack: []
  device: nikki
  mtu: 9000

dns:
  enable: true
  cache-algorithm: arc
  ipv6: true
  listen: "[::]:1053"
  respect-rules: false
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "RULE-SET:cn_domain"
  nameserver:
    - 202.96.128.86
    - 202.96.128.143

proxy-groups:
  - name: 🟠 科学
    type: url-test
    tolerance: 50
    include-all: true
    filter: "(?i)^(?!.*(?:🟢 直连)).*"

rules:
  - RULE-SET,private_ip,🟢 直连,no-resolve
  - RULE-SET,cn_domain,🟢 直连
  - RULE-SET,cn_ip,🟢 直连,no-resolve
  - MATCH,🟠 科学

rule-anchor:
  ip: &ip {type: http, interval: 86400, proxy: 🟠 科学, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, proxy: 🟠 科学, behavior: domain, format: mrs}
rule-providers:
  private_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"
  cn_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"
  private_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"
  cn_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"
```

### Description

设置fake-ip-filter-mode模式设置blacklist后，让cn域名返回真实ip，但是实际cn域名还是返回fakeip

### Reproduction Steps

另外测试了下fake-ip-filter设置gfw域名的情况下会返回真实ip，于是想了下是不是openwrt得可用磁盘空间不足(可用还剩下不到150m)，故把可用磁盘空间改为2g，情况还是不变

### Logs

```shell

```
