### ISSUE TITLE
anytls节点不能测速

### ISSUE THREAD

**Issue by niceyal** [MetaCubeX/mihomo#2076]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [ ] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [ ] I am a non-Chinese user.
- [x] I have tested with the latest Alpha branch version, and the issue still persists.
- [x] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [x] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [x] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [x] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Linux

### System Version

docker

### Mihomo Version

内核更新为了最新版

### Configuration File

```yaml
udp: true
  
- name: "US-anytls"
  type: anytls
  server: 
  port: 
  password: ""
  client-fingerprint: chrome
  udp: true
  idle-session-check-interval: 30
  idle-session-timeout: 30
  min-idle-session: 0
  sni: "bing.com"
  alpn:
    - h2
    - http/1.1
  skip-cert-verify: true
```

### Description

docker版 mihomo yaml添加anytls节点，不能测速，但是配置放在window上mihomoparty上可以正常使用同。

### Reproduction Steps

直接在yaml里面加anytls节点

### Logs

```shell

```
