### ISSUE TITLE
[Bug] 当DNS模块的监听IP为0.0.0.0或[::]时，锁定IPV6

### ISSUE THREAD

**Issue by xiandu999-yu** [MetaCubeX/mihomo#2087]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

Kwrt 24.10-SNAPSHOT 06.01.2025 by Kiddin' / LuCI openwrt-24.10 branch 26.150.60207~e459c57

### Mihomo 版本

alpha-71a8705

### 配置文件

```yaml
dns:
  enable: true
  cache-algorithm: arc
  use-hosts: true
  use-system-hosts: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:6122
  nameserver:
  - tcp://127.0.0.1:6053#lo
  proxy-server-nameserver:
  - tcp://127.22.6.1:6000#lo
  fake-ip-filter:
    - '+.*'
```

### 描述

当DNS模块的监听IP为0.0.0.0或[::]时，锁定IPV6

### 重现方式

监听IP不填即可....

### 日志

```shell
[root@Kwrt:09:55 PM ~] # lsof -i :6122
COMMAND   PID USER FD   TYPE DEVICE SIZE/OFF NODE NAME
mihomo  17474 root 11u  IPv6 714659      0t0  UDP *:6122 
mihomo  17474 root 12u  IPv6 715334      0t0  TCP *:6122 (LISTEN)
[root@Kwrt:09:58 PM ~] #
```
