### ISSUE TITLE
[Bug] chacha20报错崩溃

### ISSUE THREAD

**Issue by elysias123** [MetaCubeX/mihomo#2108]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Android

### 系统版本

Android15

### Mihomo 版本

Mihomo Meta alpha-67cc31e android arm64 with go1.24.4 Wed Jun 11 17:31:22 UTC 2025

### 配置文件

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:
  - {name: xxxx, server: xxxx.com, port: 65402, type: ss, cipher: chacha20-ietf-poly1305, password: xxxxx, plugin: obfs, plugin-opts: {mode: http, host: xxxx}, udp: true, tfo: true}
  - {name: xxx, server: xxxx.com, port: 32571, type: ss, cipher: chacha20-ietf, password: xxxxx, udp: true, tfo: true}
  - {name: xx, server: xxxx.com, port: 1096, type: ssr, cipher: chacha20-ietf, password: xxx, protocol: auth_aes128_sha1, obfs: plain, protocol-param: 308255:f00i4f1ym4r, obfs-param: xxxx, udp: true, tfo: true}


#导入的预设
pr: &pr
  type: select
  interval: 3600
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    timeout: 1000
  include-all: true
  lazy: true

proxy-groups:
  - {name: Proxy, <<: *pr}



rule-providers:

rules:
  - MATCH,Proxy

```

### 描述

就算不使用chacha20节点仅导入到mihomo，也会导致崩溃

以下是deepseek-r1对错误日志解释希望有所参考:
根据提供的错误日志，问题在于 ChaCha20 加密算法的计数器溢出，这导致程序崩溃（panic）。
问题原因
1. ChaCha20 计数器的限制：
   - ChaCha20 使用一个 64 位块计数器（32 位块索引 + 32 位块内偏移）。
   - 单个密钥/Nonce 对最多能加密 `2^32` 个数据块（每块 64 字节），即 256 GB 数据。
   - 超出此限制会导致计数器溢出，引发 `counter overflow` panic。

2.触发场景：
   - 长时间运行的连接（如大文件传输、持续代理流量）积累了超过 256 GB 数据。
   - 堆栈跟踪显示发生在 ShadowsocksR（SSR）的 `Write` 操作中（`shadowstream.Writer`），表明是**单个连接的数据量过大**。

### 重现方式

1个小时内随机崩溃

### 日志

```shell
panic: chacha20: counter overflow

goroutine 63934 [running]:
golang.org/x/crypto/chacha20.(*Cipher).XORKeyStream(0x4004c20880?, {0x4003d88028?, 0x256?, 0x800?}, {0x40034bc000?, 0x256?, 0x480?})
	golang.org/x/crypto@v0.33.0/chacha20/chacha_generic.go:218 +0x3f0
github.com/metacubex/mihomo/transport/shadowsocks/shadowstream.(*Writer).Write(0x4003d88008, {0x40034bc000, 0x256, 0x480})
	github.com/metacubex/mihomo/transport/shadowsocks/shadowstream/stream.go:28 +0xfc
github.com/metacubex/mihomo/transport/shadowsocks/shadowstream.(*Conn).Write(0x40055caa20?, {0x40034bc000?, 0x256?, 0x480?})
	github.com/metacubex/mihomo/transport/shadowsocks/shadowstream/stream.go:155 +0x54
github.com/metacubex/mihomo/transport/ssr/protocol.(*Conn).Write(0x4003e324d0, {0x40054a4b28, 0x13, 0x13})
	github.com/metacubex/mihomo/transport/ssr/protocol/stream.go:45 +0xe8
github.com/metacubex/mihomo/adapter/outbound.(*ShadowSocksR).StreamConnContext(0x40029b3940, {0x5cd9ad0f00, 0x4002295110}, {0x5cd9adc8f8, 0x4004c20840}, 0x4004f1cc00)
	github.com/metacubex/mihomo/adapter/outbound/shadowsocksr.go:65 +0x29c
github.com/metacubex/mihomo/adapter/outbound.(*ShadowSocksR).DialContextWithDialer(0x40029b3940, {0x5cd9ad0f00, 0x4002295110}, {0x5cd9ac4370?, 0x4004683860?}, 0x4004f1cc00)
	github.com/metacubex/mihomo/adapter/outbound/shadowsocksr.go:91 +0x1a4
github.com/metacubex/mihomo/adapter/outbound.(*ShadowSocksR).DialContext(0x40029b3940, {0x5cd9ad0f00, 0x4002295110}, 0x4004f1cc00)
	github.com/metacubex/mihomo/adapter/outbound/shadowsocksr.go:71 +0xc0
github.com/metacubex/mihomo/adapter/outbound.(*autoCloseProxyAdapter).DialContext(0x40031813e0, {0x5cd9ad0f00?, 0x4002295110?}, 0x0?)
	github.com/metacubex/mihomo/adapter/outbound/base.go:337 +0x34
github.com/metacubex/mihomo/adapter.(*Proxy).DialContext(...)
	github.com/metacubex/mihomo/adapter/adapter.go:64
github.com/metacubex/mihomo/adapter.(*Proxy).URLTest(0x4003181470, {0x5cd9ad0f00, 0x4002295110}, {0x40003c8160, 0x1a}, {0x0, 0x0, 0x0?})
	github.com/metacubex/mihomo/adapter/adapter.go:225 +0x1c4
github.com/metacubex/mihomo/adapter/provider.(*HealthCheck).execute.func1()
	github.com/metacubex/mihomo/adapter/provider/healthcheck.go:184 +0x15c
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.11.0/errgroup/errgroup.go:78 +0x54
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 63172
	golang.org/x/sync@v0.11.0/errgroup/errgroup.go:75 +0x94
```
