### ISSUE TITLE
[Bug]  Proxy Provider Update Fails Due to One Invalid Proxy Entry – Should Skip Instead of Stopping

### ISSUE THREAD

**Issue by 1110000111** [MetaCubeX/mihomo#2128]
### Verify steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all the configuration items I have written, rather than just piling up seemingly useful options or default values.
- [x] I have carefully reviewed the [documentation](https://wiki.metacubex.one/) and have not resolved the issue.
- [x] I have searched the [Issue Tracker](……/) for the issue I want to raise and did not find it.
- [x] I am a non-Chinese user.
- [ ] I have tested with the latest Alpha branch version, and the issue still persists.
- [ ] I have provided the server and client configuration files and processes that can reproduce the issue locally, rather than a sanitized complex client configuration file.
- [ ] I provided the simplest configuration that can be used to reproduce the errors in my report, rather than relying on remote servers or piling on a lot of unnecessary configurations for reproduction.
- [ ] I have provided complete logs, rather than just the parts I think are useful out of confidence in my own intelligence.
- [ ] I have directly reproduced the error using the Mihomo command-line program, rather than using other tools or scripts.

### Operating System

Linux, Android

### System Version

1.19.11

### Mihomo Version

Hello,

I’ve encountered an issue with Mihomo when updating proxy providers. In some cases, if one of the proxies inside a provider has a malformed or invalid configuration, the update process stops entirely instead of skipping the problematic proxy and continuing with the rest.

For example, I received the following error during an update:

proxy 61 error: 'h2-opts.path' expected type 'string', got unconvertible type '[]string'

This behavior doesn't occur in other clients using the sing-box core — they simply skip the faulty proxy and proceed with the update.

I would really appreciate it if Mihomo could also skip such entries during provider updates instead of halting the whole process. That would greatly improve reliability.

Thanks a lot for your work!

### Configuration File

```yaml
p: &p {type: http, interval: 86400, proxy: DIRECT, health-check: {enable: true, url: "https://cp.cloudflare.com/", interval: 600}}

proxy-providers:
  
  CANADA:
    <<: *p
    url: "https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/refs/heads/main/Countries/Canada.txt"
```

### Description

-

### Reproduction Steps

-

### Logs

```shell
-
```
