### ISSUE TITLE
[Bug] x64 下的 openclash 更新内核后无法运行

### ISSUE THREAD

**Issue by 22613** [MetaCubeX/mihomo#2137]
### 验证步骤

- [x] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [x] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [x] 我是中文用户，而非其他语言用户
- [x] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [x] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [x] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [x] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [x] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Linux

### 系统版本

OpenWrt 24.10.1, r7323-5602da66c

### Mihomo 版本

Mihomo Meta alpha-0d92b67 linux amd64 with go1.23.10 Fri Jun 27 09:03:24 UTC 2025

### 配置文件

```yaml
---
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
proxies:

proxy-groups:

rules:

redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
keep-alive-interval: 15
keep-alive-idle: 600
ipv6: false
tcp-concurrent: true
unified-delay: true
sniffer:
authentication:
```

### 描述

x64 下的openclash 更新内核后无法运行

### 重现方式

external-ui: "/usr/share/openclash/ui"
路径报错。

### 日志

```shell
INFO[2025-06-27T14:44:00.423112749Z] Start initial configuration in progress
ERRO[2025-06-27T14:44:00.423174549Z] path is not subpath of home directory or SAFE_PATHS: /usr/share/openclash/ui
 allowed paths: [/etc/openclash]
configuration file /etc/openclash/config.yaml test failed
```
