### ISSUE TITLE
[Feature] Hysteria2 支持自定义 DNS 远程解析

### ISSUE THREAD

**Issue by senguangd** [MetaCubeX/mihomo#2142]
### Verification Steps

- [x] I have read the [documentation](https://wiki.metacubex.one/) and confirmed that this feature is not implemented
- [x] I have searched for the feature request I want to propose in the [Issue Tracker](……/) and did not find it
- [x] I am a non-Chinese user.

### Description

**场景**：当前，Hysteria2 代理在建立连接前，会先在本地解析目标主机的 IP 地址。如果目标域名被本地 DNS 污染或屏蔽，会导致连接失败。此外，这种方式也可能造成 DNS 泄露。用户无法为 Hysteria2 代理单独指定一个 DNS 解析器来解析目标地址，缺乏灵活性。

**需求**：为了解决上述问题，建议为 Hysteria2 代理增加自定义 DNS 解析功能。通过此功能，可以让 DNS 解析请求也通过代理隧道转发，从而避免本地 DNS 的问题。

具体改动如下：

1.  **新增 `remote-dns-resolve` 选项 (布尔值)**:
    *   用于控制 DNS 解析的方式。
    *   **如果未设置或设置为 `false` (默认行为)**：客户端将在本地解析 DNS。这是为了保持与旧版本行为的兼容性。
    *   **如果设置为 `true`**：客户端会将域名直接发送到 Hysteria2 远端服务器，由服务器进行解析。

2.  **新增 `dns` 选项 (字符串列表)**:
    *   用于配置自定义 DNS 服务器，**此选项仅在 `remote-dns-resolve: false` (或未设置) 时生效**。
    *   当客户端在本地解析 DNS 时，如果 `dns` 列表被配置，则会通过代理隧道使用这些指定的 DNS 服务器来解析目标域名，然后再发起连接。

#### **详细行为说明**

为了清晰地说明这些选项如何协同工作，以下是所有可能组合的行为：

1.  **`remote-dns-resolve` 未设置 (或为 `false`)，且 `dns` 未设置 (默认情况)**
    *   **行为**: 维持原始行为。客户端使用**系统默认的 DNS** 在本地解析域名，然后连接到解析出的 IP。
    *   **场景**: 适用于普通网络环境，行为与旧版本完全一致。

2.  **`remote-dns-resolve` 未设置 (或为 `false`)，但 `dns` 已设置**
    *   **行为**: **此为本次核心新增功能**。客户端会通过 Hysteria2 代理隧道，向 `dns` 列表中指定的 DNS 服务器发起查询请求，以获取目标域名的 IP 地址。
    *   **场景**: 完美解决本地 DNS 污染问题，并能有效防止 DNS 泄露。

3.  **`remote-dns-resolve` 设置为 `true`**
    *   **行为**: 客户端**不会在本地进行任何 DNS 解析**。它会将原始域名（例如 `www.google.com`）直接发送到 Hysteria2 远端服务器，由服务器负责解析和连接。
    *   **场景**: 当信任远端服务器的解析能力，且希望最大程度简化客户端配置时使用。在此模式下，`dns` 选项会被忽略。

**配置示例:**

```yaml
- name: "hysteria2-custom-dns"
  type: hysteria2
  server: server.com
  port: 443
  password: "password"
  # remote-dns-resolve 未设置，默认为 false
  # 使用自定义 DNS (通过代理隧道) 解析目标地址
  dns:
    - https://dns.google/dns-query
    - 8.8.8.8

- name: "hysteria2-remote-dns"
  type: hysteria2
  server: server.com
  port: 443
  password: "password"
  # 明确要求由远端服务器解析 DNS
  remote-dns-resolve: true
  # 在此模式下，下面的 dns 选项会被忽略
  dns:
    - 1.1.1.1
```

**实现优势:**

*   **防止 DNS 泄露**: 所有自定义 DNS 查询都将通过代理隧道发送，保护了用户隐私。
*   **绕过 DNS 污染**: 可以使用可靠的 DNS 服务来解析域名，避免因本地 DNS 问题导致的连接失败。
*   **行为清晰且向后兼容**: 默认行为与旧版本一致，新功能需显式开启，不会对现有用户造成影响。
*   **提升灵活性**: 用户可以根据网络环境，在“本地默认解析”、“本地隧道解析”、“远端解析”三种模式中自由选择。
