### ISSUE TITLE
TUN 模式偶现创建adapter 失败

### ISSUE THREAD

**Issue by cod-soap** [MetaCubeX/mihomo#233]
开启了tun模式：
```
# Tun 配置
tun:
  enable: true
  stack: system # gvisor
  dns-hijack:
    - 198.18.0.2:53 # 需要劫持的 DNS
  auto-detect-interface: true # 自动识别出口网卡
  auto-route: true # 配置路由表
```

报错如下;

```
time="2022-11-01T15:09:44+08:00" level=info msg="Start initial configuration in progress"
time="2022-11-01T15:09:44+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2022-11-01T15:09:44+08:00" level=warning msg="Auto detect interface: WLAN"
time="2022-11-01T15:09:44+08:00" level=info msg="Initial configuration complete, total time: 16ms"
time="2022-11-01T15:09:44+08:00" level=info msg="Sniffer is closed"
time="2022-11-01T15:09:44+08:00" level=info msg="Start initial compatible provider default"
time="2022-11-01T15:09:44+08:00" level=info msg="Use IPv6"
time="2022-11-01T15:09:44+08:00" level=info msg="Use interface name: WLAN"
time="2022-11-01T15:09:44+08:00" level=info msg="RESTful API listening at: [::]:9093"
time="2022-11-01T15:09:44+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:10801"
time="2022-11-01T15:09:44+08:00" level=info msg="[TUN] Using existing driver 0.14"
time="2022-11-01T15:09:44+08:00" level=info msg="[TUN] Creating adapter"
time="2022-11-01T15:09:59+08:00" level=error msg="[TUN] Timed out waiting for device query: 等待的操作过时。 (Code 0x00000102)"
time="2022-11-01T15:09:59+08:00" level=error msg="[TUN] Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC0000035): 当文件已存在时，无法创建该文件。 (Code 0x000000B7)"
time="2022-11-01T15:09:59+08:00" level=error msg="Start TUN listening error: can't open tun: create tun: Error creating interface: Cannot create a file when that file already exists."
```
