### ISSUE TITLE
1.13.2 中TUN绑定IP的子网掩码问题？

### ISSUE THREAD

**Issue by ericcug** [MetaCubeX/mihomo#260]
在以前版本中，tun接口绑定的是fakeip第一个地址并且子网掩码相同，如fakeip range 198.18.0.0/16，tun 接口198.18.0.1/16。

在新版本中使用sing-tun之后，tun接口绑定的ip固定为198.18.0.1/30，造成问题是需要手动添加fakeip到路由表中ip route add 198.0.0/16 dev utun，而原来是不需要这个操作。

不知道ipv4 /30, ipv6 /126 这个子网掩码是有意这么设计还是出于其他目的？

**Comment by strahe** [comment]
同问， tun绑定的只有2个ip能用， fakeip range 通常是 `198.18.0.0/16`.

**Comment by lankylonky22** [comment]
im confused

**Comment by 1219099256** [comment]
同样遇到这个问题

**Comment by lankylonky22** [comment]
win 10也用不了要先执行以下命令：
```
route delete 198.18.0.0
route ADD 198.18.0.0 MASK 255.255.0.0 198.18.0.1 METRIC 256
```

**Comment by lyz05** [comment]
可以在配置中手动配置一下路由来解决，反正只要让dns解析出的fakeip路由到TUN网卡即可。
```yaml
tun:
  enable: true
  stack: system
  ...
  inet4-route-address:
    - 198.18.0.0/16
```
我也不理解这个子网掩码为啥是这样设定的。原版Permium内核就不需要额外的添加路由，默认的子网掩码 255.255.0.0 就恰好能涵盖DNS解析出的fakeip的地址。
