### ISSUE TITLE
alpha 版本: fakeip 给 google.com 解析返回了 198.18.0.3, 但 198.18.0.3 是广播地址

### ISSUE THREAD

**Issue by j178** [MetaCubeX/mihomo#290]
版本：Clash Meta alpha-cd99b2e linux amd64 with go1.19.3 Tue Dec  6 02:14:09 UTC 2022
配置：
```yaml
dns:
  enable: true
  listen: 127.0.0.1:8853
  default-nameserver:
    - 223.5.5.5
    - 1.0.0.1
  ipv6: false
  enhanced-mode: fake-ip
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
```
`ip addr` 输出：
```
16: Meta: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 9000 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none
    inet 198.18.0.1/30 brd 198.18.0.3 scope global Meta
       valid_lft forever preferred_lft forever
    inet6 fe80::aba:2e02:15d:c0be/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
```
`dig google.com` 输出：
```
$ dig google.com

; <<>> DiG 9.16.1-Ubuntu <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17695
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; MBZ: 0x0001, udp: 4096
; COOKIE: 69c897ec1dbc3da6 (echoed)
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             1       IN      A       198.18.0.3

;; Query time: 0 msec
;; SERVER: 192.168.224.1#53(192.168.224.1)
;; WHEN: Tue Dec 06 23:42:32 CST 2022
;; MSG SIZE  rcvd: 67
```
`ping google.com` 会报错：
```
$ ping google.com
ping: Do you want to ping broadcast? Then -b. If not, check your local firewall rules
```
