### ISSUE TITLE
shadowsocks作为listeners时，出向的包没有打routing-mark

### ISSUE THREAD

**Issue by zjzxj** [MetaCubeX/mihomo#385]
具体配置是这样的：
```
interface-name: eth0 
routing-mark: 6666 
proxies:  
  - name: "PROXY" 
  - type: hysteria
interface-name: eth0 
routing-mark: 6666 
proxies:  
  - name: "PROXY"
    type: hysteria
    server: 1.2.3.4
    port: 12345
    auth_str: "12345"
    alpn: 
      - ayaya
    protocol: udp         
    up: '100 Mbps'         
    down: '100 Mbps'      
    sni: "aaa.com
  
listeners:
  - name: tun-in-1
    type: tun
    stack:  system
    dns-hijack:
    auto-detect-interface: true
    auto-route: false
    mtu: 1500
    inet4-address:
      - 172.16.33.1/30
  - name: shadowsocks-in-1
    type: shadowsocks
    port: 10000
    listen: 0.0.0.0
    password: xxxxxxxx......
    cipher: 2022-blake3-chacha20-poly1305
```
无关部分暂时省略
我用的策略路由
```
ip route add default dev Meta table 2023
ip rule add not fwmark 6666 table 2023
ip rule add table main suppress_prefixlength 0
```
shadowsocks无法连接成功，发现出向数据包未打标
```
iptables -t mangle -A OUTPUT -p tcp -s 0/0 --sport 10000 -j MARK --set-mark 0x1a0a
```
运行后，一切正常
