### ISSUE TITLE
DNS server behind Clash

### ISSUE THREAD

**Issue by hadifarnoud** [MetaCubeX/mihomo#410]
due to DNS poisoning and other DNS issues related to internet censorship, I decided to use Pihole with Unbound.

However, because I have Clash setup on my router (via OpenClash), my DNS server doesn't work properly. It still returns fake-ips despite having Unbound. When I turn off clash everything works fine.

Is there a way I can turn fake-ip off for a source address? for example all DNS requests coming from 192.168.1.12, goes through without dns-hijacking

fake-ip filter doesn't work in this case. I can filter out a domain, not everything

**Comment by Skyxim** [comment]
@hadifarnoud Switch to redir-host mode

**Comment by hadifarnoud** [comment]
I use this remote config on Windows, Linux (via OpenWRT), and MacOS

It looks like redir-host has a lot of issues and OpenClash removed it

**Comment by Skyxim** [comment]
@hadifarnoud Only clash, nothing to do with clash-meta.

**Comment by hadifarnoud** [comment]
that did solve the issue. however, I now have DNS poisoning issue. my ISP does DNS hijacking and I get wrong IP for Twitter for example.

I don't know what I did wrong with redir-host config. but my DNS queries are not going through proxy servers and therefore being hijacked. this is my config:
```
tun:
  enable: true
  stack: gvisor #  only gvisor
  auto-route: true # auto set global route
dns:
  enable: true
  ipv6: false
  #enhanced-mode: fake-ip
  enhanced-mode: redir-host
  #fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - https://*****/dns-query
  - 109.71.254.155
  - 8.8.8.8
  - 114.114.114.114
  - 119.29.29.29
  - 223.5.5.5
  - https://doh.pub/dns-query
  - https://******/dns-query
  fallback:
  - 8.8.8.8
```
only DoH works.
