### ISSUE TITLE
[BUG] Trojan协议在配置client-fingerprint时似乎无法访问

### ISSUE THREAD

**Issue by hooUmAi** [MetaCubeX/mihomo#413]
在使用clashN时手动替换了Meta core的版本
ClashN: 2.14
Clash.Meta: Alpha-be5ce6249f1dd84cccbc0b4d9296badf62821456
Clash log:
```
time="xxxx-xx-xxTxx:x6:27.8951737+08:00" level=info msg="Start initial configuration in progress"
time="xxxx-xx-xxTxx:x6:27.8951737+08:00" level=info msg="Geodata Loader mode: memconservative"
time="xxxx-xx-xxTxx:x6:27.9086112+08:00" level=warning msg="Deprecated: Use Sniff instead"
time="xxxx-xx-xxTxx:x6:27.9086112+08:00" level=info msg="Initial configuration complete, total time: 13ms"
time="xxxx-xx-xxTxx:x6:27.9086112+08:00" level=info msg="Sniffer is closed"
time="xxxx-xx-xxTxx:x6:27.9086112+08:00" level=info msg="Start initial compatible provider default"
xxxx/xx/xx xx:x6:27 Change system proxy
xxxx/xx/xx xx:x6:27 Set rule mode Rule->Rule
xxxx/xx/xx xx:x6:27 Clash Proxies Latency Test
xxxx/xx/xx xx:x6:27 Refresh Clash Proxies
time="xxxx-xx-xxTxx:x6:29.6386927+08:00" level=debug msg="[Rule] use default rules"
time="xxxx-xx-xxTxx:x6:29.6386927+08:00" level=debug msg="[DNS] resolve proxy.my.server from tls://dot.my.server:853"
time="xxxx-xx-xxTxx:x6:29.6392022+08:00" level=debug msg="[DNS] resolve proxy.my.server from tls://dot.my.server:853"
time="xxxx-xx-xxTxx:x6:29.6392022+08:00" level=debug msg="[DNS] resolve proxy.my.server from https://doh.my.server:8443/dns-query"
time="xxxx-xx-xxTxx:x6:29.6392022+08:00" level=debug msg="creating a new http client"
time="xxxx-xx-xxTxx:x6:29.6392022+08:00" level=debug msg="[DNS] resolve proxy.my.server from https://doh.my.server:8443/dns-query"
time="xxxx-xx-xxTxx:x6:29.6392022+08:00" level=debug msg="[https://doh.my.server:8443/dns-query] using HTTP/2 for this upstream: HTTP3 support is not enabled"
time="xxxx-xx-xxTxx:x6:29.6392022+08:00" level=debug msg="[DNS] resolve dot.my.server from udp://119.29.29.29:53"
time="xxxx-xx-xxTxx:x6:29.6392022+08:00" level=debug msg="[DNS] resolve dot.my.server from udp://223.5.5.5:53"
time="xxxx-xx-xxTxx:x6:29.6392022+08:00" level=debug msg="[DNS] resolve dot.my.server from udp://119.29.29.29:53"
time="xxxx-xx-xxTxx:x6:29.6392022+08:00" level=debug msg="[DNS] resolve dot.my.server from udp://223.5.5.5:53"
time="xxxx-xx-xxTxx:x6:29.6392022+08:00" level=debug msg="[DNS] resolve doh.my.server from udp://223.5.5.5:53"
time="xxxx-xx-xxTxx:x6:29.6392022+08:00" level=debug msg="[DNS] resolve doh.my.server from udp://119.29.29.29:53"
time="xxxx-xx-xxTxx:x6:29.6392022+08:00" level=debug msg="[DNS] resolve doh.my.server from udp://119.29.29.29:53"
time="xxxx-xx-xxTxx:x6:29.6392022+08:00" level=debug msg="[DNS] resolve doh.my.server from udp://223.5.5.5:53"
time="xxxx-xx-xxTxx:x6:29.6556766+08:00" level=debug msg="[DNS] dot.my.server --> [server.ip], from udp://223.5.5.5:53"
time="xxxx-xx-xxTxx:x6:29.6556766+08:00" level=debug msg="[DNS] doh.my.server --> [server.ip], from udp://223.5.5.5:53"
time="xxxx-xx-xxTxx:x6:29.6562686+08:00" level=debug msg="[DNS] dot.my.server --> [], from udp://119.29.29.29:53"
time="xxxx-xx-xxTxx:x6:29.6562686+08:00" level=debug msg="[DNS] doh.my.server --> [], from udp://223.5.5.5:53"
time="xxxx-xx-xxTxx:x6:29.6562686+08:00" level=debug msg="[DNS] dot.my.server --> [], from udp://223.5.5.5:53"
time="xxxx-xx-xxTxx:x6:29.7314377+08:00" level=debug msg="[DNS] proxy.my.server --> [], from tls://dot.my.server:853"
time="xxxx-xx-xxTxx:x6:29.7332545+08:00" level=debug msg="[DNS] proxy.my.server --> [server.ip], from https://doh.my.server:8443/dns-query"
time="xxxx-xx-xxTxx:x6:29.7573784+08:00" level=debug msg="use specified fingerprint:Chrome"
time="xxxx-xx-xxTxx:x6:29.7852719+08:00" level=info msg="[TCP] 127.0.0.1:2431 --> some.google.server.ip:443 match Match using trojan"
time="xxxx-xx-xxTxx:x6:33.0007061+08:00" level=debug msg="use specified fingerprint:Chrome"
xxxx/xx/xx xx:x6:34 Refresh Clash Proxies
time="xxxx-xx-xxTxx:x6:41.325828+08:00" level=debug msg="[Rule] use default rules"
time="xxxx-xx-xxTxx:x6:41.3491686+08:00" level=debug msg="use specified fingerprint:Chrome"
time="xxxx-xx-xxTxx:x6:41.388552+08:00" level=info msg="[TCP] 127.0.0.1:2459 --> some.google.server.ip:443 match Match using trojan"
time="xxxx-xx-xxTxx:x6:58.0378649+08:00" level=debug msg="[Rule] use default rules"
time="xxxx-xx-xxTxx:x6:58.0615642+08:00" level=debug msg="use specified fingerprint:Chrome"
time="xxxx-xx-xxTxx:x6:58.0889176+08:00" level=info msg="[TCP] 127.0.0.1:2476 --> some.google.server.ip:443 match Match using trojan"
time="xxxx-xx-xxTxx:x7:02.5884992+08:00" level=debug msg="[Rule] use default rules"
time="xxxx-xx-xxTxx:x7:02.6128762+08:00" level=debug msg="use specified fingerprint:Chrome"
time="xxxx-xx-xxTxx:x7:02.6401208+08:00" level=info msg="[TCP] 127.0.0.1:2498 --> some.google.server.ip:443 match Match using trojan"
time="xxxx-xx-xxTxx:x7:19.604052+08:00" level=debug msg="[Rule] use default rules"
time="xxxx-xx-xxTxx:x7:19.6267994+08:00" level=debug msg="use specified fingerprint:Chrome"
time="xxxx-xx-xxTxx:x7:19.6578566+08:00" level=info msg="[TCP] 127.0.0.1:2532 --> some.google.server.ip:443 match Match using trojan"
```
Clash config:
```
mixed-port: 7890
allow-lan: false
bind-address: "*"
mode: rule
log-level: debug

ipv6: true

dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost
  nameserver:
    - https://doh.my.server:8443/dns-query
    - tls://dot.my.server:853

proxies:
  
  - name: "trojan"
    type: trojan
    server: "proxy.my.server"
    port: 8443
    password: somePassword
    udp: true
    skip-cert-verify: false
    alpn:
      - "http/1.1"
    client-fingerprint: chrome

rules:
  - DOMAIN-SUFFIX,my.server,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - DOMAIN,localhost,DIRECT

  - MATCH,trojan
```
cURL访问测试:
```
curl -x socks5://localhost:7890 https://google.com -v
*   Trying 127.0.0.1:7890...
* SOCKS5 connect to IPv4 some.google.server.ip:443 (locally resolved)
* SOCKS5 request granted.
* Connected to (nil) (127.0.0.1) port 7890 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* (12) (IN), , Unknown (0):
* error:0A00010B:SSL routines::wrong version number
* Closing connection 0
curl: (35) error:0A00010B:SSL routines::wrong version number
```
client-fingerprint为firefox时同样无法访问

服务端为Xray v1.7.5，似乎没有任何相关log
不配置client-fingerprint时访问正常
