### ISSUE TITLE
1.14.2 sniffer 出错后导致网站访问失败

### ISSUE THREAD

**Issue by EkkoG** [MetaCubeX/mihomo#420]
版本：alpha-4c1682b 或者 1.14.2
系统: OpenWrt 22.03.3
OpenClash 版本 v0.45.87-beta
系统架构 : amd64

从 1.14.1 升级到 1.14.2 后发现部分网站经常访问失败，后又换到 clash.meta-linux-amd64-compatible-alpha-4c1682b.gz 也是一样的问题

观察一下，访问失败后，通常会有如下日志

23-03-02 11:22:52
error
[Sniffer] [144.76.35.222] may not have any sent data, Consider adding skip

关掉 sniffer 功能后，访问正常

请求是通过 python 发起的 https://github.com/NAStool/nas-tools/blob/0f0f155a05481b92fbc37e38249937f3d3b175f1/app/sites/site_userinfo.py#L77

Python 运行于 docker 中，Dockerfile https://github.com/NAStool/nas-tools/blob/master/docker/Dockerfile

网站为加了 CloudFlare CDN 的网站，应该和具体的站点没有关系，如需要提供站点后续可以提供

**Comment by Skyxim** [comment]
@EkkoG 不要随意对任何端口嗅探，这个报错事嗅探之初就有的

**Comment by EkkoG** [comment]
```yml
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  force-domain:
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssott.com"
  skip-domain:
  - "+.apple.com"
  - Mijia Cloud
  - "+.jd.com"
  sniff:
    TLS:
    HTTP:
      ports:
      - 80
      - 8080-8880
      override-destination: true
```

「不要随意对任何端口嗅探」的意思是不要随意开嗅探功能还是说开的话要限制端口

以上是 openclash 生成的嗅探相关的配置

不太理解的是在 1.14.1 上同样的配置没什么问题，1.14.2 就有问题了，想来 1.14.2 应该有修改相关的逻辑吧
