### ISSUE TITLE
使用ipv6地址访问DNS导致防污染失效

### ISSUE THREAD

**Issue by abcfy2** [MetaCubeX/mihomo#453]
我的相关的DNS配置如下:

```yaml
dns: {enable: true, ipv6: true, listen: 0.0.0.0:1053, use-hosts: true, enhanced-mode: redir-host, default-nameserver: [114.114.114.114, 223.5.5.5, https://1.0.0.1/dns-query, https://223.5.5.5/dns-query, 127.0.0.1:53], nameserver: [https://223.5.5.5/dns-query, https://doh.pub/dns-query, tls://dns.rubyfish.cn:853], fallback: [https://1.0.0.1/dns-query, tls://1.0.0.1:853], fallback-filter: {geoip: true}}
sniffer: {enable: true, sniffing: [tls, http]}
store-selected: true
find-process-mode: "off"
```

路由器上同时监听了ipv4和ipv6地址:

```sh
# netstat -nlup | grep 1053
udp        0      0 :::1053                 :::*                                28202/clash
```

但是走ipv4地址连接DNS，得到的解析结果符合期望，域名没有被污染，并且第一次解析速度会稍慢些，感觉走了fallback-dns配置:

```sh
# nslookup www.okx.com 127.0.0.1:1053
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost.localdomain

Name:      www.okx.com
Address 1: 2606:4700::6812:297
Address 2: 2606:4700::6812:397
Address 3: 104.18.2.151
Address 4: 104.18.3.151
```

但是走ipv6地址解析DNS发现域名被污染了，似乎根本没走到fallback dns的配置上，而且DNS解析记录很快就返回了:

```sh
# nslookup www.okx.com '[::1]:1053'
Server:    ::1
Address 1: ::1 ip6-localhost

Name:      www.okx.com
Address 1: 169.254.0.2
```

可以看到域名已被污染。请问下这是怎么回事？是我的配置有哪些问题吗？

**Comment by Larvan2** [comment]
尝试补全`fallback-filter`为如下
```yaml
 fallback-filter:                   #回落DNS服务器过滤
     geoip: true                      #为真时，不匹配为geoip规则的使用fallback返回结果
     geoip-code: CN                   #geoip匹配区域设定
     geosite:                         #【Meta专属】设定geosite某分类使用fallback返回结果
       - gfw
     ipcidr:                          #列表中的ip使用fallback返回解析结果
       - 240.0.0.0/4
```
