### ISSUE TITLE
[Bug] Android 版本出现 bind: address already in use 错误，且内核不能被正确启动

### ISSUE THREAD

**Issue by nekolsd** [MetaCubeX/mihomo#550]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta alpha-8c0168d darwin amd64 with go1.20.4 Fri May  5 07:28:14 UTC 2023 Use tags: with_gvisor

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
socks-port: 61533
port: 61522
mode: rule
ipv6: true
allow-lan: false
log-level: debug
external-controller: 127.0.0.1:9090
udp: true
profile:
  store-selected: true
global-client-fingerprint: chrome


dns:
  enable: true
  ipv6: true
  prefer-h3: true
  listen: 127.0.0.1:10530

  nameserver:
    - https://223.5.5.5/dns-query

  nameserver-policy:
    "rule-set:ProxyDomain": https://8.8.8.8/dns-query#代理
    "rule-set:DirectDomain,SamsungDomain": https://223.5.5.5/dns-query#DIRECT

proxy-providers:
  Airport:
    type: http
    url: 
    interval: 3600
    path: ./Airport.yaml
    health-check:
      enable: true
      interval: 600
      url: http://cp.cloudflare.com/generate_204

proxies:
  - name: 香港 REALITY 1
    type: vless
    server: 
    port: 443
    uuid: 
    tls: true
    udp: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    servername: 
    reality-opts:
      public-key: 
      short-id: 

  - name: 香港 REALITY 2
    type: vless
    server: 
    port: 443
    uuid: 
    tls: true
    udp: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    servername: 
    reality-opts:
      public-key: 
      short-id: 

  - name: 香港 REALITY 3
    type: vless
    server: 
    port: 443
    uuid: 
    tls: true
    udp: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    servername: 
    reality-opts:
      public-key: 
      short-id: 

  - name: 香港 Trojan
    type: trojan
    server: 
    port: 443
    password: 
    network: ws
    udp: true
    ws-opts:
      path: /
    smux:
      enabled: true
      protocol: smux
      padding: true
      statistic: true

  - name: 日本 REALITY
    type: vless
    server: 
    port: 443
    uuid: 
    tls: true
    udp: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    servername: 
    reality-opts:
      public-key: 
      short-id: 

  - name: 日本 Trojan
    type: trojan
    server: 
    port: 443
    password: 
    network: ws
    udp: true
    ws-opts:
      path: /
    smux:
      enabled: true
      protocol: smux
      padding: true
      statistic: true

  - name: 美国 REALITY
    type: vless
    server: 
    port: 443
    uuid: 
    tls: true
    udp: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    servername: 
    reality-opts:
      public-key: 
      short-id: 

  - name: 美国 SS
    type: ss
    server: 
    port: 52051
    cipher: 2022-blake3-aes-256-gcm
    password: 
    udp: true
    udp-over-tcp: true

proxy-groups:
  - name: 代理
    type: select
    proxies:
      - 香港集群
      - 日本集群
      - 美国集群
      - 机场

  - name: 香港集群
    type: select
    proxies:
      - 香港 REALITY 1
      - 香港 REALITY 2
      - 香港 REALITY 3
      - 香港 Trojan
      - Airport 香港
    url: https://cp.cloudflare.com/generate_204

  - name: 日本集群
    type: select
    proxies:
      - 日本 REALITY
      - 日本 Trojan
      - Airport 日本
    url: https://cp.cloudflare.com/generate_204
  
  - name: 美国集群
    type: select
    proxies:
      - 美国 REALITY
      - 美国 Relay
      - Airport 美国
    url: https://cp.cloudflare.com/generate_204

  - name: 苹果
    type: select
    proxies:
      - 代理
      - DIRECT

  - name: 微软
    type: select
    proxies:
      - 代理
      - DIRECT

  - name: SSH
    type: select
    proxies:
      - Airport 香港
      - Airport 日本
      - Airport 美国
      - 代理
      - DIRECT

  - name: 机场
    type: select
    use:
      - Airport

  - name: Airport 香港
    type: url-test
    use:
      - Airport
    filter: Hong Kong
    tolerance: 15
    lazy: true
    url: https://cp.cloudflare.com/generate_204
    interval: 120

  - name: Airport 日本
    type: url-test
    use:
      - Airport
    filter: Japan
    tolerance: 15
    lazy: true
    url: https://cp.cloudflare.com/generate_204
    interval: 120

  - name: Airport 美国
    type: url-test
    use:
      - Airport
    filter: United States
    tolerance: 30
    lazy: true
    url: https://cp.cloudflare.com/generate_204
    interval: 120
  
  - name: 美国 Relay
    type: relay
    proxies:
      - Airport 美国
      - 美国 SS

rule-providers:
  ProxyDomain:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/ProxyDomain.yaml
    interval: 86400

  MicrosoftDomain:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/MicrosoftDomain.yaml
    interval: 10800

  AppleDomain:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/AppleDomain.yaml
    interval: 10800

  DirectDomain:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/DirectDomain.yaml
    interval: 10800

  SamsungDomain:
    type: http
    behavior: domain
    url: 
    path: ./ruleset/SamsungDomain.yaml
    interval: 10800

  ChinaCIDR:
    type: http
    behavior: ipcidr
    url: 
    path: ./ruleset/ChinaCIDR.yaml
    interval: 10800

  LANCIDR:
    type: http
    behavior: ipcidr
    url: 
    path: ./ruleset/LANCIDR.yaml
    interval: 86400

rules:
  - RULE-SET, ProxyDomain, 代理

  - RULE-SET, MicrosoftDomain, 微软
  - RULE-SET, AppleDomain, 苹果

  - RULE-SET, DirectDomain, DIRECT
  - RULE-SET, SamsungDomain, DIRECT

  - DST-PORT, 60000, SSH
  - DST-PORT, 22, SSH

  - RULE-SET, ChinaCIDR, DIRECT
  - RULE-SET, LANCIDR, DIRECT

  - MATCH, 代理
```

### Clash log

```shell
time="2023-05-05T17:44:57.066980471Z" level=info msg="Start initial configuration in progress"
time="2023-05-05T17:44:57.0672437Z" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2023-05-05T17:44:57.06734495Z" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2023-05-05T17:44:57.067401304Z" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2023-05-05T17:44:57.067500783Z" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2023-05-05T17:44:57.067573179Z" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2023-05-05T17:44:57.068121929Z" level=info msg="Geodata Loader mode: memconservative"
time="2023-05-05T17:44:57.068431252Z" level=info msg="Initial configuration complete, total time: 1ms"
time="2023-05-05T17:44:57.068505002Z" level=info msg="Sniffer is closed"
time="2023-05-05T17:44:57.068895367Z" level=error msg="Start DNS server error: listen udp 127.0.0.1:10530: bind: address already in use"
time="2023-05-05T17:44:57.069033752Z" level=error msg="External controller listen error: listen tcp 127.0.0.1:9090: bind: address already in use"
time="2023-05-05T17:44:57.06918469Z" level=error msg="Start HTTP server error: listen tcp 127.0.0.1:61522: bind: address already in use"
time="2023-05-05T17:44:57.069230835Z" level=error msg="Start HTTP server error: listen tcp 127.0.0.1:61522: bind: address already in use"
time="2023-05-05T17:44:57.069418908Z" level=error msg="Start SOCKS server error: listen tcp 127.0.0.1:61533: bind: address already in use"
time="2023-05-05T17:44:57.069633231Z" level=info msg="Start initial compatible provider SSH"
time="2023-05-05T17:44:57.06965896Z" level=info msg="Start initial compatible provider 代理"
time="2023-05-05T17:44:57.069643492Z" level=info msg="Start initial compatible provider 微软"
time="2023-05-05T17:44:57.069654013Z" level=info msg="Start initial compatible provider 美国集群"
time="2023-05-05T17:44:57.069657658Z" level=info msg="Start initial compatible provider 美国 Relay"
time="2023-05-05T17:44:57.069668596Z" level=info msg="Start initial compatible provider 香港集群"
time="2023-05-05T17:44:57.069670002Z" level=info msg="Start initial compatible provider 日本集群"
time="2023-05-05T17:44:57.069672033Z" level=info msg="Start initial compatible provider 苹果"
time="2023-05-05T17:44:57.069679013Z" level=info msg="Start initial provider Airport"
time="2023-05-05T17:44:57.072647658Z" level=info msg="Start initial compatible provider default"
time="2023-05-05T17:44:57.219640419Z" level=info msg="[TCP] clash.meta --> example.com:443 match Match using 代理[香港 REALITY 1]"
time="2023-05-05T17:44:57.228087398Z" level=info msg="[TCP] clash.meta --> example.com:443 match Match using 代理[香港 REALITY 1]"
time="2023-05-05T17:44:58.034896304Z" level=warning msg="[CacheFile] can't open cache file: timeout"
time="2023-05-05T17:44:58.035018387Z" level=info msg="Start initial provider ChinaCIDR"
time="2023-05-05T17:44:58.035268231Z" level=info msg="Start initial provider MicrosoftDomain"
time="2023-05-05T17:44:58.035440158Z" level=info msg="Start initial provider SamsungDomain"
time="2023-05-05T17:44:58.035793804Z" level=info msg="Start initial provider AppleDomain"
time="2023-05-05T17:44:58.035981252Z" level=info msg="Start initial provider LANCIDR"
time="2023-05-05T17:44:58.036900731Z" level=info msg="Start initial provider DirectDomain"
time="2023-05-05T17:44:58.036933179Z" level=info msg="Start initial provider ProxyDomain"
time="2023-05-05T17:44:58.28843547Z" level=debug msg="Health Checked 🇯🇵 Japan 01 : true 68 ms {uuid}"
time="2023-05-05T17:44:58.288639585Z" level=debug msg="Health Checking 🇯🇵 Japan 10 {uuid}"
time="2023-05-05T17:44:58.290822658Z" level=debug msg="Health Checked 🇯🇵 Japan 06 : true 83 ms {uuid}"
time="2023-05-05T17:44:58.290937502Z" level=debug msg="Health Checking 🇯🇵 Japan 07 {uuid}"
time="2023-05-05T17:44:58.293016095Z" level=debug msg="Health Checked 🇯🇵 Japan 03 : true 71 ms {uuid}"
time="2023-05-05T17:44:58.29320172Z" level=debug msg="Health Checking 🇯🇵 Japan 08 {uuid}"
time="2023-05-05T17:44:58.2988637Z" level=debug msg="Health Checked 🇯🇵 Japan 04 : true 69 ms {uuid}"
time="2023-05-05T17:44:58.298920522Z" level=debug msg="Health Checking 🇯🇵 Japan 09 {uuid}"
time="2023-05-05T17:44:58.299430002Z" level=debug msg="Health Checked 🇯🇵 Japan 02 : true 79 ms {uuid}"
time="2023-05-05T17:44:58.299510158Z" level=debug msg="Health Checking 🇯🇵 Japan 12 {uuid}"
time="2023-05-05T17:44:58.308284377Z" level=debug msg="Health Checked 🇯🇵 Japan 05 : true 70 ms {uuid}"
time="2023-05-05T17:44:58.308361877Z" level=debug msg="Health Checking 🇯🇵 Japan 11 {uuid}"
time="2023-05-05T17:44:58.310932033Z" level=debug msg="Health Checked 🇸🇬 Singapore 12 : true 114 ms {uuid}"
time="2023-05-05T17:44:58.311045262Z" level=debug msg="Health Checking 🇯🇵 Japan 13 {uuid}"
time="2023-05-05T17:44:58.312300835Z" level=debug msg="Health Checked 🇸🇬 Singapore 11 : true 120 ms {uuid}"
time="2023-05-05T17:44:58.312364325Z" level=debug msg="Health Checking 🇯🇵 Japan 14 {uuid}"
time="2023-05-05T17:44:58.332059012Z" level=debug msg="Health Checked 🇸🇬 Singapore 14 : true 114 ms {uuid}"
time="2023-05-05T17:44:58.334202814Z" level=debug msg="Health Checked 🇸🇬 Singapore 15 : true 116 ms {uuid}"
time="2023-05-05T17:44:58.357985835Z" level=debug msg="Health Checked 🇯🇵 Japan 07 : true 66 ms {uuid}"
time="2023-05-05T17:44:58.359289689Z" level=debug msg="Health Checked 🇯🇵 Japan 10 : true 70 ms {uuid}"
time="2023-05-05T17:44:58.364531252Z" level=debug msg="Health Checked 🇯🇵 Japan 08 : true 71 ms {uuid}"
time="2023-05-05T17:44:58.370560106Z" level=debug msg="Health Checked 🇯🇵 Japan 12 : true 70 ms {uuid}"
time="2023-05-05T17:44:58.373429741Z" level=debug msg="Health Checked 🇯🇵 Japan 09 : true 74 ms {uuid}"
time="2023-05-05T17:44:58.38022547Z" level=debug msg="Health Checked 🇯🇵 Japan 11 : true 71 ms {uuid}"
time="2023-05-05T17:44:58.381029429Z" level=debug msg="Health Checked 🇯🇵 Japan 14 : true 68 ms {uuid}"
time="2023-05-05T17:44:58.382695262Z" level=debug msg="Health Checked 🇯🇵 Japan 13 : true 71 ms {uuid}"
time="2023-05-05T17:44:58.382764533Z" level=debug msg="Finish A Health Checking {uuid}"
time="2023-05-05T17:45:11.252908382Z" level=warning msg="Clash shutting down"
```

### Description

这个错误是从 CMFA 最近一个版本的频繁异常发现的。

下载并在 termux 中运行 [clash.meta-android-arm64-alpha-8c0168d.gz](https://github.com/MetaCubeX/Clash.Meta/releases/download/Prerelease-Alpha/clash.meta-android-arm64-alpha-8c0168d.gz) ，发现 HTTP/SOCKS/DNS 以及外部控制端口全部出现 `bind: address already in use` 错误，但经过多次筛查，发现这四个端口并没有其他程序在占用。

进入 yacd 面板后发现代理/连接/日志/规则等页面全部空白，日志也停留在了 `Health Check` 检查的最后一步。
