### ISSUE TITLE
当proxy-groups嵌套，并且每个group的url-test interval相同，会根据嵌套关系按照顺序进行测试吗？

### ISSUE THREAD

**Issue by GeorgeRudd** [MetaCubeX/mihomo#596]
```yaml
  - name: 自动选择
    type: url-test
    proxies:  
      - A
      - B
    interval: 60
    lazy: false
    url: https://www.google.com/generate_204
        
  - name: A
    type: url-test
    proxies:
      - a1
      - a2
      - a3
    interval: 60
    lazy: false
    url: https://www.google.com/generate_204
    
  - name: B
    type: url-test
    proxies:
      - b1
      - b2
      - b3
    interval: 60
    lazy: false
    url: https://www.google.com/generate_204
```
这个配置，是不是 先分别找出A组和B组中延迟最低的，然后再单独比较A和B？

还是不按顺序？
