### ISSUE TITLE
[Bug] panic: invalid argument to Intn

### ISSUE THREAD

**Issue by tony-sung** [MetaCubeX/mihomo#642]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.15.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
# Port of HTTP(S) proxy server on the local end
port: 7890

# Port of SOCKS5 proxy server on the local end
socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS4(A)/SOCKS5 server on the same port
# mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
# bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: true

# RESTful web API listening address
external-controller: 0.0.0.0:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
external-ui: /usr/share/yacd/

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

proxy-groups:
  - name: PROXY
    type: select
    url: 'http://www.gstatic.com/generate_204'
    use:
      - GROUP_0
      - GROUP_1
      - GROUP_2
      - GROUP_3
      # - GROUP_4
      # - GROUP_5
      # - GROUP_6
      # - GROUP_7
      # - GROUP_8
      # - GROUP_9
      # - GROUP_10
      # - GROUP_11

####################################################################################################
proxy-providers:
  GROUP_0:
    type: file
    url: 'https://raw.githubusercontent.com/tony-sung/clash/main/subscription/0.yaml'
    interval: 3600
    path: subscription/0.yaml
    health-check:
      enable: true
      interval: 2000
      url: 'http://www.gstatic.com/generate_204'

  GROUP_1:
    type: file
    url: 'https://raw.githubusercontent.com/tony-sung/clash/main/subscription/1.yaml'
    interval: 3600
    path: subscription/1.yaml
    health-check:
      enable: true
      interval: 2000
      url: 'http://www.gstatic.com/generate_204'

  GROUP_2:
    type: file
    url: 'https://raw.githubusercontent.com/tony-sung/clash/main/subscription/2.yaml'
    interval: 3600
    path: subscription/2.yaml
    health-check:
      enable: true
      interval: 2000
      url: 'http://www.gstatic.com/generate_204'

  GROUP_3:
    type: file
    url: 'https://raw.githubusercontent.com/tony-sung/clash/main/subscription/3.yaml'
    interval: 3600
    path: subscription/3.yaml
    health-check:
      enable: true
      interval: 2000
      url: 'http://www.gstatic.com/generate_204'

  # GROUP_4:
  #   type: file
  #   url: 'https://raw.githubusercontent.com/tony-sung/clash/main/subscription/4.yaml'
  #   interval: 3600
  #   path: subscription/4.yaml
  #   health-check:
  #     enable: true
  #     interval: 2000
  #     url: 'http://www.gstatic.com/generate_204'
  
  # GROUP_5:
  #   type: file
  #   url: 'https://raw.githubusercontent.com/tony-sung/clash/main/subscription/5.yaml'
  #   interval: 3600
  #   path: subscription/5.yaml
  #   health-check:
  #     enable: true
  #     interval: 2000
  #     url: 'http://www.gstatic.com/generate_204'

  # GROUP_6:
  #   type: file
  #   url: 'https://raw.githubusercontent.com/tony-sung/clash/main/subscription/6.yaml'
  #   interval: 3600
  #   path: subscription/6.yaml
  #   health-check:
  #     enable: true
  #     interval: 2000
  #     url: 'http://www.gstatic.com/generate_204'

  # GROUP_7:
  #   type: file
  #   url: 'https://raw.githubusercontent.com/tony-sung/clash/main/subscription/7.yaml'
  #   interval: 3600
  #   path: subscription/7.yaml
  #   health-check:
  #     enable: true
  #     interval: 2000
  #     url: 'http://www.gstatic.com/generate_204'

  # GROUP_8:
  #   type: file
  #   url: 'https://raw.githubusercontent.com/tony-sung/clash/main/subscription/8.yaml'
  #   interval: 3600
  #   path: subscription/8.yaml
  #   health-check:
  #     enable: true
  #     interval: 2000
  #     url: 'http://www.gstatic.com/generate_204'

  # GROUP_9:
  #   type: file
  #   url: 'https://raw.githubusercontent.com/tony-sung/clash/main/subscription/9.yaml'
  #   interval: 3600
  #   path: subscription/9.yaml
  #   health-check:
  #     enable: true
  #     interval: 2000
  #     url: 'http://www.gstatic.com/generate_204'

  # GROUP_10:
  #   type: file
  #   url: 'https://raw.githubusercontent.com/tony-sung/clash/main/subscription/10.yaml'
  #   interval: 3600
  #   path: subscription/10.yaml
  #   health-check:
  #     enable: true
  #     interval: 2000
  #     url: 'http://www.gstatic.com/generate_204'
  
  # GROUP_11:
  #   type: file
  #   url: 'https://raw.githubusercontent.com/tony-sung/clash/main/subscription/11.yaml'
  #   interval: 3600
  #   path: subscription/11.yaml
  #   health-check:
  #     enable: true
  #     interval: 2000
  #     url: 'http://www.gstatic.com/generate_204'
####################################################################################################
rules:
  - geoip,lan,DIRECT,no-resolve
  - geoip,cn,DIRECT,no-resolve
  - geosite,category-ads-all,REJECT
  - geosite,google,GLOBAL
  - geosite,bing,GLOBAL
  - geosite,cn,DIRECT
  - match,GLOBAL
```

### Clash log

```shell
panic: invalid argument to Intn

goroutine 23857 [running]:
github.com/zhangyunhao116/fastrand.Intn(0xc001c7dbb0?)
        github.com/zhangyunhao116/fastrand@v0.3.0/fastrand.go:77 +0x5c
github.com/Dreamacro/clash/transport/vmess.(*httpConn).Write(0xc002a96390, {0xc000425400, 0x7c, 0x80})
        github.com/Dreamacro/clash/transport/vmess/http.go:55 +0x6b
github.com/Dreamacro/clash/transport/vless.(*Conn).sendRequest(0xc002fce3f0, {0xc00042b000, 0x56, 0x1000})
        github.com/Dreamacro/clash/transport/vless/conn.go:160 +0x7dc
github.com/Dreamacro/clash/transport/vless.(*Conn).Write(0xc002fce3f0, {0xc00042b000, 0x56, 0x1000})
        github.com/Dreamacro/clash/transport/vless/conn.go:63 +0x94
net/http.persistConnWriter.Write({0xc001c7dd67?}, {0xc00042b000?, 0xc001c7de58?, 0x5582558ec920?})
        net/http/transport.go:1781 +0x2f
bufio.(*Writer).Flush(0xc005d76600)
        bufio/bufio.go:628 +0x62
net/http.(*persistConn).writeLoop(0xc003a91c20)
        net/http/transport.go:2426 +0x1be
created by net/http.(*Transport).dialConn
        net/http/transport.go:1766 +0x173d
```

### Description

正常启动后，运行五分钟左右崩溃，旧版也是同样问题，半小时后重试，极大概率出现该问题
