### ISSUE TITLE
[Bug] VLESS reality下udp无法连接

### ISSUE THREAD

**Issue by Arxhexa** [MetaCubeX/mihomo#680]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

alpha-b0fed73

### What OS are you seeing the problem on?

Windows, Linux

### Clash config

```yaml
socks-port: 1080
allow-lan: true
mode: Rule
log-level: info

proxies:
  - {name: , server: , port: , reality-opts: {public-key: , short-id: }, client-fingerprint: chrome, type: vless, uuid: , tls: true, tfo: false, servername: , flow: xtls-rprx-vision, skip-cert-verify: false, udp: true}
proxy-groups:
  - name: Proxies
    type: select
    proxies:
      - 
rules:
  - MATCH,Proxies

仅测试使用
```

### Description

使用NatTypeTester检测udp连接状态，在VMess、Trojan、Wireguard协议下均可返回远端Public end，连接成功

VLESS协议下返回UdpBlocked

使用最新版本v2rayN及xray内核连接相同节点可以正常返回远端Public end

#641 似乎是相同的问题，但我没有测试SS协议是否仍然无法连接
