### ISSUE TITLE
[Bug] listeners中的节点，设置proxy到本地的socks5，提示  error: dial tcp 127.0.0.1:xxxxx: setsockopt: protocol not available

### ISSUE THREAD

**Issue by GeorgeRudd** [MetaCubeX/mihomo#682]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta alpha-b0fed73 linux amd64 with go1.21rc3 Tue Aug  1 09:32:47 UTC 2023 Use tags: with_gvisor

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890 # HTTP(S) 代理服务器端口
socks-port: 7891 # SOCKS5 代理端口
mixed-port: 10801 # HTTP(S) 和 SOCKS 代理混合端口
inbound-tfo: true
mode: rule
ipv6: true
log-level: debug
find-process-mode: always
allow-lan: false
geodata-mode: true
tcp-concurrent: true

external-controller: "0.0.0.0:12104"   #控制器监听地址
secret: "123" #控制器登录密码

proxies: 
  - name: "socks-12105"
    type: socks5
    server: "127.0.0.1"
    port: 12105
    username: 123
    password: 123
    # tls: true
    # fingerprint: xxxx
    # skip-cert-verify: true
    udp: true
    tfo: true
    # ip-version: ipv6



listeners:
  - name: "tuic-in-12115"
    proxy: "socks-12105"
    type: tuic
    port: 12115
    listen: "0.0.0.0"
    # rule: sub-rule-name1 # 默认使用 rules，如果未找到 sub-rule 则直接使用 rules
    # proxy: proxy # 如果不为空则直接将该入站流量交由指定proxy处理(当proxy不为空时，这里的proxy名称必须合法，否则会出错)
    # token:    # tuicV4填写（可以同时填写users）
    #   - TOKEN
    users:    # tuicV5填写（可以同时填写token）
      uuid: 123
    certificate: /ssl/domain/fullchain.cer
    private-key: /ssl/domain/key.key
    congestion-controller: bbr
    #  max-idle-time: 15000
    #  authentication-timeout: 1000
    alpn:
      - h3
    #  max-udp-relay-packet-size: 1500
    
    
rules:
  # - MATCH,socks
  - MATCH,REJECT
```

### Clash log

```shell
23-08-03 12:10:24[ warn ][TCP] dial socks-12105 [2409:xxxx]:56088 --> clients4.google.com:443 error: dial tcp 127.0.0.1:12105: setsockopt: protocol not available
23-08-03 12:10:24[ warn ][TCP] dial socks-12105 [2409:xxxx]:56088 --> clients4.google.com:443 error: dial tcp 127.0.0.1:12105: setsockopt: protocol not available
```

### Description

tuic节点没问题，若将``proxy: socks-12105"``注释掉，同时将``- MATCH,REJECT``改成DIRECT，可正常连接。
```
23-08-03 12:13:47[ info ][TCP] [2409:xxxx]:56088 --> www.google.com:443 match Match using DIRECT
```

用socks是想把流量交给xray处理。用http也是一样的报错。

我的vps是ovz的nat机器，公网ipv4是共用的，可用端口从12101到12020。有公网ipv6。

```
root@nat-sg:~# ip add
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/void 
    inet 127.0.0.1/32 scope host venet0
       valid_lft forever preferred_lft forever
    inet 10.37.120.121/24 brd 10.37.120.255 scope global venet0:0
       valid_lft forever preferred_lft forever
    inet6 2403:xxxx::1/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 2403:xxxx::2/64 scope global 
       valid_lft forever preferred_lft forever
3: WARP: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1420 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none 
    inet 172.16.0.2/32 scope global WARP
       valid_lft forever preferred_lft forever
    inet6 2606:xxxx/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::dd70:e2cc:6873:ab10/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
```
