### ISSUE TITLE
[配置询问] 策略组嵌套时的延迟测试与配置

### ISSUE THREAD

**Issue by scegg** [MetaCubeX/mihomo#713]
如果已有两个proxy-group，每个proxy-group均为load-balance且内都配置了url用于测速。再新增一个proxy-group，选择上述两个proxy-group做fallback。那么后者是否可以不指定url而直接使用前两者内测速的结果？

例如：
```
- name: TopGroup
  type: fallback
  disable-udp: false
  proxies:
  - Group1
  - Group2
- name: Group1
  type: load-balance
  disable-udp: false
  url: http://fuck.some.ass/
  interval: 300
  proxies:
  - Group1A
  - Group1B
  strategy: round-robin
- name: Group2
  type: load-balance
  disable-udp: false
  url: http://fuck.another.ass/
  interval: 300
  proxies:
  - Group2A
  - Group2B
  strategy: round-robin
```
在此例中，TopGroup的fallback会基于Group1、Group2内的测速结果，还是使用了默认的url地址重新进行测速呢？谢谢。
