### ISSUE TITLE
tuic协议 udp类型的dns无法通过

### ISSUE THREAD

**Issue by GeorgeRudd** [MetaCubeX/mihomo#739]
clash.meta-windows-amd64-alpha-7286391

udp类型的dns无法走tuic代理

<details>
  <summary>配置文件</summary>

  ```yaml
external-ui: yacd-meta

tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-detect-interface: true
  strict-route: true 
      
proxy-groups:

  - name: 节点选择
    type: select
    proxies:  
      - tuic
      - vmess

proxies:
  - name: tuic
    server: "ip"
    port: port
    type: tuic
    uuid: uuid
    password: password
    alpn: [h3]
    disable-sni: false
    reduce-rtt: false
    congestion-controller: bbr # Available: "cubic", "new_reno", "bbr". Default: "cubic"
    fast-open: true
    skip-cert-verify: false
    sni: domain.com
    udp-over-stream: true

  - name: vmess
    type: vmess
    server: ip
    port: port
    uuid: uuid
    alterId: 0
    cipher: auto
    network: grpc
    tls: true
    udp: true
    xudp: true
    tfo: true
    ip-version: ipv4
    skip-cert-verify: false
    client-fingerprint: chrome
    servername: servername.com
    grpc-opts:
      grpc-service-name: "name"   
    
port: 7890 # HTTP(S) 代理服务器端口
socks-port: 7891 # SOCKS5 代理端口
mixed-port: 10801 # HTTP(S) 和 SOCKS 代理混合端口
inbound-tfo: true
mode: rule
ipv6: true
log-level: debug
find-process-mode: always
allow-lan: false
geodata-mode: true
tcp-concurrent: true
    
rules:
  
  - AND,((NETWORK,UDP),(DST-PORT,443)),REJECT
  - DOMAIN,services.googleapis.cn,节点选择
  - DOMAIN-SUFFIX,jike.info,节点选择
  - GEOSITE,cn,DIRECT
  - GEOSITE,private,DIRECT
  - GEOSITE,geolocation-!cn,节点选择
  
  - GEOIP,cn,DIRECT
  - GEOIP,private,DIRECT
  - MATCH,节点选择
  - MATCH,REJECT
      
dns:
  enable: true
  enhanced-mode: fake-ip
  use-hosts: true
  nameserver-policy:
    'geosite:cn': 
         - 223.5.5.5
    'geosite:private': 
         - 223.5.5.5      
  nameserver:
    # - '1.1.1.1#节点选择'
    - '8.8.8.8#节点选择'
  proxy-server-nameserver:
     - 223.5.5.5  
  fake-ip-filter:
    #https://github.com/vernesong/OpenClash/blob/master/luci-app-openclash/root/etc/openclash/custom/openclash_custom_fake_filter.list
    #LAN
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    #放行NTP服务
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time-ios.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    #放行网易云音乐
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    #百度音乐
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    #酷狗音乐
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    #酷我音乐
    - '*.kuwo.cn'
    #JOOX音乐
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    #QQ音乐
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    #虾米音乐
    - '*.xiami.com'
    #咪咕音乐
    - '*.music.migu.cn'
    - 'music.migu.cn'
    #win10本地连接检测
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    #QQ登录
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    - '+.qq.com'
    - '+.tencent.com'
    #Game
    #Nintendo Switch
    - '+.srv.nintendo.net'
    - '*.n.n.srv.nintendo.net'
    #Sony PlayStation
    - '+.stun.playstation.net'
    #Microsoft Xbox
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    - 'xbox.*.microsoft.com'
    - 'xnotify.xboxlive.com'
    #Wotgame
    - '+.battlenet.com.cn'
    - '+.wotgame.cn'
    - '+.wggames.cn'
    - '+.wowsgame.cn'
    - '+.wargaming.net'
    #Golang
    - 'proxy.golang.org'
    #STUN
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    #Linksys Router
    - 'heartbeat.belkin.com'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    #ASUS Router
    - '*.router.asus.com'
    #Apple Software Update Service
    - 'mesu.apple.com'
    - 'swscan.apple.com'
    - 'swquery.apple.com'
    - 'swdownload.apple.com'
    - 'swcdn.apple.com'
    - 'swdist.apple.com'
    #Google
    - 'lens.l.google.com'
    - 'stun.l.google.com'
    - 'na.b.g-tun.com'
    #Netflix
    - '+.nflxvideo.net'
    #FinalFantasy XIV Worldwide Server & CN Server
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com' 
    - '*.ff14.sdo.com'
    - 'ff.dorado.sdo.com'
    #Bilibili
    - '*.mcdn.bilivideo.cn'
    #Disney Plus
    - '+.media.dssott.com'
    #shark007 Codecs 
    - 'shark007.net'
    #Mijia
    - 'Mijia Cloud'
    #招商银行
    - '+.cmbchina.com'
    - '+.cmbimg.com'
    #AdGuard
    - 'local.adguard.org'
    #迅雷
    - '+.sandai.net'
    - '+.n0808.com'
  
profile:
  # 存储 select 选择记录
  store-selected: true
  
  # 持久化 fake-ip
  store-fake-ip: false
```
</details>

<details>
  <summary>tuic 日志</summary>
  
```
23-09-08 18:23:47[ info ][TCP] 127.0.0.1:53127(msedge.exe) --> vpsgo.com:443 match GeoIP(cn) using DIRECT
23-09-08 18:23:47[ debug ][DNS] vpsgo.com --> [81.68.142.26], from udp://8.8.8.8:53
23-09-08 18:23:46[ debug ][DNS] vpsgo.com --> [], from udp://8.8.8.8:53
23-09-08 18:23:46[ debug ][DNS] resolve vpsgo.com from udp://8.8.8.8:53
23-09-08 18:23:46[ debug ][DNS] vpsgo.com --> 81.68.142.26
23-09-08 18:23:46[ debug ][DNS] vpsgo.com --> [81.68.142.26], from udp://8.8.8.8:53
23-09-08 18:23:46[ debug ][DNS] resolve vpsgo.com from udp://8.8.8.8:53
23-09-08 18:23:46[ info ][TCP] 127.0.0.1:53108(msedge.exe) --> vpsgo.com:80 match Match using 节点选择[tuic]
23-09-08 18:23:46[ info ][TCP] 127.0.0.1:53105(msedge.exe) --> vpsgo.com:443 match Match using 节点选择[tuic]
23-09-08 18:23:46[ debug ][DNS] resolve vpsgo.com from udp://8.8.8.8:53
23-09-08 18:23:46[ debug ][DNS] resolve vpsgo.com error: couldn't find ip
23-09-08 18:23:46[ debug ][DNS] resolve vpsgo.com error: couldn't find ip
23-09-08 18:23:44[ debug ][DNS] vpsgo.com --> [], from udp://8.8.8.8:53
23-09-08 18:23:44[ debug ][DNS] resolve vpsgo.com from udp://8.8.8.8:53
23-09-08 18:23:42[ debug ][DNS] vpsgo.com --> [], from udp://8.8.8.8:53
23-09-08 18:23:41[ debug ][DNS] resolve vpsgo.com from udp://8.8.8.8:53
23-09-08 18:23:41[ debug ][DNS] resolve vpsgo.com from udp://8.8.8.8:53
```
</details>
将udp-over-stream: true注释，同样错误

将- '8.8.8.8#节点选择' 改成 - 'tcp://8.8.8.8#节点选择，正常

<details>
  <summary>vmess 是正常的 vmess 日志</summary>
 
```
23-09-08 18:25:16[ info ][TCP] 127.0.0.1:53394(msedge.exe) --> www.vpsgo.com:443 match GeoIP(cn) using DIRECT
23-09-08 18:25:16[ debug ][DNS] www.vpsgo.com --> [81.68.142.26], from udp://8.8.8.8:53
23-09-08 18:25:16[ debug ][DNS] www.vpsgo.com --> [], from udp://8.8.8.8:53
23-09-08 18:25:15[ debug ][DNS] resolve www.vpsgo.com from udp://8.8.8.8:53
23-09-08 18:25:15[ debug ][DNS] resolve www.vpsgo.com from udp://8.8.8.8:53
23-09-08 18:25:15[ debug ][DNS] www.vpsgo.com --> 81.68.142.26
23-09-08 18:25:15[ debug ][DNS] www.vpsgo.com --> [81.68.142.26], from udp://8.8.8.8:53
23-09-08 18:25:15[ debug ][DNS] www.vpsgo.com --> [], from udp://8.8.8.8:53
23-09-08 18:25:15[ debug ][DNS] resolve www.vpsgo.com from udp://8.8.8.8:53
23-09-08 18:25:15[ debug ][DNS] resolve www.vpsgo.com from udp://8.8.8.8:53
23-09-08 18:25:15[ info ][TCP] 127.0.0.1:53386(msedge.exe) --> vpsgo.com:443 match GeoIP(cn) using DIRECT
23-09-08 18:25:15[ debug ][DNS] vpsgo.com --> [81.68.142.26], from udp://8.8.8.8:53
23-09-08 18:25:15[ debug ][DNS] vpsgo.com --> [], from udp://8.8.8.8:53
23-09-08 18:25:14[ debug ][DNS] resolve vpsgo.com from udp://8.8.8.8:53
23-09-08 18:25:14[ debug ][DNS] resolve vpsgo.com from udp://8.8.8.8:53
23-09-08 18:25:14[ debug ][DNS] vpsgo.com --> 81.68.142.26
23-09-08 18:25:14[ debug ][DNS] vpsgo.com --> [81.68.142.26], from udp://8.8.8.8:53
23-09-08 18:25:13[ debug ][DNS] vpsgo.com --> [], from udp://8.8.8.8:53
23-09-08 18:25:13[ debug ][DNS] resolve vpsgo.com from udp://8.8.8.8:53
23-09-08 18:25:13[ debug ][DNS] resolve vpsgo.com from udp://8.8.8.8:53
```

</details>
