### ISSUE TITLE
[Feature] 帮忙补充 eBPF auto-redir 模式的使用文档

### ISSUE THREAD

**Issue by lvii** [MetaCubeX/mihomo#763]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

Hi

目前 wiki 中没有关于 eBPF `auto-redir` 模式的使用介绍

在 openwrt 路由器上面，使用 `clash meta 1.15.1` 使用下面配置，运行没有报错

``` yaml
# ebpf 配置
ebpf:
  # redirect 模式，仅支持 TCP
  auto-redir:
    - eth0
tun:
  enable: false
  stack: system
```

有以下几点疑问：

- 仅使用 **透明代理** 模式 **未启用** `tun` 上面配置的使用方法是否正确
- 重启 clash debug 日志 **没有** ebpf 相关输出，请问是否有其他命令、工具查看效果

----

不知是否能实现类似 https://github.com/daeuniverse/dae 将 **直连** 的流量通过 eBPF 处理。

提高转发效率（[benchmark 数据表格](https://docs.google.com/spreadsheets/d/1UaWU6nNho7edBNjNqC8dfGXLlW0-cm84MM7sH6Gp7UE/edit?usp=sharing)）

![CleanShot 2023-09-23 at 08 49 42](https://github.com/MetaCubeX/Clash.Meta/assets/309721/26768acc-6d4b-4e33-96e7-7d0f47cf2fee)

感谢!
