### ISSUE TITLE
[Bug] 配置加密DNS疑似存在内存泄漏问题

### ISSUE THREAD

**Issue by giveup** [MetaCubeX/mihomo#785]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta alpha-5ff44730 linux arm64 with go1.21.1 Fri Oct  6 16:29:41 UTC 2023

### Clash config

```yaml
dns:
  enable: true
  listen: 127.0.0.1:1053
  ipv6: true
  default-nameserver:
    - quic://223.5.5.5
    - quic://223.6.6.6
  nameserver:
    - quic://223.5.5.5          
    - quic://223.6.6.6
  fallback:
    - quic://223.5.5.5
    - quic://223.6.6.6
  prefer-h3: true
  use-hosts: true
  enhanced-mode: redir-host
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
```

### Description

如果配置了加密DNS，包括DOH/DOQ/DOT，meta面板会看到clash占用内存较高。
![WX20231008-220009@2x](https://github.com/MetaCubeX/Clash.Meta/assets/2897585/0564e0e2-82e5-4079-a33f-9787a52f6ded)
正常情况下（刚启动时）的内存占用
![WX20231008-221142@2x](https://github.com/MetaCubeX/Clash.Meta/assets/2897585/d925d402-e09a-45c6-8f1f-e244d26d44e1)
通过观察heap，发现是DNS相关的库分配内存较多
![WX20231008-220229@2x](https://github.com/MetaCubeX/Clash.Meta/assets/2897585/51345f6c-577b-4c0e-a13e-0edfe389ae11)
光看图片可能感觉内存占用也没这么夸张，这是因为之前崩溃的时候没有保留任何日志，所以无法得知最高峰时，内存占用到底是多少。
配置为UDP DNS的情况

![WX20231008-222105@2x](https://github.com/MetaCubeX/Clash.Meta/assets/2897585/8ea97b73-812d-4c86-aca0-f0181942397b)
![WX20231008-222128@2x](https://github.com/MetaCubeX/Clash.Meta/assets/2897585/b684af3c-9d8d-40f2-9c84-049df117591d)

附件是gz格式，分别为使用加密DNS和使用普通UDP DNS的heap
[clash_with_enc_dns_pb.gz.txt](https://github.com/MetaCubeX/Clash.Meta/files/12840917/clash_with_enc_dns_pb.gz.txt)
[clash_without_enc_dns_profile.pb.gz.txt](https://github.com/MetaCubeX/Clash.Meta/files/12840920/clash_without_enc_dns_profile.pb.gz.txt)
