### ISSUE TITLE
vless+ws 无法使用

### ISSUE THREAD

**Issue by delphinuz** [MetaCubeX/mihomo#84]
请问有人成功吗？

Clash.Meta版本： Clash Meta v1.11.1 windows amd64 with go1.18.2

按下面的方式，cash.meta可成功运行，但节点 "vless-ws" 没有速度, 也无法连线。

```
  - name: "vless-ws"
    type: vless
    server: SERVER
    port: 443
    uuid: UUID
    udp: true
    network: ws
    servername: DOMAIN # priority over wss host
    # skip-cert-verify: true
    ws-path: /PATH
    ws-headers:
      Host: DOMAIN
```

如果写为以下方式，则 clash.meta无法运行。

`- {name:  "vless-ws", server: SERVER, port: 443, type: vless, uuid: UUID, network: ws, servername: DOMAIN, ws-path: /PATH, ws-headers: {Host: DOMAIN}, udp: true} 
`
