### ISSUE TITLE
[Features] Add support nameserver-policy against proxy-groups

### ISSUE THREAD

**Issue by malikshi** [MetaCubeX/mihomo#863]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

Hi I am using servers with smart DNS to access netflix, etc for certain region. I setup mihomo for mixed node/proxies/proxy-groups. If we don't set nameserver-policy per rule-set, geosite they're gone astray since nameserver and fallback will be randomized resolved.
current set
```yaml
  nameserver-policy:
    geosite:netflix: 8.8.8.8#netflixproxy
```

### Possible Solution

I Want requests features for 
```yaml
  nameserver-policy:
    proxy-groups:netflixproxy: 8.8.8.8#netflixproxy
    proxies:singleproxy: 8.8.8.8#singleproxy
```
For Someone That using smartdns it's very Useful Since we only Need setup proxies, proxy-groups DNS instead listing geosites. You May Found this features Like dns rules in sing-box

**Comment by Paulgudring** [comment]
try rule-set. I have the same original demand as you. But I found that rule-set is capable to solve the problem, it is a existing solution. rule-set as below:

```yaml
geosite, netflix
geosite, hulu
#……
domain #……
```

your config is as below:

```
rule-provider:
  netflixproxy:
    url: ……
    path: ……

dns:
  #……
  nameserver-policy:
    rule-set: netflixproxy: 8.8.8.8#specific-proxy-group

rule:
  - RULE-SET, netflixproxy, specific-proxy-group
```

note: only domain and geo rules of rule-set are supported in nameserver-policy. wish to see more types of rule supported in the future (like logic rule or even process rule).
