### ISSUE TITLE
[Bug] wireguard无法连接，不知道是不是我的配置有问题

### ISSUE THREAD

**Issue by ghost** [MetaCubeX/mihomo#865]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

最新

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
- { name: 'xxx', type: wireguard, server: xxxx, port: xxx, ip: xxx, private-key: xxx, public-key: xxx, preshared-key: xxx, dns: [xxx], udp: true}
```

### Description

使用wireguard客户端可以连接，但是使用clash不行

**Comment by skill7899** [comment]
我跟你一模一样的问题。。。我一直以为是我自已的问题，我用stash也可以连接上，用clash.meta连不了，sing-box也是连不上，我看了sing-box的配置和clash.meta一样的，估计他们用的同样的代码。我的macos m1，手机用stash没问题，sing-box也不行

**Comment by skill7899** [comment]
我也只是单纯的挂clash.meta连接家里的wg，然后分流直接IP访问的网。不是套娃

**Comment by snakem982** [comment]
注意字段要写对啊

``` yaml
  - name: "wg"
    type: wireguard
    private-key: eCtXsJZ27+4PbhDkHnB923tkUn2Gj59wZw5wFA75MnU=
    server: 162.159.192.1
    port: 2480
    ip: 172.16.0.2
    ipv6: fd01:5ca1:ab1e:80fa:ab85:6eea:213f:f4a5
    public-key: Cr8hWlKvtDt7nrvf+f0brNQQzabAqrjfBvas9pmowjo=
    allowed-ips: ['0.0.0.0/0']
    # pre-shared-key: 31aIhAPwktDGpH4JDhA8GNvjFXEf/a6+UaQRyOAiyfM=
    # reserved: [209,98,59]  # 字符串格式也是合法的，如"U4An"
    udp: true
    # mtu: 1408
    # dialer-proxy: "ss1"  # 一个出站代理的标识。当值不为空时，将使用指定的 proxy/proxy-group 发出连接
    # remote-dns-resolve: true # 强制dns远程解析，默认值为false
    # dns: [ 1.1.1.1, 8.8.8.8 ] # 仅在remote-dns-resolve为true时生效
```

**Comment by snakem982** [comment]
我贴一个我的配置给你参考下，它是可以工作的

```yaml
 - {"name":"🇺🇸US_104","server":"162.159.192.15","type":"wireguard","country":"🇺🇸US","port":1018,"udp":true,"ip":"172.16.0.2","ipv6":"2606:4700:110:82ef:29f3:592e:ed00:442c","public-key":"bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=","private-key":"qGxQqQKdNfvV15ozIuTRjd0IFfN/yfbBvWe9ZEjvcUU=","mtu":1280,"dns":["8.8.8.8","1.1.1.1"],"allowed-ips":["0.0.0.0/0","::/0"],"remote-dns-resolve":true}
 - {"name":"🇺🇸US_105","server":"162.159.192.162","type":"wireguard","country":"🇺🇸US","port":945,"udp":true,"ip":"172.16.0.2","ipv6":"2606:4700:110:82ef:29f3:592e:ed00:442c","public-key":"bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=","private-key":"qGxQqQKdNfvV15ozIuTRjd0IFfN/yfbBvWe9ZEjvcUU=","mtu":1280,"dns":["8.8.8.8","1.1.1.1"],"allowed-ips":["0.0.0.0/0","::/0"],"remote-dns-resolve":true}
```

**Comment by skill7899** [comment]
> 我贴一个我的配置给你参考下，它是可以工作的
> 
> ```yaml
>  - {"name":"🇺🇸US_104","server":"162.159.192.15","type":"wireguard","country":"🇺🇸US","port":1018,"udp":true,"ip":"172.16.0.2","ipv6":"2606:4700:110:82ef:29f3:592e:ed00:442c","public-key":"bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=","private-key":"qGxQqQKdNfvV15ozIuTRjd0IFfN/yfbBvWe9ZEjvcUU=","mtu":1280,"dns":["8.8.8.8","1.1.1.1"],"allowed-ips":["0.0.0.0/0","::/0"],"remote-dns-resolve":true}
>  - {"name":"🇺🇸US_105","server":"162.159.192.162","type":"wireguard","country":"🇺🇸US","port":945,"udp":true,"ip":"172.16.0.2","ipv6":"2606:4700:110:82ef:29f3:592e:ed00:442c","public-key":"bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=","private-key":"qGxQqQKdNfvV15ozIuTRjd0IFfN/yfbBvWe9ZEjvcUU=","mtu":1280,"dns":["8.8.8.8","1.1.1.1"],"allowed-ips":["0.0.0.0/0","::/0"],"remote-dns-resolve":true}
> ```

机场的我测了可以的，家里的就不行，我看好像不是我个例，有不少人有这种问题。同样的配置在stash也是可以的。

**Comment by skill7899** [comment]
> > 我也只是单纯的挂clash.meta连接家里的wg，然后分流直接IP访问的网。不是套娃
> 
> 我之前也遇到过，似乎需要重启clash客户端，或者把server配置成域名，很奇怪，你可以重启下clash试试

试过了，无论是域名还是IP都不行。Handshake 失败

**Comment by skill7899** [comment]
> > > > 我也只是单纯的挂clash.meta连接家里的wg，然后分流直接IP访问的网。不是套娃
> > > 
> > > 
> > > 我之前也遇到过，似乎需要重启clash客户端，或者把server配置成域名，很奇怪，你可以重启下clash试试
> > 
> > 
> > 试过了，无论是域名还是IP都不行。Handshake 失败
> 
> 重启clash试试，要还不行我就不知道了。服务模式，或者tun模式开启，试试

我电脑都重启了~各种模式都试了ORZ

**Comment by xishang0128** [comment]
如果你的dns模式为fakeip,则必须开启`remote-dns-resolve`,否则域名服务会无法联通

**Comment by skill7899** [comment]
> 如果你的dns模式为fakeip,则必须开启`remote-dns-resolve`,否则域名服务会无法联通

我直接都用ip了，链接不上，握手不成功。

**Comment by skill7899** [comment]
> > > 如果你的dns模式为fakeip,则必须开启 `remote-dns-resolve`,否则域名服务会无法联通
> > 
> > 
> > 我直接都用ip了，链接不上，握手不成功。
> 
> 还有一种可能，你ip被墙了

我是家里的IPV6，用WG原生可以直接连上的。。不是机场

**Comment by skill7899** [comment]
> 如果你的dns模式为fakeip,则必须开启`remote-dns-resolve`,否则域名服务会无法联通

我现在是连接不上，握手失败。还没有到访问，我访问都是IP的家里的IP。

**Comment by sf467** [comment]
用12月22号的alpha内核，电脑上可以访问wireguard节点
相同的配置，在11月3号的alpha版本clash meta for android上就连不上，报错也是握手失败

**Comment by skill7899** [comment]
有没有可能是V6的问题，因为我家里没有V4

**Comment by typenoob** [comment]
> 用12月22号的alpha内核，电脑上可以访问wireguard节点 相同的配置，在11月3号的alpha版本clash meta for android上就连不上，报错也是握手失败

同同同

**Comment by Arstman** [comment]
这个里是dns查询的问题， wireguard要先保证查询的dns没有被污染， 所以首要默认的nameserver应该是cf或者google的，这里有个参考配置

```yaml
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.2/dns-query
    - https://1.0.0.2/dns-query
    - https://9.9.9.9/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
 ```

参考： https://www.sainnhe.dev/post/best-practice-for-dns-in-clash/
