### ISSUE TITLE
[Bug] 1.17版本tuic节点不通，其他的（vless ws）是好的

### ISSUE THREAD

**Issue by msbtx** [MetaCubeX/mihomo#873]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta v1.17.0 linux arm64 with go1.21.4 Sun Dec  3 01:01:49 UTC 2023 Use tags: with_gvisor

### Mihomo config

```yaml
proxies:
  - {name: 🇺🇸 US_DV, server: xxxx, port: 443, client-fingerprint: safari, type: vless, uuid: xxx, tls: true, tfo: false, servername: xxx, skip-cert-verify: false, network: ws, ws-opts: {path: /xxx, headers: {Host: xxx}}, udp: true}
  - {name: 🇯🇵 JP_GC, server: xxx, port: 443, type: tuic, uuid: xxx, password: "xxx", ip: xxx, alpn: [h3], udp-relay-mode: native, disable-sni: true, reduce-rtt: false, skip-cert-verify: false, request-timeout:8000, fast-open: false, max-udp-relay-packet-size: 2944, max-open-streams: 32}

port: 3333
socks-port: 23456
redir-port: 23457
allow-lan: true
mode: rule
log-level: error
external-controller: 192.168.20.1:9990
experimental:
  ignore-resolve-fail: true
external-ui: dashboard
secret: "clash"
profile:
  store-selected: true
  store-fake-ip: true
ipv6: false

hosts:
  services.googleapis.cn: 74.125.193.94
  time.android.com: 203.107.6.88
  ipv6.msftconnecttest.com: 2a01:111:2003::52 #勿删
  www.msftconnecttest.com: 13.107.4.52 #勿删
  
routing-mark: 255

dns:
  enable: true
  ipv6: false
  listen: :23453
  enhanced-mode: redir-host
  prefer-h3: true
  nameserver-policy:
    "geosite:cn": 
      - 119.29.29.29
      - 223.5.5.5
    "geosite:netflix": 
      - 8.8.8.8#♻️ 手动切换3
      - 1.1.1.1#♻️ 手动切换3
  nameserver:
    - 8.8.8.8#♻️ 手动切换2
    - 1.1.1.1#♻️ 手动切换2

tproxy: true
tproxy-port: 23458
```

### Mihomo log

```shell
23-12-05 22:09:43[ debug ][DNS] resolve edge-mqtt.facebook.com from udp://1.1.1.1:53
23-12-05 22:09:43[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6852 --> 91.108.56.102:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:43[ debug ][DNS] cache hit for edge-mqtt.facebook.com., expire at 2023-12-05 22:09:37
23-12-05 22:09:43[ debug ][Rule] use default rules
23-12-05 22:09:43[ debug ][Rule] use default rules
23-12-05 22:09:43[ warn ][TCP] dial 🔍 谷歌服务 (match DomainKeyword/google) 192.168.20.33:6850 --> mtalk.google.com:5228 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match IPCIDR/35.184.0.0/13) 192.168.20.33:6851 --> a.nel.cloudflare.com:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6849 --> 91.108.56.102:80 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6848 --> 91.108.56.102:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6849 --> 91.108.56.102:80 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match IPCIDR/35.184.0.0/13) 192.168.20.33:6851 --> a.nel.cloudflare.com:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match DomainKeyword/google) 192.168.20.33:6850 --> mtalk.google.com:5228 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6849 --> 91.108.56.102:80 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6848 --> 91.108.56.102:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match IPCIDR/35.184.0.0/13) 192.168.20.33:6851 --> a.nel.cloudflare.com:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6848 --> 91.108.56.102:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6849 --> 91.108.56.102:80 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match DomainKeyword/google) 192.168.20.33:6850 --> mtalk.google.com:5228 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match DomainKeyword/google) 192.168.20.33:6850 --> mtalk.google.com:5228 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6848 --> 91.108.56.102:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match IPCIDR/35.184.0.0/13) 192.168.20.33:6851 --> a.nel.cloudflare.com:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6849 --> 91.108.56.102:80 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6848 --> 91.108.56.102:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match DomainKeyword/google) 192.168.20.33:6850 --> mtalk.google.com:5228 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match IPCIDR/35.184.0.0/13) 192.168.20.33:6851 --> a.nel.cloudflare.com:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match DomainKeyword/google) 192.168.20.33:6850 --> mtalk.google.com:5228 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6849 --> 91.108.56.102:80 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match IPCIDR/35.184.0.0/13) 192.168.20.33:6851 --> a.nel.cloudflare.com:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6848 --> 91.108.56.102:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match DomainKeyword/google) 192.168.20.33:6850 --> mtalk.google.com:5228 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match IPCIDR/35.184.0.0/13) 192.168.20.33:6851 --> a.nel.cloudflare.com:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6849 --> 91.108.56.102:80 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6848 --> 91.108.56.102:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match DomainKeyword/google) 192.168.20.33:6850 --> mtalk.google.com:5228 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 🔍 谷歌服务 (match IPCIDR/35.184.0.0/13) 192.168.20.33:6851 --> a.nel.cloudflare.com:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6849 --> 91.108.56.102:80 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ debug ]Closing TProxy local conn... lAddr=192.168.20.33:63995 rAddr=38.90.226.47:53535
23-12-05 22:09:42[ debug ][Rule] use default rules
23-12-05 22:09:42[ debug ]TProxy local conn listener exit.. rAddr=38.90.226.47:53535 lAddr=192.168.20.33:63995
23-12-05 22:09:42[ warn ][TCP] dial 📲 聊天软件 (match IPCIDR/91.108.0.0/16) 192.168.20.33:6848 --> 91.108.56.102:443 error: INTERNAL_ERROR (local): write udp [::]:50656->109.107.137.72:443: sendmsg: invalid argument
23-12-05 22:09:42[ debug ]Closing TProxy local conn... lAddr=192.168.20.33:57738 rAddr=172.217.12.142:443
23-12-05 22:09:42[ debug ]TProxy local conn listener exit.. rAddr=172.217.12.142:443 lAddr=192.168.20.33:57738
23-12-05 22:09:42[ debug ][Rule] use default rules
23-12-05 22:09:42[ debug ][Rule] use default rules
23-12-05 22:09:42[ debug ][Rule] use default rules
23-12-05 22:09:42[ debug ]Closing TProxy local conn... lAddr=192.168.20.33:63993 rAddr=38.90.226.47:53535
23-12-05 22:09:42[ debug ]TProxy local conn listener exit.. rAddr=38.90.226.47:53535 lAddr=192.168.20.33:63993
23-12-05 22:09:42[ debug ]Closing TProxy local conn... lAddr=192.168.20.33:50234 rAddr=142.250.72.238:443
23-12-05 22:09:42[ debug ]TProxy local conn listener exit.. rAddr=142.250.72.238:443 lAddr=192.168.20.33:50234
23-12-05 22:09:42[ debug ]Closing TProxy local conn... lAddr=192.168.20.33:56133 rAddr=142.250.68.42:443
23-12-05 22:09:42[ debug ]Closing TProxy local conn... lAddr=192.168.20.33:61730 rAddr=142.250.176.4:443
23-12-05 22:09:42[ debug ]TProxy local conn listener exit.. rAddr=142.250.176.4:443 lAddr=192.168.20.33:61730
23-12-05 22:09:42[ debug ]TProxy local conn listener exit.. rAddr=142.250.68.42:443 lAddr=192.168.20.33:56133
23-12-05 22:09:42[ debug ]Closing TProxy local conn... lAddr=192.168.20.33:59305 rAddr=142.250.68.74:443
23-12-05 22:09:42[ debug ]TProxy local conn listener exit.. rAddr=142.250.68.74:443 lAddr=192.168.20.33:59305
23-12-05 22:09:42[ debug ]Closing TProxy local conn... lAddr=192.168.20.33:55387 rAddr=142.250.217.142:443
23-12-05 22:09:42[ debug ]TProxy local conn listener exit.. rAddr=142.250.217.142:443 lAddr=192.168.20.33:55387
23-12-05 22:09:42[ debug ]Closing TProxy local conn... lAddr=192.168.20.33:52370 rAddr=142.250.188.237:443
23-12-05 22:09:42[ debug ]TProxy local conn listener exit.. rAddr=38.90.226.47:53535 lAddr=192.168.20.33:63994
23-12-05 22:09:42[ debug ]TProxy local conn listener exit.. rAddr=142.250.188.237:443 lAddr=192.168.20.33:52370
23-12-05 22:09:42[ debug ]Closing TProxy local conn... lAddr=192.168.20.33:63994 rAddr=38.90.226.47:53535
23-12-05 22:09:42[ info ][TCP] 192.168.20.33:6847 --> a.nel.cloudflare.com:443 match IPCIDR(35.184.0.0/13) using 🔍 谷歌服务[🇺🇸 US_DV]
23-12-05 22:09:41[ debug ]use specified fingerprint:Safari
23-12-05 22:09:41[ debug ][Rule] use default rules
23-12-05 22:09:41[ debug ][DNS] a.nel.cloudflare.com --> [35.190.80.1] A from udp://8.8.8.8:53
23-12-05 22:09:41[ debug ][DNS] a.nel.cloudflare.com --> [] HTTPS from udp://1.1.1.1:53
23-12-05 22:09:41[ debug ]use specified fingerprint:Safari
23-12-05 22:09:41[ debug ]use specified fingerprint:Safari
23-12-05 22:09:41[ debug ]use specified fingerprint:Safari
23-12-05 22:09:41[ debug ]use specified fingerprint:Safari
23-12-05 22:09:41[ debug ][DNS] resolve a.nel.cloudflare.com from udp://8.8.8.8:53
23-12-05 22:09:41[ debug ][DNS] resolve a.nel.cloudflare.com from udp://8.8.8.8:53
23-12-05 22:09:41[ debug ][DNS] resolve a.nel.cloudflare.com from udp://1.1.1.1:53
23-12-05 22:09:41[ debug ][DNS] resolve a.nel.cloudflare.com from udp://1.1.1.1:53
```

### Description

用23号的虚空终端所有节点都正常工作，更新到release的1.17版本之后vless节点正常，所有tuic节点不通。我反复试了几遍都是这样。tuic服务端用的sing-box 1.72搭建的
