### ISSUE TITLE
[Bug] 配置文件 v2ray-http-upgrade 类型解析错误

### ISSUE THREAD

**Issue by merrkry** [MetaCubeX/mihomo#886]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [x]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.17.0

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
- name: 
  server: 
  type: vless
  port: 443
  uuid: 
  tls: true
  network: ws
  servername:
  ws-opts:
    path: ""
    headers:
      v2ray-http-upgrade: true
```

### Mihomo log

```shell
Parse config error: proxy 1: 'ws-opts.headers[v2ray-http-upgrade]' expected type 'string', got unconvertible type 'bool'
```

### Description

`v2ray-http-upgrade` 填 `true` 时核心无法启动，核心报错见上文。该项应该为 bool 而不是 string。
