### ISSUE TITLE
[Bug] 一个未知的日志错误

### ISSUE THREAD

**Issue by Bitcion** [MetaCubeX/mihomo#887]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.17

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: warning
external-controller: '0.0.0.0:9090'
ipv6: true
proxy-providers:
 备用:
   type: http
   path: ./profiles/proxies/mx.yaml
   url: 
   filter: '韩国|vip1'
   interval: 86400
   health-check:
     enable: true
     url: http://www.gstatic.com/generate_204
     interval: 86400
 机场:
   type: http
   path: ./profiles/proxies/clash.yaml
   url: 
   exclude-filter: '韩国|vip1'
   interval: 3600
   health-check:
     enable: false
     url: http://www.gstatic.com/generate_204
     interval: 86400
 CCCloud:
   type: http
   path: ./profiles/proxies/cccloud.yaml
   url: 
   health-check:
     enable: true
     url: http://www.gstatic.com/generate_204
     interval: 86400
proxies:

  - name: 🚀 手动切换
    type: select
    use:
      - 备用
      - 机场
      - CCCloud
    proxies:
      - 🔯 故障转移 
      - DIRECT
      - 美国原生
      - 美国Oracle
      - vlessCF   
      - 台湾原生
  - name: ♻️ 自动选择
    type: url-test
    url: https://www.google.com/generate_204 
    interval: 601
    tolerance: 50
    use:
      - 机场
    proxies:
      - 美国    
      - 美台     
      - 台湾
      - 美转
      - 台美
      - 🔯 故障转移
      - vlessCF
      - 美国Oracle
  - name: 🔯 故障转移
    type: fallback
    url: http://edge.microsoft.com/captiveportal/generate_204
    interval: 86300
    tolerance: 50
    use:
      - 备用
      - 机场
      - CCCloud
    proxies:
      - 美国原生
      - 台湾
      - 美国     
      - 美台
      - 美转
      - 台美 
      - vlessCF
      - 美国Oracle             
  - name: 🔮 负载均衡
    type: load-balance
    strategy: round-robin
    url: http://cp.cloudflare.com/generate_204
    interval: 600
    tolerance: 1000
    proxies:
      - 🔯 故障转移
      - 美国    
      - 美台     
      - 台湾
      - 美转
      - 台美
  - name: 📲 电报消息
    type: select
    proxies:
      - 🔮 负载均衡
      - vlessCF
      - ♻️ 自动选择  
      - 🚀 手动切换 
  - name: 中转  
    type: relay   
    proxies:
      - 🚀 手动切换    
      - vlessCF               
  - name: 🎥 流媒体
    type: select
    proxies:
      - 🔮 负载均衡
      - 🚀 手动切换
      - 中转
      - vlessCF
  - name: 🎮 游戏平台
    type: select
    proxies:
      - DIRECT
      - 🚀 手动切换
      - 🔮 负载均衡
      - ♻️ 自动选择
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - DIRECT
      - 🔮 负载均衡
      - 🚀 手动切换
      - 🔯 故障转移
rule-providers:
  DLC规则:
    type: http
    behavior: domain
    url: "https://bitcion.github.io/zaixiantuoguan/DLC规则.txt"
    path: ./ruleset/DLC规则.yaml
    interval: 259200
 
rules:
 - GEOSITE,private,DIRECT
 - GEOIP,private,DIRECT
 - IP-CIDR6,::/0,vlessCF,no-resolve
 - RULE-SET,DLC规则,🚀 手动切换,no-resolve
 - GEOIP,Netflix,🎥 流媒体,no-resolve
 - GEOSITE,Netflix,🎥 流媒体,no-resolve
 - GEOSITE,primevideo,🎥 流媒体,no-resolve
 - DOMAIN-SUFFIX,ipinfo.io,🚀 手动切换,no-resolve
 - DOMAIN-SUFFIX,epochtimes.com,中转,no-resolve
 - DOMAIN-SUFFIX,ntdtv.com,中转,no-resolve
 - GEOSITE,openai,🚀 手动切换,no-resolve
 - GEOSITE,bing,♻️ 自动选择,no-resolve
 - GEOSITE,msn,♻️ 自动选择,no-resolve
 - GEOSITE,yahoo,♻️ 自动选择,no-resolve
 - GEOSITE,github,♻️ 自动选择,no-resolve
 - GEOSITE,tiktok,🔮 负载均衡,no-resolve
 - GEOSITE,binance,♻️ 自动选择,no-resolve
 - GEOSITE,gfw,♻️ 自动选择,no-resolve
 - GEOIP,TELEGRAM,📲 电报消息,no-resolve
 - GEOSITE,greatfire,♻️ 自动选择,no-resolve
 - GEOIP,Google,♻️ 自动选择,no-resolve
 - IP-CIDR,1.1.1.1/32,♻️ 自动选择,no-resolve
 - GEOSITE,category-games,🎮 游戏平台
 - MATCH,🐟 漏网之鱼
```

### Mihomo log

```shell
12-07 14:30:58INFO
[TCP] mihomo --> api.dler.io:443 match Match using 🐟 漏网之鱼[DIRECT]
12-07 14:30:59INFO
[TCP] mihomo --> api.dler.io:443 match Match using 🐟 漏网之鱼[DIRECT]
12-07 14:30:59WARNING
[Provider] get subscription-userinfo: &{%!e(string=ParseInt) %!e(string=1.0834333925381e+14) %!e(*errors.errorString=&{invalid syntax})}
12-07 14:30:59WARNING
[Provider] get subscription-userinfo: &{%!e(string=ParseInt) %!e(string=1.0834333925381e+14) %!e(*errors.errorString=&{invalid syntax})}
12-07 14:30:59WARNING
[Provider] get subscription-userinfo: &{%!e(string=ParseInt) %!e(string=1.0834333925381e+14) %!e(*errors.errorString=&{invalid syntax})}
12-07 14:30:59WARNING
[Provider] get subscription-userinfo: &{%!e(string=ParseInt) %!e(string=1.0834333925381e+14) %!e(*errors.errorString=&{invalid syntax})}
```

### Description

2个机场（一个机场分了两次配置）+一个规则合计，正好4个配置。

虽然不影响使用但一直报错，而且有点排查不出原因
