### ISSUE TITLE
[Bug] sniffer.override-destination 对 QUIC 不起作用

### ISSUE THREAD

**Issue by doveccl** [MetaCubeX/mihomo#896]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-06b4f88

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
dns:
  ipv6: true
  enable: true
  enhanced-mode: redir-host
  nameserver: [119.29.29.29, 223.5.5.5]
  fallback: [tls://1.0.0.1, tls://8.8.4.4, tls://9.9.9.9]

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  skip-domain: [Mijia Cloud]
  sniff:
    TLS:
      ports: [443]
    QUIC:
      ports: [443]
    HTTP:
      ports: [80]

listeners:
  - type: tun
    stack: gvisor
    auto-route: true
    auto-detect-interface: true
    dns-hijack: [any:53]
    inet4-address: [198.18.0.1/30]
    inet6-address: [fc00:198:18::1/126]

proxies:
  - type: hysteria2
```

### Description

使用如下命令进行测试
```bash
curl --http2 https://www.google.com
curl --http3 https://www.google.com
```
服务器端的 hysteria2 得到如下日志
```
2023-12-09T14:55:24Z    DEBUG   TCP request     {"addr": "*", "id": "user", "reqAddr": "www.google.com:443"}
2023-12-09T14:55:24Z    DEBUG   TCP closed      {"addr": "*", "id": "user", "reqAddr": "www.google.com:443"}
2023-12-09T14:55:24Z    DEBUG   UDP request     {"addr": "*", "id": "user", "sessionID": 0, "reqAddr": "[2607:f8b0:4005:80e::2004]:443"}
```
