### ISSUE TITLE
[Bug] UTF-8 with BOM 编码的 Base64 格式 proxy-provider 文件无法导入节点

### ISSUE THREAD

**Issue by Brbrbr1995** [MetaCubeX/mihomo#900]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
proxy-providers:

  VLS:
    type: http
    url: "http://192.168.1.14/Proxy/vless.txt"
    path: ./Provider/Proxy/vless.txt
    interval: 60
    health-check:
      enable: true
      interval: 30
      lazy: false
      url: "https://www.google.com/"
```

### Description

yaml和url格式正常
path目录无对应文件，面板显示此 provider 0 节点
节点工具导出的就是带BOM的编码
