### ISSUE TITLE
[Feature] 可否考虑在DNS部分中加入redir-host与fake-ip混合模式

### ISSUE THREAD

**Issue by lyz05** [MetaCubeX/mihomo#916]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

如题目所述，我希望mihomo在域名解析的过程中，先遍历一遍规则，发现规则匹配的是DIRECT，则返回真实IP（类似redir-host行为），若不是DIRECT，则返回fake-ip。

# 这样做有什么好处呢？
1. 让mihomo专注处理需要走代理的流量，而不需要处理直连流量。
2. 减少mihomo对设备本身物理网络的影响。

# 应用场景（本机）
当我启用TUN模式，并开启自定义路由，设置为fake-ip网段。（即：目的IP为fake-ip网段的流量被mihomo捕获，其余流量走默认物理网卡）
这样做以后，所有直连的流量都不会经过mihomo处理，这样我就能灵活开启关闭mihomo，而不会出现连接中断。

# 应用场景（局域网中所有设备）
此外，这种方法还可以扩展到局域网中的其他设备。
我仅需在主路由上设置两个参数，就能实现全局域网设备的科学上网。
1. 配置fake-ip网段静态路由到运行着mihomo TUN模式的设备上。
4. 配置主路由DNS上游为mihomo的DNS。
带来的另外的好处就是局域网中的设备直连上网，不会被运行着mihomo的设备捕获，也不会受到mihomo设备性能的影响。
局域网中其他设备，按照域名解析需要被代理的流量，会被路由表正确路由到TUN网卡中。
一个小遗憾就是，对于IP直连的应用无法走代理。但是可以通过添加静态路由解决。

下面给出配置：
``` yaml
dns:
  enable: true
  enhanced-mode: fake-ip-mixed # 上文定义的混合模式策略
  listen: :1053
  fake-ip-range: 198.18.0.1/16 #设置fake-ip范围
  nameserver:
    - 223.5.5.5
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-detect-interface: true
  auto-route: true
  inet4-route-address:
    - 198.18.0.0/16 #fake-ip段
# 下面为Telegram IP段
    - 91.108.56.0/22
    - 91.108.4.0/22
    - 91.108.8.0/22
    - 91.108.16.0/22
    - 91.108.12.0/22
    - 149.154.160.0/20
    - 91.105.192.0/23
    - 91.108.20.0/22
    - 185.76.151.0/24
```
# 目前所用方案
目前我是在主路由上运行了mosdns，来做dns分流。
针对解析IP段为国外的，会选mihomo的fake-ip dns解析结果。
解析IP为国内的，直接返回解析结果。
这样做能让局域网中其他设备直连国内网站不受任何影响。
