### ISSUE TITLE
[Bug] 活动连接数居高不下，很多连接时长几天前的都还在

### ISSUE THREAD

**Issue by imshuai** [MetaCubeX/mihomo#921]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta v1.17.0 linux arm64 with go1.21.4 Sat Dec  2 11:02:32 UTC 2023 Use tags: with_gvisor

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
mixed-port: 7890
allow-lan: true
bind-address: "192.168.4.4"
mode: rule
ipv6: true
external-controller: "127.0.0.1:9090"
interface-name: enxb827eb7678ab
geodata-mode: true
geodata-loader: memconservative
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
tcp-concurrent: true
#keep-alive-interval: 60
global-client-fingerprint: random
unified-delay: true #更换延迟计算方式,去除握手等额外延迟
profile:
  store-selected: true # 储存 API 对策略组的选择，以供下次启动时使用
  store-fake-ip: true # 储存 fakeip 映射表，域名再次发生连接时，使用原有映射地址
dns:
  enable: true
  prefer-h3: true
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  nameserver-policy:
    'geosite:cn': https://doh.pub/dns-query
    'geosite:gfw': [tls://8.8.4.4, https://1.0.0.1/dns-query]
    'rule-set:google,proxy': [tls://8.8.4.4, https://1.0.0.1/dns-query]
  nameserver:
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
    - https://doh.360.cn/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - tls://1.0.0.1:853
    - tls://dns.google:853
  proxy-server-nameserver:
    - https://doh.pub/dns-query
```

### Description

最新版的Mihomo，使用metatubexd作为UI，活动连接数居高不下，很多连接时长几天前的都还在，是不是我哪里设置不对？  
![image](https://github.com/MetaCubeX/mihomo/assets/15623716/81003a10-b8ad-45d8-98dc-721e6f7778f8)
## 关于keep-alive-interval  
我尝试过设置为15、60、300、3600以及关闭，都不能正常的断开连接
