### ISSUE TITLE
[Bug] CMFA无法使用`system`来获取本机DNS

### ISSUE THREAD

**Issue by Paulgudring** [MetaCubeX/mihomo#927]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

mihomo 1.16.0, CMFA 2.9.0

### Mihomo config

```yaml
## for other platform

dns:
  cache-algorithm: arc
  enable: true
  prefer-h3: true
  listen: :53
  ipv6: true
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
  - '*'
  - +.lan
  - +.local
  default-nameserver:
  - https://223.5.5.5/dns-query
  proxy-server-nameserver:
  - https://223.5.5.5/dns-query
  nameserver:
  - https://1.1.1.1/dns-query#url-test
  nameserver-policy:
    rule-set:private-only:
    - system
    rule-set:scholar-direct,direct-only:
    - https://223.5.5.5/dns-query
    geosite:spotify,onedrive,microsoft@cn,apple-cn,category-games@cn:
    - https://223.5.5.5/dns-query

##  for other android

dns:
  cache-algorithm: arc
  enable: true
  prefer-h3: true
  listen: :53
  ipv6: true
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
  - '*'
  - +.lan
  - +.local
  default-nameserver:
  - https://223.5.5.5/dns-query
  proxy-server-nameserver:
  - https://223.5.5.5/dns-query
  nameserver:
  - https://1.1.1.1/dns-query#url-test
  nameserver-policy:
    rule-set:private-only:
    - 10.10.10.10 #此处是组织中所用的dns服务器，ip形式
    - https://223.5.5.5/dns-query
    rule-set:scholar-direct,direct-only:
    - https://223.5.5.5/dns-query
    geosite:spotify,onedrive,microsoft@cn,apple-cn,category-games@cn:
    - https://223.5.5.5/dns-query
```

### Mihomo log

![image](https://github.com/MetaCubeX/mihomo/assets/81338177/862a52bc-919e-433b-b402-bd5454d8dec5)

### Description

先前发过[discussion](https://github.com/MetaCubeX/mihomo/discussions/866)。

因为在文档和[代码仓库](https://github.com/MetaCubeX/mihomo/blob/Alpha/dns/patch_android.go)里都看到实现了安卓端调用系统dns配置。虽然在`branch: alpha`中这个功能是`commit: 9e96d70`引入的，但是应该是把安卓端那边[patch](https://github.com/MetaCubeX/mihomo/blob/android-open/dns/patch.go)拉了过来，所以这项功能在cmfa 2.9.0应该是支持的。

但在使用中无法正常使用，目前在两部手机上都复现了这个问题（aosp12,  aosp14），不清楚是不是bug。

`system`这一配置比较灵活，能够改善内网访问体验；如果用硬编码的方式，配置间不能同步，并且内网dns服务器也可能更换地址。希望能得到支持。辛苦排查~
