### ISSUE TITLE
gprc协议在linux下休眠后出现连不通（有workaround)

### ISSUE THREAD

**Issue by bash99** [MetaCubeX/mihomo#93]
可能是非常上游的bug，同样配置在windows下正常。
vless+grpc trojan+grpc 都有这个现象；休眠后resume，怎么测速都不通，只有重启clash才能解决。
感觉和 https://stackoverflow.com/questions/69634568/grpc-long-lived-bidirectional-stream-closed-after-laptop-goes-to-sleep 的现象很接近。

下面配置中去掉 multiMode和idle_timeout也是同样情况
```
    grpc-opts:
      multiMode: true
      idle_timeout: 29
      grpc-service-name: {grpc_service_name}
```

被迫加了一个systemctl服务在系统resume后自动重启clash
```/lib/systemd/system/CMrestart.service
[Unit]
Description=Restart Clash.Meta after resume
After=suspend.target

[Service]
Type=simple
ExecStart=/usr/bin/systemctl --no-block restart Clash-Meta.service

[Install]
WantedBy=suspend.target
```
