### ISSUE TITLE
[Bug] 更新mmdb格式的GeoData失败

### ISSUE THREAD

**Issue by LzNOHentai** [MetaCubeX/mihomo#931]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.17.0

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
geodata-mode: false
geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://gcore.jsdelivr.net/gh/alecthw/mmdb_china_ip_list@release/Country.mmdb
```

### Mihomo log

```shell
[REST-API] updating GEO databases...  
[TCP] mihomo --> gcore.jsdelivr.net:443 match RuleSet(Global) using 🔰 Proxies[🇯🇵 Japan 01] 
[REST-API] update GEO databases failed: can't save MMDB database file: %!w(<nil>)
```

### Description

Windows下使用Clash Verge rev 1.4.5版本（Meta内核1.17.0）更新GeoData失败。
使用的是服务模式+TUN模式，其他所有上网功能一切正常。
Verge开发者表示更新GeoData功能为内核实现，建议向内核提issue，故尝试在此提出issue。
