### ISSUE TITLE
How to use TUN mode with an external SOCKS5 proxy?

### ISSUE THREAD

**Issue by Azadzadeh** [MetaCubeX/mihomo#957]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

v1.16.0

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
port: 1080
allow-lan: false
mode: rule
log-level: debug
dns:
  enable: true
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
  nameserver:
    - 8.8.8.8
    - tcp://8.8.8.8
tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true

proxies:
  - name: 'xray-daemon'
    type: socks5
    server: '127.0.0.1'
    port: 1085
    udp: true


proxy-groups:
  - name: 'myproxy'
    type: select
    proxies:
      - 'xray-daemon'

rules:
  - GEOIP, PRIVATE, DIRECT
  - MATCH, myproxy
```

### Description

i'm running an Xray daemon at `localhost:1085`
here is the minimal Xray config on client side:
```json
{
  "log": {
    "loglevel": "info"
  }
  ,
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct"
      }
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": "1085",
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "127.0.0.1"
      }
    } 
  ],
  "outbounds": [
    {
      "protocol": "...",
      "settings": {},
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ]
}

```

i can confirm it works independently on its own as a simple SOCKS5 proxy.

here is the Clash config with TUN:

```yaml
port: 1080
allow-lan: false
mode: rule
log-level: debug
dns:
  enable: true
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
  nameserver:
    - 8.8.8.8
    - tcp://8.8.8.8
tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true

proxies:
  - name: 'xray-daemon'
    type: socks5
    server: '127.0.0.1'
    port: 1085
    udp: true


proxy-groups:
  - name: 'myproxy'
    type: select
    proxies:
      - 'xray-daemon'

rules:
  - GEOIP, PRIVATE, DIRECT
  - MATCH, myproxy
```

when i run it, it doesn't work. it's as if there is some infinite loop problem.
on Xray side i get this error:
```
app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
```

also clash works fine in TUN mode with other native implementations of proxies.

i just want to convert this external socks5 proxy to a TUN device and use clash
for rules
