### ISSUE TITLE
[Bug] ProxyProvider  HealthCheck 时被重复测试

### ISSUE THREAD

**Issue by Brbrbr1995** [MetaCubeX/mihomo#960]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-2e12cee

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
proxies:

proxy-providers:
  Abroad:
    type: http
    url: "http://192.168.1.14/Proxy/Abroad.yaml"
    path: ./Provider/Proxy/Abroad.yaml
    interval: 60
    health-check:
      enable: true
      interval: 30
      lazy: false
      url: "https://www.google.com/"

  China:
    type: http
    url: "http://192.168.1.14/Proxy/China.yaml"
    path: ./Provider/Proxy/China.yaml
    interval: 60
    health-check:
      enable: true
      interval: 30
      lazy: false
      url: "https://www.baidu.com/"

proxy-groups:
  - name: '⏱'
    type: url-test
    disable-udp: false
    tolerance: 20
    interval: 30
    url: "https://www.bing.com/"
    proxies:
    use:
      - Abroad

  - name: '✅'
    type: fallback
    disable-udp: false
    interval: 30
    url: "https://www.bing.com/"
    proxies:
    use:
      - Abroad

  - name: '🔆'
    type: load-balance
    strategy: round-robin
    disable-udp: false
    interval: 30
    url: "https://www.bing.com/"
    proxies:
    use:
      - Abroad
```

### Mihomo log

```shell
time="2024-01-05T06:43:16.9084003+08:00" level=debug msg="Start New Health Checking {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:16.9084003+08:00" level=debug msg="Start New Health Checking {fbf50806-d9ab-4fbd-9464-09caf08e598b}"
time="2024-01-05T06:43:16.9084003+08:00" level=debug msg="Health Checking, proxy: PXY_111, url: https://www.google.com/, id: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:16.9084003+08:00" level=debug msg="Health Checking, proxy: 中国_111, url: https://www.gstatic.com/generate_204, id: {fbf50806-d9ab-4fbd-9464-09caf08e598b}"
time="2024-01-05T06:43:16.9084003+08:00" level=debug msg="Health Checking, proxy: PXY_222, url: https://www.gstatic.com/generate_204, id: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:16.9084003+08:00" level=debug msg="Health Checking, proxy: PXY_111, url: https://www.bing.com/, id: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:16.9084003+08:00" level=debug msg="Health Checking, proxy: PXY_333, url: https://www.bing.com/, id: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:16.9089098+08:00" level=debug msg="[DNS] cache hit for s.803.com., expire at 2024-01-05 06:52:48"
time="2024-01-05T06:43:16.9084003+08:00" level=debug msg="Health Checking, proxy: PXY_111, url: https://www.gstatic.com/generate_204, id: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:16.9084003+08:00" level=debug msg="Health Checking, proxy: PXY_222, url: https://www.bing.com/, id: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:16.9084003+08:00" level=debug msg="Health Checking, proxy: PXY_333, url: https://www.gstatic.com/generate_204, id: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:16.9084003+08:00" level=debug msg="Health Checking, proxy: PXY_333, url: https://www.google.com/, id: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:16.9084003+08:00" level=debug msg="Health Checking, proxy: 中国_111, url: https://www.baidu.com/, id: {fbf50806-d9ab-4fbd-9464-09caf08e598b}"
time="2024-01-05T06:43:16.9084003+08:00" level=debug msg="Health Checking, proxy: PXY_222, url: https://www.google.com/, id: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:16.9095425+08:00" level=debug msg="Health Checked, proxy: 中国_111, url: https://www.gstatic.com/generate_204, alive: false, delay: 65535 ms uid: {fbf50806-d9ab-4fbd-9464-09caf08e598b}"
time="2024-01-05T06:43:16.9095425+08:00" level=debug msg="[DNS] cache hit for s.803.com., expire at 2024-01-05 06:52:48"
time="2024-01-05T06:43:16.9100538+08:00" level=debug msg="Health Checked, proxy: 中国_111, url: https://www.baidu.com/, alive: false, delay: 65535 ms uid: {fbf50806-d9ab-4fbd-9464-09caf08e598b}"
time="2024-01-05T06:43:16.9100538+08:00" level=debug msg="Finish A Health Checking {fbf50806-d9ab-4fbd-9464-09caf08e598b}"
time="2024-01-05T06:43:17.352221+08:00" level=debug msg="Health Checked, proxy: PXY_111, url: https://www.gstatic.com/generate_204, alive: true, delay: 442 ms uid: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:17.3758446+08:00" level=debug msg="Health Checked, proxy: PXY_111, url: https://www.google.com/, alive: true, delay: 467 ms uid: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:17.4286692+08:00" level=debug msg="Health Checked, proxy: PXY_333, url: https://www.google.com/, alive: true, delay: 519 ms uid: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:17.4340151+08:00" level=debug msg="Health Checked, proxy: PXY_333, url: https://www.gstatic.com/generate_204, alive: true, delay: 524 ms uid: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:17.4856637+08:00" level=debug msg="Health Checked, proxy: PXY_111, url: https://www.bing.com/, alive: true, delay: 576 ms uid: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:17.5353318+08:00" level=debug msg="Health Checked, proxy: PXY_222, url: https://www.gstatic.com/generate_204, alive: true, delay: 626 ms uid: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:17.8646815+08:00" level=debug msg="Health Checked, proxy: PXY_333, url: https://www.bing.com/, alive: true, delay: 955 ms uid: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:17.996965+08:00" level=debug msg="Health Checked, proxy: PXY_222, url: https://www.google.com/, alive: true, delay: 1087 ms uid: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:18.0048834+08:00" level=debug msg="Health Checked, proxy: PXY_222, url: https://www.bing.com/, alive: true, delay: 1095 ms uid: {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
time="2024-01-05T06:43:18.0048834+08:00" level=debug msg="Finish A Health Checking {13d1f6b8-aa4e-48bd-914e-ab72f9b02c8f}"
```

### Description

HealthCheck 时节点被重复测试，如上配置一次HealthCheck一个节点测了6次，
试过策略组里url留空，或和provider里一样，interval=0，都没用
希望节点组内配置不要影响 provider 里的测试。
