### ISSUE TITLE
[Bug] macOS 使用 Tun 模式直连无法访问 www.baidu.com

### ISSUE THREAD

**Issue by Cyberbolt** [MetaCubeX/mihomo#963]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta alpha-2e12cee darwin arm64 with go1.20.12

### What OS are you seeing the problem on?

macOS

### Mihomo config

```yaml
mixed-port: 8890
allow-lan: true
dns:
  enabled: true
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - swscan.apple.com
    - mesu.apple.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - +.music.163.com
    - '*.126.net'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - +.y.qq.com
    - +.music.tc.qq.com
    - aqqmusic.tc.qq.com
    - +.stream.qqmusic.qq.com
    - '*.xiami.com'
    - +.music.migu.cn
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - +.xboxlive.com
    - localhost.ptlogin2.qq.com
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - '*.mcdn.bilivideo.cn'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
  device: utun123



proxies:
- name: "socks"
  type: socks5
  server: 127.0.0.1
  port: 1077
  udp: true

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - socks
      - DIRECT
  
rules:
- IP-CIDR,0.0.0.0/0,DIRECT
# - IP-CIDR,127.0.0.0/8,DIRECT
# - IP-CIDR,192.168.0.0/16,DIRECT
```

### Mihomo log

```shell
(base) ➜  test sudo ./mihomo -d ./
INFO[2024-01-05T14:08:56.389092+08:00] Start initial configuration in progress      
INFO[2024-01-05T14:08:56.389221+08:00] Geodata Loader mode: memconservative         
INFO[2024-01-05T14:08:56.389227+08:00] Geosite Matcher implementation: succinct     
INFO[2024-01-05T14:08:56.389838+08:00] Initial configuration complete, total time: 0ms 
INFO[2024-01-05T14:08:56.389849+08:00] Sniffer is closed                            
INFO[2024-01-05T14:08:56.389998+08:00] Mixed(http+socks) proxy listening at: [::]:8890 
WARN[2024-01-05T14:08:56.390107+08:00] [TUN] default interface changed by monitor,  => en0 
INFO[2024-01-05T14:08:56.391621+08:00] [TUN] Tun adapter listening at: utun123([198.18.0.1/30],[]), mtu: 9000, auto route: true, ip stack: System 
INFO[2024-01-05T14:08:56.392211+08:00] Start initial Compatible provider default    
INFO[2024-01-05T14:08:56.392222+08:00] Start initial Compatible provider PROXY      
INFO[2024-01-05T14:09:01.478856+08:00] [TCP] 198.18.0.1:50499 --> 120.232.69.34:993 match IPCIDR(0.0.0.0/0) using DIRECT
```

### Description

当我设置为全部连接走直连时，并不能访问互联网，访问 [www.baidu.com](https://www.baidu.com/)，浏览器一直转圈。请问是配置文件的问题？非常感谢！

**Comment by Cyberbolt** [comment]
> ### Verify steps
> * [x]   确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**.
> * [ ]   如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
> * [x]   我已经在 [Issue Tracker](%E2%80%A6%E2%80%A6/) 中找过我要提出的问题 I have searched on the [issue tracker](%E2%80%A6%E2%80%A6/) for a related issue.
> * [x]   我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists.
> * [x]   我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue.
> * [x]   这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core _per se_, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo.
> 
> ### Mihomo version
> Mihomo Meta alpha-2e12cee darwin arm64 with go1.20.12
> 
> ### What OS are you seeing the problem on?
> macOS
> 
> ### Mihomo config
> ```yaml
> mixed-port: 8890
> allow-lan: true
> dns:
>   enabled: true
>   listen: 0.0.0.0:1053
>   ipv6: true
>   default-nameserver:
>     - 223.5.5.5
>     - 114.114.114.114
>   enhanced-mode: fake-ip
>   fake-ip-range: 198.18.0.1/16
>   fake-ip-filter:
>     - '*.lan'
>     - '*.linksys.com'
>     - '*.linksyssmartwifi.com'
>     - swscan.apple.com
>     - mesu.apple.com
>     - '*.msftconnecttest.com'
>     - '*.msftncsi.com'
>     - time.*.com
>     - time.*.gov
>     - time.*.edu.cn
>     - time.*.apple.com
>     - time1.*.com
>     - time2.*.com
>     - time3.*.com
>     - time4.*.com
>     - time5.*.com
>     - time6.*.com
>     - time7.*.com
>     - ntp.*.com
>     - ntp.*.com
>     - ntp1.*.com
>     - ntp2.*.com
>     - ntp3.*.com
>     - ntp4.*.com
>     - ntp5.*.com
>     - ntp6.*.com
>     - ntp7.*.com
>     - '*.time.edu.cn'
>     - '*.ntp.org.cn'
>     - +.pool.ntp.org
>     - time1.cloud.tencent.com
>     - +.music.163.com
>     - '*.126.net'
>     - musicapi.taihe.com
>     - music.taihe.com
>     - songsearch.kugou.com
>     - trackercdn.kugou.com
>     - '*.kuwo.cn'
>     - api-jooxtt.sanook.com
>     - api.joox.com
>     - joox.com
>     - +.y.qq.com
>     - +.music.tc.qq.com
>     - aqqmusic.tc.qq.com
>     - +.stream.qqmusic.qq.com
>     - '*.xiami.com'
>     - +.music.migu.cn
>     - +.srv.nintendo.net
>     - +.stun.playstation.net
>     - xbox.*.microsoft.com
>     - +.xboxlive.com
>     - localhost.ptlogin2.qq.com
>     - proxy.golang.org
>     - stun.*.*
>     - stun.*.*.*
>     - '*.mcdn.bilivideo.cn'
>   nameserver:
>     - https://doh.pub/dns-query
>     - https://dns.alidns.com/dns-query
>   fallback-filter:
>     geoip: false
>     ipcidr:
>       - 240.0.0.0/4
>       - 0.0.0.0/32
> 
> tun:
>   enable: true
>   stack: system
>   auto-route: true
>   auto-detect-interface: true
>   dns-hijack:
>     - any:53
>   device: utun123
> 
> 
> 
> proxies:
> - name: "socks"
>   type: socks5
>   server: 127.0.0.1
>   port: 1077
>   udp: true
> 
> proxy-groups:
>   - name: PROXY
>     type: select
>     proxies:
>       - socks
>       - DIRECT
>   
> rules:
> - IP-CIDR,0.0.0.0/0,DIRECT
> # - IP-CIDR,127.0.0.0/8,DIRECT
> # - IP-CIDR,192.168.0.0/16,DIRECT
> ```
> 
> ### Mihomo log
> ```shell
> (base) ➜  test sudo ./mihomo -d ./
> INFO[2024-01-05T14:08:56.389092+08:00] Start initial configuration in progress      
> INFO[2024-01-05T14:08:56.389221+08:00] Geodata Loader mode: memconservative         
> INFO[2024-01-05T14:08:56.389227+08:00] Geosite Matcher implementation: succinct     
> INFO[2024-01-05T14:08:56.389838+08:00] Initial configuration complete, total time: 0ms 
> INFO[2024-01-05T14:08:56.389849+08:00] Sniffer is closed                            
> INFO[2024-01-05T14:08:56.389998+08:00] Mixed(http+socks) proxy listening at: [::]:8890 
> WARN[2024-01-05T14:08:56.390107+08:00] [TUN] default interface changed by monitor,  => en0 
> INFO[2024-01-05T14:08:56.391621+08:00] [TUN] Tun adapter listening at: utun123([198.18.0.1/30],[]), mtu: 9000, auto route: true, ip stack: System 
> INFO[2024-01-05T14:08:56.392211+08:00] Start initial Compatible provider default    
> INFO[2024-01-05T14:08:56.392222+08:00] Start initial Compatible provider PROXY      
> INFO[2024-01-05T14:09:01.478856+08:00] [TCP] 198.18.0.1:50499 --> 120.232.69.34:993 match IPCIDR(0.0.0.0/0) using DIRECT
> ```
> 
> ### Description
> 当我设置为全部连接走直连时，并不能访问互联网，访问 [www.baidu.com](https://www.baidu.com/)，浏览器一直转圈。请问是配置文件的问题？非常感谢！

**Comment by Cyberbolt** [comment]
已解决，dns 配置有问题，正确配置文件为
```yaml
mixed-port: 8890
allow-lan: true

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
  nameserver:
    - 223.5.5.5
    - 180.76.76.76
    - 119.29.29.29
    - 117.50.11.11
    - 117.50.10.10
    - 114.114.114.114
  fallback:
    - 8.8.8.8
    - 1.1.1.1
    - tls://dns.rubyfish.cn:853
    - tls://1.0.0.1:853
    - tls://dns.google:853
    - https://dns.rubyfish.cn/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
  device: utun123



proxies:
- name: "socks"
  type: socks5
  server: 127.0.0.1
  port: 1077
  udp: true

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - socks
  
rules:
  - IP-CIDR,0.0.0.0/0,socks
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
```
