### ISSUE TITLE
BUG 日志

### ISSUE THREAD

**Issue by Chuhe2399** [MetaCubeX/mihomo#975]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

CFM

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
p: &p {type: http, interval: 3600, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}
n: &n {url: 'http://www.gstatic.com/generate_204', interval: 300, filter: '^(?!.*(CFWarp|cloudflare|HK|JP|SG|US|BGP|临时|香港|东京|狮城|埃及|爱尔兰|菲律宾|首尔|澳门|台湾|美国|阿联酋|韩国|英国|新加坡|土耳其|南非|印度|德国|日本|俄罗斯|法国|巴西|马来|印尼|泰国|加拿大|瑞士|越南|沙特|以色列|意大利|西班牙|荷兰|智利|阿根廷|澳大利亚|马来西亚|洛杉矶|冰岛|美西|波兰华沙|法兰克福|澳洲|马来|阿姆|比利时|乌克兰|悉尼|企宽|【直连】)).*(广东|汕尾|珠海|广州|宿迁|广西|河北|湖北|河南|山西|辽宁|吉林|黑龙江|江苏|浙江|安徽|福建|江西|山东|湖南|海南|四川|贵州|云南|陕西|甘肃|青海|内蒙|西藏|宁夏|新疆|北京|天津|上海|重庆|扬州)'}
w: &w {url: 'http://www.gstatic.com/generate_204', interval: 300, filter: '^(?!.*(广东|汕尾|珠海|广州|宿迁|广西|河北|湖北|河南|山西|辽宁|吉林|黑龙江|江苏|浙江|安徽|福建|江西|山东|湖南|海南|四川|贵州|云南|陕西|甘肃|青海|内蒙|西藏|宁夏|新疆|北京|天津|上海|重庆|扬州)).*(CFWarp|cloudflare|HK|JP|SG|US|BGP|临时|香港|东京|狮城|埃及|爱尔兰|菲律宾|首尔|澳门|台湾|美国|阿联酋|韩国|英国|新加坡|土耳其|南非|印度|德国|日本|俄罗斯|法国|巴西|马来|印尼|泰国|加拿大|瑞士|越南|沙特|以色列|意大利|西班牙|荷兰|智利|阿根廷|澳大利亚|马来西亚|洛杉矶|冰岛|美西|波兰华沙|法兰克福|澳洲|马来|阿姆|比利时|乌克兰|悉尼|企宽|【直连】)'}

mixed-port: 8888
tproxy-port: 7893
allow-lan: true
bind-address: "*" 
find-process-mode: strict
mode: rule
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
geo-auto-update: true
geo-update-interval: 24
global-ua: clash.meta
geodata-mode: true
geodata-loader: standard
geosite-matcher: succinct
log-level: info
ipv6: true
external-controller: 0.0.0.0:9090
external-ui: Dashboard
global-client-fingerprint: chrome
keep-alive-interval: 30
tcp-concurrent: true
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true
  
tun: 
  enable: true
  device: Tun
  stack: mixed
  dns-hijack: ['any:53']
  auto-route: true
  auto-detect-interface: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - Mijia Cloud
  
dns:
  enable: true
  ipv6: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fallback-filter: {geoip: true, geoip-code: CN, geosite: ['!CN', 'GFW', 'GREATFIRE'], ipcidr: ['240.0.0.0/4'], domain: ['+.google.com', '+.facebook.com', '+.youtube.com']}
  fake-ip-filter: ['*.lan', 'connect.rom.miui.com', 'www.msftconnecttest.com', 'localhost.ptlogin2.qq.com', 'xbox.*.microsoft.com', '+.xboxlive.com', '+.bilivideo.com']
  default-nameserver: ['tls://223.5.5.5', 'tls://8.8.8.8', 'tls://119.29.29.29', 'tls://1.1.1.1']
  proxy-server-nameserver: ['tls://223.5.5.5', 'tls://8.8.8.8', 'tls://119.29.29.29', 'tls://1.1.1.1']
  nameserver: ['tls://223.5.5.5#🎯国内选择', 'tls://119.29.29.29#🎯国内选择']
  fallback: ['tls://8.8.8.8#🚀国外选择', 'tls://1.1.1.1#🚀国外选择']
```

### Mihomo log

```shell
time="2024-01-12T14:26:12.991255698Z" level=warning msg="replace fallback-filter.geosite with nameserver-policy, it will be removed in the future"
time="2024-01-12T14:26:13.247540594Z" level=info msg="Start initial GeoSite dns fallback filter `!CN`, records: 66657"
time="2024-01-12T14:26:13.314991323Z" level=info msg="Start initial GeoSite dns fallback filter `GFW`, records: 6087"
time="2024-01-12T14:26:13.369908823Z" level=info msg="Start initial GeoSite dns fallback filter `GREATFIRE`, records: 8"
time="2024-01-12T14:26:13.370245073Z" level=info msg="Initial configuration complete, total time: 7043ms"
time="2024-01-12T14:26:13.373716323Z" level=info msg="RESTful API listening at: [::]:9090"
time="2024-01-12T14:26:13.446103666Z" level=info msg="Sniffer is loaded and working"
time="2024-01-12T14:26:13.446139812Z" level=info msg="Use tcp concurrent"
time="2024-01-12T14:26:13.446358666Z" level=info msg="DNS server listening at: [::]:1053"
time="2024-01-12T14:26:13.446481219Z" level=info msg="TProxy server listening at: [::]:7893"
time="2024-01-12T14:26:13.446589708Z" level=info msg="Mixed(http+socks) proxy listening at: [::]:8888"
time="2024-01-12T14:26:13.44817825Z" level=warning msg="[TUN] default interface changed by monitor,  => rmnet_data4"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x640c870860]

goroutine 1 [running]:
github.com/metacubex/gvisor/pkg/tcpip/link/channel.(*Endpoint).Attach(0x0, {0x0?, 0x0})
	github.com/metacubex/gvisor@v0.0.0-20231209122014-3e43224c7bbc/pkg/tcpip/link/channel/channel.go:209 +0x30
github.com/metacubex/sing-tun.(*Mixed).Close(0x400230b360)
	github.com/metacubex/sing-tun@v0.2.0-beta.4/stack_mixed.go:264 +0x30
github.com/sagernet/sing/common.Close({0x4001098a38?, 0x5, 0x4001098ac8?})
	github.com/sagernet/sing@v0.3.0-rc.3/common/cond.go:351 +0x8c
github.com/metacubex/mihomo/listener/sing_tun.(*Listener).Close(...)
	github.com/metacubex/mihomo/listener/sing_tun/server.go:334
github.com/metacubex/mihomo/listener/sing_tun.New.func1()
	github.com/metacubex/mihomo/listener/sing_tun/server.go:175 +0xd8
github.com/metacubex/mihomo/listener/sing_tun.New({0x1, {0x400047a1c0, 0x3}, 0x2, {0x4000494d90, 0x1, 0x1}, 0x1, 0x1, {0x640e1a5d28, ...}, ...}, ...)
	github.com/metacubex/mihomo/listener/sing_tun/server.go:266 +0x1594
github.com/metacubex/mihomo/listener.ReCreateTun({0x1, {0x400047a1c0, 0x3}, 0x2, {0x4000494d90, 0x1, 0x1}, 0x1, 0x1, {0x640e1a5d28, ...}, ...}, ...)
	github.com/metacubex/mihomo/listener/listener.go:534 +0x1a0
github.com/metacubex/mihomo/hub/executor.updateTun(0x40002eea00)
	github.com/metacubex/mihomo/hub/executor/executor.go:352 +0x78
github.com/metacubex/mihomo/hub/executor.ApplyConfig(0x40000f06c0, 0xe0?)
	github.com/metacubex/mihomo/hub/executor/executor.go:103 +0x29c
github.com/metacubex/mihomo/hub.Parse({0x0, 0x0, 0x40?})
	github.com/metacubex/mihomo/hub/hub.go:50 +0x270
main.main()
	github.com/metacubex/mihomo/main.go:110 +0x694
```

### Description

不知道问题，只有日志
