### ISSUE TITLE
断网重连, 需要等待大约40秒网络才能正常使用 [Bug] 

### ISSUE THREAD

**Issue by Sanchew** [MetaCubeX/mihomo#980]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-edf318b

### Mihomo config

```yaml
# HTTP 端口
port: 7890

# SOCKS5 端口
socks-port: 7891

# Linux 及 macOS 的 redir 端口
# redir-port: 7892

allow-lan: false

# 仅适用于设置 allow-lan 为 true 时
# "*": 绑定所有 IP 地址
# 192.168.122.11: 绑定单个 IPv4 地址
# "[aaaa::a8aa:ff:fe09:57d8]": 绑定单个 IPv6 地址
# bind-address: "*"

# Rule / Global / Direct (默认为 Rule 模式)
mode: Rule

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

# 设置输出日志的等级 (默认为 info)
# info / warning / error / debug / silent
log-level: debug

# RESTful API for clash
external-controller: 0.0.0.0:9090
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip" #从 GitHub Pages 分支获取


# 实验性功能
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为true

hosts:
  'mtalk.google.com': 108.177.125.188

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter:
    - '*.lan'
  nameserver:
    - 119.29.29.29
  fallback:
    - 'tls://1.1.1.1#🇺🇸 Fallback'
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
  nameserver-policy:
    "geosite:private,cn": 119.29.29.29
    '+.openai.com,+.reddit.com': 'tls://1.1.1.1#🇭🇰 Fallback'
    "geosite:geolocation-!cn": "tls://1.1.1.1#🇺🇸 Fallback"
  proxy-server-nameserver:
    - https://doh.pub/dns-query
```

### Description

断网重连后, 需要等待大约40秒网络才会恢复正常,  我使用的是tun模式, 网络已经恢复了,  但是无法访问,
