### ISSUE TITLE
[Bug] 在linux上无法启用tun模式

### ISSUE THREAD

**Issue by Gedoy9793** [MetaCubeX/mihomo#983]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta alpha-edf318b linux amd64 with go1.21.5 Sat Jan 13 10:16:41 UTC 2024

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
mode: rule
mixed-port: 7897
allow-lan: false
log-level: info
secret: ''
external-controller: 0.0.0.0:9097
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
  fake-ip-filter:
  - dns.msftncsi.com
  - www.msftncsi.com
  - www.msftconnecttest.com
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
proxies:
...
```

### Mihomo log

```shell
INFO[2024-01-15T16:53:40.677057411Z] Start initial configuration in progress
INFO[2024-01-15T16:53:40.678286015Z] Geodata Loader mode: memconservative
INFO[2024-01-15T16:53:40.678303475Z] Geosite Matcher implementation: succinct
INFO[2024-01-15T16:53:40.679259116Z] Initial configuration complete, total time: 2ms
INFO[2024-01-15T16:53:40.680067431Z] RESTful API listening at: [::]:9097
INFO[2024-01-15T16:53:40.695695849Z] Sniffer is closed
INFO[2024-01-15T16:53:40.695839961Z] Mixed(http+socks) proxy listening at: 127.0.0.1:7897
WARN[2024-01-15T16:53:40.69632444Z] [TUN] default interface changed by monitor,  => ens160
INFO[2024-01-15T16:53:40.698569843Z] [TUN] Tun adapter listening at: Meta([198.18.0.1/30],[fdfe:dcba:9876::1/126]), mtu: 9000, auto route: true, ip stack: gVisor
INFO[2024-01-15T16:53:40.709364068Z] Start initial Compatible provider 故障转移
INFO[2024-01-15T16:53:40.709684681Z] Start initial Compatible provider 自动选择
INFO[2024-01-15T16:53:40.710112444Z] Start initial Compatible provider 猫猫云
INFO[2024-01-15T16:53:40.710555674Z] Start initial Compatible provider default
```

### Description

配置tun不生效，没有使用ui程序，直接使用了内核
不过安装是用了verge的deb安装

**Comment by xishang0128** [comment]
@Gedoy9793 执行一下`ip rule`看看,以及是否是root用户启动,如果非root,是否给予了对应权限

**Comment by Gedoy9793** [comment]
> ```shell
> WARN[2024-01-15T16:53:40.69632444Z] [TUN] default interface changed by monitor,  => ens160
> ```

启动时或者使用webui切换tun模式时，会出现这个warning，不知道是不是这个问题，

**Comment by Gedoy9793** [comment]
> @Gedoy9793 ping 223.5.5.5 -c4 看看是什么结果

```shell
PING 223.5.5.5 (223.5.5.5) 56(84) bytes of data.

--- 223.5.5.5 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3071ms
```
ping不通

**Comment by xishang0128** [comment]
> > ```shell
> > WARN[2024-01-15T16:53:40.69632444Z] [TUN] default interface changed by monitor,  => ens160
> > ```
> 
> 启动时或者使用webui切换tun模式时，会出现这个warning，不知道是不是这个问题，

这是正常提示,选择出站接口

**Comment by xishang0128** [comment]
> > @Gedoy9793 ping 223.5.5.5 -c4 看看是什么结果
> 
> ```shell
> PING 223.5.5.5 (223.5.5.5) 56(84) bytes of data.
> 
> --- 223.5.5.5 ping statistics ---
> 4 packets transmitted, 0 received, 100% packet loss, time 3071ms
> ```
> 
> ping不通

ping 198.18.0.1呢,以及是否安装了iproute2,如果没有,安装再尝试

**Comment by Gedoy9793** [comment]
> > > @Gedoy9793 ping 223.5.5.5 -c4 看看是什么结果
> > 
> > 
> > ```shell
> > PING 223.5.5.5 (223.5.5.5) 56(84) bytes of data.
> > 
> > --- 223.5.5.5 ping statistics ---
> > 4 packets transmitted, 0 received, 100% packet loss, time 3071ms
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ping不通
> 
> ping 198.18.0.1呢,以及是否安装了iproute2,如果没有,安装再尝试

这个可以ping通

iproute2已经安装了，刚刚试试更新了一下再重启核心，问题还在

**Comment by xishang0128** [comment]
@Gedoy9793 试试mixed栈

**Comment by xishang0128** [comment]
@Gedoy9793 那就不要用service启动,直接命令行启动内核常识一下,root用户

**Comment by Gedoy9793** [comment]
> @Gedoy9793 那就不要用service启动,直接命令行启动内核常识一下,root用户

还是不行，ping 223.5.5.5不通

**Comment by Gedoy9793** [comment]
> @Gedoy9793 那就不要用service启动,直接命令行启动内核常识一下,root用户

使用tun后路由表应该有变化吗，我看现在的默认网关还是走ens160，就是物理网卡

**Comment by levihuayuzhang** [comment]
Same, at Alpha HEAD and v1.18 (self compiled), on Ubuntu 2204. But the container image seems works fine.

**Comment by xishang0128** [comment]
@Gedoy9793 lookup到2022了看起来应该没问题才对

**Comment by Gedoy9793** [comment]
> @Gedoy9793 lookup到2022了看起来应该没问题才对

不过生成的这个，9001那条就很奇怪，把后面都跳过了，不知道为什么

**Comment by xishang0128** [comment]
@Gedoy9793 我也有9001这个,但是能正常使用,确实挺奇怪的

**Comment by Gedoy9793** [comment]
另外在Ubuntu18上，metacubexd也拿不到日志，应该是核心restfulapi的问题，更新后解决了

**Comment by Bodil-X** [comment]
CentOS 7 中也存在这个问题，按 @Gedoy9793 说的，使用命令 `ip rule del pref 9001` 后就正常了

**Comment by vichbb** [comment]
> ip rule del pref 9001

不知道为什么我的移除了也不行，请问centos7需要额外配置cat /etc/resolv.conf吗？

**Comment by Bodil-X** [comment]
> > ip rule del pref 9001
> 
> 不知道为什么我的移除了也不行，请问centos7需要额外配置cat /etc/resolv.conf吗？

我有配置，实际上即使删除了9010那条，后续在使用的过程中还发现其它的问题。
我把系统内核升级到5.4后，运行了也不用再手动删除了。（但是它还是存在其它问题，如宿主机上运行的docker运行的程序的端口无法被局域网内其它机器访问到，需要手动排除docker0这个网络接口，但是这样又导致docker0内的网络无法使用到clash）

**Comment by vichbb** [comment]
> > > ip rule del pref 9001
> > 
> > 
> > 不知道为什么我的移除了也不行，请问centos7需要额外配置cat /etc/resolv.conf吗？
> 
> 我有配置，实际上即使删除了9010那条，后续在使用的过程中还发现其它的问题。 我把系统内核升级到5.4后，运行了也不用再手动删除了。（但是它还是存在其它问题，如宿主机上运行的docker运行的程序的端口无法被局域网内其它机器访问到，需要手动排除docker0这个网络接口，但是这样又导致docker0内的网络无法使用到clash）

额，我就是想docker内的软件走代理，看样子还不行呢，那我先看看老版 clash pre吧，感谢！

**Comment by Xuchengen** [comment]
谁能分析一下如下路由表，为什么数据包最终会查2022表？我认为goto 9010然后nop就结束了，怎么还会查2022表？

```
0:	from all lookup local 
9000:	from all to 198.18.0.0/30 lookup 2022 
9001:	not from all lookup main suppress_prefixlength 0 
9001:	from all goto 9010
9001:	from all iif clash goto 9010
9002:	not from all iif lo lookup 2022 
9002:	from 0.0.0.0 iif lo lookup 2022 
9002:	from 198.18.0.0/30 iif lo lookup 2022 
9010:	from all nop
32766:	from all lookup main 
32767:	from all lookup default
```

**Comment by vichbb** [comment]
> > > > ip rule del pref 9001
> > > 
> > > 
> > > 不知道为什么我的移除了也不行，请问centos7需要额外配置cat /etc/resolv.conf吗？
> > 
> > 
> > 我有配置，实际上即使删除了9010那条，后续在使用的过程中还发现其它的问题。 我把系统内核升级到5.4后，运行了也不用再手动删除了。（但是它还是存在其它问题，如宿主机上运行的docker运行的程序的端口无法被局域网内其它机器访问到，需要手动排除docker0这个网络接口，但是这样又导致docker0内的网络无法使用到clash）
> 
> 额，我就是想docker内的软件走代理，看样子还不行呢，那我先看看老版 clash pre吧，感谢！

mihomo-linux-amd64-compatible-v1.19.8 版本，下面的配置，成功tun 在centos7,docker 内也成功走代理
```yaml
# url 里填写自己的订阅,名称不能重复
proxy-providers:
  provider1:
    url: "订阅Url"
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 300}
    override:
      additional-prefix: "[provider1]"

  provider2:
    url: ""
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 300}
    override:
      additional-prefix: "[provider2]"

proxies: 
  - name: "直连"
    type: direct
    udp: true

mixed-port: 7893
ipv6: true
allow-lan: true
unified-delay: false
tcp-concurrent: true
external-controller: 0.0.0.0:9090
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  device: utun2025
  auto-route: true
  strict-route: true
  # auto-redirect: true
  auto-detect-interface: true

# dns:
#   enable: true
#   ipv6: true
#   enhanced-mode: fake-ip
#   fake-ip-filter:
#     - "*"
#     - "+.lan"
#     - "+.local"
#     - "+.market.xiaomi.com"
#   default-nameserver:
#     - tls://223.5.5.5
#     - tls://223.6.6.6
#   nameserver:
#     - https://doh.pub/dns-query
#     - https://dns.alidns.com/dns-query
dns:
  enable: true
  listen: :1053
  ipv6: true
  # 路由器个人建议使用 redir-host 以最佳兼容性
  # 其他设备可以使用 fake-ip
  enhanced-mode: redir-host
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    - '[2402:4e00::]'
    - '[2400:3200::1]'
  nameserver:
    - 'tls://8.8.4.4#dns'
    - 'tls://1.0.0.1#dns'
    - 'tls://[2001:4860:4860::8844]#dns'
    - 'tls://[2606:4700:4700::1001]#dns'
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    "geosite:!cn,!private": 
      - "tls://dns.google"
      - "tls://cloudflare-dns.com"

proxy-groups:

  - name: 默认
    type: select
    proxies: [自动选择,直连,香港,台湾,日本,新加坡,美国,其它地区,全部节点]

  - name: Google
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: Telegram
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: Twitter
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: 哔哩哔哩
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: 巴哈姆特
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: YouTube
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: NETFLIX
    type: select
    proxies: [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: Spotify
    type: select
    proxies:  [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: Github
    type: select
    proxies:  [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  - name: 国内
    type: select
    proxies:  [直连,默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择]

  - name: 其他
    type: select
    proxies:  [默认,香港,台湾,日本,新加坡,美国,其它地区,全部节点,自动选择,直连]

  #分隔,下面是地区分组
  - name: 香港
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)港|hk|hongkong|hong kong"

  - name: 台湾
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)台|tw|taiwan"

  - name: 日本
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)日|jp|japan"

  - name: 美国
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)美|us|unitedstates|united states"

  - name: 新加坡
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)(新|sg|singapore)"

  - name: 其它地区
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*"

  - name: 全部节点
    type: select
    include-all: true
    exclude-type: direct

  - name: 自动选择
    type: url-test
    include-all: true
    exclude-type: direct
    tolerance: 10

rules:
  - RULE-SET,private_ip,直连,no-resolve
  - RULE-SET,github_domain,Github
  - RULE-SET,twitter_domain,Twitter
  - RULE-SET,youtube_domain,YouTube
  - RULE-SET,google_domain,Google
  - RULE-SET,telegram_domain,Telegram
  - RULE-SET,netflix_domain,NETFLIX
  - RULE-SET,bilibili_domain,哔哩哔哩
  - RULE-SET,bahamut_domain,巴哈姆特
  - RULE-SET,spotify_domain,Spotify
  - RULE-SET,cn_domain,国内
  - RULE-SET,geolocation-!cn,其他

  - RULE-SET,google_ip,Google
  - RULE-SET,netflix_ip,NETFLIX
  - RULE-SET,telegram_ip,Telegram
  - RULE-SET,twitter_ip,Twitter
  - RULE-SET,cn_ip,国内
  - MATCH,其他

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
rule-providers:
  private_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"
  cn_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"
  biliintl_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/biliintl.mrs"
  ehentai_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ehentai.mrs"
  github_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"
  twitter_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs"
  youtube_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"
  google_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"
  telegram_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"
  netflix_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"
  bilibili_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.mrs"
  bahamut_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bahamut.mrs"
  spotify_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs"
  pixiv_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/pixiv.mrs"
  geolocation-!cn:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"

  private_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"
  cn_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"
  google_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"
  netflix_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"
  twitter_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.mrs"
  telegram_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"
```
