### ISSUE TITLE
[Bug] tun 模式会导致 zerotier 链接不稳定

### ISSUE THREAD

**Issue by PeanutMelonSeedBigAlmond** [MetaCubeX/mihomo#984]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

操作系统是 Windows 11 专业工作站 23H2

使用 tun 模式时，发现使用 UDP 协议的软件/游戏会出现延迟很高或者直接超时的情况（如 zerotier ），取消 tun 代理后问题不存在，所以考虑为 tun 导致的问题

1. 以 zerotier 为例，在规则列表中添加 `PROCESS-NAME,zerotier-one_x64.exe,DIRECT` 后，问题存在
2. 以游戏为例，尽管在连接里面看到的游戏 UDP 连接为 DIRECT，问题依旧存在
3. 综上，尽管出站规则为直连，UDP 连接依旧不稳定

所以考虑是UDP流量导致的问题，和出站策略关系不大

### Possible Solution

如题，是否存在一种方式，能让 UDP 流量完全不流经 tun 网卡，类似于 tun 配置里面排除指定 ip 段那样。或者已经存在这种方案？欢迎指正

**Comment by PeanutMelonSeedBigAlmond** [comment]
补一个游戏连接情况的截图

![image](https://github.com/MetaCubeX/mihomo/assets/25266280/c33ac384-7052-4a06-9031-58735981c4e5)

![image](https://github.com/MetaCubeX/mihomo/assets/25266280/01dbc615-a42c-43d9-ae8a-a8d353bf1165)

**Comment by xishang0128** [comment]
@PeanutMelonSeedBigAlmond 不可能的,tun是三层设备,只能认得出ip,认不出tcp/udp这四层的

**Comment by PeanutMelonSeedBigAlmond** [comment]
> @PeanutMelonSeedBigAlmond 不可能的,tun是三层设备,只能认得出ip,认不出tcp/udp这四层的

感谢指正！

那么是否存在其他的可能性，比如，按进程排除流量？就像指定出站规则那样？

**Comment by xishang0128** [comment]
@PeanutMelonSeedBigAlmond 进程有自己的"ip"吗,有就能

**Comment by Skyxim** [comment]
@PeanutMelonSeedBigAlmond https://learn.microsoft.com/en-us/windows/win32/fwp/windows-filtering-platform-start-page

也不是没有，但是没人做

**Comment by gg4924** [comment]
是不是fakeip导致的？使用redir-host模式试试？另外有个建议，windows有个很好用的代理工具proxifier，用它接管全局流量（它直接绕过了udp），指定进程或者域名规则，和clash搭配使用，clash关闭tun，开放个socks5入站接收从proxifier过来的代理流量就行了。

**Comment by PeanutMelonSeedBigAlmond** [comment]
@gg4924 改成了 redir-host 之后似乎没有很明显的改善，这是配置文件，不相关的部分（代理规则，节点列表等）已经略去

若有错误的地方，欢迎指正

<details>
<summary> 配置文件 </summary>

```yaml
mixed-port: 10809
allow-lan: true
mode: rule
log-level: debug
unified-delay: true
tcp-concurrent: true
external-controller: '0.0.0.0:58169'
external-ui: dashboard
secret: 
ipv6: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - https://dns.alidns.com/dns-query
  fallback: []

tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
  inet4-route-exclude-address:
    - 10.0.0.0/24
    - 10.10.0.0/24
  inet6-route-exclude-address: []
  endpoint-independent_nat: true
```
</details>

另外，至于你提到的 proxifier，我看了下，似乎不支持排除指定进程，如果代理全局的话会造成把 mihomo.exe 也一并代理了，引起流量循环
