### ISSUE TITLE
[Bug] fallback 组使用 proxy-providers 时无法自动切换至有效节点

### ISSUE THREAD

**Issue by nonlog** [MetaCubeX/mihomo#998]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

mihomo-alpha-25d6ad2

### What OS are you seeing the problem on?

Windows

### Mihomo config
大致配置如下:
```yaml


u_i: &u_i {url: http://cp.cloudflare.com/generate_204, interval: 30} #url&interval
p_p: &p_p {type: http, interval: 21600, health-check: {enable: true, <<: *u_i}} #proxy-providers
f_b: &f_b {type: fallback, <<: *u_i, lazy: false} #fallback
Sub: &Sub {<<: *f_b, use: [Sub]}

proxy-providers:
  Sub: {<<: *p_p, url: '###'}

proxy-groups:
  - {name: PROXY, type: select, proxies: [test1, 2, 3, 4...]}
  - {name: test1, <<: *Sub, filter: (###)}
  - test2, 3, 4...
```

### Description

在两台电脑上 (win10 和 win11) 使用了 Clash for Windows, Clash Nyanpasu 和 Clash Verge rev 测试, v1.18.0 和前几个 alpha 版本都遇到了这个问题. 上述配置中"test1, 2, 3..." 组都是 fallback 类型, 设置了 interval 为 30, lazy 为 true 也无法自动切换至有效节点. 我也测试了配置中不使用锚点, 问题依旧.

我将机场节点放在 gist 中, proxy-providers 使用 gist 的链接, 通过修改 gist 控制节点是否可用, 多次测试组中第一个节点超时后不会自动切换至下一个节点, 手动进行延迟测试也不会切换. 

大致同样的配置, 将节点写在 proxies 里, 使用自建的节点测试, 手动控制 fallback 组中第一个节点超时, 可以正常切换至有效节点.
