### ISSUE TITLE
[Bug] TUN 模式与 Adguard for window 的 WFP 网卡不兼容

### ISSUE THREAD

**Issue by Maasea** [MetaCubeX/mihomo#999]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta v1.18.0 windows amd64 with go1.21.5 Tue Jan  2 07:30:43 UTC 2024 Use tags: with_gvisor

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  nameserver:
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16

tun:
  enable: true
  stack: mixed # gvisor or system
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true
```

### Description

之前一直使用原版clash，停止更新后更换到Mihomo。
但是在切换过程中出现一个问题，adguard for window 过滤会部分失效。
目前两个解决方法：
1. 关闭 adguard for window 中的 [WFP](https://adguard.com/kb/zh-CN/adguard-for-windows/solving-problems/wfp-driver/) 驱动后可以正常。
2. 保留WFP但是打开 adguard 中高级设置的重定向后正常

方法 2 会使得 Mihomo 中检测到的 PROCESS-NAME 均为 adguard
